### ISSUE TITLE
Directory Format

### ISSUE THREAD

**Issue by danmartinez78** [advplyr/audiobookshelf#1]
I imported a some audiobooks that I manage with both Plex and BookSonic that seem to like the directory structure to be:

author -> series -> year - title

Importing the same library into audiobookshelf treats the year as number of parts, stating that parts are missing.

**Comment by advplyr** [comment]
Thanks for testing it out.
I'm going to work on the scanner now, since it only supports the folder structure I use. I think the best way to ensure accurate scans is to have the user enter their folder structure or select from a list of options.

**Comment by advplyr** [comment]
This is added now. I chose to just auto detect it based on the number of folders.
You'll have to remove each audiobook or delete the `/mnt/user/appdata/config/audiobooks/` folder then scan again.

```
/Title/...
/Author/Title/...
/Author/Series/Title/...

Title can start with the publish year like so:
/1989 - Awesome Book/...
```
