### ISSUE TITLE
ENHANCEMENT: Add a "step arrow" (or something similar) to allow quickly moving to the next book while editing.

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#100]
At least right now, I'm doing a lot of editing to my libraries' books and I am often wanting to quickly step through the edit pages of each one.

I think adding "step arrows" will help with this. (I used the same arrows you used on the home page when there are more books than the shelf has room for)

![image](https://user-images.githubusercontent.com/25695143/137270465-13ce1c44-0846-46d2-8fb4-c284a9ee4aa3.png)

The thought is that they will step through based on whatever the current view is. e.g. next/previous book while looking at the series view, will limit the steps to books in that series' view. Books in a search result will be the only ones stepped through while clicking the arrows. Or the entire library, based on the current sorting.

What do you think?

**Comment by advplyr** [comment]
This was a great suggestion, I added in [v1.4.9](https://github.com/advplyr/audiobookshelf/releases/tag/v1.4.9) and I think it looks and functions really well.
