### ISSUE TITLE
[Question]: Folder Structure for Audiobooks by example "Perry Rhodan Silver Edition"

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1002]
Hello,

how is it best to structure the audiobooks of the series Perry Rhodan Silver Edition from the folders? With Perry Rhodan Silver Edition there are different cycles with again different episodes which are written by different authors (an episode includes the reading of several single books -> therefore also the different authors). If the episodes always had the same author, then it would be clear and one could proceed according to the recommended folder structure. But since it's always different authors, it's a bit difficult. The structure of the audio books is as follows:

- Perry Rhodan Silver Edition
  - Cycle 1
    - Episode 1 (Author1, Author2, Author3)
    - Episode 2 (Author1, Author4, Author5)
    - Episode 3 (Author5, Author6, Author7)
    - Episode 4 (Author1, Author2, Author3)
    - Episode 5 (Author9, Author8, Author6)
    - ....
  - Cycle 2
    - Episode 1 (Author1, Author2, Author3)
    - Episode 2 (Author1, Author4, Author5)
    - Episode 3 (Author5, Author6, Author7)
    - Episode 4 (Author1, Author2, Author3)
    - Episode 5 (Author9, Author8, Author6)
    - ....
  - ...

How do you deal with such structures? You can create hundreds of folders with the respective authors of each episode and then always create "Perry Rhodan Silver Edition" and the respective cycle with the matching episode in these folders. This would tear the whole series apart! Is there not a better possibility?

**Comment by Hallo951** [comment]
I just can't get this to work. My current folder structure is as follows:

![Strucktur](https://user-images.githubusercontent.com/40667862/191935070-99de2a0e-2785-47b3-9818-68e65c7ad632.jpg)

The problem is that it recognizes the individual cycles as individual series but does not integrate them into the audio book "Perry Rhodan Silver Edition" but interprets them as individual series.  It uses "Perry Rhodan Silver Edition" as author and ignores "Multible Authors". But I would like to have it so that he interprets "Perry Rhodan Silber Edition" as the actual audio book and groups the individual cycles with the episodes contained in it.

Can someone help me with my problem?

**Comment by advplyr** [comment]
I'm not sure I entirely understand what you are trying to accomplish but you have to follow the directory structure in the docs. In the case of multiple different authors in a series your best option is to either

a) once the audiobooks are scanned in manually update the authors in abs
b) make sure the meta tags on the audio file are set according to the docs and enable the scanner setting "Prefer audio metadata" which will use the authors & series from the meta tags instead of the folder structure.

**Comment by Hallo951** [comment]
Hello,

The problem with the authors is only one. In case of need, I can live with simply using "several authors" as a placeholder. 

More serious is the problem that I can not combine the individual cycles with the individual episodes as one audio book. For me it is now so that each cycle is interpreted as a single series (which is correct) but I have no way to combine these different series (which are really sub series) in audiobookshelf as one audiobook.

Is there an elegant solution for this?

Translated with www.DeepL.com/Translator (free version)

**Comment by advplyr** [comment]
A book can have multiple series. Your best option is to remove the outer series in your folder structure and just put them each into the sub-series.
Once scanned into abs you will have to edit each book and add the main series "Perry Rhodan Silver Edition" along with the sequence #.
Then in abs you will see that series containing all of the books as well as each sub-series on the series page.

**Comment by advplyr** [comment]
There is no folder structure that supports what you are doing, you need to use the folder structure in the docs and manually adjust the details in abs.

**Comment by Hallo951** [comment]
All right, I'll try to implement it that way. Thank you very much.

Another question: Is it possible in abs to write the retrieved metadata in batches into the tags of all mp3s?

**Comment by advplyr** [comment]
It's not yet possible but that is something planned

**Comment by skyzuma** [comment]
any news about this planned feature?

**Comment by drothmaler** [comment]
you are probably looking for this features: 

* #711 
* #870
