### ISSUE TITLE
Audiobook Scanner- Files using the xHE-AAC Codec cause the library scan process to crash

### ISSUE THREAD

**Issue by SuburbanVampire** [advplyr/audiobookshelf#1004]
Effected Version: Docker 2.1.5 running Debian x64 host

The codec xHE-AAC is a proprietary version of AAC from Fraunhofer. It is protected by patents and has no compatible licensed version that can be used with FFMPEG.

It is like this format will never be supported by FFMPEG. 

Currently, if the audiobook library scanner encounters a file using this codec, the process halts immediately, looks like an unhandled exception.

Steps to reproduce: Place any xHE-AAC media file in a scannable path and let scan run automatically or manually.

Example files here: https://www2.iis.fraunhofer.de/AAC/xhe-aac-abr.html

**Comment by advplyr** [comment]
Fixed in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)

This fix just prevents the crash, the audio file will still be invalid.
