### ISSUE TITLE
[Enhancement]: A way to to cancel an ongoing merging/m4b creation

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#1008]
### Describe the feature/enhancement

![image](https://user-images.githubusercontent.com/42061703/192148681-c18bc56a-06f7-4c8f-9348-f920a39b2a35.png)
Please have a 'cancel' button somewhere to cancel this operation if one changes their mind. I started this about 10m back and
![image](https://user-images.githubusercontent.com/42061703/192148788-58330a59-7b0f-465a-bb79-b5c1650205f4.png)
 the file is still at 38MB, which makes me want to do this operation on the laptop (much more powerful than the RPI that is hosting ABS).

**Comment by advplyr** [comment]
Added in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)

A lot has changed with the m4b merge feature including this cancel button
