### ISSUE TITLE
ENHANCEMENT: Add some kind of feedback when a backup is applied

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#101]
I was testing the restore from backup function and I was left not knowing what to do next. I think some kind of feedback would be super-helpful in informing the user of what to expect.

A progress bar. A timer. A text box telling the user what's going on and/or next steps to take.

Just something.

What do you think?

**Comment by advplyr** [comment]
It should be immediate, then it will refresh everyone logged into your server, and will show you a success message.

Basically all it is doing is extracting that `.audiobookshelf` zip file overwriting your database folders and `/metadata/books` folder. If you opted into storing your book covers in your own directories, then the `/metadata/books` folder is probably empty.

**Comment by Kudjo-Grand** [comment]
This now works correctly.

Great job!

Thank you.
