### ISSUE TITLE
[Enhancement]: Move "remove books with issues" process to backend

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#1013]
### Describe the feature/enhancement

I recently re-shuffled my folders and was left with over 2400 books that had issues and needed to be removed from the library.
![image](https://user-images.githubusercontent.com/42061703/192433704-7d4e88ff-97d4-40e9-96f3-d90f297d4aef.png)

The problem is that when I click the "remove" button and then navigate away from the page, the removing process stops.
![image](https://user-images.githubusercontent.com/42061703/192433786-5b5fbed9-0329-4662-9478-383391d735bb.png)

![image](https://user-images.githubusercontent.com/42061703/192433835-609688df-2e87-4201-bca7-117c0eb28a05.png)

Once the user presses the button, the process should move to the backsend/server so that the user can continue navigating/browsing/listening without worrying about the process stopping.

**Comment by raviwarrier** [comment]
Apparently, it does move to the background. The following screen is that of a log after I navigated away and started a new scan on a newly added library.

![image](https://user-images.githubusercontent.com/42061703/192439728-dafcc879-d2c9-4a56-a6ea-d7316698d930.png)


Am not sure if this is working or not and will leave it to you to close the ticket without resolution (if it is working fine).

**Comment by advplyr** [comment]
This is working. This isn't supposed to be a long running task. I can see how it can be long running with thousands to remove so we may re-design this in the future but for now I think we are okay treating this as a quick action.
