### ISSUE TITLE
[Enhancement]: Show progress while removing books

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#1014]
### Describe the feature/enhancement

![image](https://user-images.githubusercontent.com/42061703/192435031-f847b813-2238-4a64-815e-1e7503667bab.png)

I had over 2400 books to remove. I pressed the button and I see what's shown in the image above. There is no way to know (other than navigate away from the "issues" page and come back to see the count of books that have issues and need removing.

It would be nice that along with the throbber animation, the button also showed remaining books to remove - throbber animation on the left of the button and "xxxx remaining" on the right (or any other method that provides better aesthetics.

I understand that this is not a problem when someone is removing very few files, but it is a problem when someone is removing  any number of books that take more than a minute or so...

**Comment by advplyr** [comment]
I think we established your system was taking very long reading/writing to the db. Even when deleting 2400 books this should be very fast.
I don't think we need a loading indicator here for now.
