### ISSUE TITLE
[Enhancement]: Increase the time the merged book remains in the /metadata/downloads folder

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#1016]
### Describe the feature/enhancement

60 minutes is less when someone gets occupied with other work. At least leave it for 24 hours because someone may just not be able to get to it the same day.

When the m4b is deleted, all the effort and time spent doing that is wasted and the whole process needs to be started again.

**Comment by advplyr** [comment]
In the next release the merge function won't be storing books in that folder anymore. It will be moving the merged m4b into the library item dir and moving the original audio files into a cache dir. #594 mentioned "Merge and Add" feature which is basically what this will become.
