### ISSUE TITLE
BUG: when building an m4b, make both "Cover.jpg" and "cover.jpg" inputs work

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#102]
It looks like the builder is CaSe-SensITivEly looking for "cover.jpg".

So, when I tried to kick off a m4b conversion using the downloader, it failed. Because I had manually added a "Cover.jpg"

I don't even care if the m4b builder renames my file from "Cover" to "cover". As soon as I gave it what it wanted, everything worked perfectly.

What do you think?

**Comment by advplyr** [comment]
This bug turned out to be something completely different. There was an issue setting the correct cover paths when changing between covers. I believed I fixed it in [v1.4.9](https://github.com/advplyr/audiobookshelf/releases/tag/v1.4.9), but if not you can re-open this.
