### ISSUE TITLE
[Enhancement]: Selection range using Shift key

### ISSUE THREAD

**Issue by JakobTischler** [advplyr/audiobookshelf#1020]
### Describe the feature/enhancement

I often need to edit multiple items together. Easy enough when it's only a handful, but the selection process becomes tedious when it's more than that. 

I'd like to propose and selection range feature that uses the Shift key. The last selected item would be the range start, the item selected with the Shift key held would be the end of the range. Anything in between would be selected.

Previously selected items would stay selected (though I see the advantage of deselecting them as well).

Thoughts?

**Comment by advplyr** [comment]
Added in [v2.2.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.2)
