### ISSUE TITLE
[Enhancement]: Creating a self-defined series

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1021]
### Describe the feature/enhancement

It would be a good idea if you could create your own series in series. This would make it possible to manually merge other series that have already been scanned into a self-defined superordinate series. This would also solve the problem with the folder structure for nested series (main series - > subseries - > sub-subseries - > episodes - > individual mp3 files or CDs).

**Comment by advplyr** [comment]
I'm not sure what you mean exactly. You can already create your own series by just added a series onto a book in the details tab.

**Comment by Hallo951** [comment]
You're right, of course, and that's how I do it. What I meant is to create an empty series in which I can group other already existing series. This way you could group different series into one main series regardless of the folder structure.

**Comment by Hallo951** [comment]
Hello, yes, that's exactly what I mean. I would like to bundle different series under one main series. In your example, the main series would be "Foundation Universe" under which various sub-series are grouped.

That would be very good if it were possible, because it would give a much better overview.

**Comment by advplyr** [comment]
I don't see how this could be possible with a folder structure but this is already possible by manually adding another series to those books. Additionally, on the series page you can now collapse the sub-series.
