### ISSUE TITLE
[Bug]: iTunes match authors include & and not splitting correctly

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1022]
### Describe the issue

If I scrape an audiobook and the authors are not separated by a comma but by a & (e.g. Author1 & Author2), it does not recognize the individual authors and interprets the expression as 1 author. If they are separated by a comma the interpretation works correctly. I noticed this especially with the itune scrapper.

### Steps to reproduce the issue

1. scrapping a audiobook with 2 autors ans the itune scrapper

### Audiobookshelf version

current

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Do you have an example book where the author is separated by &?

**Comment by Hallo951** [comment]
Here is an example:

![Screenshot_20221003_213117_com brave browser](https://user-images.githubusercontent.com/40667862/193663406-8d35732a-7847-4dee-83e4-227a378b9b14.jpg)
![Screenshot_20221003_213132_com brave browser](https://user-images.githubusercontent.com/40667862/193663407-ebca675d-469a-430a-a140-9972c2a9e294.jpg)

**Comment by advplyr** [comment]
I don't think Audible or Google books formats their authors this way. With Audible/Google books they give us back an array of authors whereas iTunes gives us back one string with authors.
Were you able to come across this with Google books or Audible?

For iTunes I suppose we could add an additional step to split on the "&". Seems a bit scrappy though.

**Comment by advplyr** [comment]
I ended up just implementing the split on & for iTunes results. We'll see how that goes.

**Comment by Hallo951** [comment]
No, this does not apply in audible and google books. Everything works as it should. I only noticed this because I once did something with itunes and strange authors came out there.

Great, thank you very much. I still have a lot of audiobooks to scrap, so I'm happy to test that then. Can I download the new version somewhere? What is the easiest way to update the server? I use a synology with docker.

**Comment by advplyr** [comment]
This will be in the next server release probably this weekend.

**Comment by advplyr** [comment]
Updated in [v2.2.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.1)
