### ISSUE TITLE
[Enhancement] Sort title field

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#1024]
### Discussed in https://github.com/advplyr/audiobookshelf/discussions/1010

<div type='discussions-op-text'>

<sup>Originally posted by **ch1ma3ra** September 26, 2022</sup>
A number of media management tools allow you to set "sort_$whatever" metadata field in addition to the basic ones (so title and sort_title, artist and sort_artist etc) - allowing you greater control of how stuff is sorted to put it in the order of your choice without having to mangle the "visible" names - for example I would prefer in the main library view to have "The Hobbit" followed by all of the Lord of the Rings books in the correct order but currently they are all scattered across my library according to their actual book titles.

This would also be useful for multiple series of books that are interrelated but shouldn't be combined into a single series, for example Star Wars novels. </div>

**Comment by JakobTischler** [comment]
I fully agree with this and would like to see it. All my audiobooks and podcasts are tagged accordingly.

As far as I know, there are 5 usable tags:

* Sort album
  * ID3v2.3/v2.4: `TSOA`
  * MP4: `soal`
* Sort album artist
  * ID3v2.3/v2.4: `TSO2`
  * MP4: `soaa`
* Sort artist (performer)
  * ID3v2.3/v2.4: `TSOP`
  * MP4: `soar`
* Sort composer
  * ID3v2.3/v2.4: `TSOC`
  * MP4: `soco`
* Sort name (title)
  * ID3v2.3/v2.4: `TSOT`
  * MP4: `sonm`

**Comment by advplyr** [comment]
Making #1074 the primary issue for this
