### ISSUE TITLE
ENHANCEMENT: Allow for multiple Authors. Just like multiple Genres or Tags

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#103]
I just realized that if I try to enter multiple Authors (e.g. "Sunreach" by Brandon Sanderson and Janci Patterson) that it is interpreted as one line "Brandon Sanderson, Janci Patterson" instead of what I was expecting: "Brandon Sanderson" and "Janci Patterson"

This would make filtering and sorting much better.

What do you think?

**Comment by advplyr** [comment]
The author parser splits authors by comma only. With Last, First this may be strange though. I think it would be reasonable to also split by &.

The scanner is correctly parsing authors and multi-authors, but the author filter is still showing multiple authors on a line.

![image](https://user-images.githubusercontent.com/67830747/139500091-7da287da-a465-4b2b-9791-b7da538893f6.png)

We can close this issue once the filter is updated to show one author per line. Also when clicking an author on a book page multi-authors should be clickable separately.

**Comment by advplyr** [comment]
> Last, First or First Last is properly working, thanks!
> 
> Anyway in my case it seems not detecting multiple authors (I'm using "&" as separator), it reads as a single author. I suppose is WIP, otherwise this request should be closed

Can you open a separate issue for splitting authors by "&", just so I can reference it separately.

**Comment by advplyr** [comment]
Multiple authors are now separated in `v1.6.1`. You can click individual author names to filter by them. The global search and the filter menus will show 1 author per line.

![image](https://user-images.githubusercontent.com/67830747/139604370-a1eaf1bf-a782-4bc3-9e22-4d2d68296626.png)
