### ISSUE TITLE
[Bug]: Cant read ebooks with # in filename

### ISSUE THREAD

**Issue by pto199** [advplyr/audiobookshelf#1039]
### Describe the issue

ebooks that contain a # in the filename are unable to open and just stay at 0%

### Steps to reproduce the issue

The error I get in console is"

Error: ENOENT: no such file or directory, stat '/ebooks/Michael Crichton/Jurassic Park/META-INF/container.xml'

Im not sure what that /META-INF/container.xml refers too.  The path is /ebooks/Michael Crichton/Jurassic Park/Jurassic Park (Jurassic Park #1)/Jurassic Park (Jurassic Park #1) ().epub

I'm going through all my books and it seems any of them that have a # in the filename display this error and dont work.  

### Audiobookshelf version

v2.2.0 docker

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.1)
