### ISSUE TITLE
[Enhancement]: Book summary or description lookup feature in details section

### ISSUE THREAD

**Issue by yegods** [advplyr/audiobookshelf#1048]
### Describe the feature/enhancement

I would like to see a way to fill in the book description data either manually or automatically when scanning... much like the author data is filled in from the author page.  This description should be displayed on the books detail page.

I do realize there is the "desc.txt" feature when scanning, but since there is no way to automatically generate those files, it's value is not so great.  Plus, the description isn't shown on the details page AFAIK.

**Comment by advplyr** [comment]
Scanning will pull in description from meta tags also. If you want to pull in a description from some external source that is separate in audiobookshelf. 
Many other servers put the external metadata fetching together with regular scans but that is not how abs does things (yet at least). There are many ways in abs to lookup external metadata. You can use the "Match Books" button in the library table which will quick match every book with the external provider you selected when setting up the library. You can individually quick match each item, or manually match using different providers in the Match tab.

I'll close this as I believe this is a misunderstanding of the software, but let me know.

**Comment by yegods** [comment]
Ok... i see the quick match button will do what I ask, but is there a way to run this across a whole library?
