### ISSUE TITLE
[Bug]: Author page showing audiobooks from another library

### ISSUE THREAD

**Issue by rpaech** [advplyr/audiobookshelf#1049]
### Describe the issue

Each audiobook thumbnail is currently appearing twice when viewed from the author view (see first screenshot below).  The audiobook thumbnails appear to represent seperate records, which causes odd behaviour if the wrong thumbnail is selected.  This only occurs from the author view and doesn't occur in the library, series and search views.

The following illustrates the issue and some associated behaviour...

1. When I navigate to the Authors page, the thumbnail for _Graham McNeill_ indicates that he has 7 books, which is correct.  
2. If I navigate to the author page for _Graham McNeill_ (see Figure 1 below), it now indicates that he has 14 books, each book cover appearing twice, although not necessarily in order.
3. If I navigate to the first entry for _False Gods_, under _The Horus Heresy (Warhammer 40K) Series_, the audiobook page mostly looks normal, except the commands in the top bar for the library selector, search bar and stats button are missing (see Figure 2).  Playback works fine, but if I try to navigate away using the commands in the side bar, I will get an error like `Oops... Library "lib_kyjty7zdnwvl46u7dj" not found`.
4. Alternatively, if I navigate to the second entry for _False Gods_, the audiobook page is complete and the commands in the top bar are visible (see Figure 3).  Playback works fine and navigation using the commands in the side bar also work.

I have tried a range of approaches to correct the issue, including:
1. Run the Force Re-Scan command from the Library page. Doesn't fix the issue at all.
2. Run the Remove all Library Items command in the Settings page, followed by the Scan command from the Library page. Temporarily addresses the issue, although it reoccurs shortly afterwards.
3. Delete and recreate library from the Library page.  Temporarily addresses the issue, although it reoccurs shortly afterwards.

**Figure 1** (`https://.../author/aut_esvl3huhtcc0xh3hlk`)
![image](https://user-images.githubusercontent.com/7410661/194222050-a3bfd3d9-0788-4cca-b1de-ca2bb2733aa7.png)

**Figure 2** (`https://.../item/li_z1ccm8cktjc2ei7dvl`)
![image](https://user-images.githubusercontent.com/7410661/194225043-621c9182-73fd-4916-9a8a-88865d234235.png)

**Figure 3** (`https://.../item/li_eqc7wbsb51bapjfzzr`)
![image](https://user-images.githubusercontent.com/7410661/194225162-4ccb9e88-befe-4184-b54d-3164ed48820e.png)

If I can provide any other information to help figure this out, let me know.

### Steps to reproduce the issue

See description above.

### Audiobookshelf version

v2.2.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Do you have multiple libraries setup and have the same book/author in both libraries?

**Comment by rpaech** [comment]
No, there's just one library at the moment, which holds all my audiobooks.  

Could deleting a library and recreating it, with the same name, leave some remnant that causes the problem?

**Comment by advplyr** [comment]
I think the bug is the authors page is showing items that belong to another library so it would make sense if you had another library at some point with those items in it.
A second bug could be that you deleted the library and it didn't delete the library items.

**Comment by advplyr** [comment]
Library items are specific to libraries but authors are separate entities that could belong to library items in any library.
The authors page should only be showing library items that are in the library you are viewing.

**Comment by advplyr** [comment]
Fixed in [v2.2.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.1)
