### ISSUE TITLE
ENHANCEMENT: Change the appearance of the marked as read button on the book details page.

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#105]
I think if this button changed it's color to give the user some feedback, it would help in identifying books that have been marked as read. I used a color from the logo.

Super simple.

![image](https://user-images.githubusercontent.com/25695143/137303162-258ae358-a27b-4995-be38-1cdfeda21373.png)

What do you think?

**Comment by advplyr** [comment]
I tried out green for [v1.4.9](https://github.com/advplyr/audiobookshelf/releases/tag/v1.4.9)

![image](https://user-images.githubusercontent.com/67830747/137568641-3305c4ab-0166-486c-8877-d0cd4956872f.png)

Let me know what you think
