### ISSUE TITLE
[Bug]: Podcasts not downloading

### ISSUE THREAD

**Issue by lakoliu** [advplyr/audiobookshelf#1050]
### Describe the issue

Recently (within the last 2 weeks), I have not longer been able to download any podcasts. When I search for a recent episode, it finds it and says "Downloading..." but it never downloads. If I do it again, or try to download a different episode on a different podcast, it says the episode has been added to the download queue, but it never downloads. I've gone so far as erasing all my Audiobookshelf data and re-configuring the whole thing, but it that still didn't fix the issue. (I'm running it in Docker on NixOS.)

### Steps to reproduce the issue

1. On a podcast, click Edit > Episodes > [set the date] > Check & Download New Episodes
2. Episode is found and says either Downloading or Added to Queue, but it is never downloaded.

### Audiobookshelf version

v2.2.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Are you seeing any errors or messaging in the docker logs?

**Comment by lakoliu** [comment]
No error in the logs, but looking further into it I believe I've found the issue. The MP3 is in the Podcasts folder on the drive, but it isn't showing up in Audiobookshelf, so I guess it just isn't re-syncing after downloading.

**Comment by advplyr** [comment]
Make sure the disable watcher setting isn't enabled both globally and in the podcast library settings. If you have debug logs on you can see if the watcher is getting fired at all when a file is added to your library.

**Comment by lakoliu** [comment]
The "Disable Watcher" setting is off (I can only find one setting, so I believe it is global). In the logs I see the watcher is filing when I add a new podcast (it recognizes the cover image has been added), but not when I download an episode.

`2022-10-07 09:13:45 DEBUG [Watcher] File Added /podcasts/Under the Radar/cover.jpg`

`2022-10-07 09:13:45 DEBUG [Watcher] Modified file in library "Podcasts" and folder "fol_knhip4ustiwa7wwdc0" with relPath "/Under the Radar/cover.jpg"`

Also, now, after downloading the one episode, when I try to download an episode of another podcast it just says "download added to queue" and never downloads. In the log it says "starting download", but the download never seems to happen.

**Comment by advplyr** [comment]
You should actually see logs saying the Watcher is ignoring the podcast directory first. Then it should show a log saying it is downlaoding the file.

```
[2022-10-08 16:36:16] DEBUG: [Watcher] Ignoring directory "/media/podcasts/Syntax"
[2022-10-08 16:36:16] DEBUG: [fileUtils] Downloading file to /media/podcasts/Syntax/Supper Club × ORMs with Nikolas Burke from Prisma.mp3
```

**Comment by lakoliu** [comment]
That doesn't seem to be happening. I only get

`2022-10-08 21:48:35 INFO [PodcastManager] Found 1 new episodes for podcast "Under the Radar" - starting download`

but it never downloads. And it continues adding the download to the queue, even if I've cleared the queue. It said "1 Episode queued for download", I pushed the X on that and agreed to clear the queue, tried the download again, and now it says "2 Episodes queued for download", but nothing downloads.

**Comment by advplyr** [comment]
I think the download is getting stuck and there was no timeout being set so I added a 30 second timeout. I'll put that in the next release but it wouldn't solve your issue. I'm thinking your issue is with all outgoing requests from your docker.

When you press the search button to lookup podcast episodes are you able to see the episodes?

**Comment by lakoliu** [comment]
Cool! Thank you, hopefully that helps. 

Yes, when I press the search button a list of all available episodes comes up.

**Comment by advplyr** [comment]
Added the timeout in [v2.2.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.1)

**Comment by lakoliu** [comment]
Unfortunately, I'm still unable to download a second podcast episode. I was now able to successfully download one episode, and it automatically showed up in the list, but then I went to download an episode from another podcast and it got stuck on "Downloading" again. I'm not sure what else to try.

**Comment by lakoliu** [comment]
I believe I found the problem. My server (a laptop) had a semi-faulty ethernet adapter. Every 15 seconds or so the connection would drop for a second. It seems this was enough to cause this issue. I replaced the adapter and everything is working perfectly. Thank you for your help!
