### ISSUE TITLE
[Bug]: Chapter metadata write bug

### ISSUE THREAD

**Issue by garlik82** [advplyr/audiobookshelf#1052]
### Describe the issue

Weird chapter bug when embedding metadata after chapter editing.

After editing: 
<img width="784" alt="Captura de ecrã 2022-10-08, às 22 45 07" src="https://user-images.githubusercontent.com/5408803/194728997-4410256c-d112-4ca3-9453-02f14693936e.png">

After embedding and rescan:
<img width="789" alt="Captura de ecrã 2022-10-08, às 22 46 05" src="https://user-images.githubusercontent.com/5408803/194729009-a1a1a346-33f3-47c4-8975-9d894443d855.png">

### Steps to reproduce the issue

1. Edit chapters
2. Embed metadata
3. Rescan audiobook folder.

Nothing relevant shows in the logs.

### Audiobookshelf version

v2.2.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not sure why the chapter title would be blank but when testing this I found other issues with multi-track audiobooks. Can you try testing again with v2.2.1?
And noting if you are using m4b/mp3 and single track or multi track.

**Comment by garlik82** [comment]
All m4b files.

**Comment by garlik82** [comment]
Still happening.
<img width="829" alt="Captura de ecrã 2022-10-09, às 06 18 30" src="https://user-images.githubusercontent.com/5408803/194739397-179ab8eb-4c2a-4ea2-8168-c25c9d16c3a6.png">

Chapter titles get deleted and that chapters timing gets reset to the original value.

**Comment by garlik82** [comment]
I think this happens when using Shift Times with negative numbers. Edited One book in three different ways, manually syncing the chapters, add 1 second with shift time to every chapter and finally subtracting 1 second to every chapter with shift time, and this only happened when subtracting seconds. Will test further after my laptop has charged.

**Comment by garlik82** [comment]
After dumping the chapter info with tone, I concluded that the chapters are correct, the issue lies with metadata.abs not grabbing the chapters correctly.

tone dump:
<img width="491" alt="Captura de ecrã 2022-10-09, às 12 27 02" src="https://user-images.githubusercontent.com/5408803/194754460-d9b3d090-1ef9-405e-a7f6-de77f2e2cac9.png">

metadata.abs:
<img width="347" alt="Captura de ecrã 2022-10-09, às 12 29 05" src="https://user-images.githubusercontent.com/5408803/194754472-4b24a1da-3245-4df1-a0ec-9fd880e6216a.png">

**Comment by garlik82** [comment]
Been embedding metadata and I can’t reproduce this anymore.  I noticed that Apple Books can only see the chapters metadata after I run tone -tag —meta-chapters-file manually, but that is probably another issue. If you can’t reproduce this we can probably assume some bad m4b file was causing my issue. I redownload the books that were misbehaving and everything went according to plan.

**Comment by advplyr** [comment]
I wasn't able to reproduce it, hopefully just a bad file like you said. Thanks for following up.
