### ISSUE TITLE
[Bug]: after updating to v2.2.1 we cannot delete metadata anymore (x for deletion is missing)

### ISSUE THREAD

**Issue by Gunsi1973** [advplyr/audiobookshelf#1055]
### Describe the issue

After the update to v2.2.1 you cannot delete metadata anymore. It is possible to add metadata (eg. genre, narrator etc.) but not to delete anything. The mouse over (x) is missing. Confirmed in the discord with other users. 

### Steps to reproduce the issue

1. Updated to v2.2.1
2. Tried to change metadata - adding works, no option to delete anymore
3. Docker environment
4. checked file rights to metadata.abs
5. Update: community found out that if you click where the (x) is supposed to be you can delete entries

<img width="148" alt="image" src="https://user-images.githubusercontent.com/58533617/195203877-c7e416aa-e9aa-4b8a-8d4b-1d9ca19d6480.png">

### Audiobookshelf version

v2.2.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.2)
