### ISSUE TITLE
[Enhancement]: 4 suggestions for improvement for your Client and server 

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1056]
### Describe the feature/enhancement

Hello, I have 4 suggestions for improvement for your client but also for the server view.

1. in the series view it would be very nice if there was a marker for completely listened series. So that you can see at first glance which series has already been listened to completely and which not without having to look into the series every time. It can be used yes the same kind of marking, which one also uses with the individual audio books. This would definitely increase the user-friendliness. 

2. in the client there is currently no button with which you can mark a complete series as listened to. It would be nice if there would be one like on the server. 

3. for the clarity it would be good if you had a few filter options for the series similar to those in the library. Basically, I want to be able to hide series that have already been completely listened to. The current filter options only apply to the library but not to the series. 

4. in the client, it would be nice if you could display individual audiobooks grouped as series in the Library view, as is also the case with the server.

**Comment by advplyr** [comment]
For the first one this is already implemented in the web app. I didn't realize it wasn't also in the mobile app.

The last 2 there are open requests for.

**Comment by Hallo951** [comment]
All clear. Thank you for creating the themes in Audiobookshelf mobile app.
