### ISSUE TITLE
[Enhancement]: allow guests only to see/upload to specific subfolders

### ISSUE THREAD

**Issue by felixbro** [advplyr/audiobookshelf#1058]
### Describe the feature/enhancement

Can you bring in the feature that allows certain users, preferably guests, to only upload **and/or** see certain subfolders?

![guest settings](https://user-images.githubusercontent.com/64419976/195375275-5b179a36-e2ec-4756-952f-825f53bf5b62.jpg)

you could choose that guests can see the main folder including subfolders, but can only upload to the subfolder `upload`.
i created a few subfolders to avoid messing around with their unstructured file and folder naming in my organized main folder
in my case `/{mainfolder}/upload`

![library settings](https://user-images.githubusercontent.com/64419976/195376120-af8d5632-33bf-41ef-8527-de4a1ef197a9.jpg)

**Comment by advplyr** [comment]
Having a subfolder listed there will cause problems with abs scanner. The scanner scans every folder inside a library folder no matter how deeply nested, so this is going to cause some duplicates that may lead to other issues.

**Comment by advplyr** [comment]
Restricting users to folders in a library is not planned
