### ISSUE TITLE
[Bug]: Embed Metadata function removes first second from the audio

### ISSUE THREAD

**Issue by SkippyTheMonkeyKeeper** [advplyr/audiobookshelf#1059]
### Describe the issue

Okay I got a new audiobook from Audible in .m4b format with some bad metadata and decided to rewrite it using the Embed Metadata function in audiobookshelf. When I started the audiobook it started with "is audible" instead of "This is audible". I downloaded the audiobook with the new metadata and played it in a few other players, but all gave the same result. I also confirmed that the original file indeed starts with "This is audible". 

I used the Embed Metadata function on some other audiobooks, but not all audiobooks are missing the first second after rewriting the .m4b metadata. I also checked some audiobooks I used this function on when running v2.2.0 and some of those are missing the first second as well.

The weird thing is that when scanning both audiobook files with MediaInfo it returns the exact same duration for the audiotrack. 

I am not sure what to make of this. 

### Steps to reproduce the issue

1. Open the Management Tools screen for an audiobook
2. Run the Metadata Embed function
3. Listen to the new audiobook file

### Audiobookshelf version

v2.2.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Are you still having this issue? I think tone was updated since you brought this up.
