### ISSUE TITLE
ENHANCEMENT: Add a user-specific "Logbook" area.

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#106]
This one is related to other enhancement suggestions I made regarding user notes, start, and finish dates.

The idea here is it is a common place for all user created/specific data can live.

Read dates history, and user-generated notes, a "completed" bookshelf section. These are just a few ideas of what could exist in this area. 

This would also give a flexible place for future development to occur. I saw another user suggest user metrics. If something like that got added. This area could easily be a place where root and non-root users can view that kind of data.

It could be super-bare bones for now. But, then you and your users could flesh it out over time.

![image](https://user-images.githubusercontent.com/25695143/137306478-a1ea575d-0fb0-4730-baff-4b0e107da2af.png)

[Here is a link to the image I used for the icon](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F8%2F8f%2FQuill_and_ink_transparent.svg%2F1024px-Quill_and_ink_transparent.svg.png&f=1&nofb=1) there. I just changed it to the same color as the other icons. [](url)

Maybe the area could look something like this.
![image](https://user-images.githubusercontent.com/25695143/137312252-d74101b3-c480-403a-8714-f71cb924aaf6.png)

What do you think?

**Comment by advplyr** [comment]
It seems a lot of this is added now except for the notes. With all the updates in the last few months I think we need to revisit how this would be implemented and if it is still wanted.
