### ISSUE TITLE
[Enhancement]: Show green line for completely listened collapsed series

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1062]
### Describe the issue

Hi, I have another small problem. If you group audio books into series in the library view, no green line is displayed when they have been listened to completely. When you are in the series view, the green line is displayed correctly for series that have been listened to in full.

### Steps to reproduce the issue

Collapse a series that is 100% heard in the library view. Normally, a small line should indicate that the series has been heard completely. Unfortunately, this is not the case. No green line is displayed.

### Audiobookshelf version

2.2.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Added in [v2.2.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.2)
