### ISSUE TITLE
[Bug]: Linebreak in descriptions ignored

### ISSUE THREAD

**Issue by Thomas-Magnum** [advplyr/audiobookshelf#1069]
### Describe the issue

Linebreaks ("\n") embedded in texts, e.g. description for audiobooks or authors are ignored when the text shows up on both the webfrontend and the respective app on the smartphone.
Long texts are therefore difficult to read, as no breaks or paragraphs are shown.

### Steps to reproduce the issue

1. Copy/past text into audiobook description (does also apply for text already embedded in mp3tags)
2. open book in webfrontend or app
3. no linebreaks are shown

### Audiobookshelf version

v2.2.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not able to reproduce this. How are you embedding meta tags into your audio files?
If you are manually updating the details in abs copy pasting text with line breaks will work. Line breaks worked when I put them in through the windows file system. Mp3tag doesn't appear to allow line breaks at all so I couldn't test with that.
