### ISSUE TITLE
[Enhancement]: Chapter Lookup: add alert when number of chapters is different from existing file

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf#1070]
### Describe the feature/enhancement

Thank you so much for adding #991.

I would like to request an additional alert when looking up chapters. I have a couple books that have consolidated the first several small credits chapters (Opening credits/Dedication/Epigraph in the example looked up chapters) into one chapter (Intro & Epigraphs). Since the chapter marks are off by a couple seconds through out the book I can't just over write everything. I thought I could manually add a couple dummy chapters in the right places to get the titles to line up to the right chapters. But I didn't notice the number of chapters was off when I first encountered a book like this.

If you could add another alert message like the one below, but have it notify the user that the number of chapters doesn't match. That would be a great help. 

![image](https://user-images.githubusercontent.com/991618/196014064-e339015e-5a6c-4d76-9981-56c665d92c0b.png)

Thanks again.

**Comment by advplyr** [comment]
Rather then another alert I put it like this:

![image](https://user-images.githubusercontent.com/67830747/199614244-3ab08cbd-01e8-4de9-89ce-4563e22a16bd.png)

The numbers turn orange when they are mismatched.

**Comment by SenorSmartyPants** [comment]
That's cool. Any kind of visual notification is what I was after. 

Thanks.

**Comment by advplyr** [comment]
Updated in [v2.2.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.2)
