### ISSUE TITLE
[Bug]: Improper parsing of Atom feed: no podcast episodes found

### ISSUE THREAD

**Issue by dgliwka** [advplyr/audiobookshelf#1072]
### Describe the issue

Audiobookshelf is unable to parse episodes from the feed "https://audycje.tokfm.pl/rss-feed/334,8-10-Podcast-Gazety-Wyborczej".
This is atom feed and it's used by Apple podcasts and Google podcasts, which are able to parse the list of episodes out of it. Popular RSS readers such as NewsBlur are also able to get episodes list and audio files.

### Steps to reproduce the issue

1. Add feed "https://audycje.tokfm.pl/rss-feed/334,8-10-Podcast-Gazety-Wyborczej".
2. Try to download past episodes.
3. No episodes are found.

### Audiobookshelf version

v.2.2.1

### How are you running audiobookshelf?

Docker

**Comment by dgliwka** [comment]
Thank you so much for fixing. It works flawlessly on :edge version now.

Thank you for developing audiobookshelf. I'm using it daily 🙂

**Comment by advplyr** [comment]
Fixed in [v2.2.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.2)
