### ISSUE TITLE
[Enhancement]: Playlist/Play Cue Feature

### ISSUE THREAD

**Issue by dmuiX** [advplyr/audiobookshelf#1077]
### Describe the feature/enhancement

I imagine it like this:
I have an audiobook running. E.g. a short one that just goes one hour or so. After ending it I want to run another audiobook. So I would like to add it to a playlist/play cue and the app just continues to run audiobooks from the cue. 
Every streaming service is supporting this feature. I think audible also does not have this feature so far.
Woule be amazing to see it implemented :)

**Comment by advplyr** [comment]
Added a player queue for audiobooks. This was already there for podcast episodes but you couldn't add more episodes to the queue.
This is in [v2.2.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.3)

There is a lot more to do with this. A playlist is going to be different then a queue. A playlist will be basically be a queue that is saved and is specific to a user.
Once the queue feature is stable we can add playlists and implement this in the mobile apps.

**Comment by barelylit** [comment]
Not sure if I'm missing something, how do we add items to the play queue ?

**Comment by advplyr** [comment]
You have to first play an audiobook then you'll see it on the audiobook landing page next to the play button. Or in the menu dropdown on the library/home page.

**Comment by advplyr** [comment]
Playlists added in [v2.2.6](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.6)

Web app only still
