### ISSUE TITLE
[Enhancement]: Add support for webm & webma files.

### ISSUE THREAD

**Issue by kondzik** [advplyr/audiobookshelf#1079]
### Describe the feature/enhancement

It would be nice to have support for streaming audio from webm files.

**Comment by advplyr** [comment]
I'm not sure if `.webma` is actually used or not but this came up in searches as the audio only version of webm so I added support for that also. Will be in the next release

**Comment by advplyr** [comment]
Added in [v2.2.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.2)
