### ISSUE TITLE
[Enhancement]: User interface for tag/genre navigation

### ISSUE THREAD

**Issue by wtanksleyjr** [advplyr/audiobookshelf#1080]
### Describe the feature/enhancement

I'd like to be able to find and view tags, genres, and other structured properties of books, that right now cannot be found apart from clicking through tiny text in the Library view filter or clicking on a book that you already know has those tags/genres/etc.

One way to provide this would be to make a "expanded" user interface for the Library's Filter box. Right now it's very hard to use, since it has deeply nested dropdown menus with very many entries and no way to use accelerators. If there were a little "expand" menu entry at the top of that menu, it could appear as a pinned part of the Library pane, allowing more mouse exploration and also (optionally) providing room for a text box to allow the user to reduce the number of items displayed inside all of the choice boxes at once (so if I type "Heinl" in the search box, I'll quickly see the Series, Genre, and Tag selection boxes empty, and the Author box contain three entries, "Robert A. Heinlein", "Robert Heinlein", and "Virginia Heinlein", which I can easily single or multiple-select).

I was thinking of some other ways to do this as well, but let's stop and see if this is a good idea for a feature first.

**Comment by advplyr** [comment]
I think this was opened before the manage tags/genres page was adding in config. There are a few requests open for improving filtering/sorting that I've been going through. This can be merged with https://github.com/advplyr/audiobookshelf/issues/1673
