### ISSUE TITLE
[Enhancement]: Option to display accompanying PDF / Files for audiobooks

### ISSUE THREAD

**Issue by st0r4ge** [advplyr/audiobookshelf#1081]
### Describe the feature/enhancement

Hi,

i have a few audiobooks with an accompanying PDF file. For example a lot of science audiobooks come with such a file to allow the listener to look at graphs or illustrations. 

I'd love to have a feature that detects if there is a pdf file within an audiobook folder and offers the user to download/read the file. It already does show in the "file" drop-down for download, but this only applies to the web-player, and involes a lot of searching if there are many audio-tracks to a book.

When using the android/ios client there is also no way to access this file (i guess opening the web-interface would work).

Maybe it's possible to put a button for this action here:
![image](https://user-images.githubusercontent.com/69420383/197286166-4457005d-fa7d-4984-be47-c51ab61ec3c8.png)

Example of the pdf in the file-download drop-down:
![image](https://user-images.githubusercontent.com/69420383/197286322-a74db66c-f9fa-4a4d-83b8-317b5ce9c233.png)

Definitely not a high priority but i think this would be a nice usability addition in the future.

**Comment by advplyr** [comment]
The e-reader is currently experimental so if you turn on experimental features you should see a "Read" button when there is a pdf.

![image](https://user-images.githubusercontent.com/67830747/197291824-dd5b6a0e-0fcb-4bad-9e5c-79869e2f502f.png)

Currently this only supports one ebook file per book.

**Comment by st0r4ge** [comment]
@advplyr works perfectly - thank you 👍
