### ISSUE TITLE
Chapters Lookup where Audiobook duration is less than 1 hour

### ISSUE THREAD

**Issue by grehund** [advplyr/audiobookshelf#1082]
ABS Chapter lookup doesn't handle audiobook durations less than 1 hour, as it reads the timestamps as Hours instead of Minutes.
![abs_chapters_books_ 1hr](https://user-images.githubusercontent.com/22899854/197311129-e78bfbd7-e8fa-412c-a1d5-79a740d7dc2a.png)

**Comment by advplyr** [comment]
When you play that audiobook is it showing the correct duration in the audio player?

**Comment by grehund** [comment]
Yes, it plays fine, tracks fine. Seems to just be an issue in the Chapters Lookup.

**Comment by advplyr** [comment]
I'm not able to reproduce this. When you look at the audio tracks list are the durations shown there correct?

![image](https://user-images.githubusercontent.com/67830747/197340244-9ea4c20b-50f2-44d9-b0d0-cc32335cf609.png)

**Comment by grehund** [comment]
It is only one file; yes it shows the correct duration15:27 (15min, 27sec). Maybe the issue is in the data the Chapters Lookup is pulling then? I'm not sure how you're doing that or what the source is.

**Comment by advplyr** [comment]
The duration of this book according to Audible is 15 hrs and 26 mins. You are saying that your audio file is only 15 min and 27 seconds.
I don't think I understand what you are saying. To me it sounds like you have a bad copy of the audiobook that is only 15 mins.

**Comment by grehund** [comment]
Ok, maybe I have been misled. I will do some more research. Sorry to mess you around. Keep up the great work, I'm loving the project.

**Comment by grehund** [comment]
Turns out it's a Blinkist Summary of the original book, hence the confusion.
