### ISSUE TITLE
[Enhancement]: Write directly to ID3 Tags instead of metadata.abs

### ISSUE THREAD

**Issue by dmuiX** [advplyr/audiobookshelf#1083]
### Describe the feature/enhancement

Would be nice if the editor could write directly to the id3 tags instead of creating/editing the metadata.abs file.
Therefore I am currently using mp3tag to edit my files. But its way more comfortable to work with the integrated editor. But I don't want to have the additional file. I want everything inside my audiobook files.

**Comment by advplyr** [comment]
There is an embed metadata page already. In the Manage tab
