### ISSUE TITLE
[Enhancement]: manual cover for series (when collapsed) in Library view

### ISSUE THREAD

**Issue by Manantra** [advplyr/audiobookshelf#1086]
### Describe the feature/enhancement

I would like to add an option to custom covers for series and not always pick the cover for the first entry. Most known series have series covers available on the internet. Would be cool to use them.

for example:

Now: 
![grafik](https://user-images.githubusercontent.com/113709296/197410611-7510db9a-6ac8-4a5b-b574-2da476d6a56d.png)

Change to: 
![grafik](https://user-images.githubusercontent.com/113709296/197410638-b7282dbb-69c6-411d-8c53-63340b2c7dbe.png)
![grafik](https://user-images.githubusercontent.com/113709296/197410678-81038e34-9cac-464b-9c67-6363d409b2d4.png)

**Comment by advplyr** [comment]
That cover is only used when collapsing series.
I'm not sure how this would work with the series page which is double the width of a cover.

**Comment by advplyr** [comment]
This is not going to be supported for the library page as of now.
