### ISSUE TITLE
Incorrect permisson on audiobookshelf systemd service

### ISSUE THREAD

**Issue by derkington** [advplyr/audiobookshelf#1087]
### Describe the issue

Warning in system log:  

Oct 24 11:20:17  systemd[1]: Configuration file /lib/systemd/system/audiobookshelf.service is marked executable. Please remove executable permission bits. Proceeding anyway.

At install time permissions for service file are set:  **-rwxrwxr-x**  1 root root   423 Oct  9 00:11  audiobookshelf.service

Should be as follows :  **-rw-r--r--** 1 root root 423 Oct  9 00:11 audiobookshelf.service

### Steps to reproduce the issue

Installed on a Ubuntu 22.04.1 LTS,  using debian package (Not PPA method). Each time the service is started error in log is generated. 

### Audiobookshelf version

v2.2.1

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
I'm not understanding why this is an issue on your system. Do you have something configured that is enforcing some permission bits?

**Comment by derkington** [comment]
I have no idea, its a plain install of Ubuntu, nothing special.  There are no security tools, permissions manager or any permissions  changed or set on the file system that should do this.   If this is not a general problem then I guess this issues can be closed, if I  ever have to do a fresh install and encounter this again then I will  flag it.

**Comment by advplyr** [comment]
I haven't seen this mentioned before and don't have issues with the debian package on my Ubuntu server. It may be an issue though so let me know if  you gather more data.
