### ISSUE TITLE
e-reader support for cbr,cbz

### ISSUE THREAD

**Issue by binarygeek119** [advplyr/audiobookshelf#109]
i would like to have e-reader support for cbr,cbz

i believe for what i read is that cbr,cbz are just zipped folders with jpegs in it.

**Comment by advplyr** [comment]
You were right, it is just a zip, rar or tar file with images. I build a very basic comic reader with support for `cbr` and `cbz` files.

I only tested with 2 `cbr` files and they both loaded fine, although a bit slower then I would like.

![image](https://user-images.githubusercontent.com/67830747/137606680-79d1fb0c-d599-46ff-a83f-0c71cfe40863.png)

![image](https://user-images.githubusercontent.com/67830747/137606704-544e5f12-e22b-47dd-86e7-b929a14687db.png)

I didn't create an official release yet, but if you want to update and try out a few and let me know how they load that would be great.
