### ISSUE TITLE
[Bug]: Progress gets lost

### ISSUE THREAD

**Issue by ohare93** [advplyr/audiobookshelf#1090]
### Describe the issue

Listening to a book on the iOS app and I lost my progress back to the start of the latest file. The book is: a series of 36 mp3s, average of 140mb each; 37 hours long; locally downloaded. I am running the server on Unraid in Docker.

I get the following error in Docker logs when I open the iOS app:

```
today at 6:19:59 PM[2022-10-25 18:19:59] ERROR: [MeController] syncLocalMediaProgress invalid local media progress object no library item {
today at 6:19:59 PM  id: 'local_B5351EE2-0EB5-4F66-B400-7D351D7024D1',
today at 6:19:59 PM  lastUpdate: 1666714769814.36,
today at 6:19:59 PM  episodeId: null,
today at 6:19:59 PM  isFinished: false,
today at 6:19:59 PM  localLibraryItemId: 'local_B5351EE2-0EB5-4F66-B400-7D351D7024D1',
today at 6:19:59 PM  serverUserId: 'root',
today at 6:19:59 PM  progress: 0.23391476250926585,
today at 6:19:59 PM  serverAddress: '[REDACTED]',
today at 6:19:59 PM  currentTime: 8231.593776631,
today at 6:19:59 PM  startedAt: 1664094786784,
today at 6:19:59 PM  localEpisodeId: null,
today at 6:19:59 PM  serverConnectionConfigId: '[REDACTED? idk]',
today at 6:19:59 PM  duration: 35190.569797000004,
today at 6:19:59 PM  finishedAt: null,
today at 6:19:59 PM  libraryItemId: 'li_3g8wlmwhqb7gxcmpes'
today at 6:19:59 PM}
```

My progress was only lost upon hitting play on another book and then returning to the original book. A restart may have been involved in there somewhere too.

### Steps to reproduce the issue

1. Locally download a file on iOS app
2. Start playing file
3. Restart app. File should still be in progress
4. Open logs to find error?
5. Play another book
6. Play original book again. Progress should be lost.

### Audiobookshelf version

v2.2.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
It looks like the library item associated with that media progress object no longer exists.
You can check if it exists by going to a library item page on the website and updating the URL with this library item id `li_3g8wlmwhqb7gxcmpes`

**Comment by ohare93** [comment]
You seem to be correct. It takes me back to the main library page. Also the book in question has a different url `li_itg5oyabyy5qi9nmrx`.

What should I do about this?

**Comment by advplyr** [comment]
Right now the only thing you can do is remove the downloaded book from your device and download it again.

I'm not sure how we would handle this in the future

**Comment by ohare93** [comment]
I will give that a try. Surely this is still a bug, in that it happened (that the id is different on local mobile) in the first place and should not? :thinking:

**Comment by advplyr** [comment]
Something happened on your server where that library item got removed and you re-scanned it in. The mobile app reacted as expected when the library item no longer exists, although it's not ideal.

**Comment by ohare93** [comment]
Hmm, yea that probably happened. I did rename a bunch of stuff.
