### ISSUE TITLE
[Enhancement]: Duplicate checking during podcast library scan

### ISSUE THREAD

**Issue by louisjg** [advplyr/audiobookshelf#1096]
### Describe the feature/enhancement

I can download two copies of the same episode via the Find Episode button.  To me, that's fine, but the file overwrites the original, also fine, yet there are two entries in the episode list for that file.

I can manually go through and delete duplicates (not hard delete, just the dupe entries), but I think it would be handy if during a (forced) scan it checked for multiple entries pointing to the same file and either deleted the one with the least metadata information or (ideally) prompted root to do so.

Alternatively, a "check for dupes" button in settings on the library (where scan, forced scan are) would be a good addition I think.

P.S. Thank you so much for making this.  I've been trying for years to jam my podcasts and audiobooks into P**x and it was a nightmare.  This project is exactly what I've needed!

**Comment by advplyr** [comment]
You should not be able to download podcast episodes that you've already downloaded. When searching for new episodes it will look like this:

![image](https://user-images.githubusercontent.com/67830747/198140707-53807193-2c1e-4e13-b55f-2a864868f8a5.png)

Where you can't select those episodes to download.

When you download an episode from there you are not seeing that green check mark?

Keep in mind if you scan in episodes from your file system and don't manually go in and match those episodes to an RSS feed episode then abs is not going to know they are the same episode.

**Comment by advplyr** [comment]
Here is an example of an episode that I scanned in from my file system and is not linked to an RSS feed episode.

I pressed the edit button on the episode and at the bottom of the Details tab you can see it says it is not linked.
![image](https://user-images.githubusercontent.com/67830747/198141247-ee1db38c-8f1a-4cbb-a911-0817aeec2b61.png)

**Comment by louisjg** [comment]
OK I will take a look and see if I can figure out what I did.  It could be that I pulled some in from the filesystem, but I don't remember doing that.

I'll close this, and if I can repro getting duplicates without that I'll file a bug with exact repro steps.  Thanks!
