### ISSUE TITLE
[Feature]: multilanguage portal 

### ISSUE THREAD

**Issue by burghy86** [advplyr/audiobookshelf#1103]
### Describe the feature/enhancement

audiobook shelf il magic, work perfectly but is possible localize with a custom language? classic english, french, spain, italian, china?

thank for all dev

**Comment by Hallo951** [comment]
German as a system language would also be very nice.

**Comment by advplyr** [comment]
What language(s) would you be able to assist in translating for?

**Comment by burghy86** [comment]
Ii help with italian

**Comment by Hallo951** [comment]
I could help with German. You just have to tell me what and how I can integrate the translation into your programme.

**Comment by konradorlinski** [comment]
I can help with Polish translation

**Comment by springsunx** [comment]
I can translate Chinese。

**Comment by advplyr** [comment]
I started to set this up and could now use some help.

I put in some files with language code in here to start:

https://github.com/advplyr/audiobookshelf/tree/eb463a29587081965591a732b4dba74ee5c89925/client/strings

If your language is not there then you can make one and copy the format from the other file.

Having some translations in there now will help with the initial build but we will eventually need much more.

**Comment by Hallo951** [comment]
Hi,

I can't save changes to the translation files in github.dev because I don't have write permissions. Should we download the translation files, change them and then just upload them back here and you add them to the project?

**Comment by burghy86** [comment]
italian traslate pull make

**Comment by konradorlinski** [comment]
> Hi,
> 
> I can't save changes to the translation files in github.dev because I don't have write permissions. Should we download the translation files, change them and then just upload them back here and you add them to the project?

This tutorial may be helpful for you:
[https://github.com/firstcontributions/first-contributions](https://github.com/firstcontributions/first-contributions)

**Comment by advplyr** [comment]
I think I've now gotten about 90% of the strings we will need so it's a good time to start contributing.

If you can copy the english strings json file and change to your language with your language that would be great.
Here is the english one: https://github.com/advplyr/audiobookshelf/blob/master/client/strings/en-us.json

And they will go inside here: https://github.com/advplyr/audiobookshelf/tree/master/client/strings

**Comment by advplyr** [comment]
Your server will have a default language you can set in the server settings. That is what every user will start with by default.
Users will be able to go to their account page and change the language just for them.

So far we will be able to support simplified Chinese (thanks @springsunx) for the upcoming release. Release will be by this weekend most likely so if you get a chance to do the translations this week would be great!

**Comment by Hallo951** [comment]
I will try to finish the German translation tomorrow. Is it possible to change the translation afterwards?

**Comment by advplyr** [comment]
Great, translations can be updated anytime. Updates will go into future releases

**Comment by Hallo951** [comment]
I have finished the german translation and added it as a pull request to you. See if everything fits like this. I don't know much about github...

**Comment by advplyr** [comment]
Looking good! Can't verify the translations though!
![image](https://user-images.githubusercontent.com/67830747/201445835-09df0d40-34b5-451e-83b1-d64803b6306f.png)

**Comment by Hallo951** [comment]
Well, that looks good. When you have published the update, I'll have another look at the translation in the programme itself. Then I'll be able to see better whether it fits reasonably well.

**Comment by advplyr** [comment]
Added in [v2.2.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.3)

Next will be to add to the app and continue adding the missing strings.

**Comment by Hallo951** [comment]
Where can I find the new strings for the translation?

**Comment by konradorlinski** [comment]
New strings for translation were uploaded by @advplyr to files in the strings directory. In your case @Hallo951 this is the file: audiobookshelf/client/strings/de.json
