### ISSUE TITLE
[Enhancement]: API for audio being played from built-in media player

### ISSUE THREAD

**Issue by letshin** [advplyr/audiobookshelf#1104]
### Describe the feature/enhancement

Is there a way to expose the audio api / send a command out (eg play it through VLC on the server). I have a headless server that will be running audiobookshelf and it would be good if I could get the media playing from the audio jack of the server instead of from my PC.

**Comment by advplyr** [comment]
Sending a command won't be supported as this is a very unusual setup.

There is an open issue for a stream URL that we may support that would be an HLS stream #891
