### ISSUE TITLE
Latest Update - Broke icons?

### ISSUE THREAD

**Issue by Merijeek** [advplyr/audiobookshelf#111]
So, I'm seeing this at the top of my screen:

![image](https://user-images.githubusercontent.com/65377425/137612297-83b2c9c1-e818-4ef6-8504-9b7f8dc6ccc9.png)

...and my "bad tracks" bit, which I obviously need to check out, has this icon:

![image](https://user-images.githubusercontent.com/65377425/137612308-7b1cb0a9-245a-48c6-b984-597b1205e2fa.png)

**Comment by advplyr** [comment]
Have you tried a hard refresh? ctrl+shift+r
The icons are still loaded from a CDN, the request probably failed. That reminds me actually to move the icons locally.

**Comment by Merijeek** [comment]
ctrl-shift-r didn't do anything, but a fresh update did. So...I guess we'll call that good for now.

**Comment by advplyr** [comment]
In release [v1.4.11](https://github.com/advplyr/audiobookshelf/releases/tag/v1.4.11) the icon font is stored locally, so this shouldn't happen again.
