### ISSUE TITLE
[Bug]: Published Unknown for all of my podcasts

### ISSUE THREAD

**Issue by backcountrymountains** [advplyr/audiobookshelf#1116]
### Describe the issue

Audiobookshelf isn't updating my podcasts. I tell it to manually find episodes and it says no new episodes, despite new episodes being available. 
I think it's having a problem parsing pubDates? The podcast [FT News](https://feeds.acast.com/public/shows/73fe3ede-5c5c-4850-96a8-30db8dbae8bf) has pubDates but Audiobookshelf lists all episodes as "Published Unknown" when I push the "Find Episodes" magnifying glass.

![image](https://user-images.githubusercontent.com/29560911/200190416-718a411a-7e2a-4926-bf72-c12915c80645.png)

The "Published Unknown" is an issue with all of the podcasts that I have (10+ podcasts).

I don't see any errors in the logs:
![image](https://user-images.githubusercontent.com/29560911/200190822-44dc7b52-4475-4a0f-9435-1c2521402a84.png)

### Steps to reproduce the issue

Have a podcast feed?

### Audiobookshelf version

2.2.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I just tested this and the pubDate is being parsed fine
![image](https://user-images.githubusercontent.com/67830747/200191053-0dd87d04-7efe-45c7-8775-b8614b860c63.png)
![image](https://user-images.githubusercontent.com/67830747/200191070-ce8030a7-a024-40b1-bbf6-03ffca55c488.png)

Are you not seeing this?

**Comment by advplyr** [comment]
![image](https://user-images.githubusercontent.com/67830747/200191107-e6d77781-08c7-4015-9273-5638d2d4dfe1.png)

**Comment by advplyr** [comment]
My guess is you have the wrong RSS feed url

![image](https://user-images.githubusercontent.com/67830747/200191133-37a371bf-25a8-4a09-9e57-25a7f44247fa.png)

should be: https://rss.acast.com/ftnewsbriefing

that will redirect to the link you sent if accessing via the browser, which may be the initial confusion. it is detecting that a browser is accessing it so it redirects to a readable format.

**Comment by backcountrymountains** [comment]
I am actually using [](https://rss.acast.com/ftnewsbriefing) in my podcast. I was just dumb and copied and pasted from when I opened it in the browser instead of what I had set up in audiobookshelf. My bad.
These are my audiobookshelf settings:
![image](https://user-images.githubusercontent.com/29560911/200191521-e92ebe77-ec48-4272-8d4e-ae337944841e.png)

So I'm still having the error. Not sure what I have messed up. It's docker so I don't know what could be different between my setup and anyone else using docker. I don't understand any of this.
I'm going to try adding a new podcast and see if that will parse pubDate correctly.

**Comment by backcountrymountains** [comment]
I tried to add "The Moth" podcast, which has not previously been added to my audiobookshelf, and it has the same "Published Unknown" error. Weird.

**Comment by Lebo77** [comment]
I have a bunch of podcasts. None of them have any publish dates anymore.

This is definitely broken. I double checked several of them are using the correct URL for the RSS feeds and the RSS feed contains <pubDate> tags on each episode.

**Comment by jjakc-76** [comment]
Working for me now after switching to edge version

**Comment by advplyr** [comment]
Fixed in [v2.2.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.3)
