### ISSUE TITLE
[Bug]: BATCH MODE for editing audio books faulty after update to 2.2.2.

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1117]
### Describe the issue

Hi,

Since the latest update, the batch mode for editing multiple audiobooks no longer works correctly for the series (I have not tested it for the normal audiobooks). Only the first selected audio book is displayed but not all selected audio books.

Another small problem in the batch mode view is the fact that, at least in version 2.1.2, the selected audiobooks are displayed in a jumble. It would be better for them to be displayed in the same order as the audio books are ordered in the respective series.

Another idea, is it possible to add a button with which you can select all audiobooks of a series? At the moment, to edit multiple audiobooks, you have to select them all individually.

### Steps to reproduce the issue

1. Open an audio book series with many audiobooks under the view series.
2. select several audio books. 
3. open the batch-editing-mode. 
4. only one audiobook is displayed instead of all selected audiobooks.

### Audiobookshelf version

2.2.2 

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Related to #1136 and fixed in the next release

**Comment by advplyr** [comment]
Fixed in [v2.2.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.3)
