### ISSUE TITLE
[Bug] Metadata override folder structure

### ISSUE THREAD

**Issue by J4gQBqqR** [advplyr/audiobookshelf#1123]
Folder 1

> Book1

> Book2

> Book3

If the books in all three subfolders have empty idv3 metadata tags, the name of folder 1 will show up as the author name.

However, if one of the books, e.g. Book2, has idv3 tag showing metadata that has author field populated, only Book2 will be detected. The other two books which has empty idv3 tag will not show up.

Proposed solution: Optionally disable/enable idv3 metadata tag detection for specific folder or for all the folders in a library.

**Comment by J4gQBqqR** [comment]
No, the option is disabled.

**Comment by advplyr** [comment]
In this case you are saying Book2 had the author name from the audio file metadata whereas Book1 and Book3 used the folder name as the author?

Unless you have that setting enabled then all 3 books would use the folder name regardless of if there is a meta tag on those audio files for author.

**Comment by J4gQBqqR** [comment]
I tested again with the option disabled. I am observing what you have described. It is wired that I have different observation previously. I must have turned this option off at one time point. Thanks for pointing it out in a timely manner. 

Love your app, awesome work.
