### ISSUE TITLE
[Enhancement]: Adding api endpoint to get active users

### ISSUE THREAD

**Issue by thomasbrooks4** [advplyr/audiobookshelf#1125]
### Describe the feature/enhancement

It would be nice to have a basic API endpoint to get the amount of online users. Ideally it would be cool to have options to also get more info on the active listening sessions.

**Comment by advplyr** [comment]
Added in [v2.2.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.3)

`/api/users/online` must be an admin user
