### ISSUE TITLE
[Bug]: SERIES-PART id3 tag data with non-numeral characters is appended to end of Series name in ABS

### ISSUE THREAD

**Issue by chyron8472** [advplyr/audiobookshelf#1128]
### Describe the issue

When the SERIES-PART id3 tag contains text other than numerals (eg. `a1`, `b3`, `1.2`, `2.1.3`) said text is being appended to the end of the Series name in ABS, rather than being inserted into the Sequence field.

### Steps to reproduce the issue

1. Embed `2b` in the SERIES-PART id3 tag of an audiobook that exists in ABS
2. Click `Re-Scan` in the book's Details tab in ABS.

### Audiobookshelf version

v2.2.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Are you sure this is coming from the SERIES-PART tag and not the data pulled from metadata.abs

A bug was brought up in #1360 that I confirmed has to do with non-numerical characters in sequence.

**Comment by advplyr** [comment]
Fixed in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
