### ISSUE TITLE
[Bug]: Collections are available in every library but can not save Books into them

### ISSUE THREAD

**Issue by Gunsi1973** [advplyr/audiobookshelf#1130]
### Describe the issue

I have several librariers (English, German) with books in them. I use collections. The following is happening:

- 2 Collections were created in Library "English" 
- 1 Collection was created in Library "German"
- When I want to add a book into a collection I see all three of them
- Trying to add a Book from eg. "German" to a collection from "English" does not work ("Failed to add book to collection")

**Expected behavior:**
- Preferred: Collection can save Books from any library - eg. for a "Read next" collection not depending on library
- Not preferred: Only collections that are associated with the library are visible when adding to collection

**Side Note / Wish List:**
- Private Collections for me and public collections that I can share for users and/or all

### Steps to reproduce the issue

1. create at last 2 libraries
2. create collections in a library
3. try to add books from the other library to the collection

### Audiobookshelf version

2.2.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.3)

Collections will only be shown for that specific library.

Playlists will be added in the future that will basically be collections for the user only.
