### ISSUE TITLE
[Enhancement]: Schedule update of  RSS feed that abs publish 

### ISSUE THREAD

**Issue by joshuatly** [advplyr/audiobookshelf#1131]
### Describe the feature/enhancement

Use case: 

I have a library which is type is Podcast 

I currently have a folder which have a bunch of files dropped in by an external script daily, and having abs regularly scan the folder daily has made abs aware and picked up new files which has been dropped in.

I made an abs RSS feed of that item, however it is not updated upon scan. 

Can I request a feature to have Schedule to update abs published rss feed, so new items that is in the library can be published in rss as well?

Many thanks.

**Comment by joshuatly** [comment]
Just a note, I do noticed that the feed get updated upon audiobookshelf service restart (running debian).
Ideally would like to have the feed update without restarting the server and have more control over that.

**Comment by advplyr** [comment]
Fixed in [v2.2.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.3)

When the audiobook is updated then the RSS feed will update

**Comment by joshuatly** [comment]
Awesome! Thanks for the hard work
