### ISSUE TITLE
[Enhancement]: Ability to have a library that includes both podcasts and books

### ISSUE THREAD

**Issue by JaxzKyd** [advplyr/audiobookshelf#1133]
### Describe the feature/enhancement

Currently when creating a library you can choose _either_ books or podcasts. My request is for the ability to have both. Mainly for audio drama usage, because some audio dramas can be added as a podcast easily, like The Magnus Archives, Wolf 359, etc; and some can't be added with the podcast search and need to be added as books, like the GraphicAudio productions, Big Finish productions, and so on.

**Comment by advplyr** [comment]
This is not going to be supported because it would require a major rewrite of the server & data model. We would also need to redesign the frontend. Maybe there is another solution you can think of.
