### ISSUE TITLE
[Bug]: Quick Match Broken in the new update (v2.2.2)

### ISSUE THREAD

**Issue by Dr-Blank** [advplyr/audiobookshelf#1136]
### Describe the issue

Before the update, I could quick match all the currently selected books.

After the update, despite how many books are selected, only one gets cued for quick match (mostly it's the first one).

Also pressing SHIFT key does not select all the books in between like it was intended to be in the update #1020.

![msedge_d6C5Joczke](https://user-images.githubusercontent.com/64108942/201021993-236c7a98-556b-4dee-b04e-5a2ddfa0cb30.png)

### Steps to reproduce the issue

1. Go to any audiobook library
2. select multiple books
3. click on quick math

### Audiobookshelf version

v2.2.2

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
This is fixed in the next release coming soon

**Comment by advplyr** [comment]
Fixed in [v2.2.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.3)
