### ISSUE TITLE
[Bug]: ASIN search fails if item is not listed on Audible

### ISSUE THREAD

**Issue by DevinCampbell** [advplyr/audiobookshelf#1138]
### Describe the issue

When a book/audiobook is not listed on Audible, but is on Amazon, searching by the ISBN does not find the results. An example is Alcatraz vs The Evil Librarians narrated by Charlie McWade. The ISBN-10 is 0545024935. This book is not listed on Audible or any of the other currently listed providers, so there is no way to match the book to pull metadata besides manually inputting all the fields.

https://www.amazon.ca/Alcatraz-Versus-Evil-Librarians-Library/dp/0545024935/ref=tmm_abk_swatch_0?_encoding=UTF8&qid=&sr=#detailBullets_feature_div

### Steps to reproduce the issue

1. Find a book on Amazon that isn't listed in Audible.
2. Search for the book via ISBN using any current provider in Audiobookshelf.

### Audiobookshelf version

2.2.2

### How are you running audiobookshelf?

Docker

**Comment by DevinCampbell** [comment]
I realize this is probably an expected result and may not be considered a bug but more of an enhancement. I also realize that this will be resolved once searching by ISBN/Amazon as a provider is implemented. I didn't see anything about this in any issues or discussions so I figured I'd open the issue so anyone having similar issues can see this.

**Comment by advplyr** [comment]
This does come up for Audible but not with that narrator.

![image](https://user-images.githubusercontent.com/67830747/201223447-348dd905-bf05-4300-8e73-89d5f70f095b.png)

We are not going to support web scraping Amazon listings so if it doesn't come up with Audible then you'll have to try Google Books or iTunes.
The only providers we are going to support are ones that have API's setup or that someone has setup an API for.

**Comment by advplyr** [comment]
As of now I don't think this is a bug so closing it
