### ISSUE TITLE
[Enhancement]: Translation update

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1148]
### Describe the feature/enhancement

I just had a look at the German translation. Thank you very much for the implementation. But it looks like I'll have to work on it again. It doesn't fit yet. Furthermore, not all strings have been translated yet.

Is there a kind of dev mode in which I can edit the various buttons and strings directly in the programme? That would make the work a lot easier, because it's difficult to find the right string in the list.

**Comment by advplyr** [comment]
There is no way to edit directly in the program. I was thinking of making something so it would be easier but that will take a lot of time to build. I'm not sure that is worth it.
Best way is to clone the repo and open it in VSCode. Then you can search across the entire project for each string.

For example if I search for the string "ButtonNevermind" in VSCode I can see that it is used in the backups table.

![image](https://user-images.githubusercontent.com/67830747/201524732-4ce01430-8024-4581-a9e0-01fdcec0d5cd.png)

If you're not familiar with VSCode it's Ctrl+Shift+F to search across entire project

**Comment by Hallo951** [comment]
Wasn't there a design view in vs where you can see the name of the individual elements in the layout? How do I get to this in the vs code? What I'm missing is a location of the individual strings to be able to decide what is translated well and what is not so well. Do you have an idea how to do this best?

**Comment by advplyr** [comment]
This is a website so you would need to run the code locally. There are instructions to run it locally here: https://github.com/advplyr/audiobookshelf/discussions/259#discussioncomment-1869729

This is probably too much setup and effort if you aren't familiar with this development environment. There is no easier way unfortunately.
