### ISSUE TITLE
[Bug]: Getting error [DB] Update entity session Failed: Error: Lock file is already being held

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf#1151]
### Describe the issue

Seeing a lot of red icon on book cover on mobile, checked on server and see lots of this in logs:

[DB] Update entity session Failed: Error: Lock file is already being held

Restarted both client and server, no joy

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.2.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Please see #1095
You'll need to delete the lockfiles yourself

**Comment by barelylit** [comment]
Which lock file ?
