### ISSUE TITLE
Android App books in a series are not displayed in order

### ISSUE THREAD

**Issue by derkington** [advplyr/audiobookshelf#1152]
### Describe the issue

Since the update to server version 2.2.3 & 2.2.4, in my android application book series are shown out of sequence on a 1x1 and 2x2 list. Instead of books being ordered in sequence lowest number to highest as follows

Book_1	Book_2
Book_3	Book_4
Book_5 	Book_6
Book_7	Book_8
Book_9	Book_10

I get the following Instead

Book_8	Book_4
Book_2	Book_9
Book_1	Book_6
Book_5	Book_10
Book_7	Book_3

The books are ordered correctly via browser but not the android application. 

### Steps to reproduce the issue

1. Go to a series 
2. Select a series with a handful of books

### Audiobookshelf version

Server 2.2.4, Android app 0.9.59-beta

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Fixed in [v2.2.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.5)
