### ISSUE TITLE
[Enhancement]: Add play time to Detail

### ISSUE THREAD

**Issue by wiebel** [advplyr/audiobookshelf#1157]
### Describe the feature/enhancement

The detail page of a Book should contain the play time.

**Comment by advplyr** [comment]
The duration is there
![image](https://user-images.githubusercontent.com/67830747/201736124-4b8c652d-bc99-43aa-afdd-0336316a872f.png)

Not sure what you mean

**Comment by wiebel** [comment]
I ment the "Details" tab in edit mode.

**Comment by advplyr** [comment]
That Details tab is only for book details that are editable. The duration of the audiobook is not something editable so it won't be added to that tab.

**Comment by wiebel** [comment]
While i do understand  why the information is not there it would be useful to have some non-editable facts on that page, as there are many ways to enter the edit mode and only on one of it the duration and size is visible.
