### ISSUE TITLE
Listening times are not calculated correctly.

### ISSUE THREAD

**Issue by shomilsaini** [advplyr/audiobookshelf#1158]
Listening times are not calculated correctly. For total podcasts of length betweeen 20mins to 80mins you can see in the attached screenshot the time listened is not correct.

Overall listening times for all users
![image](https://user-images.githubusercontent.com/46788173/201744794-f43f7233-2bda-494b-b04e-fc84c8862921.png)

Details of the first item
![image](https://user-images.githubusercontent.com/46788173/201745210-b04f367a-2c5d-49ab-ba7d-30d80eefabc2.png)

**Comment by shomilsaini** [comment]
Yes I have some friends with iOS and myself on Android. With the server docker image deployed on Unraid.
Once the updates are pushed for all platforms I will be happy to test out again.
If there is anything I need to relay to get this fixed on iOS to my contacts please let me know thanks.

Cheers!

**Comment by shomilsaini** [comment]
> It may have been fixed with the last release, have you had any listening sessions come in incorrectly in the latest release?

Sorry forgot to answer this. Yes these stats are from today and the details page shows the date and time as well.
The server is running v2.2.4

If there are any updates please feel free to let me know how to acquire them.

Thanks.

**Comment by advplyr** [comment]
I just want to confirm you are only seeing these listening session errors coming from iOS ?

**Comment by shomilsaini** [comment]
> I just want to confirm you are only seeing these listening session errors coming from iOS ?

Yes, the `Time Listened` is incorrect for iOS only.

However, even on Android app the Date time fields dont make sense. Screenshot below.

For example - `Started At` & `Start Time` are not same. Or I am not able to comprehend their meanings. Same for other fields.

![image](https://user-images.githubusercontent.com/46788173/201749146-9cdfe3dc-6a2c-4951-8530-73e61fd6c404.png)

For reference, this is how my plex history looks on Tautulli. It may be an apples to oranges comparison, please correct me if so.

![image](https://user-images.githubusercontent.com/46788173/201749742-a2a2cee2-53c4-49ff-81a4-eb929a21087a.png)

**Comment by shomilsaini** [comment]
Also, the Android Auto app does not let me choose individual files to play.
So if I have different files for different episodes of a podcast I only see the name and not the episodes to choose from.
It will play where I last left it, but SOL if I want to jump episodes.

Cheers!

**Comment by advplyr** [comment]
> Also, the Android Auto app does not let me choose individual files to play. So if I have different files for different episodes of a podcast I only see the name and not the episodes to choose from. It will play where I last left it, but SOL if I want to jump episodes.
> 
> Cheers!

Are you using a podcast library? For podcast libraries every audio file is a separate episode always.

**Comment by shomilsaini** [comment]
> > Also, the Android Auto app does not let me choose individual files to play. So if I have different files for different episodes of a podcast I only see the name and not the episodes to choose from. It will play where I last left it, but SOL if I want to jump episodes.
> > Cheers!
> 
> Are you using a podcast library? For podcast libraries every audio file is a separate episode always.

I Will post a picture next time I am in my car.
Thanks for your time and effort i helping out.

Cheers!

**Comment by advplyr** [comment]
This should hopefully be fixed in the latest iOS release [v0.9.60](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.60-beta)
