### ISSUE TITLE
[Bug]: Marking the 'Collapse Series' box in a filter doesn't properly remove 'collapsed' items

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf#1162]
### Describe the issue

When filtering a library by series, using the 'collapse series' collapses the series, but leaves 'ghost' entries behind.
![Uploading test.PNG…]()

### Steps to reproduce the issue

1. Filter library by a filter which contains multiple items in multiple series
2. Tick the 'Collapse Series' box
3. Scroll down

### Audiobookshelf version

v2.2.4

### How are you running audiobookshelf?

Docker

**Comment by tomazed** [comment]
Are thoses the ghost items you are talking about?
![image](https://user-images.githubusercontent.com/10292533/201885227-0d214877-c0b7-4934-9472-a427d2bfcc08.png)

**Comment by advplyr** [comment]
Yeah that is fixed in the edge version. The correct items are showing it is just showing you some extra blank ones.

**Comment by advplyr** [comment]
Fixed in [v2.2.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.5)
