### ISSUE TITLE
[Enhancement]: Delete Tags in a library

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf#1163]
### Describe the feature/enhancement

A lot of Audible Tags overlap to the point that they aren't useful. For example, I have a 'Short Stories', 'Anthologies', and a 'Short Stories & Anthologies' tag from metadata Ive scraped. 

Digging into each tag, I see that 'Short Stories' has a subset of the 'Short Stories and Anthologies' tag and 'Anthologies' also has a subset of books in the 'Short Stories and Anthologies' tag. This leads to a lot of duplicate tags that don't cover all the books, when there exists one 'all encompassing tag' which collects all of the subsets of books into one tag. I expect the same goes for the common 'Fantasy', 'Scifi', and 'Scifi and Fantasy' tags. 

It'd be nice for management purpose if we could selectively delete a tag from the system, and have it removed from all books that currently have it assigned.

**Comment by austinphilp** [comment]
+1, I wrote a python script to do this using the REST API but it would be great to be able to do so from the UI

On a similar note it would also be nice to be able to "bulk rename" a tag. For Instance, audible has multiple tags it uses for Comedy ("Comedy", "Humorous", and "Humor" that I've encountered so far), it would be great to be able to just rename the latter two to "Comedy" for consistency.

Not sure what the UI would look like for this though..

**Comment by advplyr** [comment]
Added in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)

For tags and genres
