### ISSUE TITLE
[Enhancement]: Network limit

### ISSUE THREAD

**Issue by TheMaxik** [advplyr/audiobookshelf#1165]
### Describe the feature/enhancement

Please add a outgoing network limit for uploading books to a phone outside of the local network.
Currently my VM uses my whole upload bandwith(50MBit/s) when i download a book from outside of my home network.

**Comment by advplyr** [comment]
Are you talking about uploading or downloading?

**Comment by TheMaxik** [comment]
Uploading. If i click Download inside the app.

**Comment by TheMaxik** [comment]
just a simple bandwith limiter for upload and downoad for the server app. So it does not use all my bandwith

**Comment by advplyr** [comment]
I could be wrong but I'm thinking this is something that you should be implementing on your server.
If you have an example software that does this let me know and I'll take a look but for now this won't be supported.
