### ISSUE TITLE
[Bug]: Missing Translation Strings

### ISSUE THREAD

**Issue by tomazed** [advplyr/audiobookshelf#1166]
### Describe the issue

After doing the French translation, I've noticed several strings that were not in the json files
The missing labels (highlighted in yellow) are found in Book Edit => Tools
![image](https://user-images.githubusercontent.com/10292533/202142807-68749397-405c-4081-bab3-903f9aa936e2.png)

The "or" in upload page
![image](https://user-images.githubusercontent.com/10292533/202144200-679e0387-1041-46bf-80bb-2c7b7178d812.png)

The Apprise Label in the Settings => Notifications page
![image](https://user-images.githubusercontent.com/10292533/202145137-01e74e52-9ffa-4b5c-9b8a-ae33a96adf0c.png)

### Steps to reproduce the issue

1. Change language to any other than english
2. Go to one of the identified page listed in the description
3. some text in the page is translated and some other is in english. The text in english cannot be found in the json strings file

### Audiobookshelf version

2.2.4

### How are you running audiobookshelf?

Built from source

**Comment by advplyr** [comment]
Thanks, I'm sure there will be a bunch of these.
I also added some Socket strings.

**Comment by burghy86** [comment]
other missing traslation 
![Senza titolo](https://user-images.githubusercontent.com/17832100/202676953-610073af-4164-45a2-949d-57df13d9b96f.png)
![Senza titolo2](https://user-images.githubusercontent.com/17832100/202676
![Senza titolo4](https://user-images.githubusercontent.com/17832100/202677117-edcdc18d-a231-4c5b-80f2-dc38bd1e3f1c.png)
979-eed8f8fc-b278-4889-ad1e-c609d4bc9dac.png)

**Comment by tomazed** [comment]
Found some more in the metadata manager=>M4B Encoder
![image](https://user-images.githubusercontent.com/10292533/202814172-1204610d-2d94-44c2-bd45-7d9f451b3a12.png)

metadata manager =>Embedded Metadata
![image](https://user-images.githubusercontent.com/10292533/202814345-8418285f-1b20-4b7d-bc16-9c0de1bee7c9.png)

Some label of thoses two pages overlap

**Comment by advplyr** [comment]
The sort/filter ones are added but I didn't add the tooltip because that won't be staying for much longer.

**Comment by advplyr** [comment]
I also had a bunch of strings out of order, they were supposed to be alphabetical.

**Comment by tomazed** [comment]
when searching for strings, I found a lot of hardcoded strings in [client/components/app/LazyBookshelf.vue](https://github.com/advplyr/audiobookshelf/blob/8931702f1b745c1e43ff4ee9b3af3102d5caa41a/client/components/app/LazyBookshelf.vue) for example
https://github.com/advplyr/audiobookshelf/blob/30cf144090117b18dc979b91d9d361f7950a4384/client/components/app/LazyBookshelf.vue#L88-L89
lots of them seems to be related to default configuration or empty library. The only one I'm seeing in my setup is "You haven't made any collections yet" and this file is the only file that match this string

**Comment by advplyr** [comment]
I got all of these except the ones on the tools page you mentioned here https://github.com/advplyr/audiobookshelf/issues/1166#issuecomment-1320605264

These are in v2.2.5

**Comment by burghy86** [comment]
![Screenshot_20221120-003126_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875792-0b4a2c55-c5a7-444d-91d5-a7e19db600ed.jpg)
![Screenshot_20221120-003026_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875794-cb442ae1-0972-4183-b95a-2c4fc3440055.jpg)
![Screenshot_20221120-002853_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875795-1225f9c2-00d0-4e7f-9bdc-5c0dd865964e.jpg)
![Screenshot_20221120-002632_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875796-0c38d3cc-3afa-4d91-b1db-5fa7b9128537.jpg)
![Screenshot_20221120-002503_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875797-58e6fa9a-fc78-4eec-a9da-52e1fe9e68c8.jpg)
![Screenshot_20221120-002405_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875798-c9e35732-adfd-4035-a27c-8082ce13216f.jpg)
![Screenshot_20221120-002229_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875799-abbf8671-0cd1-402b-aa7c-38e15b2c12b1.jpg)
![Screenshot_20221120-002211_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875800-9fa7de93-be7e-4854-805d-4570c4a86eac.jpg)
![Screenshot_20221120-002056_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875802-4ae89a53-b639-4bba-a4b5-85165cd86a35.jpg)
![Screenshot_20221120-002026_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875803-203484af-144b-420c-b10f-7cea4cc2f0d6.jpg)
![Screenshot_20221120-002007_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875804-018bf7dc-9f4a-40f3-a373-ea9b6d375b6e.jpg)
![Screenshot_20221120-001943_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875805-b3379b2f-cc66-45ba-855c-c15e89c181a5.jpg)
![Screenshot_20221120-001856_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875806-d2b092a2-2c2f-490e-8309-f0e61bce2ba3.jpg)
![Screenshot_20221120-001846_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875807-c0f9a36f-f9bd-4415-b216-a9128121e267.jpg)
![Screenshot_20221120-001401_Samsung Internet](https://user-images.githubusercontent.com/17832100/202875808-880bd2ec-818b-4b95-a069-f6e5fb971c9b.jpg)
![20221120_001541](https://user-images.githubusercontent.com/17832100/202875810-04a314c6-b81b-4013-bd6b-28121c8cd67f.jpg)

**Comment by advplyr** [comment]
The first 3 screenshots were added already. I'm not sure about the shortened days of the week/month since those need to be that size to work with the design.

**Comment by burghy86** [comment]
The screenshot arrive with 2.2.5 release in series and library page 

The short day and months is not problem. I reduced with 3 letter
Day: lun mar mer gio ven sab dom
Months: gen Feb mar apr mag giu lug ago set ott nov dic

**Comment by advplyr** [comment]
I think I got most of these. Still need to do the tools page and the week/month short strings.

**Comment by tomazed** [comment]
Some new strings were introduced in commit https://github.com/advplyr/audiobookshelf/commit/3316394f5caa5a8b4e1e55d899256bd9235f2fb7 regarding adding series back to "Continue Listening". Thoses are not part of the translated strings
https://github.com/advplyr/audiobookshelf/blob/51070b3e7be0e4008612dd82521788b3e2c70cdf/client/components/app/BookShelfToolbar.vue#L64
https://github.com/advplyr/audiobookshelf/blob/51070b3e7be0e4008612dd82521788b3e2c70cdf/client/components/app/BookShelfToolbar.vue#L248-L254

**Comment by Hallo951** [comment]
Here is another string that is missing.

![grafik](https://user-images.githubusercontent.com/40667862/203094472-0602a9e6-95bd-4f4b-86c8-33ac50134a4c.png)

**Comment by advplyr** [comment]
Still need to get to some of these here so I'll keep this open. Also added a few more in v2.2.6
https://github.com/advplyr/audiobookshelf/commit/c72609013c0a9ba7bcaa3559ab1c7eec781df115

**Comment by advplyr** [comment]
I realized that some of the library filters would be broken when using another language

**Comment by advplyr** [comment]
I had a typo here
```json
"LabelSettingsSquareBookCovers": "Use square book covers"
```

It used to say `User square book covers`

**Comment by tomazed** [comment]
> ```json
> LabelSettingsSquareBookCovers
> ```

Apparently I did not translate the typo. Label seemed weird to me so I search it in the app I decided it should be "use" instead of "user" and translated accordingly.
no update necessary on the fr.json file ;)

@advplyr Are there any strings left untranslated or can I close the issue?

**Comment by advplyr** [comment]
I just added the "Map details" and 2 other new translations on that page.

I also haven't done the translations for the stats heatmap

**Comment by advplyr** [comment]
I suppose it depends on the context which I know can be difficult to ascertain from the translation files.
A "Library Item" is a book or podcast. A "Media Item" is a book or podcast episode.
The reason a media item is distinguished is because this is where actual progress is stored. So for podcasts we want to store progress on the episode.

Most of the time "Item" will be referring to Library Item.
For example, "No Items" is referring to Library Item's.

If you point out a specific translation I can tell you more.

**Comment by Hallo951** [comment]
I have translated "item" into German as "audiobook/podcast".

**Comment by advplyr** [comment]
We will support other media in the future so if there is a generic term for "media" then that would be more fitting.

**Comment by advplyr** [comment]
I think we can close this after [v2.2.13](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.13)

Thanks for all your help in translations and thanks @tomazed for localizing the date/time strings.
