### ISSUE TITLE
[Bug]: When Deleting the Last Entry of a "Listening Sessions" Page "No Listening Sessions" is Displayed

### ISSUE THREAD

**Issue by lkreft** [advplyr/audiobookshelf#1168]
### Describe the issue

When deleting the last element of a "Listening Sessions" page "No Listening Sessions" is displayed and the paging indicator disapperas, despite there being additional pages and sessions.

Clicking "Listening Sessions" on the sidebar also does not do anything, instead you have to select another menu entry and go back to "Listening Sessions" in order to see the remaining sessions.

### Steps to reproduce the issue

Precondition: More than ten listening sessions (in order to have more than one page displayed).

1. Go to "Settings > Listening Sessions"
2. Select the last page
3. Delete all entries on that page

### Audiobookshelf version

v2.2.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.5)
