### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wiebel** [advplyr/audiobookshelf#1169]
### Describe the issue

Audio files created by Mp3Wrap only get played to the first embeded file

### Steps to reproduce the issue

1. Create awrapped mp2 file e.g.:
    mp3wrap album.mp3 track1.mp3 track2.mp3 ...
2. Play the resulting album.mp3 via audiobookshelf
3. Playback stops after the content of tack1.mp3

### Audiobookshelf version

v2.2.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
On a quick search this appears to be a bug with Mp3Wrap. audiobookshelf is using the duration of the file found from the metadata and Mp3Wrap is not correctly updating that duration.

See:
https://hydrogenaud.io/index.php/topic,121228.0.html
