### ISSUE TITLE
[Bug]: Series with over 100 episodes are not displayed correctly; limit in batch mode when editing (49) and when scraping at (100) 

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1170]
### Describe the issue

I have a series with 158 episodes. All episodes are correctly tagged and the metadata per episode is saved as an abs file. In the settings, "Prefer abs metadata" is activated. Up to the 100th episode everything is correct. But from the 101st episode onwards, it no longer reads the abs file correctly. It starts counting from the beginning again and uses the abs file of the first episode instead of the abs file of the 101st episode.

Furthermore, there seems to be a limit when editing and scraping in batch mode. This is 49 for editing and 100 for scraping. Is it possible to increase both to, say, 300?

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.2.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Please update to the latest server version 2.2.4 where that is fixed. Unfortunately there was another bug introduced though that will be fixed in the next release.

**Comment by Hallo951** [comment]
I have updated audiobookshelf to the latest version. Fixed the problem with displaying series over 100 episodes. The limits for editing (currently 49) and scraping (currently 100) still exist. Can we increase these limits to 300?

**Comment by advplyr** [comment]
I don't know what you mean by scraping. Abs doesn't do any scraping.

**Comment by advplyr** [comment]
There is now no limit for batch editing as of [v2.2.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.5)
