### ISSUE TITLE
[Feature request] Support cast upnp/av and dlna device

### ISSUE THREAD

**Issue by burghy86** [advplyr/audiobookshelf#1178]
Is possibility to implement a cast upnp/av o dlna cast audiobook? I have a samsung tv and volumio client for liquid music. With vlc, dsaudio/dsvideo client  and mx player, youtube can send my video and music on a this device using a button in a app. If chromecast are support I think is possibile extended this function to all devices with dlna client 😇🤞
If possible this function are very flexible with sonos speakers, soundbar wifi, Alexa and Google speaker

**Comment by burghy86** [comment]
Double request. Can merge.

https://github.com/advplyr/audiobookshelf/issues/405

**Comment by advplyr** [comment]
Duplicate. I have looked into it briefly and will be a lot of effort for something I don't use. Hoping someone else steps up to build this.
