### ISSUE TITLE
Upload to <domain> Bad Gateway Websocket

### ISSUE THREAD

**Issue by DOFfactory** [advplyr/audiobookshelf#1186]
Thanks for the amazing software, using it daily. 

I am self-hosting it, with my own domain, through NGINX Proxy Manager, where I have websocket enables, as suggested in the manual. 

Whenever I try to upload a cover (jpg file), or use the search function for it, I get the following error:

```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

Am I missing some special setting, port to the websocket?

**Comment by nmatton** [comment]
I have the same when I'm using SSL. 

It works when using unsecured http

**Comment by DOFfactory** [comment]
well, this then means that the nginx settings need adjustment, or some other websocket port needs special setting. I would like to have this working as I prefer https connections

**Comment by advplyr** [comment]
This doesn't have to do with Abs.

This is something with your server config. Someone in the Discord or Matrix server may be able to help you Many users have this setup properly with NGINX Proxy Manager and would know more then I would about that.
