### ISSUE TITLE
[Bug]: Australian Audible provider is incorrect

### ISSUE THREAD

**Issue by jberlyn** [advplyr/audiobookshelf#1191]
### Describe the issue

The Australian provider for Audible when pulling covers is incorrect and doesn't present any results. The provider in the dropdown is listed as `Audible.co.au` but the correct URL is `Audible.com.au`.

### Steps to reproduce the issue

1. Select `Audible.co.au` from the list of cover providers.
2. No covers are found after searching.

### Audiobookshelf version

v2.2.5

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Thanks. Got that from the typo in their docs https://audible.readthedocs.io/en/latest/marketplaces/marketplaces.html#country-codes

**Comment by advplyr** [comment]
Fixed in [v2.2.6](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.6)

**Comment by jberlyn** [comment]
@advplyr I just noticed there is another incorrect entry for the Australian provider in `scanner.js` in the client store.

https://github.com/advplyr/audiobookshelf/blob/master/client/store/scanners.js:30

**Comment by advplyr** [comment]
That is intentional. That is just the value sent to the server but we are making the correct requests to audible and audnexus.

This appears to be a bug with Audnexus and not audiobookshelf.

**Comment by advplyr** [comment]
Here is an example.

Using audible API: https://api.audible.com.au/1.0/catalog/products/B01HFL5SC6?response_groups=contributors,media,price,product_attrs,product_desc

Using Audnexus for the same book: https://api.audnex.us/books/B01HFL5SC6?region=au

**Comment by jberlyn** [comment]
Yeah okay, it seems like a bug with their API.

For example, this works with the Audible API:
https://api.audible.com.au/1.0/catalog/products?title=nolyn

But using the ASIN and the region set to `au`, it returns a 500:
https://api.audnex.us/books/B089XC53RW

**Comment by jberlyn** [comment]
I have opened an issue over on the Audnexus repository, hopefully they can get it solved.

https://github.com/laxamentumtech/audnexus/issues/571

**Comment by jberlyn** [comment]
Just wanted to give you an update that this has been fixed on the following commit over at Audnexus.

https://github.com/laxamentumtech/audnexus/commit/ea338faf0a1ed0a5fbee9edbfd1641208f65447a

**Comment by advplyr** [comment]
Thanks for the update
