### ISSUE TITLE
[Enhancement]: split narrators/authors when pasting in meta data editor

### ISSUE THREAD

**Issue by Benni-chan** [advplyr/audiobookshelf#1198]
### Describe the feature/enhancement

when pasting multiple authors or narrators, they should be split into seperate entries.

we should decide on one split character.
maybe a comma is not the best, because somtimes the name of one author is split like "lastname, firstname".
a semicolon could work better.
or only split with comma, if there is more than one.

**Comment by Uroth** [comment]
Same should also apply for when pasting into Genres and Tags please.

**Comment by advplyr** [comment]
I implemented this using semicolons. It will work for every multi select input with user input. Narrators, authors, tags and genres

As shown in the example it will not include anything already there

![input_paste](https://github.com/advplyr/audiobookshelf/assets/67830747/05046d74-701f-44e2-be7e-4ecacfdf21fb)

**Comment by advplyr** [comment]
Added in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)
