### ISSUE TITLE
[Enhancement]: Multimedia keyboard shortcuts control

### ISSUE THREAD

**Issue by springsunx** [advplyr/audiobookshelf#1201]
### Describe the feature/enhancement

![image](https://user-images.githubusercontent.com/23657968/203246604-64c736a1-65ff-4676-aa92-ca638f24fa1f.png)

![image](https://user-images.githubusercontent.com/23657968/203247755-dd20620e-a511-48a4-88e0-b5389ebeeb58.png)

Describe the feature/enhancement

Multimedia keyboard shortcuts control previous chapter, next chapter. Now only play and pause are available.

**Comment by advplyr** [comment]
These buttons are for next and previous track which were disabled but will be available in the next release.

Just to add more context here, the jump forward/backwards buttons are already available but they just don't show up in the one in your screenshot.

Here is what it looks like in the browsers (Brave) media session widget:
![image](https://user-images.githubusercontent.com/67830747/203438440-acef8a46-db05-4000-b8e0-1576814fd06d.png)

In the current release v2.2.5 the next/prev track buttons won't be there.

**Comment by advplyr** [comment]
Updated in [v2.2.6](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.6)
