### ISSUE TITLE
Help with adding external usb hard drive.

### ISSUE THREAD

**Issue by steveuk23** [advplyr/audiobookshelf#1203]
Hi.
Thanks for this I'm loving it so far.
I have it running on a raspberry Pi4 Ubuntu server and docker.
I'm trying to work out how to add a USB hard drive so I can select it to use in the library.
I've mounted the drive into /media/usbdrive and it's showing mounted as sdb1 but all the instructions I've tried following aren't working for me.
Could you help with how to do it.
Thanks

**Comment by advplyr** [comment]
I'm not able to help with this here but if you join our discord or matrix server there are many active users there that can help. Links to those are here https://www.audiobookshelf.org/support
