### ISSUE TITLE
Is there a standard for ISBN in Tag Data? If so could the details you parse be mentioned somewhere?

### ISSUE THREAD

**Issue by LostOnTheLine** [advplyr/audiobookshelf#1207]
### Describe the feature/enhancement

I have a few of my audiobooks that include an ISBN tag or ASIN tag
Unfortunately they do not always include it the same way
The most common one is simply ISBN for the tag field, I've seen that one from multiple places & the others all are single instances with `ISBN` with a "`&`" symbol in them for some reason `&ISBN`, `IS&BN`. Most do not include the ISBN at all, but enough do that it would be nice to know the way for the app recognizes them & have that added to the details/manual/instructions in some way.
Is there a standard? Or does the scanner just look for something it recognizes as an ISBN in any of the tags? I have 1 that didn't have the tag at all, but does include the ISBN in the Details tag, but Audiobookshelf's details list it in the details for the item. Is it pulling it from the Comment? or is it just pulling it from online & they matchup?

**Comment by advplyr** [comment]
It is in the documentation here: https://www.audiobookshelf.org/docs#book-audio-metadata

There is no standard and this may change soon with the introduction of a new metadata library called tone.
