### ISSUE TITLE
[Enhancement]: Add a filter for single or multi-files audiobooks

### ISSUE THREAD

**Issue by hbooo** [advplyr/audiobookshelf#1213]
### Describe the feature/enhancement

Currently there is no way to mass encode the library to m4b audiofiles. 
As it can take some times to encode everything it could be great to have the possibility to filter for single or multi-files in order to see what books remains not encoded

**Comment by advplyr** [comment]
Added in [v2.2.7](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.7)
