### ISSUE TITLE
[Enhancement]: Include seriesID in "Book Minified"

### ISSUE THREAD

**Issue by rasmuslos** [advplyr/audiobookshelf#1222]
### Describe the feature/enhancement

The Book minified schema already has a field called "seriesName". It would be really useful to include a field "seriesId". This would allow applications to link to the series page when displaying its name

**Comment by advplyr** [comment]
seriesName is a comma separated string of all the series names.

**Comment by advplyr** [comment]
To support this we might as well return the full array of series but I would prefer keeping this as slim as possible. It isn't needed in the clients right now so I'll close this.
