### ISSUE TITLE
Add an option to copy a collection to a new or an existing playlist[Enhancement]: 

### ISSUE THREAD

**Issue by Toblun** [advplyr/audiobookshelf#1226]
### Describe the feature/enhancement

Add an option to copy a collection to a new or an existing playlist.

**Comment by advplyr** [comment]
Added in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)

This is only for creating a playlist from a collection. For adding to an existing playlist we will have to wait until the ability to multi-select collection items is added. There is another request open for that.
