### ISSUE TITLE
[Bug]: Purge options missing from mobile browser

### ISSUE THREAD

**Issue by NeuralMiner** [advplyr/audiobookshelf#1228]
### Describe the issue

Hello,
When using a mobile browser (Firefox on Android), the options to purge cache don't show up. No issue on desktop Firefox. 
![Screenshot_20221128-083444](https://user-images.githubusercontent.com/20843698/204318711-e507a0d0-61fd-4bf2-9b6b-7031ee5cce9d.png)

### Steps to reproduce the issue

1. Open site in mobile browser.
2. Browse to settings. 

### Audiobookshelf version

v2.2.5

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.7](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.7)
