### ISSUE TITLE
Bug: Progressbar does not scale when the window is resized

### ISSUE THREAD

**Issue by juriroemer** [advplyr/audiobookshelf#123]
Steps to reproduce:

1. Open audio book player
2. Resize window (x-axis)

Browser: Chrome v. 94.0.4606.81 (arm64)
OS: macOS 11.6

Pictures:
![initial size](https://user-images.githubusercontent.com/31971585/138528148-4a485d1b-b504-4f5b-80d4-96f1e65abc78.png)
![0.5x size](https://user-images.githubusercontent.com/31971585/138528213-716287a1-e50a-4fe0-bd46-9a41573c63c0.png)
![2x size](https://user-images.githubusercontent.com/31971585/138528235-39d2d491-1b0a-4c9f-800d-5b6d9c7820ae.png)

**Comment by advplyr** [comment]
Fix included in release [v1.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v1.5.0)

Nice catch!

**Comment by B0rax** [comment]
I noticed that the chapter markers are still not resized when the page is resized.

Version V2.8.0
Browser: Safari 17.0 on macOS 12.6

**Comment by advplyr** [comment]
Thanks, opened a new issue
