### ISSUE TITLE
[Bug]: Server not accessible when connected over OpenVPN 

### ISSUE THREAD

**Issue by galaxyfar** [advplyr/audiobookshelf#1233]
### Describe the issue

With recent v2.2.6 release, Android app [v0.9.59-beta] can not connect to the local server over 4/5G through OpenVPN. 

All other services all accessible, so there is no issue with OpenVPN or local server hosting the AudiobookShelf.

One useful pointer, if it helps, is if OpenVPN is connected already locally through WiFi and then transitions to 4/5G when away from home, streaming seems to works just fine. But once disconnected, it fails to reestablish fresh connection to the AudiobookShelf server. So, something to do with login/authentication with latest release because this was not an issue with prior release.

### Steps to reproduce the issue

1. Audiobookshelf 2.2.6 release docker image
2. Android v0.9.59-beta
3. OpenVPN connection to local server over 4/5G
4. Launch App, it will fail to login and ask to select different server (even though all the server details and credentials are correct)

### Audiobookshelf version

 v2.2.6 

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
With recent release you mean the recent server release right?

Are you able to connect to the server via the mobile browser?

I just double checked the most recent release did not change anything with authentication.

**Comment by galaxyfar** [comment]
> With recent release you mean the recent server release right?

Correct, the server release. It must be recent because I never had issues in the past when using OpenVPN. But as I'm thinking this through, there was app update last month too, so there is that.

> Are you able to connect to the server via the mobile browser?

Just tried with mobile browser over OpenVPN, yes, it is accessible, no problem.

Additional debug info, just reverted [v0.9.59-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.59-beta) to [v0.9.57-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.57-beta). Interestingly, after entering login/server credentials for the first time over OpenVPN, it presented all my audiobooks but once I relaunched the app, it starting behaving same as v0.9.59-beta, "Audiobook server not connected", all the while server is still accessible from mobile browser.

**Comment by hobesman** [comment]
Perhaps an issue with dns requests not using the VPN? If you can continue a connection but not start one, what other communications are involved with starting a connection but aren't used to maintain it?

**Comment by advplyr** [comment]
I'm not sure that this is an issue with Abs but I also don't know what to troubleshoot here.
If you disable OpenVPN and it works then it would seem it is something with your network setup.

**Comment by galaxyfar** [comment]
> Perhaps an issue with dns requests not using the VPN? If you can continue a connection but not start one, what other communications are involved with starting a connection but aren't used to maintain it?

Good observation. I think you could be right about DNS, as I was mucking around with that recently. But the fact that Jellyfin and Navidrome have zero issues accessing the server that's also hosting Audiobookshelf makes be believe could there is more to it than my local network or DNS. Will poke around more and report back if I find anything interesting.

Thanks everyone for chiming in.

**Comment by lincolnep** [comment]
FYI I have this exact setup and I am not having any issues.

I am using ip address and never use dns to access it.

**Comment by advplyr** [comment]
Will close this until we can find something in Abs we need to fix. You can also join the discord or matrix server that is active and has users with all types of setups.
