### ISSUE TITLE
[Bug]: Multi-select visually selects multiple books but doesn't actually select

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#1236]
### Describe the issue

In the browser, you can use Shift-Click to select multiple items, but at the top it still says "1 Items Selected" and when you try to edit multiple, it brings up the multi-edit page but only lists one book.

### Steps to reproduce the issue

1. Shift+click to select multiple books.
2. Observe the number at the top still says 1 items selected
3. Click edit.
4. Observe that only one item is shown for editing.

### Audiobookshelf version

2.2.7

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.8](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.8)
