### ISSUE TITLE
[Bug]: Save button for Chapters does not appear after using lookup

### ISSUE THREAD

**Issue by ceramicwhite** [advplyr/audiobookshelf#1237]
### Describe the issue

The Save button on the Chapter editor I see has been changed to only show once an actual change has been made but when populating chapters via Lookup with ASIN adv is not registering a change has been made and the Save button won't appear.

Quick workaround for now once populated is add a chapter or one character to a chapter, delete it, then save.

### Steps to reproduce the issue

1. Use Lookup by ASIN to populate Chapters
2. Apply Chapters
3. Save button will not appear

### Audiobookshelf version

v2.2.7

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.8](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.8)
