### ISSUE TITLE
[Enhancement]: show the name of the series on the border of the shelf

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf#1239]
### Describe the feature/enhancement

in mobil App the name of the series is visible on the border of the shelf.
would be fine same way in WebApp. You see the name only when move over with the mouse
![image](https://user-images.githubusercontent.com/72630160/205109466-51291690-41c7-47a7-ab7d-09f513f7fc81.png)

**Comment by advplyr** [comment]
Fixed in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)
