### ISSUE TITLE
[Enhancement]: List of random books

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#1240]
### Describe the feature/enhancement

One feature I kind of liked on Booksonic web interface was that it has an option to show a dozen or so (or more?) random books from the library, and it would change on an interval. So every 30 seconds or minute or whatever the list would refresh and a new random set of books would appear.

I think a "similar books" recommendation is good but doesn't expose you to as many things you wouldn't think to look for. So I think there's room for both features, and in some ways the completely random list might be easier to implement. 

Maybe just have a row on the home screen called "Random" and have a different random selection appear each time the home screen loads.

Alternatively, or in addition, have an option to sort the library in a random way. Currently most of the sort options only expose the same handful of books every time I use them (except for recently added) but that only shows the books I already have in mind since I just added them.

**Comment by advplyr** [comment]
I missed this one. The random shelf was added earlier this year with the name "Discover"
