### ISSUE TITLE
[Enhancement]: Support Subfolder Scanning for Audiobooks

### ISSUE THREAD

**Issue by Eschguy** [advplyr/audiobookshelf#1242]
### Describe the feature/enhancement

Allow for subfolders, supporting "Books/Author/Series/Book_Title/Book_File" to allow us to keep folders organized.

**Comment by hobesman** [comment]
I'm not sure I understand. How is this different from what it currently does?

**Comment by Eschguy** [comment]
For me it isn't seeing the books that are in my Books folder if they're in subfolders. 
Books/book.mp3 works
Books/Author/book.mp3 does not
Books/Author/Series/book.mp3 does not
