### ISSUE TITLE
[Bug]: Surrounding whitespace is included when editing chapter names

### ISSUE THREAD

**Issue by Weldawadyathink** [advplyr/audiobookshelf#1248]
### Describe the issue

When editing chapter names, if there is whitespace included before or after the chapter name, it is not removed. The whitespace should be removed. 

### Steps to reproduce the issue

1. Open a book
2. Edit Chapters
3. Include whitespace in the chapter
4. Save
5. Edit again, to confirm whitespace is still present

### Audiobookshelf version

v2.2.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Updated in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)
