### ISSUE TITLE
[Bug]: Embed Metadata doesn't change cover

### ISSUE THREAD

**Issue by SkippyTheMonkeyKeeper** [advplyr/audiobookshelf#1252]
### Describe the issue

In audiobookshelf I swapped the original Audible cover with a cover without the "Only on Audible" part. When I use the Embed Metadata function I expect the cover in the file to change to the clean cover, but upon checking the file it still contains the original cover with the ugly "Only on Audible" part.

### Steps to reproduce the issue

1. Have an audiobook with a cover
2. Change the cover in audiobookshelf
3. Use to Embed Metadata function
4. Check if the cover is updated or not

### Audiobookshelf version

v2.2.8

### How are you running audiobookshelf?

Docker

**Comment by jmt-gh** [comment]
Can you provide a bit more info? Are these MP3s? M4Bs?

**Comment by advplyr** [comment]
I was looking for this GH issue yesterday but I couldn't find it. I fixed this for the next release with this commit:
https://github.com/advplyr/audiobookshelf/commit/f7a3dbf209cee0316a27b3318ce00c831e157362

**Comment by opswhisperer** [comment]
Came here looking for this, glad it's already fixed. Is there an ETA for release?

**Comment by advplyr** [comment]
Fixed in [v2.2.13](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.13)
