### ISSUE TITLE
[Enhancement]: Audiobook RSS feed audio track pub date - Revert #952

### ISSUE THREAD

**Issue by Jumbs** [advplyr/audiobookshelf#1253]
### Describe the feature/enhancement

Please Revert #952 back to #888.

While #952 provides a visible order when importing a podcast, it renders it unplayable on iphone.
If you sort oldest to newest or newest to oldest, it plays backwards under both options.

Thanks

**Comment by advplyr** [comment]
Can you elaborate? Why is it unplayable? Does the podcast app show what the pubDate is?

**Comment by Jumbs** [comment]
So the correct use on iPhones, after #888 is restored is to:

- Scroll to the bottom of the list and hit chapter 1.
Or
- Visually Resort (settings for feed) Chapter 1 to the top then hit play.

**Comment by advplyr** [comment]
Updated in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)
