### ISSUE TITLE
[Enhancement]: Add an "open in bookplayer" URL on books

### ISSUE THREAD

**Issue by taxilian** [advplyr/audiobookshelf#1264]
### Describe the feature/enhancement

There is an excellent audiobook player called ["BookPlayer"](https://github.com/TortugaPower/BookPlayer) which I sometimes like to use -- particularly while the one with audiobookshelf is still young. The main downside to it is that it's hard to get books into it.

One of the things it supports is [opening via a URL](https://github.com/TortugaPower/BookPlayer/wiki/URL-scheme) e.g. `bookplayer://download?url="https://link-to/your/file.mp3"`

It would be great if we could add that to books in audiobookshelf; it would probably only work properly when there is a single file m4b or similar, but that's common enough that is seems like it'd be a useful thing.

The main "gotcha" for this is that the URL would need to bypass authentication; my thought would be to include a JWT in the URL for authentication which had an expiration.

I'd be happy to assist with implementing this but while I know node.js and javascript quite well I'm not super familiar with nuxt -- I'd need someone to point me in the right direction for adding the backend token / auth changes at the least

**Comment by keaganhilliard** [comment]
Can it use the rss feature? You can open an audiobook as an RSS and it's not authenticated. That gives you urls that you can use to download the files.

**Comment by taxilian** [comment]
> Can it use the rss feature? You can open an audiobook as an RSS and it's not authenticated. That gives you urls that you can use to download the files. You can then close the RSS when you are done.

Interesting question -- I am not familiar with that feature, so I'll play with it. If nothing else the auth mechanism may be able to be reused

**Comment by advplyr** [comment]
I don't understand this. Is this for the mobile app or the website?
Are you suggesting a button to open the BookPlayer app with the audio file from Abs?

**Comment by taxilian** [comment]
This would be for the mobile app; all it would need to do is open the link the same way e.g. safari would and if the app is installed then it would download it into BookPlayer.

I wouldn't expect you'd want to leave it there all the time and so it might make sense to make it a feature that can be toggled -- optionally an advanced feature where you can customize it for other similar players, assuming there are some? 

But yes, to be clear it would open the bookplayer app with the audio file from Abs

**Comment by advplyr** [comment]
I would prefer to improve the existing Abs mobile apps then to link to other mobile apps. 

If we ever get around to building out some form of a plugin system this seems like more of a plugin then a core feature.

Also for future requests the mobile apps have their own repo https://github.com/advplyr/audiobookshelf-app

**Comment by taxilian** [comment]
To be clear, this request was not to add something to the mobile app, it was to add something to the web app -- which is why I submitted the request in this repo and not in the other one. I absolutely agree that putting a link to a different audiobook app in the audiobookshelf app would be silly.

Perhaps this is a philosophical question; to me the `audiobookshelf` server is a library for audiobooks and the `audiobookshelf-app` is the recommended way to use it. That's great, but I don't see any reason that it should exclude the option of using other apps for those who want to do so. I don't see this as being relevant to or related to the current app.

**Comment by advplyr** [comment]
> Perhaps this is a philosophical question; to me the `audiobookshelf` server is a library for audiobooks and the `audiobookshelf-app` is the recommended way to use it. That's great, but I don't see any reason that it should exclude the option of using other apps for those who want to do so. I don't see this as being relevant to or related to the current app.

Correct, the Abs mobile apps are just mobile clients that can be used with an Abs server. Currently there are no other Abs mobile client apps in production. I know there are some in development.

The app you are referring to will not sync progress with the Abs server which will likely cause confusion as to why there is an option to use a mobile app that won't sync with Abs. As you mentioned, the URL to open the app supports a single audio file which would create more of an obstacle with the UI/UX. So we are restricted with single file audiobooks, the progress does not sync to the server, it only benefits a small percentage of users who use that specific app and it requires taking up space in the UI.
