### ISSUE TITLE
[Enhancement]: RSS feeds for book series

### ISSUE THREAD

**Issue by Weldawadyathink** [advplyr/audiobookshelf#1265]
### Describe the feature/enhancement

Support rss feeds for entire series of books. With long book series, it would be helpful to support exporting the entire series as a single rss feed.

**Comment by advplyr** [comment]
This is related to #606

I made a comment there on how this would behave with multi-track audiobooks https://github.com/advplyr/audiobookshelf/issues/606#issuecomment-1131709004
since each audio file will need to be a different episode.

**Comment by advplyr** [comment]
Added in [v2.2.12](https://github.com/advplyr/audiobookshelf/issues/606)
