### ISSUE TITLE
[Bug]: Overlapping folder view in library editor overlay 

### ISSUE THREAD

**Issue by Blindie92** [advplyr/audiobookshelf#1266]
### Describe the issue

In the edit overly of an library the folder list overlapping with the search button and the border of the overlay

![Screenshot 2022-12-13 214433](https://user-images.githubusercontent.com/94938390/207439717-991fe779-c714-4003-a254-139518e77848.png)

### Steps to reproduce the issue

1. Edit a Library
2. add a bunch of folder, so there is not enough space to show all folder in one page

### Audiobookshelf version

v2.2.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)
