### ISSUE TITLE
CD directory structure

### ISSUE THREAD

**Issue by juriroemer** [advplyr/audiobookshelf#127]
Is there a way or any plans on supporting a CD directory structure? CD ripped audio books mostly come in a structure like this:

```
-> Author
  -> Book title
     -> CD 1
     -> CD 2
     -> CD 3
```

Right now if you use this structure, you will get an idividual "audio book" in the UI for each CD. Throwing all the mp3's imto the "book title" folder only works if you sort the tracks by hand, because all individual CD's start their track ID's from 1.

**Comment by advplyr** [comment]
Supporting the CD ID3 and CD field in general is still planned. I'm making #155 the main thread for that update.
