### ISSUE TITLE
[Bug]: sort order didnt keep in series tab

### ISSUE THREAD

**Issue by Blindie92** [advplyr/audiobookshelf#1272]
### Describe the issue

abs didnt keep sort order in series tab when i hit the back button.

### Steps to reproduce the issue

1. Go to series tab
2. chase any sort order and revert it
3. klick on a series
4. hit the browser back button to go back to the sereies overview
5. sort item is the same, but reverted sort order is back to default.

### Audiobookshelf version

v2.2.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)
