### ISSUE TITLE
[Enhancement]: Remember which metadata items are enabled/disabled in "Match"

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1276]
### Describe the feature/enhancement

When I edit books and use the "Match" function I need ABS to remember which metadata-items I uncheck.

I never want ABS to add genres or tags f.ex. Every time I "Match" a book I need to uncheck those two items

**Comment by advplyr** [comment]
Added in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)
