### ISSUE TITLE
[Bug]: Unclear UI when adding series to a book

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1277]
### Describe the issue

When I add a series and sequence to a book and then click "Save", it's not actually saved. I need to click Save again in the Details view

### Steps to reproduce the issue

1. Open up a book
2. Click the edit button
3. Click the + in the series field
4. Enter a name and sequence number
5. Click save
6. Close the details-window by clicking outside it
7. Click the edit button
8. The just added series is not saved

### Audiobookshelf version

2.2.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Updated in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)
