### ISSUE TITLE
[Bug]: Toaster popup when scanning the library obscures menu

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1279]
### Describe the issue

When you initiate a scan in ABS, the toaster popup obscures the sorting menu, see attached screenshot
[screenshot](https://i.imgur.com/OVlDUs3.png)

### Steps to reproduce the issue

1. Initiate a scan
2. Click the sorting menu in the top right

### Audiobookshelf version

2.2.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Adding a note here for searching that this scan toast notification will be moved to the tasks dropdown as mentioned https://github.com/advplyr/audiobookshelf/issues/1900#issuecomment-1626278264

**Comment by advplyr** [comment]
The toast notification was removed in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)
