### ISSUE TITLE
Enhancement: Automatically sort tracks in track manager

### ISSUE THREAD

**Issue by juriroemer** [advplyr/audiobookshelf#128]
Right now the track manager (where you can rearrange the tracks of an audiobook) shows "Track Parsed from Filename" and "Track From Metadata", but you still have to sort the tracks by hand if you want to use one of these arrangements.

Automatically arranging the list by clicking on the preferred table header would save a lot of dragging and dropping (kind of related to #127, because this is where a lot of rearranging is required. Although auto sorting isn't always possible in that case).

Really love this project, hope it doesn't seem rude that I'm opening all these "issues"! :)

**Comment by jarrodCoombes** [comment]
This is great!!!

One other suggestion I would add is to make the column headings static when you scroll down the list so that they are always visible. I find I forget which column is which almost as soon as that line goes off the screen.
