### ISSUE TITLE
[Bug]: Author edit, UI inconsistency

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1280]
### Describe the issue

When editing an author, the button for saving is named "Submit". When editing books, saving is "Save"

### Steps to reproduce the issue

1. Open up an author for editing

### Audiobookshelf version

2.2.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Updated in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)
