### ISSUE TITLE
[Bug]: Series, Library view, UI inconsistency

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1281]
### Describe the issue

When you open up a series, you get a checkbox to the left of the "Mark Series Finished" button with an option to collapse the series. That option doesn't make any sense in the series view.

It doesn't seem to be connected to the same checkbox in the Library view. You can have one of them checked and the other unchecked

### Steps to reproduce the issue

1. Open up a book series

### Audiobookshelf version

2.2.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
It is for collapsing sub-series if you have one large series encompassing many small ones.
See here: https://github.com/advplyr/audiobookshelf/pull/1105#issuecomment-1302104766
