### ISSUE TITLE
[Bug]: Series Windows loads behind book detail page

### ISSUE THREAD

**Issue by ceramicwhite** [advplyr/audiobookshelf#1289]
### Describe the issue

Trying to add a  book to a series, the series window loads behind the current book details page

### Steps to reproduce the issue

1. Click the Edit button on a books cover
2. Click + to Add series
3. Page seems to be unresponsive but actually the series page has loaded behind details window.

### Audiobookshelf version

v2.2.9

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.10](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.10)
