### ISSUE TITLE
[Bug]: Selection of narrator behind the editing window

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1295]
### Describe the issue

If you are editing an audiobook and want to change or add a new narrator, the selection window of the already existing narrators is behind the actual editing window so that a selection is not possible.  The same procedure works in batch mode.

### Steps to reproduce the issue

1.  Select audiobook and Edit metadata
2. Change narrator
3. See bug

### Audiobookshelf version

2.2.10

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.11](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.11)
