### ISSUE TITLE
[Bug]: Libraries intermittently/not at all being detected in Web UI

### ISSUE THREAD

**Issue by chyron8472** [advplyr/audiobookshelf#1296]
### Describe the issue

I have 3 libraries. After upgrading to 2.2.10, ABS' web UI either only ever detects the first library or else detects none of them. Sometimes when I go to the Library tab, I am redirected to http://localhost:13378/oops?message=Library%20not%20found.

Downgrading to 2.2.9 does not fix the issue.

Downgrading 2.2.8 DOES fix the issue.

### Steps to reproduce the issue

1. Upgrade to v2.2.9 or v2.2.10
2. 

### Audiobookshelf version

2.2.9

### How are you running audiobookshelf?

Docker

**Comment by chyron8472** [comment]
Fixed. It was either a permissions problem (fixed by temporarily enabling Access All Libraries") or else it was a problem with my login session (fixed by logging out/in.)

**Comment by advplyr** [comment]
Fixed in [v2.2.11](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.11)

**Comment by BombusAlpinus** [comment]
can confirm that it is working again, thanks for the fast fix. My kids really appreciate it ;)
