### ISSUE TITLE
[Bug]: When installing PWA with Google Chrome on Windows 11, the app has no icon

### ISSUE THREAD

**Issue by jberlyn** [advplyr/audiobookshelf#1300]
### Describe the issue

When I installed Audiobookshelf as a PWA using Google Chrome on Windows 11, no icon is included with the installation, therefore it just has an icon with the letter A.

No icon when installing inside Chrome:
![image](https://user-images.githubusercontent.com/10014944/208588376-ae424657-d296-41d6-ac80-8060ff772a3d.png)

No icon in the Windows 11 start menu:
![image](https://user-images.githubusercontent.com/10014944/208588424-2125b157-7e03-4b8b-be2b-4e31932526bd.png)

I am fairly sure the icon just needs to be specified in the the `manifest.json` for the server web app.

### Steps to reproduce the issue

1. Go to the installed copy of Audiobookshelf
2. Install as a PWA using the button on the address bar in Google Chrome on Windows 11
3. See that no icon is included with the installation, just a letter A on the icon

### Audiobookshelf version

v2.2.11

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
