### ISSUE TITLE
[Bug]: Unable to change scheduled backup time 

### ISSUE THREAD

**Issue by imcdona** [advplyr/audiobookshelf#1304]
### Describe the issue

Clicking the pencil icon to change the scheduled backup time does nothing. 

### Steps to reproduce the issue

1. Login to ABS as an admin user
2. Navigate to the Backups options
3. Click the pencil icon to change the scheduled backup time
4. Note that clicking on the pencil doesn't do anything. 

### Audiobookshelf version

v2.2.10

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Oops. This was accidently removed in https://github.com/advplyr/audiobookshelf/pull/1221

**Comment by advplyr** [comment]
Fixed in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
