### ISSUE TITLE
[Bug]: Appending a series to multiple files causes multiple of the same series to be generated.

### ISSUE THREAD

**Issue by baconcow** [advplyr/audiobookshelf#1305]
### Describe the issue

Appending a series to multiple files causes multiple of the same series to be generated.

Notes:
- After appending, each of the 21 files had the same series name, but were not part of the same series within the "Series" page.
- There was another series already present. Removing this series did not allow the newly appended series to group together.
- There appears to be a single space before each of the series' names. 
- I replaced each of them manually to workaround the issue.

### Steps to reproduce the issue

1. Selected 21 files and went to edit them.
2. Made a series for the files and clicked "Append" and "Apply".
3. Saved the files.

The following is an image showing the issue:

![image](https://user-images.githubusercontent.com/11164879/208797272-db2b7e38-0f16-4ebe-91b1-459b8657a5f4.png)

### Audiobookshelf version

v2.2.11

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I think I have an idea of what could have happened. If your audio files had a series tag with a space in from like " Aubrey & Maturin" then this would have gotten saved with that space.

When adding a series from inside Abs white space gets removed. I just added an update for next release that will also remove white space from meta tags.

**Comment by advplyr** [comment]
Updated in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
