### ISSUE TITLE
[Enhancement]: m-TAGS alternative metadata

### ISSUE THREAD

**Issue by TechLoom** [advplyr/audiobookshelf#1308]
### Describe the feature/enhancement

I'm looking to update the metadata without changing the checksum to the files.

I know this would be a very low priority as the use case isn't for all users. In my case, I'm seeding audio files with rtorrent, and updating the metadata will change the checksums causing the files to redownload, (aka undoing the metadata changes).

http://www.m-tags.org/

m-TAGS is just alternative metadata that is a separate file containing the metadata with the same name as the audio file.

Allowing this alternative metadata would mean I could fix issues within Audiobookshelf not IDing correctly and still seed the audio files as the checksum would not change.

**Comment by Weldawadyathink** [comment]
Audiobookshelf by default does not edit the file. It stores metadata either in the /metadata directory set on the server or, optionally, in the same folder as a separate file. It only writes the metadata to the file if you use the embed metadata feature. Is this suitable for your setup?

**Comment by advplyr** [comment]
I think this is a misunderstanding since Abs does not modify your audio files. A separate metadata file is kept for each book/podcast which you can optionally store in the same directory as the media files.
