### ISSUE TITLE
[Enhancement]: Recommend making the activity ring clickable

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#1309]
### Describe the feature/enhancement

Audiobookshelf has become amazing! Full stop. 

Thank you for building it!

I have slight ui/ux tweak to suggest. I started an M4B task and read that I was able to navigate away from that page. I see the little activity ring going and expected to be able to click it and have it take me back to the thing it's working on (my M4B job). But, instead it does nothing.

![image](https://user-images.githubusercontent.com/25695143/209214958-3046fe63-54db-4384-8289-60b472af1794.png)

Could we make that ring take you to the M4B page again?

**Comment by Blindie92** [comment]
The problem is when you start mutible converting tasks, where to go then?

**Comment by advplyr** [comment]
The idea with this is that all background tasks will be shown in the toolbar so clicking that would be a menu that drops down with all of the running tasks.
Library scans for example would also show there. I just put a spinner up there to get started.
