### ISSUE TITLE
[Bug]: Unable to manually update author profile Photo Path/URL

### ISSUE THREAD

**Issue by Gajotres** [advplyr/audiobookshelf#1317]
### Describe the issue

In previous versions, when editing the author Photo Path/URL I was always able to manually add a new photo to **/metadata/authors/** folder and have it shown in the application front-end.

Now, no matter what I do, the application is not using the photo location manually provided in the Photo Path/URL.

### Steps to reproduce the issue

1. Add any audiobook where Audiobookshelf can pull the author's photo 
2. Create/Download a new author photo and upload it to **Metadata/authors** folder
3. In the left menu, click Authors, and find the previously added author. Edit said author and update the **Photo Path/URL** filed with the new custom author photo (for example, /metadata/authors/new_author.jpg)
4. This change will not reflect in the Audiobookshelf UI (while it was working in previous versions)

### Audiobookshelf version

2.2.11

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
