### ISSUE TITLE
[Enhancement]: Normal scan and force complete scan for Author??? 

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1323]
### Describe the feature/enhancement

I recently started updating the authors of my audio books. I noticed that there is not the same logic in this area (normal scan and force complete scan) as with the libraries. Here there is only a complete new scan of all authors, which overwrites the author information and images I added manually.

My suggestion would be to introduce the same logic for the authors as for the libraries. That is, a normal scan in which only authors who do not yet have any information are updated and then a complete scan in which all authors are updated, regardless of whether they have information or not.

**Comment by advplyr** [comment]
I'm not entirely sure what you mean. Can you give reproduction steps on overwriting author information?

Author information shouldn't get overwritten
