### ISSUE TITLE
[Enhancement] Pull "ASIN" from OPF fIle

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#1330]
### Discussed in https://github.com/advplyr/audiobookshelf/discussions/1329

<div type='discussions-op-text'>

<sup>Originally posted by **Gru0810** December 28, 2022</sup>
I use opf-File to transfer Infos to ABS. With this way I'm able to transfer the "ISBN" by using the following line in opf-File:
<dc:identifier id="BookId" opf:scheme="ISBN">9783844541236</dc:identifier>

I tried following line :
<dc:identifier id="BookId" opf:scheme="ASIN">3844541357</dc:identifier>
</div>

**Comment by superpawko** [comment]
Please add also Subtitle functionality.

<dc:subtitle>Here goes subtitle</dc:subtitle>

**Comment by advplyr** [comment]
Added in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
