### ISSUE TITLE
[Enhancement]: View Podcast download Queue

### ISSUE THREAD

**Issue by aurokon** [advplyr/audiobookshelf#1331]
### Describe the feature/enhancement

Would be pretty nifty to be able to see what's queued up to be downloaded for our podcasts

**Comment by advplyr** [comment]
What do you mean? Can you share more details and how you think it should designed?

**Comment by aurokon** [comment]
Just a window with a list of what's waiting to be downloaded with some buttons to stop/cancel/pause/start the downloads. Nothing special.
