### ISSUE TITLE
[Bug/Usability]: Hidden Settings Menu

### ISSUE THREAD

**Issue by lkiesow** [advplyr/audiobookshelf#1334]
### Describe the issue

If you limit the screen _height_ for audiobookshelf the main settings menu is hidden and there is no obvious way to open the menu. For me, the only way to access this was unrecognizable.

### Steps to reproduce the issue

- Open Audiobookshelf
- Go to settings
- Limit browser height

https://user-images.githubusercontent.com/1008395/209881189-5b1f912f-5155-47fa-bb37-93183cdf7161.mp4

### Audiobookshelf version

v2.2.11

**Comment by advplyr** [comment]
Fixed in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
