### ISSUE TITLE
[Enhancement]: Account for poorly formatted series data from Audible

### ISSUE THREAD

**Issue by Weldawadyathink** [advplyr/audiobookshelf#1339]
### Describe the issue

Some books in Audible have the series formatted as "Series #Book 1". When matching with audiobookshelf, this gets turned into a series called "Series #Book 1", with no sequence number for the book. It should be formatted to "Series", book number 1. For example, the Inheritance Cycle by Christopher Paolini. Books 2-4 get correctly placed in "The Inheritance Cycle" with the correct sequence number. Book 1, Eragon, gets placed into a separate series called "Inheritance Cycle #Book 1". 

### Steps to reproduce the issue

1. Match any library item that has this issue in the audible database. 

### Audiobookshelf version

v2.2.11

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Ah yeah I see. This appears to be just bad formatting on Audibles side but we can add an additional check in `AudibleProvider .js`to clean that up.

**Comment by advplyr** [comment]
Updated in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
