### ISSUE TITLE
[Bug]:  Unable to parse book in folder 'Machine'

### ISSUE THREAD

**Issue by andrewinmoco** [advplyr/audiobookshelf#1340]
### Describe the issue

Audiobookshelf was unable to parse/import an audiobook when the folder was titled "Machine" when the folder was renamed to anything else (Machine_book) it was imported without error. 

I'm running the ghcr.io/advplyr/audiobookshelf:latest container. current version 

Logs on upload to machine:

2022-12-29 18:51:54

INFO

[Server] 22 Files Changed

2022-12-29 18:51:54

WARN

[Scanner] Some files were modified in a parent directory of a library item "undefined" - ignoring

2022-12-29 18:51:54

ERROR

[Utils] Failed to get ino for path /audiobooks/Machine/Machine Error: ENOENT: no such file or directory, stat '/audiobooks/Machine/Machine'

2022-12-29 18:51:54

ERROR

[fileUtils] Recurse files error Error: ENOENT: no such file or directory, scandir '/audiobooks/Machine/Machine/'

2022-12-29 18:51:54

ERROR

[fileUtils] Failed to getFileTimestampsWithIno Error: ENOENT: no such file or directory, stat '/audiobooks/Machine/Machine'

2022-12-29 18:51:54

WARN

[Scanner] Library item has no media files "/audiobooks/Machine/Machine"``

After renaming folder 
``2022-12-29 18:52:11

INFO

[Server] 21 Files Changed

2022-12-29 18:52:11

INFO

[parseOverdriveMediaMarkers] Parsing of Overdrive Media Markers started

2022-12-29 18:52:11

INFO

[Book] Overdrive Media Markers and preference found! Using these for chapter definitions

2022-12-29 18:52:12

INFO

[Server] Socket B4bCZvuBz_emKf-AAAAJ disconnected from client "root" after 193521ms (Reason: transport close)

2022-12-29 18:52:13

INFO

[Server] Socket Connected mGET3TLLoCn7glvDAAAP``

### Steps to reproduce the issue

1. 

### Audiobookshelf version

v2.2.11

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Did you get this resolved?
I saw some discussion on Discord. This doesn't have to do with the name "Machine" so I'm going to close this out but let me know if you're still having issues.

**Comment by andrewinmoco** [comment]
@advplyr : It's still happening for me but I've got a workaround for now.  There was discussion that it might be something odd related to an ext4 filesystem.   No objection to closing, mainly sharing for visibility in case others are having the same issue.
