### ISSUE TITLE
[Usability/Accessibility]: Mouse dependent buttons in library settings

### ISSUE THREAD

**Issue by lkiesow** [advplyr/audiobookshelf#1342]
Going to `Settings` → `Libraries`, a user can modify a library or trigger actions run on the library. Unfortunately, for the action buttons/icons to available, you have to select the library first. Usually this means hovering over the library with a mouse. This can be problematic on a touch interface (e.g., on a tablet) or when using keyboard navigation and a screen reader.

On Android, it seems users can still access this if they click the library, but this is not obvious to anyone since there is no indicator that users can click these.

More than that, the mix of different button styles and icons feels a bit weird. I don't think it is deliberate but just happened, but as a user I did wonder what the different styles mean.

![Screenshot from 2022-12-30 18-07-33](https://user-images.githubusercontent.com/1008395/210099534-e020707a-31a8-473c-9ee9-a3c68923ef0e.png)

As an alternative, I propose to switch to a simple actions menu instead. This will not only enforce a common style for all actions but also means that the lines do not get too crowded, regardless of the number of options. The drawback is that the options are slightly harder to access on a desktop, but this shouldn't really matter since I don't expect users to use them very often. How often do you delete a library after all?

The user interface could look somewhat like this:

![Screenshot from 2022-12-30 18-08-48](https://user-images.githubusercontent.com/1008395/210099590-e81fd1e8-dd1b-4d50-b3af-99bcd335e385.png)

What do you think?

**Comment by advplyr** [comment]
Agree. On mobile this is sort of how it is already.

![image](https://user-images.githubusercontent.com/67830747/210153543-b47c2904-a211-4589-8e13-f44492d2fbe3.png)

**Comment by advplyr** [comment]
Updated in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
