### ISSUE TITLE
[Bug]: Series being created incorrectly.

### ISSUE THREAD

**Issue by baconcow** [advplyr/audiobookshelf#1345]
### Describe the issue

After scanning books, some of the books are having their series tagged with the author's name. This data is not part of the files embedded tags or the intended folder structure. All other tagged series appear to be handled correctly, without their author's having separate series under their names. I believe it is only doing this for authors that do not have any other books in a series.

### Steps to reproduce the issue

1. Scan books.
2. A series is created with the author's name for a book that does not have an embedded series tag or intended to be in a series based on the folder structure.

I have attached a screenshot which shows four (4) series that have been created using an author's name.

![image](https://user-images.githubusercontent.com/11164879/210152749-d11e4464-b913-49fa-9d0a-ddc7c0e3e5d0.png)

### Audiobookshelf version

v2.2.11

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
There are only 2 ways that this can happen.
1. Your folder structure is such that the author name is where it expects the series name
2. You have the authors name embedded in the series ID3 tag

Since you already ruled out 2 then it must be 1.
Check the directory structure again shown here https://www.audiobookshelf.org/docs#book-directory-structure

If you are still not sure then please share your full directory structure

**Comment by baconcow** [comment]
Here is my directory structure. I have used the following in Docker, for the "audiobooks" directory and the default settings within ABS:
"I:\Audiobooks\Audiobookshelf\audiobooks:/audiobooks -v"

Each author has their own folder. The authors without a series all have series created with their name.

![image](https://user-images.githubusercontent.com/11164879/210153921-4e16dcd2-61ef-41d9-8e33-49d1e6c14999.png)

**Comment by advplyr** [comment]
You are only showing part of the directory structure. Can you show the directories inside "Alighieri"?

**Comment by baconcow** [comment]
Just updated my previous comment with further supporting images.

**Comment by advplyr** [comment]
Can you remove that book from Abs and do a regular scan on that library again?

To remove just press edit and use the red button on the bottom left.
![image](https://user-images.githubusercontent.com/67830747/210175833-1a6b03dc-74f5-4da2-84fb-6a66d50264a0.png)

After you re-scan check if the series is still shown.
