### ISSUE TITLE
[Bug]: Item Metadata Utils "Please Wait" dialog does not display properly

### ISSUE THREAD

**Issue by cassieesposito** [advplyr/audiobookshelf#1346]
### Describe the issue

If you have a lot of tags or genera and you use the "Item Metadata Utils" page to rename or delete an item that affects many library items, the user feedback makes it look as though the system has hung rather than like it's working.

What you get is the screen going dark. There is a dialog box that appears halfway down the page, but unless you happen to be scrolled to the 50% mark, you can't see it. This dialog should be fixed to the center of the viewport rather than being relative to the page.

### Steps to reproduce the issue

1. Add enough different tags to library items that your viewport on the "Item Metadata Utils" interface will display fewer than half of them,
2. Navigate to Item Metadata Utils
3. Rename a tag

### Audiobookshelf version

2.2.11

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Fixed in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
