### ISSUE TITLE
[Enhancement]: Custom Sleeptimer

### ISSUE THREAD

**Issue by JAKAMI99** [advplyr/audiobookshelf#1357]
### Describe the feature/enhancement

Really love the app, but I am someone who uses sleeptimers a lot.

But I am really unhappy with the timers you can set in audiobookshelf and would love to have more options, especially in the area of "15min, 20min, 45min".
Or even better: A sleeptimer with custom minutes like on audible.

Thanks in advance, and thanks for the projekt.
Really love it!!!

**Comment by furiousM** [comment]
I am in the same boat. I'd love to have better sleep timer options! I don't even understand why there is a 10 sec timer??
Something between the 5 and 30 mins would be nice. Or ideally custom minutes as suggested by JAKAMI99 .

**Comment by advplyr** [comment]
Added in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)
