### ISSUE TITLE
[Bug]: Changing order of Authors won't allow entry to save

### ISSUE THREAD

**Issue by DieselTech** [advplyr/audiobookshelf#1361]
### Describe the issue

When changing the metadata properties for the Author field, changing the order that the authors are listed in results in it not saving because "No changes were made". This would be fine if the order they are in on the card didn't dictate the order they show up in on the book page. 

![image](https://user-images.githubusercontent.com/30128380/210643718-abc3a95d-1816-4018-93d7-623e4f177007.png)

### Steps to reproduce the issue

1. Edit book metadata
2. Change the position that authors are listed in the Author field
3. Press save

### Audiobookshelf version

2.2.11

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
