### ISSUE TITLE
Admin user has no access to settings

### ISSUE THREAD

**Issue by Maximilian85** [advplyr/audiobookshelf#137]
Admin user has no access to settings

root User
![AdminUser2](https://user-images.githubusercontent.com/76774860/138609052-beb70952-878e-4b46-9d43-58633d0050ce.PNG)

Admin User have no access
![AdminUser](https://user-images.githubusercontent.com/76774860/138609087-ce80ad21-0f6e-4529-9489-e0e6a4804b70.PNG)

**Comment by advplyr** [comment]
Admin user now has full access in [v2.0.10](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.10)
