### ISSUE TITLE
[Bug]: Folder structure when adding library is cached

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1371]
### Describe the issue

The folder structure being displayed when clicking "Browse for folder" when adding a library is cached until you reload the page.

### Steps to reproduce the issue

1. Add a new library
2. Click the "Browse for folder" button
3. Cancel adding the library
4. Adda a folder on the filesystem
5. Add a new library
6. Click the "Browse for folder" button
7. New folder is not visible

### Audiobookshelf version

v2.2.11

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Updated in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)
