### ISSUE TITLE
[Bug]: Transcode ALAC Support 

### ISSUE THREAD

**Issue by fidoriel** [advplyr/audiobookshelf#1372]
### Describe the feature/enhancement

Hey,

it would be very nice if audiobookshelf server would transcode ALAC to AAC, like FLAC in #70.
Currently ALAC seems supported on iOS and Safari. On other browsers like Firefox or Edge, the UI starts to liad/spin for ever, nothin happens. As a minimum I would expect that the WebUI throws an Error saying ALAC is not supported. But i would love to see support for it, migrating from iTunes to audiobookshelf/Jellyfin.
Thanks.

EDIT:
This is a Bug. .m4a extensions are officialy supported. So ALAC is supported, because using .m4a like aac. The transcode fallback does not work on non Apple Browsers, there might be someting wrong with content negotiation.

**Comment by advplyr** [comment]
Do you have a sample audio file I can use to test?

**Comment by fidoriel** [comment]
I tested the first ALAC file from here: http://www.hyperion-records.co.uk/testfiles.asp

Does work on iOS App, macOS Safari
Does not Work on Windows/macOS Firefox

**Comment by advplyr** [comment]
Fixed in [v2.2.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.12)

**Comment by fidoriel** [comment]
The fix is working fine since january. But there is an issue: If I listen to a audiobook which has no bookmark (saved position) it works fine. If it has it seeks indefinitely for the position and will never start.
