### ISSUE TITLE
[Enhancement]: More accessible options to refresh podcasts

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1373]
### Describe the feature/enhancement

Would be nice with a "update podcast feed" in the three dot menu on each podcast in the library view.

Also, when selecting multiple podcasts in the library view, there are options to Edit and Remove, an updated RSS feed option here too would be nice.

**Comment by advplyr** [comment]
What would "update podcast feed" do?

**Comment by ScuttleSE** [comment]
Same thing the "Check and download new episodes" button do when individually editing a podcast.

**Comment by apiweb** [comment]
> ### Describe the feature/enhancement
> Would be nice with a "update podcast feed" in the three dot menu on each podcast in the library view.
> 
> Also, when selecting multiple podcasts in the library view, there are options to Edit and Remove, an updated RSS feed option here too would be nice.

Could you give an example?
I couldn't understand the new feature.

**Comment by advplyr** [comment]
The auto-download new podcast episodes feature should cover this
