### ISSUE TITLE
[Enhancement]: open links from podcast show notes in new window

### ISSUE THREAD

**Issue by nellistc** [advplyr/audiobookshelf#1376]
### Describe the feature/enhancement

Clicking links in podcast notes opens the link in the current tab/window. If listening via the browser, this interrupts the playback.

Suggestion is to open links in a new window or at least have an option to enable this functionality.

**Comment by advplyr** [comment]
The show notes for a podcast are coming directly from the RSS feed. We aren't doing any modifications to the HTML they are providing.

If you want to open the link in a new tab you can use a keyboard shortcut when clicking the link. If you are using a Chromium based browser just hold SHIFT when you click the link.
