### ISSUE TITLE
[Enhancement]: Don't show the next book in series if you are still listening to the previous book

### ISSUE THREAD

**Issue by lkiesow** [advplyr/audiobookshelf#1382]
### Describe the feature/enhancement

If I start listening to a book in a series, let's say I start listening to “A Game of Thrones”, the next book in the series, “A Clash of Kings”, would immediately show up on the home page below the one I listened to in the category “Continue Series”. Wouldn't it make more sense to only show the book there once I finish the first one?

Reasoning:

- Assuming, I'm still listening to the first book, I'm not jumping straight into the next one before finishing. In this case, I don't need that book there.
- Assuming I abandon a book, it's unlikely that I will start the next one in the series at all. That means, I don't need a prominent listing.
- While still listening to a book, I might decide to take a break. In that case I might decide to pick up another book from a series I have read before. That means, the next one in the series I haven't yet finished the last one of is kind of in the way.

I've been wondering for a while why they are listed there, and I don't see a good reason. Any thoughts on this?

**Comment by advplyr** [comment]
Makes sense to me. There is no particular reason it is the way it is.
We can make the update then see if anyone preferred the old way and why.

**Comment by MidnightSnowleopard** [comment]
Preemptively stating that I'd prefer the new behavior of not showing next while still listening

**Comment by lkiesow** [comment]
Unless someone starts complaining here in the next days, I might take a shot at getting the work done.

**Comment by lkiesow** [comment]
Pull request is out…
