### ISSUE TITLE
[Enhancement]: Showing bitrate and container format

### ISSUE THREAD

**Issue by zelestcarlyone** [advplyr/audiobookshelf#1389]
### Describe the feature/enhancement

The enhancement is two-fold:
**Show in metadata**
First and foremost it'd be good to be able to see the bitrate of the current book you have selected, along with the container type. For instance:
![image](https://user-images.githubusercontent.com/13156143/211665689-0f74d1e0-b350-4343-ad33-5809b7364bef.png)
And yeah, I know my idea of replacing "Size" with "File" is ugly, there are better ways to do it. Could probably be it's own row to be honest. But it's there as an example to get my idea across. If one were to get really granular, one can also have an area available for encoding where it makes sense to display that information.

**Sorting and filtering**
A nifty feature would be to be able to sort your library on bitrate and container/format. This could serve many purposes, for instance if you have a lot of really old books in your library and you want to go through them and see which ones are in dire need of an update to either a new format, or higher bitrate.

**Comment by ceramicwhite** [comment]
+1 this. I have to check via cli bitrate, channels first before I can make a decision and watch options to use when encoding using ABS. Another option/addition would be to automatically set the defaults for the m4b maker to be the details retrieved here from ffprobe.

**Comment by hobesman** [comment]
One thing to note: perhaps if this is something only available to admins, and/or an option to enable or disable for my non-admin users? For my family, they don't need to know the container, bitrate, encoding, etc. They're more interested in the content than the file format, structure, etc.
Just a thought. Otherwise I like details in general...for me.

**Comment by advplyr** [comment]
Technically you could have an audiobook that is multiple tracks of different file formats. Definitely not advised, but not prohibited either.

For multi-tracks you could also have different bitrate per track.

**Comment by advplyr** [comment]
This was added a few versions ago and I missed this issue. It is in the table
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/53a0bf10-1da9-4865-b140-fefec47f8fac)

Also you can view all the audio file data by going to "More Info" in the context menu
