### ISSUE TITLE
[Enhancement]: Option to hide Series from Series overview 

### ISSUE THREAD

**Issue by Blindie92** [advplyr/audiobookshelf#1393]
### Describe the feature/enhancement

An Option for a Series to hide in Series overwiew would be nice, so we can create a Series that is only shown in another Series for a more granular sort.

**Comment by hobesman** [comment]
Another approach might be to provide a toggle "show primary series only" vs "show primary series AND subseries"

**Comment by Blindie92** [comment]
Another Idea, on the start page, the next audiobook for the series should be only from the sub series, not two from sub and main series.

**Comment by advplyr** [comment]
Can this be merged with #2092? It seems like the same

**Comment by Blindie92** [comment]
Yes, looks like the same

**Comment by advplyr** [comment]
Duplicate of #2092
