### ISSUE TITLE
[Enhancement]: Add Flag to Indicate Audiobook is Abridged

### ISSUE THREAD

**Issue by torchyboy** [advplyr/audiobookshelf#1408]
### Describe the feature/enhancement

Add a checkbox to indicate the audiobook is abridged.

**Comment by Demian98** [comment]
This would be a very useful Feature, which I'm missing currently. It would be great if this information could also be collected from online sources like audible.

**Comment by vincentscode** [comment]
How should this information be used? Should it just be a filtering option or should it also be used to show some kind of visual?

**Comment by torchyboy** [comment]
Available for filtering and displayed in the details of an audiobook would be great. An icon on the book's picture to indicate it was abridged so there would be a visual indication when browsing would be useful also, but not critical for usability.

**Comment by advplyr** [comment]
Added in [v2.2.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.18)
