### ISSUE TITLE
[Bug]: "Series Name" and "Sequence" Fields Not Aligned in modal

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#1410]
### Describe the issue

![image](https://user-images.githubusercontent.com/29721765/212571579-c7950ae0-27dd-4235-b850-608efdd8d04d.png)

The two text fields are not aligned.

### Steps to reproduce the issue

1. Click the pencil to edit book details
2. Click to add or edit a series
3. Observe the fields aren't lined up.

### Audiobookshelf version

2.2.12

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Yuck, thanks

**Comment by jmt-gh** [comment]
Opened a PR to resolve this in #1432
