### ISSUE TITLE
[Enhancement]: Ability to disable users from seeing full path

### ISSUE THREAD

**Issue by JaxzKyd** [advplyr/audiobookshelf#1411]
### Describe the feature/enhancement

Currently we are without the ability to disable users from seeing the full path of audiobook files

https://imgur.com/a/qFzrOp2

I was wondering if the ability for the admin to disable that button could be an option?

**Comment by advplyr** [comment]
I thought it would be better to just have this button only visible to admins

**Comment by advplyr** [comment]
Updated in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)

Only admin users will see the "Full Path" button
