### ISSUE TITLE
Collections RSS feed repeats the first book

### ISSUE THREAD

**Issue by benonymity** [advplyr/audiobookshelf#1417]
### Describe the issue

When I open an RSS feed of a collection, though every book is shown with proper title, description, and length, trying to play any will only play the audio file of the first book.

### Steps to reproduce the issue

1. Create a collection with multiple books
2. Open its RSS feed and add it to your RSS app.
3. Try to listen to any of the “episodes”

### Audiobookshelf version

v2.2.12

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not able to reproduce this. It is possible I fixed it in the latest release.

Let me know if you can reproduce and we will re-open
