### ISSUE TITLE
[Enhancement]: Option to hide Series that currently have only one book tagged

### ISSUE THREAD

**Issue by ceramicwhite** [advplyr/audiobookshelf#1433]
### Describe the feature/enhancement

I would love an option to hide series from showing up when there is only one audiobook currently listed in the series.
I think there's no reason to show it as a series while there's only one item currently on the server.

If I use "Match Books" after dumping a large set of new books on the server, every book on the server that's part of a series will get tagged, and I end up with tons of single-item series:
![single-series](https://user-images.githubusercontent.com/7660824/213978943-6b7d5073-7918-445d-ad62-749bd61eeccd.png)

Sometimes I dump 50-100 books at one time and use the "Match Books" feature, but if I have previously removed the series tag manually from each single-item series, they will just get added back. I also think a single item series doesn't really make sense in context to series listings and makes the series section look cluttered.

**Comment by advplyr** [comment]
This was added in v2.3.0 as a library setting.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/39d3e0fe-4699-487f-964b-131f780592ed)

**Comment by ceramicwhite** [comment]
Mate! You're a legend. Added every feature request I've made, thanks.

**Comment by advplyr** [comment]
You make good suggestions! Keep them coming
