### ISSUE TITLE
[Bug]: Opened RSS feeds not updating with new podcast episodes

### ISSUE THREAD

**Issue by rudism** [advplyr/audiobookshelf#1435]
### Describe the issue

Possible regression of #939.

Podcasts with opened RSS feeds do not update those RSS feeds with new episodes as they come out, even after audiobookshelf indexes the new episode and makes it available via the web UI. Restarting audiobookserver does not seem to help. The only way I'm able to get new episodes into audiobookshelf's opened RSS feeds is to close and re-open the feeds.

I believe the expected behavior should be that when a new episode of a subscribed podcast comes out, when audiobookshelf discovers that new episode, downloads it, and makes it available through the web UI, it should also add that episode to the RSS feed for that podcast if one is opened.

### Steps to reproduce the issue

1. Subscribe to a podcast that actively posts new episodes.
2. Open audiobookshelf's feed for that podcast.
3. Wait until a new episode of the podcast gets published and shows up in audiobookshelf's web UI.
4. Check the opened RSS feed for that podcast, observe that the new episode that is showing up in the web UI is not showing up in the RSS feed.
5. Optionally close the audiobookshelf RSS feed for that podcast and then re-open it at the same or a different url, and now observe that the new episode _is_ listed in the feed.

### Audiobookshelf version

v2.2.12

### How are you running audiobookshelf?

Docker

**Comment by Bostrolicious** [comment]
I've noticed this as well, also on v2.2.12. The RSS feed also fails to update when you use the search function to download already published episodes, so waiting for a new episode to be published isn't necessary to reproduce the bug.

**Comment by AvMavs** [comment]
Where did you even set this up? I'm not able to find any place where I can add podcasts...

**Comment by Bostrolicious** [comment]
On the server (not from the mobile app), create a new library and change the Media Type to Podcasts.

**Comment by AvMavs** [comment]
Thanks, I completely missed that. Found it now, it's super nifty.

**Comment by octopusx** [comment]
Hey, I noticed the same problem on my server after the update to v2.2.12. Also running in docker.

**Comment by advplyr** [comment]
Fixed in [v2.2.13](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.13)
