### ISSUE TITLE
[Enhancement]: Upgrade to Node 17 (Update OpenSSL)

### ISSUE THREAD

**Issue by asheingold** [advplyr/audiobookshelf#1436]
### Describe the issue

When building with Node > 17.0, OpenSSLthrows ERR_OSSL_EVP_UNSUPPORTED. This is due to:

https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V17.md#17.0.0

This should be upgraded.

### Steps to reproduce the issue

1.  Follow the build instructions.
2. When generating the static files (`npm run generate` in the client directory), it breaks.

### Audiobookshelf version

2.2.12

### How are you running audiobookshelf?

Built from source

**Comment by advplyr** [comment]
We are currently on Node 16 still

**Comment by advplyr** [comment]
I just noticed that Node 17 is no longer being maintained so the next Node version we would upgrade to is 18.

https://github.com/nodejs/release#release-schedule
