### ISSUE TITLE
[Enhancement]: Delete Items From Hard Drive

### ISSUE THREAD

**Issue by slyfoxgh** [advplyr/audiobookshelf#1439]
### Describe the feature/enhancement

Similar to Plex, can you please enable a setting to allow the admin user to delete files from ABS and the system?

**Comment by advplyr** [comment]
Bulk deleting library items
![image](https://user-images.githubusercontent.com/67830747/232345835-3fa6bdcd-274f-44fe-84ca-e0e1356e065f.png)

![image](https://user-images.githubusercontent.com/67830747/232345721-0e484c48-b6f2-44c2-8cb2-25b9e680a463.png)

Deleting a library item
![image](https://user-images.githubusercontent.com/67830747/232345801-67a9b5c4-8845-4fec-8b44-ef444bf1bff3.png)


Deleting individual files
![image](https://user-images.githubusercontent.com/67830747/232345762-3276abc9-dc72-4a92-b356-a7ccf12beef9.png)

**Comment by advplyr** [comment]
Added in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)

**Comment by njakes** [comment]
Will this be tied to user permissions so guests that have access cant delete items from my file system?

**Comment by advplyr** [comment]
Only users with the "Can Delete" permission will be able to use this

**Comment by oboe45** [comment]
Excellent, remove was a pain before
