### ISSUE TITLE
[Bug]: The seriestitle on "Recent Series" doesn't scale properly

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1440]
### Describe the issue

When resizing the UI, the series title on "Recent Series" doesn't scale

[UI at 60](https://i.imgur.com/QEfIOuH.png)

[UI at 220](https://i.imgur.com/ybthNJ5.png)

"Recent Series" is scaled properly, "Dune" is the same size

### Steps to reproduce the issue

1. Resize the UI 
2. Observe "Recent Series"

### Audiobookshelf version

2.2.12

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.15](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.15)
