### ISSUE TITLE
ENHANCEMENT: sync back played for offline downloaded

### ISSUE THREAD

**Issue by docfactory37** [advplyr/audiobookshelf#145]
i have downloaded an audiobook to my phone to listen in offline mode, but it would be good that if i reconnect back to the server that it sync what has been played back to the server to continue play once home. 

at the moment if i play in offline mode i have to continue on that device only and not able to continue on another device or by the web portal.

Please let me know your thoughts?

Note: awesome what you have done been looking a long time for a good AudioBook / book manager :)

**Comment by zombiehoffa** [comment]
I can also confirm on the very latest server and app. I was just coming to report this but you guys have the problem completely hashed out already.

**Comment by davidszp** [comment]
I tried downloading a file for offline use in the mobile app, and it currently does not work (0% progress spinning). Updated to latest docker server and mobile app from play store.

**Comment by advplyr** [comment]
@davidszp Have you tried downloading other audiobooks? Is the server showing any errors?

Have you tried selecting a different folder to download to? It seems there are still issues with some users and selecting some folders.

**Comment by davidszp** [comment]
@advplyr You were right, for some reason my original download folder was reset. I had to manually select it and then downloading worked fine again.
