### ISSUE TITLE
[Bug]: Invalid Credentials gives 'Method Not Allowed'

### ISSUE THREAD

**Issue by JoshuaGarrison27** [advplyr/audiobookshelf#1452]
### Describe the issue

When trying to login to the application from a browser (Firefox in my case), if you input the wrong username/password, you will get the HTTP Status Code of `Method Not Allowed` instead of something saying the username/password are incorrect.

### Expected behaviour
- I would expect a more appropriate message back such as `Invalid username and/or password`

### Actual behaviour
- Get response message back as `Method Not Allowed`

### Steps to reproduce the issue

1. Go to AudioBookShelf instance
2. Type in random characters for username / password
3. Click Submit.
4. Get response message back as `Method Not Allowed`

# Logs
```plaintext
[2023-01-28 15:00:36] WARN: [Auth] Failed login attempt 1 of 10 from <REDACTED-IP> (Auth.js:135)
```

### Audiobookshelf version

2.2.12

### How are you running audiobookshelf?

Kubernetes

### Screenshots

![image](https://user-images.githubusercontent.com/1706923/215288786-c2b9ec00-908c-47eb-9a13-06c035c17186.png)

**Comment by advplyr** [comment]
Abs does not return any error message of "Method Not Allowed". This must be coming from your server.

Tested on Brave & Firefox with v2.2.12
![image](https://user-images.githubusercontent.com/67830747/215290080-b56eb6a0-8948-419e-a682-5c7dfa037f57.png)

**Comment by JoshuaGarrison27** [comment]
I'm running behind Nginx on a Kubneretes cluster. Could be how nginx is processing the request.

**Comment by advplyr** [comment]
Abs is returning a 401 status code on invalid credentials. A quick search returned https://github.com/kubernetes/ingress-nginx/issues/2292

That may be relevant here. This doesn't seem like an issue with Abs now but let me know if you find something

**Comment by JoshuaGarrison27** [comment]
Ill check it out. Not a major issue. Just wanted to report it just in case.
