### ISSUE TITLE
[Bug]: IOS App incorrectly logged LISTENING SESSIONS activity multiple times

### ISSUE THREAD

**Issue by kenw** [advplyr/audiobookshelf#1455]
### Describe the issue

Checking my USER STATS on browser, it appears that the IOS app incorrectly logged LISTENING SESSIONS.

![image](https://user-images.githubusercontent.com/161240/215345463-b673bc9c-bdc0-47d9-938e-bf70ddfad502.png)

![image](https://user-images.githubusercontent.com/161240/215345265-bcec0caf-3344-4e1b-ae34-172995a82c9c.png)

...Skipping to Page 5...
![image](https://user-images.githubusercontent.com/161240/215345387-9e77b4b9-83f7-4362-b31d-d93d8bd6e96e.png)

- IOS app is v0.9.60-beta
- running on iPhone 12, IOS 16.3

### Steps to reproduce the issue

1. I don't know how to reproduce the issue

### Audiobookshelf version

2.2.12

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
A lot of changes happened since this so this may be resolved

Let me know if you can reproduce this on mobile app v0.9.65-beta and server version v2.2.23 and we can re-open this
