### ISSUE TITLE
[Enhancement]: Add logging for downloaded files

### ISSUE THREAD

**Issue by ktorq** [advplyr/audiobookshelf#1461]
### Describe the feature/enhancement

It appears that there is no logging around a user downloading a file. 
To reproduce: 
I set level to DEBUG, went to an audiobook, under Audiotracks hit Download. No logs for any action.

**Comment by devilbob** [comment]
I'd like to see this implemented similar to Listening Sessions - show User, Title and date/time of all downloads.  I have a couple of users who only use downloads and then move the book to an MP3 player to listen.

**Comment by advplyr** [comment]
In `v2.2.22` I added a log for when individual files are downloaded. Next release will have a log for when full library item is downloaded as a zip.

The mobile apps use the individual files endpoint which is where most downloads happen, so you should already see those.

They look like this:
```
INFO: [LibraryItemController] User "${user.username}" requested file download at "${filepath}"
```

**Comment by advplyr** [comment]
This was added in v2.3.0 but the latest release v2.3.3 should be used
