### ISSUE TITLE
[Bug]: Readding previously removed podcast

### ISSUE THREAD

**Issue by talkingseedling** [advplyr/audiobookshelf#1462]
### Describe the issue

Podcast added via the search function, did not select to download episodes. From the web viewer I removed the podcast. Later when trying to add the same podcast again, presented with the error "Podcast already exists". The podcast does not appear in the viewer, and there are no files on the HDD.

### Steps to reproduce the issue

1. Search for podcast
2. Add podcast, set autodownload to no
3. Browse to the home page, hover over the podcast, click the pencil, click remove
4. Search for the same podcast and try to add

### Audiobookshelf version

v2.2.12

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.15](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.15)
