### ISSUE TITLE
[Enhancement]: RPM repo for Centos or building from source

### ISSUE THREAD

**Issue by twiclo** [advplyr/audiobookshelf#1467]
### Describe the feature/enhancement

I've seen mention of an RPM in this issue: https://github.com/advplyr/audiobookshelf/issues/1466

I see no mention of an RPM repo or where an RPM can be directly downloaded anywhere in the docs or on the github. Does one exsit? If not can you please provide instructions on setting this all up manually?

**Comment by advplyr** [comment]
This is something @lkiesow has setup and is in testing. It is in the docs now https://www.audiobookshelf.org/docs#linux-install-rpm
