### ISSUE TITLE
[Enhancement]: Send ebooks to (other) devices

### ISSUE THREAD

**Issue by xAaeEx** [advplyr/audiobookshelf#1474]
### Describe the feature/enhancement

Fist let me tell you how much I love this project! You guys did a wonderful job, thank you!

Ebook support was actually a pretty cool feature for this project, but as you guys know many people read ebooks not on their phones/tables but on ebook-readers.
I myself have a calibre-web selfhosted, but if you support the sending of ebooks (to other devices like kindle, kobo etc...) from this project, it would actually be a pretty good alternative to calibre-web project (at least for me).

I think to have the chance to read the book on audiobookshelf or send it to the specific device of choice would be a great feature.

Let me know if this is an acceptable thing to implement.

Kind regards

**Comment by advplyr** [comment]
![save_ebook_to_kindle](https://github.com/advplyr/audiobookshelf/assets/67830747/ab94dd75-01ed-400d-97a7-492f3ce7eada)

**Comment by advplyr** [comment]
To use this feature you will need to setup your email provider. The screenshot is what it looks like if you are using gmail.

For gmail the password field will probably need to be an app password. https://support.google.com/mail/answer/185833

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/553871f8-5528-4d4c-a53d-05a99631d849)

The "Test" button in the email settings will send a test email to your "From Address".

Once you have your email setup and have received the test email then you need to add an ereader device.

Currently this feature is restricted to admin users. Only admin users will see the "Send ebook to..." menu item.

**Comment by advplyr** [comment]
Added in [v2.2.22](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.22)

**Comment by projx** [comment]
Could this be extended, to mark books for download by the Mobile client?

**Comment by advplyr** [comment]
I don't understand what you mean

**Comment by dpg10** [comment]
Could the send eBook to function be added to the Android app? Would be great to view the library on the phone and have a quick way of sending the eBook to your Kindle. Thank you.

**Comment by IDmedia** [comment]
New user looking to migrate from Calibre-Web here... 
Why is this a "global" settings? Shouldn't the devices be a setting on the users profile page so it's tied to a specific user?
