### ISSUE TITLE
[Bug]: Crawled author metadata has the wrong language

### ISSUE THREAD

**Issue by lukeIam** [advplyr/audiobookshelf#1475]
### Describe the issue

I have "Audible.de" configured as metadata provider.
![image](https://user-images.githubusercontent.com/5115160/216773805-ec5e1fed-f405-4bb0-9850-74b90719925c.png)

It works fine for book metadata, but for author metadata I get an English description.
I would expect an German description (like on the audible.de author page - it exists by the way ;) )

### Steps to reproduce the issue

1. Configure "Audible.de" as metadata provider
2. Add an non english book (e.g. **https://www.audible.de/pd/Natrium-Chlorid-Hoerbuch/B09KCHY49B** )
3. Click on the author ("Jussi Adler-Olsen") and click the "QuickMatch" Button
4. English metadata is loaded (instead of  the metadata from https://www.audible.de/author/Jussi-Adler-Olsen/B0043BVIJE )

### Audiobookshelf version

2.2.14

### How are you running audiobookshelf?

Docker

**Comment by lukeIam** [comment]
OT: sorry for writing multiple issues (for different topics).
I really like you project and besides such small things it's working great.
Thanks for your work!

**Comment by lukeIam** [comment]
ah it seems that you are getting the author metadata not from audible but from: api.audnex.us 

according to their docu we should append a `?region=de`.

But in my case with B0043BVIJE I also get an english result...

**Comment by advplyr** [comment]
Yeah Audible doesn't give any author information in there API. Audnexus gets that info from Audible so maybe you could look to see if they have implemented multi-region support for authors. They only recently added multi-region support.

Right now Abs is only setup for region `us` for authors but we can update that if audnexus supports it.

**Comment by advplyr** [comment]
Fyi we use the region in audnexus for regular book data https://github.com/advplyr/audiobookshelf/blob/master/server/providers/Audible.js#L65

**Comment by lukeIam** [comment]
Opened: https://github.com/laxamentumtech/audnexus/issues/609

**Comment by advplyr** [comment]
Added in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)
