### ISSUE TITLE
[Bug]: OPF reader doesn't load `title` element if it contains `file-as`

### ISSUE THREAD

**Issue by wtanksleyjr** [advplyr/audiobookshelf#1478]
### Describe the issue

Attached is an OPF generated by `odmpy 0.6.2` (https://github.com/ping/odmpy/); it mostly works, but the title doesn't load. The problem seems to be the presence of an `opf:file-as` attribute inside the title element -- if I edit that out, it all loads perfectly.

[metadata.opf.txt](https://github.com/advplyr/audiobookshelf/files/10614130/metadata.opf.txt)

Do you think this is fixable on ABS's side?

### Steps to reproduce the issue

1. Configure ABS to prefer OPF metadata rather than folder metadata
2. Grab the provided file, drop it in a folder with an audio file so it looks like an audiobook, make sure the folder's name is something distinctive
3. Move into ABS's autoscan folder
4. Check to see that the audiobook's scanned name matches the folder's name, but everything else in the metadata comes from the OPF file

### Audiobookshelf version

2.2.13

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.15](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.15)
