### ISSUE TITLE
[Bug]: Batch Update of Series not working

### ISSUE THREAD

**Issue by nodecentral** [advplyr/audiobookshelf#1482]
### Describe the issue

Hi, I’m trying to update the Series on a number of books but it does not matter how many I select it only update one of them (not all)

### Steps to reproduce the issue

1. Go into an existing series and select multiple books
2. Click the pencil edit option, and remove the current Series Selection
3. Add the new Series Selection and hit submit
4. And then hit save

### Audiobookshelf version

V2.2.14

### How are you running audiobookshelf?

Docker

**Comment by nodecentral** [comment]
Sorry, I’ve just noticed that the batch up date does not work as I assumed it would, I expected it to provide me with one general form to update and then apply it to all the books, rather than provide me with the forms for all the books I selected.

Can this be changed to a Feature Request - so that i can make a one to many change, rather than have to do the same change multiple times.

many thanks

**Comment by advplyr** [comment]
This is already how it works
![image](https://user-images.githubusercontent.com/67830747/218221223-930bf315-1630-44da-a26a-ee9a1c049c87.png)

Unfortunately this would overwrite the sequence if you have it set

**Comment by nodecentral** [comment]
Thanks @advplyr , how can I find that form you shared ?

When I select multiple books, and then click the pencil icon, it create a list a forms for me to edit each book, there is not single form that would update all selected books ?
