### ISSUE TITLE
[Enhancement]: Multicore support for M4B-encoding

### ISSUE THREAD

**Issue by Rogibaer** [advplyr/audiobookshelf#1483]
### Describe the feature/enhancement

Hello,
if I understand the m4b conversion feature correctly, it is using m4b-tool, right?

For m4b-tool there is the --jobs parameter, which lets you specify the number of cores used for encoding.
Can you implement an option to alter the number of jobs for the M4b-encode?
Would be a huge benefit for me!

Keep up the excellent work!

Kind regards,

**Comment by jmt-gh** [comment]
We leverage ffmpeg directly to handle this, not m4b-tool. My understanding is that ffmpeg, while it does have the option to specify threads, by default it will leverage the optimal number of threads given the CPU capabilities it's running on, and the job it's doing. I would be interested to know if you find otherwise

**Comment by advplyr** [comment]
@jmt-gh is correct, we are not using m4b-tool, we are using ffmpeg.

**Comment by Kuglikrug** [comment]
Hi all, while encoding a 90 part mp3 audiobook into a single m4b file using the built in M4B-encoder, I noticed that my 8 Core CPU is only at ~15% utilization.
It seems like all cores are being used but is there a way to "allow" ABS to saturate my CPU to the fullest?
I hope that this would increase the encoding speed.

**Comment by CacklingCapybara** [comment]
I also am looking for this. If using built in m4b merger, it only uses a single core (out of 16 available) and it takes over an hour to process. When I use m4b-tool, I specify jobs=10 and it completes in <10 minutes. Would appreciate a way to specify number of cores/threads as opposed to just leaving at default.
