### ISSUE TITLE
[Enhancement] Parse ID3 tags from podcast episodes

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#1488]
Sure. There's no tagging standard, really, but I'll just share what I came up with. I'm using MP3Tag, so most of these are the unified tags. There might be some that don't exist in ID3v2.3, but do in ID3v2.4 or MP4 - or vice versa.

![image](https://user-images.githubusercontent.com/748857/193668784-182ad19a-8de6-4b28-b11c-b38409230e78.png)

* `album`, `albumsort`: Podcast title
* `artist`: Hosts plus guests. I did this specifically for Plex so I could see the guests in the track view. If this should be implemented in ABS, `artist` should only be the host, with maybe `composer` as guests (similar to `composer` being used as the narrator tag for audiobooks).
* `artistsort`, `albumartist`, `albumartistsort`: Hosts
* `comment`, `unsyncedlyrics`: Episode description
* `composer`, `guests`: Guests, if applicable. `guests` is not a real tag (and should be ignored), I created and misused it for automatic file naming options. I think `performer` could be used as well.
* `contentgroup`: Kind of like a subtitle. It's a residue from an audiobook tagging standard that I continued with this. Not really necessary, really.
* `discnumber`: Season, if applicable
* `genre`: Well, the genres
* `language`: Language
* `movementname`, `series`: Podcast title
* `movement`, `series-part`, `track`: episode number
* `origyear`: publication year
* `podcast`: I think this is an iTunes specific tag that's always set to 1
* `publisher`: podcast studio
* `showmovement`: this is part of the `movement` tag, not sure which software uses that.
* `title`: episode title
* `year`: publication date. I use yyyy-mm-dd specifically for Plex, in case it ever supports that on a track level. The whole publication date thing can be juggled around as there are a handful of tags that might be valid: `year`, `date`, `releasedate`, ...

Season and episode number together with `series-part` can be tricky. But since `series-part` can be a string, and not only a number, one might also do a "season.episode" series-part, IMO (like 6.3 for season 6 episode 3=.

_Originally posted by @JakobTischler in https://github.com/advplyr/audiobookshelf/discussions/1038#discussioncomment-3790601_

**Comment by tfranken90** [comment]
+1 for this tagging scheme. The most important tags are tracknumber (Episode), discnumber (Season), comment (Description), and date (Publication Date).

**Comment by JakobTischler** [comment]
Just to add a discussion topic, I'd like to talk about a suggestion from the original issue by @tfranken90:

> Rather than scanning tags, it would be helpful if ABS could just pickup some basic information from folder structure and file names. For example, my files are named with a pretty conventional SS-EE scheme.

I have to say I somewhat disagree with this. Using directory structure as content / metadata information is bad practice in my opinion. ID3 tags are perfect for directly defining any information you'd like - including season and episode. At the very least, they should take priority over a folder structure/file naming scheme. Maybe even make it a configurable preference, like the already existing `Prefer audio metadata` setting.

**Comment by advplyr** [comment]
Added in [v2.2.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.18)

Still need to do up the docs on this and there will probably be some kinks to work out

**Comment by sizzleweet** [comment]
I think that mp3tag is improperly using the year functionality.  It's the only application I've found that can add that much data into the year field.

Looking at a file that I have tagged like your example but using exiftool, the year is only shown as a 4 digit value.

**Comment by advplyr** [comment]
@sizzleweet Abs is using a 4 digit year for the `year` tag. `date` and `releasedate` are getting the full pubDate
