### ISSUE TITLE
[Enhancement]: Show 'Next backup in [duration]' on the backup dialog

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#1491]
### Describe the feature/enhancement

For those who use cron to schedule their backup, it might take a little mental maths to figure out when the next backup is scheduled to take place. It would be nice if there was a label somewhere on the dialog that calculated the cron schedule day/date and displayed it as 'Next backup in [duration in days]'.

Example (note: mine is every two days and is easy, but someone might have a really complicated cron schedule set up).
![image](https://user-images.githubusercontent.com/42061703/217508313-79ab7571-f74f-4f48-a096-2615f73ec962.png)

**Comment by advplyr** [comment]
Added in [v2.2.16](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.16)
