### ISSUE TITLE
[Enhancement]: Continue Series no longer repeating the same book.

### ISSUE THREAD

**Issue by MrBearedJoe** [advplyr/audiobookshelf#1492]
### Describe the feature/enhancement

If the next book in the series is in multiple series in a library, it shows the book as many times as it is in a different series. 
I would propose only showing the book one time. 

Maybe consolidate and show the multiple number of the series in the top right. 
Also, somehow putting the name of the series somewhere

![image](https://user-images.githubusercontent.com/43275672/217627272-087898b6-d2d6-4268-a48b-ca023b2858e8.png)

**Comment by advplyr** [comment]
What version of the server are you running?

**Comment by MrBearedJoe** [comment]
2.2.12, has this changed in 2.2.14?

**Comment by MrBearedJoe** [comment]
We had issues with 2.2.13 (deb) and haven't tried 2.2.14 yet.

Didn't seeing "Books being listed twice in continue series by @lkiesow in https://github.com/advplyr/audiobookshelf/pull/1398"

**Comment by advplyr** [comment]
Yeah fixed in 2.2.14 but let me know how if not

**Comment by MrBearedJoe** [comment]
It looks like continue series was removed.
