### ISSUE TITLE
[Enhancement] Search for narrator

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#1495]
### Discussed in https://github.com/advplyr/audiobookshelf/discussions/1494

<div type='discussions-op-text'>

<sup>Originally posted by **Travillion** February  9, 2023</sup>
Would be helpful if tagged narrators were a searchable entity. For example, looking for titles narrated by Scott Brick. All of my audiobooks are fully tagged with embedded metadata, which ABS uses as preferred source. ABS correctly recognizes my narrators, but searching for a narrator doesn't produce any results.</div>

**Comment by ljo123** [comment]
Agreed. Also just providing more details in the search results such as narrator, publisher, etc would help find the correct match.

**Comment by advplyr** [comment]
Added in [v2.2.20](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.20)
