### ISSUE TITLE
[Enhancement]: Check if directory already exists before upload

### ISSUE THREAD

**Issue by juriroemer** [advplyr/audiobookshelf#1497]
### Describe the feature/enhancement

Currently, if you upload an audiobook/folder via `/upload/` that already exists, you will only get an error when the upload is completed. It might be more resourceful to check if the folder exists before starting the upload.

![image](https://user-images.githubusercontent.com/31971585/218166707-41ab9d82-3009-4882-9035-855db9325fc6.png)

**Comment by advplyr** [comment]
Added in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)
