### ISSUE TITLE
[Bug]: Error on import, import failure

### ISSUE THREAD

**Issue by kavemang** [advplyr/audiobookshelf#1499]
### Describe the issue

import a single file book in m4b format ~600mb, expected import of the book

error in log is:

`ERROR: Invalid request, no files (MiscController.js:23)`

### Steps to reproduce the issue

1. import m4b file of ~600mb size

### Audiobookshelf version

2.2.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not able to reproduce this. What browser are you using to upload?
Are you connecting through local ip address?

**Comment by kavemang** [comment]
after you mentioned browser I tried a different one, this bug is specific to vivaldi it looks like, just had successful upload with waterfox

**Comment by advplyr** [comment]
Are you able to upload smaller audio files using Vivaldi?

This seems more like a bug with Vivaldi then with Abs

**Comment by kavemang** [comment]
I tried very small files as well as large ones, however this also seems to happen in librewolf so vivaldi and librewolf so far are affected

**Comment by advplyr** [comment]
I'm not familiar with these browsers. Are there some settings you can try messing with, maybe a firewall the browser is enabling.

**Comment by advplyr** [comment]
@lkiesow May be familiar with these browsers

**Comment by lkiesow** [comment]
I'm not.But since it seems to be browser related, are you seeing any errors in the developer console of these browsers (you can probably open that with F12)?
