### ISSUE TITLE
[Bug]: Sort Order when group by sereies in another Series

### ISSUE THREAD

**Issue by Blindie92** [advplyr/audiobookshelf#1503]
### Describe the issue

When you Group by series in another series, the colapsed series are unsorted.

![grafik](https://user-images.githubusercontent.com/94938390/218404320-9d1fd283-92e3-4396-a268-84aa5ef443f5.png)

### Steps to reproduce the issue

1. You need Multiple Book Series in Anouther Series
2. Open the series Tab and navigate to the Series where the multiple series are
3. Activate Collapse Series
4. now you see the Series are complete random, not sorted by Series name, ore Book name ore something else i found.

### Audiobookshelf version

v2.2.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
They should be sorted by series sequence but it looks like you have no sequence set in your series

**Comment by Blindie92** [comment]
Yes, the main series have no sequenz, it's a book universe with a lot of indipendent series and time jumps like star wars ore star trek, in this case a alphanumeric sort order would be nice if no sequenz is there.

**Comment by advplyr** [comment]
Added in [v2.2.16](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.16)
