### ISSUE TITLE
[Bug]: RSS feed not working

### ISSUE THREAD

**Issue by fillilutten** [advplyr/audiobookshelf#1507]
### Describe the issue

I opened a RSS feed but the link isn't working in any app. In the top it says "This XML file does not appear to have any style information associated with it. The document tree is shown below." Could that has to do with anything?

### Steps to reproduce the issue

1. Added private rss url from Patreon podcast. 
2. Downloaded all episodes
3. Opened a RSS feed.
4. Trying to add into different podcast players

### Audiobookshelf version

v2.2.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I looked up that message and is just something from your browser. See https://billing.ragesw.com/index.php/knowledgebase/113/This-XML-file-does-not-appear-to-have-any-style-information-associated-with-it.html

What is the error you are getting when adding the RSS feed from Abs into podcast players?
Which podcast players are you trying?
Are you using an `https` URL?

**Comment by fillilutten** [comment]
Ah ok. Something about not finding the url or that its not the correct url. But I just was thinking - could it maybe have to do with something my cloudflare settings? Hm...

**Comment by advplyr** [comment]
Could be, I'm not sure. What podcast players?
There are also websites that will validate RSS feeds and maybe give you more information.

You can try https://podcasts.google.com which works for mine.

**Comment by fillilutten** [comment]
Oh it was cloudflare firewall that blocked it. Have my firewall set to block all countries except the one I live in. Made an exception and now it works perfect, should have understood that in the first place so sorry to take your time but huge thanks!

**Comment by advplyr** [comment]
Glad it is working for you now!
