### ISSUE TITLE
[Enhancement] Filter out podcasts from search that do not have an RSS feed

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#1514]
I just checked that podcast and iTunes is not returning the RSS feed url. I didn't know that was something that could happen so we will have to filter out these podcasts that don't return a feed url or add some sort of alert.

I looked it up and it is the podcast author who chose not to expose their RSS feed url.

> Apple Podcasts Connect now offers podcasters the ability to hide their RSS feed from the catalog API. If you don't see the feedUrl field then the podcaster has unchecked the option in the Availability tab in Apple Podcasts Connect.

Ref: https://stackoverflow.com/questions/65843154/itunes-search-podcast-json-api-repository-sometimes-does-not-return-feedurl

Unfortunately there is nothing we can do about that. I have never seen this before so I doubt there are many podcasters who are doing that.

_Originally posted by @advplyr in https://github.com/advplyr/audiobookshelf/issues/1511#issuecomment-1435008690_

**Comment by eskiiom** [comment]
Hello,
as I am progressing to restore all my feeds and library, I noticed something.

Even if the backup/restore function works well, it seems that it doesn't store the RSS xml feed, and only rely on the match/quick-match that will populate everything publicly accessible, and not the rss feed if it is hidden on apple podcast.

Is that correct in the way it works ?

If so, it would probably be good to store a local version of the feed url, no ?

Thanks

**Comment by advplyr** [comment]
We don't store a copy of the RSS xml. I don't think that is something we want to store in the DB since it should be fetched every request anyway.

**Comment by eskiiom** [comment]
Yes I understand, but in the case the feed is not published on the podcast but available somewhere else, it means you can update the library item with then feed url you found yourself. 
If it's refreshed it's lost.
I would say store it in DB, compare with the fetched data, if the same do nothing, if fetched data is empty, leave the library item or ask the user what to do. keep or remove ?
does that make sense to you ?

**Comment by eskiiom** [comment]
Yes it happens quite frequently on the podcasts I have subscribed. 
When adding to the library the feed url was empty but I could fill it in with the help of Google.
I can provide you examples if needed :)

**Comment by advplyr** [comment]
Yes if you can give an example. I still don't understand

**Comment by eskiiom** [comment]
Hello @advplyr 
sorry it took quite a while to answer.
I finally found a good example
The podcast "Grand bien vous fasse" by France Inter

![image](https://github.com/advplyr/audiobookshelf/assets/26815164/dcd26443-944e-4976-b2d3-7549e901cf99)

It says invalid/no feed
If I go on apple podcast (https://podcasts.apple.com/us/podcast/grand-bien-vous-fasse/id1148602643?uo=4) i can find it
And if I go on franceinter.fr (https://www.radiofrance.fr/franceinter/podcasts/grand-bien-vous-fasse) I can have access to the RSS feed (https://radiofrance-podcast.net/podcast09/rss_16173.xml)

![image](https://github.com/advplyr/audiobookshelf/assets/26815164/6cb31a8f-4c8d-4c22-86a3-e788254a5445)

That mean that there's a difference between the official provider/creator, but still you can find, add or edit feeds to your needs.

Does that make more sense ?
Have a nice day

**Comment by advplyr** [comment]
Apple api is not giving us the RSS feed for that podcast so we can't do anything about that. You can however enter the RSS feed directly into the search bar and add it that way.
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/0c633b01-4918-462e-b2da-ae29a6bbb82f)

**Comment by advplyr** [comment]
Added in v2.3.0
