### ISSUE TITLE
[Bug]: In a series RSS feed, all audio file downloads point to the first file

### ISSUE THREAD

**Issue by Weldawadyathink** [advplyr/audiobookshelf#1531]
### Describe the issue

All audio files in a series RSS feed point to the file for the first item in the series. Tested using the [Temeraire Series](https://en.wikipedia.org/wiki/Temeraire_(series)), but should be reproducible with any series. Also tested with Overcast and Apple Podcasts for Mac. 

The RSS feed correctly points to different links for the different books in the series, but all links return the audio file for the first item. For example:
/feed/ser_1tcyx12el13axtq1yt/item/1/Empire of Ivory: Temeraire, Book 4.m4b
/feed/ser_1tcyx12el13axtq1yt/item/1/Black Powder War: Temeraire, Book 3.m4b
These endpoints both return the same file. 

### Steps to reproduce the issue

1. Create a series
2. Open  an RSS feed for the series
3. Import RSS feed into a podcast program
4. Play or Download any books in the series, excluding the first one

### Audiobookshelf version

v2.2.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.16](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.16)
