### ISSUE TITLE
[Bug]: Crash when updating metadata via API

### ISSUE THREAD

**Issue by rosystain** [advplyr/audiobookshelf#1540]
### Describe the issue

Not sure if it's my personal problem or a bug.
I want to update some information as a batch using API. According to the Docs, most requests work well but which including `authors` fails and occurs a crash without any log.

 I use requests module of Python to patch metadata and here is my code.
``` 
metadata = {
    "metadata": {
        "authors": [{'name':'TEST'}],
        "narrators": ['TEST'],
        "publisher":None
        }
    }
patchdata = json.dumps(metadata)
x = requests.patch(url, data=patchdata, headers=head)
```
 

### Steps to reproduce the issue

1. Run the code above.
2. ABS crash and Python return `requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`
3. Delete `authors` and just keep `narrators` and `publisher`.
4. Run the code again.
5. Items updated successfully.

### Audiobookshelf version

v2.2.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.18)
