### ISSUE TITLE
[Bug]: multiple Authors from a audiobook are treates as on autor

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf#1543]
### Describe the issue

I have several audiobooks with multiple Authors. For example this:
![image](https://user-images.githubusercontent.com/72630160/220986407-94fcf471-d90a-4075-ba3b-7e66fad61335.png)
The syntax for multiple authors on filesystem is ok:
![image](https://user-images.githubusercontent.com/72630160/220986574-89d33288-89db-4eec-851c-cbbf31580138.png)
But I have only one "Author"-Item with the Name of the two authors:
![image](https://user-images.githubusercontent.com/72630160/220989154-9a88b520-7af5-49e3-a364-b770d8c772f3.png)

But these two authors also have also other audio books as "single author".
The Info within opf-file it seems to be ok:
![image](https://user-images.githubusercontent.com/72630160/220988172-8cb542c3-70a7-4b27-a2b2-26a1e9f2279d.png)
Also within ID3Tags it looks fine:
![image](https://user-images.githubusercontent.com/72630160/220988639-6d3ff533-d347-4572-b40a-a04fb5468e69.png)

I would expect two seperate Author Items.

### Steps to reproduce the issue

1. upload a audiobook written by two authors with correkt naming syntax on filesystem and ID3-tags and opf-file
2. you will get 1 Author-Item instead of 2

### Audiobookshelf version

2.2.11

### How are you running audiobookshelf?

Docker

**Comment by hobesman** [comment]
Author is Kuenstler. Komponist is narrator. In your id3 tag Kuenstler has some odd symbols. Perhaps those are causing the trouble?

**Comment by advplyr** [comment]
Your ID3 tag is putting the authors where the narrator would be (TCOM)

I suspect that the author is being pulled from your OPF file though which as @wtanksleyjr pointed out is not correct. Each author must be its own line.
