### ISSUE TITLE
[Enhancement]: Show resolution of currently active cover

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#1547]
### Describe the feature/enhancement

Currently the edit cover screen shows the resolution of searched covers, and the resolution of local covers, but doesn't tell you the resolution of the currently active cover.

Could it be set to show that resolution as well?

**Comment by nichwall** [comment]
Would positioning like this be good? I think if the information is added it should always be added instead of being toggleable.

![cover_resolution_added](https://user-images.githubusercontent.com/5686638/224214692-44738814-0ba5-44b6-874a-53108ff90839.png)

**Comment by hobesman** [comment]
That's what I was imagining, yes.

**Comment by advplyr** [comment]
Added in [v2.2.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.18)
