### ISSUE TITLE
[Bug]: Spell Error when creating a new Collection (German)

### ISSUE THREAD

**Issue by ErsterImChat** [advplyr/audiobookshelf#1550]
### Describe the issue

When creating a new Collection the "Create" Button has a typo.

Its called "Erstellen", not "Ertsellen". 

![image](https://user-images.githubusercontent.com/64809589/221311420-a2c67804-0f90-435d-9f01-3eb72e20a872.png)

### Steps to reproduce the issue

1.  Create a new Collection

### Audiobookshelf version

v2.2.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.16](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.16)
