### ISSUE TITLE
[Bug]: Entries from items folder are not deleted

### ISSUE THREAD

**Issue by Demian98** [advplyr/audiobookshelf#1561]
### Describe the issue

I have around 250 books in ABS:
![grafik](https://user-images.githubusercontent.com/77210091/221556631-2c2ad60c-7aea-46eb-bb62-965791190bb5.png)

But the items folder of the docker volume shows around 590 items:
![grafik](https://user-images.githubusercontent.com/77210091/221556701-4b817b45-02b7-4834-af4e-7457ee997b73.png)

I guess this is, because I deleted a lot of books and added them again with the next library scan. Could it be, that entries form the items folder are not deleted, when the book is deleted in the UI?

### Steps to reproduce the issue

Add some books, delete them and check the volume with the command above :)

### Audiobookshelf version

2.2.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not sure I understand.
When you use the "Remove" button it is only removing it from the database and not removing your actual files.

**Comment by Demian98** [comment]
I mean the items under "/metadata/items" in the docker container. They are not getting deleted when I remove something from the library.

It is perfectly fine that my actual data are not touched :)

**Comment by advplyr** [comment]
Updated in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)
