### ISSUE TITLE
[Enhancement]: .awb (AMR-WB Audio File)  format support 

### ISSUE THREAD

**Issue by iAHTOH** [advplyr/audiobookshelf#1565]
### Describe the feature/enhancement

There are a lot of audiobooks on old phones. I wish this format was supported.

**Comment by advplyr** [comment]
Can you link to a website I can download a sample AWB file? I've never heard anyone have an audiobook in this format.

**Comment by iAHTOH** [comment]
I have a book in the library in this format. Douglas Adams The Hitchhiker's Guide to the Galaxy. But it's in Russian
https://drive.google.com/file/d/17ZtAm9MIxik1YM_QoFzH6zy3m7m8c6AS/view?usp=sharing

**Comment by advplyr** [comment]
Added in [v2.2.17](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.17)
