### ISSUE TITLE
[Bug]:backslash to create folder?

### ISSUE THREAD

**Issue by KUKARAF** [advplyr/audiobookshelf#1566]
### Describe the issue

When adding a library with type podcast and then adding objects to that library the folders get created on the same level as the library folder due to the wrong type of slash for linux. 

### Steps to reproduce the issue

1. Add new Library from settings. Media Type: Podcast
2. Upload OPML file 
3. Add all podcasts 
4. Cry because you have to somehow remove all of those weird foldernames on linux and you have no clue how to escape a escape character 
<img width="1728" alt="Screenshot 2023-02-28 at 18 45 40" src="https://user-images.githubusercontent.com/24418303/221935027-f3d57346-f218-4135-970d-26b609ccdaad.png">

### Audiobookshelf version

2.2.12

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
This was fixed already if you update to the latest version.
