### ISSUE TITLE
[Enhancement]: AirPlay support for iOS App

### ISSUE THREAD

**Issue by peterpiglet** [advplyr/audiobookshelf#1572]
### Describe the feature/enhancement

Currently there is not AirPlay support in the iOS App. Would be greate to have that feature and just send the stream to speakers around the house as needed.

**Comment by advplyr** [comment]
Are you not able to see an AirPlay button when you swipe down? There is no button built-in to the app right now but I think you can still use AirPlay.

**Comment by peterpiglet** [comment]
Aaaah, yes. You are right, of course! I never went that way. Always through implemented buttons in other apps and therefore thought that the feature needs to be integrated.

Never mind this. I'll close it. Thanks :-)
