### ISSUE TITLE
[Bug]: Under Recently Added, Books with no series, Unrelated Option "Removie Series"

### ISSUE THREAD

**Issue by MrBearedJoe** [advplyr/audiobookshelf#1575]
### Describe the issue

Under Recently Added List
Books with no series: Under Options - "Remove Series from Continue Series"
Books with a series don't have this option.

![notseries](https://user-images.githubusercontent.com/43275672/222785657-47169658-0aea-4888-aad7-b944063d30be.png)

### Steps to reproduce the issue

1. Click Option on a book without a series Under the "Recently Added" list

### Audiobookshelf version

2.2.15

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
This is intentional because those items are not in continue series. That is only shown for items on the continue series shelf.

**Comment by MrBearedJoe** [comment]
Interesting. I refreshed the page without click on that option and it is no longer there. 🤷‍♂️

**Comment by advplyr** [comment]
I don't understand what you mean. If you go to the series there will be a button to re-add it to the continue series shelf.

**Comment by MrBearedJoe** [comment]
I got that option with no book on continue series shelf

**Comment by advplyr** [comment]
That option will only show for items on the continue series shelf. Are you able to see this option for items not on that shelf?

**Comment by MrBearedJoe** [comment]
The image able shows it's under recently added shelf. It is not a book that even has a series attached to it. I do no longer see it now for some reason.

**Comment by advplyr** [comment]
The menu will follow you when you scroll so the image doesn't necessarily show that it is for the recently added shelf.
Let me know if you can reproduce this though and we will re-open it.
