### ISSUE TITLE
Bug: Series filter based on progress not working

### ISSUE THREAD

**Issue by Mega-Volti** [advplyr/audiobookshelf#1577]
### Steps to reproduce

1. Switch to Series view in web interface
2. Set filter to "Series progress: not-finished"
3. Observe list auf series

### Expected behaviour
- Series that have been completely listened to (are finished) should not be displayed in the list.

### Actual behaviour
- Series that have been completely listened to (are finished) still are displayed in the list. They are even marked as finished with a green bar underneath, but still displayed.
- In general, setting the "Series progress" filter to anything does not change the displayes series at all.

### Environment data

Audiobookshelf Version: v2.2.15

**Comment by advplyr** [comment]
Fixed in [v2.2.16](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.16)
