### ISSUE TITLE
[Bug]: Editing the schedule for a podcast kinda broken

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1582]
### Describe the issue

If you open up a Podcast for editing, the Schedule tab does not update if you use the left/right icons to flip to other podcasts

### Steps to reproduce the issue

1. Open up a podcast for editing
2. Click the Schedule tab
3. Click left or right to another podcast
4. The schedule is still the one from the originally opened podcast

### Audiobookshelf version

2.2.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Handled in #1530 for next release

**Comment by advplyr** [comment]
Fixed in [v2.2.16](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.16)
