### ISSUE TITLE
[Bug]: Playback event is wrong

### ISSUE THREAD

**Issue by Demian98** [advplyr/audiobookshelf#1594]
### Describe the issue

Yesterday evening, I listened to an audiobook with a sleep timer of 15 min. But in ABS an event appeared with a listening time of 96 minutes.

Screenshot from the event:
![2023-03-09_09h25_32](https://user-images.githubusercontent.com/77210091/223964604-5f08ac54-6730-439f-83a8-3df63cb2ea53.png)

Screenshot from the App player history:
![Screenshot_20230309-092254_audiobookshelf](https://user-images.githubusercontent.com/77210091/223964663-d002d199-ea0e-4ec4-aabf-7672037c7823.jpg)

Some background information:
- Somewhere in-between the 15 min I enabled offline mode on the phone.
- I often skipped some seconds from the audiobook.
- Nothing else was listened from me on this whole Day. Not in the App nor the web player.

### Steps to reproduce the issue

Just listen as described above :)

### Audiobookshelf version

2.2.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you see when the playback session was started? Maybe the playback session was opened the day before

**Comment by advplyr** [comment]
Ah yeah, thanks for confirming that. This is a known issue and there is a issue already #1445

We are going to have to come up with a new data model for playback sessions
