### ISSUE TITLE
[Enhancement]: Add "Updated" to the Series Sort Options

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#1595]
### Describe the feature/enhancement

This is to make sure that the series that had the latest book added to it, comes on top (or bottom) when sorted by "Updated"...

![image](https://user-images.githubusercontent.com/42061703/224004908-21c1b9ee-cbc3-4260-b4f0-8d0871187ef0.png)

The series may have been added a while back, but a newly released book could have been added recently.

**Comment by advplyr** [comment]
Added in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)
