### ISSUE TITLE
[Bug]: When adding books, drag and drop onto the upload panel works fine, but I cannot add books by selecting from the same place or any place.

### ISSUE THREAD

**Issue by oboe45** [advplyr/audiobookshelf#1596]
### Describe the issue

I am able to add books without issue by dragging and dropping 1 or many files to the displayed add files panel.  I cannot however select books and add them that way.  It seems to allow the selection, but the upload never happens

### Steps to reproduce the issue

1. Select upload
2. Select “choose files”
3. Locate and height the files, 
4. Click return

Nothing happens

### Audiobookshelf version

V2.2.16

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I just tested this and was able to upload. What do you mean when you say nothing happens? The button doesn't respond or it freezes or the books doesn't show up?

**Comment by oboe45** [comment]
button does not respond, the books are not added, there in no list of books
to add as in the drag and drop method.

**Comment by oboe45** [comment]
I uplloaded about 1200 audio books yesterday - could not get it to work
except by using drag.  AFter your email today, i tred again and was now
able to add books by selecting the books or folder method.  Other than a
reboot, nothing different from yesterday - it clearly works!

Thanks for prompt response

**Comment by advplyr** [comment]
Glad it is working now for you. Hopefully just a one-off kind of thing.
