### ISSUE TITLE
[Enhancement]: Support Matroska Audio files

### ISSUE THREAD

**Issue by YodaDaCoda** [advplyr/audiobookshelf#1597]
### Describe the issue

I have an audiobook with Matroska Audio files (`.mka` extension). Audiobookshelf flags this book in the "Issues" panel saying "Item has no audio track & ebook".

### Steps to reproduce the issue

1. Have an audiobook consisting soully of matroska audio files (`.mka` extension)
2. Observe the presence of this book in audiobookshelf's Issues panel.

### Audiobookshelf version

v2.2.16

### How are you running audiobookshelf?

Docker

**Comment by YodaDaCoda** [comment]
Additional info:

`ffprobe` shows a Matroska/WebM file with one audio track with the Opus codec.

```
Input #0, matroska,webm, from 'redacted':
  Metadata:
... redacted
  Duration: 01:21:57.79, start: -0.007000, bitrate: 71 kb/s
  Stream #0:0: Audio: opus, 48000 Hz, mono, fltp
    Metadata:
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 01:21:57.794000000
```

**Comment by advplyr** [comment]
Added in [v2.2.17](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.17)
