### ISSUE TITLE
[Enhancement]: Per-chapter time remaning

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1598]
### Describe the feature/enhancement

When listening to a book that is separated by chapters, it would be nice to have the option to have the time line display time left in the current chapter instead of time left of the whole book.

**Comment by nichwall** [comment]
Do you mean like this? This can be done by changing the view in the player using the three dots in the upper right corner. You can toggle both the full book and chapter track individually.

![Screenshot_20230310-123508.png](https://user-images.githubusercontent.com/5686638/224411539-01d7f098-ef9d-4fe3-b4c6-87b3ab1f9e31.png)

**Comment by ScuttleSE** [comment]
Yep, that's absolutely it, can't belive I missed that one :D
