### ISSUE TITLE
[ENHANCEMENT] splitting multiple authors by "&" 

### ISSUE THREAD

**Issue by rubbo898** [advplyr/audiobookshelf#160]
As per issue #103, splitting multiple authors by "&" would be very useful

**Comment by advplyr** [comment]
This was released in [v1.6.0](https://github.com/advplyr/audiobookshelf/releases/tag/v1.6.0).

This works with both Last, First and First Last. All of the following naming conventions will work:
`Friedman, Milton & Friedman, Rose`
`Milton Friedman & Rose Friedman`
`Friedman, Milton, Friedman, Rose`
`Milton Friedman, Rose Friedman`

Supporting multiple authors in the filters is still on the to-do list.
