### ISSUE TITLE
[Enhancement]: Multiple "instances" of books

### ISSUE THREAD

**Issue by Travillion** [advplyr/audiobookshelf#1601]
### Describe the feature/enhancement

I would love if ABS could manage different "instances" of the same book, with their own listening history and progress.
My wife and I have our own accounts and our own devices, but my children do not. For my children, I usually cast books for them. Sometimes they are listening to the same book, but separately. For this reason, it would be really handy if ABS had the option to create separate instances of the book, so my son and daughter's progress can be tracked separately.
I imagine there could be a single button on a book's page that, when pressed, opens a window allowing you to add/select/delete instances.

**Comment by hobesman** [comment]
The app is pretty good at switching accounts. For me I just created a separate account for my kids and I switch my phone to that account when I want to play something for them.

Tap "log out" and get this. The button says add new server, but it can be the same server and just a different account.

![Screenshot_20230311-182516_audiobookshelf](https://user-images.githubusercontent.com/29721765/224520748-41059c7d-b407-4ed3-9c75-a56efa6cd872.jpg)

**Comment by Travillion** [comment]
That's a great tip, and is a good work-around. I still think it would be
easier from a user's perspective to be able to just switch instances of a
book. Then I don't run the risk of accidentally starting my books in the
wrong the account and having to fish around for where my progress is.

**Comment by advplyr** [comment]
This would make things much more complex with our data model. One of the primary purposes for having user accounts in Abs is to solve this very problem. I can see how in certain cases it wouldn't be convenient to switch users, but implementing something like this would require a large development effort outweighing the minor benefit.
