### ISSUE TITLE
[Enhancement]: Add a way to clear all chapters without replacing them

### ISSUE THREAD

**Issue by maskoficarus** [advplyr/audiobookshelf#1603]
### Describe the feature/enhancement

I have found that some of the audiobooks in my collection don't have accurate chapters available in the lookup or I can't find the correct ASIN. Many of these they were originally split into multiple files solely to reduce the file size, so the tracks don't correspond with chapters. In cases like these, I'd prefer just to clear all chapter data rather than include something wrong. 

Currently, the only way to clear all of the chapter data is:
1. Click Edit Chapters.
2. Click Remove Chapter repeatedly for every chapter listed.
3. Set the only remaining chapter to 00:00:00.
4. Click Save.

I imagine a single "Delete All" button, placed to the right of the Lookup button could reduce the amount of clicking required. 

If there's no plans for anything similar to this in the near future, I'd be happy to take a look myself.

**Comment by advplyr** [comment]
![image](https://user-images.githubusercontent.com/67830747/232346460-5eeb45eb-11af-45c9-a7b1-b290c6122e58.png)

**Comment by advplyr** [comment]
Added in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)
