### ISSUE TITLE
[Enhancement]: Show cover comparison information when manually matching

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#1605]
### Describe the feature/enhancement

Similar to comparing proposed vs current author, title, etc. when matching, it would be nice to be able to compare current vs proposed cover image. 

E.g. if the current one has no banner, but the proposed match has the audible banner, I'd like to be aware before accepting the matched cover. Currently I'd have to cancel the match, go back to the cover tab or close the edit window to see the currently active cover.

And the other part of comparing for such a decision is the resolution. It would be nice if it showed the resolution of the current and proposed images. If my current one has no banner but it's 100x100 resolution, and the proposed one is 2400x2400 but has a banner, I might just take the banner version anyways, if I know the rest of the image is that much better quality.

**Comment by advplyr** [comment]
![image](https://user-images.githubusercontent.com/67830747/229247198-7c7b7763-37f4-43b1-a193-c16afdf4b7ca.png)

**Comment by hobesman** [comment]
Nice! And sorry for the duplicate post. Apparently my memory isn't what it used to be...

**Comment by advplyr** [comment]
Hah, no problem

**Comment by advplyr** [comment]
Added in [v2.2.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.18)
