### ISSUE TITLE
[Enhancement]: PDF viewer📖

### ISSUE THREAD

**Issue by 4volodin** [advplyr/audiobookshelf#1608]
### Describe the feature/enhancement

I would like to look at a cool JS library PDF viewer [https://mozilla.github.io/pdf.js/](url) 
like in nextcloud [https://apps.nextcloud.com/apps/files_pdfviewer](url) or
like in kavita [http://kavitareader.com](url)

**Comment by advplyr** [comment]
We have a PDF viewer and it is using the same library pdfjs. You must enable experimental features in the settings page.

**Comment by 4volodin** [comment]
Yes
I have enabled experimental features but pdf viewer doesn't have the same functionality like kavita or nextcloud
