### ISSUE TITLE
[Enhancement]: Authors page pagination

### ISSUE THREAD

**Issue by Dr-Blank** [advplyr/audiobookshelf#1615]
### Describe the feature/enhancement

A major point for posting this issue was the load time for the authors' section.

Contrary to the library and series sections, authors section has a longer load time for my library. The issue, I guess, is that it is trying to **fetch all the images of all the authors at once**, unlike other sections where the images are fetched as you scroll.

Minor Things: 

1. Another thing which could cause higher load times for other sections, as the library grows, would be the **lack of pagination**. While inspecting the network calls, I saw that all the metadata of every book in the library is fetched at once, and the covers are fetched as we scroll. This is good for load times now but could become worse with size even though it is only text.

2. Even within the response of the calls, I noticed that **everything** about the books **everywhere** in the library is returned **all at once** (sorry :P), which is not displayed on the library section, like the description, genre, etc. Getting rid of this unnecessary data would also improve performance.

`v2.2.17`

**Comment by advplyr** [comment]
The library page doesn't fetch all books at once, that api endpoint is paginated. The library page also doesn't load the full details about the book, this is a condensed version but could maybe be condensed down further.

I agree the authors page needs pagination.

**Comment by Dr-Blank** [comment]
> The library page doesn't fetch all books at once, that api endpoint is paginated. The library page also doesn't load the full details about the book, this is a condensed version but could maybe be condensed down further.

I am so sorry I overlooked the details; the library items call is indeed paginated.

for my other point
I meant that the call below
`/api/libraries/lib_ulikw8mlitmd9a6/items? Filter=issues&sort=media.metadata.title&desc=0&limit=100&page=0&minified=1&include=rssfeed`

fetches the description, tags, path, addedat, folderid, mtime, ctime, birthtime, publisher, etc. 

Another Idea would be to use this fetched info in some form, like on hover, it could show some extended info about the book, like audible shows reviews on hover.
