### ISSUE TITLE
BUG/ENHANCEMENT: Make web UI "responsive"

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#162]
This app is SO good! I use the webui for everything. (the native android app seems to be far behind in feature parity last time I checked.)

However, I've noticed that there are several pages and modals that I can't access without increasing the webpage size or rotating the screen (when on a mobile).

I have some examples posted below.

![image](https://user-images.githubusercontent.com/25695143/139540602-c3e655e4-3b77-4113-af0d-472421906f27.png)
 
![image](https://user-images.githubusercontent.com/25695143/139540837-40744f1b-3f1b-4eb4-82ee-c8d3f9991352.png)

![image](https://user-images.githubusercontent.com/25695143/139541048-0308d77f-e79e-4db2-9950-3afb603c0369.png)

![image](https://user-images.githubusercontent.com/25695143/139541063-5829cae8-f56a-4fd2-98bf-f59e18e52e50.png)

You can see a few issues in the two  previous examples: the settings "cog" icon is visible only when the phone's screen is oriented to landscape mode. While in portrait mode, the "cog" is invisible. The same applies to the user details button that's next to the "cog".

Another issue is that I am unable to interact with some items that are covered by the "floating" menu no matter which way the screen is oriented (or if the windows is too small, while on desktop). For example, I have no way of toggling backups on or off, or changing the backup count. Regardless of orientation.

These next two images demonstrate another little wrinkle in your otherwise highly usable webUI: I cannot scroll down to access the logout button while in landscape mode on my phone. So, I have to turn the screen in to portrait mode to access that button.

![Screenshot_20211030-102724775](https://user-images.githubusercontent.com/25695143/139541577-60639ddf-5a8c-4992-bd1c-47933729fb3b.jpg)

![Screenshot_20211030-102735533](https://user-images.githubusercontent.com/25695143/139541571-2b9f621a-2453-406f-b1c3-fa4e0d71e3f5.jpg)

These fairly constant back and forth switches to landscape, portrait and scroll guessing leave the un-technical user in a struggle or scratching their head.

The native android app is okay. But, I've found that it's MUCH easier to just create a new username/password and tell someone to use those credentials on my website. (No setting up an app required). This means that they'll have to rely on the webUI. Which feels like it's only a few tweaks away from being FANTASTIC!

But, that's just me. What do _**you**_ think?

**Comment by advplyr** [comment]
I haven't even looked at the web app on mobile yet. There will be some elements of the web app that will need to be completely re-designed to have it looking nice on mobile.
I think it's a worthy task though. Are you able to stream and download okay from the web app?

**Comment by advplyr** [comment]
If progressive web apps were a bit further along then I would have just made one progressive web app, that would have been nice. But unfortunately things like managing downloads, and showing a player on the home screen when the phone is asleep, are just not possible with PWA's yet.

**Comment by juriroemer** [comment]
I second this, I would love to use the web app on my iPhone (as long as there's no iOS app - which could also be a reason to have the sleep timer in the web app aswell, #165 ) - which isn't possible right now. Besides the UI elements being all over the place, it doesn't load the progress or play/stream at all.


![IMG_0651](https://user-images.githubusercontent.com/31971585/140169047-8e0d4df9-decc-4ede-899b-b037951b59df.PNG)

**Comment by Kudjo-Grand** [comment]
I was thinking the same thing about the sleep timer being useful on the web app, because I use it almost exclusively. #165 

The web app is SOOO good! This would be the cherry on top.

Also, (in case it helps) my brave browser shows controls for play and pause (no tracking, as you mentioned) while using the web app. So, at least there's that. (Android 11. I'll have to check other versions soon)

![Screenshot_20211103-212051660](https://user-images.githubusercontent.com/25695143/140305414-afd45c8f-c699-4192-adf8-2f3d113c8f15.jpg)

**Comment by advplyr** [comment]
I got started on this and just pushed `v1.6.5`.

Bookmarks and chapters are hidden right now in the audio player. The audio player will need an overhaul to work nicely on mobile, I will use the same design used in the mobile app.

Tooltips need to be disabled still, there is a bug with there. I think I missed a few pages in config also.

Let me know what you think so far. I'm going to make this a Progressive Web App, so it will function more like a mobile app.

**Comment by juriroemer** [comment]
Tested this on both Android and iOS (Chrome on both).
UI looks great, it also works great on Android, but it won't load progress, playtime or play on iOS.

![2125ACC2-62AD-42AA-B2D8-5EE9A2D4EABA_1_201_a](https://user-images.githubusercontent.com/31971585/140953066-7d352755-77c8-4475-93ca-fddd718136c1.jpeg)

**Comment by advplyr** [comment]
@juriroemer I confirmed the iOS bug and will handle that in #180 

The UI is responsive enough on mobile we can open up a new issue if anything comes up specifically on mobile.

Thank you all for testing! Hopefully the iOS issue can be resolved easily.
