### ISSUE TITLE
[Bug]: Chapters populated from embedded tags do not respect colons (:).

### ISSUE THREAD

**Issue by chyron8472** [advplyr/audiobookshelf#1628]
### Describe the issue

Chapter tracks using colons in their id3 Title tag do not have the colon displayed in ABS.

### Steps to reproduce the issue

1. mp3tag:
![image](https://user-images.githubusercontent.com/12549803/226669949-096bd3be-7501-4438-bf4b-327c8ca2cbf4.png)

2. audiobookshelf, Chapters tab:
![image](https://user-images.githubusercontent.com/12549803/226671134-593afc13-d46a-4b1b-918f-6a004ed99f4a.png)

### Audiobookshelf version

v2.2.17

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Looks like it didn't use the title tag at all. Is your audio file named the same as the chapter?

**Comment by chyron8472** [comment]
The chapters listed in ABS were the filenames. I did a Rescan and it correctly repopulated the chapter titles using the id3 tags,

**Comment by advplyr** [comment]
This is because you have prefer audio metadata scanner setting enabled
