### ISSUE TITLE
[Enhancement]: Stats improvement on stats page

### ISSUE THREAD

**Issue by xAaeEx** [advplyr/audiobookshelf#1637]
### Describe the feature/enhancement

Hey @advplyr ,

I was looking for a way to make the stats a bit more readable like the way audible does it.
Right now I can't compile the client locally but I created a snipped where you can see the way I would like to convert the data for the UI:
https://jsfiddle.net/1yfdb3tx/

I found another issue #1199 where another suggested more or less the same thing. What do you think about this?
When I get the code compiled I create a Pull-Request for you to look at.

Kind regards

**Comment by advplyr** [comment]
Hey, sure I'm open for anything. If you want to chat about it you can join the Discord or Matrix server.

**Comment by advplyr** [comment]
I'll close this out since it is the same as #1199 so feel free to chat in that thread or chat in the servers.
