### ISSUE TITLE
[Enhancement]: Recognize the CDEK tag.

### ISSUE THREAD

**Issue by filviu** [advplyr/audiobookshelf#1640]
### Describe the feature/enhancement

Libation - a nice tool that allows backing up audible purchases writes the ASIN inside the `CDEK` tag for m4b files reasoning that it's the same tag Audible uses: https://github.com/rmcrackan/Libation/issues/557 For mp3 they use `AUDIBLE_ASIN`

My first thought was to script something to copy from CDEK to com.apple.iTunes:ASIN but either I'm too thick or I can't find the right tool but I tried mp4v2, AtomicParsley and exiftool and the only one that did write the tag was AtomicParsley but it's very, very slow. 

So to make it short - would it be terribly complicated to also recognize the CDEK tag for the ASIN ? 

Alternatively - since it's possible - would it be any way to specify  the ASIN in the file name ?

Cheers!

**Comment by advplyr** [comment]
We use ffprobe to read the meta tags. If you can check what the ffprobe output is for an m4b and an mp3 that would be helpful.

`ffprobe -i audiofile.m4b -show_format -print_format json`

You can do this from inside the docker container since ffprobe is installed in the container.

**Comment by filviu** [comment]
Hm,

So mp3 was easy the tag shows under `AUDIBLE_ASIN`: https://pastebin.com/QhXUehRd

For the m4b on the other hand doesn't show the CDEK tag:  https://pastebin.com/Nn9BZjtw

AtomicParsley does show it:  https://pastebin.com/emw9TjXH but I couldn't find a way to convince ffprobe to show those tags - either it can't or I didn't find how...

So I'm not sure it's possible...

**Comment by advplyr** [comment]
Yeah unfortunately ffprobe has limitations with mp4 metadata. Here it is in code https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mov.c#L310

I added the `AUDIBLE_ASIN` support for mp3.

I don't see a good way to switch from ffprobe because ffprobe is the best at getting the codec info. I was going to add support for tone library in the scanner but then we would need to use both ffprobe and tone which would be very slow.
If there is an alternative to ffprobe I'm open for that

**Comment by advplyr** [comment]
Added in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)

**Comment by damajor** [comment]
> I don't see a good way to switch from ffprobe because ffprobe is the best at getting the codec info. I was going to add support for tone library in the scanner but then we would need to use both ffprobe and tone which would be very slow.
> If there is an alternative to ffprobe I'm open for that

Did you at "mediainfo" ?
