### ISSUE TITLE
[Debian] Cannot embedded Metadata in audio tracks 

### ISSUE THREAD

**Issue by derkington** [advplyr/audiobookshelf#1643]
### Describe the issue

Metadata is not written to audio tracks. 

1) Expected Metadata to be written to the track and be visable when read by MP3tag or MusicBrainz applications.
2) The UI to report a failure if the process fails (especially if the failure is written to the log). Currently it reports that the process is finished with a green tick, which you would assume means sucessful.

![Capture](https://user-images.githubusercontent.com/80588965/229338993-8b53364a-91dd-4812-9bad-7fe3d7be3b7e.JPG)
![Capture2](https://user-images.githubusercontent.com/80588965/229338998-d3482842-f36b-4edf-986f-7c51a6fb5409.JPG)

### Steps to reproduce the issue

1.  Via Audiobookshelf web UI as root user
2. Locate target audiobook
3. "Match" file to get Metadata
4. Via "Tools> then the Metadata Manager
5. Click "Start Embed Metadata"

Note I have tried the following
- Removed and reinstalled Audiobookshelf (keeping only my config)
- Created a seperate library, copied the file to a new directory with open permissions (777)
-  Have tried diffrent files (MP3 and MP4)

### Audiobookshelf version

v2.2.17

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Does that path in the error log exist? The one starting with `/tmp/Process/..`?

Can you check the config file at `/etc/default/audiobookshelf`, it should include TONE_PATH

by default it is `TONE_PATH=/usr/lib/audiobookshelf-ffmpeg/tone`

If that is in your config then can you make sure that the `tone` binary exists in that folder?

**Comment by derkington** [comment]
**Does that path in the error log exist? The one starting with /tmp/Process/..?**

Yes, I created it so that I could play around with directory and file premissions to exclude that as an issue. This directory has full read,write, execute permissions. I also created a library and pointed it at this location which works fine and finds the files I have tested this issue against.

**Can you check the config file at /etc/default/audiobookshelf, it should include TONE_PATH**

It does.

cat /etc/default/audiobookshelf 

METADATA_PATH=/usr/share/audiobookshelf/metadata
CONFIG_PATH=/usr/share/audiobookshelf/config
FFMPEG_PATH=/usr/lib/audiobookshelf-ffmpeg/ffmpeg
FFPROBE_PATH=/usr/lib/audiobookshelf-ffmpeg/ffprobe
TONE_PATH=/usr/lib/audiobookshelf-ffmpeg/tone
PORT=13378
HOST=0.0.0.0

by default it is TONE_PATH=/usr/lib/audiobookshelf-ffmpeg/tone

**If that is in your config then can you make sure that the tone binary exists in that folder?**

It does.

/usr/lib/audiobookshelf-ffmpeg/tone -v
0.1.2

ls -lh tone 
-rwxr-xr-x 1 1001 avahi 26M Nov  4 23:33 tone

**Comment by advplyr** [comment]
Can you try using tone directly?
It would be like
`/usr/lib/audiobookshelf-ffmpeg/tone dump /tmp/Process/...`

**Comment by derkington** [comment]
That all works fine.  The tone binary can be run by any user.

![image](https://user-images.githubusercontent.com/80588965/230179950-1ddf3480-09d0-451f-9a20-ce95a49070d1.png)

**Comment by advplyr** [comment]
I found the issue, will be fixed in the next release

**Comment by advplyr** [comment]
Fixed in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)
