### ISSUE TITLE
ENHANCEMENT: Sleep Timer

### ISSUE THREAD

**Issue by limitlessbritt** [advplyr/audiobookshelf#165]
First off love this project and the app! 

It would be nice to have a sleep timer in the web player and in the mobile app. Something with either pre-defined times or let the user set the times.

Thanks!

**Comment by advplyr** [comment]
Just released a sleep timer on the mobile app yesterday. https://github.com/advplyr/audiobookshelf-app/discussions/24
Let me know if that is what you were looking for.

I'm not sure it would be used in the web app, wouldn't your computer sleep on its own?

**Comment by limitlessbritt** [comment]
I just tested the mobile app and yes thats what I'm looking for. 

For the web app it was for devices where I can't install the mobile app so I would just use the web app to play audiobooks.

**Comment by advplyr** [comment]
Added a basic sleep timer in [v1.7.2](https://github.com/advplyr/audiobookshelf/releases/tag/v1.7.2)

If you have improvements please open a new issue!
