### ISSUE TITLE
[UI]: Show "abridged" only when true.

### ISSUE THREAD

**Issue by Dr-Blank** [advplyr/audiobookshelf#1656]
### Describe the feature/enhancement

Since abridged is of type Boolean, it can be shown/hidden based on the value. Right now the metadata feels unnecessarily long and abridged = no seems like it is adding no value.

I would suggest something like a pill (see below) as a solution to show abridged only if it is so, or the tag can contain the text itself, whether it is abridge or unabridged, getting rid of the extra yes and no. looks nice too imo.

![image](https://user-images.githubusercontent.com/64108942/230758348-fb21b313-024d-4d42-b38a-8766422f6db0.png)

**Comment by sumitshinde-84** [comment]
i would like to work on this issue can you please assign it to me ?

**Comment by Dr-Blank** [comment]
On second thought, I think that space would be better suited for tags and labels as they are not in the ui as of now, see below for another rendition.

![image](https://user-images.githubusercontent.com/64108942/230759128-582f1c98-f75c-4d32-a4c2-fb676ed5a3b9.png)


I used the same classes for both of the pills which if slightly different but in align to the theme, should look better.

**Comment by skronenwerth** [comment]
Personally, I would prefer to see unabridged when the abriged flag is not set. What do you think?

**Comment by Dr-Blank** [comment]
> Personally, I would prefer to see unabridged when the abridged flag is not set. What do you think?

@skronenwerth for me it is the opposite. 99% of my library contains unabridged books :D

**Comment by skronenwerth** [comment]
> > Personally, I would prefer to see unabridged when the abridged flag is not set. What do you think?
> 
> @skronenwerth for me it is the opposite. 99% of my library contains unabridged books :D
> 
> But it can be both, always enabled, showing the type.

@Dr-Blank For me, too, about 99% are unabridged. I mean, however, that when setting the flag abridged and when not setting the flag unabridged is displayed. I think that I had expressed myself misleadingly.

**Comment by advplyr** [comment]
I wasn't sure how to display it so I did it that way in the hopes someone would come with some better suggestions.

I'm still not sure but here is how explicit flag is displayed. I'm hovering over it in this screenshot which shows the tooltip.

![image](https://user-images.githubusercontent.com/67830747/230775709-b97775c6-5c39-4be1-b63d-3c6a43bf6b9b.png)

If we put this next to the book title then I don't think we should show the word "unabridged".
If you don't see the word "abridged" then you can just assume it is unabridged.

@sumitshinde-84 sure

**Comment by Dr-Blank** [comment]
I completely forgot about the explicit tag. Will have to come up with some new to accommodate both.

**Comment by Dr-Blank** [comment]
@advplyr 
> I'm still not sure but here is how explicit flag is displayed. I'm hovering over it in this screenshot which shows the tooltip.

Why not just line them up next to each other? I mean how often is a book abridged and that too explicit at the same time? Even if that is the Case, the "e" doesn't seem to take up much space.

Or maybe we could place a similar "🄰" next to the existing 🅴 which on hover showed a tooltip of "abridged" like explicit. Now these Unicode do not match up entirely, so maybe we need a custom svg for that, let me know if you need help with those, in case you decide to process with that. I found this font which somewhat resembles those Unicode characters but it is not perfect, [here](https://www.dafont.com/inversionz.font) it is (not sure about the copyright though).

 
> If we put this next to the book title then I don't think we should show the word "unabridged". If you don't see the word "abridged" then you can just assume it is unabridged.

yup

**Comment by advplyr** [comment]
I like the idea of just using an "A" SVG. I think we'll want to use an SVG because some browsers won't render some unicode characters.

**Comment by advplyr** [comment]
![image](https://user-images.githubusercontent.com/67830747/232258776-cb7211aa-cc5c-46ef-ab3c-8a6038f03d74.png)

**Comment by advplyr** [comment]
Updated in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)
