### ISSUE TITLE
Library Management: Lock metadata fields or the entire book.

### ISSUE THREAD

**Issue by Dr-Blank** [advplyr/audiobookshelf#1658]
### Describe the feature/enhancement

As we go along and introduce tools that will help manage the library automatically, there will be a need to prevent some manually edited fields/chapters/covers getting overwritten [like plex does it](https://support.plex.tv/articles/201272763-edit-details/#:~:text=LOCKING%20AND%20UNLOCKING).

One of the issues which happens now is that I edit some books which are on audible but not the exact same version, it is slightly tweaked, and if I were to accidently refresh metadata, it will get overwritten and lost (quick match, because in match you can control what field get overwritten). So, I have to remember to only quick match books I know I haven't edited.

Any field user edits manually, gets locked from any future changes made by automated tasks, only another edit from user can change it.

This feature could extend to chapters too, if user sets the chapters using the edit page (doesn't matter if shifted or fetched form audible, the final save button determines if it was user action), they should be locked, until edited intentionally by user. If a user wants automatic chapter fetching, as being talked in #1580 , one could freely just click "refresh chapters for all library" without worrying about their manually edits, same would apply for metadata.

**Comment by advplyr** [comment]
Duplicate of #928?

**Comment by Dr-Blank** [comment]
It's weird searching for "lock" in the issues search did not bring that up. 

Yes, it is the same feature request with the only difference being the highlighted use case, re-scan vs quick match and all future metadata refresh.

closing this as it is a duplicate indeed.
