### ISSUE TITLE
[Bug]: Missing German translation for Abridged

### ISSUE THREAD

**Issue by szemlicka** [advplyr/audiobookshelf#1661]
### Describe the issue

Latest Docker container:

The new field Abridged translation (German) is missing. 
Abridged = gekürzt
Unabridged = ungekürzt

...:-)

### Steps to reproduce the issue

1. Always there. Switch to German translation will not translate the new field

### Audiobookshelf version

2.2.18

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Thanks, this is already updated for the next release
