### ISSUE TITLE
[Bug]: Series Name dialog locks up web UI requiring reload of interface.

### ISSUE THREAD

**Issue by jessearmstrong** [advplyr/audiobookshelf#1663]
### Describe the issue

When attempting to add a Series Name and sequence number. The typeahead search will often freeze after a few characters are typed. Once this happens the changes can not be submitted. The Submit button doesn't function, nor does pressing the Return key. The only way to resume using the server is to reload the interface. 

### Steps to reproduce the issue

1. Click pencil icon on the book to be edited.
2. Click click the plus icon in the "Series" field to change the books series relationship
3. Type the new series name in the provided field. 
4. Once Typeahead freezes, no further action can be completed without reloading the page.

![Screenshot 2023-04-10 at 4 45 01 PM](https://user-images.githubusercontent.com/241981/231005466-5b1a4500-5d4d-4613-9442-e626c3d7a6f0.png)

### Audiobookshelf version

2.2.18

### How are you running audiobookshelf?

Docker

**Comment by jessearmstrong** [comment]
Here it is with a video. This series is sorted into "The Last Hunter" but the others I have on the server are sorted as "The Last Hunter Series" I was trying to get them all in the same series and set their sequence numbers. You can see in the video bottom left that I am on 2.2.18 Docker.


https://user-images.githubusercontent.com/241981/231012210-bdd4c1bb-6da5-47b5-88ac-2fe1f945e226.mp4

**Comment by jessearmstrong** [comment]
This error hits the console when it breaks:
TypeError: a is undefined
    NuxtJS 56
db5cefa.js:2:19085
![Screenshot 2023-04-10 at 7 18 19 PM](https://user-images.githubusercontent.com/241981/231023521-c623db2f-46d8-436e-8a2f-f1ab938da27f.png)

**Comment by jessearmstrong** [comment]
No idea why it is formatted like that, however.
It seems to happen the moment I hit the space bar after Typing "The"

**Comment by jessearmstrong** [comment]
I've been poking around on this a bit more and Strangely it only seems to happen when I start with the worth "The" If I use a different word to begin with it appears to work as expected and will allow me to type the word "the" after the first word.

**Comment by jessearmstrong** [comment]
So doing even more poking around, I think the issue might have been caused by some bad data (or funky characters of some sort) in one of the other series. I started cleaning up some of the other series names that were not very good and now it doesn't seem to be happening for me any more. I will report back if that changes, but I guess something was breaking the javascript in the typeahead search when matching to another series name that may have been malformed.

That is essentially a guess, but ¯\_(ツ)_/¯

**Comment by advplyr** [comment]
Ah ok. Let me know if you can find out what the series name was that was breaking this.

**Comment by methosinhiding** [comment]
I can actively reproduce this same issue on my ABS instance but have not had any further success isolating a root cause by looking at my series in the SQLite DB
a workaround so far has been to type the problematic series of characters in reverse order which hasn't seemed to encounter the triggering issue

**Comment by ScuttleSE** [comment]
Encountering this bug too

```
TypeError: e.name is null
    NuxtJS 75
522a7ce.js:2:19370

```

I's formatted the same way as in [this](https://github.com/advplyr/audiobookshelf/issues/1663#issuecomment-1502503399) post

**Comment by nichwall** [comment]
Writeup of the problem here https://github.com/advplyr/audiobookshelf/issues/3207#issuecomment-2306119057
