### ISSUE TITLE
[Enhancement]: Allow ebooks to be marked as a supplement

### ISSUE THREAD

**Issue by divyangbw** [advplyr/audiobookshelf#1664]
### Describe the feature/enhancement

ATM, for a library item with an ebook attached to it, you'll simply see "Read". There's 2 problems:

1. Sometimes audiobooks come with supplementary material in the format of ebooks. This is not the same thing as the actual ebook version of it.
2. Users will assume "Read" implies reading the actual ebook version of the audiobook.

Proposal:

Add a library wide setting to mark ebooks as supplements. For now, that will simply change the text from "Read" to "Supplement". 

This reduces confusion for something like my use case where I'll have a different library for the ebooks vs audiobooks.

I'm new to Vue so going to explore a bit before opening a PR (and of course see if there's better ideas). Here's what I have so far:

<img width="717" alt="Screenshot 2023-04-10 at 11 08 51 PM" src="https://user-images.githubusercontent.com/4261609/231046146-257f1ec9-eb99-4cdc-8c8e-b0292c05ef9e.png">

<img width="557" alt="Screenshot 2023-04-10 at 11 10 19 PM" src="https://user-images.githubusercontent.com/4261609/231046355-de7c9949-da30-4056-9add-418755112c6b.png">

**Comment by advplyr** [comment]
What about if we have an ebook that has supplementary material?
What about if we have multiple files that are supplementary?

One thing I had a while back was a read button in the library files table so you could have multiple ebook files and be able to read them.
![image](https://user-images.githubusercontent.com/67830747/231199080-7a033bc3-d37d-4dd5-977b-9fe301d2db85.png)

Maybe we have some way to mark an ebook as supplementary?

There is another feature request open that comes down to the user doesn't want ebooks to show at all. If we had a library setting like "Audiobooks only" then we automatically treat any extra ebook files as supplementary. This would solve both cases.

Just throwing some thoughts out there

**Comment by divyangbw** [comment]
> What about if we have an ebook that has supplementary material?

Yea, I considered that, and it took me down the path you described right after -- mark each individual file as supplementary. Problem is it becomes tricky since I wasn't sure how to consider something as a "main item". How do we update the UI to differentiate reading the main thing vs supp. Or what happens if some mp3 is tagged is supplement but in reality its a chapter. How does file scanning get affected by this. Etc. Lots of questions 😅

Don't have answers since I'm still in the process of understanding the source code, and don't want to blindly do something. Could limit it to just epub, pdf, mobi, etc first as well, and not worry about some of those questions above. I can definitely see this as an improvement to make in the future.

> What about if we have multiple files that are supplementary?

How do we currently handle multiple files when the library item is an ad? From a quick look it seems it picks the first file from the list and shows that reader. So regardless of the changes here, wouldn't we need to add better support for multiple files (like your idea around read button on the files table) first? I see that as a different feature 🤷🏽‍♂️ One that could affect what is done here when complete though.

> There is another feature request open that comes down to the user doesn't want ebooks to show at all. If we had a library setting like "Audiobooks only" then we automatically treat any extra ebook files as supplementary. This would solve both cases.

Hmm, so assuming we don't want a new type (instead of just "book"), I'm guessing you mean if there's no audio tracks, hide the item everywhere (including under home and series)? Yea, I could look into that. Can you link me the issue if you have it handy?

I'm curious if there's a need for hiding, but not marking attached as supplements. For example if I only want to show the item if the audiobook has been added, but the attached ebook is the text version of that book. This way one could start adding their ebooks while they wait on the audiobook.

**Comment by advplyr** [comment]
If there are multiple ebook files found then it will take the first one and create an `EbookFile` which gets stored on the `Book` object.

All the other ebook files just remain in the library files array on the `LibraryItem`. Basically any ebook file that is not an `EbookFile` attached to the book would be supplementary, if that makes sense. So, I don't think we would actually need a flag for it to be supplementary or not.

The ebook file that was actually created as an ebook could be marked as supplementary by just removing it from the `Book`. In that case maybe we would allow you to set an ebook file as the actual ebook if there isn't one already. That would solve the case where Abs marked the wrong ebook file as the ebook.

As I was typing this I realized it probably wouldn't make much sense so I think I'll have to put something together to show what I mean.

**Comment by KK4BitsPerSecond** [comment]
Support for supplements in the audiobook library would be nice. 

I have many audiobooks that came with PDFs of things like world maps and illustrations that I would love if I could access from the book in the audiobook library.

**Comment by advplyr** [comment]
Added in [v2.2.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.23)

There was a lot here so I put it in a guide https://www.audiobookshelf.org/guides/ebooks

**Comment by skyzuma** [comment]
the "problem" is, the entire book (audio / eBook)will display on deck but i can only play the audiobook (play button) ... maybe if is possible make 2 decks ? 1 for audiobook if  played and 1 for eBook if read? or make playbutton twice (if played) like play audio book (play button) / read book (read button)?

**Comment by skyzuma** [comment]
idk how github handle (re)edits and give every edit an notification or only once on its create ... have u read all the edits ? @advplyr

**Comment by advplyr** [comment]
Yes you can't just remove the ebook from Abs only. If you want to remove the ebook then manually move it out of the audiobook folder.
