### ISSUE TITLE
[Enhancement]: Author/Narrator seperator

### ISSUE THREAD

**Issue by AarynRobinson** [advplyr/audiobookshelf#1666]
### Describe the feature/enhancement

When manually entering Author and Narrator fields, a separator such as a comma could be used to separate names as separate entries, both as soon as typed and when copy-pasting.

**Comment by advplyr** [comment]
The problem with this is some users prefer to enter the author as "Last Name, First Name"

**Comment by advplyr** [comment]
Related https://github.com/advplyr/audiobookshelf/issues/1198

Can probably be merged with #1198

**Comment by advplyr** [comment]
Duplicate of #1198
