### ISSUE TITLE
[Enhancement]: Show more detailed info on audio files (e.g. Bit rate)

### ISSUE THREAD

**Issue by AarynRobinson** [advplyr/audiobookshelf#1667]
### Describe the feature/enhancement

I would really appreciate if the files tab showed more file info for each file, for example: Bit rate, Sample rate, Channels (Stereo, Mono), Codec, etc

**Comment by advplyr** [comment]
In the audio tracks table you can now open up more info
![image](https://user-images.githubusercontent.com/67830747/232346233-6fd6dae5-0137-40eb-8548-e643972f711a.png)

The more info modal
![image](https://user-images.githubusercontent.com/67830747/232346301-6f948f04-fff6-4654-b96b-bb5f9824efc0.png)

**Comment by advplyr** [comment]
Added in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)
