### ISSUE TITLE
[Bug]: Chapters in second .m4b files not detected

### ISSUE THREAD

**Issue by raubreywhite** [advplyr/audiobookshelf#1683]
### Describe the issue

What happened: When there are two .m4b files (e.g. `book.part1.m4b` and `book.part2.m4b`) the characters are only extracted from `book.part1.m4b` and are ignored from `book.part2.m4b`.

In the below example, chapters 1-27 come from `WoT 05 - The Fires of Heaven p1.2.m4b` while nothing is shown from `WoT 05 - The Fires of Heaven p2.2.m4b`.

![E4086D89-D3F5-4A7C-8E2C-6C923E4FEF25](https://user-images.githubusercontent.com/1532091/232508194-8fb0ec18-8d88-4b59-97a7-a774a71f1fb6.jpeg)

### Steps to reproduce the issue

1. Have an audiobook that corresponds to two .m4b files with multiple chapters in each of them.

### Audiobookshelf version

2.2.18

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Did you recently add that audiobook? A few versions ago support was added to pull in chapters from multi-track audiobooks

**Comment by raubreywhite** [comment]
Ah that solved it! You are correct, these were old books. I deleted them and readded them and it solved the problem. Thank you!
