### ISSUE TITLE
Enhancement: Ignore list for library

### ISSUE THREAD

**Issue by VladoPortos** [advplyr/audiobookshelf#169]
Would it be possible to add ignore “folders” files in library folder ?

Mainly, for example **.Recycle.Bin** when the library is on samba share, deleted files get stored there for time, but app will pick them up anyway.

Thanks.
Love the app !

**Comment by advplyr** [comment]
How about having the scanner ignore files/folders that start with a "."
I think that is standard procedure.

**Comment by VladoPortos** [comment]
@advplyr yea that should be enough :)

**Comment by advplyr** [comment]
Just pushed `v1.6.7` that ignores directories and files that start with "."
