### ISSUE TITLE
[Bug]: when previewing a "Match", Genres do not autocomplete

### ISSUE THREAD

**Issue by wtanksleyjr** [advplyr/audiobookshelf#1690]
### Describe the issue

When editing Genre in the Match editor, autocomplete is partially present, but doesn't connect to the normal list of Genres available in the regular book editor -- it only allows autocompletion of already-present Genres (which of course isn't allowed). It would make more sense if either it would include full autocompletion (allowing me to check whether what I've typed matches a genre I used in the past).

### Steps to reproduce the issue

1. I click on a book's "..." button, choose Match from the dropdown
2. Wait for match to load, click the correct matching data
3. Edit Genre. Type in something, notice that autocomplete only works to complete genres already present in the list.

### Audiobookshelf version

2.2.18

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.20](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.20)
