### ISSUE TITLE
[Enhancement]: Allow deleting a duplicate tag from Genre or Tags

### ISSUE THREAD

**Issue by wtanksleyjr** [advplyr/audiobookshelf#1691]
### Describe the feature/enhancement

Currently, books can be imported with duplicate tags in at least Genre and at least using OPF, but if the user tries to delete one of the duplicates both will vanish. I'd rather have only one of the duplicates vanish. (Alternately, of course, the OPF importer could deduplicate those fields. I don't know if other importers would also suffer from that.)

**Comment by advplyr** [comment]
Tags, authors, narrators, genres should all be removing duplicates now no matter what source they are coming from. Let me know if you still find these coming in though.
