### ISSUE TITLE
[Bug]: Some Opus/mka audiobooks are silent

### ISSUE THREAD

**Issue by YodaDaCoda** [advplyr/audiobookshelf#1693]
### Describe the issue

I have a number of audiobooks in Opus format encapsulated in Matroska with mka extension. These audiobooks will often stream, but the audio is silent and no errors are visible.

I believe the issue relates to the flags passed to `ffmpeg` when generating the hls files - attempting to play the resulting files in VLC gives an error about timestamps. I was able to get the ffmpeg command from ABS's logs and after some modifications (removing random flags related to timestamps) produced hls files that would play without error, but I couldn't seem do this consistently so I'm not sure if it was my messing with cli flags that did something, or if there's some inherent randomness to the hls generation and sometimes it works and sometimes it doesn't.

Happy to jump on discord to discuss & share problematic files.

### Steps to reproduce the issue

1. Add an audiobook in mka/opus format
1. Attempt to play the audiobook, observe that playback proceeds, but no sound comes out

### Audiobookshelf version

v2.2.19

### How are you running audiobookshelf?

Docker

Example audiobook that doesn't work: https://projectsend.yodadacoda.info/download.php?id=1&token=26JadKUZ3et3CoPREwHJY9CwZVSXuN5o

**Comment by itzexor** [comment]
This doesn't help with the issue at hand, which sounds like a transcoding problem. However, if you are not using ios clients, which don't support opus well and will rely on transcoding, then you can use mkvmerge to remux the opus mka into opus webm and the compatibility should go way up. in my experience opus webm is supported on web and android clients just fine for direct play. I did have issues in firefox linux when using ogg opus.

Personally, I mux in the chapter and other metadata during the mkvmerge to webm, so I'm not sure how well it will preserve it doing a pure remux, but it supports almost the same metadata as mkv.

I use something like this to convert .opus to .webm without a transcode:
`mkvmerge -o output.webm --webm --quiet --global-tags [matroska_simple_tags_file] --chapters [matroska_chapter_atoms_file] input.opus`

I assume omitting the tags and chapters parts _should_ work for your mkvs.

Hope it helps

**Comment by YodaDaCoda** [comment]
Interesting suggestion, thanks. I used ffmpeg to convert a non-working audiobook to webm (`ffmpeg -i ... -map 0 -c copy ....webm`) and the resulting files worked fine. Out of interest, I tried simply renaming the `mka` files to `webm` - that also worked.

I inspected the logs, and found that the ffmpeg command for `mka` files has `-c copy` while for webm files has `-c aac`. I would expect `mka` files to work without transcoding though.

**Comment by itzexor** [comment]
I would expect mka to work on android, but probably not anything else. The browser clients basically just use the html5 audio player api and that lacks support for mkv/a on all browsers as far as I know. ios probably doesn't support it either I'm not sure. Webm is a subset of mkv and is supported on all browsers afaik.

Renaming mka to wemb may work, and it may break randomly. Not all mkv/a features are supported by the webm specification.

Regarding the ABS command, transcoding is a fallback thing...if the client fails to play the file it just transcodes it to AAC no matter what the source is. -c copy means don't re-transcode just transfer the encoded stuff (remux), -c aac makes it a transcode to aac which is basically supported on everything.

**Comment by itzexor** [comment]
Also it _should_ always work on any client regardless of what the source file is, if the transcoding starts successfully... I don't have experience with that stuff though, so I can't help with that part of things. My suggestions are more along the lines of making more compatible files that just play on the clients without a transcode. iOS is always going to be an issue if you're using opus though.

**Comment by YodaDaCoda** [comment]
Yeah the audiobook I tested with happens to be mka that complies with the restrictions of webm/a so renaming wouldn't work in all scenarios but it works here, and it's interesting to note the transcode/remux behaviour appears to change depending on the file extension rather than the player's abilities (testing with the ABS app on Android in all scenarios).

**Comment by advplyr** [comment]
I'm not sure what to do here. Is this a bug in Abs or an issue with your encoding?

**Comment by YodaDaCoda** [comment]
Y'know, I'm not sure if it's ABS or ffmpeg. The encoding appears fine best as I can tell. Feel free to test with the public-domain audiobook I shared as an example in OP.

**Comment by advplyr** [comment]
Did you encode these audiobooks?

**Comment by YodaDaCoda** [comment]
I use [tdarr](https://home.tdarr.io/) to transcode my media library offline rather than having to transcode while streaming. It's had a huge impact on my Plex->Chromecast experience. I recognise I can (read: will) exclude or change the parameters for the audiobook library, but ABS might then still have issues with mka :)

According to the logs, the command for the attached book's files was:

`ffmpeg -i <infile> -metadata title= -map 0:0 -c:0 libopus -mapping_family:0 0 -map -0:d? <outfile>`

Update: after going back to my ABS server... the audiobook attached in OP actually plays fine. I wonder if it's due to a server restart (clearing some kinda cached state?). There's another mka audiobook that doesn't play if I seek, but does play from the beginning without issue. I seeked about an hour into the audiobook and left it "playing" (nothing was happening, current time wasn't progressing) and after about 10 minutes it started actually playing. I wonder if it's due to Matroska writing the index to the end of the file rather than the beginning. But I think this is a separate/different issue.

**Comment by advplyr** [comment]
I think we chatted about this in discord some. This is due to the encoding and not Abs but let me know if you think there is something that needs fixing in Abs.
