### ISSUE TITLE
[Enhancement]: Ability to restart ABS for Root/Admin level users

### ISSUE THREAD

**Issue by LynxCub** [advplyr/audiobookshelf#1698]
### Describe the feature/enhancement

sometimes doing a quick restart can help "break" the .lock issues.  

It would be helpful to do this when you don't have direct access to the host, but using web interface.

**Comment by advplyr** [comment]
How have you installed Abs?

**Comment by LynxCub** [comment]
Linux/docker/docker-compose - when I'm at a location where i have access to the box, i can easily enough do a sudo docker stop audiobookshelf.  It's when i'm away, and just using the web interface that i would like the ability to restart.

**Comment by nichwall** [comment]
Is this still needed since the migration to SQLite in version `2.3.x` which removes the lock files? I'm not aware of any issues that have been solved in the past year by restarting the server.

**Comment by nichwall** [comment]
Figures there would be weird problems fixed by restarting the container in 2.12.1 less than 3 days after I said that.

**Comment by advplyr** [comment]
Hah but no I don't think this is needed either way. I wouldn't know how to implement it either
