### ISSUE TITLE
[Bug]: Wrong episode is downloaded

### ISSUE THREAD

**Issue by update-freak** [advplyr/audiobookshelf#1699]
### Describe the issue

I wanted to download older podcast episodes, but it was downloaded an other podcast episode and not the selected one (see screenshots):
selected to download: Ist das Handy schlecht für uns? Jein!
this was downloaded: Was wirklich bei Pollen-Allergie hilft

![1](https://user-images.githubusercontent.com/40196995/232851237-c49759b7-a4c8-459b-bf62-da2dc938259c.png)
![2](https://user-images.githubusercontent.com/40196995/232851250-d1f0b630-9d69-4812-af05-348e060725da.png)
![3](https://user-images.githubusercontent.com/40196995/232851253-c991eaaf-4fa1-4732-b727-23b42d5e7581.png)

RSS feed URL: https://besserleben.podigee.io/feed/mp3
version: 2.2.19

### Steps to reproduce the issue

1. Add the feed url : https://besserleben.podigee.io/feed/mp3
2. Try to download an older podcast episode
3. Check the downloaded podcast episode

### Audiobookshelf version

 2.2.19

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Thanks, this has to do with the search filter. Until the next release you can avoid using the search filter.

**Comment by advplyr** [comment]
Fixed in [v2.2.20](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.20)
