### ISSUE TITLE
[Enhancement]: Smarter handling of genre, author, narrator metadata

### ISSUE THREAD

**Issue by deanishe** [advplyr/audiobookshelf#1700]
### Describe the feature/enhancement

When "Prefer audio metadata" and "Prefer OPF metadata" are both turned on, genres from the OPF file are ignored.

This is a problem because `ffprobe` doesn't support multiple values for tags and only returns the first one. So in practical terms, its support for multiple genres (and author/artist, narrator/composer) is broken.

Seeing as ABS supports multiple values for these fields, but `ffprobe` doesn't, could this situation be handled more intelligently? Perhaps genres could be merged? Or OPF metadata prioritised over tag metadata?

I'd prefer not to have to turn tags off and use OPF for everything.

**Comment by advplyr** [comment]
I'm not sure what you mean that ffprobe doesn't handle multiple tags. You can put multiple genres
