### ISSUE TITLE
[Enhancement]: Notification if filename/path is too long

### ISSUE THREAD

**Issue by AeonPrime** [advplyr/audiobookshelf#1719]
### Describe the feature/enhancement

I started adding my audiobooks to ABS and had a mismatch between folder content and the library. After some manual searching I found out that it didn't add a book that has a very long path due to the naming convention of [https://github.com/audiamus/AaxAudioConverter](url) from @audiamus. 
Would it be possible to at least get an error message or notification that content couldn't be added to the library? I understand that longer path support might be difficult to implement but this would give users a clue where to look for missing content.

![image](https://user-images.githubusercontent.com/57683359/234226447-81c3082c-b61d-4d4e-81e5-d3f58b52bcb0.png)

**Comment by audiamus** [comment]
Let me as the author of AaxAudioConverter comment on this: You can shorten the resulting directory and file names in AaxAudioConverter via the context menu and the Preview/Customize dialog.

**Comment by advplyr** [comment]
What did this show up as in the logs? We aren't filtering out folders with long characters so maybe this was your filesystem.
