### ISSUE TITLE
[Enhancement]: seekForward/Backward instead of next/previousTrack option

### ISSUE THREAD

**Issue by Alistair1231** [advplyr/audiobookshelf#1721]
### Describe the feature/enhancement

Hi!
Love the app. Thanks for your work.
I would love it, if there were an option to allow me to use my media keys, for skipping tracks forward/backwards, to instead of skipping an entire chapter, only skipping 10 seconds. In audiobooks I often simply miss what was said and want to hear it again. On android, the media keys simply skip back a bit, on desktop it skips entire chapters however. I rarely need to do that, and if I do I can just use the UI. Since other people may have different needs I feel an option is better, than just changing the current way it works.  
I was playing around with the code, and found that in `StreamContainer.vue` on Lines 369 - 371 can be changed to easily accomplish the change in behaviour. I would've made a pull request. But I am hopelessly lost in how to make a settings option with my change instead of hardcoding it. My change is simply.
From this:
```js
navigator.mediaSession.setActionHandler('previoustrack', this.mediaSessionPreviousTrack)
const hasNextChapter = this.$refs.audioPlayer && this.$refs.audioPlayer.hasNextChapter
navigator.mediaSession.setActionHandler('nexttrack', hasNextChapter ? this.mediaSessionNextTrack : null)
```
To this:
```js
navigator.mediaSession.setActionHandler('previoustrack', this.mediaSessionSeekBackward)
navigator.mediaSession.setActionHandler('nexttrack', this.mediaSessionSeekForward)
```

**Comment by advplyr** [comment]
Hey are you using a keyboard for the media keys?

**Comment by advplyr** [comment]
In the browser controls there is both seek and next track buttons.

![image](https://user-images.githubusercontent.com/67830747/234431603-57a727cd-8084-48b1-b7d5-529ceee4ff81.png)

Are you using something that doesn't have the seek buttons?

**Comment by advplyr** [comment]
Ah ok so it doesn't support the seek forward/backward media keys?

**Comment by Alistair1231** [comment]
No, neither my Keyboard, nor Autohotkey support those. I also checked the Powertoys Keyboard Manager and couldn't see such a key. The typically well supported keys are Play/Pause, Stop, Prev Track and Next Track.
Outside of UI elements I have never encountered seekforward / seekbackward.

**Comment by advplyr** [comment]
Are there other websites you use the media session keys for?

I just checked youtube.com and it looks like next/prev track isn't set for regular video. Maybe for a playlist. They are setting the seek forward/backward.

podcasts.google.com is showing both next/prev track and seeking. The next/prev track buttons actually seek like you are proposing here, so they have enabled both and they both do the same thing in my testing.

Curious if you have other examples

**Comment by Alistair1231** [comment]
My main comparison would be how pretty much all Audiobook/Podcast players on Android work. 
Android apps for audiobooks or podcasts, including the audiobookshelf app on Android, do seekbackward or seekforward when I use the media_prev or media_next keys on my Bluetooth headset.
On my PC, Audiobookshelf is the only app I use for this kind of content . So I don't have a lot of Apps to compare it to, except for how it works on my phone.

But in general, since Media_prev and Media_Next keys are far more common on keyboards as well as Bluetooth headsets, and users will on average more often want to skip forwards or backwards a bit instead of entire chapters, allowing for the remapping of this key would make sense in my opinion.

**Comment by Alistair1231** [comment]
I went ahead and gave the whole options thing a go, and I figured it out. I tried to keep all the conventions you use and made sure that the implmentation works. Also, be default I kept this option disabled.
If there are any issues let me know.

**Comment by advplyr** [comment]
I'm not sure if we need a setting for this. The reason I was asking if you had more examples is because I was thinking we just make both the media keys to seek forward/backward.

**Comment by Alistair1231** [comment]
Personally, I think that would suffice. Though, it never hurts to provide options. There are all kinds of people with different habits out there. I would be fine either way. 
Maybe the default could be to seek, with the option to enable skipping chapters?

**Comment by Alistair1231** [comment]
Is there any update on this? Should I create a pull request that changes this behavior to be the default instead of adding an option or will you do it and are just busy?

**Comment by advplyr** [comment]
Thanks yeah I think that is better for now. I was thinking of adding settings to the audio player instead of a server setting.

**Comment by Alistair1231** [comment]
> Thanks yeah I think that is better for now. I was thinking of adding settings to the audio player instead of a server setting.

Ah. Yeah, my solution would always apply to all users, which is suboptimal. Allowing the change on a user by user basis would be ideal, of course. Though, I am happy with simply changing the default behaviors and will close the issue now. If someone doesn't like it, they can create a new issue.

**Comment by advplyr** [comment]
Added in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)
