### ISSUE TITLE
[Enhancement]: Adjustable skip amount

### ISSUE THREAD

**Issue by Alistair1231** [advplyr/audiobookshelf#1722]
### Describe the feature/enhancement

Would it be possible to make the 10s skip amount in the web app (which is 30s in the Android app), adjustable?
Maybe chosing between 5, 10, 20, 30 and 60s or something like that?
I always need to skip several times because 10s doesn't suffice.

**Comment by nichwall** [comment]
I don't think skip time is configurable in the web browser yet, but it is configurable in the Android app if you're listening there (can't tell if you're aware of it from how you worded it)

https://github.com/advplyr/audiobookshelf/assets/5686638/403a90b7-a9bb-4c07-8253-e2be0f1df668
