### ISSUE TITLE
[Enhancement]: MP3 Series tag support multiple series

### ISSUE THREAD

**Issue by Sp4rky001** [advplyr/audiobookshelf#1728]
### Describe the feature/enhancement

I'm using the "series" and "series part" id.3 tags to store series information for my collection.  Once the tags are updated, I organize the books into the recommended structure:
author/
  series/
    vol 01 - year - title/
      title 01.mp3

For Michael Connelly's Harry Bosch series, the later books are also listed as part of the Renee Ballard series.  While I know that I can assign multiple series to a book after scanning, I think it would still be nice to be able to list multiple series in the tags and folder structure using commas, just as authors can be listed with commas.

So my id.3 tags look like this:
- Series: Harry Bosch, Renee Ballard
- Series Part: 21, 02

and my folder structure becomes:
Michael Connelly/
  Harry Bosch, Renee Ballard/
    vol 21, 02 - 2018 - Dark Sacred Night/
      Dark Sacred Night 01.mp3

I look forward to your feedback regarding this feature.  Thank you

**Comment by advplyr** [comment]
This would be difficult to implement in the folder structure so I don't see that happening.
It is possible to do this with the id3 tag but we would need to be careful with series that have commas in them already. I think we would have to use a different separator

**Comment by CLHatch** [comment]
> This would be difficult to implement in the folder structure so I don't see that happening. It is possible to do this with the id3 tag but we would need to be careful with series that have commas in them already. I think we would have to use a different separator

Possibly a semicolon?  I already use that myself instead of a comma for authors an narrators in my folders.

**Comment by Sp4rky001** [comment]
I think that if you do go with semi-colon, it should be across the board.  I believe a comma is recognized for the author tag so for consistency, separators should just be the same across the board.

**Comment by advplyr** [comment]
Commas don't work with series because a series name can have a comma

**Comment by Sp4rky001** [comment]
I think semi-colon is a good idea but I don't see this as something absolutely necessary.  Thanks for thinking about it.

**Comment by tfranken90** [comment]
I use Picard to automatically set my series data from Musicbrainz. However, if releases belong to multiple series they often end up split between the series. Support for multiple series from tags would resolve the issue.
