### ISSUE TITLE
ENHANCEMENT: add a "mark as read" button to each book in the library view 

### ISSUE THREAD

**Issue by zombiehoffa** [advplyr/audiobookshelf#173]
Jellyfin has a really nice feature where I can mark stuff watched right from the equivalent view to the library in audibookshelf. It woould be great to be able to mark thing as read directly from that screen without having to go into each book individually.

**Comment by advplyr** [comment]
Can you share some screenshots of how this would look? I don't have my jellyfin server up at the moment.

**Comment by zombiehoffa** [comment]
It doesn't really screen cap well, but you can see it in action here: https://demo.jellyfin.org/stable/web/index.html#!/login.html?serverid=713dc3fe952b438fa70ed35e4ef0525a

user is demo, password is blank. If you click on one of the categories (for example TV) and hover over a show poster you will see a white or red checkmark. If you click a white checkmark it marks everything as watched and turns red. If you click a red check mark it turns white and marks everything unwatched.

Managed to screen cap it abusing krdc and a window remote desktop:
![image](https://user-images.githubusercontent.com/627402/140842942-703c8e80-9157-470b-92c5-e6d3dfa27dbc.png)

**Comment by advplyr** [comment]
I've been thinking about adding the more icon (3 vertical dots) with a menu of quick actions. Since the book covers are smaller than jellyfins covers I think it would be cleaner to add the more icon with a dropdown item for "Mark as read".

In case you didn't see, there is also the ability to bulk mark books as read: https://github.com/advplyr/audiobookshelf/issues/35

**Comment by zombiehoffa** [comment]
That's pretty useful, I didn't know that was  in there, and it mitigates some of my pain. It would still be nice to have a mark as read option per book, your 3 dots solution would likely work well and leave a lot more space for more quick manipulation via the sub menu.

**Comment by advplyr** [comment]
I just released `v1.6.14` with the more menu. It is pretty ugly right now and not many items, but I wanted to get the basic functionality released to start testing.

![image](https://user-images.githubusercontent.com/67830747/141040762-4f2fc29c-17c8-48ef-ba04-3c1ac3fcbd32.png)

The "Re-Scan" button is only available for the root user. The download/match/tracks buttons are only available for users with update permissions.
Let me know what you think.

**Comment by zombiehoffa** [comment]
That's perfect, thansk so much!
