### ISSUE TITLE
[Bug]: The lable "Recommanded" is not translated into German on the start page

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1731]
### Describe the issue

The label "Recommanded" is not translated into German on the start page although it has been entered in the German strings,

### Steps to reproduce the issue

1. 

### Audiobookshelf version

v2.2.19

### How are you running audiobookshelf?

Docker

**Comment by Hallo951** [comment]
Oh, I've looked through everything but I must have missed that.... Thanks

**Comment by Hallo951** [comment]
Hmmm, I just checked the de.json file again. I was not mistaken after all. It is translated correctly in the file, it is just not displayed correctly...

![Screenshot_20230427_223031_com brave browser](https://user-images.githubusercontent.com/40667862/234984865-8fcd3828-d65e-42e9-b9bb-a60d9757b6c0.jpg)

**Comment by Hallo951** [comment]
![Screenshot_20230427_223031_com brave browser](https://user-images.githubusercontent.com/40667862/234985540-fb74e39b-cc90-4995-94d9-1252ed5fa692.jpg)

**Comment by Hallo951** [comment]
Hmmm, I just checked the de.json file again. I was not mistaken after all. It is translated correctly in the file, it is just not displayed correctly...

![Screenshot_20230427_223031_com brave browser](https://user-images.githubusercontent.com/40667862/234985773-3d42935a-6271-40d7-9646-a291436b0142.jpg)

**Comment by divyangbw** [comment]
Ah, that's my bad. I didn't realize my fork was outdated 🤦🏽‍♂️

**Comment by divyangbw** [comment]
@Hallo951 Once a PR is merged, it won't show up in Docker until a new release has been made. I checked locally and it seems ok, so I'd just wait until a new version is released. Unless you referring to some other location.

<img width="518" alt="Screenshot 2023-04-27 at 5 23 42 PM" src="https://user-images.githubusercontent.com/4261609/234994458-6e0c2110-32af-46f2-8330-848403296c6e.png">

**Comment by advplyr** [comment]
This translation hasn't been released yet. If you use the `edge` docker label you will see it.
