### ISSUE TITLE
[Enhancement]: Status finished / partly heard series

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1734]
### Describe the feature/enhancement

It would be very nice to have a visual feature in the series view for series that have been started, just as it is now for series that have been completed. I imagine it like this:

Finished series = green bar (already implemented in the web interface)
Started series = yellow bar (does not exist yet)
Series not started = no bar (already implemented on the web interface)

**Comment by advplyr** [comment]
This is how I implemented this.

**Example 1**
1 of the 10 books in this series is finished, the next book hasn't been started yet. (10% yellow progress bar)
![image](https://user-images.githubusercontent.com/67830747/235324979-643d84d7-feb7-44cf-a1bb-8e07949ca261.png)

**Example 2**
1 book finished, 1 book partially finished. (66% yellow progress bar)
![image](https://user-images.githubusercontent.com/67830747/235325005-8007a098-eedc-4e30-aa6d-2c369137a42e.png)

**Example 3**
4 books finished, 1 book unfinished. (100% yellow progress bar)
![image](https://user-images.githubusercontent.com/67830747/235325045-7fb38a2f-0cce-471c-94e7-10311a631712.png)

**Example 4**
All books finished
![image](https://user-images.githubusercontent.com/67830747/235325080-c5fbfd0f-55c7-47e3-ab6b-7325bcd947fb.png)

**Comment by Hallo951** [comment]
Wow, that's really not bad. I'm just not sure if what you've built isn't a bit too much of a good thing. For example, if you have your case 1, I could imagine that you wouldn't see it at all in the big overview because the bar is so short.

That's why I suggested making it a bit simpler and just colouring the bar yellow for series that have started.

Another idea would be to always show a complete bar and then work with different colours. For example:

0% no bar
1% - 50% orange bar
51% - 99% yellow bar
100% green bar

Of course, this can also be graded even more finely.

**Comment by vsuh** [comment]
It seems to me that for the deaf-eyed, a label like "4/6" would be more understandable

**Comment by Hallo951** [comment]
@advply What do you think about my proposal?

**Comment by advplyr** [comment]
I don't think changing the bar color would be more clear then changing the bar length. The bar length is how we currently show progress on individual items.
In addition to the bar length we could change the label "4/6". I'm not sure it would be clear what the "4" means though.

**Comment by vsuh** [comment]
"4/6" - fourth book of six in this series

**Comment by Hallo951** [comment]
Is it possible for you to implement a fixed bar length gradient in addition to your solution, so that the display type can be selected in the settings?

This would be great and should not be difficult to implement as you have already implemented your solution.

**Comment by advplyr** [comment]
Added in [v2.2.20](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.20)

I didn't have time to revise the current implementation before this release. I'm also not sold on any of the ideas mentioned so I think this will need some more user feedback.
Feel free to open another issue for more updates but try out the current update first. I don't think a color gradient on the progress bar would be added but I'm open to more user feedback.

**Comment by skyzuma** [comment]
i think the best way is the length of the cover ... if we have 6 books: 1st cover = % of cover length (25% = 1/4 of cover length /// 50% = middle of the cover /// 100% = end of the cover) ... 

and numbers in the line of the titlename maybe a green number for readed book, yellow for "not finished" books and normal (white) color vor "not yet readed" ... like:

 "titlename (2 (green color) | 2 (yellow color) | 2 (white color (normal color like the titlename)))
