### ISSUE TITLE
[Enhancement]: Log client IP address on successful login

### ISSUE THREAD

**Issue by Jdiesel87** [advplyr/audiobookshelf#1740]
### Describe the feature/enhancement

I would like to request that logging be changed to capture the client IP on successful/unsuccessful authentication to the server.

This info would allow for integration with Fail2ban for the purpose of hardening server security.

Not required but maybe a nice addition, include client IP in listening session view.

**Comment by advplyr** [comment]
We currently log the ip on failed login attempts. We also display the ip in the listening session if you click on it.
We can display the ip address on successful logins

**Comment by Jdiesel87** [comment]
Thanks! Still learning something new every day!

**Comment by advplyr** [comment]
Added in [v2.2.20](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.20)

**Comment by gitdeath** [comment]
Is there something I need to enable to see the login attempts (success or fail?) My logs do not appear to show them. 2.7.1

**Comment by Magusbear** [comment]
Same here. I was looking to setup fail2ban but I don't see any login attempts in the log files. Has this been removed?
