### ISSUE TITLE
[Enhancement]: Prefer (podcast) description over subtitle when subtitle is null

### ISSUE THREAD

**Issue by chrispinkney** [advplyr/audiobookshelf#1752]
### Describe the feature/enhancement

Hey there,

I currently have three podcasts being managed by the server. Two of them have "correct" metadata embedded in their rss feed per file. Each file has both a description and subtitle filled out appropriately.

![firefox_HrtKK3SGQ4](https://user-images.githubusercontent.com/7242003/236358231-1580ab77-fbfb-4876-a2d8-c7fb51cf687c.png)

However, I have one podcast which never has a subtitle filled out and thus each episode's subtitle is blank:

![firefox_GU3Y7PRGCx](https://user-images.githubusercontent.com/7242003/236358236-fc4a1c92-7d42-41e1-afa0-da45bc731ea7.png)

![firefox_iLhMkAbO6Q](https://user-images.githubusercontent.com/7242003/236358340-23ba8d58-a41f-4493-b9a4-26bc7a72689f.png)

Would it be possible to implement a per podcast feature (_or server-wide feature?_) which will show the description in the subtitle's field when no subtitle is provided? I don't think this feature currently exists nor do I think this would be challenging to implement and would love to try to attempt this on my own.

Thanks so much. I love the app, and use it daily, wonderful work.

**Comment by advplyr** [comment]
Added in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)
