### ISSUE TITLE
[Enhancement]: Re-Scan Multiple Selected

### ISSUE THREAD

**Issue by AarynRobinson** [advplyr/audiobookshelf#1754]
### Describe the feature/enhancement

It would be helpful to be able to re-scan multiple selected books, perhaps as an option next to the delete button or in the drop-down menu beneath Quick Embed Metadata

**Comment by advplyr** [comment]
Added in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)
