### ISSUE TITLE
[Bug]: Covers failing to download. Uploading, or pasting a URL also fails with error.

### ISSUE THREAD

**Issue by picklepopper1** [advplyr/audiobookshelf#1756]
### Describe the issue

I found this issue in another user's bug report, but it was closed due to the users lack of response. I'm running Ubuntu 22.04 LTS and running audiobook straight from the OS (without docker). I've tried restarting audiobook shelf, rebooting the machine, uninstall and reinstall ffmpeg, but nothing seems to fix the issue. 

This is freshly installed and was working for about 30 mins and without any changes to the machine, it seems to have stopped working on its own. I have verified that the URLs work when manually going to them, and I've already tried downloading them and manually uploading with an error being the end result.
![Screenshot 2023-05-05 204744](https://user-images.githubusercontent.com/79949408/236592056-a27b4b1f-496f-4f4d-950b-7ec1ad004311.png)

![Screenshot 2023-05-05 204813](https://user-images.githubusercontent.com/79949408/236592060-4caa36a7-508a-41f6-99c6-5abbca1a26fb.png)

### Steps to reproduce the issue

1. Edit the cover
2. Image fails to download from URL, or upload from local file

### Audiobookshelf version

v2.2.20

### How are you running audiobookshelf?

Debian/PPA

**Comment by picklepopper1** [comment]
I've reverted back to v2.2.19 and now I instead get "Socket disconnect" when I do the exact same actions as above.

**Comment by picklepopper1** [comment]
I've updated back to v2.2.20. It seems turning off the option "Store covers with item" has fixed the issue, but this is still not a desirable outcome due to it working for a brief amount of time.

**Comment by advplyr** [comment]
Can you check the logs? This is most likely a permission issue.

**Comment by picklepopper1** [comment]
I realized I changed file structures through my windows machine via samba. This seems to have screwed with all of the permissions of a ton of my folders, thanks for the suggestions!
