### ISSUE TITLE
[Enhancement]: Add a "Add to listen later" list option on the book page. Similar to Plex Watchlist

### ISSUE THREAD

**Issue by picklepopper1** [advplyr/audiobookshelf#1758]
### Describe the feature/enhancement

This would basically create a list that would act almost like a book mark for books you want to get to and revisit later in your library. Ideally this would have a similar button on the book page like the "mark read" button.

**Comment by advplyr** [comment]
I think playlists cover this. This is how I used playlists in Plex. Playlists are per user so each user can have their own.

Let me know if this doesn't cover your use-case

**Comment by Dr-Blank** [comment]
It does cover the use case, but if there were a handy watchlist button right next to mark as finished that added to a "Listen Later" playlist would be a UX improvement, not that its necessarily bad right now.

Right now, it takes about 3 clicks and 1 hover to add an item to playlist, which includes moving mouse over a lot of different areas on the screen and scrolling if you have a lot of playlists.

Also having the server track user's watchlist could help with showing recommendations on the home page.

Hence I feel a dedicated playlist would be a good addition.

**Comment by picklepopper1** [comment]
Also, It would automatically remove the book whenever it was completed ideally.
