### ISSUE TITLE
[Bug]: [UI] Refreshing autor page causes library switching

### ISSUE THREAD

**Issue by nschepsen** [advplyr/audiobookshelf#1767]
### Describe the issue

Hello,

Idk if it affects my installation only, or not... but there is a bug. First of all, if you have more than one library and refresh an author page

![Image A](https://i.imgur.com/vUNVnKX.png)

a selected library resets to the first one and you get a page with 0 books. (because there isn't any books for this author in the library)

![Image B](https://i.imgur.com/4yZ9SR8.png)

1: url | 2: selected library | 3. author's name

### Steps to reproduce the issue

1. select a library but not the first one
2. navigate to an author page
3. reload the page

### Audiobookshelf version

v2.2.20

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Fixed in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)
