### ISSUE TITLE
[Bug]: Clicking on Narrators button crashes server

### ISSUE THREAD

**Issue by iamjmulligan** [advplyr/audiobookshelf#1770]
### Describe the issue

Recently when I click on the Narrators tab in the web interface, it crashes the server and I need to restart the server. This is using a web browser to access the server.

The error log for the container in docker has these lines:
![error-log-ABS](https://github.com/advplyr/audiobookshelf/assets/7078397/496656ba-44a9-437c-b4c7-a125f10ae084)

### Steps to reproduce the issue

1. Click on the Narrators button on the left side tab.
2. Server crashes and needs to be restarted.

### Audiobookshelf version

2.2.20

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not sure how this happened for you but a narrator on one of your books is invalid. My guess is it is an empty string but I couldn't find how that would be possible.

**Comment by iamjmulligan** [comment]
I'll have to dig through the list manually to see if I can work out which book it is.

**Comment by advplyr** [comment]
Fixed in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)
