### ISSUE TITLE
[Enhancement]: keep android app alive longer when paused

### ISSUE THREAD

**Issue by toxic0berliner** [advplyr/audiobookshelf#1773]
### Describe the feature/enhancement

Using my car's Bluetooth (again) if I pause a book and want to unpause it later, quite often the play action sent by my car or my Bluetooth headphones is not starting audiobookshelf.
I'm not having this issue when listening to YouTube music for example.
Probably you are more concerned with preserving my battery but I'd very much like to give up some battery and keep audiobookshelf indefinitely as long as it's the last app that played media on my device.

**Comment by toxic0berliner** [comment]
Oups, I just realized somehow the android options to remove limit on background activity as well as "battery optimization" option got dropped. Just fixed it I hope the fix was as simple as that 😁 will report in a few days if it works as expected now 😂

**Comment by advplyr** [comment]
Sounds good. The mobile app issues should be reported here https://github.com/advplyr/audiobookshelf-app
