### ISSUE TITLE
[Enhancement]: Search all cover providers at once

### ISSUE THREAD

**Issue by Rdkang** [advplyr/audiobookshelf#1774]
#### Problem
Having to click on a different provider and wait several times if the user want to see which cover they like best

#### solutions
Add a "All" button in the provider drop down menu which will search for the title's cover using all the providers available
![image](https://github.com/advplyr/audiobookshelf/assets/68774237/83a3e988-6960-424a-8089-00320e98a5ac)

- An example of the solution is done by [Jellyfin](https://jellyfin.org/)
![image](https://github.com/advplyr/audiobookshelf/assets/68774237/89d04dad-eaf5-4cd8-aa89-030a1e3e44d3)

**Comment by CLHatch** [comment]
I would like to see something like this for the metadata also, not just the covers.  With some sort of indication which provider the metadata came from.  Possibly include local metadata like `.opf` files, etc, and pick and choose which info to take from?

**Comment by advplyr** [comment]
This could be very slow making a dozen requests to different providers. It would also be difficult to sort these based on the most accurate. I'm not sure how many requests Jellyfin is making

**Comment by Rdkang** [comment]
> This could be very slow making a dozen requests to different providers. It would also be difficult to sort these based on the most accurate. I'm not sure how many requests Jellyfin is making

I think it would be better having to wait 20 seconds once, to search all the providers and then selecting a cover.

Rather than having to go through each provider, waiting a few seconds and maybe backtracking to the one you find best.

So overall the "All" button will be easier even if the cover's aren't sorted :)

**Comment by advplyr** [comment]
We can try it out. In my small amount of testing the Audible regions were returning the same cover image URLs. The request will remove the duplicates.
This will be available on the edge docker version if you want to test it out. If we could limit the requests to Audible that would make this much faster. I'm not that familiar with how they return results for different regions.

<img width="794" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/67830747/bf27389e-f7cb-4e87-b6a4-51b791105305">

**Comment by CLHatch** [comment]
> We can try it out. In my small amount of testing the Audible regions were returning the same cover image URLs. The request will remove the duplicates. This will be available on the edge docker version if you want to test it out. If we could limit the requests to Audible that would make this much faster. I'm not that familiar with how they return results for different regions.
> 
> <img alt="image" width="794" src="https://user-images.githubusercontent.com/67830747/238204307-bf27389e-f7cb-4e87-b6a4-51b791105305.png">

Might be an idea to include (possibly under the resolution) which provider each cover came from.  You said it's removing duplicates, so maybe show only one, and populate all of them in a "tooltip"?

**Comment by advplyr** [comment]
It's the same URL that Audible is using for all the different regions. What does it matter which provider it is coming from? Maybe we could make it a tooltip since I would prefer keeping the design simple.

**Comment by CLHatch** [comment]
> It's the same URL that Audible is using for all the different regions. What does it matter which provider it is coming from? Maybe we could make it a tooltip since I would prefer keeping the design simple.

I was thinking in terms of knowing if it came from Audible, or Google, or that new cover provider, etc. And I wasn't sure if the various Audible sources used the same cover or not.

**Comment by advplyr** [comment]
Added in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)

**Comment by advplyr** [comment]
We can open other issues to make future improvements to this
