### ISSUE TITLE
[Enhancement] change 'Listen Again' to 'Read Again' in ebook library

### ISSUE THREAD

**Issue by Spray190** [advplyr/audiobookshelf#1782]
A very minor gripe but if you have separate ebook and audiobook libraries on ABS can the 'Listen Again' label be changed to 'Read Again' in ebook specific libraries, this could possibly be added as an option in the settings in order to be able to differentiate library types

**Comment by advplyr** [comment]
Agree, this will happen on the server side.

**Comment by advplyr** [comment]
Added in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)
