### ISSUE TITLE
[Bug] Bad chapter ID breaks mobile app downloads

### ISSUE THREAD

**Issue by Fribb** [advplyr/audiobookshelf#1783]
I own the Mountain Man Omnibus Audiobook which consists of the first three books in the series. Since I wanted to have them as separate books, I split them apart with MKVToolnix. All three of them are Playable through the WebUI.

When trying to download them through the steps below or play them on my Android phone, the app absolutely refuses to play or download them without any message.

After doing some testing I think I could narrow the problem down a bit.

Working Audiobooks had the chapter ID set to something like 0, 1, 2 and so on.

Audiobooks that don't work had the following IDs: 

![image](https://user-images.githubusercontent.com/10223913/231978301-0c7ad77f-5f65-403d-ab05-30691b0be60f.png)

I downloaded the Full Omnibus file and used m4b-tool to extract all chapters, moved them to individual folders so that the Books are separated and then merged all files in those folders together. This then resulted in the IDs being "corrected" and set to 0,1,2 etc. which then also allowed me to download and play the audiobook through the Android app.

I cannot say specifically if it is because of the ID or if there was some other issue with the File itself that got corrected using m4b-tool instead of splitting with MKVToolNix.

### Steps to reproduce

1. Select an Audiobook 
2. click download

### Expected behaviour
Audiobook is being downloaded

### Actual behaviour
The download button is greyed out but nothing happens.

### Environment data

Audiobookshelf Version:

App: 0.9.63-beta

Server: v2.2.18 docker

- [ x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: Pixel 4XL

Stock or customized system: Stock

**Comment by advplyr** [comment]
You are right the chapter id would break this. When we scan in the audiobook we shouldn't be using the chapter id in the metadata so this would be a server bug. There is no reason to use the id from the chapter metadata and instead we will use the index there.

**Comment by advplyr** [comment]
Fixed in v2.3.0
