### ISSUE TITLE
[Enhancement]: Support "and" as a separator between multiple authors

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#1790]
### Describe the feature/enhancement

If you see the image below, due to bad tagging (using 'and' instead of comma between the names), the author's name includes both the authors.
![image](https://github.com/advplyr/audiobookshelf/assets/42061703/c34b030a-162d-403d-9246-13df258ba49b)

I know this can and does get fixed when the book is matched, but for older books or books that slip in unnoticed, check for "and" between the names while doing "match all authors" (or "match new authors - previous enhancement request), and split the names as necessary to get correct names.

**Comment by advplyr** [comment]
Added in v2.3.0
