### ISSUE TITLE
[Enhancement]: Save progress of PDF ebooks

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#1791]
### Describe the feature/enhancement

We can save progress by saving the page number

**Comment by advplyr** [comment]
Added in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)

**Comment by wieluk** [comment]
Thanks. It does work on the web-ui but the android app still opens page 1 everytime and doesn't save progress.

**Comment by advplyr** [comment]
@wieluk That is coming in the next mobile app release
