### ISSUE TITLE
[Bug]: Delete bookmark not working

### ISSUE THREAD

**Issue by itkfilelor** [advplyr/audiobookshelf#1793]
### Describe the issue

Clicking delete on a bookmark does not work, This goes for the WebUI, mobile (Android) and the API. All three get an affirmative response (green alert modal on UI; 200 with API), but no change is affected. I noticed in [server/routers/ApiRouter.js](https://github.com/advplyr/audiobookshelf/blob/master/server/routers/ApiRouter.js) only the filter exists but no action.

### Steps to reproduce the issue

1. Click delete on a bookmark.

### Audiobookshelf version

v2.2.20

### How are you running audiobookshelf?

Docker

**Comment by Canderson8495** [comment]
So I just started a fresh dev environment. Added some books, opened a book, created a bookmark. Checked to make sure bookmark was working correctly. It was working correctly. I deleted it, but I had no problems on my side

**Comment by itkfilelor** [comment]
> So I just started a fresh dev environment. Added some books, opened a book, created a bookmark. Checked to make sure bookmark was working correctly. It was working correctly. I deleted it, but I had no problems on my side. Does this occur for all of your books or just some?

I only tried the one thus far. I'll look into it further.

**Comment by itkfilelor** [comment]
I lied, it's not working 😄. If a bookmark is created "normally" via the app or WebUI it all works as expected. But if the bookmark is created via the api it does not. As mentioned in the OP this goes for all three methods. 
Since @advplyr can't or won't expose intents for use with Tasker on android, (Not a gripe, just happy for this great software.) I took to python scripting. To not guild the lily, I can successfully create and update a bookmark, but I cannot delete.

**Comment by advplyr** [comment]
Can you share the API request you are making that is creating the bookmark?

**Comment by itkfilelor** [comment]
I'm just gonna stop. it appears to be my code. I works fine with Postman. 
If I come back just slap me.
