### ISSUE TITLE
[Bug]: cannot be played directly

### ISSUE THREAD

**Issue by wangruiStart** [advplyr/audiobookshelf#1797]
### Describe the issue

Open RSS, I can subscribe in packet casts and also download to play. But it cannot be played directly.

### Steps to reproduce the issue

1. open rss
2. subscribe in packet casts

### Audiobookshelf version

2.2.20

### How are you running audiobookshelf?

Other

**Comment by advplyr** [comment]
Can you provide more information? What is the format of the audio files? Are you using `https` when creating the RSS feed?

**Comment by wangruiStart** [comment]
> Can you provide more information? What is the format of the audio files? Are you using `https` when creating the RSS feed?

the format of the audio files is mp3.It is my local audio file.When I opened the RSS feed, I did not find the HTTPS option.

**Comment by advplyr** [comment]
You have to setup the HTTPS yourself. Once you are using the web over HTTPS and open an RSS feed it will open using that address.
This is most likely your problem and it is mentioned at the bottom of that screenshot.
Feel free to join the Discord/Matrix server and someone may be able to help you out.
