### ISSUE TITLE
Author Match not working [Bug]: 

### ISSUE THREAD

**Issue by sveyon** [advplyr/audiobookshelf#1799]
### Describe the issue

Running as a Docker container on Synology NAS.  Running 2.2.18 tried to update and it failed rolled back and now Author Match no longer working.  Created a New Docker container 2.2.20 and Saw the button for Match All authors and it is parsing through but has found NO authors.  Changed to used Google and Audible and still the same result.

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.2.18 & 2.2.20

### How are you running audiobookshelf?

Docker

**Comment by sveyon** [comment]
2023-05-27 11:45:11

ERROR

[Audnexus] Author ASIN request failed for Todd%20Tucker Error: getaddrinfo EAI_AGAIN api.audnex.us

2023-05-27 11:45:11

INFO

[Audnexus] Searching for author "https://api.audnex.us/authors?name=Tom%20Bradby&region=us"

2023-05-27 11:45:16

ERROR

[Audnexus] Author ASIN request failed for Tom%20Bradby Error: getaddrinfo EAI_AGAIN api.audnex.us

2023-05-27 11:45:16

INFO

[Audnexus] Searching for author "https://api.audnex.us/authors?name=Tom%20Clancy&region=us"

2023-05-27 11:45:21

ERROR

[Audnexus] Author ASIN request failed for Tom%20Clancy Error: getaddrinfo EAI_AGAIN api.audnex.us

2023-05-27 11:45:21

INFO

[Audnexus] Searching for author "https://api.audnex.us/authors?name=Tony%20Hillerman&region=us"

2023-05-27 11:45:26

ERROR

[Audnexus] Author ASIN request failed for Tony%20Hillerman Error: getaddrinfo EAI_AGAIN api.audnex.us

**Comment by advplyr** [comment]
Looks like an issue with your network. Every instance of the `EAI_AGAIN` error that has been reported was an issue with the end-users network. I tested the author lookup just to make sure and it is working.
Someone in the discord/matrix server may be able to help you troubleshoot

**Comment by sveyon** [comment]
Thanks for pointing me in the right direction.  I recently enabled the firewall on my Synology NAS.  I disabled it temporarily and ran the Author Match and it began updating
