### ISSUE TITLE
Loging screen showing ROOT username

### ISSUE THREAD

**Issue by scorpio862** [advplyr/audiobookshelf#18]
I forwarded the port to have an access to the server externally but I think there is few things that needs to be done to make the server more secure.

On the login screen the user ROOT shows up. I think username field should be empty.
![image](https://user-images.githubusercontent.com/50056988/132140446-3187eedf-0af4-43cf-ac5e-9417653573d8.png)

It would be good if there was an option to delete user ROOT if another admin user has been created as the root user is the most attacked user name. 

I think this should make the server a bit more secure.

**Comment by advplyr** [comment]
Agree with this, except the root user cannot be deleted, only the root username can be changed.

This is live in v1.0.5

**Comment by scorpio862** [comment]
Great stuff. Thanks
