### ISSUE TITLE
[Enhancement]: Keep audio controls visible over ebook reader

### ISSUE THREAD

**Issue by darth3pio** [advplyr/audiobookshelf#1800]
### Describe the feature/enhancement

Ignoring the Text-to-Speech versus Speech-to-Text debate, a simple change on the road to either or just as a standalone feature would be to have the audio playback controls visible above the e-book reader.

**Comment by advplyr** [comment]
Added in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)
