### ISSUE TITLE
[Bug]: Podcast episodes with the same name share one audio file

### ISSUE THREAD

**Issue by rasmuslos** [advplyr/audiobookshelf#1802]
### Describe the issue

The audio file of a podcast episode is save as `title.ext`. When two episodes share a name the audio file of the older episode gets overwritten

### Steps to reproduce the issue

1. Add a podcast where some episodes have the same name (I used Tagesschau, the most popular news show in Germany [rss](https://www.tagesschau.de/multimedia/sendung/tagesschau_20_uhr/podcast-ts2000-audio-100~podcast.xml))
2. download multiple episodes
3. All episodes share one audio file

### Audiobookshelf version

v.2.20.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.22](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.22)
