### ISSUE TITLE
[Bug]: Epub shows white text on white background on browser and android app

### ISSUE THREAD

**Issue by naatumach** [advplyr/audiobookshelf#1804]
### Describe the issue

I downloaded an epub3 from https://www.gutenberg.org/ebooks/2641 . When I try to open the book in the browser or my android phone, the screen is all white. The text can only be revealed when the text is highlighted. ![image](https://github.com/advplyr/audiobookshelf/assets/10781804/856e023c-fdfd-44e5-8713-bb28b6e81ace)

### Steps to reproduce the issue

1. Download epub3 ebook from https://www.gutenberg.org/ebooks/2641
2. Upload it to the library in audiobookshelf
3. Open the ebook in the browser or android app

### Audiobookshelf version

v2.2.21

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.22](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.22)
