### ISSUE TITLE
[Enhancement]: Library level setting of book cover dimensions

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#1805]
### Describe the feature/enhancement

The square dimensions that work for audiobooks don't really work for ebooks. I have created a separate library for ebooks (testing it out) and as you can see from the screenshot below, the ebooks have a rectangular cover because of which the extra filler gradient/blur needs to be added.

![image](https://github.com/advplyr/audiobookshelf/assets/42061703/d4b01d08-2760-4b5e-9c3e-ffb1112a76d5)

It would be nice if we can set the cover dimensions in the library settings.

**Comment by advplyr** [comment]
You can set the dimensions to use standard book aspect ratio.
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/33313248-e9a2-48f2-bfbc-6443c442ba05)
