### ISSUE TITLE
[Bug]: "Close Player" on Web-UI deletes progress

### ISSUE THREAD

**Issue by mxsrm** [advplyr/audiobookshelf#1807]
### Describe the issue

When using the "close player" (X) in the webui, it will delete my progress for that audiobook. If I start playing it again, it starts at the beginning and is no longer showed on the Home page under "Continue Listening".

### Steps to reproduce the issue

1. Start audiobook in web ui
2. Skip around as much as you like
3. Use the "X" sign to close the audio player in the webui
4. Progress gets deleted

### Audiobookshelf version

v.2.2.21

### How are you running audiobookshelf?

Docker

**Comment by mxsrm** [comment]
Also thank you for this great peace of software. I love it!

**Comment by advplyr** [comment]
Fixed in [v2.2.22](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.22)
