### ISSUE TITLE
[Enhancement] Multiple Narrators

### ISSUE THREAD

**Issue by keaganhilliard** [advplyr/audiobookshelf#182]
I have a number of books that have multiple narrators. Putting a comma doesn't create two separate narrators on a book, it creates a new narrator with both names separated by a comma. It would be awesome to be able to separate those out.

**Comment by advplyr** [comment]
Multiple narrators are supported in `1.6.21`

**Comment by sydlexius** [comment]
Does this still function?  When I attempt to paste a comma-separated list to the Narrators section, I get the following:

![Image](https://github.com/user-attachments/assets/f3821503-3325-490c-9d10-2b6194154bcc)

**Comment by advplyr** [comment]
When copy pasting into the edit modal you can use semicolons as a delimiter if you want them to automatically split. https://github.com/advplyr/audiobookshelf/issues/1198#issuecomment-1751449349

Commas are not a great delimiter, although Abs does support comma delimited names in the scanner. You can see it can get somewhat complex dealing with names that could be Last, First or First Last or first name only etc etc.  https://github.com/advplyr/audiobookshelf/blob/master/server/utils/parsers/parseNameString.js
