### ISSUE TITLE
[Enhancement]: Add button to download page while viewing comic

### ISSUE THREAD

**Issue by GianniBYoung** [advplyr/audiobookshelf#1822]
### Describe the feature/enhancement

Often when I read comics I  screenshot panels or pages that I like. Adding a button to download the currently viewed page would make this process easier, more consistent, and would not degrade image quality.

**Comment by advplyr** [comment]
Added in [v2.2.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.23)

**Comment by GianniBYoung** [comment]
> Added in [v2.2.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.23)

Thank you so much!
