### ISSUE TITLE
[Bug]: Unable to view comic issues of the same collection

### ISSUE THREAD

**Issue by GianniBYoung** [advplyr/audiobookshelf#1823]
### Describe the issue

If I have Issues 1-6 of a comic book in the same folder I am able to view the first issue but not the others.

I have the following directory structure:
comics/Dynamite/Red Sonja/Unchained
├── Red Sonja Unchained 01 (of 04) (2013).cbr
├── Red Sonja Unchained 02 (of 04) (2013) (Digital).cbr
└── Red Sonja Unchained 03 (of 04) (2013) (Digital) .cbr

ABR recognizes the collection of Unchained and provides me options to download each issue but when I click the read button I can only view the first issue.

### Steps to reproduce the issue

1. Create a Library for Comic books
2. Scan Library of Comics with the structure of series containing individual issues
3. Series are recognized as a a single entity containing the issues as 'Library Files'
4. Attempt to view any other than the first issue.

### Audiobookshelf version

v2.2.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Books have to follow the folder structure https://www.audiobookshelf.org/docs#book-directory-structure

What you are seeing is all of the comic books being picked up as the same book when they should be separate. This is mentioned in the FAQ https://www.audiobookshelf.org/docs#faq
