### ISSUE TITLE
[Enhancement]: EBook libraries should prefer 'epub' file types over other existing file types

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf#1825]
### Describe the feature/enhancement

Right now, the Epub file type seems to be the only type of 'ebook' that tracks user position and has a decent reader. ABS should 'prefer' epub file types as the read option when an epub is available, and then fall back to azw3/mobi/pdf if there is no epub available.

**Comment by advplyr** [comment]
Added in [v2.2.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.23)
