### ISSUE TITLE
[Bug]: Editing the rich-text description of a podcast episode does not allow quick navigation (arrow keys) of existing text

### ISSUE THREAD

**Issue by depwl9992** [advplyr/audiobookshelf#1826]
### Describe the issue

When editing a pocast episode description and navigating the text description to insert links and formatting, arrow key navigation does not work properly in the [ui-rich-text-edit](https://github.com/advplyr/audiobookshelf/blob/fde07d26e5a994c3b9fc8dcdc3d3429f7151510f/client/components/modals/podcast/tabs/EpisodeDetails.vue#L23), specifically when moving the cursor _without_ selecting text.

### Steps to reproduce the issue

1. View pocast episode list and click the pencil icon on an individual episode to bring up the details/match tabs.
2. All text and textarea fields, when active, allow arrow-key navigation.
3. Activate the 'Description' field and paste or type text if it doesn't already exist.
4. Shift-arrow-key selects text as expected, as do up/down arrows, however left/right arrow keys by themselves do not move the cursor, and instead will usually, briefly (for a half-second or so) pop up the 'Please Wait' progress indicator overlay animation.

### Audiobookshelf version

v2.2.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.23)
