### ISSUE TITLE
[Enhancement]: Convert epub to mobi when send to a Kindle device via mail

### ISSUE THREAD

**Issue by tubezleb** [advplyr/audiobookshelf#1830]
### Describe the feature/enhancement

It's known that Kindle does not handle .epub file very well.

When en epub file is sent to a Kindle via Calibre, Calibre convert the file in Mobi before sending it to the Kindle.

Can be nice to have a checkbox "Convert to mobi" when we add an email adresse in "E-Reader Devices"

**Comment by advplyr** [comment]
Mobi is an old ebook format and is getting phased out.


> Note: Beginning in early 2023, you'll no longer be able to send MOBI (.AZW, .MOBI) files to your Kindle library using Send to Kindle. This change won't affect any MOBI files already in your Kindle library. You can still read them with Kindle. MOBI is an older file format and won't support the newest Kindle features for documents.

https://www.amazon.com/gp/help/customer/display.html?nodeId=G5WYD9SAF7PGXRNA

I'm not sure but I think Kindle should be getting better at displaying epub.
Either way mobi is getting phased out and this would be a large effort to build so I don't think it makes sense to support this.

I'm considering removing `mobi` and `azw3` support from Abs altogether but I can see it still being useful for archiving even if the ereader won't continue getting developed.
