### ISSUE TITLE
Ebooks not appearing as separate items ?

### ISSUE THREAD

**Issue by nodecentral** [advplyr/audiobookshelf#1835]
### Describe the issue

Hi

As ebooks / comics have moved out of being an experimental feature, I’d thought I’d upgrade to the latest version and test them out, as I have number of them, which I’d love to have all together and maybe retire something else I have like Kavita etc.

Reading the guide. https://www.audiobookshelf.org/guides/ebooks/#introduction

It seems to suggest I should be able to see where I have ebooks and seperate them out, however for me it doesn’t, everything is still all together ? I guess I’m missing something obvious ??

![IMG_3433](https://github.com/advplyr/audiobookshelf/assets/4349292/c9506999-a8e3-4dc8-8adb-74a734fb7645)

### Steps to reproduce the issue

1. Go to library find a book you know has an ePUB in and see it what it shows you under files

### Audiobookshelf version

2.2.23

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
If you want them to show up as separate items in your library they would need to be in separate folders.

I think you are misunderstanding something but I'm not sure what exactly. You can join the discord server if you are still confused.

**Comment by nodecentral** [comment]
Thanks , i think the confusion is that the guide (linked in my original post) states the following…

‘ A library item can be both an ebook and an audiobook by keeping the ebook in the same folder as the audiobook.’ and it goes on to show an ‘ example of a library item that is both an audiobook and an ebook’ - extract of the screenshot from the above guide below, which is different to what is see in my screenshot (shared earlier)

![IMG_3439](https://github.com/advplyr/audiobookshelf/assets/4349292/20d713a4-11ad-46bd-9428-c022026d953b)

**Comment by advplyr** [comment]
That is a screenshot of the item page and not a screenshot of the Files tab in the edit modal.

That files tab is just showing all the files picked up in that book.
