### ISSUE TITLE
[Enhancement]: Option to set first image in cbz/cbr as cover

### ISSUE THREAD

**Issue by GreatToCreate** [advplyr/audiobookshelf#1837]
### Describe the feature/enhancement

Almost all comics are going to use the first image as the cover so this would reduce the current workflow of having to manually upload covers for each entry.

I currently see this as just an option on the edit cover page if the item filetype (cbz,cbr) matches, but maybe it makes sense to be able to mark an entire library as a comic type where this becomes the default behavior at the time the item is scanned by the server.

**Comment by 2IkHLHB** [comment]
+1

**Comment by advplyr** [comment]
Added in https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.2
