### ISSUE TITLE
[Bug]: 对WAM格式的音频支持很差，无法快速的加载。

### ISSUE THREAD

**Issue by XlangNan** [advplyr/audiobookshelf#1841]
### Describe the issue

[Bug]: 对WAM格式的音频支持很差，无法快速的加载。后来我将所有的WMA 格式音频都转换为MP3就可以正常流畅播放了。

### Steps to reproduce the issue

1.源文件为WMA 格式音频

### Audiobookshelf version

V2.2.23

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I had to translate your issue to English. From what I understand you had trouble playing WMA audio files.

WMA audio files are not going to direct play in chromium browsers so it is being transcoded. I don't know your specific issue but I wouldn't recommend using an audio format that you won't be able to direct play.
I have several WMA test files that I use for testing and these transcode and play correctly for me with just a slight delay when starting.
