### ISSUE TITLE
[Enhancement]: Mark book as Did Not Finish

### ISSUE THREAD

**Issue by celerohop** [advplyr/audiobookshelf#1843]
### Describe the feature/enhancement

It would be nice if we could mark books as DNF. There are some books (and series) that I know I will never finish, but I don't want to delete them. I don't like when they are stuck forever in In Progress or in Not Started, and if I mark them Finished, they would skew stats.

**Comment by advplyr** [comment]
You mark it as finished then mark it as unfinished.
Or you can just discard the progress. In the web client there is a X button, in the mobile app there is a "Discard Progress" button.

I think this handles your use-case but let me know if I didn't understand

**Comment by hobesman** [comment]
> You mark it as finished then mark it as unfinished. Or you can just discard the progress. In the web client there is a X button, in the mobile app there is a "Discard Progress" button.
> 
> I think this handles your use-case but let me know if I didn't understand

I believe that sets it to the same as "Not started" which was one of the scenarios they _didn't_ want.

**Comment by advplyr** [comment]
I don't understand the use-case for that then. If you don't want it to show in the continue listening shelf it can be removed.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/5410ee00-e9ff-4350-9345-173717e78830)

There is no "Not started" shelf

**Comment by celerohop** [comment]
Remove Series from Continue Series kinda works, thanks.

My use case is that when I decide what to listen to next, I go to Library and filter by Progress: not-started. Here I would like to get rid of books I don't intend to listen.

I could start them and then Remove from Continue Listening like you suggest, but it is a bit messy.
