### ISSUE TITLE
[Bug]: Non-Admins should not get to account creation

### ISSUE THREAD

**Issue by lkiesow** [advplyr/audiobookshelf#1848]
### Describe the issue

As a non-admin user, I should not be able to get to the list of users and to the account creation dialog, but you can via “Your Stats” → “View all”:

https://github.com/advplyr/audiobookshelf/assets/1008395/993e182a-7ea2-4488-ad4c-37bf6a2d121a

### Audiobookshelf version

2.2.23

### How are you running audiobookshelf?

Other

**Comment by advplyr** [comment]
Fixed in v2.3.0
