### ISSUE TITLE
[Enhancement]: Recognize `[ASIN]` in folder names

### ISSUE THREAD

**Issue by CLHatch** [advplyr/audiobookshelf#1852]
### Describe the feature/enhancement

It would be very helpful to be able to recognize the ASIN of a book in the folder names, especially seeing as apparently the `CDEK` tag for the ASIN isn't readable by ffprobe in M4B files.  This would make matching books by folder name much more foolproof. 
Many will put the ASIN in brackets, such as:

 `01 - (2008) - 2001꞉ A Space Odyssey [B002UZJGYY] {Dick Hill}`

It could also be a possibility to try to match to either ASIN or ISBN.

**Comment by AeliusSaionji** [comment]
It's worth noting that Libation has [ASIN] by default, and now I have a rather large collection of unmatched data, unique identifier in the name notwithstanding :)

**Comment by advplyr** [comment]
Added in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)

Still need to update docs
