### ISSUE TITLE
[Enhancement]: Enlarged view of covers

### ISSUE THREAD

**Issue by jullit31** [advplyr/audiobookshelf#1853]
### Describe the feature/enhancement

Currently, when clicking on some point of a cover, other than the "Play" or "Edit" buttons, nothing happens. It would be nice to get an enlarged view of the cover instead. I'm thinking a pop-up, like you get with the "Edit" button, but just showing the cover.
Mockup:
![image](https://github.com/advplyr/audiobookshelf/assets/19243986/26de9d6f-e5d4-49aa-be58-73553feb7793)

**Comment by advplyr** [comment]
Added in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)
