### ISSUE TITLE
wrong direction in epub page turn from mobile browser

### ISSUE THREAD

**Issue by darkzero-sdz** [advplyr/audiobookshelf#1854]
### Steps to reproduce

1. open Audiobookshelf on an Android phone from the browser
2. open any epub file
3. Swipe from right to left

### Expected behaviour
- next page should open like in the Android app

### Actual behaviour
- previous page opens

### Environment data

Audiobookshelf Version:

latest nightly and edge

#### Android Issue
Android version: 13

Device model: Samsung Galaxy S23 Ultra

Stock or customized system: stock

**Comment by advplyr** [comment]
Fixed in v2.3.0
