### ISSUE TITLE
[Bug]: Issue with Automatic Download of Updated Episodes

### ISSUE THREAD

**Issue by datougua** [advplyr/audiobookshelf#1855]
### Describe the issue

Dear Audiobookshelf team,

I have been using Audiobookshelf and I greatly appreciate the utility it provides. However, I have encountered an issue while using the application that I’d like to bring to your attention.

The problem arises when new episodes are updated on the RSS feed. Even though the updates are live, Audiobookshelf does not automatically download these new episodes. Strangely, when I manually check for updates, the application can locate and download the updated files without a hitch.

This has been a consistent issue and I was wondering if there is any solution to this. The automatic download feature is one of the main reasons I use Audiobookshelf and I would really appreciate if you could assist me in resolving this issue.

Thank you for your time and I look forward to hearing from you.

Best regards

### Steps to reproduce the issue

1.	Add an RSS feed to Audiobookshelf.
	2.	Wait for a new episode to be updated on the feed.
	3.	Check Audiobookshelf for the new episode - it does not appear automatically.
	4.	Manually trigger an update check on Audiobookshelf.
	5.	The new episode is now detected and downloaded.

### Audiobookshelf version

v2.2.23

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you share the logs showing the error message when it fails to download?
