### ISSUE TITLE
[Enhancement]: Configurable Podcast Feed Fetch Timeout

### ISSUE THREAD

**Issue by tomershvueli** [advplyr/audiobookshelf#1856]
### Describe the feature/enhancement

Hello! 

I'm a new user of AudioBookShelf and am looking forward to taking full advantage of this application! 

I have a few podcast feeds that are private and dynamically generated. It seems that these requests take longer than 6000ms to complete (I'm able to see the output in a browser, but it does take longer than 6 seconds). Could we make [the timeout here](https://github.com/advplyr/audiobookshelf/blob/36b1f43f4c576498485a747d11fd41a4eccbe8e9/server/utils/podcastUtils.js#L207) a configurable value? 

Alternatively, if you can point me in the right direction I can try to tackle it myself if this is something you'd welcome in the application. 

I guess another option would be to up the timeout for this globally? But I understand wanting to leave it at a reasonable 6 seconds. 

Thanks!

**Comment by advplyr** [comment]
Hey, I updated the timeout to 12s. I think making this configurable would be overkill but let me know if that works for you.

Auto downloading episodes is synchronous so the timeout should be reasonable if you have a hundred podcasts or something.

**Comment by tomershvueli** [comment]
@advplyr thanks for the prompt turnaround! I'll try this out in the next release and report back.

**Comment by tomershvueli** [comment]
Confirmed that the 12s timeout is now working for me, thanks again!
