### ISSUE TITLE
[Enhancement]: Ability to mark an entire podcast as played without having to select each episode individually. 

### ISSUE THREAD

**Issue by Pouncingkitten** [advplyr/audiobookshelf#1862]
### Describe the feature/enhancement

I would like a better method of marking all episodes of an item as played. Having to individually select hundreds of episodes and mark them as played is tedious. It would be nice to have:

a) An option in the right click menu of a podcast to mark it as played.
b) Ability to batch select all episodes under the podcast itself without having to mark each episode individually.

**Comment by advplyr** [comment]
Added in v2.3.0 as a context menu option above the episodes list.
