### ISSUE TITLE
[Enhancement]: Improve book editing performance when saving changes

### ISSUE THREAD

**Issue by Timtam** [advplyr/audiobookshelf#1867]
### Describe the feature/enhancement

I'm aware that changing from NJODB to SQLite is already in the works, I however just wanted to let you know that even with an SSD cache caching the database, changing book details in a large library (about 5000 books right now), takes half a minute to save. I just scanned my entire library and now want to edit almost any book to have proper categories and everything, it'd literally take days just for saving the changes. I guess that is because its always saving away the gigabytes of NJODB whenever I press save... guess we'd either need to change to SQLite which is fast enough to only change the stuff that we need or find a way to only save on in a kinda scheduled way instead of saving whenever you press save. Something like caching it in-memory so that you don't have to wait whenever you want to edit something within the library.

**Comment by advplyr** [comment]
I don't think 5k books is large enough that this would be taking that long.
Perhaps the file system where the `/config` folder is mapped to has a very slow read/write. Maybe it is network attached storage?

**Comment by Timtam** [comment]
Nope, i'm on a Synology NAS with the config folder being a local folder that is even backed up by an SSD cache. config folder is about 1 GB in size.

**Comment by advplyr** [comment]
What is taking up so much space in the config folder?

**Comment by Timtam** [comment]
The library items folder is 1.02 GB in size and takes up almost everything. And yeah, thats about 560K mp3 files, and i'm not planning to switch all that to M4B because most of the players i'm using apart from ABS don't handle that format too well unfortunately.

**Comment by advplyr** [comment]
DB has been switched to sqlite
