### ISSUE TITLE
[Enhancement] Author metadata

### ISSUE THREAD

**Issue by keaganhilliard** [advplyr/audiobookshelf#187]
I'm currently in the process of porting my library over from Emby/Plex to Audiobookshelf, just to check it out. In Emby I was able to get author metadata using my own plugin and Audnexus. I'm wondering if it would be possible to be able to add some metadata for the author beyond just the name. The same could be applied to narrator but that info is generally harder to get anyway. 

I also think it would be cool to be able to have an "Authors" tab where you can look at all of your authors, hopefully have images and a description. For reference what it looks like in Emby at the moment:
![image](https://user-images.githubusercontent.com/27737278/142069794-938e0bdf-14c7-4ac0-a6fe-778db8460faa.png)
![image](https://user-images.githubusercontent.com/27737278/142069887-d121a550-c5dc-439a-9f4a-5bfa33b365c1.png)

I'm loving everything in the app so far, being able to group by series is awesome and a lot better than collections in the other streaming apps.

**Comment by advplyr** [comment]
I just haven't seen a good way to acquire author metadata, even google books API only provides a name. Can you provide a list of metadata you think should be stored for authors?

I like the idea of an authors tab, but I think we need to come up with a slick design first that accounts for the majority of authors not having a photo. @p1xelll may have some idea for this.

**Comment by keaganhilliard** [comment]
Honestly, all I have right now is name, description and profile photo. https://audnex.us/ scrapes audible to grab author metadata/images but at least wraps it in an API that's easy to use. It's about the best source that I've been able to find. Goodreads has some but they don't let you generate API tokens and their TOU is a nightmare, but Readarr is using it so there might be an avenue there.

**Comment by advplyr** [comment]
If someone is hosting a public audnexus api then audiobookshelf could use it for metadata.

The author page and support for metadata can be added before a reliable source is found though. If the page can look good with just placeholder author photos then I'm up for moving forward on that.

**Comment by keaganhilliard** [comment]
Awesome! Yeah the link I sent earlier gives you the api documentation and https://api.audnex.us is the endpoint.

You would end up making callouts to these endpoints:
https://api.audnex.us/authors?name=adrian%20tchaikovsky
https://api.audnex.us/authors/B002XLHS8Q

**Comment by advplyr** [comment]
This is great, I thought the whole time it was meant to be self-hosted.

**Comment by p1xelll** [comment]
First look
![author bio](https://user-images.githubusercontent.com/81173399/142232341-25582045-250c-42a2-9607-e424cf620b6a.png)
![author bio - no photo](https://user-images.githubusercontent.com/81173399/142232355-30d4be38-1b63-44dd-9aa7-a0382fe85d8e.png)
![authors](https://user-images.githubusercontent.com/81173399/142236483-13234867-5bed-485e-bb1f-c9986722ae57.png)
but I'll probably change the /author page

[Figma](https://www.figma.com/file/YVE3OjdbG39jjffozEC2Ah/web?node-id=234%3A5753)
[Prototype](https://www.figma.com/proto/YVE3OjdbG39jjffozEC2Ah/web?page-id=0%3A1&node-id=234%3A5366&viewport=241%2C48%2C1.41&scaling=contain&starting-point-node-id=234%3A5366&show-proto-sidebar=1)

**Comment by advplyr** [comment]
Nice! I like that more than Jellyfin because it is not leaving a bunch of white space. The problem remains though of finding a placeholder image for authors without photos, since this will likely be the default for a while until a source is integrated.

**Comment by p1xelll** [comment]
I used the icon for those who don't have a photo. It doesn't look that bad. I'll try to think of something else.

**Comment by p1xelll** [comment]
![author](https://user-images.githubusercontent.com/81173399/142266199-c789b266-6d20-4a38-9c5d-3c47d30399f1.png)   ![Frame 41](https://user-images.githubusercontent.com/81173399/142266265-53af130d-ba1d-46c0-bc91-0de39e0759ec.png)
This probably looks better.

**Comment by advplyr** [comment]
`v1.6.33` with experimental features turned on has the very start of the authors page. No ability to add images/metadata yet, and no authors page. Clicking on one takes you to a filtered bookshelf.

![image](https://user-images.githubusercontent.com/67830747/144530359-82491327-cbef-475e-b813-185361fa7944.png)

**Comment by JKamsker** [comment]
@advplyr Have you thought about how we are going to be able to add covers and metadata?
- cover.png + metadata.odf in the author directory?
- In the UI?
- Automatically from Audnexus/Audible?

**Comment by prolife86** [comment]
> @advplyr Have you thought about how we are going to be able to add covers and metadata?
> 
> * cover.png + metadata.odf in the author directory?
> * In the UI?
> * Automatically from Audnexus/Audible?

Has there been any progress in this process?
I've located the JSON files and the folder which has the metadata, can I add the pictures there and link to them in the JSON?

**Comment by advplyr** [comment]
There is no way to use your own author images yet without manually editing metadata files. There will need to be an uploader made on the edit author modal.

You can update those JSON files in the database /config/authors but be careful doing.

**Comment by advplyr** [comment]
Authors page is officially in [v2.0.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.1) but still basic. We still need to add in uploading your own author photos.

**Comment by jt196** [comment]
@advplyr - I know this is closed but been doing some tagging today and reading the docs a bit, one option could be to apply the same rules to the Author folder as the books folders, desc.txt and any photos get added to the author metadata/section, if the user wishes to manually add the data.

**Comment by advplyr** [comment]
I don't think each author gets their own folder right now. You can open an issue for this though and we'll figure something out.
