### ISSUE TITLE
[Enhancement]: Remove episode from "Newest Episodes" when marked as finished

### ISSUE THREAD

**Issue by darthrater78** [advplyr/audiobookshelf#1871]
### Describe the issue

Podcast Episodes Stay in "Newest Episodes" even after being marked as finished. Ideally, when a podcast is marked as finished it should no longer be referenced there. 

### Steps to reproduce the issue

1. Finished podcast, view the "home" page

### Audiobookshelf version

v2.2.23

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Added in v2.3.0
