### ISSUE TITLE
[Enhancement]: Calculate runtime with playback speed increase taken into account

### ISSUE THREAD

**Issue by michaeldvinci** [advplyr/audiobookshelf#1876]
### Describe the feature/enhancement

Hey there, first off THANK YOU as this app is amazing and I get a ton of use out it! 

I usually listen to my audiobooks at 1.6-1.7x speed. I usually have to go to https://asc.pixelofink.com to find out what the actual runtime is, as it obviously will be shorter than the given runtime. 

I was wondering if you could have a setting for "default" increased playback speed and calculate all runtimes based on that>?

Thanks and always here to chat more if you'd like more info / explanation.

**Comment by advplyr** [comment]
Hey I think this is already how it works unless I'm misunderstanding. For example in the screenshot below I changed the playback speed to 1.5x and all of the times adjusted relative to that.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/9da3dfa1-2e7b-4955-8542-6f2bfbbaa073)

**Comment by michaeldvinci** [comment]
ahhh I must have missed it in the actual player. I was thinking along the lines of Library View, but this is one more click and totally reasonable! Thanks!

**Comment by michaeldvinci** [comment]
see above

**Comment by CLHatch** [comment]
> Hey I think this is already how it works unless I'm misunderstanding. For example in the screenshot below I changed the playback speed to 1.5x and all of the times adjusted relative to that.
> 
> ![image](https://user-images.githubusercontent.com/67830747/249574406-9da3dfa1-2e7b-4955-8542-6f2bfbbaa073.png)

Actually, how about showing both the "converted" time remaining, as well as the 1x speed time remaining?  Show both scales.
