### ISSUE TITLE
[Enhancement]: 'Select all' Podcast episodes download limit to search/filter

### ISSUE THREAD

**Issue by undaunt** [advplyr/audiobookshelf#1878]
### Describe the feature/enhancement

Currently, if I search for a specific set of episodes (perhaps by a seasonal subtitle) in a feed, and I only wish to download those episodes in bulk, I'd like to hit "select all" and have that select only what is showing as my search results. Currently, regardless of if I'm looking at an entire podcast's feed or a subset of the feed via episode search, "select all" selects every episode in the feed for downloading.

**Comment by advplyr** [comment]
Added in v2.3.0
