### ISSUE TITLE
[Bug]: Not syncing played location

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf#1879]
### Describe the issue

Listening on browser on desktop, pause the play, go away from office, open the app and then hit play, starts at what i presume is where i was up to when i last paused on mobile.

This has happened a few times lately, so today i even made sure that i exited the app entirely before leaving the office, still started playing from the wrong place and replaying what i had just listened to on the desktop

![image](https://github.com/advplyr/audiobookshelf/assets/101836977/bd247774-9cf2-41eb-a230-63f4bff84de2)

### Steps to reproduce the issue

1.  Play on desktop for a while
2. Pause
3. Open Android app
4. Play

### Audiobookshelf version

2.2.23

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Are you using the latest mobile app?

**Comment by barelylit** [comment]
Yup. Play store just shows open, not update when viewing app

**Comment by advplyr** [comment]
Can you double check the version is 0.9.65-beta?
Mobile syncing was improved in this release

**Comment by barelylit** [comment]
It is now, couldn't say if it was at the time depending on release date /
time.

**Comment by advplyr** [comment]
Let me know if you can provide reproducible steps for this on the latest versions

**Comment by dedors** [comment]
Switching between 2 android players, it did sync but resumed playback on old position.
![Screenshot_20230705-195742~2](https://github.com/advplyr/audiobookshelf/assets/17786985/8a4989c6-33c5-4b84-b495-33b4d582161f)

**Comment by barelylit** [comment]
Latest versions, still happening.

Was listening on the phone. 
Went into office
Listened for ages
Went out of office
Phone started playing as soon as bluetooth in car connected
Was playing from where phone was up to

It seems like its starting playing before establishing a connection to the server, cached data perhaps, and then over writing the stored location with that 

![image](https://github.com/advplyr/audiobookshelf/assets/101836977/6b525881-3e01-4ab6-aef0-54c7cab3741b)

![image](https://github.com/advplyr/audiobookshelf/assets/101836977/58075f6c-46e0-4c90-b2c9-ffb7cbc09c5a)

**Comment by dedors** [comment]
I also had this problem occuring a few times again on my android phone.
It always happened when book was playing in the background for some time, and after a pause, when reopening the app, it dropped back
