### ISSUE TITLE
BUG: Docker dropping NFS mounted folders, recovers upon restart

### ISSUE THREAD

**Issue by Allastratou** [advplyr/audiobookshelf#188]
Server is running Ubuntu Bullseye, with latest docker image.

Have an NFS share " /share/media/audiobooks " mapped on ubuntu to " /mnt/media/audiobooks ". Within container, host folder " /mnt/media/audiobooks " is mounted to " /audiobooks "

After a few hours (unsure the exact amount of time, but definitely less than a day) all covers show as "invalid file type", non-cached books will not play, and when I connect to the container's console, running " ls /audiobooks " returns "stale file handle". Upon restarting the container, access is restored and everything functions as expected.

I've confirmed other containers that access this NFS share do not have this issue, and the parent OS does still have the NFS folder mounted and accessible. Running " ls /mnt/media/audiobooks " works as expected.

**Comment by advplyr** [comment]
Have you tried setting up a docker volume for the NFS instead of mounting it in ubuntu?
https://docs.docker.com/storage/volumes/

Audiobookshelf doesn't do anything differently then other docker images, so I'm not sure why it would be different.

**Comment by zombiehoffa** [comment]
This seems like a pretty common problem using nfs in docker and also kubernetes: https://duckduckgo.com/?q=stale+file+handle+nfs+docker

Here's one possible solution if you absolutely must use nfs: https://engineerworkshop.com/blog/automatically-resolve-nfs-stale-file-handle-errors-in-ubuntu-linux/

**Comment by Allastratou** [comment]
Thanks for the responses! I just thought it was odd that this was the only container with this behavior, even though I have two more containers with the exact same setup. I went ahead and created an NFS docker volume, I'll let ya know how it goes.

**Comment by Allastratou** [comment]
> Have you tried setting up a docker volume for the NFS instead of mounting it in ubuntu? https://docs.docker.com/storage/volumes/

Yup! Works perfectly so far. Thanks again people!
