### ISSUE TITLE
[Bug]: Unable to trigger library actions from mobile view of an admin user

### ISSUE THREAD

**Issue by Jerk-Solutions** [advplyr/audiobookshelf#1886]
### Describe the issue

Unable to trigger library actions from mobile view of an admin user

### Steps to reproduce the issue

1. Login as an admin on a mobile view
2. Go to server settings
3. Go to library settings
4. Open the setting popup for an existing library
5. Click on edit/scan/force rescan

Expected : confirmation popup should be displayed
Actual : popup does not appear 

### Audiobookshelf version

V2.2.23

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in v2.3.0
