### ISSUE TITLE
[Enhancement]: New filter for ebooks

### ISSUE THREAD

**Issue by Demian98** [advplyr/audiobookshelf#1889]
### Describe the feature/enhancement

The follow filters are available to find audiobooks with ebooks or supplementary ebooks:
![grafik](https://github.com/advplyr/audiobookshelf/assets/77210091/619823eb-2cac-42a1-a3be-057fcc057138)

It would be great to have the opposites too:

- has no ebook
- has no supplementary ebooks

**Comment by advplyr** [comment]
Added in [v2.8.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.1)
