### ISSUE TITLE
[Enhancement]: Podcast item page should have a place that show episodes count

### ISSUE THREAD

**Issue by joshuatly** [advplyr/audiobookshelf#1891]
### Describe the feature/enhancement

Currently the total episode count for podcast is only shown as a badge on the library page, top right of the item's image. 

Inside the item page, there are no way of checking the amount of episodes (total/filtered). 

I propose on the item page, there should be a place for amount of episodes in an item (of podcast), either total amount or in filtered view under Episodes list, it should show the amount of items in the filtered view (example incomplete).

**Comment by advplyr** [comment]
Added in v2.3.0
