### ISSUE TITLE
[Enhancement]: Change the standart bitrate for m4b encoding to 128k

### ISSUE THREAD

**Issue by MoriarT3a** [advplyr/audiobookshelf#1892]
### Describe the feature/enhancement

I've converted a lot of Audiobooks to m4b with the standart settings. After that I recognize, that the soundquality is very very bad. After looking into the advanced settings, I saw that the standart bitrate is 64k. Fortuneatly all original data was in the cache folder. It was very timeconsuming to roll everything back. ^^

Is it possible to change the standart bitrate to 128k? I think that would be enough for a spoken Audiobook. 64k realy makes my ears bleeding. 

![grafik](https://github.com/advplyr/audiobookshelf/assets/30555787/a8bc0f4e-3ddf-4cc3-96de-2a8beb75c298)

**Comment by advplyr** [comment]
Updated in v2.3.0
