### ISSUE TITLE
[Bug]: Access All Libraries toggled off causes viewing errors with some Series 

### ISSUE THREAD

**Issue by kevlp3000** [advplyr/audiobookshelf#1899]
### Describe the issue

When a user profile has the option Can Access All Libraries toggled off and a Series is touched/clicked to view a message
`This page could not be found Back to the home page` on Mobile (using Android, don't have iOS to test) and `Oops... Series not found` on Browser is displayed instead of showing the books in that series.

In the log, this message is displayed
`WARN [SeriesController] User attempted to access series "ser_ql0azwv2f3qc2z8o1q" without access to the library [object Object]`

This happens on Account Type User and Admin when Can Access All Libraries is toggled off.

If you enable Can Access All Libraries for that user, the series/books display properly.

### Steps to reproduce the issue

1. Go into Settings > Users > Select a User to edit
2. Change Can Access All Libraries to Off and Save
3. From ABS mobile or browser go to Series and select a series to view and that is when the message This page could not be found will display (note: it is random or appears to be as some series will display as expected an others will not)

### Audiobookshelf version

2.2.23

### How are you running audiobookshelf?

Docker

**Comment by yamimizu832** [comment]
I also experienced the same issue and the only work around was to enable all libraries for all users. This issue was not present until I updated to v.2.23. I am also running this program on Debian 11 in Docker.

**Comment by advplyr** [comment]
This is a design flaw with the data model. This will be specific to if you the series of the same name exists in a library the user doesn't have access to.

**Comment by advplyr** [comment]
Fixed in v2.3.0
