### ISSUE TITLE
False duplicate detected. Adjustment needed.

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#19]
Found a wrinkle that could use some smoothing...

![image](https://user-images.githubusercontent.com/25695143/132169902-368cc05f-007e-440f-8325-0bfcdeb8a348.png)

You'll notice that I numbered this particular series "Brandon Sanderson - [Mistborn -4.0]" and then "Brandon Sanderson - [Mistborn -4.5]", but there is an incorrect duplicate detected. I suspect it is ignoring the decimal. Is there a way this precision could be added. I know I can "cheat" and rename 4.5 to 5 and increment that way. But, then the correct book order wouldn't be represented in the filename (and that would be nice to preserve, if possible).

A thought: maybe it would work out to have an override for the duplicate detection and "force" it to be included. Maybe on this screen?

![image](https://user-images.githubusercontent.com/25695143/132170650-affcfbb4-0574-4302-8f85-b5a943cb5ea5.png)

Just thinking out loud here.

What do you think?

**Comment by advplyr** [comment]
The scanner first tries to get a number from the track metadata, then falls back to pulling the first number in the filename (excluding the title/author/publish year).
These edge cases are why I made the tracklist manager page. When you press "Save Tracklist" it will store the correct order and remove the error notes. I have a few audiobooks that need some manual adjustments when they come in.
This pointed out a potential issue with the scanner though, decimal tracklist numbers pulled from metadata will be stored with a decimal index, so I'll have to resolve that.
