### ISSUE TITLE
[Enhancement]: Remove toast notification for marking items as finished/unfinished

### ISSUE THREAD

**Issue by deanishe** [advplyr/audiobookshelf#1900]
### Describe the feature/enhancement

Would it be possible to adjust notifications so they don't interfere with using the application so much?

The default positioning is right where many of the controls are (I'm trying to mark a range of episodes as played, but the notifications keep obscuring the buttons I need to press):

![Notifications](https://github.com/advplyr/audiobookshelf/assets/747913/4f6540a1-56bd-4040-bcf4-f23c4287a8ea)

The "playback not syncing" and "scanning" notifications are particularly bad because they don't go away after a few seconds.

![No Playback](https://github.com/advplyr/audiobookshelf/assets/747913/55e71a6f-7f65-42f5-b381-d6b2ccf2d544)

![Scanning](https://github.com/advplyr/audiobookshelf/assets/747913/d293fa6d-1ef8-41ac-931e-8796a1a50a7c)

In the case of those two, would it not make sense to move the "scanning" notification to the "tasks" dropdown and the "progress not syncing" warning to the player UI?

The "Item marked as Finished" notifications in my first screenshot seem a little superfluous, too: in this case, they're only telling me the same as the button I just clicked on.

**Comment by advplyr** [comment]
I agree the "Item marked as finished" toast is unnecessary. This was already removed from the mobile apps and I'll remove them for the next server release.

There are plans to move the scanning toast to the tasks dropdown. The tasks dropdown was added relatively recently. There is an issue in for this #1279.

The "progress is not being synced" error should probably be addressed rather then dismissed. Do you have multiple tabs open streaming? Are you on the latest mobile and server?

**Comment by deanishe** [comment]
> Do you have multiple tabs open streaming? Are you on the latest mobile and server?

It's the aggressive timeout and the weedy Kimsufi server I'm running ABS on. It should be fixed by #1884.

**Comment by advplyr** [comment]
Updated in v2.3.0
