### ISSUE TITLE
[Enhancement]: Allow podcast to be queued to browser storage before playing (ie: not streaming to device)

### ISSUE THREAD

**Issue by wanderling** [advplyr/audiobookshelf#1902]
### Describe the feature/enhancement

A setting on the web UI to allow a podcast episode to be fully queued to browser storage before starting to play. I have had numerous instances where I have asked for a podcast to play but the stream can't keep up. instead of waiting for the buffer to refill, the player stops playing and declares the playback 'finished'. Manual retries result in the same behavior. I am making a similar ask for the android app as well.

**Comment by advplyr** [comment]
This is discussed here https://github.com/advplyr/audiobookshelf-app/issues/782. As mentioned there it seems this is an issue with the podcast(s) you are playing and not the audio player.
Abs is using the native web browser HTML5 audio element. This should handle buffering well on its own
