### ISSUE TITLE
[Bug]: Discs Imported as Books, when folder names are "Book Name (Disc ##)"

### ISSUE THREAD

**Issue by CarsonDavis** [advplyr/audiobookshelf#1904]
### Describe the issue

Discs are imported as books when the disc folder follows the structure "Book Name (Disc 01)". The following example will be imported as 2 books.

I've got an 80 book library and this affects 6 of the titles, a little less than 8%.

Book Name by Author
├── Book Name (Disc 01)
│   ├── Track 01.mp3
│   └── Track 02.mp3
└── Book Name (Disc 02)
    ├── Track 01.mp3
    └── Track 02.mp3

### Steps to reproduce the issue

1. add folder, "Book Name by Author" to audiobooks folder
2. navigate to the audiobook app in the browser
3. observe many books added instead of only one

### Audiobookshelf version

2.2.22

### How are you running audiobookshelf?

Docker

**Comment by Deviousretard** [comment]
You gotta change your folder structure

Put both discs in a single folder. So your directory would be ;

Author\Book\CD01\track.mp3
Author\Book\CD02\track.mp3

This will result in ABS creating a single entry book the book, but track order will be based on Disc order.

Additional info can be found at 

https://www.audiobookshelf.org/docs#book-title-folder-naming

**Comment by advplyr** [comment]
That is an unsupported directory structure right now. We could expand the support but it is unlikely the folder name you mentioned would be supported.
