### ISSUE TITLE
[Bug]: Number of backups to keep not being respected

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#1909]
### Describe the issue

The old backups don't get deleted.
![Screenshot 2023-07-16 083031](https://github.com/advplyr/audiobookshelf/assets/42061703/ee679c88-d576-41fa-b87b-465ffac9951b)
![Screenshot 2023-07-16 083215](https://github.com/advplyr/audiobookshelf/assets/42061703/ff7eff6a-21d9-47e3-b6a3-4018d614ef02)

As you can see the setting is to keep 3 backup copies, but the app doesn't delete the older ones. Just noticed it in the debacle of 2.3.0 update and revert to 2.2.3. 

Unfortunately, due to the migration to 2.3.0 and return to 2.2.3, all my old logs are no longer available.

### Steps to reproduce the issue

Can't say.

### Audiobookshelf version

2.2.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I don't think we should automatically delete old backups once you adjust the limit. It seems there was some bug happening where it kept more than 3 backups. If you can reproduce that bug let me know

**Comment by advplyr** [comment]
That would be great, just the logs around the time of the automated backup. It works by creating a new backup, then it will remove 1 backup if there are more than X amount of backups. Only 1 at a time is removed and this will be in the logs that it successfully removed 1 backup.
