### ISSUE TITLE
Feature Request:  Prefer ID3 tag over folder structure

### ISSUE THREAD

**Issue by itschrisonline** [advplyr/audiobookshelf#191]
Is there any way there could be a option to prefer ID3 over folder structure or even setting the folder structure.

There are some book series that have multiple authors for different books so current folder structure doesn't work

**Comment by advplyr** [comment]
Yes, setting the precedence for book details in the scanner is planned.

The way I handle multiple authors is they get a folder of their own.
e.g.
"John Smith, Adam Smith"

or if you prefer Last, First
"Smith, John & Smith, Adam"

Audiobookshelf will parse out those authors and you can filter by individual authors.

If you have your audiobook duplicated and put in each author folder then you will end up with 2 of the same audiobook in audiobookshelf regardless of precedence.

**Comment by itschrisonline** [comment]
The issues is when its the same series but different authors per book. this is my current structure for series.

Series/Track - Author(s) - (Series #Track) - Book

the first track is to keep order and if the series is apart of a larger universe

├── Andromeda
│   ├── 01 - Michael Crichton - (Andromeda #01) - The Andromeda Strain
│   └── 02 - Daniel H. Wilson, Michael Crichton - (Andromeda #02) - The Andromeda Evolution
├── Covert-One
│   ├── 01 - Robert Ludlum, Gayle Lynds - (Covert-One #01) - The Hades Factor
│   ├── 02 - Robert Ludlum, Philip Shelby - (Covert-One #02) - The Cassandra Compact
│   ├── 03 - Robert Ludlum, Gayle Lynds - (Covert-One #03) - The Paris Option
│   ├── 04 - Gayle Lynds - (Covert-One #04) - The Altman Code
│   ├── 05 - Patrick Larkin - (Covert-One #05) - The Lazarus Vendetta
│   ├── 06 - Patrick Larkin - (Covert-One #06) - The Moscow Vector
│   ├── 07 - James H. Cobb - (Covert-One #07) - The Arctic Event
│   ├── 08 - Kyle Mills - (Covert-One #08) - The Ares Decision
│   ├── 09 - Jamie Freveletti - (Covert-One #09) - The Janus Reprisal
│   ├── 11 - Jamie Freveletti - (Covert-One #11) - The Geneva Strategy
│   └── 12 - Kyle Mills - (Covert-One #12) - The Patriot Attack
├── Dragonlance- Chronicles
│   ├── 01 - Margaret Weis, Tracy Hickman - (Dragonlance- Chronicles #01) - Dragons of Autumn Twilight
│   ├── 02 - Margaret Weis, Tracy Hickman - (Dragonlance- Chronicles #02) - Dragons of Winter Night
│   ├── 03 - Margaret Weis, Tracy Hickman - (Dragonlance- Chronicles #03) - Dragons of Spring Dawning
│   └── 04 - Margaret Weis - (Dragonlance- Chronicles #04) - Dragons of Summer Flame
├── Dragonlance- Elven Nations
│   ├── 01 - Paul B. Thompson, Tonya C. Cook - (Dragonlance- Elven Nations #01) - Firstborn
│   ├── 02 - Douglas Niles - (Dragonlance- Elven Nations #02) - The Kinslayer Wars
│   └── 03 - Paul B. Thompson, Tonya C. Cook - (Dragonlance- Elven Nations #03) - Qualinesti
├── Dragonlance- Heroes
│   ├── 01 - Richard A. Knaak - (Dragonlance- Heroes #01) - The Legend of Huma
│   ├── 02 - Nancy Varian Berberick - (Dragonlance- Heroes #02) - Stormblade
│   ├── 03 - Michael Williams - (Dragonlance- Heroes #03) - Weasel's Luck
│   ├── 04 - Richard A. Knaak - (Dragonlance- Heroes #04) - Kaz the Minotaur
│   ├── 05 - Dan Parkinson - (Dragonlance- Heroes #05) - The Gates of Thorbardin
│   └── 06 - Michael Williams - (Dragonlance- Heroes #06) - Galen Beknighted
├── Dragonlance- Legends
│   ├── 01 - Margaret Weis, Tracy Hickman - (Dragonlance- Legends #01) - Time of the Twins
│   ├── 02 - Margaret Weis, Tracy Hickman - (Dragonlance- Legends #02) - War of the Twins
│   └── 03 - Margaret Weis, Tracy Hickman - (Dragonlance- Legends #03) - Test of the Twins
├── Dragonlance- Lost Histories
│   ├── 01 - Douglas Niles - (Dragonlance- Lost Histories #01) - The Kagonesti
│   ├── 02 - Linda P. Baker - (Dragonlance- Lost Histories #02) - The Irda
│   ├── 03 - Paul B. Thompson, Tonya C. Cook - (Dragonlance- Lost Histories #03) - The Dargonesti
│   ├── 04 - Richard A. Knaak - (Dragonlance- Lost Histories #04) - Land of the Minotaurs
│   ├── 05 - Dan Parkinson - (Dragonlance- Lost Histories #05) - The Gully Dwarves
│   └── 06 - Douglas Niles - (Dragonlance- Lost Histories #06) - The Dragons
├── Dragonlance- Preludes
│   ├── 03 - Kevin Stein - (Dragonlance- Preludes #03) - Brothers Majere
│   └── 06 - Barbara Siegel, Scott Siegel - (Dragonlance- Preludes #06) - Tanis, the Shadow Years
├── Elemental Witches of Eternal Springs
│   ├── 01 - Amanda M. Lee - (Elemental Witches of Eternal Springs #01) - Bat Out of Spell
│   ├── 02 - Leighann Dobbs - (Elemental Witches of Eternal Springs #02) - Spell on Earth
│   ├── 03 - Annabel Chase - (Elemental Witches of Eternal Springs #03) - Hotter Than Spell
│   └── 04 - Gina LaManna - (Elemental Witches of Eternal Springs #04) - Spell or High Water

**Comment by advplyr** [comment]
I see what you mean now. Each of those volumes are folders that contain the audiobook?

**Comment by itschrisonline** [comment]
Yes

**Comment by advplyr** [comment]
I just pushed `v1.6.28` which is using the new scanner (v5)

I setup an audiobook using the same structure as you shared and enabled the following scan options:

![image](https://user-images.githubusercontent.com/67830747/143513297-7e0003bf-b23d-44f9-b26e-089be31df77d.png)

The ID3 tags in the first audio file will are used for details as shown in docs: https://www.audiobookshelf.org/docs/#metadata

You can test this without removing audiobooks or resetting your library by pressing the re-scan button.

Ideally in the future your library set-up won't require adjusting settings, but I'm still not sure which way to go. In my library the ID3 tags are not very accurate, so I prefer to use the folder names.
