### ISSUE TITLE
[Bug]: abs starts libraries in wrong way

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#1911]
### Describe the issue

abs starts the libraries with the last one to the first one

<img width="1015" alt="Bildschirmfoto 2023-07-16 um 06 30 22" src="https://github.com/advplyr/audiobookshelf/assets/1676196/80988d2c-8d59-4dd7-9a8a-5024234a0e87">

<img width="428" alt="Bildschirmfoto 2023-07-16 um 06 28 24" src="https://github.com/advplyr/audiobookshelf/assets/1676196/5b483c73-6463-4e0f-aa13-cd7a2d1a1ad2">

### Steps to reproduce the issue

1. start abs an see the log, the last created library starts first and if i connect on web / mobile the last library is the first entry but the library list shows this as the last

### Audiobookshelf version

2.3.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I don't understand. The logs shouldn't have anything to do with the order. The order should come from the libraries page in config.

**Comment by skyzuma** [comment]
iam not a native english btw ...

here is the order, but abs starts from the last one ... starts with "podcast" instead of "hoerbuch" ...

<img width="920" alt="Bildschirmfoto 2023-07-16 um 16 53 55" src="https://github.com/advplyr/audiobookshelf/assets/1676196/046db578-9552-4f91-ad79-5e4a864f7f26">

**Comment by nealhead** [comment]
I am also experiencing this. When opening the app, it is defaulting to my test library instead of my main library. This is even happening to users who don't have permissions to use other libraries.

**Comment by advplyr** [comment]
I fixed this for the patch I will put out soon

**Comment by advplyr** [comment]
Fixed in [v2.3.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.3.1)

**Comment by skyzuma** [comment]
sucessfully ...
