### ISSUE TITLE
[Enhancement]: KODI addon

### ISSUE THREAD

**Issue by mmBesar** [advplyr/audiobookshelf#1920]
### Describe the feature/enhancement

Great project, it's my go to on Linux and Android.
I would love to be able to listen to Podcasts/Books from [KODI](https://kodi.tv/), as it is my main media center, and keep my history in sync with other devices.
Thank you.

**Comment by advplyr** [comment]
I may be misunderstanding what you are requesting here because I've never used KODI. From what I understand that is its own media server and I'm not sure it makes sense to integrate a different media server.
Maybe this is something to request of KODI? I'm not sure
