### ISSUE TITLE
[Enhancement]: Rating System

### ISSUE THREAD

**Issue by stiefelus** [advplyr/audiobookshelf#1921]
### Describe the feature/enhancement

I would find it great if I could rate completed books and also make a few notes to sort and record my thoughts on the book. That way you can keep track of which series you want to continue or whether you want to listen to certain books a second time.
The cherry on top would be if users could access the ratings of other users and thus have recommendations for the next book.

**Comment by advplyr** [comment]
Please use the search feature to make sure what you are requesting hasn't already been requested.

Ratings has been brought up a few times #701 #901 #1184 #1153

User notes & reviews was requested #1890
