### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by ChickenCasual** [advplyr/audiobookshelf#193]
On unraid i get this error message when trying to make collections.
![image](https://user-images.githubusercontent.com/16338130/143031551-37ce3c46-6ad3-4ed7-b0d7-43edb859b483.png)
Even after a deletion of the docker image and removal of residual folders. and a reinstallations. it makes the same error. 
So no idea on the issue. 
Thank you for making a much needed product.

**Comment by parsleycolton** [comment]
Same thing is happening to me. It either started yesterday or this morning sometime.

**Comment by parsleycolton** [comment]
Same thing is happening to me. It either started yesterday or this morning sometime.

**Comment by advplyr** [comment]
I was updating the API routes and missed this one. Just fixed in `v1.6.27`
