### ISSUE TITLE
[Bug]: No start after update from 2.3.1 to 2.3.2 of audiobookshelf with linux directly (without docker or simmilar)

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1931]
### Describe the issue

Hi,

oh man, my problems don't stop after the update from 2.2.23 with abs. I use abs with linux ubuntu without docker. In the version 2.2.23 abs ran with me without problems. I updated abs first from version 2.2.23 to version 2.3.0 with the known problem that my database was not migrated. An update to version 2.3.1 unfortunately did not bring my data back, because the file olddb.zip was missing under linux ubuntu for whatever reason. But in the version 2.3.1 it ran then first again, after I have read all my data again.

Just now I have updated from version 2.3.1 to version 2.3.2. Now abs does not work at all, or is in an infinite loop when starting. My little mini computer is now always running at high speed because it tries to start abs all the time but it doesn't work. I have now turned off the computer from abs. The abs update went through without any problems. I have attached the linux log file to identify the error. 

How do I get abs to run again without losing all my data? @advplyr  can you help me?

Logfiles:
[syslog.log](https://github.com/advplyr/audiobookshelf/files/12078117/syslog.log)
[apport.log](https://github.com/advplyr/audiobookshelf/files/12078118/apport.log)

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.3.2

### How are you running audiobookshelf?

Debian/PPA

**Comment by kaiminator** [comment]
got the same with docker/docker-compose

`Attaching to Audiobookshelf
Audiobookshelf  |
Audiobookshelf  | <--- Last few GCs --->
Audiobookshelf  |
Audiobookshelf  |
Audiobookshelf  | <--- JS stacktrace --->
Audiobookshelf  |
Audiobookshelf  |
Audiobookshelf  | #
Audiobookshelf  | # Fatal javascript OOM in GC during deserialization
Audiobookshelf  | #
Audiobookshelf  |
Audiobookshelf exited with code 133`

**Comment by Maxklos** [comment]
I got the Error: `[Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed]` but i think it is a similar Problem
In the Changenotes is a hint for the solution -> [v2.3.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.3.2)
 I renamed my `config/absdatabase.sqlite` file to `absdatabase.sqlite.old` and restarted the Docker Container.
Now my ABD Server is running again.

**Comment by kaiminator** [comment]
> I got the Error: `[Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed]` but i think it is a similar Problem In the Changenotes is a hint for the solution -> [v2.3.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.3.2) I renamed my `config/absdatabase.sqlite` file to `absdatabase.sqlite.old` and restarted the Docker Container. Now my ABD Server is running again.

tried it before - does not work for me

Attaching to Audiobookshelf
Audiobookshelf  |
Audiobookshelf  | <--- Last few GCs --->
Audiobookshelf  |
Audiobookshelf  |
Audiobookshelf  | <--- JS stacktrace --->
Audiobookshelf  |
Audiobookshelf  |
Audiobookshelf  | #
Audiobookshelf  | # Fatal javascript OOM in GC during deserialization
Audiobookshelf  | #
Audiobookshelf  |
Audiobookshelf exited with code 133

**Comment by Hallo951** [comment]
> I renamed my `config/absdatabase.sqlite` file to `absdatabase.sqlite.old` and restarted the Docker Container.
> Now my ABD Server is running again.

Unfortunately, that didn't work for me either. The error remains the same... @advplyr  do you have another idea?

**Comment by derkington** [comment]
Same problem for me on Linux (not a container).  My logs show the same as what has been reported in the syslog file attached by  Hallo951.

**Comment by CoryM** [comment]
In 2.3.2 added NODE_OPTIONS=--max-old-space-size=8096 to the Dockerfile. this causes node to grab 8 gigs of ram and then release it on startup.  

Add this to your docker-compose.yaml file
```
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024 
```

If your using "docker run" then add bellow to work around the issue.
`-e "NODE_OPTIONS=--max-old-space-size=1024"`

**Comment by cdmatter** [comment]
> In 2.3.2 added NODE_OPTIONS=--max-old-space-size=8096 to the Dockerfile. this causes node to grab 8 gigs of ram and then release it on startup.
> 
> Add this to your docker-compose.yaml file
> 
> ```
>     environment:
>       - NODE_OPTIONS=--max-old-space-size=1024 
> ```
> 
> If your using "docker run" then add bellow to work around the issue. `-e "NODE_OPTIONS=--max-old-space-size=1024"`
> 
> -- EDIT -- I run mine on a 2G Raspberry Pi 4 and could not run it, had to find out why.

I was getting the same errors as @kaiminator with my docker instance of audiobookshelf.  Applying the environment edit to my docker compose file as suggested by @CoryM fixed my issue and now my audiobookshlef container is running again!  I am running Armbian with OMV6 installed (using the openmediavault-compose plugin for docker) on an ODROID HC2 (similar to an XU4).  Thanks!

**Comment by Hallo951** [comment]
Hmm, nice if this works under Docker but how do I solve the problem directly under Linux Ubuntu?

**Comment by kaiminator** [comment]
> > In 2.3.2 added NODE_OPTIONS=--max-old-space-size=8096 to the Dockerfile. this causes node to grab 8 gigs of ram and then release it on startup.
> > Add this to your docker-compose.yaml file
> > ```
> >     environment:
> >       - NODE_OPTIONS=--max-old-space-size=1024 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If your using "docker run" then add bellow to work around the issue. `-e "NODE_OPTIONS=--max-old-space-size=1024"`
> > -- EDIT -- I run mine on a 2G Raspberry Pi 4 and could not run it, had to find out why.
> 
> I was getting the same errors as @kaiminator with my docker instance of audiobookshelf. Applying the environment edit to my docker compose file as suggested by @CoryM fixed my issue and now my audiobookshlef container is running again! I am running Armbian with OMV6 installed (using the openmediavault-compose plugin for docker) on an ODROID HC2 (similar to an XU4). Thanks!

Can confirm this works under raspbian/arm/pi 4

**Comment by Hallo951** [comment]
I don't know if it helps but here I found a post about setting a node option on Linux. I'm not a computer expert on Linux directley, so I can't do much with it, but maybe the link helps to solve the problem.

Link: [https://stackoverflow.com/questions/56982005/where-do-i-set-node-options-max-old-space-size-2048](https://stackoverflow.com/questions/56982005/where-do-i-set-node-options-max-old-space-size-2048)

**Comment by Hallo951** [comment]
Ha, I solved it.  Adudiobookshelf (Abs) is now running again under Linux directly (without docker or ....). Jeppi :)

My procedure and solution was as follows: 

1. stop Abs
2. go to the environment file of Abs (on Linux this file is located in the path /etc/default/audiobookshelf) and open the edit mode of this file
3. add a new line with the command: NODE_OPTIONS=--max-old-space-size=8192 (Info: if you have less RAM available the space size should be smaller)
4. save the changes (save) and close the file.
5. restart Abs.
6. done

For a better overview here is a screenshot of my environment file:
![Audiobookshelf_Einstellungen](https://github.com/advplyr/audiobookshelf/assets/40667862/f6aa0a51-62bf-4576-be63-c3d5430e4328)

With this I was able to fix the error.

@advplyr  For future versions, could you make it so that this NODE_OPTIONS is automatically set in the environment file?

**Comment by advplyr** [comment]
We don't want to require users to have 8GB of available space in order to install Abs
