### ISSUE TITLE
[Enhancement]: Manually or Automatically restart running progresses after crash

### ISSUE THREAD

**Issue by b3nd1k** [advplyr/audiobookshelf#1934]
### Describe the feature/enhancement

I (unfortunately) often find that Audiobookshelf crashes when I have books in the queue waitting to be embedded or converted into a single file. After the restart, I have no idea which book was sucessfulle embedded and which were not. 

When I want the embeded information in the file to match what is displayed in the Audiobookshelf app, this is a nightmare. When the server crashes for whatever reason, allow us to either manually restart the queue or have it do so automatically.

**Comment by advplyr** [comment]
Can you share any information on the crash that is happening?

**Comment by b3nd1k** [comment]
I am. I couldn't find any good ways to export the logs from my Synology server, so I had to restult to taking screenshots. The screenshots have to be read from botton to the top. There is two screenshots.
<img width="1781" alt="1" src="https://github.com/advplyr/audiobookshelf/assets/96381857/8ceaec4d-0b24-4a51-99d6-f8e3bc16c9c9">
<img width="1778" alt="2" src="https://github.com/advplyr/audiobookshelf/assets/96381857/f23a5145-1560-44bc-b8f1-a0fbc5d10139">

**Comment by advplyr** [comment]
What version of the server are you using?

**Comment by advplyr** [comment]
Somehow a new author is being created without a name causing that crash you shared. I fixed it so it won't crash but it would be nice to know how your data is getting pulled in. Are you using OPF files?
