### ISSUE TITLE
[Enhancement]: Option to "Embed All" and "Convert All"

### ISSUE THREAD

**Issue by b3nd1k** [advplyr/audiobookshelf#1937]
### Describe the feature/enhancement

I'd like the option to convert all multi-track audiobooks into a M4B file, as well as the option to embed all files or all files where information differs from Audiobookshelf and naitive file. That way I don't have to select each book manually.

**Comment by advplyr** [comment]
Duplicate of #1679

**Comment by advplyr** [comment]
Duplicate of #1267
