### ISSUE TITLE
[Bug]: do not start due to libc change

### ISSUE THREAD

**Issue by nephaste** [advplyr/audiobookshelf#1939]
### Describe the issue

I built Qnap NAS QPKG for Audiobookshelf

https://www.myqnap.org/product/audiobookshelf/

but your last version 2.3.2 is breaking start due to libc issue on sqlite node module

![image](https://github.com/advplyr/audiobookshelf/assets/3392684/b192f0e7-9c01-4797-9928-a70d7630d8ed)

i am building QPKG with the ppa version you propose , since you only propose a docker version and no instruction to build it from source

all Qnap users was very happy to have an undockerised version, can you please fix this issue ?

thanks a lot from all Qnap Community

### Steps to reproduce the issue

1. Load Qnap QPKG
2. /etc/init.d/Audiobookshelf.sh restart
3. bring the error on startup

### Audiobookshelf version

3.2.3

### How are you running audiobookshelf?

Debian/PPA

**Comment by nephaste** [comment]
if i remember to avoid this issue you need build node_sqlite3 from source

 npm install --build-from-source

**Comment by advplyr** [comment]
Yeah unfortunately there isn't much I can do about it since we are using sqlite now. I don't know anything about Qnap

https://www.npmjs.com/package/sqlite3

**Comment by nephaste** [comment]
Hi thanks for the answer

any chance to get the nativ build instruction, i can compile it on nativ Linux for the old glibc
We have a lot of users using it and this issue is real problem..

thanks a lot
