### ISSUE TITLE
[Bug]: RSS feeds not showing artwork post 2.3.X upgrade

### ISSUE THREAD

**Issue by captainnapalm** [advplyr/audiobookshelf#1948]
### Describe the issue

The cover for RSS feeds does not seem to be working anymore. Checking an RSS feed, the <image> tag ends with `/cover` with no extension and when visiting that link in my browser I get `Not found`. 

### Steps to reproduce the issue

1. Visit a podcast or an audiobook 
2. Click 3 dot menu and "Open RSS Feed"
3. Subscribe to this feed from a podcast or RSS feed reader
4. No image shows up

### Audiobookshelf version

v2.3.3

### How are you running audiobookshelf?

Docker

**Comment by Jakerfv** [comment]
I'm also having this issue. I tried on two different podcasting apps (Pocket Casts and Apple Podcasts). I also seem to be having an issue with playback. I get errors from both of these platforms and I can't play anything even though the podcast shows up on their UI (without the cover art, of course).

**Comment by garyee** [comment]
I have the same issue.

**Comment by advplyr** [comment]
Fixed in [v2.4.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.0)

**Comment by garyee** [comment]
It works now for newly added podcasts.
