### ISSUE TITLE
[Bug]: book not downloading

### ISSUE THREAD

**Issue by kcmccombs** [advplyr/audiobookshelf#1951]
### Describe the issue

sense last server up date i have issues with the screen and downloading  books this is a image of trying to download a book and the screen also is oversize some

![IMG_2218](https://github.com/advplyr/audiobookshelf/assets/34385839/0c59eaf8-9156-44cd-a243-1de1041b18c2)

### Steps to reproduce the issue

1. not sure how 

### Audiobookshelf version

version 2.3.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
A bunch of fixes were made in v2.3.3, please update to the latest version

**Comment by kcmccombs** [comment]
thanks for the fast reply
