### ISSUE TITLE
[Bug]: "Save metadata with item" has no effect

### ISSUE THREAD

**Issue by theS1LV3R** [advplyr/audiobookshelf#1952]
### Describe the issue

Metadata is never saved to file, regardless of the value of the option "Save metadata with item" or "Metadata File Format".

Possible reason could be that LibraryItem.saveMetadata is never called anywhere in the codebase. See [this search](https://github.com/search?q=repo%3Aadvplyr/audiobookshelf%20saveMetadata&type=code).

### Steps to reproduce the issue

1. Fresh install, have books or audiobooks
2. Set up library, enable "Save metadata with item"
3. Scan library, observe how no metadata files are created.

### Audiobookshelf version

v.2.3.3

### How are you running audiobookshelf?

Docker

_edit was cuz I thought I had missed a result, turns out it was actually the bug being fixed, ignore the edits_

**Comment by advplyr** [comment]
Fixed in [v2.4.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.0)
