### ISSUE TITLE
[Bug]: Quick Embed for existing m4b files

### ISSUE THREAD

**Issue by gplans73** [advplyr/audiobookshelf#1955]
### Describe the issue

ABS seems to do a decent job of locating this information regarding the books ide tags but will not embed into my existing m4b files. If I have mp3's then this function works but not on existing m4b files. 

### Steps to reproduce the issue

1. Books that have been converted by Audiobookconverter (MAC)
2. ABS is able to identify the books ide tag but the quick embed will not save this to the m4b file.

### Audiobookshelf version

2.3.3

### How are you running audiobookshelf?

Docker

**Comment by Khameleon05** [comment]
I too just noticed this issue. I'm not sure what was used to convert these audiobooks, but any changes (quick embed or full) nothing saves any of the changes and it reverts back. Any I personally downloaded with Libation (or thousands of my other books) don't have this issue, it's specifically a set of (so far) three books I absolutely cannot embed tags.

**Comment by nichwall** [comment]
I reference this issue a lot, but do those m4b files have an issue with their metadata like it's discussed here? The new server versions correctly force a transcode when streaming so they play correctly, but wondering if an issue with the file metadata prevents the embed.

https://github.com/advplyr/audiobookshelf/issues/1872
