### ISSUE TITLE
Add checkbox to users page to disable remote access for users with root privileges [Enhancement]: 

### ISSUE THREAD

**Issue by VacantlyCrushing** [advplyr/audiobookshelf#1958]
### Describe the feature/enhancement

A good security feature to have would be able to add the ability to disable remote access (via checkbox under user settings), for those with root privileges. This is another level of security for the service.

**Comment by advplyr** [comment]
Is this a duplicate of #1269 ?

**Comment by VacantlyCrushing** [comment]
Th

> Is this a duplicate of #1269 ?

This is an additional layer, in conjunction with 1269. I know Emby (Which JF is based upon) allows this as a setting under Users to simply "disable remote connections" (e.g. anything that isn't on the local subnet, 10.0.0.24 etc etc)

**Comment by advplyr** [comment]
This can be combined with #1269 since what you are mentioning here is the primary use-case for #1269.

**Comment by advplyr** [comment]
Duplicate of #1269
