### ISSUE TITLE
[BUG] Scanner doesn't parse Volume # with decimal in it

### ISSUE THREAD

**Issue by typhooncarr** [advplyr/audiobookshelf#196]
Scanning books with a Volume #0.5, or any decimal point, the parser fails and just uses the whole number (ie. 0)
![image](https://user-images.githubusercontent.com/94880451/143155320-39e9344e-37c8-4cb6-a5cb-86ea77d7505e.png)

Correct Entry for the example above
![image](https://user-images.githubusercontent.com/94880451/143155411-7ebbacc8-6af5-445d-a163-8ab723738213.png)

**Comment by advplyr** [comment]
I didn't set it up to parse decimals originally. I just released `v1.6.29` that will parse volumes with decimals.
