### ISSUE TITLE
[Feature Request] ARMv7 support

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#197]
Hi, it would be awesome if this could be installed on my raspberry pi since that's what I use to host my Plex and other libraries.

Cheers. Stay safe.

**Comment by advplyr** [comment]
Hey I just released `v1.6.29` with a docker build for linux/arm/v7. I haven't tested this yet if you could let me know if it runs.
Hopefully you were talking about docker.
https://hub.docker.com/layers/advplyr/audiobookshelf/latest/images/sha256-d88677d850961d5ae778d84a01952abf37720d15e238773f98d2699a3bd32ca7

**Comment by raviwarrier** [comment]
That's amazing. Will install and try it out this week and let you know how it goes soon. Thanks for creating this version.
