### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by patrickrobbins** [advplyr/audiobookshelf#1971]
### Describe the issue

Server crashed.  restarted docker and worked fine so far. I will try to find how to increase logging levels

### Steps to reproduce the issue

1. unknown

here are the logs before and after crash: 

{"timestamp":"2023-07-26 11:19:08","source":"Logger.js:114","message":"[Watcher] Initializing watcher for \"AudioBooks\".","levelName":"INFO","level":2}
{"timestamp":"2023-07-26 11:19:08","source":"Logger.js:114","message":"Listening on port :80","levelName":"INFO","level":2}
{"timestamp":"2023-07-26 11:19:22","source":"Logger.js:114","message":"[Watcher] \"AudioBooks\" Ready","levelName":"INFO","level":2}
{"timestamp":"2023-07-26 12:27:14","source":"Logger.js:114","message":"[Server] Socket Connected NuM9CpJnNyIQ9npMAAAB","levelName":"INFO","level":2}
{"timestamp":"2023-07-26 12:27:14","source":"Logger.js:126","message":"[MeController] syncLocalMediaProgress invalid local media progress object no library item [object Object]","levelName":"ERROR","level":4}
{"timestamp":"2023-07-26 21:24:36","source":"Logger.js:114","message":"=== Starting Server ===","levelName":"INFO","level":2}
{"timestamp":"2023-07-26 21:24:36","source":"Logger.js:114","message":"[Server] Init v2.3.3","levelName":"INFO","level":2}

### Audiobookshelf version

2.3.3

### How are you running audiobookshelf?

Docker

**Comment by patrickrobbins** [comment]
I have set the logging level to debug to see if I can capture a future crash.

**Comment by advplyr** [comment]
Can you capture the logs from the container instead of using the ones from Abs? There is an uncaught exception that isn't going to show up in Abs logs, we need to get the container logs to see it.

**Comment by patrickrobbins** [comment]
I use unraid, and it looks like it is not persisting the logs past a container restart.  I will investigate more.

**Comment by advplyr** [comment]
I took another look and I found the issue. There is media progress on your mobile device that is trying to sync with the server but the linked library item no longer exists. The next server release will fix this, otherwise you can try finding the downloaded item on your device that is the problem and removing it.

**Comment by patrickrobbins** [comment]
ok.  I had some books but they had issues, so I removed and readded them, so that might be the issue.  I have had some issues previously where I click the remove from continue listening and it will remove, but next login it will be back, if that tries to sync that might exacerbate the issue.  Thanks for the quick response.

**Comment by advplyr** [comment]
Fixed in [v2.4.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.0)

Although the latest server version is now 2.4.1. This is for the original issue you can let me know if it is still causing issues on 2.4.1
