### ISSUE TITLE
[Bug]: scan library triggers full scan instead of change only

### ISSUE THREAD

**Issue by adispi** [advplyr/audiobookshelf#1973]
### Describe the issue

every time i add a book or change my book folder structure to comply with ABS, triggering a full scan is updating the entire library.
since i have 14K book, each scan is taking 8-10 hours.
can this be returned to what it used to be where a scan only looked for new books only?

### Steps to reproduce the issue

1. add a book or change a folder
2. go to settings and run scan under library

### Audiobookshelf version

2.3.3

### How are you running audiobookshelf?

Docker

**Comment by wtanksleyjr** [comment]
Is this possibly why when I ran a scan a couple of days ago I got 1400 books re-scanned (i.e. they went from their hand-curated Matched settings to the first-scanned settings based on OPF or folder names)? I very carefully did NOT choose "Force Re-Scan". Fortunately the backups work, no lost data.

**Comment by advplyr** [comment]
The scanner was updated in v2.4.2 and this shouldn't be the case. Let me know if this is still an issue on latest
