### ISSUE TITLE
[Bug]: No cover art rehosting RSS 

### ISSUE THREAD

**Issue by fillilutten** [advplyr/audiobookshelf#1979]
### Describe the issue

The url to the cover art is just returning "Not Found" 

https://audiobookshelf.xxxx.com/feed/sib/cover

### Steps to reproduce the issue

1. Add podcast
2. Rehost with RSS
3. Add in Podcast player 

### Audiobookshelf version

v.2.3.3

### How are you running audiobookshelf?

Docker

**Comment by PulsarFTW** [comment]
I am experiencing the same problem. I am also running v.2.3.3 with docker. Any other podcast app is not displaying the cover and going direct to the URL results in a "Not Found" error.

It also occurs when going via local IP.

**Comment by fillilutten** [comment]
Sorry, missed that it was already posted. My bad!  https://github.com/advplyr/audiobookshelf/issues/1948

**Comment by advplyr** [comment]
Duplicate of #1948

**Comment by advplyr** [comment]
Yeah this will be fixed in the next release
