### ISSUE TITLE
[Enhancement]: Enable users to configure and use Ereader Devices

### ISSUE THREAD

**Issue by rileytb** [advplyr/audiobookshelf#1982]
### Describe the feature/enhancement

Just like root can create an ereader device/email and send ebooks to the ereader, allow a user to enter their own ereader device/email and give them the ability to have the "Send to device" option on ebooks.

**Comment by R-Jimenez** [comment]
Would love to see this feature too. Could be as simple as just adding another toggle in the user permissions section to enable the option. 

Current workaround does suffice though. My wife doesn't want to deal with managing or accidentally deleting things (I primarily listen to audio, she primarily reads, so this ebook support has been incredible!), so I made her user account an "Admin", but then manually untoggled the other permissions (like Deleting/Updating), and it seems to be working fine.

**Comment by SpartacusIam** [comment]
Following this.  Would love this feature so I can ditch Calibre & Calibre-Web.

**Comment by advplyr** [comment]
Partially added in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)

When you add/edit an ereader device on the /config/email page you can now set which users can send ebooks to it. By default it is only admin users.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/1c7c4340-4954-4ef5-862a-66d8ab2a8b82)

Managing ereader devices still must be done by an admin users. Once a user has access to an ereader device they will see the "Send ebook to..." context menu.

I will leave this issue open for now if allowing users to add their own ereader device is wanted

**Comment by SpartacusIam** [comment]
> Partially added in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)
> 
> When you add/edit an ereader device on the /config/email page you can now set which users can send ebooks to it. By default it is only admin users.
> 
> ![image](https://user-images.githubusercontent.com/67830747/278892592-1c7c4340-4954-4ef5-862a-66d8ab2a8b82.png)
> 
> Managing ereader devices still must be done by an admin users. Once a user has access to an ereader device they will see the "Send ebook to..." context menu.
> 
> I will leave this issue open for now if allowing users to add their own ereader device is wanted

I would love the ability for users to add their own readers.  That way I can create user accounts and give them to my friends and family and let them run with it.

**Comment by ZLoth** [comment]
> Managing ereader devices still must be done by an admin users. Once a user has access to an ereader device they will see the "Send ebook to..." context menu.
> 
> I will leave this issue open for now if allowing users to add their own ereader device is wanted

Anything to relieve the administrative burden and make it self service. There may be times, however, that the administrator may have to set this up for a technologically challenged person.
