### ISSUE TITLE
M4B Encoding Progress Bar[Enhancement]: 

### ISSUE THREAD

**Issue by haptiqblack** [advplyr/audiobookshelf#1986]
### Describe the feature/enhancement

The M4B encoding feature is incredible. The only thing that I would like to see is a progress letting us know how it is going along. Sometimes it takes long enough to where I might think something is wrong. Would be nice to be able to see progress and how it looks. Same thing with the quick embeds as well.

**Comment by mew1033** [comment]
For the m4b encoding, it looks like abs uses fluent-ffmpeg (https://github.com/fluent-ffmpeg/node-fluent-ffmpeg). Fluent ffmpeg has a progress estimator/emitter/thing: https://fluent-ffmpeg.github.io/#:~:text=transcoding%20progress%20information. Maybe we could see that information in the abs UI?

**Comment by nichwall** [comment]
Addressed in https://github.com/advplyr/audiobookshelf/pull/3182
