### ISSUE TITLE
[Bug]: Deleting a library deletes all content within

### ISSUE THREAD

**Issue by Rade0nFighter** [advplyr/audiobookshelf#1989]
### Describe the issue

When removing a library, all the contents of the corresponding folder on my hard drive was removed.

This resulted in lots of lost content which wasn't the intention, my assumption (given the lack of warning) was that this was simply to delete the Audiobookshelf library, not the underlying content.

If this is intentional, might I suggest having a checkbox that says "Would you like to also remove all library content (delete all files)"?

Excellent app by the way, just had a massive panic using it earlier :)

### Steps to reproduce the issue

1. Create a library pointing to an existing audiobooks/podcast folder 
2. (optional) Add content to it
3. Delete the library
4. Weep as your content has been hard deleted from your device

### Audiobookshelf version

v2.3.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Deleting a library does not delete any contents, it only removes data from the database. It will delete the metadata folders from `/metadata/item/{item id}/` if it exists because those are managed by Abs. Abs will not delete anything from your mapped media folders without a message saying it will do so.

I tested this and looked over the code again and I'm not sure how this could have happened for you. Is this reproducible for you if you create a test folder?

**Comment by advplyr** [comment]
No problem, you can also join the Discord or Matrix server if you have any questions. It's pretty active

**Comment by Clancey** [comment]
This is 100% reproducable. Just hapened to me. Steps to reproduce:

Folder Structure:

- AudioBooks
  - Author
    - Book1
      - book1.m4b
      - meta.json
    - Book2
      - book2.m4b
      - meta.json

I have the setting to save the meta.json and cover art to the book folder.

Now to reproduce. Add an m4b to the Author folder So it looks like:
- AudioBooks
  - Author
    - Book1
      - book1.m4b
      - meta.json
    - Book2
      - book2.m4b
      - meta.json
    - book3.m4b
    - meta.json

Once book3 is added, do a force scan of the library. And it will think book 1 and 2 are gone.

So fix book 3

- AudioBooks
  - Author
    - Book1
      - book1.m4b
      - meta.json
    - Book2
      - book2.m4b
      - meta.json
    - Book 3
      - book3.m4b
      - meta.json

At this point book 3 will show up as missing. If it isn't don't move the meta.json so it's still at the author root. Force scan. And it should show up missing.

Now you will have 2 copies of book 3 in your library.

If you delete the one marked as missing, it will delete the Author Folder. Removing missing items should be a local database function only. Deleting the folders should never happen.

**Comment by nichwall** [comment]
> If you delete the one marked as missing, it will delete the Author Folder. Removing missing items should be a local database function only. Deleting the folders should never happen.

Did you have the checkbox that says "Delete Item from filesystem" selected on the delete popup? If so, then it will also delete the files from your filesystem.
