### ISSUE TITLE
[Enhancement]:  Select storage location for backups

### ISSUE THREAD

**Issue by gravitykillseverything** [advplyr/audiobookshelf#199]
It defaults to /backups right now which means a new mount point in docker.   Sonarr/Radarr/etc. store their backups in a subfolder of /config which should already be mounted.   

This would be helpful for those backing up their docker configs directory so they could also get snapshots of the internal backups.  

It's easy enough to add another mount point but it may be helpful of having the option to match the behavior of other containers.

It may be worth doing this for the metadata as well.

**Comment by advplyr** [comment]
This may be an error because backups are stored in `/metadata/backups`.

I didn't know about Unraid overriding the /config volume mapping and built the initial project thinking the /config was going in `/appdata/audiobookshelf/config/`.
I haven't updated the directory structure yet because it is going to require writing code to fix the old structures.

**Comment by gravitykillseverything** [comment]
Ok i see that now.  I didn't go into the filesystem, I was just looking at the backups page where indicated path is: /backups/2021-11-28T1522.audiobookshelf

Maybe, have it say /metadata/backups instead?

I'm also not using unraid and am unfamiliar with it.  I'm using Debian and using Portainer and docker-compose.  I've mounted all the docker /config directories to /docker/config/$app_name, 

Also, having everything in the config directory is really minor and probably not worth pursuing.   This is great project and is way better than other solutions.

**Comment by jaymarvels** [comment]
+1 on this specifically with this solution:

https://github.com/advplyr/audiobookshelf/discussions/340#discussioncomment-2077531

**Comment by advplyr** [comment]
Closing this to make #2973 the main thread on this issue
