### ISSUE TITLE
[Bug]: Series are not displayed in the expected order on an authors page.

### ISSUE THREAD

**Issue by alexedwards565** [advplyr/audiobookshelf#1992]
### Describe the issue

Series are not displayed in the expected order on an authors page.

The Directory structure I entered was:

```
── Author Name
   ├── 1. Series 1
   │   └── Books
   ├── 2. Series 2
   │   └── Book 1 - The Runes of the Earth (2004)
   ├── [...]
   ├── 11. Series 11
   │   └── Books
   └── 12. Series 12
       └── Books

```

The outcome of this on the author page was:

1. Series 1
11. Series 11
12. Series 12
2. Series 2\
...

The Expected outcome was:

1. Series 1
2. Series 2
...
11. Series 11
12. Series 12

### Steps to reproduce the issue

1.  Use an ordered list in the directory structure when inputting an ordered list of series under an author

### Audiobookshelf version

v2.3.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Are you using the `edge` docker image?

**Comment by alexedwards565** [comment]
I'm using `latest`

**Comment by alexedwards565** [comment]
Ive just tested on the `edge` image and it is behaving the same way

**Comment by CLHatch** [comment]
> ### Describe the issue
> Series are not displayed in the expected order on an authors page.
> 
> The Directory structure I entered was:
> 
> ```
> ── Author Name
>    ├── 1. Series 1
>    │   └── Books
>    ├── 2. Series 2
>    │   └── Book 1 - The Runes of the Earth (2004)
>    ├── [...]
>    ├── 11. Series 11
>    │   └── Books
>    └── 12. Series 12
>        └── Books
> ```
> 
> The outcome of this on the author page was:
> 
> 1. Series 1
> 2. Series 11
> 3. Series 12
> 4. Series 2
>    ...
> 
> The Expected outcome was:
> 
> 1. Series 1
> 2. Series 2
>    ...
> 3. Series 11
> 4. Series 12
> 
> ### Steps to reproduce the issue
> 1. Use an ordered list in the directory structure when inputting an ordered list of series under an author
> 
> ### Audiobookshelf version
> v2.3.3
> 
> ### How are you running audiobookshelf?
> Docker

Isn't this expected behavior?  A "Series" doesn't have a number associated with it, the BOOKS in a series have numbers associated with them.  So ABS would just see the `1. Series` as a series with that exact name `1. Series`, no parsing of the number.

**Comment by alexedwards565** [comment]
Thanks for the workaround

Yes, in most use cases the order of the series wouldn't matter, but I'm I'm trying to organise Doctor Who audio dramas, so the order of series does matter. I imagine there are other cases where it would matter too. 

I know ABS doesn't parse the numbering on a series as it would with books, but I did expect series to be listed in alphabetical order, which they largely are. The issue is that numerals are not sorted alphabetically in the expected way, as they are in a file browser.

**Comment by CLHatch** [comment]
> Thanks for the workaround
> 
> Yes, in most use cases the order of the series wouldn't matter, but I'm I'm trying to organise Doctor Who audio dramas, so the order of series does matter. I imagine there are other cases where it would matter too.
> 
> I know ABS doesn't parse the numbering on a series as it would with books, but I did expect series to be listed in alphabetical order, which they largely are. The issue is that numerals are not sorted alphabetically in the expected way, as they are in a file browser.

I actually 0 fill the numbers when adding the series order to books to force the sorting. Not all file systems try to recognize numbers like that, and just do straight ASCII sorting.

**Comment by alexedwards565** [comment]
Ah, I don't think i've encountered sorting like this before, but ill keep it in mind. Thank you!
