### ISSUE TITLE
[Enhancement]: Feature Request - Custom Forward/Back Skip Increment times

### ISSUE THREAD

**Issue by copey02** [advplyr/audiobookshelf#1995]
### Describe the feature/enhancement

Currently the mobile apps allow for setting 5/10/30 second custom increment times for forward/backwards playback skipping. 
There doesn't appear to be any equivalent from the desktop/server UI. 

Would really love the ability to set custom skip increments on the desktop, additionally if we could either set a custom skip time or at the very least get greater than 30 second defaults added to both mobile app and server. 
I see a lot of apps use 15 second increments up to 60, then 30 second increments. ie - 15/30/45/60/90/2min. 
Personally, I like to use Backwards skip 30 seconds and Forward skip 90 seconds for my podcast listening. 
A default of only 10 second skip on the desktop is painful for podcast listening 😆

**Comment by nichwall** [comment]
Related issue
https://github.com/advplyr/audiobookshelf/issues/1722

**Comment by advplyr** [comment]
Added in [v2.12.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.12.0)
