### ISSUE TITLE
[Enhancement]: Reading List for Audiobooks

### ISSUE THREAD

**Issue by mdeeter** [advplyr/audiobookshelf#1997]
### Describe the feature/enhancement

Make it easier to keep track of (and update) what book(s) to read next.

I'd love to see the ability to add a book to a list that is easy to organize (like a drag/drop list).

![image](https://github.com/advplyr/audiobookshelf/assets/136902/bef17e08-2f9c-4f51-be0a-f8c248fe2017)

![image](https://github.com/advplyr/audiobookshelf/assets/136902/d68d4247-516c-4f5e-948c-01311a92001c)

**Comment by Mega-Volti** [comment]
Just create a collection called "Reading List" and add your ABs to that collection. Problem solved?

**Comment by mdeeter** [comment]
> Just create a collection called "Reading List" and add your ABs to that collection. Problem solved?

I'll try that out... thanks!

**Comment by mdeeter** [comment]
Ah yes.... okay.  yeah... this will solve my UX

**Comment by skronenwerth** [comment]
In my opinion, this does not solve the problem:

1. the audiobooks in my reading list should appear directly on the start screen, as should the Continue listening, Continue series, etc. sections.

2. in practice, I have to make more clicks than with other apps. With Prologue, for example, I have to press and hold on the book and I immediately have the option to add it to my reading list. This doesn't feel quite right for ABS.

I have attached a screenshot of Prologue and how it is solved there, I have used the option on the start screen very intensively here, this is one of the few functions that I miss in ABS.

_Leseliste = Reading List_

![291DBAC4-134C-4696-AB31-60383E5B3C2E_4_5005_c](https://github.com/advplyr/audiobookshelf/assets/786982/c8ae3b8d-8477-43eb-a56c-aa56926bd457)

**Comment by advplyr** [comment]
There is a feature request open to allow customizing the home screen shelves that would solve your use-case.

**Comment by skronenwerth** [comment]
> There is a feature request open to allow customizing the home screen shelves that would solve your use-case.

That would be really great if it could be solved on this way.

I currently have three reasons why my family mainly continue to use the Plex / Prologue combination and don't switch to ABS. The reading list is one of them ...

**Comment by advplyr** [comment]
Hmm that one seems very minor. It is something planned but there many other things that would take priority over that.

**Comment by advplyr** [comment]
Fyi when I'm looking for what the most popular feature requests are I sort by the number of thumbs up on the issues. Give a thumbs up on anything you want to see, like these:

https://github.com/advplyr/audiobookshelf/issues/1273

https://github.com/advplyr/audiobookshelf/issues/1241

**Comment by skronenwerth** [comment]
> Hmm that one seems very minor. It is something planned but there many other things that would take priority over that.

I've been following the development here and I'm amazed at what you've managed to do in a very short time. I agree that there are more important things to implement.

My solution before ABS was the combination of Plex and Prologue, at least those to whom I had given access are now used to this function ... I think it's pure habituation, that they don't want to do without it. It doesn't affect very many people at the moment, but I still wanted to report back what is stopping them from switching.

**Comment by skronenwerth** [comment]
> Fyi when I'm looking for what the most popular feature requests are I sort by the number of thumbs up on the issues. Give a thumbs up on anything you want to see, like these:
> 
> #1273
> 
> #1241

I will do it, thanks!

**Comment by mdeeter** [comment]
Just a note... the "collection" solution of this didn't solve my problem like I mentioned... I instead used a playlist.
