### ISSUE TITLE
[Bug]: Some genre tags are not being parsed correctly

### ISSUE THREAD

**Issue by kevingatera** [advplyr/audiobookshelf#1998]
### Describe the issue

Some genre tags are not being parsed correctly. See below for more details. Thank you!!

### Steps to reproduce the issue

1. Choose audible.com in the match tab
2. Type in "B0797YBP7N" for a book example or a book called "12 Rules for life"
3. Observe that one of the tags is "Relationships, Parenting & Personal Development" instead of 2 separate tags: "Relationships" and "Parenting & Personal Development" respectively.

See image below:
![image](https://github.com/advplyr/audiobookshelf/assets/22301610/0caa25b7-63f8-41f3-ba15-040a95d0684b)

### Audiobookshelf version

v2.3.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This is coming from audible and isn't a parsing issue. You can see that audible considers that a genre: https://api.audible.com/1.0/catalog/products/B0797YBP7N?response_groups=category_ladders

```json
{
  "ladder": [
    {
      "id": "18574784011",
      "name": "Relationships, Parenting & Personal Development"
    },
    {
      "id": "18574800011",
      "name": "Personal Development"
    },
    {
      "id": "18574809011",
      "name": "Personal Success"
    }
  ],
  "root": "Genres"
}
```
