### ISSUE TITLE
Scanner won't scan

### ISSUE THREAD

**Issue by Amitheous** [advplyr/audiobookshelf#2]
When clicking scan, just shows "Scanning... 0 of 0 0%", and the log shows an error of "Api called without a token", along with a few other things. When I initially tested the scan after the install, it did scan the 2 books I put in there for testing, but after the recent update it won't add any of the other books that I added. I've attached a txt file that's a copy of the log for reference

[Audiobookshelf log 8-20-2021.txt](https://github.com/advplyr/audiobookshelf/files/7024893/Audiobookshelf.log.8-20-2021.txt)

**Comment by advplyr** [comment]
I believe I fixed that on one of the recent updates. Try the latest version.

**Comment by MangaValk** [comment]
fixed now for me!

**Comment by Amitheous** [comment]
Yep latest update fixed it, thank you!
