### ISSUE TITLE
[Bug]: 2.3.3 Docker container fails to start

### ISSUE THREAD

**Issue by jlacount** [advplyr/audiobookshelf#2001]
### Describe the issue

Running great on 2.2.23.  Tried updating to 2.3.3 and docker container fails to start.  I couldn't find a report for this exact issue, but I saw reading through issue reports that 2.3.0 introduced a new SQLITE db.  The new absdatabase.sqlite file was created, but sitting at size 0.  I deleted that file and reverted back to 2.2.23 without issue.   I also tried upgrading to 2.3.0 and experienced the same issue, so I figured it would be the same for 2.3.1 and 2.3.2, didn't try them.

Running in Docker for Windows.  Docker log here (trimmed to a single failure, as I have restart set to "always" and the error appeared multiple times):

Config /config /metadata
[2023-08-11 16:13:23] INFO: === Starting Server ===
[2023-08-11 16:13:23] INFO: [Server] Init v2.3.3
[2023-08-11 16:13:23] INFO: [Database] absdatabase.sqlite not found at /config/absdatabase.sqlite
[2023-08-11 16:13:23] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
[2023-08-11 16:13:23] INFO: [Database] Db connection was successful
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Database.<anonymous> (/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
    at /node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
    at new Promise (<anonymous>)
    at Query.run (/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
    at /node_modules/sequelize/lib/sequelize.js:315:28
    at async SQLiteQueryInterface.createTable (/node_modules/sequelize/lib/dialects/abstract/query-interface.js:98:12)
    at async Function.sync (/node_modules/sequelize/lib/model.js:942:7)
    at async Sequelize.sync (/node_modules/sequelize/lib/sequelize.js:377:9)
    at async Database.init (/server/Database.js:58:5)
    at async Server.init (/server/Server.js:100:5) {
  name: 'SequelizeTimeoutError',
  parent: [Error: SQLITE_BUSY: database is locked] {
    errno: 5,
    code: 'SQLITE_BUSY',
    sql: 'CREATE TABLE IF NOT EXISTS `users` (`id` UUID PRIMARY KEY, `username` VARCHAR(255), `email` VARCHAR(255), `pash` VARCHAR(255), `type` VARCHAR(255), `token` VARCHAR(255), `isActive` TINYINT(1) DEFAULT 0, `isLocked` TINYINT(1) DEFAULT 0, `lastSeen` DATETIME, `permissions` JSON, `bookmarks` JSON, `extraData` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);'
  },
  original: [Error: SQLITE_BUSY: database is locked] {
    errno: 5,
    code: 'SQLITE_BUSY',
    sql: 'CREATE TABLE IF NOT EXISTS `users` (`id` UUID PRIMARY KEY, `username` VARCHAR(255), `email` VARCHAR(255), `pash` VARCHAR(255), `type` VARCHAR(255), `token` VARCHAR(255), `isActive` TINYINT(1) DEFAULT 0, `isLocked` TINYINT(1) DEFAULT 0, `lastSeen` DATETIME, `permissions` JSON, `bookmarks` JSON, `extraData` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);'
  },
  sql: 'CREATE TABLE IF NOT EXISTS `users` (`id` UUID PRIMARY KEY, `username` VARCHAR(255), `email` VARCHAR(255), `pash` VARCHAR(255), `type` VARCHAR(255), `token` VARCHAR(255), `isActive` TINYINT(1) DEFAULT 0, `isLocked` TINYINT(1) DEFAULT 0, `lastSeen` DATETIME, `permissions` JSON, `bookmarks` JSON, `extraData` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);',
  parameters: {}
}

### Steps to reproduce the issue

1. Have existing, issue-free 2.2.23 installation.
2. Upgrade to 2.3.3
3. Attempt to start Docker container:

Windows docker startup command:
docker run -d -e AUDIOBOOKSHELF_UID=99 -e AUDIOBOOKSHELF_GID=100 -p 13378:80 -v audiobooks:/audiobooks -v podcasts:/podcasts -v config:/config -v metadata:/metadata --name audiobookshelf --restart always ghcr.io/advplyr/audiobookshelf

### Audiobookshelf version

2.3.3

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Related issue that should have been fixed since 2.3.0, but may still be happening. https://github.com/advplyr/audiobookshelf/issues/1910

**Comment by advplyr** [comment]
I don't think I've released the fix for #1910 yet.

This same issue was mention on discord and was fixed by moving the db off of a network share. See https://discord.com/channels/942908292873723984/1006652923306066040/1139290656460771348

**Comment by advplyr** [comment]
This has been resolved in v2.4.2
