### ISSUE TITLE
re-scan and update DB

### ISSUE THREAD

**Issue by Maximilian85** [advplyr/audiobookshelf#201]
I don't understand when the database is updated and changes in existing audiobooks become current. 

For example, I have an audiobook that is incorrectly numbered Part 101-202. Then I change on the server the correct name in the file name and if wrong also in the ID3 tag. When I then re-scan the audiobook it shows me the new filenames but the audiobook is still displayed incorrectly. Only when I go to Manage Tracks and press Save, the new sorting takes over and the issue message disappears. This should actually happen directly during a re-scan. 

Edit: 
I had a wrong folder structure in a series. 

Name/Vol 1 ../Name/.mp3

So each episode was recognized as a separate series. 

I have now all copied so that the structure is correct. 

Name/Vol 1../.mp3

Now the series is displayed correctly but all other series per folder are displayed after updating the database. Here the old entries should be removed. 

![Unbenannt](https://user-images.githubusercontent.com/76774860/143719506-61085062-4653-4dfc-aa1f-f757c1e91a5d.png)

**Comment by advplyr** [comment]
You have to manually remove them. If you filter by issues and select all you can batch delete them all at once.

**Comment by Maximilian85** [comment]
Thank you, I have now done so, I had assumed that the wrong entries are removed from the database during a re-scan.

**Comment by advplyr** [comment]
It definitely shouldn't take more than a few seconds, there is something wrong here.
I'm seeing the book is attempting to be removed twice, is there any chance you may have pressed delete multiple times?

I would recommend restarting the server if you haven't already. The database updates should be less than a second and I see yours are taking up to 6 seconds in some cases.

**Comment by Maximilian85** [comment]
I marked all 200 entries and then pressed Delete at the top. And I hope only once. I'll restart the container and see if I have the same problems the next time I edit.

**Comment by advplyr** [comment]
There have been a few updates that may have resolved this. If this is still an issue feel free to re-open this.
