### ISSUE TITLE
[Bug]: Download Podcast Episode via local PodSync App

### ISSUE THREAD

**Issue by berts83231** [advplyr/audiobookshelf#2012]
### Describe the issue

I'm using PodSync to create podcast audio files from Youtube videos.

PodSync and AudioBookShelf are both running in Docker on the same network.

I can add RSS feeds from PodSync to AudioBookShelf. But I can not download the "episodes".

The main error is
``[ffmpegHelpers] Failed to download podcast episode with url "http://localhost:8080/Kurzgesagt/cFslUSyfZPc.mp3" Error: connect ECONNREFUSED 127.0.0.1:8080`

It should not try to download the episode from localhost. It should use the IP address of the PodSync docker container.

Here are curl tests run from inside the AudioBookShelf docker container.

```
/ # curl -I http://localhost:8080/Kurzgesagt/28T91fgkpkA.mp3
curl: (7) Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server

/ # curl -I http://localhost:8090/Kurzgesagt/28T91fgkpkA.mp3
curl: (7) Failed to connect to localhost port 8090 after 0 ms: Couldn't connect to server

/ # curl -I http://podsync230816:8080/Kurzgesagt/28T91fgkpkA.mp3
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 883364
Content-Type: audio/mpeg
Last-Modified: Thu, 17 Aug 2023 01:02:31 GMT
Date: Thu, 17 Aug 2023 01:38:35 GMT

/ # curl -I http://192.168.2.0:8090/Kurzgesagt/28T91fgkpkA.mp3
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 883364
Content-Type: audio/mpeg
Last-Modified: Thu, 17 Aug 2023 01:02:31 GMT
Date: Thu, 17 Aug 2023 01:38:40 GMT
```

### Steps to reproduce the issue

1. Download the docker-compose and config file from the Gitlab link below.
2. Get a YouTube Data API v3 key; https://console.cloud.google.com/apis/api/youtube.googleapis.com/credentials
3. Tweak the docker and config file
4. Run https://github.com/mxpv/podsync and AudioBookShelf in Docker
5. Add a new podcast library
6. Add a new podcast from a URL generated by podsync
7. Try to download an episode

Config & logs files: https://gitlab.com/-/snippets/2584528

Video: https://www.dropbox.com/scl/fi/9xwky2v0bb020fuqbj7iv/audiobookshelf-podsync.webm?rlkey=evsefmgllw8ii1grcm0v6j263&dl=0

### Audiobookshelf version

v2.3.3

### How are you running audiobookshelf?

Docker

**Comment by online-ua** [comment]
Set hostname for podsync.

```
[server]
port = 8080
hostname = "https://my.test.host:4443"
```

**Comment by advplyr** [comment]
Abs is going to download from whatever URL you put in there. You will need to put a URL in there that Abs can reach.
