### ISSUE TITLE
[Enhancement]: Show publish year on library page when sorting books by publish year

### ISSUE THREAD

**Issue by xAhlen** [advplyr/audiobookshelf#2017]
### Describe the feature/enhancement

Hi
First off love the project! My feature request is to be able to toggle the option to show publish date under the name of the book. 
Maybe as a third row?

Book Title
Author
Publishing Year, with a smaller font.

**Comment by advplyr** [comment]
Added in [v2.4.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.0)
