### ISSUE TITLE
[Enhancement] More speed options

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf#202]
There is many audiobooks apps and we all can agree that listening to audiobook with preffered speed is a standard.  
Could you please add more speed options, so we could change it by 0.1 .  I'm mostly listening to 1.7 tempo. There is a big gap between 1.5 and 2. 

Thank you, great app!

**Comment by advplyr** [comment]
Just released `v1.6.30` with a new playback speed widget that allows adjusting by 0.1 between 0.5 and 3. I had been meaning to re-do that for a while.
![image](https://user-images.githubusercontent.com/67830747/143726506-f932697e-30cf-4396-8d7e-083c8603913e.png)
