### ISSUE TITLE
[Bug]: Searches fail and Audiobookshelf crashes

### ISSUE THREAD

**Issue by PurpleBooth** [advplyr/audiobookshelf#2023]
### Describe the issue

I am seeing a crash every time I search. I think this is something to do with data, as the application was working fine prior to adding any of my books to it.

```
[Query] Elapsed 6ms
/server/utils/queries/authorFilters.js:57
      limit,
      ^

ReferenceError: limit is not defined
    at Object.search (/server/utils/queries/authorFilters.js:57:7)
    at Object.search (/server/utils/queries/libraryItemsBookFilters.js:1102:47)
    at async ApiRouter.search (/server/controllers/LibraryController.js:742:21)\
```

Note: this works fine on "latest", so not a big deal I guess so long as it doesn't make it to latest.

### Steps to reproduce the issue

1. Perform a search

(I am sure there is more to this than just the search, otherwise someone else would have spotted it)

### Audiobookshelf version

v2.3.3 - ghcr.io/advplyr/audiobookshelf:edge (ghcr.io/advplyr/audiobookshelf@sha256:38d9b1969b2f3c3c524ef39a9ff49e9555750a0373ac9cb9dbbf0ba9953e2c31)

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Thanks, just fixed this on edge
