### ISSUE TITLE
CarPlay for iOS app

### ISSUE THREAD

**Issue by tedstriker** [advplyr/audiobookshelf#2024]
### Describe the feature/enhancement

It would be really nice, if the Audiobookshelf app would show up on the Apple CarPlay display just like Spotify.

**Comment by nichwall** [comment]
https://github.com/advplyr/audiobookshelf-app/issues/475

**Comment by advplyr** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/475
