### ISSUE TITLE
Feature Request: Store Book Information in Folder

### ISSUE THREAD

**Issue by itschrisonline** [advplyr/audiobookshelf#203]
Wondering if it is possible to store book info in the book folder like an opf file especially after a match

Thanks for the help

**Comment by advplyr** [comment]
There is a "Save Metadata" button when you edit a book that saves a `.nfo` file with some book details, but it may not be complete.
I've been waiting for suggestions on this feature and seeing what format people would prefer this to be saved as. Then eventually there can be an option to save it for all books automatically or something.

Is there a format that you would prefer?

**Comment by itschrisonline** [comment]
To be honest. I would prefer what the standard is which seems to be nfo or opf.

Would like it so that if the database would crash and I had to re-add all the books, I could rely on that file.

**Comment by itschrisonline** [comment]
nfo seems like the easist so the user could generate it themselves

**Comment by advplyr** [comment]
The difference is an NFO file is intended to be human readable, whereas an OPF file is for software. Audiobookshelf also parses OPF files.
The way to go might be to just include both with some settings.

**Comment by FlamingoDaBird** [comment]
Hi
Regarding this issue, opf seems to be connected to ebooks.
Audiobooks seems to be without a standard.. but it seems like they're working on it and w3c has somewhat of a standard.
But oh boy is it complicated and beyond our needs I'm guessing :)

All audiobooks I seem to acquire follows the ID3 "standard" which is kind of volatile but for our purposes it could be more than sufficient. I was able to transfer my PLEX audiobook library (which I first created/tagged  first with MP3 tag: https://www.mp3tag.de/en/    )

What would be the purpose of generating xml/opf/nfo/other versus using ID3 tags? 

Also is there a specific reason reason why audiobookshelf doesn't update the ID3 tags when editing? It only saves text files? I might be confused on that part :)

regarding MP3tag and populating (scraping) the ID3 fields, it works quite well. Here's an example:

![image](https://user-images.githubusercontent.com/47981216/145244720-1b6affca-5356-40b5-bb8a-b4e9c3a5d381.png)


Thanks.

**Comment by wtanksleyjr** [comment]
I don't mind allowing audiofile retagging if people want it. Please don't make it the primary means, though... I want to be able to hand over the data I want this app to see without having to change the main files themselves. One reason for this is that we're still in the early days of audiobooks, and I have 3 applications I'm forced to use to manage them; none of them agree completely on what the right way to do that is. I don't want a tagfight. Another reason is that those are huge files and will really mess up my backups if people start changing them.

**Comment by advplyr** [comment]
The implemented solution is the abmetadata file stored as "metadata.abs" and can be optionally stored in your library item folder.

Not fully built out yet but you can find more info here: https://www.audiobookshelf.org/docs#abmetadata

**Comment by itschrisonline** [comment]
Sorry for reopening. Just want to see if is still the standard ot if it has been change. Unable to see on the website

**Comment by wtanksleyjr** [comment]
I'm still seeing ABS files generated, and my ODF files are still being
loaded, so I'd say "yes".

I'm slowly building up my own YAML-based book description for my own
audiobook organization, though; it can handle anything in Audible, ODM, and
of course in tags. If we need a new standard I'd be glad to offer mine --
it's based on some 3000 Audible books and about the same number of ODM
files I scraped out of my various recycle bins.

-Wm
