### ISSUE TITLE
[Bug]: multiple adding audiobooks not working

### ISSUE THREAD

**Issue by swoop124** [advplyr/audiobookshelf#2034]
### Describe the issue

I have a folder for a bookseries (audioplays) I added about 50 audiobooks (all *.m4b) they are not recognized when I scan for new content.
the structure:
<author>/<series>/<separate folder for each book>

When i search for new content, audiobookshelf edds only 3 books per partial-scan. Full-Scan recognize only the audiobooks already listed in audiobookshelf. It is annoying to scann for example for 100 new books.

the Books are located in a Samba Mount. the docker container is seeing all new files

### Steps to reproduce the issue

1. goto settings
2. select librarys
3. select the library you would scan
4. kilck the tree dots
5. select partial-scan
6. wait til the scan is completet
7. klick on audiobookshelf on the top
8. change into series 
9. search for the series you have added now books
10. only 3 +/- books are added.

### Audiobookshelf version

2.3.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you share your directory structure? I just see `//`

Can you check the docker logs to see if there are any errors during the scan?

**Comment by swoop124** [comment]
sorry the structure is like 
author / series / book1
author / series / book2
author / series / book3
to
author / series / book59
