### ISSUE TITLE
[Bug]: Comic reader incorrect sort order. Only using first 5 digits in file name.

### ISSUE THREAD

**Issue by wfulcher** [advplyr/audiobookshelf#2036]
### Describe the issue

Book reader is reading Manga CBZ internal files out of order. The internal files are 0000XX so when it reads the files it sees 00002X before 000001. Spoke on discord about this.  Advplyr mentioned the program was searching for numbers between 1-5 digits. Unfortunately my internal files have longer names.  

Im not certain why mangal names internal like this. Short term fix, Ill see if I can change naming. But I image when others start using this feature they may run into similar issues.

Attached should be screenshots of the issue. 

![image_2023-08-29_153609963](https://github.com/advplyr/audiobookshelf/assets/8878898/6ed686e2-c550-431e-9aae-aa0ea0a347eb)
![image_2023-08-29_153625424](https://github.com/advplyr/audiobookshelf/assets/8878898/3d0598a0-d1b3-46a3-9a12-9321bb3c01eb)

### Steps to reproduce the issue

1. Add Library for Manga or comics
2. Add downloaded CBZ
3. Attempt to read with web app or phone app and it will read out of order if file is named 0000XX

### Audiobookshelf version

2.3.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.4.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.0)
