### ISSUE TITLE
[Enhancement]: Filter Category for unset

### ISSUE THREAD

**Issue by CSuerig** [advplyr/audiobookshelf#2037]
### Describe the feature/enhancement

I as a content admin would like to be able to filter the criteria (e.g. author, reader, language etc.) of my audiobooks for unset fields. This allows me to add missing information to the audiobook metadata easily. 

Please tell me in case, such a feature already exists. I searched for it, but could not find it. btw. Its a really great piece of software! I would also like to contribute as developer.

**Comment by advplyr** [comment]
Are you looking for the "Missing" filter?

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/3dbd8260-feac-469b-a25c-05abf7aea65b)

**Comment by CSuerig** [comment]
Yes, thats exactly what I was looking for. Sorry, I didn't see that it was implemented as separat filter
