### ISSUE TITLE
[Enhancement]: Backup Enhancements

### ISSUE THREAD

**Issue by projx** [advplyr/audiobookshelf#2043]
### Describe the feature/enhancement

Hi

Currently the ABS backup page is a little confusing:

1.The interface suggests the backup path is "/backups/filename.autobookshelf", but they appear to be stored under /metadata/backups
2. When downloading a backup via the browser, no filename is presented to the browser, so the browser just calls it "download"

This could be addressed by the following:

1. Displaying fhe full OS path, I would suggested adding this once, as long with the other information sections i.e. "Number of Backups to Keep".
2. In the table which shows the backup files, remove "/backup", so it just shows the filename
3. When downloading one of the backup files, the browser should name the file accordingly, as it is shown in table mention in #2
4. Allow the back-up location to be configurable.

Thank you :)

**Comment by advplyr** [comment]
Setting the back-up location has been requested in #199 
I agree with the other updates you suggest

**Comment by advplyr** [comment]
This was implemented for the next release in https://github.com/advplyr/audiobookshelf/pull/2133

**Comment by advplyr** [comment]
Added in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
