### ISSUE TITLE
[Enhancement]: search in ebooks

### ISSUE THREAD

**Issue by coandco** [advplyr/audiobookshelf#2045]
### Describe the feature/enhancement

Most ebook readers I've seen have the ability to search for a particular phrase in the book and jump to it.  It's a very handy feature if you're trying to pull up a quote from a book, or if you want to synchronize your progress between devices that don't otherwise support it.

**Comment by advplyr** [comment]
Added in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)
