### ISSUE TITLE
[Bug]: Get Connection refused when downloading

### ISSUE THREAD

**Issue by The-Ducktor** [advplyr/audiobookshelf#2049]
### Describe the issue

whenever i try to download a audiobook on browser and click the button i get a connection refused error

### Steps to reproduce the issue

1. Go to book
2. click on more options
3. click on download

### Audiobookshelf version

v2.3.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Please provide error logs or more details about your setup. Like have you tried using a local IP address. This is currently not reproducible for me.

**Comment by The-Ducktor** [comment]
sure it's I  used docker compose and binded a directory to the host machine it seems to be an issue with some audiobooks but not for others i use the local ip for the linux machine running it or a dns rewrite

https://github.com/advplyr/audiobookshelf/assets/130664593/eb3385a9-7bc9-484f-a6de-b647d75d25e1

the built in logger set to debug doesn't look very helpful but

-
[logs.txt](https://github.com/advplyr/audiobookshelf/files/12543061/logs.txt)

**Comment by advplyr** [comment]
Are you still having this issue on v2.4.3? I'm not sure how to reproduce this

**Comment by The-Ducktor** [comment]
had i issue with some files so i just put them in audacity and immediately exported them and it fixed my issue so kinda
