### ISSUE TITLE
[Enhancement]: Show audiobook duration (or a comparison) in Match search workflow

### ISSUE THREAD

**Issue by danseitz** [advplyr/audiobookshelf#2050]
### Describe the feature/enhancement

Right now, when I’m searching for a match, I can’t see the duration of my current audiobook unless I go back to the audiobook details. I can see the duration of the potential matches, so showing the duration of the book I’m trying to match would be helpful as often audiobook duration is a good indicator of a match. Here’s an example:

<img width="790" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/3443594/58d39124-2399-4c25-bd3d-8e60b633f4ec">

A few options:
- Show the duration of the audiobook somewhere in the search (like top right)
- Show a comparison of the duration of the audiobook next to each search result (for instance “Runtime: 9h 7m (1m shorter)” or (exact match) if same duration)

I actually think the second one would be a little more elegant and not require finding a place to put the duration of your audiobook in the search.

**Comment by nichwall** [comment]
#1803
Has nice additional ideas though

**Comment by danseitz** [comment]
> #1803
> Has nice additional ideas though

Thanks! I searched but missed this. I’ll add my comments to the other post and close this one.
