### ISSUE TITLE
[Bug]: the urls of the items in the rss feed do not work due to special characters in the title

### ISSUE THREAD

**Issue by garyee** [advplyr/audiobookshelf#2061]
### Describe the issue

I setup my library and one of the episodes could not be played. I looked a the raw rss file and saw that the links are broken by the special characters like @ and &. I think they should be url encoded in order for it to work.

### Steps to reproduce the issue

1. upload a file with a name containing whitespaces and special characters like @ and &
2. open the rss feed
3. the link in the item section will be broken due to the special characters like @ and & beeing in the link

### Audiobookshelf version

Latest version

### How are you running audiobookshelf?

Docker

**Comment by garyee** [comment]
Could the not encoded url be part of the reason for #2008 ? If so this could be closed as a duplicate.

**Comment by advplyr** [comment]
Can you test again in v2.4.1?

**Comment by garyee** [comment]
It is still broken sorry. I think the problem is that the characters which are not allowed in a URL like `&` and `@` are not [URL encoded](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI), but I could be wrong.
![image](https://github.com/advplyr/audiobookshelf/assets/5537949/b2dab2e5-940f-41fb-9b6f-706837ea66bb)

**Comment by advplyr** [comment]
I'm not able to reproduce this. I just created an RSS feed with an episode that has all of those characters in the filename with no issues.
