### ISSUE TITLE
[Bug]: With v2.4.0, GETting all library items with no limit returns empty results array

### ISSUE THREAD

**Issue by mihailim** [advplyr/audiobookshelf#2067]
### Describe the issue

Since v2.4.0, trying to issue [Get a Library's Items API call](https://github.com/advplyr/audiobookshelf-slate/blob/main/source/includes/_libraries.md#get-a-librarys-items) without any limit returns an empty `results[]` array, despite returning the correct `total`.

This can be worked around by specifying a very large limit and either ommitting the page number or asking for page 0, but it's a surprising breaking change.

### Steps to reproduce the issue

1. `curl "https://abs.example.com/api/libraries/LIBRARYIDHERE/items" -H "Authorization: Bearer TOKENHERE"`
    yields:
    `{"results":[],"total":2031,"limit":0,"page":0,"sortDesc":false,"mediaType":"book","minified":false,"collapseseries":false,"include":"","offset":0}`
1. By contrast, `curl "https://abs.example.com/api/libraries/LIBRARYIDHERE/items?limit=99999" -H "Authorization: Bearer TOKENHERE"`
    yields:
    `{"results":[ <elided all the 2031 correct results here> ],"total":2031,"limit":0,"page":0,"sortDesc":false,"mediaType":"book","minified":false,"collapseseries":false,"include":"","offset":0}`

The behavior is the same, empty results, when trying with varying other query parameters. Only `limit` seems to work.

### Audiobookshelf version

v2.4.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.4.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.1)
