### ISSUE TITLE
[Bug?] Missing Books

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#207]
Plex shows 1261 books:
![image](https://user-images.githubusercontent.com/42061703/143880722-55a5ec21-ca70-4289-af5d-ac64f8a56a97.png)

While ABS shows only 1245 books:
![image](https://user-images.githubusercontent.com/42061703/143880842-67c1249b-b5c7-4393-9851-ac8bdd60a974.png)

They both use the same audiobooks folder, so what could be the reason for missing books? As far as I can remember, my books are either in M4B/M4A (single or multiple) or MP3 (single or multiple) formats. Are there any formats that ABS doesn't recognize?

**Comment by advplyr** [comment]
Audiobookshelf supports 'm4b', 'mp3', 'm4a', 'flac', 'opus', 'mp4'.

All audiobooks must be in their own folder. Scanner log files are stored in `/metadata/logs/scans/`, might be worth looking at that.

**Comment by raviwarrier** [comment]
Ah, okay. Will check the logs and report back if I find anything or have a question. Cheers.

**Comment by raviwarrier** [comment]
The scans didn't show any errors. I am searching for a way to re-scan the library, but can't find any button that allows me to do so. Can you tell me where I can perform that action from, please?

**Comment by advplyr** [comment]
Let me know if this is still an issue

**Comment by raviwarrier** [comment]
I'll let you know. December's busy for me and I am taking a break from listening to books. Will resume in January and then test out both your server and app. Cheers.
