### ISSUE TITLE
[Bug]: Library size total uses too large of a unit

### ISSUE THREAD

**Issue by BlackHoleFox** [advplyr/audiobookshelf#2072]
### Describe the issue

After updating from v2.3.3 to v2.4.1 I looked at a library and saw it was estimating too much storage in use. Neither the host its running on nor the NAS holding the files via SMB has that much capacity (136 TB) so this just seems like a numbers calculation bug somewhere.

<img width="641" alt="Capture" src="https://github.com/advplyr/audiobookshelf/assets/20936452/67af731c-0733-41ef-9699-2df5f06b6fa1">

This is what Windows reports about the SMB share where the podcast audio is stored:

<img width="183" alt="Capture" src="https://github.com/advplyr/audiobookshelf/assets/20936452/5def2627-ca8c-4243-9384-c5a4a61877bb">

### Steps to reproduce the issue

1. Create a podcast library in audiobookshelf
2. Fill it with at least a few gigabytes of content
3. Open the library statistics page
4. See that its saying you have `n` TB of audio and not GB

### Audiobookshelf version

v2.4.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.4.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.2)
