### ISSUE TITLE
[Bug]: can not download episode using proxy in ABS docker in Synology

### ISSUE THREAD

**Issue by hozorro** [advplyr/audiobookshelf#2078]
### Describe the issue

I have add two enviroment variable:
HTTP_PROXY=http://192.168.1.2:7890
HTTPS_PROXY=http://192.168.1.2:7890
192.168.1.2 is another host which run clash on it, and configed with lan proxy.
when using abs to add a new podcast rss with its url, the abs server can get the right infomation from the url. when chcek new episode, it returned right items, but when downloading the episodes, nothing appears.
the logs showed: "https://xxxx/xxx.mp3" Error: Client network socket disconnected before secure TLS connection was established.

### Steps to reproduce the issue

1. set environment varibles http_proxy and https_proxy
2. add rss url in abs podcast, get right rss information, the check new episode, and right episode item number information appeared.
3. when downloading the episodes files, nothing appears.
4. the logs: "https://xxxx/xxx.mp3" Error: Client network socket disconnected before secure TLS connection was established.

### Audiobookshelf version

v2.3.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Did you end up getting this working? These errors are usually not a bug with Abs but rather an issue with your setup. If you still think this is a bug with Abs let me know

**Comment by raiots** [comment]
Same issue and I am now using ABS v2.4.3, have you solve that problem?

**Comment by Chandler-QJL** [comment]
> Same issue and I am now using ABS v2.4.3, have you solve that problem?

Same issue here. Running ABS 2.16.2
