### ISSUE TITLE
[Bug?] Discrepancy in Filtered/sorted view

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#208]
Both Plex and ABS have been sorted by Date Added, but they show different results in the view. I know Plex is correct because I remember the days/dates I added the books and Soil was indeed the last book I added.

Could you check for (and fix) this?

Plex: ![image](https://user-images.githubusercontent.com/42061703/143880722-55a5ec21-ca70-4289-af5d-ac64f8a56a97.png)
ABS:  ![image](https://user-images.githubusercontent.com/42061703/143880842-67c1249b-b5c7-4393-9851-ac8bdd60a974.png)

**Comment by advplyr** [comment]
Date added is the date the audiobook was added to audiobookshelf. If they are all scanned at the same time then they will have similar date added depending on how long they took to scan.

**Comment by raviwarrier** [comment]
Got it.
