### ISSUE TITLE
[Bug]: Refreshing Podcast Queue Page Causes Error

### ISSUE THREAD

**Issue by l3gitpanda** [advplyr/audiobookshelf#2088]
### Describe the issue

When trying to refresh the Queue Page in Podcasts, this error occurs in the web ui: 
Cannot GET /library/e5173eeb-485d-4cd9-974f-e587db420752/podcast/download-queue
I noticed this after downloading a ton of podcasts then refreshing the Queue page once i saw it was blank so I assume this is reproducible as long as there isn't anything in queue.

### Steps to reproduce the issue

1. Go to download queue page for podcasts
2. make sure there are not any podcasts queued
3. refresh page
4. Profit?

### Audiobookshelf version

v2.4.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.4.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.2)
