### ISSUE TITLE
[Bug]: Failed to get feeds, when RSS feed URLs starting with https://anchor.fm/

### ISSUE THREAD

**Issue by so02iti01** [advplyr/audiobookshelf#2094]
### Describe the issue

I've used audiobookshelf for over 100 days. However, when I used `Find Episodes` in my library and some of the podcasts `Failed to get podcast feed`. I tried to delete the data and re-add from the build-in `Search`, but I could not add them back. The only things in common with those bug podcasts is that, they share RSS feed URLs starting with `https://anchor.fm/`, e.g. https://anchor.fm/s/94175a4/podcast/rss

### Steps to reproduce the issue

1. In v.2.4.1, I delete the library items from the database and file system. I typed the names of those podcasts in the build-in `Search` and they showed up there. But I see `Failed to get podcast feed` and failed to add them back in the library. I updated to v.2.4.1, tried the same but failed again.
2. Since I can refresh the RSS data one month ago, I rolled back to v.2.3.3. But the problem is still there.

### Audiobookshelf version

v.2.4.2, v.2.4.1, v.2.3.3

### How are you running audiobookshelf?

Docker

**Comment by so02iti01** [comment]
I tried to add the RSS URL in miniflux (a RSS reader) and failed to fetch this resource, too. Then I searched in google and know that `anchor.fm` is owned by Spotify now.  I believe that something is going wrong with the hosting platform. This is evidence found on [spotifeed](https://spotifeed.timdorr.com/)
> For exclusive podcasts, Spotify is using their audio-fa.scdn.co server, which appears to be using a chunked MP4 stream that is not usable by general podcast clients.

**Comment by advplyr** [comment]
I didn't have any issues adding that podcast. You should check the logs to see what error you are getting. This is most likely your server setup

**Comment by so02iti01** [comment]
> I didn't have any issues adding that podcast. You should check the logs to see what error you are getting. This is most likely your server setup

Thanks a lot for your help. Yes, you are right. The problem is not from Audiobookshelf itself. 

I ran ` curl https://anchor.fm/s/94175a4/podcast/rss` on two of my VPS located in the US. One received normal response, while the other (with Audiobookshelf on it) received that:
```
<h1>Page unavailable</h1><p>Anchor is now part of Spotify and is not available in your country.</p><a href="https://help.anchor.fm/hc/articles/5181704556187">Learn more</a></main></body></html>%
```
It is weird, for Spotify is available in the US.

**Comment by advplyr** [comment]
Thanks for confirming. If you find any info please follow up here in-case someone else stumbles across the same thread in the future.

**Comment by so02iti01** [comment]
My friend and I find a temporary way to handle the issue：
- Run a transparent proxy on another VPS. Make sure the VPS is not rejected by Spotify.
- Add a record in `/etc/hosts` on the previous "rejected" VPS, and point `anchor.fm` and `podcasters.spotify.com` to the IP address of your proxy VPS.
