### ISSUE TITLE
[Bug]: Match Books only updates 95 of the 350+ books in my Library since 2.4.1

### ISSUE THREAD

**Issue by Spinonduality** [advplyr/audiobookshelf#2096]
### Describe the issue

When I match books in my library, only 95 of them are updated. It was working fine for all 350+ audiobooks in version 2.4.0.

### Steps to reproduce the issue

1. Match books in library
2. Note number updated
3. Confirm by looking at cover art of matched and non-matched books.

### Audiobookshelf version

2.4.2

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Is the "noted number" 95?

What happens if you go into one of the books which did not match and manually Match that book (from the edit view). Are there any results?

**Comment by iconoclasthero** [comment]
I'm having a similar issue.  A lot of books are not being matched (at least with covers; I cannot see what's going on with the metadata because...).  Additionally, to answer the question, "What happens if you go into one of the books which did not match and manually Match that book (from the edit view). Are there any results?"  The "Details" and "Match" tabs are empty regardless of how long I wait, the upload cover does not work regardless of whether I give it a local file or URL, and if I try to search for it, a bunch of thumbs come up but none of them are downloadable.

4.2.2 on native Ubuntu 22.04 (i.e., no container/docker/etc/)—apt pushed an upgrade today.

**Comment by advplyr** [comment]
If using the debian install it will be helpful if you provide logs. You can use the command `journalctl -u audiobookshelf` to see those. Optionally use flag `-f` with that command and you can watch them while you attempt to match to see what error is showing up.

If using the docker container please get the logs from the container (as opposed to using the logs in the Abs page).

**Comment by iconoclasthero** [comment]
a) how do you get journalctl to output to something I can paste,
b) how do you get jounralctl to limit to say the last few days?  I'm at line 12000 and I'm still on 2023.08.26

**Comment by advplyr** [comment]
You should only need to paste a small amount of code. I recommend not going through the entire log and instead use `journalctl -u audiobookshelf -f` and then open the match tab that isn't working. You should see the error happening and you can copy paste it.
Also, make sure you have DEBUG logs turned on. You can do that by going to the settings -> logs in the web client.
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/f138157c-e7d4-4c11-bc6a-3d00ebf21af4)

**Comment by advplyr** [comment]
Can you share the relevant log here? You don't need to share the entire log, just the relevant error message or logs shown relating to matching.

**Comment by iconoclasthero** [comment]
I put up what I have.  If it doesn't have the debug info then I'll have to wait until it generates more.

**Comment by Spinonduality** [comment]
> Is the "noted number" 95?
> 
> What happens if you go into one of the books which did not match and manually Match that book (from the edit view). Are there any results?

Yes, an alert comes up with "95 books were matched"

When I go into the books that did not match automatically, and match them manually, it seems to work fine. It is just the automatic, full-library matching that doesn't seem to work.

**Comment by Spinonduality** [comment]
> > Is the "noted number" 95?
> > What happens if you go into one of the books which did not match and manually Match that book (from the edit view). Are there any results?
> 
> Yes, an alert comes up with "95 books were matched"
> 
> When I go into the books that did not match automatically, and match them manually, it seems to work fine. It is just the automatic, full-library matching that doesn't seem to work.

Oh wow, okay when I saved the manually updated book the alert stated "no changes were made," however the cover is now showing up in my library. That seems very weird.

**Comment by advplyr** [comment]
Is this still an issue for you? I read through this again and it's not clear to me what is going on without more info and logs

**Comment by colonelmattyman** [comment]
Trying to match all books in a Library using the 3 dots menu under Settings - Library, only matches the first 100 books.

**Comment by colonelmattyman** [comment]
If I tick skip matching books with ASIN it terminates straight away. Only the first hundred books that have been scanned have an ASIN.

Are you using a 'SELECT TOP 100' query somewhere?

**Comment by advplyr** [comment]
Thanks I found the issue and it will be fixed for the next release

**Comment by colonelmattyman** [comment]
You're too good. Thank you!
