### ISSUE TITLE
Sort by Volume number in the Series

### ISSUE THREAD

**Issue by scorpio862** [advplyr/audiobookshelf#21]
It would be great if there was an option to sort the books by Volume number in the Series. 
So for example if I'm filtering books by Series, it would make sense to have the books in order by Volume number.

**Comment by advplyr** [comment]
Just added that in v1.0.8, and user permissions update/download/delete.

**Comment by baloodusudouest** [comment]
Hello, it is working? because i have a lot of books which are not sort by number in the series?

Thanks

**Comment by advplyr** [comment]
Make sure the series number is set correctly by pressing edit on the book then edit on the series in the dropdown.
If you need help with this join the Discord or Matrix server.

**Comment by baloodusudouest** [comment]
Ok, my bad, i use mp3tag to have all information tag, but the order is somehow not reconnize by audiobookshelf, but with a quick match it's working
Sorry
