### ISSUE TITLE
[Bug]: Series Name with Comma's (,) Are Split into Multiple Series

### ISSUE THREAD

**Issue by ThePlaidHatHacker** [advplyr/audiobookshelf#2100]
### Describe the issue

After upgrading from 2.3.3 to 2.4.2 and running a library scan, several audiobook series that had a comma in their name were put in to several series.  As an example Drew Hayes' "Spells, Swords, & Stealth" series turned in to 3 series, "Spells" "Swords" and "& Stealth".  All of the books are in all 3 of the series, but only the "& Stealth" series kept the book number.

I manually fixed the issue, then ran a rematch and broke them out in to 3 series again.

I was able to reproduce this with another series "Fred, The Vampire Accountant", also by Drew Hayes, split int to two series, "Fred" and "The Vampire Accountant".

I do not see any other series in my library with comma's, but I do have series with other special characters that did not break.

![Screenshot 2023-09-14 221027](https://github.com/advplyr/audiobookshelf/assets/111385078/b9ad0fd9-334a-495e-9040-d80a3d17d566)

![Screenshot 2023-09-14 221056](https://github.com/advplyr/audiobookshelf/assets/111385078/a9ed5c26-a9ad-4572-bc0c-0b9baeae269f)

### Steps to reproduce the issue

1.  Run a Match on a series that has a comma in the series name.

### Audiobookshelf version

2.4.2

### How are you running audiobookshelf?

Other

**Comment by ljlongwing** [comment]
I just came to report this same issue with the same series, thank you :)  I'm also on 2.4.2, but I believe it was an issue before this version

**Comment by advplyr** [comment]
I'm not able to reproduce this but I'm not sure how you are pulling in the series. The server settings you have are also relevant here.

Can you share your server settings, where the series information is stored and more steps on how to reproduce?

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/3f2763a9-a934-4657-a4fe-4016166697fe)

**Comment by ThePlaidHatHacker** [comment]
This looks like it was resolved in 2.4.3.  I updated this evening when i saw the notice, rescanned the affected series and they are all corrected now. 

For reference though here is how i have my server settings.

![1](https://github.com/advplyr/audiobookshelf/assets/111385078/3e0981d4-d325-493e-a8a3-cecff3c6372a)

**Comment by advplyr** [comment]
Ah I see the issue here. This is why the `.json` metadata file format was introduced. https://github.com/advplyr/audiobookshelf/issues/1775#issuecomment-1585668398

I didn't want to force everyone to switch to .json who already had an Abs server but it is the default now so I recommend changing it. It will only replace the .abs file with a .json once a change is made to the library item.
