### ISSUE TITLE
[Enhancement]: ebook type conversion

### ISSUE THREAD

**Issue by xAaeEx** [advplyr/audiobookshelf#2104]
Since you added the ebook support, which is awsome by the way, the tools tab on a ebook could have some cool toolings like conversion from epub to mobi or vice-versa.

What is your opinion on this?

**Comment by advplyr** [comment]
This would be cool but is outside the scope of this project. That would be a big project to take on and mobi support will be getting dropped from Abs in the future. Calibre handles conversion well
