### ISSUE TITLE
[Bug]: duplicate series being generated when using quick match

### ISSUE THREAD

**Issue by dtayme** [advplyr/audiobookshelf#2106]
### Describe the issue

When updating audiobook meta data using "quick match" when the series tag is populated a new entry in the series table is created. This creates multiple entries in the series view with 1 book each in those series. 

### Steps to reproduce the issue

1.  Fresh docker install
2. Create a new library
3. Run a scan on existing audiobooks (All books in root directory M4B Files generated from OpenAudible)
4. Edit an audiobook and select "quick match"
5. Each subsequent book in the series when using "quick match" will create a duplicate series entry.

### Audiobookshelf version

2.4.2

### How are you running audiobookshelf?

Docker

**Comment by WarHawk8080** [comment]
I concur...same problem, will also break them if I manually go in and match the book names later on

**Comment by JohanPotgieter** [comment]
I tried deleting all but one of the series. It will show the show however I can't select it. Other times it will not list any series when I start typing.

**Comment by The-Ducktor** [comment]
same issue

**Comment by Toblun** [comment]
Same issue if you us manual match, but you also get duplicate author with the same name :( 
![Skärmbild 2023-09-16 140726](https://github.com/advplyr/audiobookshelf/assets/51099399/57b90683-e3fc-41e6-b4aa-74ef7f5a97d0)

**Comment by Toblun** [comment]
![Skärmbild 2023-09-16 141050](https://github.com/advplyr/audiobookshelf/assets/51099399/45226a01-cee2-4e15-a843-8bb79a6a2c43)

**Comment by hobesman** [comment]
Same here. This makes the curater in me cringe. I think I'll hold off adding new books/matching existing books as much possible until this is sorted out.

**Comment by ThePlaidHatHacker** [comment]
I am seeing the same thing.  I opened another bug report on series with commas in their names getting split into multiple series, so i have been tinkering with running matches and i can't find a rhyme or reason why some are getting duplicated.  But I also seeing them fix themselves after a little while in some occurrences but not others.

**Comment by rikuddo91** [comment]
Can confirm, having similar issue. Even downgrading back to 2.3.3 doesn't help.
Matched all the book in same series with similar path, but still get each book in its own series. Trying to manually add it to same series by editing doesn't help with that.

**Comment by Mavarius1989** [comment]
When you edit the audiobook and delete the other, you can select the right one qafter that out of the drop down menu.But even if there are no duplicates under "authors-menu", there are multiple ones when you edit a title in the drop down menu.
![Screenshot 2023-09-17 173427](https://github.com/advplyr/audiobookshelf/assets/98676965/cf0ee9d8-7e8c-4a3d-ba67-711539f025ee)

**Comment by Savisthorv** [comment]
Was just about to comment the same, glad it is awaiting release, can't wait to tidy this up. Thanks!

**Comment by hobesman** [comment]
@advplyr will the planned fix address existing duplicates or just future creation of duplicates?

**Comment by advplyr** [comment]
@hobesman Unfortunately not. These can be cleaned up by using the library search and bulk edit to remove all series/authors affected. After removing re-add them. It's not ideal but writing a script to clean those on startup would take some time.

**Comment by advplyr** [comment]
Fixed in [v2.4.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.3)

**Comment by hobesman** [comment]
> @hobesman Unfortunately not. These can be cleaned up by using the library search and bulk edit to remove all series/authors affected. After removing re-add them. It's not ideal but writing a script to clean those on startup would take some time.

I'm not sure how. If I try to filter by that author, I get nothing. Should I tag a random book with that author, then remove the book and re-add it? I had already retagged the orphans to go under the primary instance of that author.

![Screenshot_20230917-154937_Chrome](https://github.com/advplyr/audiobookshelf/assets/29721765/3653d4e0-baaa-48bc-b350-9a9833d43c04)

**Comment by advplyr** [comment]
@hobesman Type the author name in the search at the top and press enter

**Comment by hobesman** [comment]
It looks like that doesn't work anyways. I switched a book from the "correct" author to one of the duplicates, then deleted that book from the db. It didn't remove the author from the search results. Now I'm scanning to re-add the deleted book but in the meantime the orphaned author entry remains. (I had 4 before and 4 after deleting the book.)

![Screenshot_20230917-161557_Chrome](https://github.com/advplyr/audiobookshelf/assets/29721765/200e6416-bd8f-4e2c-9d9e-0780328a91af)


Are you saying I have to remove everything from Brandon Mull from the library just to remove the empty references?

**Comment by advplyr** [comment]
Can you try renaming one of the empty authors and saving, then naming it back to the original name. That should remove the duplicate. I'll add a delete button on the author modal so these can be cleaned up in the next release easier.

The reason I didn't set it up to automatically remove empty authors is because you may have manually filled out some metadata on the author and it would get removed. I do have some logic in place for the scanner to remove authors with no books and no additional metadata but that would be difficult to trigger for this case.

**Comment by hobesman** [comment]
That worked. Thanks!
