### ISSUE TITLE
[Enhancement]: pigz instead of gzip

### ISSUE THREAD

**Issue by WarHawk8080** [advplyr/audiobookshelf#2107]
### Describe the feature/enhancement

Any way to impliment using multithreaded pigz instead of gzip in compression of the database/data to increase speed of searching of libraries?
And have the script see how many processor the machine has and limit it to one or two less than maximum?

https://stackoverflow.com/questions/12313242/utilizing-multi-core-for-targzip-bzip-compression-decompression
https://zlib.net/pigz/

**Comment by advplyr** [comment]
What compression are you referring to?

**Comment by WarHawk8080** [comment]
in case you are using gzip in any of your processing...if not disregard

Will allow for much more streamlined and much faster multi-core processor usage in order to gzip compressed files such as backups and whatever

**Comment by advplyr** [comment]
Thanks, this isn't being used but I'll keep that in mind
