### ISSUE TITLE
[Bug] Re-scanning books when cover is not stored with library item causes cover to be extracted again

### ISSUE THREAD

**Issue by derkington** [advplyr/audiobookshelf#2110]
### Describe the issue

- If the audiobook file has 2 or more covers/images audiobookshelf consistently does not show a cover after the file is scanned.
   
- If the image is a .Png images this also seems to cause issues and the cover image is not shown. Convert or change to jpeg or jpg and that solves the problem.

- This issue stops the files which only have one cover having their covers scanned properly. But not all of them. If you have a large group of files some “good” files will not have their image displayed after the scan.  

- Modifiying a audiobook file to only having one image, then doing a rescan of that file does not work, only a library scan worked for me.

**To correct this problem manually**

1. For each affected file I used mp3tag to remove all covers except the 1. If the image in the file was a .png I converted to jpeg/jpg.

3. Deleted audiobook  from the audiobookshelf database only

4. Perform a library scan, audiobook will be added as a new book with cover image

### Steps to reproduce the issue

perform a library scan to add a new file which has more than jpeg for its cover/image or a file where the cover/image is of the format .png

**Log file errors – I do not know if these are relevant or not.**

ERROR
[FfmpegHelpers] Extract Cover Error Error: ffmpeg exited with code 69: frame= 0 fps=0.0 q=0.0 Lsize= 0kB time=N/A bitrate=N/A speed=N/A Conversion failed! 
2023-09-17 07:48:50
ERROR
[FfmpegHelpers] Extract Cover Error Error: ffmpeg exited with code 234: frame= 1 fps=0.0 q=6.8 Lq=6.2 size=N/A time=00:00:00.00 bitrate=N/A speed= 0x Conversion failed! 
2023-09-17 07:48:51
ERROR
[FfmpegHelpers] Extract Cover Error Error: ffmpeg exited with code 69: frame= 0 fps=0.0 q=0.0 Lsize= 0kB time=N/A bitrate=N/A speed=N/A Conversion failed! 
2023-09-17 07:48:52

ERROR
[FfmpegHelpers] Extract Cover Error Error: ffmpeg exited with code 69: frame= 0 fps=0.0 q=0.0 Lsize= 0kB time=N/A bitrate=N/A speed=N/A Conversion failed! 
2023-09-17 07:48:53
ERROR
[FfmpegHelpers] Extract Cover Error Error: ffmpeg exited with code 234: frame= 1 fps=0.0 q=-0.0 Lq=-0.0 q=-0.0 size=N/A time=00:00:00.00 bitrate=N/A speed= 0x Conversion failed! 
2023-09-17 07:48:53
ERROR
[FfmpegHelpers] Extract Cover Error Error: ffmpeg exited with code 69: frame= 0 fps=0.0 q=0.0 Lsize= 0kB time=N/A bitrate=N/A speed=N/A Conversion failed! 
2023-09-17 07:48:55

### Audiobookshelf version

v2.4.2

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
I wasn't able to reproduce this. I used mp3tag to and added a jpg and a png to an audio file. I also tried just adding a single png to an audio file. These were extracted correctly.
I did find one issue that had to do with removing the old cover cache but that is unrelated to yours here.

Can you provide the full ffprobe output for the audio file you are having an issue with?

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/b7f03d9b-8898-4331-96ea-35ea9fa5586e)

Then click "Probe Audio File" in the top right of that modal.

**Comment by derkington** [comment]
Here are three examples of files that do not work. It seems like I only have half the story in what is going on. 
All the files that had given me problems before had more than 1 cover or was .png  according the mp3tag, this looks like a red herring. As described removing from DB and library scanning fixed the issue. I did that for all affected files after logging the bug ticket so they have all been modified now.

What interesting is I did a bit more of tidy on the tags of a few files last night but did not remove from the DB, then left the routine scan to run. I found some files that I thought had been fixed, again without the cover images. So something strange is happening.

Here is the output you requested for 3 files that now do not display a cover but have an embeded image.

**EXAMPLE 1** 
{
  "programs": [],
  "streams": [
    {
      "index": 0,
      "codec_name": "mp3",
      "codec_long_name": "MP3 (MPEG audio layer 3)",
      "codec_type": "audio",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "sample_fmt": "fltp",
      "sample_rate": "11025",
      "channels": 1,
      "channel_layout": "mono",
      "bits_per_sample": 0,
      "initial_padding": 0,
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/14112000",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 581548506336,
      "duration": "41209.503000",
      "bit_rate": "32000",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      }
    },
    {
      "index": 1,
      "codec_name": "mjpeg",
      "codec_long_name": "Motion JPEG",
      "profile": "Baseline",
      "codec_type": "video",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "width": 500,
      "height": 500,
      "coded_width": 500,
      "coded_height": 500,
      "closed_captions": 0,
      "film_grain": 0,
      "has_b_frames": 0,
      "sample_aspect_ratio": "1:1",
      "display_aspect_ratio": "1:1",
      "pix_fmt": "yuvj420p",
      "level": -99,
      "color_range": "pc",
      "color_space": "bt470bg",
      "chroma_location": "center",
      "refs": 1,
      "r_frame_rate": "90000/1",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "duration_ts": 3708855270,
      "duration": "41209.503000",
      "bits_per_raw_sample": "8",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 1,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "comment": "Cover (front)"
      }
    }
  ],
  "chapters": [],
  "format": {
    "filename": "/Books/Iain M. Banks/Culture/1988 - The Player of Games [Culture 2]/The Player of Games (1988) [Culture 2] - pt01.mp3",
    "nb_streams": 2,
    "nb_programs": 0,
    "format_name": "mp3",
    "format_long_name": "MP2/3 (MPEG audio layer 2/3)",
    "start_time": "0.000000",
    "duration": "41209.503000",
    "size": "164888621",
    "bit_rate": "32009",
    "probe_score": 51,
    "tags": {
      "album": "The Player of Games",
      "artist": "Iain M. Banks",
      "album_artist": "Iain M. Banks",
      "comment": "The Culture - a human\\/machine symbiotic society - has thrown up many great Game Players, and one of the greatest is Gurgeh: Jernau Morat Gurgeh, The Player of Games, master of every board, computer, and strategy. Bored with success, Gurgeh travels to the Empire of Azad, cruel and incredibly wealthy, to try their fabulous game... a game so complex, so like life itself, that the winner becomes emperor. Mocked, blackmailed, almost murdered, Gurgeh accepts the game, and with it the challenge of his life - and very possibly his death.\"",
      "composer": "Peter Kenny",
      "grouping": "Culture, Book #2",
      "copyright": "1988 Iain M. Banks",
      "genre": "Science Fiction Fantasy",
      "publisher": "Hachette Digital",
      "ITUNESGAPLESS": "1",
      "TIT3": "Culture Series, Book 2",
      "title": "The Player of Games",
      "track": "1/1",
      "tmp_Genre1": "Science Fiction Fantasy",
      "album-sort": "Culture 2 - The Player of Games",
      "ASIN": "B004EF2FXM",
      "SHOWMOVEMENT": "1",
      "SERIES": "Culture",
      "series-part": "2",
      "DESCRIPTION": "The Culture - a human\\/machine symbiotic society - has thrown up many great Game Players, and one of the greatest is Gurgeh: Jernau Morat Gurgeh, The Player of Games, master of every board, computer, and strategy. Bored with success, Gurgeh travels to the Empire of Azad, cruel and incredibly wealthy, to try their fabulous game... a game so complex, so like life itself, that the winner becomes emperor. Mocked, blackmailed, almost murdered, Gurgeh accepts the game, and with it the challenge of his life - and very possibly his death.\"",
      "ITUNESMEDIATYPE": "Audiobook",
      "date": "1988"
    }
  }
}

EXAMPLE 2
{
  "programs": [],
  "streams": [
    {
      "index": 0,
      "codec_name": "mp3",
      "codec_long_name": "MP3 (MPEG audio layer 3)",
      "codec_type": "audio",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "sample_fmt": "fltp",
      "sample_rate": "44100",
      "channels": 2,
      "channel_layout": "stereo",
      "bits_per_sample": 0,
      "initial_padding": 0,
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/14112000",
      "start_pts": 353600,
      "start_time": "0.025057",
      "duration_ts": 16226795520,
      "duration": "1149.857959",
      "bit_rate": "192000",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "encoder": "LAME3.98r"
      }
    },
    {
      "index": 1,
      "codec_name": "mjpeg",
      "codec_long_name": "Motion JPEG",
      "profile": "Baseline",
      "codec_type": "video",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "width": 1211,
      "height": 970,
      "coded_width": 1211,
      "coded_height": 970,
      "closed_captions": 0,
      "film_grain": 0,
      "has_b_frames": 0,
      "pix_fmt": "yuvj422p",
      "level": -99,
      "color_range": "pc",
      "color_space": "bt470bg",
      "chroma_location": "center",
      "refs": 1,
      "r_frame_rate": "90000/1",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 2255,
      "start_time": "0.025056",
      "duration_ts": 103487216,
      "duration": "1149.857956",
      "bits_per_raw_sample": "8",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 1,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "comment": "Cover (front)"
      }
    }
  ],
  "chapters": [],
  "format": {
    "filename": "/Books/Robert A. Heinlein/2005 - Space Cadet/Space Cadet (2005) - pt01.mp3",
    "nb_streams": 2,
    "nb_programs": 0,
    "format_name": "mp3",
    "format_long_name": "MP2/3 (MPEG audio layer 2/3)",
    "start_time": "0.025056",
    "duration": "1149.857959",
    "size": "27964129",
    "bit_rate": "194557",
    "probe_score": 51,
    "tags": {
      "album": "Space Cadet",
      "artist": "Robert A. Heinlein",
      "album_artist": "Robert A. Heinlein",
      "comment": "This is the seminal novel of a young man's education as a member of an elite, paternalistic non-military organization of leaders dedicated to preserving human civilization, the Solar Patrol, a provocative parallel to Heinlein's famous later novel, Starship Troopers. Only the best and brightest--the strongest and the most courageous--ever manage to become Space Cadets, at t",
      "composer": "David Baker and The Full Cast Family",
      "genre": "Science Fiction",
      "publisher": "Tor Books",
      "title": "Space Cadet",
      "track": "1",
      "ITUNESGAPLESS": "1",
      "asin": "B00IKVE14M",
      "tmp_Genre1": "Science Fiction",
      "DESCRIPTION": "This is the seminal novel of a young man's education as a member of an elite, paternalistic non-military organization of leaders dedicated to preserving human civilization, the Solar Patrol, a provocative parallel to Heinlein's famous later novel, Starship Troopers. Only the best and brightest--the strongest and the most courageous--ever manage to become Space Cadets, at t",
      "ITUNESMEDIATYPE": "Audiobook",
      "date": "2005"
    }
  }
}

EXAMPLE 3
{
  "programs": [],
  "streams": [
    {
      "index": 0,
      "codec_name": "mp3",
      "codec_long_name": "MP3 (MPEG audio layer 3)",
      "codec_type": "audio",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "sample_fmt": "fltp",
      "sample_rate": "44100",
      "channels": 1,
      "channel_layout": "mono",
      "bits_per_sample": 0,
      "initial_padding": 0,
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/14112000",
      "start_pts": 353600,
      "start_time": "0.025057",
      "duration_ts": 45699194880,
      "duration": "3238.321633",
      "bit_rate": "96000",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "encoder": "LAME3.98 "
      }
    },
    {
      "index": 1,
      "codec_name": "png",
      "codec_long_name": "PNG (Portable Network Graphics) image",
      "codec_type": "video",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "width": 394,
      "height": 596,
      "coded_width": 394,
      "coded_height": 596,
      "closed_captions": 0,
      "film_grain": 0,
      "has_b_frames": 0,
      "pix_fmt": "rgb24",
      "level": -99,
      "color_range": "pc",
      "color_space": "gbr",
      "refs": 1,
      "r_frame_rate": "90000/1",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 2255,
      "start_time": "0.025056",
      "duration_ts": 291448947,
      "duration": "3238.321633",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 1,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "comment": "Other"
      }
    }
  ],
  "chapters": [],
  "format": {
    "filename": "/Books/AStephen King/1991 - Needful Things (read by Stephen King)/1_ Part One - Grand Opening Celebration - Chapter 01.mp3",
    "nb_streams": 2,
    "nb_programs": 0,
    "format_name": "mp3",
    "format_long_name": "MP2/3 (MPEG audio layer 2/3)",
    "start_time": "0.025056",
    "duration": "3238.321633",
    "size": "39272226",
    "bit_rate": "97018",
    "probe_score": 51,
    "tags": {
      "album": "Needful Things",
      "artist": "Stephen King, Stephen King",
      "album_artist": "Stephen King",
      "comment": "Stephen King's number-one national best seller about a store where Leland Gaunt can sell you whatever your heart desires - sexual pleasure, wealth, power, or even more precious things - but not without exacting some price in return. Leland Gaunt opens a new shop in Castle Rock called Needful Things. Anyone who enters his store finds the object of his or her lifelong dreams and desires: a prized baseball card, a healing amulet. In addition to a token payment, Gaunt requests that each person perform a little \"deed\", usually a seemingly innocent prank played on someone else from town. These practical jokes cascade out of control, and soon the entire town is doing battle with itself. Only Sheriff Alan Pangborn suspects that Gaunt is behind the population's increasingly violent behavior. Praised as \"tremendous...wonderful...one of King's best\" (Kirkus Reviews).",
      "composer": "Stephen King",
      "copyright": "1991 Stephen King",
      "genre": "Horror",
      "publisher": "Penguin Highbridge Audio",
      "ITUNESGAPLESS": "1",
      "title": "  Part One - Grand Opening Celebration - Chapter 01",
      "track": "2",
      "tmp_Genre1": "Horror",
      "album-sort": "Needful Things",
      "ASIN": "B019HMBEWE",
      "DESCRIPTION": "Stephen King's number-one national best seller about a store where Leland Gaunt can sell you whatever your heart desires - sexual pleasure, wealth, power, or even more precious things - but not without exacting some price in return. Leland Gaunt opens a new shop in Castle Rock called Needful Things. Anyone who enters his store finds the object of his or her lifelong dreams and desires: a prized baseball card, a healing amulet. In addition to a token payment, Gaunt requests that each person perform a little \"deed\", usually a seemingly innocent prank played on someone else from town. These practical jokes cascade out of control, and soon the entire town is doing battle with itself. Only Sheriff Alan Pangborn suspects that Gaunt is behind the population's increasingly violent behavior. Praised as \"tremendous...wonderful...one of King's best\" (Kirkus Reviews).",
      "ITUNESMEDIATYPE": "Audiobook",
      "date": "1991"
    }
  }
}

**Comment by advplyr** [comment]
Can you also share a screenshot of your current server settings?

**Comment by derkington** [comment]
![Capture1](https://github.com/advplyr/audiobookshelf/assets/80588965/d302144d-7d7c-4028-9848-91f5fe80c27f)
![Capture2](https://github.com/advplyr/audiobookshelf/assets/80588965/0539f3b5-29bd-4676-a3ec-ae0a0acbfb8e)

**Comment by advplyr** [comment]
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
