### ISSUE TITLE
[Enhancement]:copy encoded m4b at last

### ISSUE THREAD

**Issue by Mavarius1989** [advplyr/audiobookshelf#2113]
### Describe the feature/enhancement

Right now, when you encode mp3 into m4b, it puts the not ready-yet m4b in the main folder and the mp3 in the backup folder. When the encoding fails, you got a not done m4b and the few not used mp3 and have to sort your files gain to start from the beginnen.

Wouldn't it be better, when you put the m4b in the backup folder and paste it into the main folder, when the encoding is done?

**Comment by advplyr** [comment]
This is currently how it is setup. Can you share the related logs, they will have `[AbMergeManager]` in them

**Comment by Mavarius1989** [comment]
I am an idiot. Didn't go for the log, just assumed something and I was wrong. There was a problem with my server in deleting all the mp3 Files after the conversion into m4b
