### ISSUE TITLE
[Bug]: When mass editing library items, somethings strange happens.

### ISSUE THREAD

**Issue by JAKAMI99** [advplyr/audiobookshelf#2116]
### Describe the issue

I have this strange issue, where, when I edit multiple items:
Let's assume I have 20 episodes of series “ABC” freshly added.
Now I select those 20 episodes and assign the series “ABC” to them.
Then I end up with 20 series, including one episode each, and there seems no way of merging them.

I also achieve the same result, when using “audible.de” for metadata.
If the metadata for multiple episodes is the same series, it creates a new series for every episode.

### Steps to reproduce the issue

1. Add new files
2. Assign same series name trough: Selecting, edit, mass edit.

### Audiobookshelf version

2.4.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This was just fixed in v2.4.3 released a minute ago. Also reported already here https://github.com/advplyr/audiobookshelf/issues/2106

**Comment by JAKAMI99** [comment]
Duplicate https://github.com/advplyr/audiobookshelf/issues/2106#issue-1899259871

**Comment by JAKAMI99** [comment]
@advplyr Damn you are fast. :D Thank you!

**Comment by JAKAMI99** [comment]
Updated, reassigned a series name for all items, no duplicates.
Thank you! You rock!
Where can I leave some pennies for a coffee?

**Comment by advplyr** [comment]
I haven't set up anything for donations. Glad it is working for you!

**Comment by JAKAMI99** [comment]
Would love to leave some appreciation in the shape of money :)
