### ISSUE TITLE
[Bug]: Cannot save series with "'s" in their name.

### ISSUE THREAD

**Issue by cooperferguson42** [advplyr/audiobookshelf#2117]
### Describe the issue

Whenever I attempt to save changes to an entry's metadata and part of that save is a series name that conatinas ['s], the changes are not saved.

### Steps to reproduce the issue

1. Edit an entry's metadata
2. Add a series whose name that contains ['s]
3. Attempt to save and close

### Audiobookshelf version

v2.4.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This is fixed already in the latest server release v2.4.3
