### ISSUE TITLE
[Bug]: [Scanner] matchLibraryItems: Library has no items after Matching Books

### ISSUE THREAD

**Issue by jezaldanluthar** [advplyr/audiobookshelf#2118]
### Describe the issue

After Matching Books on my 2nd Library the scanner will freeze and I get this error message: ERROR [Scanner] matchLibraryItems: Library has no items 01f7d1f4-2a9e-4706-bbc0-ad2cf1c3bdb1

The library Circle keeps spinning forever and the Scanning Library info won't disappear until I restart the docker

The weird thing is that this only happens for one of my libraries! If I match audiobooks in my first library with 150 audiobooks I dont get the error. Whenever I match audiobooks from my 2nd library I get this error: 

ERROR [Scanner] matchLibraryItems: Library has no items 01f7d1f4-2a9e-4706-bbc0-ad2cf1c3bdb1

Using v2.4.3 with Docker, Using Edge on Windows 10, Audiobooks are mostly mp3s and m4b files

I tried trial and error to see if it maybe was one of my audiobooks in the 2nd library was causing this. I deleted the 2nd library, created a new library, moved 1 of my audiobooks from my first library to it and still got the same error. 

I don't think it's a file name issue since matching and scanning works fine for my first library. 

Here is the file tree for the library I get the error on: https://pastebin.com/hUjErUve

I rolled back to 2.3.3 where I dont get this error. Any idea what it could be?

### Steps to reproduce the issue

1. Add 2nd library
2. Scan Library
3. Match Books
4. [Scanner] matchLibraryItems: Library has no items 01f7d1f4-2a9e-4706-bbc0-ad2cf1c3bdb1
5. Go to config/libraries
6. Circle keeps spinning forever and the Scanning Library info won't disappear until I restart the docker

![msedge_F0Ao0Mpd3C](https://github.com/advplyr/audiobookshelf/assets/47871184/77d1543b-f137-450c-86dc-ae17f30072e2)

### Audiobookshelf version

2.4.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
After you scan the library are you able to see all the books populated?

**Comment by advplyr** [comment]
Actually, I see a bug in the code that could be showing that error. How many books are scanned in for that library?

**Comment by jezaldanluthar** [comment]
> After you scan the library are you able to see all the books populated?

Yes. 

> Actually, I see a bug in the code that could be showing that error. How many books are scanned in for that library?

27 audiobooks. 

I just tried it 1 on 1. Reinstalled audiobookshelf, added 1 audiobook, scanned, match and got the error after 1 book even. 

I don't get why it works on my library with +150 books though

**Comment by advplyr** [comment]
I just tried reproducing this with a library of 4 books and a library of 22 books and wasn't able to reproduce it.

I just realized you said you have that notification that spins forever. Is that also happening with 1 book?

**Comment by advplyr** [comment]
I found the original issue you mentioned about the scan staying there spinning until you restart the server. I was only able to reproduce this by having a library that was empty, so we still need to identify how you are getting this when you have books already in your library.

**Comment by jezaldanluthar** [comment]
> I just realized you said you have that notification that spins forever. Is that also happening with 1 book?

Yes! Here is a 50 second video showing it. Maybe you're spotting something I am doing wrong! Fresh install of audiobookshelf, add a new "Test" Library with 1 Audiobook. Scan Library, wait for scan to finish, Match Books --> Get error and scanner freezes



https://github.com/advplyr/audiobookshelf/assets/47871184/52201d6d-f95b-435c-b250-bf5b0a201366

LOGS: 
![FcSyv9Q](https://github.com/advplyr/audiobookshelf/assets/47871184/198063ee-6fa4-4e38-bee4-c2542c64275a)

**Comment by advplyr** [comment]
This may be a permissions issue with the database. After you scan in that single book like you showed in your test video, if you then restart your server is the book still there?

**Comment by jezaldanluthar** [comment]
> This may be a permissions issue with the database. After you scan in that single book like you showed in your test video, if you then restart your server is the book still there?

Just tested it and yes, the book is still there after I restart the docker

**Comment by advplyr** [comment]
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
