### ISSUE TITLE
[Bug]: "Newest Episodes" section has disappeared as of 2.3.4

### ISSUE THREAD

**Issue by bootsofglory** [advplyr/audiobookshelf#2119]
### Describe the issue

Upon upgrading from 2.3.3, the "newest episodes" section of my podcast library has disappeared. Adding new episodes after upgrading does not fix the issue. 

### Steps to reproduce the issue

1. Upgrade to any version after 2.3.3
2. Newest episode section no longer appears on home view of podcast library

### Audiobookshelf version

2.3.4+

### How are you running audiobookshelf?

Docker

**Comment by jurgenhaas** [comment]
For me, not even new episodes are shoing there. Only when I go to the page with newest episodes, but no longer on the front page.

**Comment by advplyr** [comment]
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
