### ISSUE TITLE
[Bug]: Add ability to delete authors

### ISSUE THREAD

**Issue by oboe45** [advplyr/audiobookshelf#2124]
### Describe the issue

Updated to version 2.4.3. - I had previously noticed that, for example, the 5 Connie Willis books that I have were not all listed as being authored by her.  In Author drop downs, there are 5 separate drop down items for her, one shows :Doomsday Book, three show no books, one lists three other books of hers.  

I had expected to see a single Connie Willis in the Author drop down with all 5 books listed under here name in a similar fashion

### Steps to reproduce the issue

1.  Had noted an issue with Authors not listing their books correctly - seemed only to happen when new books were added
2. Read the update notes for v 2.4.3 - one of the fixes seemed relevant
3. Applied v2.4.3 and reviewed state of the database
4. Loks exacly as before

### Audiobookshelf version

v. 2.4.3

### How are you running audiobookshelf?

Docker

**Comment by oboe45** [comment]
Is there some DB clean up that needs to be applied, plus deletion and re-add of the books affected??  Since this seems to have been an insidious type of original error, how can I find any offending book/authors in a very large library (1500 books)

**Comment by oboe45** [comment]
Thanks, but the implication is that the authors name is mis-spelled.  It is not, every one of the duplicated entries in the drop down author table is identical and correct.  Some of the entries are associated with one or more books, some are associated with no books.  A better solution would be to delete all of the author entries, but I cannot see any way to do this.  Even if I delete each book, from the system and the database, and then reload them from the original source (Audible) I still get the same issues occurring - multiple author entries. some with books associated and some with no books.

**Comment by hobesman** [comment]
Sorry, I wasn't implying that they were misspelled. I was just saying that jumping through hoops of first intentionally misspelling them, and then renaming them again to the correct spelling, triggers the system to "realize" that it's the same author, and merges them.

The Dev also said he plans to add a "delete" button to the author details window on the next server release. But in the meantime I was just providing an option to clean up the mess made by the bug.

**Comment by oboe45** [comment]
Thanks for the update.  This is a truly excellent app, and the current
issue under discussion is a minor blip, a bit like a pimple on the nose -
it's hard to leave it alone, and it will be a relief when it is fixed!

Love to see the delete button, there are a few little glitches with the
Author list and even a fresh download doesnt always solve the problem.

**Comment by advplyr** [comment]
Added in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
