### ISSUE TITLE
[Bug]: Renaming my Library made me lose all matches / metadata.

### ISSUE THREAD

**Issue by xAhlen** [advplyr/audiobookshelf#2125]
### Describe the issue

I renamed my Library and after that all my matched books lost their meta data and fellback to the default data when I first imported them. So I had to go through and manually add them again and double check so that the narrator was correct. 
I have metadata / cover stored in the docker metadata, not with the book. 

### Steps to reproduce the issue

1. Rename Library. 
2. Lost all matches

### Audiobookshelf version

2.4.3

### How are you running audiobookshelf?

Docker

**Comment by xAhlen** [comment]
restored from backup. worked just fine. Can't reproduce again. Something I did make the metadata reset.

**Comment by advplyr** [comment]
I don't think renaming the library caused whatever you experienced. I tested just to be sure but it's just updating a column on in the libraries table of the db and doesn't affect anything else. I'm glad you got it resolved
