### ISSUE TITLE
[Bug] eBook file type indicator missing from book cover on home page and library page for newly added files on the web client

### ISSUE THREAD

**Issue by lwobniar** [advplyr/audiobookshelf#2126]
Issue: eBook file type indicator missing from book cover on home page and library page for newly added files on the web client

It appears that the display issue only applies to files added **after** the 2.4.x updates. The ebook file type indicator is still there for older files.

### Steps to reproduce

1. Add a new ebook to library, OR
2. Delete a previously added ebook and re-scan library

### Expected behaviour
- eBook file type (e.g. epub, pdf) should be displayed at the bottom left corner of the book cover when the mouse hovers over the book on the home page or library page.

![image](https://github.com/advplyr/audiobookshelf-app/assets/141289995/9ac4dee8-308a-4a58-a2b4-104e33ab4648)

### Actual behaviour
- Newly added books no longer show ebook file type at the bottom left corner.

![image](https://github.com/advplyr/audiobookshelf-app/assets/141289995/6884348f-8253-48de-8135-a255b549dcfe)

### Environment data

Audiobookshelf Version: v.2.4.3

**Comment by advplyr** [comment]
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
