### ISSUE TITLE
[Bug]: (Match tab) If Search Title or Author contain &, search query is incorrectly encoded

### ISSUE THREAD

**Issue by mikiher** [advplyr/audiobookshelf#2128]
### Describe the issue

In the match tab, when either Search Title or Author fields contain an ampersand character, the search query is incorrectly encoded, and an incorrect search url is sent to the server.

### Steps to reproduce the issue

1. Open Match tab for any book
2. Set Search Title to "a&b" and Author to ""
3. Click "Search"
Expected search URL: http://localhost:3333/api/search/books?provider=audible&fallbackTitleOnly=1&title=a%26b
Actual search URL: http://localhost:3333/api/search/books?provider=audible&fallbackTitleOnly=1&title=a&b

1. Open Match tab for any book
2. Set Search Title to "a" and Author to "b&c"
3. Click "Search"
Expected search URL: http://localhost:3333/api/search/books?provider=audible&fallbackTitleOnly=1&title=a&author=b%26c
Actual search URL: http://localhost:3333/api/search/books?provider=audible&fallbackTitleOnly=1&title=a&author=b&c

### Audiobookshelf version

v2.4.2

### How are you running audiobookshelf?

Built from source

**Comment by advplyr** [comment]
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
