### ISSUE TITLE
Add/Rescan Library with Match

### ISSUE THREAD

**Issue by itschrisonline** [advplyr/audiobookshelf#213]
Is it possible to rescan library and auto-match while selecting provider?

**Comment by itschrisonline** [comment]
and report failed/multiple matches

example comictagger using comicvine as provider

**Comment by itschrisonline** [comment]
Or even  just a auto match tab?

Sorry with all the suggestions

**Comment by advplyr** [comment]
This is not available yet, but is in the plans. Matching is still a manual one-by-one thing.

**Comment by advplyr** [comment]
This is possible now see #359
