### ISSUE TITLE
[Bug]: Recent Series on "Home" tab shows single book series despite library setting to "hide single book series"

### ISSUE THREAD

**Issue by r1aven** [advplyr/audiobookshelf#2134]
### Describe the issue

Recent Series on "Home" tab shows single book series despite library setting to "hide single book series."  The setting does work properly for content shown in the "Series" tab.  I assume this bug is also present in all versions between v2.4.0 through v2.4.3 but have only verified in v2.4.3.

Relevant setting in audiobooks library settings tab.
![image](https://github.com/advplyr/audiobookshelf/assets/6191252/134ae085-1c8a-481c-8175-a8e8599721ba)

Image on home tab showing that recent series shows series containing only one book
![image](https://github.com/advplyr/audiobookshelf/assets/6191252/62cece2f-78af-4165-8ade-41e9a5a66513)

Same server/library/content after rolling back the version to v2.3.3.  Shows proper operation of the setting.
![image](https://github.com/advplyr/audiobookshelf/assets/6191252/9e0015c9-cd6b-46b8-b410-909f52b4db00)

### Steps to reproduce the issue

1.   Nothing specific to the server instance other than the audiobookshelf version.

### Audiobookshelf version

v2.4.3

### How are you running audiobookshelf?

Docker

**Comment by neingeist** [comment]
I noticed the same problem.

**Comment by advplyr** [comment]
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
