### ISSUE TITLE
[Bug]: Filtered User is populated to Open Listening Sessions

### ISSUE THREAD

**Issue by Echelon101** [advplyr/audiobookshelf#2136]
### Describe the issue

![image](https://github.com/advplyr/audiobookshelf/assets/22678948/bbcf4f5e-3c0d-4df3-b4e6-3cba099a2907)
![image](https://github.com/advplyr/audiobookshelf/assets/22678948/057c3365-4bed-4e2d-906c-49bac19ab81e)

If I select a User to filter Listening Sessions all open Listening Sessions are displayed as the filtered user.

### Steps to reproduce the issue

1. Open \<audiobookshelfurl\>/config/sessions
2. Select a user in filter dropdown
3. look at Open Listening Sessions Table

### Audiobookshelf version

v2.4.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
