### ISSUE TITLE
[Bug]:The playback progress is out of sync.

### ISSUE THREAD

**Issue by zrwd01** [advplyr/audiobookshelf#2137]
### Describe the issue

Bro ,This is a very good project. My library has up to 600 books and 5T. The error that occurs now is that the playback progress is not synchronized.

### Steps to reproduce the issue

1. Normal use

### Audiobookshelf version

2.4.3

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Is this a new server install, or did you upgrade from a previous version?

What client are you using (web, Android, iOS)?

Are you streaming or listening to a downloaded book?

**Comment by zrwd01** [comment]
new server install, Android client , listening to a downloaded book,But my database is a bit large, 740 MB

**Comment by nichwall** [comment]
Where is it out of sync? Is it not syncing to the server?

Do you have any screenshots to show what you mean?

**Comment by zrwd01** [comment]
Chinese-voiced audio novels are always very large, each one is about 10Gb.

**Comment by zrwd01** [comment]
Yes, it is not synced to the server,

**Comment by zrwd01** [comment]
![image](https://github.com/advplyr/audiobookshelf/assets/33946060/4db8b46f-076f-4ec0-9751-658b5d0cf0d4)
![微信图片_20230923005713](https://github.com/advplyr/audiobookshelf/assets/33946060/f35dd660-e396-4429-8bbf-c8ff864b3c5f)
They were always in sync before, but now they are not in sync, and the time will not be synchronized the next time you listen to it.

**Comment by nichwall** [comment]
You have two sessions open (one in the app and one in the browser). Do you close the player when you're done listening?

In the Android player, look at the History in the upper right and check to see if the sync is happening. Also if you have any Debug server logs that would be useful

**Comment by zrwd01** [comment]
The purpose of opening two players is to observe the synchronization of playback time. They will be closed during normal use.

**Comment by zrwd01** [comment]
![微信图片_20230923011322](https://github.com/advplyr/audiobookshelf/assets/33946060/99085533-f5bd-4ad5-84e1-5914de603810)
![image](https://github.com/advplyr/audiobookshelf/assets/33946060/73ffd7e4-f444-430f-8e2a-3381d0f73bd1)
The server side has no log information since 17:12 yesterday.

**Comment by advplyr** [comment]
Are you still having this issue? The downloaded book needs to have been downloaded from the same server connection (ip address & user) as the one you are connecting to in the app.
If you have changed ip address or switched to a reverse proxy then the local download won't sync, it has to be re-downloaded.

**Comment by zrwd01** [comment]
I tried it, and it was indeed because I used a different server.

**Comment by zrwd01** [comment]
thanks

**Comment by advplyr** [comment]
Thanks for following up
