### ISSUE TITLE
[Bug]: Reverting to older RSS feed when updated RSS feed is accessed

### ISSUE THREAD

**Issue by JJGerace** [advplyr/audiobookshelf#2139]
### Describe the issue

I noticed that all of my podcast RSS feeds are reverting to the state when I first opened said RSS feed (so effectively, I can't use the feature to listen to any podcasts released after opening the RSS feed). ABS is properly downloading new episodes and adding an entry to the feed, but actually requesting the feed makes the feed revert.

I was able to reproduce this with a test podcast consistently (I used NPR News Now because it updates with a new episode every hour). Logs are below, I believe the entry (near the end) at 2023-09-23 14:20:53 "DEBUG [RssFeedManager] Updating RSS feed for item 521c2a39-d807-4704-b28d-3902997ce882 "NPR News Now" " may be the problematic behavior. 

[RSSfeedbug.txt](https://github.com/advplyr/audiobookshelf/files/12707063/RSSfeedbug.txt)

### Steps to reproduce the issue

1. Subscribe to a new podcast
2. Download most recent episode
3. Set recurring download. I set it to download at 20 after the hour (20 * * * *) 
4. Open a local RSS feed rebroadcasting the podcast
5. Open the RSS feed url in the browser, verify that it contains the one episode (correct behavior).
6. Wait for a new episode to be released, then wait for the next download period (see 3).
7. Open the RSS feed url in the browser again, verify that it now contains the entry for the new episode (correct behavior).
8. Open the RSS feed url in the browser a third time, now the feed only has one episode again (looks the same as in step 4).

### Audiobookshelf version

v2.4.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
