### ISSUE TITLE
Home/Library/Series content not visible on Android app. 

### ISSUE THREAD

**Issue by Helico-Pter** [advplyr/audiobookshelf#214]
Server - 1.63.1 (docker)
Client - 0.9.31-beta 

After installing latest server version the content on the home, library and series pages is not visible on the Android app but the content can still be found by searching. The collections tab is populated though.

**Comment by advplyr** [comment]
I just released an update to the server `v1.6.32` with the fix.
No need to update the app

**Comment by Helico-Pter** [comment]
> I just released an update to the server `v1.6.32` with the fix.
> No need to update the app

Excellent. Thank you.
