### ISSUE TITLE
[Enhancement]: Collapse sub-series showing JSON object

### ISSUE THREAD

**Issue by samszotkowski** [advplyr/audiobookshelf#2140]
### Describe the feature/enhancement

Currently when you have series collapsed in the library view, they all show the number of books inside in the top right, whether they're a subseries or a top-level series.  And hovering over with the cursor simply dims the image.
![image](https://github.com/advplyr/audiobookshelf/assets/94253934/adae2810-469b-43c8-820b-29127d08a462)

However, collapsing series in the series view shows the sub-series books' indices in the top-level series, and hovering over shows the first book's id and sequence number:
![image](https://github.com/advplyr/audiobookshelf/assets/94253934/0d1bd2f3-be62-4f0a-ad13-876e2dd4d556)

So right now it seems like sub-series are treated as regular series in the library view, and both as regular and as sub-series in the series view.

**Comment by samszotkowski** [comment]
I think if there was a separate metadata tag for sub- vs top-level series, as has been discussed in various other places (https://github.com/advplyr/audiobookshelf/issues/2092), some of these inconsistencies might be easier to solve.

**Comment by advplyr** [comment]
I fixed that bug with the collapse sub-series. The difficulty with collapsing series is the sql queries. I think what you are requesting is covered by #2092 and this issue will be for fixing that bug.

**Comment by advplyr** [comment]
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
