### ISSUE TITLE
[Bug]: Cant update podcast episode limit

### ISSUE THREAD

**Issue by truthsword** [advplyr/audiobookshelf#2143]
### Describe the issue

I need to change podcast update limit. When I re-enter a new value, there is no "save" option on the Episodes tab.
![](https://i.imgur.com/hQIBojy.png)

Running latest 2.4.3 on docker

### Steps to reproduce the issue

1. Edit episodes limit 3>10 or 3>0. No Save button appears. If I switch tabs and come back to Episodes tab, the original value (ex., 3) remains.

### Audiobookshelf version

2.4.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
That setting is not meant to be saved. That is a one time check & download. You may be looking for the settings in the podcast schedule tab
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/23b0adcb-9d99-4544-a01b-d0549bb323e7)

**Comment by advplyr** [comment]
It was originally temporary before auto downloads were setup but then people liked it because it allowed them to bulk download based on a timestamp, so I kept it in.
