### ISSUE TITLE
[Enhancement]: Nested library structure

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf#2148]
### Describe the feature/enhancement

Having a flat structure for the library poses challenges for various organizational schemes.  There is already a [req. open](https://github.com/advplyr/audiobookshelf/issues/1568) to do something with podcasts, but I would like to be able to nest libraries.  One use case would be large collections of stuff.  I'd like to have a collections library and then have different collections, e.g., blinkist, the great courses, the modern scholar, business-related audiobook collection...  But having some sort of library hierarchy as opposed to a flat structure would allow for more customization for the organization of personal libraries.

**Comment by advplyr** [comment]
I may not be understanding what you mean. A flat structure is not recommended but is supported. The supported directory structures are in the docs https://www.audiobookshelf.org/docs#book-directory-structure
