### ISSUE TITLE
[Feature Request] Date Added (to the library) is taken from folder modification date

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#215]
I understand that the date added is taken as the date ABS scans and adds the book to the library. But it would be nice to have a setting that allows this order to be taken from folder modification dates, especially when a new library is created.

I make my to-read/listen list based on the latest books I have added into my audibook folder, but because of the existing method, I can't really (or easily) know which books I uploaded recently (and hence wanted to read them next).

Cheers.

**Comment by advplyr** [comment]
[v1.7.1]() now supports sorting by file creation time and modified file time for the audiobook folder.

![image](https://user-images.githubusercontent.com/67830747/155910668-eabcc10d-52da-4b23-bf0c-e6e78d6f0258.png)
