### ISSUE TITLE
[Enhancement]: Make the library folder path editable

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf#2150]
### Describe the feature/enhancement

Presently, once you enter the path and then navigate away from the page for any reason, e.g., to hit F12 and go into guake to check/copy the path name, the field is locked and can only be deleted and re-entered.  It happened to me yesterday that I left off the terminal ')' character and there is no way to edit it.

**Comment by advplyr** [comment]
Updated in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
