### ISSUE TITLE
[Bug]: Doesn't install on IPv6 only server

### ISSUE THREAD

**Issue by glor** [advplyr/audiobookshelf#2151]
### Describe the issue

I ran into this issue on an ubuntu 22.04 server that has only IPv6 configured:
```
Preparing to unpack .../audiobookshelf_2.4.3_amd64.deb ...
Existing config found.
METADATA_PATH=/usr/share/audiobookshelf/metadata
CONFIG_PATH=/usr/share/audiobookshelf/config
FFMPEG_PATH=/usr/lib/audiobookshelf-ffmpeg/ffmpeg
FFPROBE_PATH=/usr/lib/audiobookshelf-ffmpeg/ffprobe
TONE_PATH=/usr/lib/audiobookshelf-ffmpeg/tone
PORT=13378
HOST=0.0.0.0
Starting FFMPEG Install
--2023-09-27 20:11:18--  https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
Resolving johnvansickle.com (johnvansickle.com)... 107.180.57.212
Connecting to johnvansickle.com (johnvansickle.com)|107.180.57.212|:443... failed: Network is unreachable.
dpkg: error processing archive /var/cache/apt/archives/audiobookshelf_2.4.3_amd64.deb (--unpack):
 new audiobookshelf package pre-installation script subprocess returned error exit status 4
Errors were encountered while processing:
 /var/cache/apt/archives/audiobookshelf_2.4.3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
It seems like johnvansickle.com only has IPv4 configured. Works after adding an IPv4 address.
Edit: Seems like the provider does not configure IPv4 gateways by default.

### Steps to reproduce the issue

1.  install deb packages on a server with only IPv6

### Audiobookshelf version

2.4.3

### How are you running audiobookshelf?

Debian/PPA

**Comment by DieselTech** [comment]
The server that FFMPEG uses to host the files does not have have a ipv6 address. Your server can't reach the FFPMEG server so the install stops. You need to setup a 6to4 tunnel so you can reach the regular v4 internet space.

**Comment by glor** [comment]
Please do feel free to close the issue if you don't think it's important enough :)

**Comment by advplyr** [comment]
Abs now gets the ffmpeg binaries from github
