### ISSUE TITLE
[Bug]: In one of my libraries, I am unable to create series. 

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf#2158]
### Describe the issue

Select an item or items and either edit or batch edit, respectively, click the add series plus symbol, type in series name and [optional] enter its order.  Then press Submit.  I expect that it will proceed to record the series, close the dialog box (in the case of single edit), and allow me to save the file(s).  What happens is that the text for the series name (and sequence if adding) is displayed properly in the dialog box along with the series name dropdown (which functions).  After pressing Submit, nothing happens and the website is frozen.  Clicking on the top-right X doesn't do anything, Esc doesn't, clicking off the dialog box doesn't...  The only thing left is either F5 or closing the tab and starting again.

Incidentally, it will not let me pick a series name from the dropdown.

### Steps to reproduce the issue

1. Try to create a series name and watch it not work on just one of my libraries.
2. You're almost assuredly going to need to try this on my machine to see that it is happening.  Figuring out why will then be another matter.

### Audiobookshelf version

v2.4.3

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Can you check the console logs in the browser to see what error you are getting?

**Comment by iconoclasthero** [comment]
DEBUG

[Scan] "7da0785c-9941-4505-8d2a-2c3b877de3c1": Library item "Campbell, Joseph/The Eastern Way, Vol. 02 (1997)" key "mtime" changed from "1695937301323" to "1695937326879"

2023-09-28 17:42:15

DEBUG

[Scan] "7da0785c-9941-4505-8d2a-2c3b877de3c1": Library item "Campbell, Joseph/The Eastern Way, Vol. 02 (1997)" key "ctime" changed from "1695937301323" to "1695937326879"

2023-09-28 17:42:15

DEBUG

[Scan] "7da0785c-9941-4505-8d2a-2c3b877de3c1": Library file "/library/books/opus/Campbell, Joseph/The Eastern Way, Vol. 02 (1997)/The Eastern Way -- Cover 01.jpg" was removed from library item "Campbell, Joseph/The Eastern Way, Vol. 02 (1997)"

2023-09-28 17:42:15

DEBUG

[Scan] "7da0785c-9941-4505-8d2a-2c3b877de3c1": Library item "Campbell, Joseph/The Eastern Way, Vol. 02 (1997)" changed: [mtime,ctime,libraryFiles,size,lastScan]

2023-09-28 17:42:16

DEBUG

[Scan] "7da0785c-9941-4505-8d2a-2c3b877de3c1": Found metadata file "/library/books/opus/Campbell, Joseph/The Eastern Way, Vol. 02 (1997)/metadata.json" - preferring

2023-09-28 17:42:16

DEBUG

[Scan] "7da0785c-9941-4505-8d2a-2c3b877de3c1": Success saving abmetadata to "/library/books/opus/Campbell, Joseph/The Eastern Way, Vol. 02 (1997)/metadata.json"

2023-09-28 17:42:16

DEBUG

[LibraryScanner] Folder update for relative path "Campbell, Joseph/The Eastern Way, Vol. 05 (1997)" is in library item "The Eastern Way, Vol. 05 (1997)" - scan for updates

2023-09-28 17:42:16

DEBUG

[Scan] "ea3376ea-53b0-46bd-b50d-a1c83f8bbc2f": Library item "Campbell, Joseph/The Eastern Way, Vol. 05 (1997)" key "mtime" changed from "1695937301583" to "1695937326879"

2023-09-28 17:42:16

DEBUG

[Scan] "ea3376ea-53b0-46bd-b50d-a1c83f8bbc2f": Library item "Campbell, Joseph/The Eastern Way, Vol. 05 (1997)" key "ctime" changed from "1695937301583" to "1695937326879"

2023-09-28 17:42:16

DEBUG

[Scan] "ea3376ea-53b0-46bd-b50d-a1c83f8bbc2f": Library file "/library/books/opus/Campbell, Joseph/The Eastern Way, Vol. 05 (1997)/The Eastern Way -- Cover 01.jpg" was removed from library item "Campbell, Joseph/The Eastern Way, Vol. 05 (1997)"

2023-09-28 17:42:16

DEBUG

[Scan] "ea3376ea-53b0-46bd-b50d-a1c83f8bbc2f": Library item "Campbell, Joseph/The Eastern Way, Vol. 05 (1997)" changed: [mtime,ctime,libraryFiles,size,lastScan]

2023-09-28 17:42:16

DEBUG

[Scan] "ea3376ea-53b0-46bd-b50d-a1c83f8bbc2f": Found metadata file "/library/books/opus/Campbell, Joseph/The Eastern Way, Vol. 05 (1997)/metadata.json" - preferring

2023-09-28 17:42:17

DEBUG

[Scan] "ea3376ea-53b0-46bd-b50d-a1c83f8bbc2f": Success saving abmetadata to "/library/books/opus/Campbell, Joseph/The Eastern Way, Vol. 05 (1997)/metadata.json"

2023-09-28 17:42:17

DEBUG

[LibraryScanner] Folder scan results [object Object]

2023-09-28 17:56:06

INFO

[SocketAuthority] Socket Connected gFcZHGn7A6PMaZUaAAAV

2023-09-28 17:56:06

DEBUG

[SocketAuthority] User Online $USER

2023-09-28 18:01:52

DEBUG

[SocketAuthority] User Offline $USER

2023-09-28 18:01:52

INFO

[SocketAuthority] Socket gFcZHGn7A6PMaZUaAAAV disconnected from client "$USER" after 346007ms (Reason: ping timeout)

2023-09-28 18:32:30

DEBUG

[SocketAuthority] User Offline $USER

2023-09-28 18:32:30

INFO

[SocketAuthority] Socket ueCNn9siDETKNi_MAAAR disconnected from client "$USER" after 9336555ms (Reason: transport close)

2023-09-28 18:32:31

DEBUG

Loaded filterdata in 0.31s

2023-09-28 18:32:32

INFO

[SocketAuthority] Socket Connected sgjgEr2lJPLZxWK-AAAX

2023-09-28 18:32:32

DEBUG

[SocketAuthority] User Online $USER

2023-09-28 18:32:32

DEBUG

Loaded 100 of 2175 items for libary page in 0.41s

**Comment by advplyr** [comment]
The browser console logs you would find in the browser. Using Ctrl+Shift+i

The error you would want to share would be in red and would likely occur when you open up the dropdown or open the series modal.

**Comment by iconoclasthero** [comment]
![Screenshot from 2023-09-28 18-39-30](https://github.com/advplyr/audiobookshelf/assets/535962/5c5b4582-eba5-4564-93eb-9f4302dadb40)

**Comment by iconoclasthero** [comment]
What I can do is create or select a series if I start typing something in but do **not** hit space.   So whatever is happening in that field is happening _after_ I hit space.  I could work around this for now editing the sqlite table on the back end.

I should note that this library has its own unique directories but also has directories that are libraries in their own right.  Could this have any implications?

.
_|-- GCMS_
|-- **audiobooks**
|-- collections
   ..    _|-- Blinks_
   ..    _**|-- Business-Related Audiobook Collection**_   
_|-- comedy
|-- meditation_
**|-- mp3**
_**|-- new**_
**|-- opus**


**bold**=only in "Audiobook Library"
_italic_=library not included in "Audiobook Library"
_**bold-italic**_=Is a stand-alone library that is included in "Audiobook Library", i.e., "New Audiobooks" and "Business-Related Audiobooks"

**Comment by iconoclasthero** [comment]
Ok, so I updated the server to 2.4.4 and it is working in the normal edit process, i.e., if I'm editing a book singly, I can create or select a series name.  

When in batch-edit mode, I can do the same thing as above in  the individual series fields for elements of the batch selection.  What I still cannot do, and it still freezes the window is use the mapping details box.

**Comment by advplyr** [comment]
I'm confused now about what steps you are taking to get that error you showed. Can you give a list of steps I can do to reproduce this?

**Comment by iconoclasthero** [comment]
"When in batch-edit mode, I can do the same thing as above in the individual series fields for elements of the batch selection. What I still cannot do, and it still freezes the window is use the map details box regardless of the length, existing label, spaces in the [typed] entry, etc."

So if I go into batch edit and then hit the dropdown f/map details and then check on the series field and then start typing the browser window freezes and I got that error in 2.4.4.
