### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [advplyr/audiobookshelf#2159]
### Describe the issue

Github Security Lab has found some potential vulnerabilities in audiobookshelf.  Please enable [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) under the security tab so that we can privately report these issues. Thank you.

### Steps to reproduce the issue

1. 

### Audiobookshelf version

v2.4.3

### How are you running audiobookshelf?

Built from source

**Comment by advplyr** [comment]
Thanks, I wasn't aware of that. It is enabled now.
