### ISSUE TITLE
[Enhancement] Better blur for fill of ebook covers in 1:1 covers

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf#216]
I made it for you, you can use it or not. I have edited someone else work, as my skills are low.  I really love your work! So it's just a suggestion maybe someone else will have better idea.  Main idea is to set background image with the same height of top image so they match.

Version 1: 
https://codepen.io/superpawko/pen/WNZvqYa

Version 2:
https://codepen.io/superpawko/pen/vYeOoJj

**Comment by advplyr** [comment]
I put together some samples and some of them look better to me using the current version, and some of them look better using the increased blur. I think we need some more opinions on this, I could go either way.

![image](https://user-images.githubusercontent.com/67830747/144680776-e240358f-227f-4293-af66-46a0fda0cf75.png)
![image](https://user-images.githubusercontent.com/67830747/144680793-1f6dea75-7a49-4470-881f-36f6a5db8250.png)
![image](https://user-images.githubusercontent.com/67830747/144680830-d1e66b23-ddf5-43df-a549-4cd89e3a94e2.png)
![image](https://user-images.githubusercontent.com/67830747/144680854-0833aac5-eb65-4346-ba8e-8977abc506ff.png)

**Comment by superpawko** [comment]
I think 2nd option with more blur looks better, you can more focus on the cover. Of course most people will use one covers or another so this is only escape method.  Thank you for you hard work! I took this idea from IRFANVIEW. 
Inmo in some iteration maybe it is good idea to add title and author to the Book grid view. Because it sometimes hard to know the tile based on image only. I have for example:  Seasons of stories from Storytel which have the same audiobookcover.

**Comment by advplyr** [comment]
That makes sense, it does make the cover stand out more. Do you have suggestions on how to include the title and author on the book grid?

**Comment by superpawko** [comment]
Not yet,  I will try prototype something for you and show best solutions , tommorrow or sunday. There are many options to consider. And there is no pefect solution. I will do some reasearch and show you what I know. So you can focus more time on develepoment.

For me the top priority where you should invest your time is chapter view in android app.  (smart audiobook player) use the easiest trick by adding another timeline for chapter. I'm currently listening to 38 hour book, and it is impossible to navigate. 

Thank you for you time.

**Comment by advplyr** [comment]
I included the updated cover blur in `v1.6.34`

**Comment by advplyr** [comment]
Thanks for helping with designs. You can open up a discussion with those when you are ready, I'm going to close this one.
