### ISSUE TITLE
[Bug] Local playback sessions from the mobile app are not showing in daily stats chart

### ISSUE THREAD

**Issue by Drudoo** [advplyr/audiobookshelf#2168]
My server is not always on. With high electricity prices i turn on my server when needed. Most of my listening is therefore done offline using the iOS app. 

I have noticed that my listening stats aren't updated when the server comes online. Progress is synced fine but my Recent Sessions doesn't show the offline sessions I've had. 

### Steps to reproduce

1. Download a book to the app on iOS
2. Turn off the server
3. Listen to the book
4. Turn on the server
5. Stats are not appearing 

### Expected behaviour
- When the server comes online again, i would expect listening stats to be send from the app to the server

### Actual behaviour
- No stats (just position) is send to the server

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [ x] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version:
16.4.1 (a) 

iPhone model:
13 Pro

Audiobookshelf app version:
0.9.63-beta

Audiobookshelf server version
2.2.19

**Comment by advplyr** [comment]
This will be fixed in the next server release

**Comment by RingoRohe** [comment]
Yeah! Great.
Thanks for your work. :)

**Comment by advplyr** [comment]
Fixed in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)
