### ISSUE TITLE
[Enhancement]: Option to include subtitles in dis[play

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf#2169]
### Describe the feature/enhancement

Whereas subtitles often offer a *significant* amount of information about a particular title about a book at a glance, it would be helpful if this could be turned on both in a thumbed display and [hopefully] in a future list display.

Additionally, including the publication date about a particular book tends to offer a lot of information about a book.  (This would be more useful if the publication date was an expanded field where more than one publication date could be entered and/or a first published date was an additional field).

**Comment by advplyr** [comment]
Subtitle was added https://github.com/advplyr/audiobookshelf/pull/3117
