### ISSUE TITLE
[Bug] Buttons on series page not working

### ISSUE THREAD

**Issue by igorkaldowski** [advplyr/audiobookshelf#217]
When I click on the series buttons on the series page they don't work. They do work on the homepage. I think its a issue with the url.

Here is the url of a series on the series page:
http://192.168.23.72:13378/library/main/bookshelf/series?series=VGhlIFVud3JpdHRlbiBXb3JkcyBTZXJpZXM%3D

Here is the url for the same series on the homepage:
http://192.168.23.72:13378/library/main/series/VGhlIFVud3JpdHRlbiBXb3JkcyBTZXJpZXM=

**Comment by advplyr** [comment]
Thanks, missed that somehow. Fixed in `v1.6.34`
