### ISSUE TITLE
[Enhancement]: Add azw3 support for the abs reader

### ISSUE THREAD

**Issue by Elekam** [advplyr/audiobookshelf#2170]
### Describe the feature/enhancement

Add support for azw3 files for the reader of abs.

It would be a great addition, but I do not know how feasible this really is.
It would be great if a dev could chime in.

Currently the reader behaves like this when a azw3 file is read: [Github issue](https://github.com/advplyr/audiobookshelf/issues/2058)

**Comment by advplyr** [comment]
This is not going to be supported as explained in https://github.com/advplyr/audiobookshelf/issues/2058#issuecomment-1743385331

Perhaps in the future if it becomes a container for epubs instead of mobi
