### ISSUE TITLE
[Bug]: Using M4B generation tool results in a much bigger file than original files combined

### ISSUE THREAD

**Issue by ReaderGuy42** [advplyr/audiobookshelf#2172]
### Describe the issue

The original six files of an audiobook have about 700 MB and after turning it into a M4B with ABS's M4B tool it had about 1.4 GB. 

This has also happened with another book.

I've just updated to the newest version but that actually made the M4B file even bigger, now it's 1.9 GB?

### Steps to reproduce the issue

1. Choose book
2. select M4B generation tool
3. wait
4. see it's a bigger file.

### Audiobookshelf version

2.4.4

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
It could be due to the default bitrate being changed from 64k to 128k (or whatever the exact number was), but otherwise I don't have any ideas either

**Comment by advplyr** [comment]
Yeah that's a good point. That would make sense as to why the size increased
