### ISSUE TITLE
[Bug]: Socket failed to connect

### ISSUE THREAD

**Issue by mbaggott** [advplyr/audiobookshelf#2193]
### Describe the issue

QNAP qpkg version 2.4.4.0 x86_64
Accessing via http locally
Fresh install

Was able to install, create user, select media folder, scan for files.
Then on going to the library to view audibooks get a repeated socket failed to connect error.
This is what is showing in the browser dev window:

![image](https://github.com/advplyr/audiobookshelf/assets/5018715/9ffb619d-c11d-42e8-ba90-6a0d484c25b0)

Tried restarting the service, same error on going back in to library.

### Steps to reproduce the issue

1. Install QNAP package
2. Create a user and login
3. Add a media folder
4. Scan library
5. Attempt to view library via web interface on http

### Audiobookshelf version

2.4.4.0x86_64 from QNAP store

### How are you running audiobookshelf?

Other

**Comment by advplyr** [comment]
The QNAP package isn't maintained by anyone associated with this project. Abs needs to be able to establish a socket connection so I think you should raise this issue with the QNAP package maintainer

**Comment by advplyr** [comment]
Also, feel free to join the discord or matrix server. Someone may be able to help you there

**Comment by mbaggott** [comment]
Ok thank you.

**Comment by mbaggott** [comment]
For any other QNAP user who comes across this bug, just install with Container Station, very easy to set up and works without issue

**Comment by y2ksw** [comment]
I had this issue on a Plesk server and not in local. So I went manually to the /var/www/vhosts/system folder to the respective domain and edited the docker entry on nginx.conf with the following additions (see **ADD THIS**). That solved it.

```
        #extension docker begin
        location ~ ^/.* {
                proxy_pass http://0.0.0.0:13378;
                proxy_set_header Host              $host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                # ADD THIS:
                proxy_set_header Upgrade            $http_upgrade;
                proxy_set_header Connection         "upgrade";
                proxy_http_version                  1.1;
                proxy_redirect                      http:// https://;
        }

        #extension docker end
```
