### ISSUE TITLE
CSS issue with version in bottom left corner of screen when book open

### ISSUE THREAD

**Issue by mbaggott** [advplyr/audiobookshelf#2195]
### Describe the issue

When a book is open, the version in the bottom left menu gets pushed up over the Narrators button, then further up if you make the window shorter.

Suggestion: either make it stay in position and be covered by the play bar, or give it a solid background color so it is fully visible and not obscured by the underlying buttons

Screen resolution: 3840 x 2160
Scale: 250%

![image](https://github.com/advplyr/audiobookshelf/assets/5018715/565070c2-8c8b-43b4-8d95-ffed57939a4c)

![image](https://github.com/advplyr/audiobookshelf/assets/5018715/e2a0fb9d-70c0-40c1-9679-53d620c5ed49)

### Steps to reproduce the issue

1. Read a book and vertically resize window to make it shorter

### Audiobookshelf version

2.4.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)
