### ISSUE TITLE
Enhancement: Requesting support for chapters

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#22]
I have most of my audiobooks built as .m4b with chapter support (built with: https://github.com/yermak/AudioBookConverter).

Is it possible to add chapter support to the playback of the audiobooks?

I first noticed this was missing when I tried the download feature that combines all related tracks into one file (which totally works, BTW!). It seems related, and just in case it is, would it be possible to maintain chapters when combining tracks into one file? That would be really cool too.

What do you think?

Either way, THANK YOU for building this! AS-IS this is exactly what I was hoping to find. I wanted something that could easily serve my audiobook collection to family and friends that wouldn't require anything technical on their end, and this TOTALLY delivers! So, thank you.

**Comment by advplyr** [comment]
I've been looking into this because I thought it would be useful to be able to look at and skip to chapters from the audiobook player. I think this is an important feature, and for the downloader to merge audio files into an m4b with chapters shouldn't be a problem.

Some audiobooks have multiple introductions or even interludes between chapters. In these cases I think it will be useful to add a field in the track editor where you can name the chapter yourself.

By default they would be named:

> Chapter 1
> Chatper 2
> etc..

But you may want to name them like

> Preface
> Introduction
> Chapter 1
> etc..

Great suggestion! I'm thrilled that this is providing value for you.

**Comment by advplyr** [comment]
The first version chapter support is live in v1.1.1

When the audiobook is scanned it attempts to get chapters from the file. If no chapters are found and the audiobook is has multiple tracks then chapters will be created using the tracks.

If an audiobook has chapters you can jump to each chapter from the player. This chapters icon will be show:

![image](https://user-images.githubusercontent.com/67830747/132526489-c6bd6ba8-01bd-41d0-96f3-6ed79ae27a6d.png)

As for your original request, the downloader has been changed to instead generate M4B audiofiles with embedded cover art, metadata, and chapters.

As of v1.1.0 updated files and new files are automatically scanned. So you could trigger a scan by renaming an audio file, or you could remove the audiobook and press scan. This will generate the chapters.

**Comment by Kudjo-Grand** [comment]
Tried to test this, but while the new chapter icon was present, it wouldn't allow me to click it. I tried multiple books and multiple browsers with no luck.

Please advise.

**Comment by advplyr** [comment]
The icon becomes clickable only if there are chapters. If you open the edit modal there is a chapters tab now, you can also view them there.
You need to update the audiobook files or remove the audiobook and press scan to have the chapters get set. Chapters are set during the scan.

**Comment by advplyr** [comment]
If you have a lot of details you don't want to lose, just rename 1 file in the directory and it will auto-scan again since it detected an update.

**Comment by Kudjo-Grand** [comment]
Okay. I'll try that and report back.

**Comment by Kudjo-Grand** [comment]
Looks like the chapter logic might need a little tweak.

I have multiple books in the "Mistborn Series" 'Book'. (I had it organized this way before I found your application and will consider changing it later).

However, the chapters detected are each entire book, instead of the chapters for EACH book file.
![image](https://user-images.githubusercontent.com/25695143/132600773-ba63745f-c9e8-4d2a-bce8-30d20718ecd1.png)

**Comment by advplyr** [comment]
The chapter scanner originally only used embedded chapters if the audiobook consisted of a single file. For multi-files it used the start of each file as a chapter.
I updated it to use embedded chapters if they are found and fallback to using the file start time as a chapter.

If you re-scan that audiobook and check the chapters tab, it should show the correct chapters now.
