### ISSUE TITLE
Bug/Enhancement? Sort by Series

### ISSUE THREAD

**Issue by itschrisonline** [advplyr/audiobookshelf#220]
Heya,

Just trying to sort by series on library page, There is no option.
On the Series page there is no sort options and seems to be in reverse

CHeers

**Comment by advplyr** [comment]
I noticed this yesterday also, the series covers are not getting sorted properly.

**Comment by advplyr** [comment]
This is fixed in `v1.6.37`. Covers will show in order of volume # if it is set.
