### ISSUE TITLE
[Bug]: Genres and Tags are case-sensitive when they should be case-insensitive and also not be able to be duplicates

### ISSUE THREAD

**Issue by Uroth** [advplyr/audiobookshelf#2206]
### Describe the issue

I noticed that when I clicked on the genre **Science fiction** on one of my books it only then returned 7 results.
![image](https://github.com/advplyr/audiobookshelf/assets/11475365/47ccb203-386d-4d4c-bb2a-c82a42d14dd8)
![image](https://github.com/advplyr/audiobookshelf/assets/11475365/ba69bda5-9921-4ef2-acc8-7146cadea319)
But I knew I had more books with that genre. So I went and looked up a book that should have been on the list, then I saw that book had the genre but it was with capital S and F and not a small f  **Science Fiction** 
![image](https://github.com/advplyr/audiobookshelf/assets/11475365/1ae93260-3661-41db-b6d7-25b5b3c161cf)
When I then click on this genre I get the result I was expecting.
![image](https://github.com/advplyr/audiobookshelf/assets/11475365/e0f1e76b-79a3-4df2-9d03-f0350e485be5)

So we have an issue with case sensitive genres and tags.

I also noticed that I could add the same genre and tag twice using lower and uppercase spelling.
![image](https://github.com/advplyr/audiobookshelf/assets/11475365/9b348d50-f2b4-490b-a59b-7a4ac45ea2de)
Here I have Fantasy and fantasy and both return different results when clicked.

Maybe a fix from https://github.com/advplyr/audiobookshelf/issues/1198  to not allow the same genre and tag be entered twice?

### Steps to reproduce the issue

1. Click on genres or tags with different combinations of lower and upper case spelling and the results will be different.

### Audiobookshelf version

2.4.4

### How are you running audiobookshelf?

Docker

**Comment by mikiher** [comment]
@advplyr this is now fiixed for a long time, now also supporting non-ascii case-insensitivity. Let's close?
