### ISSUE TITLE
[Bug]: Old streams are not cleaned up on server initialization

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#2209]
### Describe the issue

HLS streams created in `/metadata/streams` should be automatically cleaned up on server initialization. Since changing to using UUIDv4 in server v2.3.x the function is broken.

### Steps to reproduce the issue

1. 

### Audiobookshelf version

v2.4.4

### How are you running audiobookshelf?

Docker

**Comment by MidnightShake** [comment]
My docker is also experiencing this situation and has taken up a lot of storage space.Hope to release updates in a timely manner. Thank you

**Comment by nichwall** [comment]
> My docker is also experiencing this situation and has taken up a lot of storage space.Hope to release updates in a timely manner. Thank you

If you need it now, this is already fixed in the `edge` tag on Docker. This tag includes everything up to the latest commit on GH, but you will likely encounter other bugs due to features or bug fixes still being worked on.

The `latest` tag is the latest release.

**Comment by MidnightShake** [comment]
Effective results have been achieved. Thank you very much to the developer, as I am not sure if manual cleaning will have an unknown effect on the original data, so I dare not manually delete it. Thank you again

**Comment by advplyr** [comment]
Fixed in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)
