### ISSUE TITLE
[Bug]: RSS feed not updating with new episodes

### ISSUE THREAD

**Issue by mchill** [advplyr/audiobookshelf#2212]
### Describe the issue

Looks like a regression of #1435. The only additional note I can add is that I noticed the new episode shows up in the RSS feed for a few seconds, and then disappears. The only way to make it stay is to close and reopen the feed.

### Steps to reproduce the issue

1. Add a new podcast
2. Remove latest episode (but don't delete the file)
3. Open the RSS feed
4. Re-scan the podcast to get the latest episode back
5. Check the RSS feed and see that the new episode isn't there

### Audiobookshelf version

v2.4.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This was fixed in v2.4.4 https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4
