### ISSUE TITLE
[Bug]: Audiobook file management tools translate texts...

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#2217]
### Describe the issue

In the audiobook file management tools there are still some texts that are not yet translatable...

![grafik](https://github.com/advplyr/audiobookshelf/assets/40667862/f790c67e-282e-4b9f-be42-e7a35e4c07b8)

### Steps to reproduce the issue

1. Go to the audiobook file management tools and see for yourself ;)

### Audiobookshelf version

2.3.3

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
The tone text in the top left is going to be removed once tone is removed

**Comment by Hallo951** [comment]
Ok, but I can't find the rest of the texts in the language file to be able to translate them. They would have to be made available there...

**Comment by Hallo951** [comment]
Here is another text that has not yet been translated...

![grafik](https://github.com/advplyr/audiobookshelf/assets/40667862/5410db83-60a6-4b24-bc95-9df8dace517c)

The window appears when you select several audio books, then click on the 3 dots at the top right and select the option "Quick Embed Metadata". The option "Quick Embed Metadata" itself is also not yet translatable.

**Comment by advplyr** [comment]
I believe all these are added now but let me know
