### ISSUE TITLE
[Bug]: No line breaks in the author view

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#2218]
### Describe the issue

In the author view, the line breaks are not taken over correctly.

Input text
![grafik](https://github.com/advplyr/audiobookshelf/assets/40667862/62b1cfca-a1fe-4f62-b780-7c30002d03fd)

Result
![grafik](https://github.com/advplyr/audiobookshelf/assets/40667862/70cf0f7a-b5d5-46d8-90fc-3e9fa5ea4f87)

### Steps to reproduce the issue

1. Enter text and save...

### Audiobookshelf version

2.3.3

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Fixed in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)
