### ISSUE TITLE
[Bug]: Using a Comma in a Series name now separates the series into multiple different ones around the comma

### ISSUE THREAD

**Issue by Khameleon05** [advplyr/audiobookshelf#2219]
### Describe the issue

When using a comma in a series name it separates the series into two separate ones (each side of the comma). This is relatively new because I have a couple hundred Warhammer: 40,000 books (and add more every update) but any new ones I try to tag separate into "Warhammer 40" and "000". I also tested this with a "20,000" series and it also does "20" and "000.

### Steps to reproduce the issue

1. Add a series with a comma in it and then rescan the library, it'll constantly repeat the split no matter how many times you remove the wrong ones and readd what you're trying to use.

### Audiobookshelf version

v2.4.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Make sure you have this dropdown set to .json
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/c0f832c8-414d-4e67-852a-e06b0731a448)

.abs was replaced but if you installed the server before that happened then your server stayed on .abs. The default is now .json and fixed this issue.

If that is not your issue let me know

**Comment by Khameleon05** [comment]
Yes I've had it installed for about a year and using abs the entire time, that did fix it thanks.
