### ISSUE TITLE
Batch edit failure.

### ISSUE THREAD

**Issue by Helico-Pter** [advplyr/audiobookshelf#222]
Hi. I've been having a mixed experience with batch edits.

Select audiobooks > add tag or genre (pressing enter on each one) > Save > 'Failed to batch update'.

Server 1.6.36 (Docker Compose) but has been happening well before this update.

Tried locally and through nginx proxy. Individual edits work perfectly. 

**Logs**

2021-12-06 09:18:01
DEBUG
[DB] Inserted 1 session
2021-12-06 09:18:01
DEBUG
[DB] Updated user: 1
2021-12-06 09:18:01
INFO
[STREAM-CHECK] Check Files 7402 of 11256 65.76% Furthest Segment: 7401
2021-12-06 09:18:03
INFO
[STREAM-CHECK] Check Files 8158 of 11256 72.48% Furthest Segment: 8157
2021-12-06 09:18:05
INFO
[STREAM-CHECK] Check Files 8903 of 11256 79.10% Furthest Segment: 8902
2021-12-06 09:18:07
INFO
[STREAM-CHECK] Check Files 9606 of 11256 85.34% Furthest Segment: 9605
2021-12-06 09:18:09
INFO
[STREAM-CHECK] Check Files 10302 of 11256 91.52% Furthest Segment: 10301
2021-12-06 09:18:11
INFO
[STREAM-CHECK] Check Files 10959 of 11256 97.36% Furthest Segment: 10958
2021-12-06 09:18:12
INFO
[FFMPEG] Transcoding ended
2021-12-06 09:19:07
DEBUG
Set Log Level to DEBUG
2021-12-06 09:19:07
DEBUG
[DB] Updated settings: 1

Then I updated 2 completely different audiobooks and it worked fine

**Logs**

2021-12-06 09:24:50
DEBUG
[DB] Updated user: 1
2021-12-06 09:25:41
INFO
[ApiController] 2 Audiobooks have updates
2021-12-06 09:25:41
DEBUG
[DB] Audiobook updated 1
2021-12-06 09:25:41
DEBUG
[DB] Audiobook updated 1

**Comment by advplyr** [comment]
This is fixed in `v1.6.37`
