### ISSUE TITLE
[Bug]: Files don't disappear after converting in m4b

### ISSUE THREAD

**Issue by Mavarius1989** [advplyr/audiobookshelf#2220]
### Describe the issue

I converted an audiobook from mp3 into m4b. After completion there is only a m4b file (and other files like metadata...) but no mp3-files in the folder, but in audiobookshelf, when you click on an audiobook -> Audiofiles: There are mp3 leftovers, that i cannot delete (failed to delete - [LibraryItemController] Library file "210175074" does not exist for library item). They are not listed under "all files". Scanning does not help.

### Steps to reproduce the issue

1. Converted audiobook in audiibookshelf into m4b. (not always, just sometimes there are leftovers)

### Audiobookshelf version

2.4.4

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Are they removed on a re-scan?

**Comment by Mavarius1989** [comment]
Unfortunately, no. Did a partial scan on the library, and nothing was changed. No error in the log

**Comment by advplyr** [comment]
Press edit on the book and use the Rescan in the modal

**Comment by Mavarius1989** [comment]
"item was up to date". Nothing in the log.

**Comment by Mavarius1989** [comment]
Did that. The *.txt was added afetr re-scanning, but the mp3s persist.

**Comment by advplyr** [comment]
Are you still having this issue on v2.5.0? I think this is resolved on a re-scan.
