### ISSUE TITLE
[Bug]: unable to open RSS feed from Series/Collections

### ISSUE THREAD

**Issue by cobra88king8** [advplyr/audiobookshelf#2223]
### Describe the issue

Whenever I try "open RSS feed" and input the URL into my browser, I get a simple page that says "Not Found". 

### Steps to reproduce the issue

1. I have created multiple collections of audiobooks, both with MP3 and M4B filetypes as well as tried several different series, the problem persists. 

### Audiobookshelf version

v2.4.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not able to reproduce this. Can you check the server logs? Also, share the simple page that says "Not Found".

**Comment by cobra88king8** [comment]
Sure
![Screenshot 2023-10-17 182019](https://github.com/advplyr/audiobookshelf/assets/8955137/ef9c6619-a49b-401b-a717-89c04a1f0833)

Docker Log: 

audiobookshelf  | Config /config /metadata
audiobookshelf  | [2023-10-17 16:37:57] INFO: === Starting Server ===
audiobookshelf  | [2023-10-17 16:37:57] INFO: [Server] Init v2.4.4
audiobookshelf  | [2023-10-17 16:37:57] INFO: [Database] absdatabase.sqlite not found at /config/absdatabase.sqlite
audiobookshelf  | [2023-10-17 16:37:57] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf  | [2023-10-17 16:37:57] INFO: [Database] Db connection was successful
audiobookshelf  | [2023-10-17 16:37:58] INFO: [Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting
audiobookshelf  | [2023-10-17 16:37:58] INFO: [Database] Server upgrade detected from null to 2.4.4
audiobookshelf  | [2023-10-17 16:37:58] INFO: [BackupManager] 0 Backups Found
audiobookshelf  | [2023-10-17 16:37:58] INFO: [BackupManager] Auto Backups are disabled
audiobookshelf  | [2023-10-17 16:37:58] INFO: [LogManager] Init current daily log filename: 2023-10-17.txt
audiobookshelf  | [2023-10-17 16:37:58] INFO: Listening on port :80
audiobookshelf  | [2023-10-17 16:38:00] INFO: [SocketAuthority] Socket Connected 8SGALowdqaej-dPoAAAB
audiobookshelf  | [2023-10-17 16:38:00] ERROR: JWT Verify Token Failed JsonWebTokenError: invalid signature
audiobookshelf  |     at /server/libs/jsonwebtoken/verify.js:133:19
audiobookshelf  |     at getSecret (/server/libs/jsonwebtoken/verify.js:90:14)
audiobookshelf  |     at Object.module.exports [as verify] (/server/libs/jsonwebtoken/verify.js:94:10)
audiobookshelf  |     at /server/Auth.js:97:11
audiobookshelf  |     at new Promise (<anonymous>)
audiobookshelf  |     at Auth.verifyToken (/server/Auth.js:96:12)
audiobookshelf  |     at Auth.authenticateUser (/server/Auth.js:92:17)
audiobookshelf  |     at SocketAuthority.authenticateSocket (/server/SocketAuthority.js:150:41)
audiobookshelf  |     at Socket.<anonymous> (/server/SocketAuthority.js:95:41)
audiobookshelf  |     at Socket.emit (node:events:513:28) (Auth.js:99)
audiobookshelf  | [2023-10-17 16:38:00] ERROR: Cannot validate socket - invalid token (SocketAuthority.js:152)
audiobookshelf  | [2023-10-17 16:38:11] ERROR: JWT Verify Token Failed JsonWebTokenError: invalid signature
audiobookshelf  |     at /server/libs/jsonwebtoken/verify.js:133:19
audiobookshelf  |     at getSecret (/server/libs/jsonwebtoken/verify.js:90:14)
audiobookshelf  |     at Object.module.exports [as verify] (/server/libs/jsonwebtoken/verify.js:94:10)
audiobookshelf  |     at /server/Auth.js:97:11
audiobookshelf  |     at new Promise (<anonymous>)
audiobookshelf  |     at Auth.verifyToken (/server/Auth.js:96:12)
audiobookshelf  |     at Auth.authMiddleware (/server/Auth.js:61:29)
audiobookshelf  |     at Server.authMiddleware (/server/Server.js:84:15)
audiobookshelf  |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
audiobookshelf  |     at trim_prefix (/node_modules/express/lib/router/index.js:328:13) (Auth.js:99)
audiobookshelf  | [2023-10-17 16:38:11] ERROR: Verify Token User Not Found eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZWU5YjU5Yy03MWQxLTQ3ZGUtODQzMC01OWY2ZjI3YjUyZmEiLCJ1c2VybmFtZSI6ImpsaXR3aW5rYSIsImlhdCI6MTY5NzU2MDEwOH0.KPyViBTvwTcyxQHYLFumyAi1GgcIJJZQXUg-vbO1Aec (Auth.js:63)
audiobookshelf  | [2023-10-17 16:38:58] INFO: [Server] Initializing new server
audiobookshelf  | [2023-10-17 16:39:04] INFO: [Auth] jlitwinka logged in from 192.168.0.1
audiobookshelf  | [2023-10-17 16:39:05] INFO: [SocketAuthority] Socket Connected Cmd1R3jzaD1eLWnoAAAD
audiobookshelf  | [2023-10-17 16:39:45] INFO: [Watcher] Initializing watcher for "Audiobooks".
audiobookshelf  | [2023-10-17 16:40:09] INFO: [Watcher] Initializing watcher for "Podcasts".
audiobookshelf  | [2023-10-17 16:40:09] INFO: [Watcher] "Podcasts" Ready
audiobookshelf  | [2023-10-17 16:40:13] INFO: [Scanner] Starting library scan e9b40b2f-5590-42ad-b4b1-c77edfbe4a3d for Audiobooks
audiobookshelf  | [2023-10-17 16:40:19] INFO: [Watcher] "Audiobooks" Ready
audiobookshelf  | [2023-10-17 16:45:50] INFO: [Server] Requesting rss feed cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983
audiobookshelf  | [2023-10-17 16:45:50] WARN: [RssFeedManager] Feed not found cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983 (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 16:47:26] INFO: [Scanner] Library scan e9b40b2f-5590-42ad-b4b1-c77edfbe4a3d completed in 7:13.0 | 303 Added | 0 Updated | 0 Missing
audiobookshelf  | [2023-10-17 16:47:26] INFO: [LibraryScan] Scan log saved "/metadata/logs/scans/2023-10-17_e9b40b2f-5590-42ad-b4b1-c77edfbe4a3d.txt"
audiobookshelf  | [2023-10-17 16:47:26] INFO: [LibraryController] Scan complete
audiobookshelf  | [2023-10-17 16:51:53] INFO: [CoverManager] Downloaded libraryItem cover "/metadata/items/87a48373-26cb-4f58-9958-63418e6c7fb3/cover.jpg" from url "https://books.google.com/books/content?id=i1_1QAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api" for "Ptolemy's Gate"
audiobookshelf  | [2023-10-17 16:52:07] INFO: [CoverManager] Downloaded libraryItem cover "/metadata/items/712a9906-5112-4a5d-936d-07ceaf4c3f91/cover.jpg" from url "https://books.google.com/books/content?id=j_quYgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api" for "The Ring of Solomon"
audiobookshelf  | [2023-10-17 16:52:17] INFO: [CoverManager] Downloaded libraryItem cover "/metadata/items/6f687ed6-48b5-41c0-bbb8-43cf33989708/cover.jpg" from url "https://books.google.com/books/content?id=6Q2y2FpaWKMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api" for "The Golem's Eye"
audiobookshelf  | [2023-10-17 16:52:36] INFO: [CoverManager] Downloaded libraryItem cover "/metadata/items/2d12e2fb-9948-4766-aa42-9eb1c3249b1e/cover.jpg" from url "https://books.google.com/books/content?id=akK_Ox-1cUIC&printsec=frontcover&img=1&zoom=1&source=gbs_api" for "The Amulet of Samarkand"
audiobookshelf  | [2023-10-17 16:52:38] INFO: [SocketAuthority] Socket Cmd1R3jzaD1eLWnoAAAD disconnected from client "jlitwinka" after 813470ms (Reason: transport close)
audiobookshelf  | [2023-10-17 16:52:39] INFO: [SocketAuthority] Socket Connected hUS9hT83BynFNnwiAAAF
audiobookshelf  | [2023-10-17 16:53:01] INFO: [CoverManager] Downloaded libraryItem cover "/metadata/items/3a262b2e-8a62-4297-b3e7-c34d457517b6/cover.jpg" from url "https://books.google.com/books/content?id=EI9gQPw29aYC&printsec=frontcover&img=1&zoom=1&source=gbs_api" for "Eragon"
audiobookshelf  | [2023-10-17 16:53:13] INFO: [CoverManager] Downloaded libraryItem cover "/metadata/items/fe5a507a-d163-47d3-a398-f6194d3dd2b7/cover.jpg" from url "https://books.google.com/books/content?id=vn1YsvmmEaoC&printsec=frontcover&img=1&zoom=1&source=gbs_api" for "Eldest"
audiobookshelf  | [2023-10-17 16:53:22] INFO: [CoverManager] Downloaded libraryItem cover "/metadata/items/08052ed2-ea39-45d6-8d54-5b1dcf4f777f/cover.jpg" from url "https://books.google.com/books/content?id=EZqODQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api" for "Brisingr"
audiobookshelf  | [2023-10-17 16:53:33] INFO: [CoverManager] Downloaded libraryItem cover "/metadata/items/17fd9f59-95bc-4e8f-82bb-42267e3ae3d0/cover.jpg" from url "https://books.google.com/books/content?id=NNsoed6bmNMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api" for "Inheritance"
audiobookshelf  | [2023-10-17 16:53:41] INFO: [CoverManager] Downloaded libraryItem cover "/metadata/items/46f2bbb5-d27d-4089-a105-43f6d95519ef/cover.jpg" from url "https://books.google.com/books/content?id=wCRyDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api" for "The Fork, the Witch, and the Worm"
audiobookshelf  | [2023-10-17 16:53:43] INFO: [SocketAuthority] Socket hUS9hT83BynFNnwiAAAF disconnected from client "jlitwinka" after 64129ms (Reason: transport close)
audiobookshelf  | [2023-10-17 16:53:45] INFO: [SocketAuthority] Socket Connected OtB2TMCaLTlNJQNdAAAH
audiobookshelf  | [2023-10-17 16:54:46] INFO: [Server] Requesting rss feed cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983
audiobookshelf  | [2023-10-17 16:54:46] WARN: [RssFeedManager] Feed not found cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983 (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 17:08:03] INFO: [Server] Requesting rss feed cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983
audiobookshelf  | [2023-10-17 17:08:03] WARN: [RssFeedManager] Feed not found cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983 (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 17:09:45] ERROR: JWT Verify Token Failed JsonWebTokenError: invalid signature
audiobookshelf  |     at /server/libs/jsonwebtoken/verify.js:133:19
audiobookshelf  |     at getSecret (/server/libs/jsonwebtoken/verify.js:90:14)
audiobookshelf  |     at Object.module.exports [as verify] (/server/libs/jsonwebtoken/verify.js:94:10)
audiobookshelf  |     at /server/Auth.js:97:11
audiobookshelf  |     at new Promise (<anonymous>)
audiobookshelf  |     at Auth.verifyToken (/server/Auth.js:96:12)
audiobookshelf  |     at Auth.authMiddleware (/server/Auth.js:61:29)
audiobookshelf  |     at Server.authMiddleware (/server/Server.js:84:15)
audiobookshelf  |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
audiobookshelf  |     at trim_prefix (/node_modules/express/lib/router/index.js:328:13) (Auth.js:99)
audiobookshelf  | [2023-10-17 17:09:45] ERROR: Verify Token User Not Found eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZWU5YjU5Yy03MWQxLTQ3ZGUtODQzMC01OWY2ZjI3YjUyZmEiLCJ1c2VybmFtZSI6ImpsaXR3aW5rYSIsImlhdCI6MTY5NzU2MDEwOH0.KPyViBTvwTcyxQHYLFumyAi1GgcIJJZQXUg-vbO1Aec (Auth.js:63)
audiobookshelf  | [2023-10-17 17:09:46] INFO: [Auth] jlitwinka logged in from ::ffff:192.168.0.1
audiobookshelf  | [2023-10-17 17:09:47] INFO: [SocketAuthority] Socket Connected UGGwUolayjF2UiRGAAAJ
audiobookshelf  | [2023-10-17 17:09:59] INFO: [Server] Requesting rss feed cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983
audiobookshelf  | [2023-10-17 17:09:59] WARN: [RssFeedManager] Feed not found cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983 (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 17:10:31] WARN: [Auth] Failed login attempt 1 of 10 from 192.168.0.1 (Auth.js:163)
audiobookshelf  | [2023-10-17 17:10:33] WARN: [Auth] Failed login attempt 2 of 10 from 192.168.0.1 (Auth.js:163)
audiobookshelf  | [2023-10-17 17:10:40] INFO: [Auth] jlitwinka logged in from 192.168.0.1
audiobookshelf  | [2023-10-17 17:10:40] INFO: [SocketAuthority] Socket Connected 1R3BOjf7cHRnI_reAAAL
audiobookshelf  | [2023-10-17 17:10:54] INFO: [Server] Requesting rss feed cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983
audiobookshelf  | [2023-10-17 17:10:54] WARN: [RssFeedManager] Feed not found cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983 (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 17:10:57] INFO: [Server] Requesting rss feed cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983
audiobookshelf  | [2023-10-17 17:10:57] WARN: [RssFeedManager] Feed not found cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983 (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 17:11:19] INFO: [Server] Requesting rss feed d749e568-c214-47f9-b1ea-e3a6ed6d20be
audiobookshelf  | [2023-10-17 17:11:19] WARN: [RssFeedManager] Feed not found d749e568-c214-47f9-b1ea-e3a6ed6d20be (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 17:12:45] INFO: [Server] Requesting rss feed cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983
audiobookshelf  | [2023-10-17 17:12:45] WARN: [RssFeedManager] Feed not found cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983 (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 17:12:50] INFO: [RssFeedManager] Fetched all feeds
audiobookshelf  | [2023-10-17 17:12:53] INFO: [SocketAuthority] Socket OtB2TMCaLTlNJQNdAAAH disconnected from client "jlitwinka" after 1148529ms (Reason: transport close)
audiobookshelf  | [2023-10-17 17:12:54] INFO: [RssFeedManager] Fetched all feeds
audiobookshelf  | [2023-10-17 17:12:54] INFO: [SocketAuthority] Socket Connected Dc6ChLx3rQSqfOsMAAAN
audiobookshelf  | [2023-10-17 17:15:26] INFO: [RssFeedManager] Fetched all feeds
audiobookshelf  | [2023-10-17 17:16:33] INFO: [Server] Requesting rss feed 2ca14c68-b07d-464a-9642-139b78981a4c
audiobookshelf  | [2023-10-17 17:16:33] WARN: [RssFeedManager] Feed not found 2ca14c68-b07d-464a-9642-139b78981a4c (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 17:16:39] INFO: [Server] Requesting rss feed 2ca14c68-b07d-464a-9642-139b78981a4c
audiobookshelf  | [2023-10-17 17:16:39] WARN: [RssFeedManager] Feed not found 2ca14c68-b07d-464a-9642-139b78981a4c (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 17:17:01] INFO: [Server] Requesting rss feed cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983
audiobookshelf  | [2023-10-17 17:17:01] WARN: [RssFeedManager] Feed not found cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983 (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 17:27:32] INFO: [RssFeedManager] Fetched all feeds
audiobookshelf  | [2023-10-17 17:29:35] INFO: [Scanner] Starting library scan 20062752-0fc2-4852-b08d-35cdc7835740 for Audiobooks
audiobookshelf  | [2023-10-17 17:31:12] INFO: [Scanner] Library scan 20062752-0fc2-4852-b08d-35cdc7835740 completed in 1:37.0 | 0 Added | 0 Updated | 0 Missing
audiobookshelf  | [2023-10-17 17:31:12] INFO: [LibraryController] Scan complete
audiobookshelf  | [2023-10-17 17:48:38] INFO: [SocketAuthority] Socket Dc6ChLx3rQSqfOsMAAAN disconnected from client "jlitwinka" after 2143981ms (Reason: transport close)
audiobookshelf  | [2023-10-17 17:48:39] INFO: [SocketAuthority] Socket Connected YPu2WCEnFaPbkJ4SAAAP
audiobookshelf  | [2023-10-17 17:48:53] INFO: [Server] Requesting rss feed cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983
audiobookshelf  | [2023-10-17 17:48:53] WARN: [RssFeedManager] Feed not found cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983 (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 17:49:42] INFO: [Scanner] Starting library scan 73ee3930-0ac8-4e07-a68b-f21843955345 for Audiobooks
audiobookshelf  | [2023-10-17 17:51:18] INFO: [Scanner] Library scan 73ee3930-0ac8-4e07-a68b-f21843955345 completed in 1:35.0 | 0 Added | 0 Updated | 0 Missing
audiobookshelf  | [2023-10-17 17:51:18] INFO: [LibraryController] Scan complete
audiobookshelf  | [2023-10-17 20:38:41] INFO: [SocketAuthority] Socket YPu2WCEnFaPbkJ4SAAAP disconnected from client "jlitwinka" after 10201201ms (Reason: transport close)
audiobookshelf  | [2023-10-17 22:10:45] INFO: [SocketAuthority] Socket Connected LpCdMWYb3uAWMFF8AAAR
audiobookshelf  | [2023-10-17 22:10:52] INFO: [RssFeedManager] Fetched all feeds
audiobookshelf  | [2023-10-17 22:16:15] INFO: [SocketAuthority] Socket Connected 0lxfkgxRoKn7ki7XAAAT
audiobookshelf  | [2023-10-17 22:16:27] INFO: [SocketAuthority] Socket 0lxfkgxRoKn7ki7XAAAT disconnected from client "jlitwinka" after 11773ms (Reason: transport close)
audiobookshelf  | [2023-10-17 22:16:27] INFO: [Server] Requesting rss feed cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983
audiobookshelf  | [2023-10-17 22:16:27] WARN: [RssFeedManager] Feed not found cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983 (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 22:19:02] INFO: [SocketAuthority] Socket UGGwUolayjF2UiRGAAAJ disconnected from client "jlitwinka" after 18554954ms (Reason: transport close)
audiobookshelf  | [2023-10-17 22:19:02] INFO: [Server] Requesting rss feed cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983
audiobookshelf  | [2023-10-17 22:19:02] WARN: [RssFeedManager] Feed not found cc1e7fa9-9288-4ab8-a100-6c0e6e2b4983 (RssFeedManager.js:83)
audiobookshelf  | [2023-10-17 22:19:50] INFO: [SocketAuthority] Unauth socket 8SGALowdqaej-dPoAAAB disconnected (Reason: transport close)

**Comment by advplyr** [comment]
Can you share the screenshot of the open RSS feed? Like this
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/cac78e47-38dc-400e-95dc-02ce29d3e70f)
