### ISSUE TITLE
[Enhancement]: Cover Search using Google Images

### ISSUE THREAD

**Issue by dedors** [advplyr/audiobookshelf#2235]
### Describe the feature/enhancement

For searching covers, it would be nice to also just use google image search (and maybe other search engines?), as they can yield results when other methods fail.
_Alternatively or additionally, consider allowing users to provide a URL for the cover image instead of requiring them to download and upload it.._

This probably should not be included in "match books" nor in "search all" (using google books is also excluded at the moment)

**Comment by advplyr** [comment]
You can already provide a URL for the cover image. It will be downloaded from the URL.

As far as I know the google image search API is not free up to a certain point and requires an API key, so this isn't a viable option. We need public APIs to use for providers

**Comment by dedors** [comment]
Oh I thought the "Cover Image URL" is only for the local file, without the ability download it.

**Comment by advplyr** [comment]
This will be more clear in the next release, I have updated the UI
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/831c937f-8bfb-4a6b-a544-6ee328991094)
