### ISSUE TITLE
Sort Book Match Results by closest to length

### ISSUE THREAD

**Issue by PulsarFTW** [advplyr/audiobookshelf#2238]
The new book length on the match page is excellent. A potention suggestion for improvement: Once a list of results has been found for a book, rather than the default ordering from the provider, organise them from closest to book length to biggest difference.

**Comment by mikiher** [comment]
I will pick this one. 

I think it's best to implement this on the server. It requires some changes in the search API so it also accepts the libraryItemId as a parameter.

**Comment by advplyr** [comment]
Added in [v2.7.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.0)
