### ISSUE TITLE
Audible search API seems broken

### ISSUE THREAD

**Issue by keaganhilliard** [advplyr/audiobookshelf#225]
Not sure if they turned it off but all searches return 0 results for me at the moment. I'm going to make a PR that allows pasting in an ASIN to match for now.

Is anyone else having this issue?

**Comment by ChiefMedicalOfficer** [comment]
Working for me.

Any additional characters within the author or title fields?

**Comment by keaganhilliard** [comment]
Even the android app can't search at the moment... So I'm assuming they are having an outage of some kind.

**Comment by keaganhilliard** [comment]
#226 Should at least give an option to search Audible for the correct ASIN and paste it into the title field.

**Comment by advplyr** [comment]
ASIN search is released in `v1.6.38`, thanks for adding that.
Let's leave this issue open until the API is functional again to prevent duplicates.

**Comment by itschrisonline** [comment]
It currently seems like it is pulling data from Open Library when you select Audible at the moment

**Comment by advplyr** [comment]
Oops yeah I see what happened. Thanks

**Comment by keaganhilliard** [comment]
The API appears to be fully functional again.

**Comment by advplyr** [comment]
I just released a patch `v1.6.39` to fix the match
