### ISSUE TITLE
Authors on user accounts

### ISSUE THREAD

**Issue by burnshroom** [advplyr/audiobookshelf#2250]
### Steps to reproduce

1. Add user.
2. During setup, deselect "Can Access All Tags"
3. Select applicable tags under "Tags Accessible to User"
4. Login to new account and select "Authors"
5. The new user sees all authors within the library instead of only the ones they have access to.

### Expected behaviour
- Ideally the user would only see the author(s) for which they have books included in their profile based on the tags they have access to.
### Actual behaviour
- User sees all authors whether they have access to them or not.

### Environment data

Audiobookshelf Version: 2.4.4: edge

**Comment by advplyr** [comment]
Fixed in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)
