### ISSUE TITLE
[Enhancement]: Option to exclude finished podcast episodes from RSS feeds

### ISSUE THREAD

**Issue by rudism** [advplyr/audiobookshelf#2251]
### Describe the feature/enhancement

My use case is I listen to podcast episodes on a device with very limited podcast functionality--it can list episodes from an RSS feed and download or stream them, but doesn't keep track of and hide episodes that have already been played. What I'd like to be able to do is mark episodes as read in Audiobookshelf and have those episodes no longer appear in the RSS feed. I think I can kind of achieve this already as long as I fully delete the episode from Audiobookshelf, but I want the ability to remove an episode from the RSS feed while still keeping the original media file in Audiobookshelf (because I'm a shameless data hoarder).

Perhaps something along the lines of a toggle when opening the RSS feed that says "Exclude finished episodes from feed."

**Comment by nichwall** [comment]
Is the device able to run the ABS app? Are you manually logging in on another device to mark the episodes as finished?

This would need user-specific RSS feeds to be implemented.

**Comment by rudism** [comment]
I log in with my computer to mark the episodes as finished after I've listened to them. The device is a Lightphone 2 (which is Android-based but with a custom shell and unable to run a web browser or any other apps). I realized after I posted that the finished state of podcast episodes is user-specific, which would complicate things since the RSS feeds don't really know which user is fetching them.

I think for now I'll probably just delete the episodes from ABS entirely for listening purposes, and use a separate solution to archive the podcasts that I care about keeping for posterity.

**Comment by nichwall** [comment]
Another option may be to create two libraries, one where you keep all episodes, and the other where you delete them after listening. You would need to be careful that you're deleting from the correct library.

You could also add episodes to a collection, open the RSS for that collection, and remove episodes from that collection after listening. That's better than the two libraries since you're not deleting files or having duplicate files.

**Comment by advplyr** [comment]
Another solution for this in the future is the feature we have been calling "filters" for podcast. The idea is a dynamic playlist that auto populates based on criteria, so you could have a filter that is unfinished episodes for a specific podcast.
https://github.com/advplyr/audiobookshelf/issues/1477
