### ISSUE TITLE
[Enhancement]: Direct download for supplemental ebooks

### ISSUE THREAD

**Issue by kanine** [advplyr/audiobookshelf#2259]
### Describe the feature/enhancement

It would be great if it was possible to have a direct download option when epubs etc are stored alongside the audiobook. At the moment the only option appears to be using the internal reader when the ebook is stored together with the audiobook.

Having a direct download would then allow devices IOS / Android / PC etc to handle the download and take into their favourite ereader like Play Books, Appple Books etc in an almost seamless manner.

**Comment by advplyr** [comment]
You can already download any individual file in the web client. Also, downloading the entire book will download all files in a zip.
If this what you are asking or am I missing something?

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/1fdc9ef2-dd8e-49a5-90c3-5f628fe93224)

**Comment by kanine** [comment]
Sorry I must have missed that when looking through the interface. Thanks for the response.
