### ISSUE TITLE
[Enhancement]: Support case insensitive search for non-ASCII characters

### ISSUE THREAD

**Issue by 000al000** [advplyr/audiobookshelf#2260]
### Describe the issue

![image](https://github.com/advplyr/audiobookshelf/assets/59219537/96ee3d22-3b4e-4a0c-aaa7-155a96be5dae)
not found

but
![image](https://github.com/advplyr/audiobookshelf/assets/59219537/68784168-5769-4089-9dcf-c12dc82f658c)

### Steps to reproduce the issue

1.  search without first capital letter
2. search with first capital letter

### Audiobookshelf version

2.5.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Non-ascii characters are case sensitive until we can figure out how to get sqlite to support it.

Mentioned it the other day https://github.com/advplyr/audiobookshelf/issues/2187

**Comment by mikiher** [comment]
@advplyr I believe we can close this now as fixed.

**Comment by 000al000** [comment]
Thanks, working!
