### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Polly-Jeanius** [advplyr/audiobookshelf#2267]
### Describe the issue

Since upgrading to 2.5.0 (Docker image) I can no longer add an author image via file path, it only accepts a URL. Is there a way to still add an image by file path, or is this a bug? 

I store author profile pics in the `/metadata/authors` folder. 

Authors that had a locally hosting image I had added previously by file path prior to upgrading are still working, but there doesn't seem to be a way to add any new ones. 

I have tried putting a local path (as I would in the previous version) in the URL field but it rejects it as an invalid URL. 

<img width="1547" alt="Screenshot 2023-10-31 at 9 26 22 pm" src="https://github.com/advplyr/audiobookshelf/assets/67853900/75007d66-bc5a-4c34-901c-d8a797333f37">

### Steps to reproduce the issue

1. Go to 'Authors' in Audiobookshelf lefthand tab
2. Click on the pencil on an author
3. Only a URL field exists where previously there was a field that accepted local path or URL. 

### Audiobookshelf version

2.5.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fyi you could enter the local filepath directly in the sqlite db if you need this now.
