### ISSUE TITLE
[Enhancement]: Allow rescanning of audio files to fix incorrect chapter length

### ISSUE THREAD

**Issue by Timtam** [advplyr/audiobookshelf#2269]
### Describe the feature/enhancement

I'm still searching and tagging my almost 6000 books large library right now, but I already noticed that i've got some books where ABS (or probably FFMPEG) just detected an incorrect length, almost doubling the length displayed for the audio book. The actual MP3 is 20 minutes in length, whereas ABS detected it to be a few hours long. I thus tried to find a quick way to rescan and try to fix this error, but there doesn't seem to be a way to rescan specific books to try and fix those mistakes. Could we get a tool for that, maybe within the tools section of the audio book entry edit screen or something?

**Comment by nichwall** [comment]
Are you sure the metadata for the file is correct? That sounds like the metadata is reporting the wrong length of the file.

**Comment by Timtam** [comment]
I don't know, that might very well be true. I thought FFMPEG would kinda scan the file and see how long it is by scanning the audio data, I don't know what tag needs to be defined to indicate its actual length.

**Comment by nichwall** [comment]
Ffmpeg does technically scan the audio file, but it only scans the metadata for the file unless it is encoding or something like that.

Also to answer your original question, you can rescan a specific book on the book edit page in the Details tab (next to the "Quick Match" button at the bottom)

**Comment by advplyr** [comment]
@nichwall Is correct here. The audio file may be poorly encoded. The duration that FFMPEG/FFPROBE gets from the audio file is not necessarily the actual duration if it is poorly encoded.
There is nothing we can do about that so if you can check if that is the issue we can close this.

**Comment by Timtam** [comment]
Great, thats good to know, thanks. Yep, I missed the rescan button there, so that does it for me, thanks.
