### ISSUE TITLE
[BUG] Resume Progress not working on IOS

### ISSUE THREAD

**Issue by Subdarub** [advplyr/audiobookshelf#227]
Let me preface this with a huge thank you for developing this piece of software. Ive been on a long journey trying to find an audiobook solution that works on both PC and Mobile and this one seems to be it.

Unfortunatetly i ran into an issue, that resuming where you left of does not work in IOS Browsers, it does work on Android (Firefox) tho.

IOS Version: 15.1.1
Browser: Firefox, Safari, Chrome
Reverse Proxy: Traefik
Audio Book format: Mp3 and M4b

I assume this is once again some form of Apple not adhering to standards.
I am happy to assist with any form of debugging.

**Comment by advplyr** [comment]
When you open the web app on ios does it show the current progress at all?
Are you able to play audiobooks?
Are you running v1.6.39?
The progress sync depends on the web socket connection, but so does the audio player.

**Comment by Subdarub** [comment]
>When you open the web app on ios does it show the current progress at all? 

It does not, its always at "0"

>Are you able to play audiobooks? 

Yes

> Are you running v1.6.39? 

Yes

> The progress sync depends on the web socket connection, but so does the audio player.

Progress sync does work on Android and on my PC. I tried debugging the with the safari web inspector, but the only thing i found was a warning message:

`HLS Player fallback, falling back to audio element.`

**Comment by SephirothMarasov** [comment]
i have this same problem, wanted to let you know so its not just a fluke occurence. Basically the same as op it shows the progress % correctly across all devices but as soon as i hit play on ios it goes back to 0.00 or sometimes 1min20 weirdly. tried a few different browsers and they all do the same. I have kept up to date with the updates and its installed via docker, ubuntu, local network only.

**Comment by advplyr** [comment]
This should be fixed in `v1.6.43`

**Comment by Subdarub** [comment]
> This should be fixed in `v1.6.43`

I tested your fix, unfortunately it still doesnt set the progress on ios for me.
I am on the newest version `INFO: [Server] Init v1.6.43`

Tested on Safari IOS and Chrome IOS, including closing the tabs several times and restarting the docker container.

**Comment by advplyr** [comment]
Just pushed `v1.6.44`, I think I got it now.
In testing on ios I also noticed a bunch of other little UI annoyances that I resolved.

**Comment by Subdarub** [comment]
> Just pushed `v1.6.44`, I think I got it now. In testing on ios I also noticed a bunch of other little UI annoyances that I resolved.

Absolute legend, it is infact working now tested on Safari IOS.
