### ISSUE TITLE
[Bug]: Collection view shows ebook duration in seconds

### ISSUE THREAD

**Issue by vincentscode** [advplyr/audiobookshelf#2278]
### Describe the issue

The collection view shows a duration in seconds for ebooks which doesn't really make sense as it's always just 0, since ebooks don't have a duration.
It would be better to show the read percentage (or no value at all).

![image](https://github.com/advplyr/audiobookshelf/assets/26576880/da803fb4-fcfb-498a-a41d-b0edd310a59c)

### Steps to reproduce the issue

1. Add ebook to collection
2. View collection

### Audiobookshelf version

v2.5.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.6.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.6.0)
