### ISSUE TITLE
[Bug]: PDF Reader is flickering

### ISSUE THREAD

**Issue by vincentscode** [advplyr/audiobookshelf#2279]
### Describe the issue

The PDF reader flickers on each page change, which makes using it rather uncomfortable.
The page number also flickers and the green loading bar is rather distracting.

![chrome_snkqSByONM](https://github.com/advplyr/audiobookshelf/assets/26576880/b46bf73f-27aa-4945-836f-59847d062c0e)

This does not seem necessary since the page is rendered, then white, then rendered again.
Is the first render lower resolution? Would it be possible to not render a white "frame" in between (and remove the loading bar) to make it less jaring?

### Steps to reproduce the issue

1. Open a PDF ebook
2. Flip through pages

### Audiobookshelf version

v2.5.0

### How are you running audiobookshelf?

Docker

**Comment by vincentscode** [comment]
This might be entirely due to the PDF Viewer Library used which appears to be rather unmaintained.
Perhaps switching to something like https://github.com/TaTo30/VuePDF might resolve the issue.

**Comment by advplyr** [comment]
Thanks, the codebase isn't using Vue3 yet

**Comment by vincentscode** [comment]
I see, makes sense. For Vue 2 https://www.npmjs.com/package/pdfvuer looks rather compelling and has a similar programming interface to what is currently used, though a feature to only show a single page at a time does not seem available.

**Comment by vincentscode** [comment]
After testing it out for a bit, it seems like pdfvuer would basically be a drop-in replacement without any of the issues. I can create a pull request, however my CSS / styling knowledge is quite limited, so somebody else might need to have a look at that afterwards.

**Comment by DownloadableFox** [comment]
What's the current status on this issue? I am experimenting this bug a lot myself.

Would love to contribute for this issue to be fixed ❤️

**Comment by vincentscode** [comment]
The linked PR is functional. Feel free to test it out and improve upon it, if you notice something that could be better!

**Comment by kabaga** [comment]
I am on 2.8.1 installed on Debian 12. Mine doesn't flicker, but after a few pages, the page turned dark and the turn pages become unresponsive.

**Comment by advplyr** [comment]
The flickering is fixed now so I don't think the other PDF reader library is necessary at this time.

**Comment by vincentscode** [comment]
Sounds good to me. The landscape of Vue 2 PDF libraries is rather abandoned as a whole unfortunately.

**Comment by advplyr** [comment]
Fixed in [v2.11.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.11.0)
