### ISSUE TITLE
[Feature request] Cross library search functionality

### ISSUE THREAD

**Issue by juriroemer** [advplyr/audiobookshelf#228]
I think having search look across all libraries that the user has permissions for would be a great. Maybe with a small indicator as to in which library the book was found, or UI shelves per library that has a match (see mockup screenshot)

![image](https://user-images.githubusercontent.com/31971585/145217681-1759ff07-5e27-4a6e-87c0-1eff99dccfbf.png)

**Comment by advplyr** [comment]
One issue with this design is the search page has a shelf for matching series, authors and tags. Was planning on adding a shelf for collections now that they are here.
How would cross-library search work when showing matches on series/collections/etc?
