### ISSUE TITLE
[Bug]: language String for number of books on authors page

### ISSUE THREAD

**Issue by Lionfox2** [advplyr/audiobookshelf#2284]
### Describe the issue

Hey, 

i use the german version of audiobookshelf. Most strings are translated, but one string does not exist in de.json: 

On the authors library page there is written beneath every author the number of books:

![image](https://github.com/advplyr/audiobookshelf/assets/50257663/cee858e3-6ff9-46d6-a0fb-350c65875b92)

Unfortunately the corresponding string does not exist in the de.json.

### Steps to reproduce the issue

1. Change language of Audiobookshelf to any foreign language
2. Open the library authors page
3. See the written number of books beneath every photo of an author.

### Audiobookshelf version

2.5.0

### How are you running audiobookshelf?

Built from source

**Comment by Lionfox2** [comment]
i wrote an comment to this commit:

https://github.com/advplyr/audiobookshelf/commit/8f4c75ff2b9f8bad28ce73ac671fded891e9a0a2#commitcomment-134093094

**Comment by advplyr** [comment]
This is in v2.6.0
