### ISSUE TITLE
Possible UI z depth tweak

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#23]
I wanted to see where the "delete" button was and couldn't find it, until I realized it was being hidden by the playback UI at the bottom of the screen.

A possible solution might be to have the "edit" UI be on a higher layer (I think it's called z-depth) than the playback UI elements.

To be clear, this is NOT a big deal, but it did take me a moment to realize what to do. (In case it matters, I'm on a 2160p windows resolutions with 200% windows auto-scaling) I just figured I'd point it out in case it was an easy fix.

**Comment by advplyr** [comment]
Nice catch, this is fixed in v1.1.1
