### ISSUE TITLE
Bug app

### ISSUE THREAD

**Issue by orrionis** [advplyr/audiobookshelf#230]
Hi

Since the Last update of my app, ive à little problem
The say empty librairie. Or the Web gui show all book.

![Screenshot_20211210-004501_AudioBookshelf](https://user-images.githubusercontent.com/65168007/145493262-f483c7a9-400d-456e-941d-4e5399893c96.jpg)

![Screenshot_20211210-004714_Chrome](https://user-images.githubusercontent.com/65168007/145493327-2153b9fb-86b3-4bfa-a2ff-79c6ec7601b7.jpg)

But i can Still play the book is in progress

**Comment by advplyr** [comment]
Is your server version 1.6.39?

**Comment by orrionis** [comment]
My version server, 1.6.18

**Comment by advplyr** [comment]
Many of the mobile app updates come with updates to the server, because the app is still in beta.
Updating the server should solve your issue.

**Comment by orrionis** [comment]
Okok i très this. Thanks
