### ISSUE TITLE
[Enhancement]: Rename "Search" page in podcast library

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf#2301]
### Describe the feature/enhancement

Renaming the "Search" tab on the web client will help reduce confusion on how to add podcasts from the internet (since people try to use the search bar at the top of the screen.

I think "Add" is a good word for it, since it clarifies that a podcast is being "searched to add to server" versus "searching what is on the server".

(as of 2.5.0)

**Comment by nichwall** [comment]
Reference image (from 2.5.0)
![image](https://github.com/advplyr/audiobookshelf/assets/5686638/ef23b08c-232e-428c-bdb4-53d30697fc03)

**Comment by advplyr** [comment]
Updated in [v2.6.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.6.0)
