### ISSUE TITLE
[Bug]: Some Audiobooks are not included into the library

### ISSUE THREAD

**Issue by StarPicard** [advplyr/audiobookshelf#2306]
### Describe the issue

Hello,

I have a folder with some audio books by the author Stephen King. Unfortunately, Audiobookshelf only recognizes one audiobook from this folder. The folder is structured as follows:

```
├───Der dunkle Turm
│   └───Schwarz
├───Es
├───Es (Kopie)
├───Revival
├───Sleeping Beauties
└───The Stand
```

I will be happy to provide further information.

Best regards

### Steps to reproduce the issue

Start Audiobookshelf and wait to scan all folders

### Audiobookshelf version

2.5.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Have you checked the logs for errors?

Are you sure multiple books are not being grouped as the same book? https://www.audiobookshelf.org/faq#why-are-multiple-books-showing-as-the-same-book

**Comment by StarPicard** [comment]
Hi, actually, this was the error. Thank you!
