### ISSUE TITLE
[Enhancement]:  Ability to sort/rename directory structure based on metadata

### ISSUE THREAD

**Issue by austinsr1** [advplyr/audiobookshelf#2309]
### Describe the feature/enhancement

Hello,

A feature similar to Sonarr/Radarr for renaming and organizing directory structure would be amazing. 
In Sonarr/Radarr, when you are in a view for a show, you have an option to rename the files and directory structure to match what they are expecting (c:\tv\Series Name\Season Number\Episodes).

An option similar to that would be a great addition to Audiobookshelf. I have been cleaning up the metadata and series names on my collection, but the ability to move it all into a proper directory structure afterward would be very useful. (c:\audiobooks\Author Name\Series Name\Book Name\Book.extension)

Thanks!

**Comment by nichwall** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/312

**Comment by austinsr1** [comment]
Apologies. I missed that when I was searching for this.

**Comment by nichwall** [comment]
No worries, it's hard to find the right search terms when someone describes it differently
