### ISSUE TITLE
Donation link or "Buy me a coffee"

### ISSUE THREAD

**Issue by danmed** [advplyr/audiobookshelf#231]
Do me a favor and add a link where i can donate to you for this project!

Not looking for any special treatment in return.. just let me give something back!

(I only have 1 bug report and it's to do with AA and not updating the play progress which i think has already been reported)

**Comment by Subdarub** [comment]
i would second that. You deserver it :)

**Comment by advplyr** [comment]
I appreciate your support! A server will be needed soon to host the binaries, and that could be funded via donations. Although it won't cost much.
There is a discussion opened on this #171 and I will put any updates in there. Thank you!
