### ISSUE TITLE
[Bug]: [FfmpegHelpers] Extract Cover Error Error

### ISSUE THREAD

**Issue by dmuiX** [advplyr/audiobookshelf#2316]
### Describe the issue

Scanning new m4a files tagged with mp3tag throws:
[FfmpegHelpers] Extract Cover Error Error: ffmpeg exited with code 1: Error while decoding stream #0:2: Invalid data found when processing input Cannot determine format of input stream 0:2 after EOF Error marking filters as finished Conversion failed!

### Steps to reproduce the issue

1. put a file in the audiobookfolder and let audiobookshelf scan new files

### Audiobookshelf version

v.2.5.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you share the full ffprobe output?

**Comment by dmuiX** [comment]
Where can i find it? Or do you mean the whole log that I can find under logs?

**Comment by advplyr** [comment]
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/218571ae-8a45-4a99-be17-5c59c71f6eea)


Then you will see a "Probe Audio File" button

**Comment by dmuiX** [comment]
{
  "programs": [],
  "streams": [
    {
      "index": 0,
      "codec_name": "aac",
      "codec_long_name": "AAC (Advanced Audio Coding)",
      "profile": "HE-AAC",
      "codec_type": "audio",
      "codec_tag_string": "mp4a",
      "codec_tag": "0x6134706d",
      "sample_fmt": "fltp",
      "sample_rate": "44100",
      "channels": 2,
      "channel_layout": "stereo",
      "bits_per_sample": 0,
      "initial_padding": 0,
      "id": "0x1",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/22050",
      "start_pts": 1056,
      "start_time": "0.047891",
      "duration_ts": 26463232,
      "duration": "1200.146576",
      "bit_rate": "82570",
      "nb_frames": "25843",
      "extradata_size": 5,
      "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "creation_time": "2023-11-16T17:43:54.000000Z",
        "language": "und",
        "vendor_id": "[0][0][0][0]"
      }
    },
    {
      "index": 1,
      "codec_name": "mjpeg",
      "codec_long_name": "Motion JPEG",
      "profile": "Progressive",
      "codec_type": "video",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "width": 1552,
      "height": 1080,
      "coded_width": 1552,
      "coded_height": 1080,
      "closed_captions": 0,
      "film_grain": 0,
      "has_b_frames": 0,
      "pix_fmt": "yuvj444p",
      "level": -99,
      "color_range": "pc",
      "color_space": "bt470bg",
      "chroma_location": "center",
      "refs": 1,
      "id": "0x0",
      "r_frame_rate": "90000/1",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 4310,
      "start_time": "0.047889",
      "duration_ts": 108013192,
      "duration": "1200.146578",
      "bits_per_raw_sample": "8",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 1,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      }
    },
    {
      "index": 2,
      "codec_name": "mjpeg",
      "codec_long_name": "Motion JPEG",
      "profile": "JPEG LS",
      "codec_type": "video",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "width": 0,
      "height": 0,
      "coded_width": 0,
      "coded_height": 0,
      "closed_captions": 0,
      "film_grain": 0,
      "has_b_frames": 0,
      "level": -99,
      "color_space": "bt470bg",
      "chroma_location": "center",
      "refs": 1,
      "id": "0x0",
      "r_frame_rate": "90000/1",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 4310,
      "start_time": "0.047889",
      "duration_ts": 108013192,
      "duration": "1200.146578",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 1,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      }
    }
  ],
  "chapters": [],
  "format": {
    "filename": "/audiobooks/Hoerspielprojekt.de/Zwanzig durchnummerierte Minuten/Zwanzig durchnummerierte Minuten.m4b",
    "nb_streams": 3,
    "nb_programs": 0,
    "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
    "format_long_name": "QuickTime / MOV",
    "start_time": "0.047889",
    "duration": "1200.146576",
    "size": "18890088",
    "bit_rate": "125918",
    "probe_score": 100,
    "tags": {
      "major_brand": "M4A ",
      "minor_version": "0",
      "compatible_brands": "M4A mp42isom",
      "creation_time": "2023-11-16T17:43:54.000000Z",
      "gapless_playback": "0",
      "description": "Zwanzig durchnummerierte Minuten\n\nBeschreibung:\nEin Individuum steht draußen in der Nacht. Mitten auf dem weiten Raum. \nAls ein Mann die Szene betritt, beginnt eine zwanzigminütige Reise, die durch die Ereignisse der darauffolgenden zwei Tage führt.\n\nEin Hörstück in zwanzig Minuten - inspiriert durch die Musik von psykheart (@psykheart).\n\n\n\nCredits:\nErzählerin 1:\t\tAnja Klukas\nErzähler 1:\t\tBenno Silberer\nErzähler 2:\t\tRobert Kerick\nErzählerin 2:\t\tMaria Arato\n\nSkrip + Schnitt: \tRaphael Drechsler\nLektorat:\t\tMarek Schaedel\n\nCovergestaltung:\tpsykheart\n\nMein spezieller Dank gilt Sascha Panevin als Testhörer und Sound-Magier!\n\n\n\nMusik und Sounds:\nMinute 1: \tpsykheart \t\t\t\tPeaceful ambient track with singing bowl and trash compactor \t\twww.youtube.com/watch?v=ISOSg7f8OvY\nMinute 2:\tmartypinso\t\t\t\tSOUND: DMP013016 HEAVY SNOW STORM MS\t\t\t\t\twww.freesound.org/people/martypinso/sounds/35480/\nMinute 3:\tpsykheart \t\t\t\tSidrax & Wingie & Make Noise Easel in the Dark\t\t\t\twww.youtube.com/watch?v=qZXEKvJbdYk\nMinute 4+5:\tSUNTAPES\t\t\t\tSolomon view (Zertifizierte Nutzung durch Jamendo Licensing)\t\twww.jamendo.com/track/528340/solomon-view\nMinute 6+7: \tTHE MIND ORCHESTRA\t\t\tBruwynn\t\t\t\t\t\t\t\t\twww.jamendo.com/track/1885799/bruwynn\nMinute 8: \tBenbojangles\t\t\t\tSOUND: Desert binaural Wind\t\t\t\t\t\twww.freesound.org/people/Benbojangles/sounds/457159/\nMinute 9: \tpsykheart \t\t\t\tAmbivalentines Day Film Textures\t\t\t\t\twww.youtube.com/watch?v=0U_NJhYRWZ0\nMinute 10:\tETHNOSOULSOUNDSYSTEM\t\t\tJe taime nature\t\t\t\t\t\t\t\twww.jamendo.com/track/1545623/5-je-taime-nature\nMinute 11:\tpsykheart \t\t\t\tPeaceful ambient track with singing bowl and trash compactor \t\twww.youtube.com/watch?v=ISOSg7f8OvY\nMinute 12:\tAMBIENT SAMURAI (ICHIRO NAKAGAWA)\tMusic For Music / Poetry Sphere\t\t\t\t\t\twww.jamendo.com/track/1195365/music-for-music-poetry-sphere\nMinute 13:\tpsykheart\t\t\t\tonce you fall in love with drones...\t\t\t\t\twww.youtube.com/watch?v=ZFLbNuo6DAc\nMinute 14:\tpsykheart\t\t\t\tSketchbook, coffee, sunlight & ambient synths\t\t\t\twww.youtube.com/watch?v=1V7Iwi6YMcc\nMinute 15:\tSeanSecret\t\t\t\tSOUND: Original Ambience Sound Unaltered\t\t\t\twww.freesound.org/people/SeanSecret/sounds/251652/\nMinute 16:\tARTSOMERVILLE\t\t\t\tBeat Noir\t\t\t\t\t\t\t\twww.jamendo.com/track/370640/beat-noir\nMinute 17:\tNOISESURFER\t\t\t\tWorld 11 \t\t\t\t\t\t\t\twww.jamendo.com/track/989917/world-11\nMinute 18:\tNOISESURFER\t\t\t\tWorld 8 \t\t\t\t\t\t\t\twww.jamendo.com/track/989924/world-8\nMinute 19+20:\tpsykheart\t\t\t\tA Descent into Covid Chaos\t\t\t\t\t\twww.youtube.com/watch?v=Xmm6EPxfe08\n",
      "genre": "Audiobook",
      "date": "2023",
      "encoder": "Music 1.4.1.29",
      "title": "Zwanzig durchnummerierte Minuten",
      "LANGUAGE": "German",
      "iTunSMPB": " 00000000 00000840 00000460 000000000193BF60 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000",
      "composer": "Anja Klukas, Benno Silberer, Robert Kerick, Maria Arato",
      "artist": "Hoerspielprojekt.de",
      "album_artist": "Hoerspielprojekt.de",
      "album": "Zwanzig durchnummerierte Minuten",
      "Encoding Params": "vers"
    }
  }
}

**Comment by advplyr** [comment]
Did you embed 2 images into the file? Can you try removing the second one for testing this because I'm not recognizing the format of that.

**Comment by dmuiX** [comment]
Yeah there a two pictures inside this file.
Actually its not that important for me as I am always saving the cover as cover.jpg in every folder. And I have in almost every file more than 1 cover. So for me its okay when audiobookshelf throws this error.
Just thought this might be a more general error and could help others.

**Comment by advplyr** [comment]
It shouldn't matter if you have multiple images embedded but the ffprobe stream for the second image isn't looking familiar to me so we would have to dig into what that second image is

**Comment by dmuiX** [comment]
Ah okay yeah then lets do that. I will try what you wrote and will post the ffprobe. 
Currently my system is not running but I might find time tomorrow or the day after tomorrow.

**Comment by dmuiX** [comment]
then it might help others^^
