### ISSUE TITLE
[Bug]: Author Quick Match Grabs the wrong author. No way to manually remove it without removing author?

### ISSUE THREAD

**Issue by strmca** [advplyr/audiobookshelf#2319]
### Describe the issue

Matching Emily Brontë and Adam Savage bring up the wrong bios and photos.  
Other than removing the authors - which removes the books - there seems to be no way to correct this.  
(I added this as a bug instead of an enhancement because of the multi step challenge of removing the incorrect information. Perhaps it should be an enhancement though?)

Adam Savage appears to be a duplicate with another author.  Google agrees with me though that Savage is the Mythbusters guy.

![Screenshot 2023-11-17 at 00-41-43 Audiobookshelf](https://github.com/advplyr/audiobookshelf/assets/44687131/c54fcafd-0272-4a99-b5e1-f78a26191d3a)

And this isn't Emily Brontë or her bio either - the name isn't that close even:  
![Screenshot 2023-11-17 at 00-11-24 Audiobookshelf](https://github.com/advplyr/audiobookshelf/assets/44687131/a73153a5-97c9-474a-ba16-b73c8bd28d3e)

At first, I thought maybe it was the special character in Brontë's name but there's no such thing in Savage's name. 

The behaviour I would have expected for a duplicate would be a choice to make manually.  For Brontë, I would not expect to see a completely different bio and person automatically inserted.   Perhaps a "No match" sort of message instead, like other authors that had no matches.

Also the behaviour I'd like to see is the ability to remove a mismatched author's info not purge the author and their books from the library. 

Running this on Ubuntu 20.04LTS

My scanner (I think irrelevant?) options are:
![Screenshot 2023-11-17 at 00-38-09 Audiobookshelf](https://github.com/advplyr/audiobookshelf/assets/44687131/bbc5b5e1-0a5a-484f-aaef-bcde6adf62b2)

### Steps to reproduce the issue

1. Add a folder of books (In my case, Emily Brontë or Adam Savage)
2. The scanner sees the books and adds them and the author. 
3. Go to the Authors and see Emily Bronte (or Bronte)'s name, click on pencil, then Quick Match
4. See the wrong bio and photo.
5. See no easy way to remove this incorrect info. 

### Audiobookshelf version

2.5.0. debian

### How are you running audiobookshelf?

Debian/PPA

**Comment by hobesman** [comment]
I'm not disputing whether a change is appropriate, but just to confirm my understanding of the current situation, are you able to go back to clicking the pencil, then delete the ASIN, bio, and picture, and that leaves you just where you were to start?

**Comment by strmca** [comment]
> I'm not disputing whether a change is appropriate, but just to confirm my understanding of the current situation, are you able to go back to clicking the pencil, then delete the ASIN, bio, and picture, and click save, and that leaves you just where you were to start?
> 
> When I hover over the picture, for example, a little trash can appears for me.

I swear I tried that last night and it didn't work but in the light of day now it appears to.  I tried to remove Savage's info but it highlighted but delete did nothing.  Now today, I can do exactly as you mentioned and obviously no version update to the software.  That's really strange.  Maybe just some weird glitch on my end?  

Additionally, neither author gets a match today either - which is closer to what I'd expect to be proper behaviour.

**Comment by advplyr** [comment]
For your scanner settings screenshot keep in mind that if you are disabling "Audiobookshelf metdata file" then the scanner won't use the updates you are making manually to book details.

Is there anything that needs to get fixed with this original issue?

**Comment by strmca** [comment]
> For your scanner settings screenshot keep in mind that if you are disabling "Audiobookshelf metdata file" then the scanner won't use the updates you are making manually to book details.
> 
> Is there anything that needs to get fixed with this original issue?

Ah, thank you!  I will re-enable that one then.  I was struggling with a bunch of CD ripped audiobooks and took the easiest path.  Now, I think the scanner will only affect things added going forward? 

I think the original issues are maybe some weird glitch on my end.  Possibly related to having a server that's old enough to drink in almost any country in the world. Thank you though for your attention!
