### ISSUE TITLE
[Enhancement] audiobooks titles

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf#232]
Hello I would suggest adding audiobook title and athor under the cover, b/c very often it is hard to find a book only  by the cover ;)

I made few suggestions: https://imgur.com/a/D9tH5Lz  
My favourites are Plexamp 1 , Plexamp 2.
Where:
1st line:  #(series number)  Title 
2nd line: Autthor, readby
3rd line: rating, genre whatever is sorted by now.

Adding series number before Title is great, because it lets you see if you miss a book or let you choose first title right away. ( Could be different color to seperate it from Title)

Storytel and audible have cool functionality of allowing to get more info about book without openning new window.
I think it is imporant to design app from smallest device screen to biggest.

**Comment by advplyr** [comment]
There was a list view for a bit but it has to be re-done to work with large libraries.
Are you suggesting doing away with the books sitting on a shelf design? I agree there should be an option to show titles/author/etc, but I'm not sure about the design.

**Comment by keaganhilliard** [comment]
One option would be adding a small overlay with the title like this:
![image](https://user-images.githubusercontent.com/27737278/145721720-e795a628-6169-45e2-8493-c6bdd4d99427.png)

**Comment by advplyr** [comment]
Good idea, if you have experimental features on the authors page does that.

**Comment by superpawko** [comment]
I did it because you ask me about it last time I asked about covers. 

Honestly I care more about functionality. For now it is really hard for me to use app , because lack of basic functionality and other bugs.

But if you want to fix design. Yes i think current design is out-dated.  Most people who care about self-hosting libraries are Collectors.  I myself treat audiobook covers as peace of art, and adiobook library as art gallery so I find current design as distracting. 

I think what could be easier to do is cleaner design and oriented for mobile app first. And scaled to web. Adding anything on top of piece of art is illegal and should be punished :D

I really like plexamp design. Storytel have also clean design. Plex itself is also clean design. There is many things to choose from. The simpler the better.

**Comment by advplyr** [comment]
I'm open to all design suggestions.
I think the best way to handle this is to have the layout be configurable in settings.

**Comment by advplyr** [comment]
Just pushed `v1.6.49` that has a server setting to use an alternative bookshelf view

![image](https://user-images.githubusercontent.com/67830747/147611348-deb1b322-0a98-4db6-a4f9-128f9ad168a0.png)

![image](https://user-images.githubusercontent.com/67830747/147611291-f5896fd2-5151-4b81-a1dd-2d63ccbeab46.png)

This does not yet include the 3rd line when filtering or sorting and this may be changed to a user setting instead of a server setting. Just wanted to get the ball rolling on this one.

**Comment by superpawko** [comment]
Could you add series number before title ?    #1 , #2 , #3  etc.  it easy to see if you miss a title, or see if book is series.  https://i.imgur.com/Oe6DfHB.png

**Comment by advplyr** [comment]
Added the volume number in `v1.6.55`

**Comment by advplyr** [comment]
In `v1.6.67` the alternate view will also show a 3rd line when sorting by added at, duration or size.

![image](https://user-images.githubusercontent.com/67830747/153968207-4451e2a7-83c9-48cb-93be-3b16cc485b42.png)

When sorting by author Last, First it will update the author line.
