### ISSUE TITLE
[Bug]: Podcast image and categories are not pulled into iTunes Podcast Connect

### ISSUE THREAD

**Issue by yigitkeremoktay** [advplyr/audiobookshelf#2321]
### Describe the issue

I wanted to add my podcast to iTunes Podcast Connect however the thumbnail did not seem to appear and no Category was selected.

### Steps to reproduce the issue

1. Setup Audiobookshelf
2. Create a podcast library with iTunes feed type selected
3. Add an audio file
4. Add episode details
5. Add podcast details including genre and tags
6. Upload a cover that is 3000px x 3000px
7. Open an RSS feed, dismiss the message by clicking anywhere outside the box after copying the URL.
8. Submit the RSS feed to podcasts connect.
9. Podcasts connect does not detect genre or the thumbnil.

### Audiobookshelf version

v2.5.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I tested this and can confirm the cover image doesn't show up in iTunes Podcast Connect. I don't know why that would be since the RSS feed is following specs and the image shows up in other podcast apps. It seems like an issue on their end or they are wanting something beyond the specifications.

**Comment by yigitkeremoktay** [comment]
> I tested this and can confirm the cover image doesn't show up in iTunes Podcast Connect. I don't know why that would be since the RSS feed is following specs and the image shows up in other podcast apps. It seems like an issue on their end or they are wanting something beyond the specifications.

I have tested other software and looks like with a similar RSS feed format, the image is pulled. I believe the issue is the format. iTunes probably expects specific dimensions and image format, likely requiring conversion from audiobookshelf.

I also feel like the categories should be added to the RSS feed. I'm not sure if there is a feature to put them in the RSS feed but iTunes requires them for publishing a podcast so would be really useful. Without it the RSS feed loses lots of its purpose.

**Comment by advplyr** [comment]
You could test the cover by using a cover image of their specification in Abs. Abs is just serving the raw cover that you are providing.

**Comment by yigitkeremoktay** [comment]
> You could test the cover by using a cover image of their specification in Abs. Abs is just serving the raw cover that you are providing.

Did try a 3000x3000 PNG image, did not work. Created the cover with Illustrator. Could have been a case of PPI, resolution and dimension combination. Maybe a simple conversion is required before saving in the settings page handler?

**Comment by advplyr** [comment]
Might be because the RSS feed doesn't have a file extension at the end. That was a case recently for audio files https://github.com/advplyr/audiobookshelf/pull/2272

**Comment by advplyr** [comment]
I just realized that update hasn't been released yet, so the next server release may fix the cover part
