### ISSUE TITLE
[Enhancement]: UX - "Metadata order of precedence" doesn't make sense to me

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#2322]
### Describe the feature/enhancement

It's a list of 5 items. The top item in the list is the item with the lowest priority.

Sure, there is a text saying that "1 is lowest 5 is highest". I still makes no sense having the list in that order.

Also, the documentation at https://www.audiobookshelf.org/guides/book-scanner/#book-metadata-parsing indicates the exact opposite.

**Comment by nichwall** [comment]
Does this clarify the guide enough? It's says the same thing since it's based on the numbers, but the guide wasn't super clear.

https://github.com/advplyr/audiobookshelf-web/pull/59

**Comment by advplyr** [comment]
This was updated in v2.6.0 to be more intuitive
