### ISSUE TITLE
[Bug]: Some Podcasts won't download. AxiosError: self signed certificate

### ISSUE THREAD

**Issue by strike84** [advplyr/audiobookshelf#2337]
### Describe the issue

I have a bunch of podcasts that just won't download. I don't know if it's an ABS issue or an issue with the particular podcasts,other podcasts downloads fine so I don't think it's a config issue. It finds all the episodes, but it fails to download them. All of them show up with the same error in the log. If I try to go t the link in the log in a web browser the episodes plays fine. I've tried to remove the podcasts and add them again, but same issue.
Here is the log for one episode:

[2023-11-21 21:10:40] ERROR: [ffmpegHelpers] Failed to download podcast episode with url "https://pdst.fm/e/pscrb.fm/rss/p/chrt.fm/track/C35921/traffic.megaphone.fm/GLT2616025051.mp3?updated=1693576186" AxiosError: self signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:953:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 30000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.27.2'
    },
    url: 'https://pdst.fm/e/pscrb.fm/rss/p/chrt.fm/track/C35921/traffic.megaphone.fm/GLT2616025051.mp3?updated=1693576186',
    method: 'get',
    responseType: 'stream',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/e/pscrb.fm/rss/p/chrt.fm/track/C35921/traffic.megaphone.fm/GLT2616025051.mp3?updated=1693576186',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'pdst.fm',
      port: null,
      nativeProtocols: [Object],
      pathname: '/e/pscrb.fm/rss/p/chrt.fm/track/C35921/traffic.megaphone.fm/GLT2616025051.mp3',
      search: '?updated=1693576186'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /e/pscrb.fm/rss/p/chrt.fm/track/C35921/traffic.megaphone.fm/GLT2616025051.mp3?updated=1693576186 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Host: pdst.fm\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/e/pscrb.fm/rss/p/chrt.fm/track/C35921/traffic.megaphone.fm/GLT2616025051.mp3?updated=1693576186',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'pdst.fm',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://pdst.fm/e/pscrb.fm/rss/p/chrt.fm/track/C35921/traffic.megaphone.fm/GLT2616025051.mp3?updated=1693576186',
    _timeout: null,
    [Symbol(kCapture)]: false
  }
} (ffmpegHelpers.js:99)
[2023-11-21 21:10:45] DEBUG: [Watcher] removeIgnoreDir: No longer ignoring directory "/podcasts/The Diary Of A CEO with Steven Bartlett" (Watcher.js:351)

 

### Steps to reproduce the issue

1. Try to download the podcast "The Diary Of A CEO with Steven Bartlett" as a test, or "Command Line Heroes" 

### Audiobookshelf version

v2.5.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I just tested both of these podcasts and had no issues downloading the most recent 2 episodes from each. I'm not sure what is going on for you

**Comment by strike84** [comment]
Thanks for testing. I don't really know what's happening then. :/ I've tried everything I can think of on my side.

**Comment by advplyr** [comment]
Have you resolved this issue?
