### ISSUE TITLE
[Enhancement]: A way to create connections between ABS entries, e.g., to link a Blink to a book

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf#2350]
### Describe the feature/enhancement

I'm sure that others can find a myriad of uses for such a feature, but this is my particular use case this morning: 

I've got all these Blinks sitting around that I never do anything with because I never think to listen to them before I take on a multi-day book (e.g. Niall Ferguson - The House of Rothschild is 2 days 1/2 hour).  In this particular case, when I put the book into my library, I can check to see if the Blink exists and I could then manually create a cross reference that would display an icon (e.g., the Blinkist favicon: https://www.blinkist.com/favicon.ico) in front of the book cover to let the user know that there's a Blink available for that title.  

I could see perhaps having a cross to the Fresh Air episode with the author in the case of Savage Continent (https://www.goodreads.com/en/book/show/13167112 and https://www.npr.org/2013/07/24/204538728/after-wwii-europe-was-a-savage-continent-of-devastation).   The _Times_ has a book review podcast; that could be a connection.

Something like this would require the ability for a podcast library to communicate with an audiobook library so that might be a bit more challenging, but I also think it's useful to be able to bridge the library silos so that you can see a bit more of what's going on in the entire collection.  Which actually makes me think of another enhancement... 
(See also https://github.com/advplyr/audiobookshelf/issues/2236)

**Comment by advplyr** [comment]
I'm not understanding this to the point that I'm not sure what question to ask

**Comment by nichwall** [comment]
I *think* it's another request to rewrite the libraries so users can combine podcasts and audiobooks based on the linked FR, but yeah I'm also very confused.

**Comment by iconoclasthero** [comment]
I'm at lunch, I'll flesh this out on discord.
