### ISSUE TITLE
[Bug]: Random audiobooks disappearing periodically

### ISSUE THREAD

**Issue by babbysross** [advplyr/audiobookshelf#2354]
### Describe the issue

Random audiobooks have been disappearing from my library over the past few months. Any time I refresh the webUI, there seems to be at least another one missing, and the actual files in my server are also gone. If the book that disappears is the only one of an author's that I have, the author folder will also be removed.

### Steps to reproduce the issue

1. Periodic issue, seemingly random, though it has been occurring for a few months across multiple audiobookshelf versions.

### Audiobookshelf version

v2.5.0(Unraid)

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Abs is not going to remove files from your file system so if that is happening for you then you have something else going on.
