### ISSUE TITLE
[Bug]: Error 'Playback failed: Source error' appearing when trying to play a downloaded audio book

### ISSUE THREAD

**Issue by andrewklajman** [advplyr/audiobookshelf#2358]
### Describe the issue

Application version v2.2.20 0.9.67-beta
Device: Pixel 6a
Android version: 14

I am able to install Audiobookshelf from the Play store without an issue.  I am also able to stream content from my Audiobookshelf server without any issue.  I can also download an audio book without a problem (it says that it downloads successfully and the 'Stream' button changes to 'Play).

But when I try to play content that has downloaded I get an red banner error message at the bottom of the application saying 'Playback failed: source error'

I then delete the download and attempt to download it to another folder instead of the 'Internal App Storage' folder.  At the end of the download I get a red banner error message at the bottom of the application saying 'Item download complete but failed to create library item'.  It is worth noting that this time the 'Stream' button does not change to 'Play'

This is happening to all files that I test.  Also Im unsure if it is related but these files are mp3.

Im not sure if there is a more verbose method to get logs from the mobile app?

Server is running from NixOs respository

### Steps to reproduce the issue

1. Press download button
2. Press Play button
3. Experience error

### Audiobookshelf version

v2.2.20 0.9.67-beta

### How are you running audiobookshelf?

Other

**Comment by advplyr** [comment]
The mobile apps require server v2.2.23 or up. Upgrading the server should do it for you

**Comment by andrewklajman** [comment]
Yes, youre right. 

So sorry I just presumed this was an app issue and did not consider to upgrade the server.  It is working fine now.

Regards
