### ISSUE TITLE
[Bug]: Narrators page go 404 when reload

### ISSUE THREAD

**Issue by MrDaft** [advplyr/audiobookshelf#2359]
### Describe the issue

When I go to narrators page and try to refresh it there is an 404 with 'Cannot GET /library/b7093f9c-922b-44eb-95f3-ce3e8053c123/narrators'
Not a big deal, but sometimes narrators doesnt come up when added first time, need to delete narrator and add again

### Steps to reproduce the issue

1. open chrome browser on PC
2. go to narrators page
3. click refresh

### Audiobookshelf version

v2.5.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.7.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.0)
