### ISSUE TITLE
[Enchantment] Books being in Multiple Series and Volumes

### ISSUE THREAD

**Issue by DK2Maverick** [advplyr/audiobookshelf#236]
An example Would be Ship of Magic by Robin Hobb. It is The Liveship Traders # 1 and The Realm of the Elderlings Series # 4

Would it be possible to add the book to both series and show in both series with its respective volume #?

Thanks

**Comment by advplyr** [comment]
It's not possible now, but it has been brought up before. This would cause some issues with the current setup that would need to be resolved first.

Right now there is only 1 volume number input, how would this need to change to support multiple series and what would that look like from a design perspective?

Currently the series & volume number is used under the book title, just like good reads. https://www.goodreads.com/book/show/45100.Ship_of_Magic
I'm not sure how this would look with multiple series.

Goodreads, google books and audible just use The Liveship Trader but you can still see the book when going directly to the series page for The Realm of the Elderlings.

**Comment by DK2Maverick** [comment]
Maybe a spot for secondary series and secondary volume #. Something that only effects the display in the series tab.
Very useful for the big arcing stories.  So you could have Pern publication order and then Pern chronological.  and the before mentioned small 3 book trilogy in the larger overarching story with multiple trilogies that have a definitive order.

**Comment by itschrisonline** [comment]
Instead of a new field maybe auto generate a collection?

**Comment by advplyr** [comment]
I think series just needs to be more like collections. Meaning it is not something you set in the details tab, it has a "Add to Series" option in the menu dropdown and looks like collections except it includes a volume # for each book.

It seems like this is the cleanest way to handle this, but it is a big project.

**Comment by develroo** [comment]
> I think series just needs to be more like collections. Meaning it is not something you set in the details tab, it has a "Add to Series" option in the menu dropdown and looks like collections except it includes a volume # for each book.
> 
> It seems like this is the cleanest way to handle this, but it is a big project.

I concur. Making a collection of say "Discworld" would make more sense than trying to sort either by series or authors, come to think of it. I can think of many other genres like the as well including Feynman lectures etc.

**Comment by MidnightSnowleopard** [comment]
Agreed, an easy way to add books into a collection and set position in a collection would likely be the easiest.  Only problem at that point that I can see is a way to create collections based on library scan data.  Some collections are just too large/unrelated based other information to easily try and place into a collection from the UI.

**Comment by DK2Maverick** [comment]
Collections would work, but a book would need to be able to be in multiple diff collections with different volume numbers in each collection.

**Comment by itschrisonline** [comment]
1 series for the standalon series
Collection for the universe?
I'm pretty sure you can have the same book in multiple collection

**Comment by develroo** [comment]
Well that would kinda make sense as often world series can be written by other authors. Not everyone is Anne McCaffrey ;) 

Seriously, though, I would like things like the Dragon Lance Chronicles to be their own 'set' and Legends etc. etc. Obviously books can span different sets but, if you think about how Calibre manages it, it has a field to show if a book belongs to a series of a set as well as genres worlds etc. It is all to do with what the metadata is included in normal books and if extra data is needed to be kept locally instead.

**Comment by itschrisonline** [comment]
Yeah but hopefully when reading the series it shouldn't matter which author it is but the series id itself

**Comment by advplyr** [comment]
In [v2.0.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.1) books can belong to multiple series!
