### ISSUE TITLE
[Bug]: "Use square book covers" library option is not working

### ISSUE THREAD

**Issue by racemus** [advplyr/audiobookshelf#2366]
### Describe the issue

Option is not working

### Steps to reproduce the issue

When I recreate library and book has multiple files for cover, ABS choose not the square one

### Audiobookshelf version

2.6.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you share a screenshot of what you mean it's not working?

**Comment by hobesman** [comment]
I think maybe there's a misunderstanding of what that option does. I don't think that option changes which cover image is selected. That option only changes whether the image is shown with borders to fit the chosen aspect ratio, or without.

**Comment by advplyr** [comment]
Yeah I think this is a misunderstanding but let me know if you have more info
