### ISSUE TITLE
[Bug]: Hide `Change Password` when `Password Authentication` disabled

### ISSUE THREAD

**Issue by jflattery** [advplyr/audiobookshelf#2367]
### Describe the issue

Currently when `Password Authentication` is disabled, the user still has the option to change their password. This may cause confusion for the user as changing the password within the app will have no affect on the password used by the `OpenID Connect Authentication`

### Steps to reproduce the issue

1. Enable `OpenID Connect Authentication`
2. Disable `Password Authentication`
3. User navigates to their account page and is presented with an option to change their password.

### Audiobookshelf version

v2.6.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.7.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.0)
