### ISSUE TITLE
[Enhancement]: Audiobookshelf wrapped

### ISSUE THREAD

**Issue by glacasa** [advplyr/audiobookshelf#2373]
It's the time of the year when everybody posts their Spotify Wrapped on their social networks, and I think it would be nice to have a feature like that on audiobookshelf :
- a section for the last year in the stats page, with some infos like : total audiobooks listened, total hours, longest book, etc
- generate images to post on social network, and a share button
- add a link on the home page in december "Get your audiobookshelf wrapped" (with an option to disable this, of course)

Probably related : #1564

**Comment by advplyr** [comment]
I like stats too

> * total audiobooks listened, total hours, longest book, etc

Is there anything else you can think of that would be interesting?

**Comment by Teekeks** [comment]
I personally would love a list of all audiobooks that I listened to in that time period as well

**Comment by glacasa** [comment]
> Is there anything else you can think of that would be interesting?

Maybe most listened authors, genre, number of unfinished books

**Comment by advplyr** [comment]
I'm not sure how to handle if you just marked a book as finished without listening. If we are calculating the total hours you listened in 2023 this would only include tracked listening time. If we are calculating the longest book you finished this would just look for books marked as finished in 2023.

**Comment by advplyr** [comment]
I was having some fun with this yesterday and after discussing on Discord landed on this so far:

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/10277b6c-da17-4818-adfc-a621ef4c0e6e)

The covers in the background are random books you read for the year. I'm not a designer so if anyone with design skills wants to help out that would be great. I will probably release the first variation of this over the weekend.

This is already available on the `edge` docker image if you go to the user stats page for anyone who wants to try it out.

**Comment by advplyr** [comment]
Added in [v2.7.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.0)
