### ISSUE TITLE
[Enhancement]: Add an HTTPS redirect URL for OIDC support on mobile

### ISSUE THREAD

**Issue by mark-monteiro** [advplyr/audiobookshelf#2379]
### Describe the feature/enhancement

Currently, the mobile app uses the redirect URI `audiobookshelf://oauth` for the mobile app. I'm not sure how common it is for OAuth providers to support custom schemes in the redirect URI, but at least for Authelia, only the `http` or `https` schemes are supported ([see docs](https://www.authelia.com/configuration/identity-providers/open-id-connect/#redirect_uris)). For OAuth providers with this limitation, it is not possible to use OIDC on the mobile app.

I am going to quote the [documentation from Immich](https://immich.app/docs/administration/oauth#mobile-redirect-uri) on how this problem is solved in that application, because I think the same approach can be used here:

> The redirect URI for the mobile app is `app.immich:/`, which is a [Custom Scheme](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app). If this custom scheme is an invalid redirect URI for your OAuth Provider, you can work around this by doing the following:
>
> 1. Configure an http(s) endpoint to forwards requests to app.immich:/
> 2. Whitelist the new endpoint as a valid redirect URI with your provider.
> 3. Specify the new endpoint as the Mobile Redirect URI Override, in the OAuth settings.
>
> With these steps in place, you should be able to use OAuth from the [Mobile App](https://immich.app/docs/features/mobile-app) without a custom scheme redirect URI.
info

> Immich has a route (/api/oauth/mobile-redirect) that is already configured to forward requests to app.immich:/, and can be used for step 1.

I think a new https endpoint should be defined on the server that redirects to `audiobookshelf://oauth`, so that this scenario can be supported.

The redirect URI for the mobile app would also have to be changed to point to this new endpoint. Alternatively, the redirect URI for the mobile app could be configurable with a server setting so that users can chose to either use the new https endpoint or `audiobookshelf://oauth` as the redirect URI. This is the approach taken in Immich, though I'm not entirely sure why, since it seems simpler to just always use the HTTPS endpoint. Perhaps it was made configurable in order to avoid introducing a breaking change.

**Comment by Sapd** [comment]
I also thought about implementing  that because it is a workaround for Googles' Policy on non-https URLs, however I did not come around in doing that time wise.

We probably just need a new route `/auth/openid/mobile` and forward the code and state parameter and redirect (and verify the state parameter with the session to be sure before redirecting).

**Comment by advplyr** [comment]
Added in [v2.7.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.0)
