### ISSUE TITLE
[Bug]: Data inconsistencies on landing page (cache not clearing bug)

### ISSUE THREAD

**Issue by lkiesow** [advplyr/audiobookshelf#2392]
### Describe the issue

With 2.6.0, the home page started displaying incorrect data. Books already finished remained in the “Continue Listening” section. Books in “Discover” remained there even after marking them as already finished. This is likely caused by the new caching introduced in #2343. I would rather have correct data than what feels like a barely noticeable speedup.

### Steps to reproduce the issue

1. Go to home page
2. Select first book in “Continue Listening”
3. Mark as read
4. It is still being displayed in “Continue Listening” as half-finished

### Audiobookshelf version

2.6.0

### How are you running audiobookshelf?

Other

**Comment by advplyr** [comment]
Any database update right now clears cache but the upsert hook for sequelize was overlooked which is what the media progress endpoints were using.

**Comment by advplyr** [comment]
Fixed in [v2.7.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.0)

**Comment by andrewakessler** [comment]
Continuing to run into this issue on version 2.8.0. Using ios app. I've tried discarding progress on both the server and the app, as well as checking off "remove from continue listening", but book reappears after refresh.

**Comment by nichwall** [comment]
> Continuing to run into this issue on version 2.8.0. Using ios app. I've tried discarding progress on both the server and the app, as well as checking off "remove from continue listening", but book reappears after refresh. 

You are probably running into a different issue (https://github.com/advplyr/audiobookshelf/issues/2528, but several duplicate issues of the same thing)
