### ISSUE TITLE
Volume boost

### ISSUE THREAD

**Issue by jtechguru1** [advplyr/audiobookshelf#2398]
### Describe the feature/enhancement

Some books are really quiet even with volume am the way up. Can we get a proper volume boost specifically for ranges of different voices. 

If not a general volume boost across the board is better than nothing.

**Comment by advplyr** [comment]
Volume boost in the browser?

**Comment by jtechguru1** [comment]
I apologize. I requested it in the wrong spot, and realized it too late. I
meant that strictly for the apps.
