### ISSUE TITLE
Enhancement request: Add per-user support for book Uploads

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#24]
It would be awesome if it would be possible to upload (maybe drag and drop?) directly into our audiobook library using the browser. And adding permissions for this would be even _better_! That way, our libraries don't get bogged down with poor curators' contributions.

What do you think?

**Comment by advplyr** [comment]
This would be interesting. So you could share your AudioBookshelf server with others who can safely upload their own audiobooks. I like that a lot.
This comes with some challenges though. For example, multiple directory structures are supported, so there would need to be some configuration for how you want uploaded audiobooks to get stored.
There would need to be a form where the uploader enters the authors name and the title, since those are normally retrieved from the directory path during the scan.

**Comment by Kudjo-Grand** [comment]
Well, I've been thinking about this folder structure conundrum and I have a few ideas, motivated by one driving thought.

Ideas
1) you could pick a standard, default, supported folder structure and only use that. (This could also server as a fallback if something is off with
2) (if possible, this is the one I'd love to see) a fancier version could be: you have the user select their default folder structure for uploads in server settings ahead of time. (e.g. author > series > book title. Or: series > author > book title. Etc.)
Both of the above options ensures that the uploading user doesn't get overwhelmed with options. And the server folder organization stays consistent. Now, maybe there could be another, per-user option to allow the permission'd user to change upload folder path. (Override the default setup on the server).

The thought? - Progress trumps perfection. So, it might not be perfect, but it's better than nothing. So just pick something, I guess. Whatever's easiest or sound best for now. If it sucks, we can tweak it later.

What do you think?

**Comment by advplyr** [comment]
I agree with your thought, it's something I struggle with often. Paralysis by analysis.

I took your advice and just pushed an experimental uploader page for root user only. You'll see the upload button in the top right. It accepts audio and image files only and follows 1 folder structure. Once uploaded the audiobook should be automatically added to your collection.

Before taking it out of experimental it needs permissions for other users, error handling, validating file size, and some better solution for the folder structure.

This is v1.1.7

**Comment by advplyr** [comment]
In `v1.1.13` you can now set the upload permission to allow other users to upload audiobooks.
I opted not to include file size validation for now. The only additional validation is to prevent uploading if the directory already exists.
