### ISSUE TITLE
[Bug]: web brower-EDGE shows an error covering the buttons when I use IPV6

### ISSUE THREAD

**Issue by wbhinspector** [advplyr/audiobookshelf#2407]
### Describe the issue

ABS installed on my UNRAID server. I can use IPV6 to visit ABS. But the web browser always shows a net connection error message and covers the control buttons. this error element can't move and don't disappear, but the audiobook can continue playing. I have to use ublock origin to block this element. when I use IPV4 to visit the same server, this error didn't show.

### Steps to reproduce the issue

1. visit the server on IPV6
![image](https://github.com/advplyr/audiobookshelf/assets/39436441/0eb9ea1f-ffa1-4c1f-b07a-b758d6e5b615)

3. after about 1min, the error will be poped.
![image](https://github.com/advplyr/audiobookshelf/assets/39436441/e9a5f266-9206-4b69-920c-477defdb2a46)
![image](https://github.com/advplyr/audiobookshelf/assets/39436441/47f0d381-b5a1-4e70-9401-098c6b339c2b)

### Audiobookshelf version

v2.6.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you allow web sockets?

**Comment by wbhinspector** [comment]
> web sockets

Yes. I mapped the port 80 to 13378. as you see the screenshoot, I can visit the server by [IPV6]:13378, and it can play well, I can hear the book, just pop that error.

**Comment by advplyr** [comment]
The error is that your network is not allowing the web socket connection that the software requires to work properly. I don't know anything about your specific setup to help you but this is an issue on your end and not Abs. I will close this out but if you give more info maybe I can help. There are also a lot of users in Discord that are more knowledgeable than me about networking.
