### ISSUE TITLE
Socket failed to connect

### ISSUE THREAD

**Issue by dietrichmd** [advplyr/audiobookshelf#241]
Fresh install using docker-compose and apache2.  I can access site and login, but everything I try to do is greeted with a Socket Failed to Connect error.

Please advise.

Thanks

**Comment by dietrichmd** [comment]
here is proxypass info

   ProxyPreserveHost On 
    ProxyPass /.well-known/ !
ProxyPass / http://192.168.1.11:4040/
ProxyPassReverse /.well-known/ !
ProxyPassReverse / http://192.168.1.11:4040/
Alias / http://192.168.1.11:4040/
RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/?(.*) "ws://localhost:4040/$1" [P,L]

**Comment by dietrichmd** [comment]
Solved:  proxy_wstunnel_module was not enabled.  For those looking, its a2enmod proxy_wstunnel

**Comment by advplyr** [comment]
Running a reverse proxy? SSL?

**Comment by silentArtifact** [comment]
Yeah, reverse proxy set up through the DMS os itself, same with SSL. I've got the same thing done with Plex and a bunch of other containers, so I'm not sure what I should do with this.

**Comment by advplyr** [comment]
The difference is that audiobookshelf requires a web socket connection, so the reverse proxy config will probably not be the exact same as other media servers. In NGINX proxy manager there is a toggle for web sockets support.
![image](https://user-images.githubusercontent.com/67830747/153679106-b2a7f5b9-0702-48c6-9740-b26b401986e9.png)

**Comment by silentArtifact** [comment]
Agreed. For synology, I followed these steps:

1. Open Control Panel > Application Portal
2. Change to the Reverse Proxy tab
3. Select the proxy rule for which you want to enable Websockets and click on Edit
4. Change to the "Custom Header" tab
5. Click Create > WebSocket
6. Click Save

Now it works!

**Comment by advplyr** [comment]
Awesome, thanks for following up with your steps. It is still a bit messy, but I added your steps for synology and the screenshot for nginx proxy manager in the readme.
https://github.com/advplyr/audiobookshelf/blob/master/readme.md#reverse-proxy-set-up

**Comment by silentArtifact** [comment]
Hey, I should be thanking _you_ for all the work you've done on this! It's exactly what I've been looking for, and I seriously appreciate all your effort!

**Comment by advplyr** [comment]
There is nothing setup for donations at the moment, but I appreciate your support!

**Comment by timbatog** [comment]
Pick a charity maybe? I’ll donate :)


12 Feb 2022, 00:07 by ***@***.***:

**Comment by advplyr** [comment]
Too much pressure! If you follow the project and donate when that need arrives then that would be ideal.

**Comment by adamk33n3r** [comment]
> > Agreed. For synology, I followed these steps:
> > 
> > 1. Open Control Panel > Application Portal
> > 2. Change to the Reverse Proxy tab
> > 3. Select the proxy rule for which you want to enable Websockets and click on Edit
> > 4. Change to the "Custom Header" tab
> > 5. Click Create > WebSocket
> > 6. Click Save
> > 
> > Now it works!
> 
> Not working for https,if I do this for the ios app,only http is working ( that I don't want for outside my network)

Same, I'm trying to use https through reverse proxy (so the app still receives via http) and in the Android app it fails to ping and replaces what I've typed with `http`. It works fine if I connect from `http` but obviously I'd prefer to use `https` for everything.

**Comment by SyndicatedPillbug** [comment]
> Agreed. For synology, I followed these steps:
> 
> 1. Open Control Panel > Application Portal
> 2. Change to the Reverse Proxy tab
> 3. Select the proxy rule for which you want to enable Websockets and click on Edit
> 4. Change to the "Custom Header" tab
> 5. Click Create > WebSocket
> 6. Click Save
> 
> Now it works!

I'm missing the other information for this, though! What ports do I need to use? It's like the first half of the instructions are missing for this reverse proxy thing.

**Comment by onthecliff** [comment]
>     Agreed. For synology, I followed these steps:
> 
>     1. Open Control Panel > Application Portal
> 
>     2. Change to the Reverse Proxy tab
> 
>     3. Select the proxy rule for which you want to enable Websockets and click on Edit
> 
>     4. Change to the "Custom Header" tab
> 
>     5. Click Create > WebSocket
> 
>     6. Click Save
> 
> 
> Now it works!

Thank you this worked immediately!

**Comment by coracoo** [comment]
great ,It work .

**Comment by guhanmathi** [comment]
> The difference is that audiobookshelf requires a web socket connection, so the reverse proxy config will probably not be the exact same as other media servers. In NGINX proxy manager there is a toggle for web sockets support. ![image](https://user-images.githubusercontent.com/67830747/153679106-b2a7f5b9-0702-48c6-9740-b26b401986e9.png)

This help my service running through nginx

**Comment by m4tz3** [comment]
![grafik](https://github.com/advplyr/audiobookshelf/assets/6939489/11a558e6-63d8-4b67-b27f-f20da4c7ede6)
DSM Changed a bit, could somebody share some screenshots, for me it's still not running

**Comment by robinjoseph08** [comment]
For posterity, just wanted to recount my experience here too, in case it helps someone else. I'm using a Synology NAS with DSM 7.2. I have ABS deployed using Container Manager, and it all works fine on my local network. I originally had ABS exposed publicly using Web Station (since that's also how I have Jellyfin exposed), but even though I could load it using my domain, it would always show the "Socket failed to connect" error.

Following these instructions, I deleted the entry for ABS in Web Station (since it doesn't seem like Web Station really has support for websockets yet) and instead went to the Reverse Proxy settings (now found in Control Panel > Login Portal > Advanced), and added entries for both HTTP and HTTPS for ABS, making sure to add the Websocket custom headers mentioned in [this comment](https://github.com/advplyr/audiobookshelf/issues/241#issuecomment-1036732329). After doing that, I was able to get ABS to connect to the socket without issue!

One thing I wanted to note though is that for some reason, if I try to access my domain when I'm on my local network, it's painfully slow, sometimes it times out, and the socket connection is very spotty. If I switch to just using the local IP of my NAS, everything is snappy and reliable again, and if I connect to the domain from a different network, it's also snappy. I mention this since it was messing up my testing a little bit because even after I fixed things with the Reverse Proxy settings, using my domain on my local network was still having issues, so I had to test it on a different network to see that it was fixed.

**Comment by rpgdev** [comment]
> The difference is that audiobookshelf requires a web socket connection, so the reverse proxy config will probably not be the exact same as other media servers. In NGINX proxy manager there is a toggle for web sockets support. ![image](https://user-images.githubusercontent.com/67830747/153679106-b2a7f5b9-0702-48c6-9740-b26b401986e9.png)

This worked! Needed to wait a few minutes for the setting to take effect and audiobookshelf to tell me that it was able to connect the socket.

**Comment by loganank** [comment]
If using typical nginx and not nginx proxy manager, adding the following in the location portion of my .conf file did it.

```
 location / {
        proxy_pass http://192.168.1.mylocalip:13378;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```

**Comment by kanine** [comment]
Thanks @loganank  these were the lines that made the difference for me:

`        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
`

**Comment by hjalte81** [comment]
> The difference is that audiobookshelf requires a web socket connection, so the reverse proxy config will probably not be the exact same as other media servers. In NGINX proxy manager there is a toggle for web sockets support. ![image](https://user-images.githubusercontent.com/67830747/153679106-b2a7f5b9-0702-48c6-9740-b26b401986e9.png)

Thank you. That worked.

**Comment by lakestonelabs** [comment]
For those using opnsense with the nginx plugin, I could not get my android client to play media.  I could connect to the audiobookshelf server and see the bookshelf listing but when I pressed "Stream" I would get an error.  What ended up being the root cause for me is that the opnsense nginx plugin automatically has a preset list of bot user agents applied to its auto-ban list.  The 'okhttp' http client is being used by audiobookshelf client apps and this was on the bot list for auto-banning.  As soon as I removed this from the bot list in the nginx pluygin and reloaded nginx, everything started working.

**Comment by rpgdev** [comment]
@lakestonelabs thanks for sharing.. I'm setting up opnsense as we speak.

**Comment by kchism2020** [comment]
> The difference is that audiobookshelf requires a web socket connection, so the reverse proxy config will probably not be the exact same as other media servers. In NGINX proxy manager there is a toggle for web sockets support. ![image](https://user-images.githubusercontent.com/67830747/153679106-b2a7f5b9-0702-48c6-9740-b26b401986e9.png)

This fixed the issue for me, nginx rpm

**Comment by MilesTEG1** [comment]
Hello,

> I'm having this issue, but _only_ when attempting to stream off the local network. Everything else works. It's running from Docker on a Synology NAS.

I'm exprimenting the same issue, and like @silentArtifact I only have this message when I'm on my LAN network:
<img width="1290" height="204" alt="Image" src="https://github.com/user-attachments/assets/fb4bb471-9880-4879-8102-6ba29ff87512" />

When I accessed from outside, so from internet, websocket is connected:
<img width="1290" height="191" alt="Image" src="https://github.com/user-attachments/assets/ee859549-9a43-4e78-ad09-2e5c704fe14b" />

But for me, Audiobookshelf is installed in docker inside a VM debian 13 (proxmox).

When I use SWAG as reverse proxy, I get the "Websocket failed to connect" message.
**I also have AdGuardHome as DNS server inside my LAN, so I rewrite my domain name to point the reverse proxy.**

<details>
  <summary>my audiobbokshelf.conf file</summary> 

  ```nginx
  ## Version 2025/07/18
# make sure that your audiobookshelf container is named audiobookshelf
# make sure that your dns has a cname set for audiobookshelf

server {
    listen 443 ssl;
    listen 443 quic;
    # listen [::]:443 ssl;
#    listen [::]:443 quic;

    server_name my_audiobook_subdomaine.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 10240M;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    #include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    #include /config/nginx/authentik-server.conf;

    # enable for Tinyauth (requires tinyauth-location.conf in the location block)
    #include /config/nginx/tinyauth-server.conf;

    # GeoIP Blocking with Maxmind Docker-MOD
    include /config/nginx/maxmind-geoblock_and_LAN.conf;

    # Restrict access to some IPs only (LAN & VPNs)
    # include /config/nginx/ACL.IP-LAN.conf;

    # Log général pour tout le reste (optionnel)
    access_log /config/log/nginx/access.log;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        #include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        #include /config/nginx/authentik-location.conf;

        # enable for Tinyauth (requires tinyauth-server.conf in the server block)
        #include /config/nginx/tinyauth-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.2.141;
        set $upstream_port 10880;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
  ```
 
</details>

---

But now, I set up a new reverse proxy with NPMplus:

<img width="1021" height="605" alt="Image" src="https://github.com/user-attachments/assets/ffd6b768-0982-4926-b831-1ceed7a5fc52" />

And now, I don't have anymore the message about the websocket failed.


@advplyr Could you add NPMplus configuration in the doc?
