### ISSUE TITLE
[Bug]: Can't write podcasts to folder

### ISSUE THREAD

**Issue by flintstones-fred** [advplyr/audiobookshelf#2410]
### Describe the issue

Using Proxmox privilaged LXC (debian 12 based) for running Audiobookshelf. 
After creating the LXC, mounting the disk on the LXC (e.g. `pct set 122 -mp1 /mnt/USBHDD,mp=/mnt/USBHDD`

This drive has my audiobooks and would like to have podcasts on the same drive. However, when I create a podcast library and try to add a podcast, I get an error
`[PodcastController] Failed to ensure podcast dir "/mnt/USBHDD/Podcasts/Self-Hosted" Error: EACCES: permission denied, mkdir '/mnt/USBHDD/Podcasts/Self-Hosted'`

From the LXC commandline, I am able to access mkdir to create directories just fine. 

### Steps to reproduce the issue

1. Create a privilaged Proxmox LXC
2. Install Audiobookshelf
3. Create a mount point within LXC that points to the folder where you want to store your podcast. 
4. Try to create a podcast library in Audiobookshelf, and add a podcast show

### Audiobookshelf version

2.6.0

### How are you running audiobookshelf?

Debian/PPA

**Comment by Hallo951** [comment]
I had the same problem recently. This is not a bug in Abs. It is due to the authorisation of the folder in which you want to save the podcast. This must be in the same group as Abs itself. If you use Abs natively under Linux (without Docker), Abs has the group "audiobookshelf". This means that your podcast folder must have the following authorisation: user:audiobookshelf. It worked for me with this...

**Comment by flintstones-fred** [comment]
> I had the same problem recently. This is not a bug in Abs. It is due to the authorisation of the folder in which you want to save the podcast. This must be in the same group as Abs itself. If you use Abs natively under Linux (without Docker), Abs has the group "audiobookshelf". This means that your podcast folder must have the following authorisation: user:audiobookshelf. It worked for me with this...

Thank you. So, if I understand correctly, even though I am operating as root in the LXC shell and installed audiobookshelf directly using apt, it doesn't have write permissions. Okay, that makes a lot of sense. For changing the permissions of the folder, do I change these permissions from the LXC shell or from the Proxmox host shell?

**Comment by flintstones-fred** [comment]
Thank you @Hallo951 . I can confirm that after assigning the correct permissions for the user audiobookshelf, this problem disappears. I am closing with this comment.

**Comment by indiependente** [comment]
Hey @flintstones-fred would you mind posting the command you used here for future reference? I can see that you're not the only one who experienced this issue. Thanks!

**Comment by flintstones-fred** [comment]
> Hey @flintstones-fred would you mind posting the command you used here for future reference? I can see that you're not the only one who experienced this issue. Thanks!

In my case, since the sole purpose of the LXC was audiobookshelf and I don't expose my audiobookshelf instance externally, I added the "user" audiobookshelf to the root group. This enabled all the relevant access permissions. This can be done by editing the /etc/passwd file and modifying the UID and GID of the user "audiobookshelf" to those of root (0:0). I hope this is helpful.
