### ISSUE TITLE
[Bug]: Auther Narrator being added as an author.

### ISSUE THREAD

**Issue by HappyPants9999** [advplyr/audiobookshelf#2418]
### Describe the issue

Recently when adding books the narrator gets added as a coauthor. In some cases the narrator and author gets mashed together as a single name. Example of this is I added Book of the dead 2 by RinoZ and read by Phil Thron. Metadata set by mp3 tag this as always and file copied into file structure books/RinoZ/Book of the dead/2 - Book of the Dead 2 Sacrifice {Phil Thron}/Book of the Dead 2 Sacrifice.m4b. In Audiobookshelf author was added as Phil Thron RinoZ. Single incorrect author. This same behavior happens with the primal hunter books by Zogarth. All other books seem to add the actual author and the narrator(s) individually. This week I had to completely reinstall my server and when it rebuilt the library it did this for every single book. All files had been processed correctly in the past and no changes were made to the library files and file structure.  Currently running version v2.6.0 I first noticed this with some books I added last month. 

### Steps to reproduce the issue

1. Add a book

### Audiobookshelf version

v2.6.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Discussed in Discord

**Comment by windsifter** [comment]
Also experiencing this. I spent a good 10 minutes searching Discord but wasn't able to find anything. Any links appreciated

**Comment by advplyr** [comment]
The narrator name is in the album ID3 meta tag on the audio file https://www.audiobookshelf.org/docs#book-audio-metadata
