### ISSUE TITLE
[Docker] Feature Request: Add the ability to set the UID/GID of the docker container

### ISSUE THREAD

**Issue by tvories** [advplyr/audiobookshelf#243]
I have a shared directory for my book files.  I would love to be able to set the docker container to run as a specific UID/GID so I can match my directory permissions for my central book storage.

I know the [LinuxServer](https://github.com/linuxserver/docker-bookstack#docker-compose-recommended-click-here-for-more-info) containers offer this ability, but I don't know how to add this to the docker container.

**Comment by advplyr** [comment]
You can set them when running the docker container.

```
docker run -d \
    -e AUDIOBOOKSHELF_UID=99
    -e AUDIOBOOKSHELF_GID=100
    -p 1337:80 \
    -v </path/to/audiobooks>:/audiobooks \
    -v </path/to/config>:/config \
    -v </path/to/metadata>:/metadata \
    --name audiobookshelf \
    --rm advplyr/audiobookshelf
```

The docs still have a way to go

**Comment by advplyr** [comment]
Just updated the docs on the site https://www.audiobookshelf.org/install#docker
Let me know how it goes

**Comment by tvories** [comment]
Thanks for the info!  I was digging around for that.  For my own knowledge, where is that set in the code to respect that env?

**Comment by advplyr** [comment]
At the entry point https://github.com/advplyr/audiobookshelf/blob/master/index.js#L21

The only place UID/GID are used right now is when uploading audiobooks through the upload form, and when backups are created. This will need to be extended to include setting the file owner for cache and cover metadata as well.
