### ISSUE TITLE
[Bug]: deleted podcast episodes are downloaded again

### ISSUE THREAD

**Issue by amatriain** [advplyr/audiobookshelf#2432]
### Describe the issue

When an episode from a podcast is deleted, audiobookshelf downloads it again and sends a new episode notification. There seems to be no way to permanently delete an episode, the delete episode feature is useless for podcasts with scheduled automatic episode downloads.

### Steps to reproduce the issue

1. Go to any podcast with scheduled automatic episode downloads (e.g. every hour)
2. Click on the delete button (X icon) in any episode
3. Check the "Hard delete file" checkbox
4. Click on "Remove" button

Expected result: episode is deleted and it never appears again in audiobookshelf.

Actual result: episode is deleted, but next time the podcast automatically downloads episodes, it detects the deleted episode as if it was a new episode and downloads it again (sending an apprise notification if configured).

### Audiobookshelf version

2.6.0

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/836

**Comment by amatriain** [comment]
Since there's already an open feature request for this, I guess this ticket can be closed.
