### ISSUE TITLE
[Bug ?]: only show first audio book when in a subfolder

### ISSUE THREAD

**Issue by Beulu** [advplyr/audiobookshelf#2433]
### Describe the issue

Hi !

Very amazing software !

Got an issue : i've put several audiobooks in a folder, but ABS only show me the first audio book (but see all others in "files", and/or doesn't transform them in chapters, playlist or serie. Maybe I misunderstood something ?

### Steps to reproduce the issue

1. put several audiobooks in a folder

### Audiobookshelf version

2.6.0

### How are you running audiobookshelf?

Docker

**Comment by Beulu** [comment]
OK, my bad, I found how to tell ABS to make chapters from each files. ^^

BUT chapters don't take cover and titles are filename and not title from idtag

**Comment by advplyr** [comment]
Hey I believe this is a misunderstanding. Your question is answered in the FAQ here https://www.audiobookshelf.org/faq#why-are-multiple-books-showing-as-the-same-book

The directory structure to use is also in the docs
