### ISSUE TITLE
[Enhancement]: show categories

### ISSUE THREAD

**Issue by Beulu** [advplyr/audiobookshelf#2434]
### Describe the feature/enhancement

Is there a way to have lines for "last adds" and "discover" but for each categories and/or series, with extended line as Netflix or Prime ?

Categories doesn't appear in the library

Is it possible to add an icon and/or color for each line title ?

**Comment by advplyr** [comment]
Is this the same as https://github.com/advplyr/audiobookshelf/issues/1241?

**Comment by Beulu** [comment]
yes, sort of. :)

**Comment by advplyr** [comment]
Duplicate of #1241
