### ISSUE TITLE
[Enhancement]: Add GraphicAudio as a match provider

### ISSUE THREAD

**Issue by almog-t** [advplyr/audiobookshelf#2435]
### Describe the feature/enhancement

Some of my audiobooks were bought from GraphicAudio, would be great if we could get metadata directly from their website, as more often than not audible does not contain the correct metadata for the dramatized edition of the audiobook.

**Comment by advplyr** [comment]
Yeah this was looked into last year and there was no public API so we can't use it as a metadata provider. Once there is one we can add it

**Comment by binyaminyblatt** [comment]
I built a custom metadata provider

https://github.com/binyaminyblatt/graphicaudio_scraper
https://graphicaudio-api.endl.site/
