### ISSUE TITLE
aac support?

### ISSUE THREAD

**Issue by felixbro** [advplyr/audiobookshelf#244]
Sorry if im blind and could not find anything about it, its late and i finaly got the shelf working. so is there, or will there be aac-audio support?
some of my audiobooks are in aac, do i have to wait, or convert them?
thanks alot!

**Comment by advplyr** [comment]
I just added .aac audio files to the list of support audio files in `v1.6.43`.

It was just overlooked, if you update and scan again it should pull those in.

**Comment by felixbro** [comment]
ok, nice. it works, just had to restart the docker! thanks.
