### ISSUE TITLE
[Bug]: Cover Size Widget is not visible when the Stream Container is open

### ISSUE THREAD

**Issue by GetOutOfMyBakery** [advplyr/audiobookshelf#2443]
### Describe the issue

The cover size widget is visible when no stream container is open:
<img width="112" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/12701930/84d92735-ee1b-4036-9f5e-615032074f43">

When the scream container is opened, the button is hidden in the background:
<img width="184" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/12701930/27905b49-d694-439f-b7f2-410386376894">

Changing it's z-index, shows that it's still there, but in the wrong position:
<img width="127" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/12701930/440e9ccb-3059-43d6-8250-8a68ed861195">

### Steps to reproduce the issue

1. Go to the Library, cover size widget is visible
2. Start streaming, the stream container opens and hides the cover size widget

### Audiobookshelf version

v2.6.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.7.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.0)
