### ISSUE TITLE
[Enhancement]: Add tooltip/hover text for book titles in library view (for all books, or only when display is truncated) 

### ISSUE THREAD

**Issue by methosinhiding** [advplyr/audiobookshelf#2451]
### Describe the feature/enhancement

When viewing books in the library view, it would be great to be able to see the full name of a long-titled book without having to open its specific page.
![292934133-011c1043-b815-481f-ab00-bdd6888930ee](https://github.com/advplyr/audiobookshelf/assets/146374353/5cc75267-dabf-401c-9b1f-567c0a0bf789)

When hovering the mouse over the title of a book item in library view, show a tooltip/hover-text of the full book name.
It may make sense to only display the requested tooltip/hover text if the book currently being moused over is actually truncated, but it would be understandable if that is burdensome to determine.

**Comment by advplyr** [comment]
Added in https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.2
