### ISSUE TITLE
[Enhancement]: Add a button for each episode on the "latest" page to add to the playlist directly.

### ISSUE THREAD

**Issue by edersong** [advplyr/audiobookshelf#2455]
### Describe the feature/enhancement

Add a button for each episode on the "latest" page to add to the playlist directly instead of entering on each episode to add it to a playlist.

**Comment by advplyr** [comment]
When you say "the playlist" you are talking about playlists and not the player queue, right?

**Comment by edersong** [comment]
Yes, that is.

**Comment by advplyr** [comment]
Added in https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.2
