### ISSUE TITLE
[Enhancement]: 'Full' backup option

### ISSUE THREAD

**Issue by Yehuda-Bergstein** [advplyr/audiobookshelf#2458]
### Describe the feature/enhancement

First off, great application and thanks for all the work done! 
I really like the backup feature and how it's implemented, and was wondering would it be possible to do a 'full' backup that includes all the media files? (mp3,pdf,epub etc)

**Comment by nichwall** [comment]
It would probably be better for you to manually back up your media files or use another automated tool. The media library can easily exceed hundreds of GB and even TB (but I'm assuming you don't have a very large library based on the request).

Other media servers do not back up the media files and only back up the associated database files.

**Comment by advplyr** [comment]
This is outside the scope of the application because of what @nichwall said. This is better suited for dedicated software
