### ISSUE TITLE
[Bug]: Playback speed in firefox (121.0) remains at 1.0 despite changing to higher speed

### ISSUE THREAD

**Issue by samtrek** [advplyr/audiobookshelf#2462]
### Describe the issue

Changing the playback speed in firefox (121.0) on archlinux does not actually change the speed, no matter the level to which the playback speed is changed to the actual playback speed remains at 1.0. However, the playback speed changes in the android app. I have not tried it on chrome or other browser to see if it is only peculiar to firefox.

### Steps to reproduce the issue

1. Start the server
2. open the link in firefox in archlinux
3. play a podcast or audiobook
4. change the playback speed
5. the playback speed changes but audio playback speed remains at 1.0

### Audiobookshelf version

2.7.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I tested this in Firefox on Windows and a bunch of other browsers but don't have that specific browser on archlinux.
This may be specific to the audio file, can you check the dev console logs to see if it is throwing an error when trying to change the playback speed?

**Comment by KaiStarkk** [comment]
Worth checking in private browsing with all add-ons disabled - might be an extension conflict. (Like VideoSpeedController, StreamKeys, or similar popular ones out there).

**Comment by samtrek** [comment]
Thank you @KaiStarkk for the suggestion, the main cause was a tampermonkey HTML5 script, once it was disabled the playback speed started responding.
Will be closing the issue as been resolved.
