### ISSUE TITLE
[Bug]: Playlist navigation entry not visible on mobile website

### ISSUE THREAD

**Issue by MatrixRetoastet** [advplyr/audiobookshelf#2469]
### Describe the issue

Hi,

I created a playlist in Audiobookshelf and added some audiobooks to it. In the App and on the desktop website of Audiobookshelf the Playlist navigation entry is displayed.
When I use the mobile website on my phones (Samsung Galaxy S23 Ultra, iPhone 13) the Playlist navigation entry is not visible.
I have "Home", "Library", "Series", "Collections" and "Authors".

Have a great new year =)

### Steps to reproduce the issue

1. Create Playlist in Audiobookshelf
2. Navigation entry "Playlists" is displayed in the App and on the desktop version of the website.
3. Switch to / Use mobile version of the website and the "Playlists" navigation entry is not visible anymore

### Audiobookshelf version

2.7.0

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Thanks for reporting it. You can fix the playlist tab not showing up by removing the server connection in the app and then sign in again. The issue right now is creating the first playlist if you are already signed in to the app.

**Comment by nichwall** [comment]
Oh, apologies. I misread "mobile site" as "mobile app".

**Comment by advplyr** [comment]
Fixed in [v2.7.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.1)
