### ISSUE TITLE
Bug: Reload site change cover style

### ISSUE THREAD

**Issue by mx03** [advplyr/audiobookshelf#247]
If the site is reloaded within a series or filtered library (Library without filter works) the cover style changes.
![image](https://user-images.githubusercontent.com/1390929/146807008-63ec7a4b-6217-4f3c-96c9-cd95a054e66c.png)

Reloading
![image](https://user-images.githubusercontent.com/1390929/146807040-66a7d31e-9a15-4033-8ac8-907f485478a4.png)

**Comment by advplyr** [comment]
This was a race condition, should be fixed in `v1.6.46`, but re-open if not.
Thanks for reporting these issues!
