### ISSUE TITLE
[Bug]: Sorting books by duration bugged

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#2470]
### Describe the issue

Arranging books by durations looks to be bugged. If you sort them by longest->shortest it seems to work, but other way around it looks really strange.

These are the ten longest books:
![image](https://github.com/advplyr/audiobookshelf/assets/4344284/0a0d0ca0-a8ac-487a-b096-6f98531eafa6)

These are supposed to be the ten shortest books:
![image](https://github.com/advplyr/audiobookshelf/assets/4344284/2b95284b-7d97-4cb5-8245-85f503fbbfad)

### Steps to reproduce the issue

1. Open up library
2. Order by Duration, ascending

### Audiobookshelf version

2.7.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not able to reproduce this. Can you check that the durations in the audio tracks table for some of those match up with what they actually are?
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/6490649c-b939-45a9-8a95-f79aeeb90c64)

**Comment by ScuttleSE** [comment]
They seem to match 
![image](https://github.com/advplyr/audiobookshelf/assets/4344284/2aee7f0b-8b46-4934-9206-9b88f1e462fa)
![image](https://github.com/advplyr/audiobookshelf/assets/4344284/718d7cd6-4b53-45af-b8eb-d5ec1775db77)
![image](https://github.com/advplyr/audiobookshelf/assets/4344284/60847001-5466-4680-b103-ef034ca73058)

**Comment by advplyr** [comment]
Did this ever get worked out?
