### ISSUE TITLE
[Bug]: Listen history not work

### ISSUE THREAD

**Issue by mafian021** [advplyr/audiobookshelf#2483]
### Describe the issue

I have Audiobookshelf installed on an ubuntu server. I have the library created and the user as root. Now I created a second user that can see the library and can play it which works. But the listening history is not saved, i.e. after closing the playback, the listened item is not created on the home page for this user, and when I start the listened book, it starts again from the beginning. In the history for this user, it still shows 0 min for books listened to.
As a root user, everything works fine for me. Do you know where the problem could be? Unless something needs to be set elsewhere, but that doesn't seem likely to me. It doesn't matter what I enable in the settings for the user, or if he is root, user or guest.

### Steps to reproduce the issue

1. I create a second root user ( user, host )
2. I will give him all rights to the library
3. I start playing the audiobook
4. I turn off playback
5. the listening tab will not be created
6. there is no listening procedure in the statistics
7. everything works fine for the first root user

### Audiobookshelf version

2.7.1

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Is this still an issue? When you first start playing an audiobook the first progress sync won't happen for 30 seconds, so you have to listen for 30 seconds for the audiobook to show progress.
I'll re-open this if there is a bug here but I think the case is you didn't listen for 30 seconds
