### ISSUE TITLE
[Bug]: Double quotes in Podcast names are not escaped when exported to OPML

### ISSUE THREAD

**Issue by FreedomBen** [advplyr/audiobookshelf#2487]
### Describe the issue

When one of the podcasts you are subscribed to has double quotes in the title (and probably other fields that get written into attributes), the current exporter does not properly escape them, leading to invalid OPML/XML. 

### Steps to reproduce the issue

1. Add a podcast with double quotes in the title.  Example '"Your Welcome" with Michael Malice':  https://www.podcastone.com/podcast?categoryID2=2232
2. Export OPML:  From podcasts library, click 3-dot menu, select Export OPML
3. You can use `xmllint "<filename>.opml"` to verify

To escape correctly, double quotes going inside an attribute should be replaced with `&quot;`

Example incorrect line (currently produced):

```xml
<outline type="rss" text=""YOUR WELCOME" with Michael Malice" title=""YOUR WELCOME" with Michael Malice" xmlUrl="https://www.podcastone.com/podcast?categoryID2=2232" description="Michael Malice brings his unique perspective – and plenty of sick burns – as he discusses everything from north Korea to American politics and culture with a bevy of guests." language="en-us"/>
```

Example correct line:

```xml
<outline type="rss" text="&quot;YOUR WELCOME&quot; with Michael Malice" title="&quot;YOUR WELCOME&quot; with Michael Malice" xmlUrl="https://www.podcastone.com/podcast?categoryID2=2232" description="Michael Malice brings his unique perspective &#x2013; and plenty of sick burns &#x2013; as he discusses everything from north Korea to American politics and culture with a bevy of guests." language="en-us"/>
```

### Audiobookshelf version

2.7.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.2
