### ISSUE TITLE
[Bug]: Unable to locate package audiobookshelf

### ISSUE THREAD

**Issue by pradeda** [advplyr/audiobookshelf#2492]
### Describe the issue

On Raspi 4 using the second entry in the installation guide for linux ( debian etc )

After activating the repository and running the sudo apt install audiobookshelf it says its unable to locate package.

The package is present after running the apt update:

Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 https://advplyr.github.io/audiobookshelf-ppa ./ InRelease

However even going to https://advplyr.github.io/audiobookshelf-ppa/ gives a 404 is this ok?

### Steps to reproduce the issue

1. Follow the instructions from https://www.audiobookshelf.org/docs/#linux-install-deb
2. Try to run sudo apt install audiobookshelf 

### Audiobookshelf version

v2.7.1.

### How are you running audiobookshelf?

Debian/PPA

**Comment by pradeda** [comment]
Worked perfectly using the docker container install.

**Comment by Gummibeer** [comment]
Even if docker works - how can I/we fix the `apt` command? 🤔 Does it support Ubuntu 22?

```
$ uname -a
Linux 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:37:39 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```
```
$ sudo apt install audiobookshelf
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package audiobookshelf
```

**Comment by heinrich-k** [comment]
I have the same issue running raspberryOS.

**Comment by heinrich-k** [comment]
Switching the contents of the .list file to 
deb https://raw.githubusercontent.com/advplyr/audiobookshelf-ppa/refs/heads/master ./
seems to have worked, although there isn't an arm64 variant, only amd64
