### ISSUE TITLE
[Bug]: Server crashes without error when querying API for (non-existant) author image

### ISSUE THREAD

**Issue by LeoKlaus** [advplyr/audiobookshelf#2493]
### Describe the issue

Using the ghcr.io/advplyr/audiobookshelf Docker image, the server crashes without warning or logs when querying /api/authors/<id>/image

### Steps to reproduce the issue

1. curl http(s)://<server-ip>:<port>/api/authors/<some-id>/image

### Audiobookshelf version

v2.7.1

### How are you running audiobookshelf?

Docker

**Comment by LeoKlaus** [comment]
Doesn't happen with raw parameter enabled, so I guess the error occurs somewhere in the [CacheManager](https://github.com/advplyr/audiobookshelf/blob/master/server/managers/CacheManager.js#L132)

**Comment by advplyr** [comment]
I'm not able to reproduce this. Can you be more specific about what you are doing to cause the crash?
