### ISSUE TITLE
[Enhancement]: Sort series alphanumerically instead of alphabetically.

### ISSUE THREAD

**Issue by ElDubsNZ** [advplyr/audiobookshelf#2495]
### Describe the feature/enhancement

Currently, series are listed alphabetically, so you get this:
Bernice Summerfield - Series 1
Bernice Summerfield - Series 10
Bernice Summerfield - Series 11
Bernice Summerfield - Series 2
Bernice Summerfield - Series 20
etc...

If ordering of series was set to be alphanumeric, it would resolve this issue and series would look as intended.

**Comment by nichwall** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2281

**Comment by ElDubsNZ** [comment]
Closed as duplicate of #2281 .
