### ISSUE TITLE
users' "is active" status seems to be ignored at this time.

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#25]
I noticed that the "active" toggle switch doesn't seem to be doing anything yet. Meaning, I am able to log in (with the proper credentials) to a user even if they are not marked as an "active" account.

Hopefully, that was helpful.

What do you think?

P.S. I had a much larger report that I deleted because all seems to be fixed when I thought to create a new user on the current version of the app and test with that. (All my previous tests were with users created on an older version)

**Comment by advplyr** [comment]
I added the isAdded flag but didn't get around to implementing it. I just added it for v1.1.3
