### ISSUE TITLE
[Bug]: TestFlight beta is full 

### ISSUE THREAD

**Issue by Dag0n** [advplyr/audiobookshelf#2501]
### Describe the issue

TestFlight beta is full

### Steps to reproduce the issue

1. Visit https://testflight.apple.com/join/wiic7QIW, see text. 

### Audiobookshelf version

v2.7.1

### How are you running audiobookshelf?

Built from source

**Comment by DieselTech** [comment]
So what is the bug?

**Comment by advplyr** [comment]
Correct, Apple has a 10k limit on the number of beta testers we can have that they will not increase. You can run the app from source or you can sideload it. You can also use the web client and save it to your homescreen as a progressive web app. You can join the Discord or Matrix server to keep up-to-date.

**Comment by tedstriker** [comment]
Is there a roadmap when the usage of testflight will end and the app will be moved to the regular appstore?

**Comment by vonProteus** [comment]
when are you planning a normal publication in the store?
what's stopping you from doing it now?

**Comment by nichwall** [comment]
https://github.com/advplyr/audiobookshelf-app/issues/541
