### ISSUE TITLE
[Enhancement]: Add book covers into RSS feeds generated from collections and series 

### ISSUE THREAD

**Issue by PulsarFTW** [advplyr/audiobookshelf#2508]
### Describe the feature/enhancement

When opening an RSS feed of a series the overall image of the RSS feed is the ABS logo
`<itunes:image href="https://audiobookshelf.myserverserver.com/Logo.png"/>`
 and individual entries do not have any other associated image. 

Suggestion:
Each entry in the RSS feed would have the book cover as the associated image for that "episode".
I am unsure how best to handle the main podcast image? Prehaps the ABS logo could remain there as a placeholder.

**Comment by nichwall** [comment]
This was brought up again in https://github.com/advplyr/audiobookshelf/issues/3193 and is fixed for the next release.

**Comment by advplyr** [comment]
Thanks I missed this one. Fixed in 2.12.0
