### ISSUE TITLE
Modal is closed if mouse is released outside of the modal

### ISSUE THREAD

**Issue by mx03** [advplyr/audiobookshelf#251]
If you select text in an input inside of a model, and mark outside of the model it closes. (Mostly within the edit window)

Example:
https://i.stack.imgur.com/CugGW.gif

Relevant:
https://github.com/ndelvalle/v-click-outside/issues/450
https://stackoverflow.com/questions/55732804/modal-is-closed-when-cursor-is-released-outside-the-modal-after-chrome-update-a

**Comment by advplyr** [comment]
Thanks for sharing that solution, I did something similar to fix in `v1.6.47`
