### ISSUE TITLE
[Bug]: Multiple progress losses again

### ISSUE THREAD

**Issue by 0verEngineer** [advplyr/audiobookshelf#2512]
### Describe the issue

I have an audiobook and i listen to it on the phone and sometimes on the pc, i lost the progress multiple times when switching from pc back to mobile (don't really know if it also happens the other way around)

### Steps to reproduce the issue

1. listen on mobile
2. stop listen and switch to the pc to listen (hopefully there is no progress loss here)
3. stop listen on pc and switch back to mobile
4. progress was lost

### Audiobookshelf version

v2.7.1

### How are you running audiobookshelf?

Docker

**Comment by 0verEngineer** [comment]
Addition: I just wanted to continue listen to the book on pc and the progress was lost completely, it started from scratch
Then i opened the app on mobile and waited till the audiobook is loaded from the server and it was correctly loaded with my correct progress. This is not a downloaded audiobook

**Comment by advplyr** [comment]
I suspect the issues you are having in #2500 are related to this and I'm not sure what the actual problem is with your setup.

**Comment by 0verEngineer** [comment]
I had the progress losses multiple times woth the last two audiobooks i listened since uodating to the current version, one of the two audiobooks did not have the filesystem issue and this issue did only happen once.
Given the fact that the progress losses happened before and after the filesystem issue i don't think it is related.

If i have another issue i will setup a second audiobookshelf instance on a different machine with a different filesystem and try it there.

Thanks a lot
