### ISSUE TITLE
[Bug]: Library name change doesn't work

### ISSUE THREAD

**Issue by gitdeath** [advplyr/audiobookshelf#2513]
### Describe the issue

Changing the library name will save, but then opening a new webgui session will showcase the original name.

### Steps to reproduce the issue

1. Edit an existing library.
2. Change the name
3. Hit Save
4. Notice the library name is changed in the top left.
5. Close browser.
6. EDIT: Some period of time passes - I don't know what triggers / else needs to go here..
7. Open a new browser.
8. Notice the library name is the original in the top left.

### Audiobookshelf version

2.7.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not able to reproduce this. If I had to guess the server is crashing OR something is wrong with the `/config` mapping in your docker container.
Can you check the logs and share your docker container setup.

**Comment by gitdeath** [comment]
So it doesn't appear to happen every time I reopen the webGUI, so my original steps are wrong, but for some reason it is reverting over some period of time. I only have one library and from the logs showing the library scans I try the name change a couple different times and at some point in the future it will revert.

[logs-abs.txt](https://github.com/advplyr/audiobookshelf/files/13932241/logs-abs.txt)

**Comment by advplyr** [comment]
This is most likely then an issue with how you mapped the `/config` directory that contains the database in your docker container. Can you share your docker config? Can you find the `absdatabase.sqlite` file on your file system that contains the database?

**Comment by gitdeath** [comment]
I'll close this as it appears the last time I changed it it hasn't switched back
