### ISSUE TITLE
[Enhancement]: Higher resolution covers in PWA while on the lock screen on iOS

### ISSUE THREAD

**Issue by ipcintron** [advplyr/audiobookshelf#2514]
### Describe the feature/enhancement

I noticed on the lock screen on iOS, my audiobook cover is lower res than when I have the ABS PWA app open. Example (this cover is 2400x2400 res):
![IMG_1742](https://github.com/advplyr/audiobookshelf/assets/15165416/634201db-dc09-48f1-8e12-edc052d92d27)
![IMG_1743](https://github.com/advplyr/audiobookshelf/assets/15165416/676028d5-f1fe-4769-8298-a6c04cafc21e)

**Comment by ipcintron** [comment]
TEST

**Comment by ipcintron** [comment]
This issue still exists. It appears as on the audio bookshelf the artwork is lower res until you press the album cover. I think the album cover being passed to the lock screen is the low res one.

**Comment by advplyr** [comment]
Added in [v2.8.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.0)
