### ISSUE TITLE
[Enhancement]: Better support for Ultrawide monitors on home page

### ISSUE THREAD

**Issue by ipcintron** [advplyr/audiobookshelf#2518]
### Describe the feature/enhancement

Ultrawide monitors could show more entries of audiobooks/authors. There is a lot of space on the right. 
I am using a 21:9 aspect ratio 3440x1440 resolution monitor. While this screenshot is from MacOS, I was able to replicate this on Windows:
![Screenshot 2024-01-16 at 4 41 17 PM](https://github.com/advplyr/audiobookshelf/assets/15165416/4dbd3831-a279-438e-b3df-917e798fc045)

**Comment by glorenzen** [comment]
This is due to the default max of 10 items when the personalized shelves are pulled from the database.

Maybe it can be increased to higher by default?
