### ISSUE TITLE
[Enhancement]: Higher resolution PWA app icon

### ISSUE THREAD

**Issue by ipcintron** [advplyr/audiobookshelf#2520]
### Describe the feature/enhancement

The PWA icon for Audiobookshelf is low resolution compared to there PWAs. I would like to see that improved. Here is an example with other PWA apps:

![IMG_86E9D7CACB4E-1](https://github.com/advplyr/audiobookshelf/assets/15165416/0a4340e6-86c1-4d28-8e07-dac73baf8de7)

**Comment by advplyr** [comment]
I wasn't able to reproduce that but I was including 2 icons in the PWA manifest file. One of the icons was a 64x64 PNG which is probably the low quality one you are seeing, so I removed that.
I don't know why your device would choose the PNG over the SVG so if you feel like trying to the `edge` docker image it would be curious to see if your device uses the SVG when it's the only one available.

**Comment by ipcintron** [comment]
I used the edge image, erased the old PWA icon and tried re-adding it but I only got this "A" generic icon. I went back to the latest image and also added the PWA app back and took a side by side image. (This is on an iPhone 15 Pro Max).
![image](https://github.com/advplyr/audiobookshelf/assets/15165416/1cdc4d4e-ae01-4016-8f0a-0b0ae862d74f)

**Comment by advplyr** [comment]
Thanks for testing. iOS doesn't support SVG yet I guess. I added back in a PNG icon that is higher quality. Let me know how that goes if you update the edge container again.

**Comment by sevenlayercookie** [comment]
Using the edge release, icon resolution much improved on PWA. However, and this is nitpicky, I don't love the black ring around the edge. Can the PWA be made to use the same icon as the iOS app? Screenshot for reference.
![image](https://github.com/advplyr/audiobookshelf/assets/15989705/a699559c-d086-4a25-8305-375e7adf5ca7)

**Comment by advplyr** [comment]
Added in [v2.8.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.0)
