### ISSUE TITLE
[Enhancement]: Allow specification of OIDC user role and permissions with attribute mappings 

### ISSUE THREAD

**Issue by DonQuinleone** [advplyr/audiobookshelf#2523]
### Describe the feature/enhancement

I have managed to configure OIDC authentication for ABS, which is working brilliantly, but if I want to make someone an admin or give them additional permissions, this still has to be done via ABS' admin page.

It would be much better if we could manage roles and permissions via the OIDC provider, so can you add support for claims and attribute mappings to add this functionality please?

**Comment by Sapd** [comment]
I think I would implement it like this:

```js
{
  "sub": "1234567890",
  "name": "John Doe",
  "email": "john.doe@example.com",
  "groups": ["user"], // Can include user, admin or guest, highest will be taken. Names configurable and scopename configurable
  "abspermissions": { // name of the scope configurable
    "canDownload": true,
    "canUpload": false,
    "canDelete": false,
    "canAccessExplicitContent": true,
    "canAccessAllLibraries": false,
    "allowedLibraries": ["Library1", "Library2"],
    "canAccessAllTags": false,
    "allowedTags": ["Tag1", "Tag2"]
  }
}
```

While making the name of the claim `groups`, `abspermissions` configurable.
Also name of the groups itself would be configurable, so name of `user`, `admin`, `guest`. 
But I would however not make the name of the permissions inside abspermissions configurable given the complexity, one should be able to just add that json into the claims of the Idp.

So in the end basically we would have 5 new options in the Admin-Page to configure. All being optional. 

What do you think?

**Comment by Sapd** [comment]
Implemented in PR https://github.com/advplyr/audiobookshelf/pull/2769

**Comment by advplyr** [comment]
Added in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)
