### ISSUE TITLE
[Bug]: Server crash when .cbr file is added

### ISSUE THREAD

**Issue by criscrafter** [advplyr/audiobookshelf#2526]
### Describe the issue

Putting a .cbr file in the Books Library causes the Server to crash.
![grafik](https://github.com/advplyr/audiobookshelf/assets/95765057/82cea6cc-2ea9-4401-998c-491f27b6ffab)
It doesnt matter if it is in a folder or subfolder:
![grafik](https://github.com/advplyr/audiobookshelf/assets/95765057/dd264405-9134-4ebd-a910-59ac4094a849)
This is the affected File. Maybe others as well, I couldnt test yet.
I don't think there will be copyright issues with a 27 Year old Comic.
[Simpsons Comics 001.zip](https://github.com/advplyr/audiobookshelf/files/13981685/Simpsons.Comics.001.zip)
log file: 
[2024-01-18.txt](https://github.com/advplyr/audiobookshelf/files/13981714/2024-01-18.txt)

### Steps to reproduce the issue

1. Put .cbr File in any directory or subdirectory
2. Server crashes

### Audiobookshelf version

2.7.2

### How are you running audiobookshelf?

Docker

**Comment by commandcom** [comment]
FWIW, I have the exact same issue:
- Audiobookshelf version: 
  - 2.8.0
- How are you running audiobookshelf?
  - Docker

Debug log excerpt showing the crash:
```
2024-03-09 17:08:31.476

INFO

[LibraryScanner] Starting (forced) library scan 45601171-34e4-444f-9923-4c962a778d8b for Graphic Novels

2024-03-09 17:08:31.540

DEBUG

[fileUtils] Ignoring path has . "Kirkman, Robert, Adlard, Charlie, Rathburn, Cliff/The Walking Dead/.vscode/launch.json"

2024-03-09 17:08:31.579

DEBUG

[LibraryScan] "Graphic Novels": 32 item data found in folder "/graphicnovels"

2024-03-09 17:08:31.587

DEBUG

Parsing metadata from comic at "/graphicnovels/Kirkman, Robert, Adlard, Charlie, Rathburn, Cliff/The Walking Dead/9. Here We Remain/Here We Remain.cbr"

2024-03-09 17:08:32.299

DEBUG

[LibraryScan] "Graphic Novels": "Here We Remain" Getting metadata with precedence [folderStructure, audioMetatags, nfoFile, txtFiles, opfFile, absMetadata]

2024-03-09 17:08:33.006

FATAL

[Server] Unhandled rejection: [object Object], promise: Promise { <rejected> { message: 'Parsing filters is unsupported.', name: 'Error', stack: 'Error: Parsing filters is unsupported.\n' + ' at ArchiveReader.entries (/server/libs/libarchive/wasm-module.js:110:17)\n' + ' at entries.next (<anonymous>)\n' + ' at MessagePort.<anonymous> (/server/libs/libarchive/libarchiveWorker.js:43:20)\n' + ' at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)\n' + ' at exports.emitMessage (node:internal/per_context/messageport:23:28)' } }
```

**Comment by zerojay** [comment]
Workaround: Convert your .cbr to .cbz and it'll work fine.
