### ISSUE TITLE
[Bug]: Book can't be removed from "Continue Listening"

### ISSUE THREAD

**Issue by zahroc** [advplyr/audiobookshelf#2528]
### Describe the issue

Using v2.7.2 of audiobookshelf in Microsoft Edge v120.0.2210.133, I am unable to remove a book from "Continue Listening". I click the three dots, select "Remove From Continue Listening" and nothing happens. The book is complete. I would try in IOS but the option doesn't exist.

### Steps to reproduce the issue

1. Click three dots on book cover in "Continue Listening"
2. Click "Remove from Continue Listening"
3. It doesn't disappear

### Audiobookshelf version

2.7.2 

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Is this for a completed book, or one that you don't want to finish?

If a completed book, try clicking "remove progress", then "mark as finished".

If an incomplete book that you want to keep the progress on, try removing progress, playing again and jumping back to where you left off, then "remove from Continue Listening".

There are a few combinations of old iOS and server versions (including migration from 2.2.23) that cause duplicate progress states of a book which prevents it being removed from Continue Listening. This duplicate progress sticks around after an update, so it would be good if you can try the above to make sure it's not that.

**Comment by zahroc** [comment]
Thank you for the comments. 

Unfortunately, there is no option to "remove progress". I only have the options shown in the screenshot.

Yes, it is a completed book.

![image](https://github.com/advplyr/audiobookshelf/assets/41906902/464a61ae-fdd0-4b7b-a6df-b0df3972c498)

**Comment by zahroc** [comment]
I clicked "Marked as Not Finished", then clicked "Marked as Finished" and then clicked "Remove from Continue Listening". It disappeared but as soon as the page refreshed, it came back.

**Comment by zahroc** [comment]
Yes, I had only did it in the browser. Using the IOS app, I had to "discard progress" twice as it did not fully go back to the beginning and then "marked it as finished" and it disappeared from both.

Thanks for the help!

**Comment by nichwall** [comment]
Glad it worked! Yep, definitely a case of duplicate progress.

**Comment by zahroc** [comment]
Thank you

**Comment by Xelveki** [comment]
I am also having this problem and marking as complete and/or removing it from the continue listening list is not working.
