### ISSUE TITLE
[Enhancement]: Allow reordering of tracks

### ISSUE THREAD

**Issue by mpldr** [advplyr/audiobookshelf#2530]
### Describe the feature/enhancement

It would be nice if it was possible to reorder a books tracklist. For some very long books, there is no "single file" version available for download. One such example would be "Under the Dome" by Stephen King.

After downloading them, ripping them, and uploading them to ABS, I now have this mess (I assume because the disk number wasn't set as a tag):
![2024-01-19-11-58-57](https://github.com/advplyr/audiobookshelf/assets/33086936/8fbbb9ee-dd84-43f9-a4f0-db11552e75c0)

It would be nice if I could just reorder this in the chapter overview instead of having to retag all those files.

**Comment by mpldr** [comment]
I am not quite sure what you mean. All files are in the same `[Author]/[Book]` directory. No subdirectories. Unfortunately, the sorting in ABS, does not match the order of a "traditional" sorting.

```
moritz@atlas ❯ ls audiobooks/Stephen\ King/Die\ Arena\ -\ Under\ the\ Dome          /srv/audiobookshelf
.rw-r--r-- 191k root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-01 Kapitel 1.opus
.rw-r--r-- 240k root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-02 Kapitel 2.opus
.rw-r--r-- 5.5M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-03 Kapitel 3.opus
.rw-r--r--  13M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-04 Kapitel 4.opus
.rw-r--r--  22M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-05 Kapitel 5.opus
.rw-r--r--  28M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-06 Kapitel 6.opus
.rw-r--r--  33M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-07 Kapitel 7.opus
.rw-r--r--  42M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-08 Kapitel 8.opus
.rw-r--r--  49M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-09 Kapitel 9.opus
.rw-r--r--  31M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-10 Kapitel 10.opus
.rw-r--r--  27M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-11 Kapitel 11.opus
.rw-r--r--  33M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-12 Kapitel 12.opus
.rw-r--r--  31M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-13 Kapitel 13.opus
.rw-r--r--  39M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-14 Kapitel 14.opus
.rw-r--r--  36M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-15 Kapitel 15.opus
.rw-r--r--  35M root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-16 Kapitel 16.opus
.rw-r--r-- 221k root 19 Jan 11:19 Die Arena - Teil 1 - Under the Dome-17 Kapitel 17.opus
.rw-r--r--  43M root 19 Jan 11:19 Die Arena - Teil 2 - Under the Dome-01 Kapitel 1.opus
.rw-r--r--  45M root 19 Jan 11:19 Die Arena - Teil 2 - Under the Dome-02 Kapitel 2.opus
.rw-r--r--  43M root 19 Jan 11:19 Die Arena - Teil 2 - Under the Dome-03 Kapitel 3.opus
.rw-r--r--  46M root 19 Jan 11:19 Die Arena - Teil 2 - Under the Dome-04 Kapitel 4.opus
```

**Comment by criscrafter** [comment]
Can you send a screenshot of the main Page of the Audiobook?
I cannot find the page, where you took the screenshot.

**Comment by mpldr** [comment]
Item > Edit > Chapters > Edit Chapters

-- 
Moritz Poldrack
https://moritz.sh
Official sponsor of the letter ＠

> Edited for television.

**Comment by criscrafter** [comment]
Oh, okay.
Having the option to move them there easily would be nice.
You can move them however by going to Item and on the right of the "Audio Tracks" dropdown you can click "Manage Tracks".
There you can move them around.

**Comment by advplyr** [comment]
I think you want to re-order the tracks and not re-order the chapters. If you only re-order the chapters then it will still be out of order when you listen to it.
To re-order the tracks use the manage tracks page like @criscrafter mentioned.
When you go to the manage tracks page you can also use the column headers to quickly sort them. Abs attempts to get the track and disk number from the filename and the audio file meta tags but isn't always successful like in your case so you have to manually manage tracks.
