### ISSUE TITLE
[Bug]: Chromecast from chrome-browser, not working properly 

### ISSUE THREAD

**Issue by Torstein-Eide** [advplyr/audiobookshelf#2531]
### Describe the issue

Casting to chromecast from Android work okay.

But casting from web with chrome 120, 
It able to initiate, but not able to start.
 
How can I find more information  on it? I am only able to start the cast in chrome from my https proxy, not from $server:13378. 

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.7.2

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Chromecast only supports https. If using a chromium browser you can work around that in chrome://flags
