### ISSUE TITLE
[Bug]: Logs do not contain [Auth] entries

### ISSUE THREAD

**Issue by gitdeath** [advplyr/audiobookshelf#2533]
### Describe the issue

I am attempting to utilize the IP logging features found in the below commits, but my logs do not show any [Auth] entries at all.  My logs are working and I do see entries for things like: [ApiCacheManager], [PlaybackSessionManager], [LibraryScan], [fileUtils] 

I have tried with the Server Log Level set to 'Debug', 'Info', and 'Warn'

https://github.com/advplyr/audiobookshelf/issues/1740
https://github.com/advplyr/audiobookshelf/commit/4db26f9f79fb22d8355341c42bb3970676b198d2

https://github.com/advplyr/audiobookshelf/issues/1172
https://github.com/advplyr/audiobookshelf/commit/892fb6410c80892f54931e0a4a0cc6b92e175395

### Steps to reproduce the issue

1. Install via Docker 2.7.2
2. Login successfully
3. Login with incorrect password
4. Review logs

### Audiobookshelf version

2.7.2

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
After doing some research, it looks like this functionality broke in server version `2.6.0`, which is when SSO support was added. I assume that change to the authorization flow is what broke the logging.
I tested this on all of the releases between `2.5.0` and `2.7.2`, and `2.5.0` was the last release where this logging and rate limiting worked.
