### ISSUE TITLE
Duplicate track number "n"

### ISSUE THREAD

**Issue by JKamsker** [advplyr/audiobookshelf#254]
Duplicate track numbers occur when having merged 2 'Discs' of the same album.

Example: 
``ffprobe '.\001 - Chapter 1 - Blood of the Mantis - Shadows of the Apt, Book 3.mp3'``
```
    title           : Chapter 1 - Blood of the Mantis - Shadows of the Apt, Book 3
    artist          : Adrian Tchaikovsky
    track           : 1/312
    album           : Blood of the Mantis - Shadows of the Apt, Book 3 (Unabridged)
    disc            : 1/2
```

`` ffprobe.exe '.\157 - Chapter 157 - Blood of the Mantis - Shadows of the Apt, Book 3.mp3'``

```
    title           : Chapter 157 - Blood of the Mantis - Shadows of the Apt, Book 3
    artist          : Adrian Tchaikovsky
    track           : 1/312
    album           : Blood of the Mantis - Shadows of the Apt, Book 3 (Unabridged)
    disc            : 2/2
```

I suggest adding discs to the sorting

**Comment by mx03** [comment]
Looks similar to [#155](https://github.com/advplyr/audiobookshelf/issues/155)
