### ISSUE TITLE
服务端自动关闭。CPU占用高。

### ISSUE THREAD

**Issue by syzh0675** [advplyr/audiobookshelf#2542]
### Describe the issue

![screenshot-1705907543295](https://github.com/advplyr/audiobookshelf/assets/37237882/c7f3274e-a542-4112-94ba-f1f7e56754ff)

### Steps to reproduce the issue

1. 

### Audiobookshelf version

v2.7.2

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
You seem to have a bad input audio file. There isn't enough information to do anything else with this.
