### ISSUE TITLE
RSS option for filenames as episodes

### ISSUE THREAD

**Issue by windsifter** [advplyr/audiobookshelf#2543]
### Describe the feature/enhancement

Add an option to list audiobook RSS as filenames instead of the current mixture of chapters and filenames deepening on where the files align. Having a number / track in the title would also allow for easy sorting and to know the order / progress in a book.

Currently the Episode names are taken from Chapters if they align with the start of the file, but otherwise default to a file so it will be inconsistent throughout the feed. I've had this issue with every books I've tried. (abs view: https://i.imgur.com/gj7dSXp.png RSS feed view: https://i.imgur.com/sbn9Z6N.png)

Current relevant code: https://github.com/advplyr/audiobookshelf/blob/master/server%2Fobjects%2FFeedEpisode.js#L118-L127

**Comment by advplyr** [comment]
A better solution might be to only use the chapter names if all audio files match timestamps with the chapters

**Comment by windsifter** [comment]
Yes, that is true if all chapters align with file names. The worst scenario is a mixture of chapters and file names which is something I consistently get. But the other key item is adding a number as the first part of the episode name so you can sort or know if you are listening to the first or last episode. You may need to be smart or use 2 digits or you'll get 1, 11, 2, 3, etc 

Thanks!

**Comment by advplyr** [comment]
We had this issue with using filenames as chapters I initially was prepending a number in front of the filename but most users already have a number in the filename so it was creating a duplicate number.
Here is the request for the mobile app repo https://github.com/advplyr/audiobookshelf-app/issues/981. I couldn't find the original one for this repo but it was brought up a few times.

**Comment by advplyr** [comment]
Added in [v2.8.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.0)

**Comment by nichwall** [comment]
Can this be closed?
