### ISSUE TITLE
[Enhancement]: Build/run from source guide

### ISSUE THREAD

**Issue by ghost** [advplyr/audiobookshelf#2545]
"Run from source" section is there, but it is empty. I hope it will be filled soon. Docker is not an option on low-end hardware and *BSD servers.

**Comment by moozhub** [comment]
I second this, I have a bsd host that I'd like to have audiobookshelf self hosted server running on. Are there any details on how to build this from source?

**Comment by nichwall** [comment]
The instructions directly under running from source (How to Contribute) includes instructions on how to run from source. It begins with VSCode instructions, but you can use the npm commands to run it from a regular terminal.

**Comment by advplyr** [comment]
It is there underneath contributing. You would want to use manual environment setup if you are using that for prod
