### ISSUE TITLE
[Bug]: Match with Amazon uses completely wrong ASIN

### ISSUE THREAD

**Issue by Silther** [advplyr/audiobookshelf#2550]
### Describe the issue

I have imported almost 40 books and matched all with Amazon.com, but the Asin which is used is completly  wron (if you search for the book on Amazon. 
`B09HR33QHH` is the asin: audiobookshelf uses but the real book has `B09HR36CQN`.
` (Star Wars: Brotherhood). I find it kind of strange that every ASIN i matched was wrong

### Steps to reproduce the issue

1. match `Star Wars: Brotherhood` via title and amazon.com in audiobookshelf -> ASIN=`B09HR33QHH`
3. search for `B09HR33QHH` on Amazon website -> No results for B09HR33QHH.
4. search for `Star Wars: Brotherhood` on Amazon website -> ASIN=`B09HR36CQN`
5. try match with ASIN=`B09HR36CQN `in audiobookshelf -> no book will be found

### Audiobookshelf version

2.7.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Abs doesn't use ASIN from amazon.com, it uses ASIN from audible.com. They are different as far as I know.

**Comment by advplyr** [comment]
I'm not sure. Maybe you have the wrong ASIN
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/03921349-dc50-4298-9665-5048e1f86672)

This is all pulled in from audnexus and audible api so if the data is incorrect then that is something to bring up to audible, we can't control that.

**Comment by advplyr** [comment]
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/018aebd3-d575-401c-8bac-46b2f20eb4ba)

Must be an error with audibles page then because I have the Jim Dale copy and it is 26h 29m. I doubt Stephen Fry read the book at the exact same pace.
