### ISSUE TITLE
[Enhancement]: Request to add support for storing/displaying or linking to a Privacy Policy

### ISSUE THREAD

**Issue by methosinhiding** [advplyr/audiobookshelf#2552]
### Describe the feature/enhancement

**Capability Gap**

- It would be great for enabling easier use of ABS in educational settings, open-source media public-hosted settings, or in GDPR-scoped countries if there were either an app-internal way to host and display the text of a Privacy Policy OR to link to an external one from within the app.
- Currently, any privacy policy would need to presented externally to the ABS UI which weakens protections for both the server administrator and the chance a user would actually see and/or read it.
- Even if stock ABS doesn't come with a boilerplate/default/predefined privacy policy it would be pretty handy to have the option of displaying a Privacy Policy or Privacy Policy link if one has been configured by the Admin.

**Requested Enhancement(s):**
- Add a way to _either_
     1) store a link to an externally-hosted privacy policy;
     **or**
     2) define/display an internally-hosted privacy policy (in a way not requiring that viewers be authenticated)
- Add a 'Privacy Policy' link to the pre-login screen and the main web UI (perhaps in the bottom-left corner near the version number) which points to either the user-defined Privacy Policy URL or the ABS-hosted Privacy Policy text blurb.
- Add links/views in the ABS mobile applications to the Privacy Policy

**Related items which would be understandably out-of-scope:**
- Populating a default privacy policy for the stock ABS installation settings
- Generating a dynamic default privacy policy based on the ABS instance's elected application/library settings

**Comment by Sapd** [comment]
I think what would be cool to have for that use case would be a "Privacy/GPDR" page in the admin section where one can has:
- A textbox with HTML support for a Privacy Policy. If filled out it could make a link at the bottom automatically, pointing to a very simple page with the content.
- The same for an Imprint
- It could contain further options, like disable IP-Adress logging or history or so.


Forum systems etc. usually have something similar.

**Comment by advplyr** [comment]
We discussed this in Discord a bit and I think the best solution is to offer the option to put your own custom message on the login page. This is something I intended on adding for a while because it can help with demo instances.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/bb28c000-8a5e-45a6-b6ab-8df5691d13a0)

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/2609d6c3-d9a3-49d5-b87b-8c29ca09c8b9)

**Comment by advplyr** [comment]
Added in [v2.8.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.0)
