### ISSUE TITLE
[Enhancement]: Allow keyboard navigation and selection in drop-down lists

### ISSUE THREAD

**Issue by mikiher** [advplyr/audiobookshelf#2555]
### Describe the feature/enhancement

There are many places in the product in which you can select an item from a drop-down list (authors, genres, tags, etc...).
Currently the only way AFAIK to select an item from the list is to click on it. 

I'd like to ask for support for keyboard navigation and selection - it is quite annoying to switch between keyboard and mouse, especially when adding tags and other metadata fields.

**Comment by djripcord** [comment]
This is a good idea. It will tremendously improve the speed in which you can manually catalogue your library.

**Comment by mikiher** [comment]
I will try to work on it soon.

**Comment by advplyr** [comment]
Added in [v2.8.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.1)
