### ISSUE TITLE
Bug: Opus files metadata parsing issue

### ISSUE THREAD

**Issue by mx03** [advplyr/audiobookshelf#256]
Opus files (ogg) metadata (vorbis comment/id3) dont get parsed. Chapters works.

Update:
Probably because the mp3 can has only one stream and ogg format multiple, the tags are embedded inside the stream.

ffprobe mp3:
`raw.format.tags`

ffprobe opus/ogg:
`raw.streams[streamNumber].tags`

ffprobe examples:
[meta.mp3.json.txt](https://github.com/advplyr/audiobookshelf/files/7765343/meta.mp3.json.txt)
[meta.opus.json.txt](https://github.com/advplyr/audiobookshelf/files/7765344/meta.opus.json.txt)

**Comment by advplyr** [comment]
Ah yeah, didn't think about that. We can add an additional check for stream tags if format tags are not found.

**Comment by advplyr** [comment]
In `v1.6.47` the prober will fallback to using the tags on the audio stream.
I didn't actually test this since I don't have any audio files like that.

**Comment by mx03** [comment]
Thanks works perfect!
