### ISSUE TITLE
[Bug]: Series doesn't sort alphabetically properly

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#2563]
### Describe the issue

When sorting series alphabetically, ascending sorting is broken

Both below screenshots are the first four series after selecting sorting.

![image](https://github.com/advplyr/audiobookshelf/assets/4344284/331b5d83-f0ff-42e4-a482-52cbedae6f4e)

![image](https://github.com/advplyr/audiobookshelf/assets/4344284/eccb0d92-5f4d-4a2f-a7c4-f32037543663)

### Steps to reproduce the issue

1. Sort series alphabetically descending

### Audiobookshelf version

v2.7.2

### How are you running audiobookshelf?

Docker

**Comment by ScuttleSE** [comment]
Seems like there is a bug(?) where nameIgnorePrefix doesn't get updated

```
sqlite> select * from series where nameIgnorePrefix IS NULL;
9a4e2b64-04c9-49b7-9806-a842fb9331f5|Rook & Rose||2023-09-10 13:03:09.016 +00:00|2023-09-10 13:03:09.016 +00:00|dac312d8-6b0e-4b3c-ad6e-8e50a9d8d8b1|
b93a7522-3db9-451e-9f41-c126b2eb07b8|Taken to the Stars||2023-09-17 12:05:52.601 +00:00|2023-09-17 12:05:52.601 +00:00|dac312d8-6b0e-4b3c-ad6e-8e50a9d8d8b1|
8cb40cf6-ea39-4471-b20d-17ebd41101ea|The Last Binding||2023-09-17 13:26:39.321 +00:00|2023-09-17 13:26:39.321 +00:00|dac312d8-6b0e-4b3c-ad6e-8e50a9d8d8b1|
7a82b038-6d13-43fa-a713-e800f73f7296|Wayfarers||2023-09-17 13:35:53.454 +00:00|2023-09-17 13:35:53.454 +00:00|
```

**Comment by ScuttleSE** [comment]
Interesting...the books that are not being sorted properly has the series name as null

![image](https://github.com/advplyr/audiobookshelf/assets/4344284/c37d6f70-f2ff-45c6-bd5a-fd18f25f8660)

**Comment by nichwall** [comment]
Related to https://github.com/advplyr/audiobookshelf/issues/2385

**Comment by advplyr** [comment]
Was this ever resolved or did you figure out anything here?
