### ISSUE TITLE
[Bug]: Open Listening Session stays open forever

### ISSUE THREAD

**Issue by allthesebugsv2** [advplyr/audiobookshelf#2565]
### Describe the issue

Another thing I noticed regarding "Open Listening Sessions": 
I'd expect the "Open Listening Sessions" to close active sessions after some time has passed without an update.
![Screenshot 2024-01-28 190844](https://github.com/advplyr/audiobookshelf/assets/50304079/78eb34ff-e915-492c-ab4e-ee3bc2bf8761)
I have had open sessions for more than 10 hours without any update; still they remain open. It would be nice to maybe even have a configuration option like "Close open session after x minutes without update".

### Steps to reproduce the issue

1. Start a stream of an audiobook (I can reproduce this with the Android app and the web version).
2. Verify that there is an Open Listening Session
3. Stop the playback via different means (i.e. pause first, then close; or just close without pausing the app).
4. Notice that there is still an open session which stays active even though playback has long since stopped

### Audiobookshelf version

2.7.2

### How are you running audiobookshelf?

Docker

**Comment by doctordarko** [comment]
With server not even 2 weeks old, I am seeing listening sessions 170 days long.

<img width="188" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/57649463/196f2a19-0a19-4452-9c34-36835444c5a9">

**Comment by advplyr** [comment]
As of about 6 months ago open listening sessions that have been inactive for 36 hours are closed automatically
