### ISSUE TITLE
[Bug]: "Mark as finished" not staying enabled

### ISSUE THREAD

**Issue by WinterLoki** [advplyr/audiobookshelf#2575]
### Describe the issue

When I mark an audiobook as finished, the app or the browser app doesn't keep that setting for that book consistently. Quite often, it will show as still in progress with the correct amount of time left on it. (I will usually mark an audiobook finished once it gets to the credits at the end and I stop listening - there's usually still a minute or so left.) This not only happens when switching from platform to platform (switching from the iOS app to the browser and vice versa) but within the same app that I'm using. For example, I have finished two books and have started on a third. I marked those two as finished. However multiple times the two pop back up in my "Currently listening" list and don't show as finished. I've so far marked them as finished 3 times.

### Steps to reproduce the issue

1. Listen to audiobook.
2. Click the option to mark it as finished.
3. Go to the home page or refresh. Or go to a different platform to check your library
4. Books marked as finished show with the yellow "in progress" bar instead of the green "completed" bar and don't state that they are at 100%, instead showing the percentage they were at when marked as finished.

### Audiobookshelf version

v2.7.1

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Same behavior as https://github.com/advplyr/audiobookshelf/issues/2528, try following those steps.
