### ISSUE TITLE
[Bug]: idtag language

### ISSUE THREAD

**Issue by Beulu** [advplyr/audiobookshelf#2577]
### Describe the issue

Audiobook got language idtag. When I import them, no problem. When I check box in options "Prefer matched metadata", language is overwrited with online information. Other idtag stay. This options got info : "Matched data will override item details when using Quick Match. By default Quick Match will only fill in missing details." So I thinl it's not logic or doing the totally inverse. Maybe I missed something ?

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.7.2

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Quick Match will by default only fill in missing fields, but if you "Prefer Matched Metadata" then your local metadata within ABS will be overwritten by the match. This will apply to all fields, not just the language field.

**Comment by Beulu** [comment]
But if I don't check it the description is incomplete while is complete inside the audiobook file...

**Comment by nichwall** [comment]
Can you provide screenshots of what you're experiencing? It sounds like your metadata priority is not correct.

https://www.audiobookshelf.org/guides/book-scanner#book-metadata-parsing

The metadata JSON file is a copy of what is stored in the ABS database and is updated whenever the item is updated within ABS, which can occur from a scan, matching against an online provider, manually editing within ABS, or using the API.

If an incomplete description field is showing up in ABS and the ABS metadata file is a higher priority than your media metadata, then the description won't be updated after updating your metadata tags. If you match against an online provider and "Prefer Matched Metadata" or force an overwrite with the batch edit modal, then the metadata from the online provider will overwrite what is in ABS.

**Comment by Beulu** [comment]
OK ! Scan priority was changed
![image](https://github.com/advplyr/audiobookshelf/assets/72515988/b8d71d0f-5f6e-4f2c-bcda-4ce85cbfa1d6)

but ABS continues to go online, changing an english audio book with french description, and sometime with chinese or russian metadata...

All my audiobooks are configurated with musicbee software. So they are totally independent. ABS just have to check within metadata. In priority, even if metadata already exist with previous configuration.

**Comment by nichwall** [comment]
So don't match against an online provider or disable the "Prefer Matched Metadata", because that will overwrite the metadata within ABS.

With those settings, your metadata in ABS will always be overwritten by the media file metadata whenever you perform a scan.

**Comment by Beulu** [comment]
OK :
![image](https://github.com/advplyr/audiobookshelf/assets/72515988/86d93a38-b789-4a75-99a1-bb5aeb0aba59)
![image](https://github.com/advplyr/audiobookshelf/assets/72515988/743c3156-8ee6-4931-87b1-6703101baa24)

erased two metadata files
![image](https://github.com/advplyr/audiobookshelf/assets/72515988/9a06e71c-efc6-4c08-92a4-6e517f8585a8)

new library analysis, search books but description is still cut :
![image](https://github.com/advplyr/audiobookshelf/assets/72515988/efd2dbb5-5d24-42db-ad19-6354d89ccb30)

**Comment by Beulu** [comment]
![image](https://github.com/advplyr/audiobookshelf/assets/72515988/89c8fdf9-aa20-4c04-8575-6e3d7c137308)

highlighted the dutted sentence

**Comment by Beulu** [comment]
![image](https://github.com/advplyr/audiobookshelf/assets/72515988/83a0a7c9-d3dc-4f7e-98b6-0343cf4138ae)
narrator is not good too. I don't know where it's taking informations. Changing cover too.

![image](https://github.com/advplyr/audiobookshelf/assets/72515988/7a7138bc-7df5-404b-af55-0b4b09324370)

**Comment by nichwall** [comment]
Have you looked at the metadata from ffprobe? You can do this within the web client by clicking on "More Info" in the dropdown on the Audio Tracks list (first screenshot) and then clicking on the "probe audio file" in the upper right (second screenshot) to see what ffprobe is saying your tags are.

The narrator is in the wrong metadata tag on your files, it should be in `composer`. https://www.audiobookshelf.org/docs#book-audio-metadata

![image](https://github.com/advplyr/audiobookshelf/assets/5686638/a5643c75-1a65-4ed4-918b-bae5624bf1ff)
![image](https://github.com/advplyr/audiobookshelf/assets/5686638/55f9cbde-a9c7-4339-8c86-edc9be63db20)
