### ISSUE TITLE
[Bug]: Cannot add podcast with localhost URL

### ISSUE THREAD

**Issue by BradleyMarie** [advplyr/audiobookshelf#2581]
### Describe the issue

I'm attempting to add a podcast by URL where the http server hosting the RSS feed is served on localhost. When I do this, I receive an error back from the server "Podcast RSS feed request failed or invalid response data". I also looked at the server logs and observed the following:

```ERROR: [podcastUtils] getPodcastFeed Error AxiosError: Call to 127.0.0.1 is blocked.```

Based on some chatter I found [here](https://stackoverflow.com/questions/49529201/node-js-axios-wont-connect-to-localhost), I believe the issue is that Axios is not configured to allow connections to localhost, but I'm also entirely unfamiliar with Node.js.

### Steps to reproduce the issue

1. Add a podcast where the RSS feed is served on localhost

### Audiobookshelf version

v2.7.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Due to the security advisory submitted here https://github.com/advplyr/audiobookshelf/security/advisories/GHSA-mgj7-rfx8-vhpr I added an SSRF request filter. https://github.com/y-mehta/ssrf-req-filter

That validates the path being entered is external.

**Comment by BradleyMarie** [comment]
Thanks for the quick reply. It sounds like this is working as intended and is not a bug.

It would be nice to be able to add local feeds directly, but I am able to workaround this by behavior by bouncing the request off my router.

I'll close this issue out. Thanks!
