### ISSUE TITLE
[Enhancement]: Abilty to edit or unlink users from SSO Providers

### ISSUE THREAD

**Issue by mdbell** [advplyr/audiobookshelf#2587]
### Describe the feature/enhancement

While testing some stuff with Authentik I inadvertently logged in with a test user with my email address, instead of logging in as my desired account. I then deleted the user from Authentik, effectively locked out of SSO on account. While I was able to manually edit the `extraData` column in the sqlite DB, it's not something that all server admins can be realistically expected to do (at least without clobbering their DB).

It would be nice for an admin user to be able to edit, or just reset; the UID. Perhaps just a "Unlink SSO" button on the edit user dialog?

**Comment by advplyr** [comment]
Added in [v2.8.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.0)

This is available in the user edit modal
