### ISSUE TITLE
[Enhancement]: Author description page

### ISSUE THREAD

**Issue by izyspania** [advplyr/audiobookshelf#2590]
### Describe the feature/enhancement

Would be nice to have an Author page with a description , image and albums and not just showing the albums.

**Comment by nichwall** [comment]
Like this?
![Screenshot_20240206-081348.png](https://github.com/advplyr/audiobookshelf/assets/5686638/afeff421-8523-46c2-9e16-fd30bc988c81)

**Comment by izyspania** [comment]
Yes , that looks great!

**Comment by nichwall** [comment]
This is already implemented

**Comment by izyspania** [comment]
Ah right , i just checked and it is , sorry  , i was looking in the android client and its missing from there if im not wrong?

**Comment by nichwall** [comment]
Oh, yeah that isn't implemented in the mobile apps.
You want https://github.com/advplyr/audiobookshelf-app

**Comment by izyspania** [comment]
Added it there, sorry i didnt check from start. https://github.com/advplyr/audiobookshelf-app/issues/1064
