### ISSUE TITLE
[Bug]: New tag not showing in filter list

### ISSUE THREAD

**Issue by fivestones** [advplyr/audiobookshelf#2597]
### Describe the issue

I added a tag ("Recommended books") to a bunch of books (none of them audiobooks). Then I tried to filter by this tag in the library, but it didn't show up in the list of tags. I refreshed the site, but still it didn't show up.
I noticed that all the tags that did show up were applied to audiobooks.
When I applied the "Recommended books" tag to an audiobook, it suddenly showed up in the list of tags to filter the library by, and when I chose it, I could see both the single audiobook and all the text books I had tagged with this tag.

Probably related is that when the tag has been used to tag books already, when trying to tag another book, it doesn't appear in the drop down of existing tags to choose from.

### Steps to reproduce the issue

1. Tag one or more text books with a new tag.
2. Do not tag any audiobook with the tag.
3. The tag doesn't show up in the list of tags when filtering the library view.

### Audiobookshelf version

v2.7.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This isn't specific to ebooks. This has to do with the filters being cached and adding the new tag is not updating the cached filters correctly.

**Comment by advplyr** [comment]
Fixed in [v2.8.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.0)
