### ISSUE TITLE
UI clarification suggestion for "remove" option

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#26]
I had to manually test for how the "remove" function worked because it wasn't clear.

I assumed it wouldn't "delete" the files from my storage location and only "remove" the listing from my bookshelf and it turned out that WAS how it worked. But I wonder if there might be a little confusion in others as well.

Maybe a quick note somewhere noting that this will "remove from audiobookshelf library only and not 'touch' the files on the filesystem" ... or something. Maybe the note could be on the confirmation prompt when we are asked to verify our removal action.

What do you think?

P.S. I hope I'm not coming off as "picky", but you got all the really big, important stuff almost totally tackled! At least in my opinion, you're almost at the point where all that's left are little "picky" fixes, and feature enhancements! 

You're doing GREAT work!!!

**Comment by advplyr** [comment]
Not at all, I really appreciate your help, and agree with this suggestion. I added the extra note in the prompt for v1.1.1
