### ISSUE TITLE
[Enhancement]: Ignore Thumbs.db file

### ISSUE THREAD

**Issue by JBHorne2** [advplyr/audiobookshelf#2602]
### Describe the feature/enhancement

Every one of my books in audiobookshelf has a "Thumbs.db" file. This is a hidden file in windows. Can this be ignored on scanning/import?

![image](https://github.com/advplyr/audiobookshelf/assets/122175763/09389a5e-9b5a-4616-b30a-d9ef7f60b880)

**Comment by nichwall** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1641

**Comment by advplyr** [comment]
Duplicate of #1641
