### ISSUE TITLE
[Bug] Series volume sorting with dot

### ISSUE THREAD

**Issue by mx03** [advplyr/audiobookshelf#261]
For some series that are splitted up in multiple seasons or books i abuse the series-part with following pattern: _seriesnumber_._volumenumber_ (eg: 1.1 , 1.2 , 2.3).

The series is currently sorted: ( 1.10 , 1.1, 1.2, [...] 1.9, 2.10, 2.1 [...] ), better would be the natural sorting. ( 1.1 1.2 [...] 1.9 1.10 2.1 )

Not sure if the volume numbering overall wanted to be other than pure number or if its ok with dot.

**Comment by advplyr** [comment]
This is a bug then, as long as it is a valid number it should be sorted as that.

**Comment by mx03** [comment]
The problem is ab.book.volumeNumber is a string, if you use Number the result is:
```js
Number('1.1') // => 1.1
Number('1.10') // => 1.1
```

If it should works with this logic it shouldn't treated as Number and use https://www.npmjs.com/package/fast-sort#natural-sorting--language-sensitive-sorting instead

**Comment by advplyr** [comment]
I wasn't aware of language sensitive sorting, thanks for finding that.
This is included in `v1.6.48`

**Comment by mx03** [comment]
regression after changing series route https://github.com/advplyr/audiobookshelf/commit/6b9ce453b9c0f1bafff24c254c6d967c628d1588

**Comment by advplyr** [comment]
I just pushed a patch for this, same version.
