### ISSUE TITLE
[Enhancement]: Read More for big album/author descriptions

### ISSUE THREAD

**Issue by izyspania** [advplyr/audiobookshelf#2614]
### Describe the feature/enhancement

Would be nice to have a read more button for big album/author description, something like:

![Untitled-3](https://github.com/advplyr/audiobookshelf/assets/93366907/cb3f518e-f3ce-4fa8-9079-8e161732bfd1)

**Comment by advplyr** [comment]
Added in [v2.8.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.0)
