### ISSUE TITLE
PWA icon (iOS)

### ISSUE THREAD

**Issue by sevenlayercookie** [advplyr/audiobookshelf#2616]
### Describe the feature/enhancement

The PWA iOS icon has an ugly black border. The native iOS app icon does not and looks great. Can we use the native icon as the default for the PWA? Screenshot for reference:
![image](https://github.com/advplyr/audiobookshelf/assets/15989705/45d2bb0d-e84a-4a22-b491-4aa72bc318fc)

**Comment by sevenlayercookie** [comment]
> Fixed in #2617 

That did the trick looks great!

**Comment by advplyr** [comment]
Added in [v2.8.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.0)
