### ISSUE TITLE
[Enhancement]: PWA (iOS) theme color fix

### ISSUE THREAD

**Issue by ipcintron** [advplyr/audiobookshelf#2618]
### Describe the feature/enhancement

On iOS PWA the top bar gray doesn't mesh well with the gray underneath it. I am opening a PR to fix this:

Before:
![image](https://github.com/advplyr/audiobookshelf/assets/15165416/ded7e6da-55a1-4007-90b5-5a164a79fd8d)

After:
![IMG_1827](https://github.com/advplyr/audiobookshelf/assets/15165416/b8d67090-ba96-466a-80d9-cfa018329410)

**Comment by advplyr** [comment]
Added in [v2.8.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.0)
