### ISSUE TITLE
[Enhancement]: Year in review API endpoint

### ISSUE THREAD

**Issue by donkevlar** [advplyr/audiobookshelf#2622]
### Describe the feature/enhancement

I would love to see an endpoint or series of endpoints for the year in review functionality. 

Maybe include: Year, User, specific part of the generated year in review.

**Comment by advplyr** [comment]
These exist already they just aren't documented in the api docs yet. The clients are generating the images on their own so the API is just returning the data.
`/api/stats/year/:year` <-- server stats
`/me/stats/year/:year` <-- current user stats

Is that what you are requesting? Can you be more specific?

**Comment by donkevlar** [comment]
Yes, that's pretty much what I was asking about. But to pull the images themselves using the API. Are they stored on the server, or just refreshed every time the pages load in?

**Comment by donkevlar** [comment]
Just to be clear, I'm referring to these:

When looking at the inspector I didn't see any storage paths when these are pulled in and didn't see what the request was either. That's why I was asking. 

![image](https://github.com/advplyr/audiobookshelf/assets/21166416/6ab6dd97-97da-4f1d-b35d-ba01fde61549)

**Comment by advplyr** [comment]
Those images are generated client side using HTML canvas. I don't want to add a library to generate images on the server at this time but you can look at how I built this with HTML canvas https://github.com/advplyr/audiobookshelf/blob/master/client/components/stats/YearInReview.vue
