### ISSUE TITLE
[Bug]: "See Year in Review" crashes the app

### ISSUE THREAD

**Issue by plague-doctor** [advplyr/audiobookshelf#2623]
### Describe the issue

Container crashes with:
```
/server/utils/queries/userStats.js:144
        const genres = (ls.mediaMetadata.genres || []).filter(g => !g.toLowerCase().includes('audiobook') && !g.toLowerCase().includes('audio book'))
                                                                      ^
TypeError: Cannot read properties of null (reading 'toLowerCase')
    at /server/utils/queries/userStats.js:144:71
    at Array.filter (<anonymous>)
    at Object.getStatsForYear (/server/utils/queries/userStats.js:144:56)
    at async ApiRouter.getStatsForYear (/server/controllers/MeController.js:350:18)
```
when trying to "See Year in Review"

### Steps to reproduce the issue

1. Stats
2. See Year in Review

### Audiobookshelf version

v2.7.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Somehow you have a listening session with a null genre.

**Comment by izyspania** [comment]
With server in dev mode the refresh on See Year in Review is crashing for me.
![image](https://github.com/advplyr/audiobookshelf/assets/93366907/0e236bbc-01da-4eba-ad32-0f4a13726786)
![image](https://github.com/advplyr/audiobookshelf/assets/93366907/858e0bda-6199-415a-9209-02bc69e060a6)
