### ISSUE TITLE
[Enhancement]: Custom covers for Series and Collections

### ISSUE THREAD

**Issue by SAS-1** [advplyr/audiobookshelf#2627]
### Describe the feature/enhancement

Currently both Series and Collections use auto generated covers based on the books included in those options for the covers.
I would like to see an enhancement to this to allow users to add custom covers to both options I think this would give more control to users and maybe speed the loading up as it doesn't have to create covers by merging multiple ones as it does now.

**Comment by nichwall** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2589

**Comment by advplyr** [comment]
Duplicate of #2589
