### ISSUE TITLE
[Bug]: web login screen leaves [invisible] trailing whitespace after username

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf#2628]
### Describe the issue

[Bug]: web login screen leaves [invisible] trailing whitespace after username.  This never happens on other websites so there must be some kind of automatic whitespace trimming or there is some other error going on because I do not enter my username with a trailing whitespace.

### Steps to reproduce the issue

1. Try logging into the web from chrome desktop or android while accidentally leaving a trailing whitespace after login name
2. Fail to login
3. Get frustrated and check password
4. Reenter username and see accidental trailing whitespace
5. Remove trailing whitespace
6. login.
7. 

### Audiobookshelf version

v.2.7.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Updated in [v2.8.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.1)
