### ISSUE TITLE
[Bug]:  audiobookshelf_2.8.0_amd64.deb' uses unknown compression for member 'control.tar.zst'

### ISSUE THREAD

**Issue by ThePlaidHatHacker** [advplyr/audiobookshelf#2631]
### Describe the issue

I am running AudioBookShelf 2.7.2 in an LXC hosted on ProxMox.  I attempted to update to 2.8.0 this evening and received an error reading:
dpkg-deb: error: archive '/var/cache/apt/archives/audiobookshelf_2.8.0_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up

Other updates were installed at the same time.  I tried rebooting and trying again but got the same results.

I rebooted again and my existing install of 2.7.2 is unaffected.

Please let me know if there is any additional information I can provide.

Here is the full output from the apt upgrade command:

root@abs01:~# sudo apt update && apt upgrade -y
Hit:1 https://advplyr.github.io/audiobookshelf-ppa ./ InRelease
Hit:2 http://security.debian.org bullseye-security InRelease                        
Hit:3 http://deb.debian.org/debian bullseye InRelease
Hit:4 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  audiobookshelf
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
16 not fully installed or removed.
Need to get 0 B/25.9 MB of archives.
After this operation, 0 B of additional disk space will be used.
apt-listchanges: Reading changelogs...
dpkg-deb: error: archive '/var/cache/apt/archives/audiobookshelf_2.8.0_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/audiobookshelf_2.8.0_amd64.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 323, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 104, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 358, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 127, in readdeb
    raise RuntimeError(_("Error processing '%(what)s': %(errmsg)s") %
RuntimeError: Error processing '/var/cache/apt/archives/audiobookshelf_2.8.0_amd64.deb': Command '['dpkg-deb', '-f', '/var/cache/apt/archives/audiobookshelf_2.8.0_amd64.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.
dpkg-deb: error: archive '/var/cache/apt/archives/audiobookshelf_2.8.0_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/audiobookshelf_2.8.0_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/audiobookshelf_2.8.0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

### Steps to reproduce the issue

1.   Run apt upgrade to go from 2.7.2 to 2.8.0

### Audiobookshelf version

2.7.2

### How are you running audiobookshelf?

Other

**Comment by MrBearedJoe** [comment]
Same with 2.7.0 to 2.8.0

**Comment by advplyr** [comment]
Are you all using ProxMox?

**Comment by MrBearedJoe** [comment]
Yes, we do

**Comment by jonarihen** [comment]
`/var/cache/apt/archives$ sudo dpkg -i audiobookshelf_2.8.0_amd64.deb
dpkg-deb: error: archive 'audiobookshelf_2.8.0_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive audiobookshelf_2.8.0_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 audiobookshelf_2.8.0_amd64.deb`

it's also happening for me on Debian GNU/Linux 11 (bullseye) x86_64

**Comment by prowaynes** [comment]
> Вы все используете ProxMox?
no, vmware, with debian

**Comment by Deekerman** [comment]
Think its the same for me too

```
dpkg-deb: error: archive './audiobookshelf_2.8.0_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive ./audiobookshelf_2.8.0_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 ./audiobookshelf_2.8.0_amd64.deb
An error occurred during the update process.
```

**Comment by danmed** [comment]
This seems to detail the issue.. 

https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg

**Comment by prowaynes** [comment]
Confirmed, source.list needs to be modified
`/etc/apt/sources.list`
to the official repository, Debian code
`deb http://deb.debian.org/debian bookworm main non-free-firmware
deb-src http://deb.debian.org/debian bookworm main non-free-firmware

deb http://deb.debian.org/debian-security/ bookworm-security main non-free-firmware
deb-src http://deb.debian.org/debian-security/ bookworm-security main non-free-firmware

deb http://deb.debian.org/debian bookworm-updates main non-free-firmware
deb-src http://deb.debian.org/debian bookworm-updates main non-free-firmware`

**Comment by advplyr** [comment]
Thanks @danmed
I found that I can pass a flag in to `dpkg-deb` to change the compression method from `zstd` to `xz`

I just re-packaged v2.8.0 if anyone here wants to test it out. I'm not sure if apt update will recognize it as an update

**Comment by Deekerman** [comment]
> Thanks @danmed I found that I can pass a flag in to `dpkg-deb` to change the compression method from `zstd` to `xz`
> 
> I just re-packaged v2.8.0 if anyone here wants to test it out. I'm not sure if apt update will recognize it as an update

I'm willing to give it a go but I feel like you want someone who is better versed in well, everything. Lol. But if you make a script I'll run it. Worst case deploy a back up lol.

**Comment by danmed** [comment]
> Thanks @danmed I found that I can pass a flag in to `dpkg-deb` to change the compression method from `zstd` to `xz`
> 
> I just re-packaged v2.8.0 if anyone here wants to test it out. I'm not sure if apt update will recognize it as an update

Nice, do i need to do anything seeing as i upgraded to Debian 12 and started fresh?  (btw.. your backup functionality is awesome.. literally had me back up and running in minutes!)

**Comment by advplyr** [comment]
I don't think the original issue exists on Debian 12 as per that stackexchange you shared.

If anyone still on Debian 11 can pull the package again that will let us know if my update fixed it. The debian package for 2.8.0 is replaced in the PPA repo already https://github.com/advplyr/audiobookshelf-ppa so doing an apt update, apt install audiobookshelf should do the trick.

**Comment by Deekerman** [comment]
Updated

**Comment by advplyr** [comment]
Great, thanks!
