### ISSUE TITLE
[Bug]: Docker update fail arm v7

### ISSUE THREAD

**Issue by Thomas-O** [advplyr/audiobookshelf#2637]
### Describe the issue

Just tried and failed to update 2.72 to 2.80.

_no matching manifest for linux/arm/v7 in the manifest list entries_

If support for v7 is being discontinued, is it possible to reinstall ABS v2.72 via Docker?

### Audiobookshelf version

2.80

### How are you running audiobookshelf?

Docker

**Comment by SAS-1** [comment]
Hi

Can't speak for the project, but arm V7 is old and alot of repos are dropping support have a look at https://www.linuxserver.io/blog/a-farewell-to-arm-hf 

> If your hardware is Armv7 or Armv6 you don't have a lot of options other than replacing it or accepting the risk and inconvenience of remaining on old versions of the images, the hardware simply doesn't support 64-bit.

to use 2.7.2 instead change your compose from latest (or whatever you use) to 
advplyr/audiobookshelf:2.7.2

should work

**Comment by advplyr** [comment]
Yeah arm7 is no longer supported

**Comment by DieselTech** [comment]
@Thomas-O Are you sure you're not just running a 32bit OS on x64 hardware? For example, even the RPI3 is a 64 bit CPU but for the longest time Raspbian was only a 32 bit OS. There is even some updated versions of the Pi 2 (v1.2) that have the 64 bit CPU. You might just need to do a fresh OS install with the 64 bit OS in order to keep using things.

**Comment by Thomas-O** [comment]
> @Thomas-O Are you sure you're not just running a 32bit OS on x64 hardware?

It's a Cubox-i2 (2013) with an armv7l processor. I'm using DietPi to host the docker. The DietPi image converted from Armbian 32bit using the DietPi script.

Guess I'll just have to accept that it's doomed to be another paperweight. Pity because the device still has more than enough grunt to host my Audiobookshelf, Jellyfin and Squeezebox servers.
