### ISSUE TITLE
Bug: Serieslist repeats entries after 100

### ISSUE THREAD

**Issue by mx03** [advplyr/audiobookshelf#264]
Url: /library/XXXX/series/XXXX

There are 224 entries in the series, but after 100 entries it starts again with the first (and the same api call is requested again, even the first request already has all 224 entries)

**Comment by advplyr** [comment]
Ah yeah I know what happened. I didn't even think of a series with so many books. This is a quick fix.

**Comment by advplyr** [comment]
This is included in `v1.6.48`
