### ISSUE TITLE
[Enhancement]: Editing User's "Tags Accessible to User"

### ISSUE THREAD

**Issue by MrBearedJoe** [advplyr/audiobookshelf#2667]
### Describe the feature/enhancement

It would be nice, **when editing a user's "Tags Accessible to User",** for them to be in alphabetical order and searchable just like when adding Tags to a book.

**Comment by advplyr** [comment]
Updated in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)
