### ISSUE TITLE
[Enhancement]: audiobookshelf logo or name on the login screen

### ISSUE THREAD

**Issue by PulsarFTW** [advplyr/audiobookshelf#2682]
### Describe the feature/enhancement

It was pointed out on discord that the login page has not identification to tell you what you’re logging in to. 

It might be nice to have text or the ABS logo on this page by the “Login” heading. 

![IMG_1595](https://github.com/advplyr/audiobookshelf/assets/115924048/4f6c2bc0-8a7e-4663-8a03-82e2b88454e9)

**Comment by mfcar** [comment]
Last year, I began working on adding 2FA support (I need back to this task). I made some changes to the login page as well. 
I will isolate the login page and create a pull request to asking feedback

<img width="1262" alt="Screenshot 2024-02-28 at 19 23 44" src="https://github.com/advplyr/audiobookshelf/assets/814828/b0dad3e3-e7fe-4c50-a520-bfeca14062d8">

**Comment by advplyr** [comment]
Updated in [v2.8.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.1)
