### ISSUE TITLE
[Bug]: When editing chapters, hitting tab for next field skips the timestamp column

### ISSUE THREAD

**Issue by DavidPesticcio** [advplyr/audiobookshelf#2685]
### Describe the issue

While editing the chapter details you are unable to use tab to access the timestamp column.

### Steps to reproduce the issue

1. From Home or Library view, select the "Pencil" of item cover
2. Select "Chapters" tab
3. Select "Edit Chapters"
4. Select first chapter "TITLE"
5. Attempt to tab into the START (timestamp) column either forward or backwards
6. Observe that you are unable to access in either direction with TAB or SHIFT-TAB

### Audiobookshelf version

2.8.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
