### ISSUE TITLE
[Bug] Audiobook length wrong (only some books)

### ISSUE THREAD

**Issue by pardofelis** [advplyr/audiobookshelf#2689]
Dear advplyr, dear folks who made this project possible,

first of all: Thank you for your time you put into this project. 

Sadly, my library has sometimes a wrong audiobook length for some books.

### Steps to reproduce - Type 1: Missing audio files

1. I have scanned  a folder containing multiple folders, each containing exactly 1 audiobook.
2. The mp3 files in it are following always the same naming: %Author% %Album% - %Track%.mp3 [even renaming them to %Track% - %Album%.mp3 didn't help]
3. When looking into the File Tab, there are all files visible and all audio files (e.g. 1-10) are shown as type "audio"
4. When looking into the Chapter Tab, there is a length calculated that is way *shorter* than the length of all audio files and there are *tracks "randomly" missing*. E.g. chapter 1,2,4,5,6,7,9,10 is available, but chapters 3 and 8 are missing.
5. This doesn't apply to every book, but in my case, I found 3 books (out of 30) that share this problem.

Ways I tried to get past this - and to add them to the library:
- Delete the book in the library and rescan the whole library
- Clicking the "Re-Scan" in the Edit Details Panel
- Rename the files and Re-Scan
- Retagging the files  and Re-Scan
Sadly, all of that didn't help.

### Expected behaviour
- Every audio file is added to the track list and the audiobook has the right playing length
### Actual behaviour
- Some audio files are not added and the audiobook is way shorter than the length of all audio files (because of the missing files)

### Steps to reproduce - Type 2: Audiofiles with wrong length — Solved

1. I have scanned  a folder containing multiple audiobooks.
2. The mp3 files in it are following always the same naming: %Author% %Album% - %Track%.mp3 [even renaming them to %Track% - %Album%.mp3 didn't help]
3. When looking into the File Tab, there are all files visible and all audio files (e.g. 1-10) are shown as type "audio"
4. When looking into the Chapter Tab, there is a length calculated that is way *longer* than the length of all audio files and *some files show a length way more than when checking them on VLC Player, Windows Details or TagScanner*. This results in my case in an audiobookt with twice the length than it actually has. 
5. This doesn't apply to every book, but in my case, I found 1 book with this problem.

Ways I tried to get past this - and to add them to the library:
- using mp3val, I was able to repair the mp3 file.

### Expected behaviour
- Every audio file is added to the track list and the audiobook has the right playing length
### Actual behaviour
- Some audio files show an incorrect length and the audiobook is way longerthan the length of all audio files (because of the wrong times)

### Environment data

Audiobookshelf Version:
v2.8.0 windows

Any suggestions how to solve these inconsistences is highly appreciated.
Have a nice day and thank you for your time

sincerely pardofelis

**Comment by advplyr** [comment]
This turned out to be an issue specific to ffprobe 6.1 so I updated the binary manager to only accept 5.1 for now until we can determine if it is a bug with ffprobe.

https://github.com/advplyr/audiobookshelf/commit/d2b006b909f2b3ab2569e3929f8018aeb342fe75

**Comment by advplyr** [comment]
Fixed in [v2.8.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.1)

**Comment by cooperferguson42** [comment]
I'm having a similar issue. A single m4b file that is about 31 hours long is reading in Audiobookshelf as only about 4 hours. My current Audiobookshelf version is 2.17.7.

**Comment by nichwall** [comment]
> I'm having a similar issue. A single m4b file that is about 31 hours long is reading in Audiobookshelf as only about 4 hours. My current Audiobookshelf version is 2.17.7.

This is most likely due to having bad metadata in the files. https://www.audiobookshelf.org/guides/ffprobe

**Comment by unitedchic10** [comment]
> > I'm having a similar issue. A single m4b file that is about 31 hours long is reading in Audiobookshelf as only about 4 hours. My current Audiobookshelf version is 2.17.7.
> 
> This is most likely due to having bad metadata in the files. https://www.audiobookshelf.org/guides/ffprobe

I also am having a similar issue however the audiobook in question is showing as 7hrs23mins when in fact the file is 36hrs03mins, Im currently using version 2.20.0

**Comment by cshaa** [comment]
I'm also having this problem. The penultimate chapter is listed as having the same length as the last one, even though it is, in fact, 49 minutes long.

![Image](https://github.com/user-attachments/assets/2d570bf5-dafe-45d7-a1d7-02524da117e6)

Downloading the penultimate chapter and checking it with ffprobe shows the correct length.

**Comment by kirillsimin** [comment]
Not a fix, but a **workaround** I have found is to re-encode the mp3 with ffmpeg. I think audiobookshelf was getting tripped up by the header, even though I didn't see anything weird in ffprobe.

```
ffmpeg -i "original.mp3" \
  -codec:a libmp3lame -b:a 128k \
  -map_metadata -1 -map_chapters -1 \
  "original_clean.mp3"
```
