### ISSUE TITLE
[Bug]: Server crashes

### ISSUE THREAD

**Issue by digitalwm** [advplyr/audiobookshelf#2693]
### Describe the issue

FATAL: [Server] Unhandled rejection: TypeError: Cannot read properties of undefined (reading 'authors'), promise: Promise {
audiobookshelf  |   <rejected> TypeError: Cannot read properties of undefined (reading 'authors')
audiobookshelf  |       at BookScanner.scanNewBookLibraryItem (/server/scanner/BookScanner.js:446:86)
audiobookshelf  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
audiobookshelf  |       at async LibraryItemScanner.scanNewLibraryItem (/server/scanner/LibraryItemScanner.js:178:24)
audiobookshelf  |       at async LibraryScanner.scanFolderUpdates (/server/scanner/LibraryScanner.js:584:30)
audiobookshelf  |       at async LibraryScanner.scanFilesChanged (/server/scanner/LibraryScanner.js:385:33)
audiobookshelf  | } (Server.js:166)

### Steps to reproduce the issue

1. Matching a book using audible.com

### Audiobookshelf version

v2.8.0

### How are you running audiobookshelf?

Docker

**Comment by mikiher** [comment]
Looking at the stack trace, the crash seems to have happened not while matching, but while the library watcher was adding a new book (but perhaps both things happened around the same time). The error itself is also very odd.

Can you please attach the full log file so I can examine what led up to the crash? you can find it under <your_metadata_dir>/logs/daily

**Comment by digitalwm** [comment]
[2024-03-01.txt](https://github.com/advplyr/audiobookshelf/files/14473550/2024-03-01.txt)

**Comment by mikiher** [comment]
Thanks. In your server settings, Do you have "Store covers with item" enabled?

**Comment by digitalwm** [comment]
Yes I do.

**Comment by digitalwm** [comment]
Hi, thank you for your detailed response and workaround. 
Also thank you in advance for the fix.

**Comment by advplyr** [comment]
Fixed in [v2.8.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.1)
