### ISSUE TITLE
[Bug]: Matched Covers lost

### ISSUE THREAD

**Issue by BumbleCast** [advplyr/audiobookshelf#2697]
### Describe the issue

After upgrading to v.2.8 (deployed via docker), some of my Podcasts do not keep the covers after matching them.
The podcast is correctly identified and I save these changes (save & close). But as soon as a new episode is added, the Cover and all the other information is lost again. It before migrating to 2.8 (your maybe before migrating to the new DB structure).

I tried removing the podcast, and re-adding everything. It did not work.

![2024-03-03 10_11_31-Audiobookshelf - Chromium](https://github.com/advplyr/audiobookshelf/assets/112068435/df3f2e09-20e0-43c8-90d5-ce84483b0057)
![2024-03-03 10_11_47-Audiobookshelf - Chromium](https://github.com/advplyr/audiobookshelf/assets/112068435/06d1a69f-aa31-4c91-b365-d5664eb58aa0)
![2024-03-03 10_10_31-Audiobookshelf - Chromium](https://github.com/advplyr/audiobookshelf/assets/112068435/084e5d46-bcb3-4774-9ae8-ff9c70bb8f3f)

### Steps to reproduce the issue

1.  Add podcast (I download them using a different program)
2. Match podcast info to get Cover and other meta data
3. Loose cover and data after adding an additional episode
4. Rinse and repeat

### Audiobookshelf version

2.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you check the server logs to see if you are getting permission errors?

Assuming you don't have the server setting enabled "Store covers with item" the covers will be stored in your `/metadata/items/<item id>` folder. You can find the id of the podcast library item in the URL when you navigate to the podcast page.
One test you can do is find that folder and note that the cover is there, then add a new episode and see what happens to the cover. You can also watch the server logs when you do that and look for errors.

**Comment by BumbleCast** [comment]
> Can you check the server logs to see if you are getting permission errors?
> 
> Assuming you don't have the server setting enabled "Store covers with item" the covers will be stored in your `/metadata/items/<item id>` folder. You can find the id of the podcast library item in the URL when you navigate to the podcast page. One test you can do is find that folder and note that the cover is there, then add a new episode and see what happens to the cover. You can also watch the server logs when you do that and look for errors.

Thanks for the quick reply. I was indeed a permission error. I changed the permission before adding the new podcast episode and it works flawless now. Thanks!
