### ISSUE TITLE
Users can't always see audiobooks

### ISSUE THREAD

**Issue by alexpegrum** [advplyr/audiobookshelf#27]
Just set up audiobookshelf in a docker container, works great when signing in as root but the other user couldn't see the audiobooks. I created another user for testing and that user could see the audiobook - refreshing the library did nothing. In this screenshot you can see me signed in to the main user in one tab and the root user in another. 
![image](https://user-images.githubusercontent.com/48214476/132593200-1896d0a3-a08d-42d0-827f-67b434912bcf.png)

Please let me know if you need any more info for diagnosis.

**Comment by advplyr** [comment]
Looks like something went wrong with the auth token for that user.
If you look at the docker logs and refresh the page you would see something like "Invalid token for request".

If that is the case, then try creating another user which will get a fresh auth token.
If not, share whatever error is showing up when refreshing.

**Comment by alexpegrum** [comment]
Thank you that is exactly what was happening, I deleted the user and created them again and it seems to be working. Is there anything I can do to stop it happening in future or is it just a bug on the software end at the moment? 

Thanks again

**Comment by advplyr** [comment]
There was a bug with the tokens on an earlier version, so it shouldn't happen with any new users. Just make sure you have the latest version and you are good to go.
