### ISSUE TITLE
[Bug]: Author text input gets clipped when editing book details

### ISSUE THREAD

**Issue by mikiher** [advplyr/audiobookshelf#2700]
### Describe the issue

When you manually type a new author name, after typing a few letters, the ending gets clipped and you don't see what you type until you press Enter (and then the Authors field is populated correctly with the full author name you typed).

While typing, all the letters you typed briefly flicker on and then get truncated.

### Steps to reproduce the issue

1. Open a book's details tab
2. Go the Authors field
3. Add a new author by typing it manually (e.g. "J. K. Rowling")
4. After typing the name, but before hitting Enter, the field looks like this:
<img width="166" alt="Screenshot 2024-03-03 224218" src="https://github.com/advplyr/audiobookshelf/assets/22557398/045a3737-0928-47df-8c45-73a606c4d1dd">

5. After hitting Enter, The field is correctly populated, like this:
<img width="158" alt="Screenshot 2024-03-03 224600" src="https://github.com/advplyr/audiobookshelf/assets/22557398/b3582327-f58d-476e-a6fd-bc8f8ae8faa7">

### Audiobookshelf version

v2.8.0

### How are you running audiobookshelf?

Built from source

**Comment by advplyr** [comment]
I noticed that recently also. I may have broken something because that wasn't always the case.

**Comment by mikiher** [comment]
Analysis:

In MultiSelectQueryInput.vue, when a new letter is pressed, we call setInputWidth, which registers a function to recalcualte and set the width after 50 ms. That function is called and sets a correct value. 

However after that, some other code (I have not identified exactly which, but I suspect it is some internal Vue framework code, perhaps the one that takes care of reacting to the input box v-model change) is changing the width back to its default value, which is 40px. 

The above causes for the flicker (because the width property changes value twice) and the truncation (since the final width value is always 40px).

**Comment by mikiher** [comment]
Resolution:

After trying to fix this by increasing the setTimout time (which works but, looks ugly and also flickers), I found that `width` has a `fit-contents` property. I set the initial element style to `width: fit-contents`, and removed the call to setInputWidth altogether. This seems to work perfectly.

I will send a PR.

**Comment by mikiher** [comment]
I noticed that the Geners, Tags, and Narrators suffer from the same issue (in MultiSelect.vue). I will fix there as well.

**Comment by advplyr** [comment]
Fixed in [v2.8.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.1)
