### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dawnsummit** [advplyr/audiobookshelf#2712]
### Describe the issue

the cover cannot be updated normally after matching.
the log shows http not supported.   possible reason is that I am using a http proxy.

### Steps to reproduce the issue

1. choose one book
2. click the match button.
3. select to update the book information, and it prompts the cover can not be updated and all item details are already updated.
![屏幕截图 2024-03-06 181342](https://github.com/advplyr/audiobookshelf/assets/172002/40df6acf-2e34-4fdf-8130-f1341de58532)

### Audiobookshelf version

2.8.0

### How are you running audiobookshelf?

Docker

**Comment by mikiher** [comment]
Can you please attach the relevant logs?
