### ISSUE TITLE
Library Empty

### ISSUE THREAD

**Issue by brianalsum** [advplyr/audiobookshelf#272]
Im running ABS on a a docker on an unraid machine.

I have 100's of books in my library folder, and they show up in collections and series but the library section on ABS is empty... why?

I have books organized as i saw on the file layout section:
Author/Series/Book Name/Bookfiles.m4b

**Comment by mx03** [comment]
Something in your log?

**Comment by brianalsum** [comment]
I ended up deleting the docker and re installing it... new issues
