### ISSUE TITLE
[Bug]: failed to download cover image via url

### ISSUE THREAD

**Issue by yefoenix** [advplyr/audiobookshelf#2729]
### Describe the issue

![1710122227296_d](https://github.com/advplyr/audiobookshelf/assets/8215230/18a162f8-ca9b-43d8-b9a6-ce2e319bede7)
As you can see, I filled a https image url to update the podcast cover, but it gave an err message:
`Failed to download image from url: Protocol "http:" not supported. Expected "https:"`
The log shows:

> {"timestamp":"2024-03-11 10:53:59.766","source":"    at Logger.debug (C:\\snapshot\\audiobookshelf\\server\\Logger.js)","message":"[LibraryItemController] Requesting download cover from url \"https://bts-image.xyzcdn.net/aHR0cHM6Ly9pbWFnZS54eXpjZG4ubmV0L0ZyMDNsM2dIVnMxRUVQRWhkZXN1eUpycGN1Zk4ucG5n.png\"","levelName":"DEBUG","level":1}
{"timestamp":"2024-03-11 10:53:59.767","source":"    at Logger.debug (C:\\snapshot\\audiobookshelf\\server\\Logger.js)","message":"[fileUtils] Downloading file to C:/Apps/AudioBookShelf/win/metadata/items/b6eb8cf9-99d0-4a9e-966a-0ca4b0ef11e2/cover","levelName":"DEBUG","level":1}
{"timestamp":"2024-03-11 10:53:59.769","source":"    at Logger.error (C:\\snapshot\\audiobookshelf\\server\\Logger.js)","message":"[fileUtils] Failed to download file \"C:/Apps/AudioBookShelf/win/metadata/items/b6eb8cf9-99d0-4a9e-966a-0ca4b0ef11e2/cover\" TypeError [ERR_INVALID_PROTOCOL]: Protocol \"http:\" not supported. Expected \"https:\"","levelName":"ERROR","level":4}
{"timestamp":"2024-03-11 10:53:59.769","source":"    at Logger.error (C:\\snapshot\\audiobookshelf\\server\\Logger.js)","message":"[CoverManager] Download image file failed for \"https://bts-image.xyzcdn.net/aHR0cHM6Ly9pbWFnZS54eXpjZG4ubmV0L0ZyMDNsM2dIVnMxRUVQRWhkZXN1eUpycGN1Zk4ucG5n.png\" Protocol \"http:\" not supported. Expected \"https:\"","levelName":"ERROR","level":4}

### Steps to reproduce the issue

1.  Fill in an image url
2. submit

### Audiobookshelf version

V 2.8.0

### How are you running audiobookshelf?

Windows Tray App

**Comment by advplyr** [comment]
I wasn't able to reproduce this with the image url you provided. Have you tested with any other urls and having this issue?

**Comment by yefoenix** [comment]
After searching the issue list and testing, I confirmed that this bug originates from http proxy.
So just waiting #2666 merged.
