### ISSUE TITLE
[Enhancement]: Add  Element for Creator

### ISSUE THREAD

**Issue by torchyboy** [advplyr/audiobookshelf#2746]
### Describe the feature/enhancement

Add an element for the creator of the of a book. This is needed for characters that are continued by different authors, such as the Jason Bourne series which has been continued after the death of its creator, Robert Ludlum. opf has an attribute for creator in opf:role: 
<dc:creator opf:role="creator"></dc:creator>.

**Comment by advplyr** [comment]
Where do you see this information being shown in the UI?

**Comment by torchyboy** [comment]
After the author and narrator

**Comment by advplyr** [comment]
Would that be shown for all books or is this something specific to series?

**Comment by torchyboy** [comment]
It should be shown when it is populated even if there is not series because it seems possible that a creator's work may be used in a work that is not part of a series. Such as Larry Niven's Tales of the Known Universe characters could be used by a new author in a stand alone novel.

**Comment by torchyboy** [comment]
I provided an update on this issue 5 days ago, but it's still showing as waiting. Is there additional info you're waiting for?

Regards

**Comment by advplyr** [comment]
I don't understand what the creator field on the book would have to do with series. I'm not sure what would need to be implemented here

**Comment by torchyboy** [comment]
ok, creator field on a book is probably the better fit than on a series.

**Comment by nichwall** [comment]
Does adding them as a second author not work? (such as Robert Jordan for the Wheel of Time books that Brandon Sanderson wrote)
