### ISSUE TITLE
[Bug]: wma can't play in web

### ISSUE THREAD

**Issue by mysll** [advplyr/audiobookshelf#2748]
### Describe the issue

The files is wma, open in web can't play. always show loading state or play few seconds then pause and no sound, log prints STREAM-CHECK check files. When close web and reopen STREAM_CHECK progress will restart from begin.
![2024315-212518](https://github.com/advplyr/audiobookshelf/assets/3783323/890e930f-eb56-4ef3-9736-ef60c9a770c0)

Play in android app it works,by the way can play before update . I'm not sure  it's due to an upgraded version. my version is v2.8.0 and use docker.

### Steps to reproduce the issue

1. open  wma audio in web

### Audiobookshelf version

v2.8.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.8.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.1)
