### ISSUE TITLE
[Enhancement]: Theming system for web app

### ISSUE THREAD

**Issue by SurjitSahoo** [advplyr/audiobookshelf#2754]
### Describe the feature/enhancement

- Option to integrate 3rd party community themes into the web-app
- Audio visualisers + option to add 3rd party visualisers.

**Comment by nichwall** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1705

**Comment by advplyr** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1705
