### ISSUE TITLE
[Bug]: Can't add/edit series

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#2755]
### Describe the issue

When trying to add or edit a series on a book, the Submit-button is dead

### Steps to reproduce the issue

1. Open up a book for editing metadata
2. Try to add a series

### Audiobookshelf version

v2.8.0

### How are you running audiobookshelf?

Docker

**Comment by ScuttleSE** [comment]
Slight correction

I can add a series if I pull the metadata from Audible, but I can not manually add a series to a book.

**Comment by ScuttleSE** [comment]
After some manual digging in the database I found a series without a name, after deleting that, it started working again...I have no idea how that series ended up in the database... in the web UI it was simply named "null"

**Comment by advplyr** [comment]
I wonder if you still have some left over oddities from when you migrated the db. I remember your migration being a difficult one.

**Comment by ScuttleSE** [comment]
The migration was never an issue. 
The problem seems to be that somewhere along the line, things in the database that was OK in older versions were changed, but ABS doesn't seem to have "sanitized" the data, and when the UI hits one of these old entries, it doesn't know how to deal with it.

**Comment by advplyr** [comment]
I remember there was something going on where you were going back and forth between versions but anyway yeah the migration script wasn't checking every possible scenario. It shouldn't have been possible to add an empty series. Do you have any thoughts on if the empty series was added a while ago or recently? Maybe you haven't used that series dialog in a while which might suggest the series was migrated over
