### ISSUE TITLE
[Enhancement]: Really hope to add the function to skip the intro and outro of audiobooks.

### ISSUE THREAD

**Issue by xyswordzoro** [advplyr/audiobookshelf#2761]
### Describe the feature/enhancement

Many audiobook intros contain advertisements, etc. I hope to be able to manually set to skip intros. Thank you very much.

**Comment by nichwall** [comment]
Delicate of https://github.com/advplyr/audiobookshelf/issues/2203

**Comment by advplyr** [comment]
Duplicate of #2203
