### ISSUE TITLE
[Bug]:  no matching manifest for linux/arm/v7

### ISSUE THREAD

**Issue by Flopsipopsi** [advplyr/audiobookshelf#2763]
### Describe the issue

Hi guys. I'm running Audiobookshelf on a Raspberry Pi 4 4gb. Since the version 2.8.0, the output of

```dockerfile
docker-compose pull
``` 
is: 

ERROR: for audiobookshelf  no matching manifest for linux/arm/v7 in the manifest list entries
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

I know the note that since v2.8.0 armv7 is no longer supported. But the output of

```dockerfile
docker info --format '{{ .OSType }}/{{ .Architecture }}'
```  
is:
linux/aarch64

Thats is my docker-compose.yml file:

```dockerfile
version: '3.5'
services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    ports:
      - 13378:80
    volumes:
      - /media/ext_festplatte2/Hoerbuecher:/audiobooks
      - /home/pi/audiobookshelf/podcasts:/podcasts
      - /home/pi/audiobookshelf/config:/config
      - /media/ext_festplatte2/Hoerbuecher/metadata:/metadata
      - /media/ext_festplatte2/Hoerbuecher:/Hoerbuecher
``` 

So I'm trying to solve this problem since days but I can't solve it... Do you have any solution other than change Hardware? Thank you very much!

### Steps to reproduce the issue

```dockerfile
docker-compose pull
``` 

### Audiobookshelf version

v2.8.2

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Support for arm v7 was dropped in 2.8.0. You will need to switch to a 64 bit OS or run from source.

https://github.com/advplyr/audiobookshelf/issues/2637
