### ISSUE TITLE
Reverse Proxy - Subdirectory

### ISSUE THREAD

**Issue by mediacowboy** [advplyr/audiobookshelf#277]
While I have this working with the SWAG example configuration. I am wondering if it is possible to all the app to have a base_url so that it can be used with a  subdirectory?

Ex.
Instead of https://audiobookshelf.abc.xyz it could be https://abc.xyz/bookshelf

**Comment by advplyr** [comment]
It is not supported. If this was added to the server it would break all the links used in the mobile app.
Is this something you do for other servers? I would be curious to how they handle that.

**Comment by mediacowboy** [comment]
> It is not supported. If this was added to the server it would break all the links used in the mobile app.
> Is this something you do for other servers? I would be curious to how they handle that.

Understandable and this doesn't need to be implemented right away.

Yes I use sub directories with all most of my services. The *arrs, deluge, etc.

**Comment by mx03** [comment]
Should work with nginx proxy pass, it automatically rewrite the url. Only problem could be the web socket.

**Comment by mediacowboy** [comment]
> Should work with nginx proxy pass, it automatically rewrite the url. Only problem could be the web socket.

I believe this to be the case. As I can navigate there via abc.xyz/audiobookshelf but I get just a spinning circle. When I look at the development console of Chrome I see it is unable to reach /__nuxt/randomnamem.js.

**Comment by advplyr** [comment]
Consolidating subdirectory issues to #385
