### ISSUE TITLE
[Bug]: When enabling/diabling library watcher, change does not take effect until server restart

### ISSUE THREAD

**Issue by mikiher** [advplyr/audiobookshelf#2775]
### Describe the issue

When you enable or disable folder watcher for a library,  the change doesn't acrually happen until server restart.

We should at least let the user know they should restart the server for the change to take effect.

### Steps to reproduce the issue

1. Enable or disable a library's folder watcher through the library setting "Enable folder watcher for library".
2. Save.

The server now requires a restart for the setting to take effect (if disabled, watcher still listens and acts on changes. If enabled, watcher is not set up until server restart).

### Audiobookshelf version

v2.8.1

### How are you running audiobookshelf?

Built from source

**Comment by advplyr** [comment]
Fixed in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)
