### ISSUE TITLE
[Bug] Cosmetic/programmatic inconsistency when viewing audiobook details

### ISSUE THREAD

**Issue by DavidPesticcio** [advplyr/audiobookshelf#2778]
### Steps to reproduce

1. View audiobook details in mobile app
2. Observe the order of items;
3. "Chapters", "Audio Files", "Ebook Files"
4. This is in contrast to the order of items in the web browser which shows;
5. "Audio Files", "Chapters", "Edook Files"

### Expected behaviour
- The order of items in the web browser and mobile app should be the same

### Actual behaviour
- The order of items in the web browser and mobile app are not the same

### Environment data

Audiobookshelf Version: 0.9.72-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Pixel 6 Pro

Stock or customized system: Stock

**Comment by advplyr** [comment]
Thanks, I thought it made the most sense to show chapters first then audio tracks.

**Comment by advplyr** [comment]
Updated in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)
