### ISSUE TITLE
[Bug]:  2.8.1 (Docker) Library Scan Fails Getting Repeated "alert number 12" in log file

### ISSUE THREAD

**Issue by freddyyeddy** [advplyr/audiobookshelf#2782]
### Describe the issue

When triggering library scan (using NFS so I cant trust auto scans) It throws The Errors Below. Im gonna let it take forever and see if it finally finishes and detects the one New audiobook. After Looking at Debug log it looks like more work than dont (Second Image). So I suspect this could be a red herring.
![image](https://github.com/advplyr/audiobookshelf/assets/26309499/43ea4e05-f0ed-4ed9-8e4e-23f7a972f6c0)
![image](https://github.com/advplyr/audiobookshelf/assets/26309499/e9dcf276-3576-42f4-9206-4f7f4cff57c0)

### Steps to reproduce the issue

1. Manually Trigger Library Scan And Watch.

### Audiobookshelf version

1.8.2

### How are you running audiobookshelf?

Docker

**Comment by freddyyeddy** [comment]
Update With It finished (First Image) and picked up the new Book. But it seems needlessly long for a simple single book find. Has there been a change to the scan methodology that affects if pre-existing books are re-checked after updating. The second scan seems more reasonable (Second Image). So I assume It has to do with how the update process (re-pull/build container for latest version). If Im right might be worth updating the Change notes for clarity. Im closing this ticket myself as seems problem did not persist.
![image](https://github.com/advplyr/audiobookshelf/assets/26309499/7bce7f82-8209-458a-8352-5c0e46f22473)
![image](https://github.com/advplyr/audiobookshelf/assets/26309499/be6ea68f-5566-4019-8bbd-fd31c1be8389)

**Comment by freddyyeddy** [comment]
I seems this is still happening and I can no longer search Audible For Meta data either

**Comment by nichwall** [comment]
Looks like TLS error 112 is something specific to your setup, or an issue with Audnexus?

https://stackoverflow.com/questions/5671000/what-does-this-tls-alert-mean

**Comment by freddyyeddy** [comment]
I cant Seem to find any real reason for this to happen. All I did was update docker image to new version. Then it started happening. Got any tips for where to look. I basically turned off the firewall for the server. So I dont think its bocking there. I recently moved to using ngix proxy manager. But the reverse proxy has been fine there too. This happens when I attempt to search for a match.
![image](https://github.com/advplyr/audiobookshelf/assets/26309499/f5740a30-d852-4a25-abb8-58637fb8e2b3)

**Comment by advplyr** [comment]
Are you getting this error using a local ip address?

**Comment by freddyyeddy** [comment]
No I'm using a DNS to access the instance via reverse proxy (web socket
enabled)

**Comment by freddyyeddy** [comment]
Checking Via Local IP:Port and still same same (Searched different book this time)
![image](https://github.com/advplyr/audiobookshelf/assets/26309499/9f1c9640-b5df-41c6-9319-3eb8bc90c5d3)

**Comment by freddyyeddy** [comment]
No problem. I am unsure what directly was causing the issue but Its been
resolved. Thanks for the help and support. Sorry I left this go stale and
never followed up.
