### ISSUE TITLE
[Enhancement]: add webp image support for cbz files?

### ISSUE THREAD

**Issue by gotbletu** [advplyr/audiobookshelf#2792]
### Describe the feature/enhancement

cbz with webp images does not work when using the webui to read the comic.
please make it work =)

P.S i convert all my images to webp, since it saves me a lot of hard drive space vs png/jpg

**Comment by advplyr** [comment]
Can you send me one of these comics for testing? Via email to dev@advplyr.com or on Discord

**Comment by advplyr** [comment]
Disregard, it was an easy update.

**Comment by advplyr** [comment]
Added in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)
