### ISSUE TITLE
Keyword Filter is too unforgiving because it is CaSe-SenSitiVe

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#28]
The Keyword Filter is meant to help find books quicker. However, anything other than a CASE-SENSITIVE match will yield no results. I wonder if the tolerance needs to be "loosened up" a bit by removing case-matching.

Exact Match result for "The Language":
![image](https://user-images.githubusercontent.com/25695143/132601865-0cb037a7-8d32-430b-85ac-951ffd7f217b.png)

Result for "language":
![image](https://user-images.githubusercontent.com/25695143/132602011-f3f5d66d-6ac9-4167-8965-b8699cc61f42.png)

**Comment by advplyr** [comment]
I agree with this and updated it in v1.1.3
