### ISSUE TITLE
[Enhancement]: Accessibility Tool Tips for audiobook details/links and playback control icons

### ISSUE THREAD

**Issue by DavidPesticcio** [advplyr/audiobookshelf#2800]
### Describe the feature/enhancement

Audiobook details/links, and Playback control icons do not have tool tips, whereas the other icons to the right of the playback dialog do. Adding these Tool Tips would be helpful to people that rely upon the accessibility details being present, and would potentially increase the audience for ABP.

**Comment by DavidPesticcio** [comment]
Details for the book title, author, and duration, and maybe something to describe the presence of an image would be helpful. Along with descriptions for each of the playback controls.

The third group of icons to the right each have their respective descriptions as a tooltip. It would be helpful, and consistent, if all the items related to the playback dialog had the same.

Also, I've just noticed that "View player queue" and "Playback speed" items are not accessible when using TAB, and the progression seems to be non-intuitive - i.e. the order goes left, right, middle for the three groups of items. :crying_cat_face: lol

**Comment by advplyr** [comment]
Updated in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)
