### ISSUE TITLE
Separate location for metadata

### ISSUE THREAD

**Issue by kabaga** [advplyr/audiobookshelf#2806]
### Describe the feature/enhancement

Would it be possible to add an option for a different location for metadata?
It would be nice to have this option especially for instances that the ABS doesn't have write access to the media directory. 

I would use my use case as an example. My ABS is a VM. The media is located in an NFS share that has only read-only. I have another NFS share with read/write for backups. For now, I have to manually import the audiobook covers so that ABS can read it.

**Comment by advplyr** [comment]
By default Abs does not store the metadata or covers with your media. They are stored in the `/metadata` folder. I may be misunderstanding what you are asking, do you have those 2 settings enabled in the server settings?

**Comment by kabaga** [comment]
I had a brain fart. I forgot the path was configured in the /etc/default/audiobookshelf file
