### ISSUE TITLE
[Bug]: Podcast already exists

### ISSUE THREAD

**Issue by kabaga** [advplyr/audiobookshelf#2809]
### Describe the issue

I am adding some podcast. But somehow I could not add Joe Rogan's. I was able to add it at first but it was not visible, so I tried to add it again. This time I was getting "Podcast already exists". I checked the podcast library and I could see the directory there, but not visible in the web UI.

I deleted the directory, but I was still getting the same error "Podcast already exists".

### Steps to reproduce the issue

1. Add Joe Rogan podcast
2. Click on Edit "pencil icon"
3. Go to the Match tab
4. Search for another podcast
5. Click on that podcast
6. Go to the Library and Joe Rogan podcast will not be visible
7. Go to Add and try to add Joe Rogan again then you will get the error

### Audiobookshelf version

8.8.1

### How are you running audiobookshelf?

Debian/PPA

**Comment by nichwall** [comment]
Can you look in the database to see if the podcast already exists?

You can also enable Debug logs in the server settings to help look for the cause.

**Comment by kabaga** [comment]
Can you point me how to check the database?
I checked the settings and didn't see any section that could point me to the database.

I installed ABS via apt https://www.audiobookshelf.org/docs/#linux-install-deb

**Comment by advplyr** [comment]
You can also see if it exists in your library by searching. You will see a green checkmark next to the title and clicking on the cover will redirect you to the podcast in your library. However, this typically happens when the folder already exists so even though you said you tried deleting it I would suggest double checking that.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/92819e33-f638-4909-8aa7-0248c9896a10)

**Comment by kabaga** [comment]
I do not see the green check mark when I search for it. 
![image](https://github.com/advplyr/audiobookshelf/assets/44072579/3ef7d6fd-7904-4b06-897a-f8c99586592d)

This is the library looks like:
![image](https://github.com/advplyr/audiobookshelf/assets/44072579/ce5e924a-40ee-4a44-9f3c-a389766d7c62)

**Comment by advplyr** [comment]
Do you have any other podcast libraries? I just checked and the only time that error is shown is if the database has a library item with the same "Podcast Path" that it is showing you in the UI.

**Comment by kabaga** [comment]
I only have two libraries - one for audiobooks and one for podcast.
Is there a way to fix the database?

**Comment by advplyr** [comment]
It is a sqlite database so you can open it up and look at it. If you don't have any software installed to open it up there are websites that allow you to view it. One is https://sqliteonline.com/

You upload your sqlite file in there and look at the libraryItems table for the record that has the same path.

**Comment by kabaga** [comment]
That worked. 

I downloaded the database and deleted Joe Rogan's line from libraryItems. I uploaded it back to the ABS server and replaced the original database with the edited version.  Thank you
