### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ylnest2018** [advplyr/audiobookshelf#2810]
### Describe the issue

Run library eBook library scan, it begins, then after ~900 I receive socket disconnected/reconnected (assuming this is the service crashing and restarting)

![image](https://github.com/advplyr/audiobookshelf/assets/150770555/c5680099-295a-4b18-9610-01219c63edda)

I told ABS to store metadata in the ebook folder as a way to see which way the read is going, then I noticed with goes Z>A, I removed the folder causing the crash and then it progressed 4 more books and then crashed again. appears to be some form of bug in this 2.8.1 and being that I am using an LXC Im not too sure how I downgrade so will just need to wait for a patch to be released.

![image](https://github.com/advplyr/audiobookshelf/assets/150770555/7957d5a4-34f9-43f6-a02f-2ba0c37a2388)

I cant see anything out of the ordinary on the books that it fails on. After I removed one it failed on, it progressed 4 more books then failed again so I have just given up a bit. someone else said he had the same and dropped to 2.8.0 to fix it. If I can provide any more info please ask and ill help

### Steps to reproduce the issue

1. Run library eBook library scan

### Audiobookshelf version

v2.8.1

### How are you running audiobookshelf?

Debian/PPA

**Comment by nichwall** [comment]
Could you provide one of the problem files?

**Comment by ylnest2018** [comment]
> Could you provide one of the problem files?

how should I upload as i get this error when uploading an epub

![image](https://github.com/advplyr/audiobookshelf/assets/150770555/40170dea-91c8-4bfb-8922-8da0713e646b)

**Comment by nichwall** [comment]
You could rename it to another extension if it is a public domain book, or send it to advplyr or myself through the e-mail on our GitHub accounts or through a DM on the ABS Discord.

**Comment by ylnest2018** [comment]
> You could rename it to another extension if it is a public domain book, or send it to advplyr or myself through the e-mail on our GitHub accounts or through a DM on the ABS Discord.

just checking you got the files I sent you to support the above

**Comment by nichwall** [comment]
> just checking you got the files I sent you to support the above

If you sent it to me I didn't get it.

**Comment by ylnest2018** [comment]
Fixed in 2.9.0
