### ISSUE TITLE
[Enhancement]: If ASIN is present, allow to provide link to Audible store page

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2812]
### Describe the feature/enhancement

One feature I would like to see is that, if a book data includes a ASIN number, (e.g. B002V8LA1W), there should be a link to allow someone to open up a new browser tab/window and open up https://www.audible.com/pd/B002V8LA1W which then redirects to a book's information page on Audible.

**Comment by advplyr** [comment]
What do you mean redirects to a book's information page? Do you mean redirects to the audible page?

**Comment by ZLoth** [comment]
Yes, that's correct.

**Comment by advplyr** [comment]
Where do you see this link being shown in the UI?

**Comment by ZLoth** [comment]
It's not being displayed in the UI. It's an enhancement request because the currently functionality does not exist. The ASIN is already being stored as part of the book metadata, and this is another use of said metadata.

**Comment by advplyr** [comment]
I know it doesn't exist, I'm asking where do you think this would be shown in the UI if it were to be added

**Comment by ZLoth** [comment]
In the mobile app... in the three dot menu → View on Audible

On the Web page.... as a Audible icon just to the left of the three dot menu.

**Comment by advplyr** [comment]
I think this is better something that gets put in by the user in the description if #1820 gets added. The reason is because we want to keep the UI clean and I think this is something few users would click on.
