### ISSUE TITLE
[Enhancement]: Add existing users to libraries

### ISSUE THREAD

**Issue by alfureu** [advplyr/audiobookshelf#2818]
### Describe the feature/enhancement

I searched the Github tickets, but was not able to find the solution. One can create a new user and associate libraries to the new user: https://www.audiobookshelf.org/guides/users/

However, I would like to add an existing user (without resetting password, reading progress) to a new library. Example: I have an existing Main library, accessible to admin and user1. User1 reads books, (s)he has progress that I do not want to delete. However, I want to add user1 to a newly created library "Podcast". 

I wasn't able to find an answer how to achieve this...

**Comment by jimski427** [comment]
In the user account settings there is a setting to access all libraries. If that is active, they can access everything. If it's not active you type in the libraries you want to give them access too. In your browser go to the gear icon in the top right, go to users, click the pencil on the user you want to edit, then you will see the "can access all libraries" option.

**Comment by alfureu** [comment]
Thanks, I was blind not noticing this setting, closing
