### ISSUE TITLE
ABS hangs while when adding books to a new collection..

### ISSUE THREAD

**Issue by brianalsum** [advplyr/audiobookshelf#282]
I had to delete my docker and rebuild ABS as the library was empty, I have solved that issues and now i have a new one. when ever I try to add books to a collection it hangs at the screen where it says "please wait" nothing shows up in the log and i've tried it under other users.. no joy

**Comment by advplyr** [comment]
Can you take a screenshot of the page where it is hanging

**Comment by brianalsum** [comment]
![Capture](https://user-images.githubusercontent.com/58796011/147895717-83268c96-7e6b-48b1-a4b1-9c67fef711dc.PNG)

**Comment by brianalsum** [comment]
So I actually just found a workaround. Make the collection using one book then add in the other books

**Comment by brianalsum** [comment]
Nope nevermind... now thats failing also

**Comment by mx03** [comment]
Get the same error with multiple books.

Does adding a single book with the 3dot menu in the corner of the cover "Add to Collection"? That works for me.
![image](https://user-images.githubusercontent.com/1390929/147922016-6d99cb80-ba46-4c35-b39d-31ecc7ec9a2b.png)

**Comment by brianalsum** [comment]
Yeah that worked? odd... I like ABS but they still have some work todo!

**Comment by advplyr** [comment]
We do have a lot of work to do! If only it was all as simple a fix as this one..
This is fixed in `v1.6.51`
