### ISSUE TITLE
[Bug]: Server fails to start on Arch Linux with "Pkg: Error reading from file."

### ISSUE THREAD

**Issue by michaelnew** [advplyr/audiobookshelf#2822]
### Describe the issue

After updating to 2.8.1, the server fails to start. The only line I see in the log is: `Pkg: Error reading from file`. This is on Arch Linux, and happens both when starting from a systemd service and when running the binary manually.

Wish I had more info to give, but I can't find anything else to go on.

### Steps to reproduce the issue

1. run `audiobookshelf` binary

### Audiobookshelf version

v2.8.1

### How are you running audiobookshelf?

Other

**Comment by advplyr** [comment]
Where did this binary come from?

**Comment by TillDiem** [comment]
Also run into this bug today. Was not able to determine the root cause, but the binary @michaelnew is talking about, very likely comes from https://aur.archlinux.org/packages/audiobookshelf-git 
Similar issue is noted there, and this is where I am running in to this issue.

**Comment by advplyr** [comment]
Thanks, I'm not sure who is managing that. You'll have to report the issue with them
