### ISSUE TITLE
[Enhancement]: Adjust fields on cover tab in item modal on narrow screen

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf#2832]
### Describe the feature/enhancement

When editing books on mobile, the fields on the Cover tab get squished.

![Cover tab](https://github.com/advplyr/audiobookshelf/assets/5686638/54398973-ee9a-46d0-913a-5a9085ae94fa)

I think it would be nice if the fields changed to several rows instead of columns when the screen is sufficiently small enough, similar to how the Match tab does it.

![Match tab](https://github.com/advplyr/audiobookshelf/assets/5686638/fe69ad49-9c6b-41d4-86ed-9698ef839bb0)

(Initially noticed from looking at https://github.com/advplyr/audiobookshelf-app/issues/1170)

**Comment by nichwall** [comment]
Reviewing the screenshot again, looks like there's an alignment issue with the current cover dimensions being behind the upload button as well.

**Comment by advplyr** [comment]
Cleaned it up a bunch

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/5b2a5de1-f168-4a40-8209-0b337125cc02)

**Comment by advplyr** [comment]
Updated in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)
