### ISSUE TITLE
[Enhancement]: Show Language on Audiobook Detail View

### ISSUE THREAD

**Issue by mutschler** [advplyr/audiobookshelf#2834]
### Describe the feature/enhancement

I cant seem to find any place where the Language is shown. I know i can use search to filter by language but there's no way to see the Language on the Books Detail view expect for hitting the Edit button and checking there.

Would be cool if Language would be displayed alongside other Metadata (maybe above the Duration?)

**Comment by advplyr** [comment]
Updated in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)
