### ISSUE TITLE
[Bug]: metadata.json not updated

### ISSUE THREAD

**Issue by richterma** [advplyr/audiobookshelf#2837]
### Describe the issue

When using the Settings / Item Metadata Utils to make changes to Tags/Genres or edit Author / Narrator information via the respective dialogs, the metadata for all affected books seems to be updated in the db.
However, at the same time, the metadata.json is not updated.

I have just noticed this after quite a big cleanup.
Apart from any potential solution for this ticket: Is there any way to force a re-write of all or all affected files?

### Steps to reproduce the issue

1. (Maybe relevant) Enable option to write metadata.json next to the library files.
2. Tag a book with Narrator "Mister Taipo".
3. Go to the Narrator tab. Edit "Mister Taipo", change it to "Mister Typo".
4. Check book info within Audiobookshelf and the metadata.json in the filesystem.

### Audiobookshelf version

v2.8.1

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Are you looking at the metadata JSON file located next to the media files, like `/audiobooks/Author/Book/metadata.json`, or are you looking in `/metadata/items/[uuid]/metadata.json`?

Do files exist in both locations, and if so is one of them being updated correctly, just not the one you expect?

**Comment by richterma** [comment]
I'm looking at the files in /audiobooks/*, which I enabled in the settings.
There are no files in /metadata/items (in fact, the directory doesn't even exist).

Looking at the delete function in AuthorController.js, I guess this actually is "as designed" in the current code. It seems like there just is no code to update the files.

**Comment by advplyr** [comment]
Fixed in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)
