### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by Beulu** [advplyr/audiobookshelf#2839]
### Describe the feature/enhancement

Is it possible to add collection for podcasts ? Wanna group them into host (Deezer, Spotify, Audible...) or group them with the main folder name ?

Thanks !

**Comment by advplyr** [comment]
Is using tags not suitable for this for you?

**Comment by Beulu** [comment]
I'm using Musicbee. Which tag is it ? Does ABS manage collection as audiobooks ?

**Comment by advplyr** [comment]
You create your own tags

**Comment by Beulu** [comment]
I've tried this for something else and it didn't seem to work.

A tag titled "collection" ?

**Comment by advplyr** [comment]
You would use a tag for each group that you want. "Deezer", "Spotify", etc. Then you can use the filters at the top of the library page to see all podcasts with that tag.

**Comment by Beulu** [comment]
Gor only "genre" and "tag" and the search doesn't work for it.Missing something ?

Want a screenshot of something ?

**Comment by nichwall** [comment]
I think the "tag" advplyr is referring to is the tags in ABS, not a media metadata tag like that.

Book metadata: https://www.audiobookshelf.org/docs#book-audio-metadata

Podcast metadata (may need some updates): https://github.com/advplyr/audiobookshelf/issues/1488

**Comment by Beulu** [comment]
Thanks Nichwall !

But I can't find in Musicbee performer tag, in the website help neither. Can I had in ABS :
#customtag1 = Service
#customtag2 = explicit content ect...

**Comment by advplyr** [comment]
I'm confused now on what you are requesting. Can you be more specific about the feature you want and how it would be used?

My suggestion has nothing to do with audio file meta tags. It was using the tagging system in Abs

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/7fc3e11b-4fd7-418f-9c56-24ebb6ef84a8)

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/a575085d-1a81-4179-84d6-06cc339a4f87)
