### ISSUE TITLE
[Bug]: Subtitle metadata overwriting description

### ISSUE THREAD

**Issue by Brancliff** [advplyr/audiobookshelf#2843]
### Describe the issue

I've manually tagged an example episode to get used to the tagging system here. While the docs note that the "description" field is based on the "description" metadata, my descriptions field is being replaced with whatever is in the "subtitle" field. It seems I can't have both. Attached is an image:

![description overriding](https://github.com/advplyr/audiobookshelf/assets/22332774/763520b0-0259-497a-8061-e37afd47deb7)

### Steps to reproduce the issue

1. Add "description" and "subtitle" metadata to a podcast episode, they should be different
2. Rescan the library
3. The description and subtitle fields on Audiobookshelf will instead be the same

### Audiobookshelf version

v2.8.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)
