### ISSUE TITLE
Support for Audiobooks.com API

### ISSUE THREAD

**Issue by misuchiru03** [advplyr/audiobookshelf#2844]
### Describe the feature/enhancement

I have found another audiobook website, audiobooks.com, that has an API that may be helpful in identifying audiobooks that aren't on current providers. https://api.audiobooks.com/api/v2/

I have a few books that are not available for matching anywhere else in current providers.

**Comment by advplyr** [comment]
This is not a public API. Users would have to reach out to support and get their own API key.

**Comment by misuchiru03** [comment]
I totally missed the big bold print. No worries then, I will close.
