### ISSUE TITLE
[Enhancement]: Support ASIN with lowercase characters in Audible Match

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2849]
### Describe the issue

One thing that I notice... if I have a ASIN code filled in, that the book matching is done by ASIN number rather than by the title, resulting in an exact match. However, if that ASIN code contains lowercase characters, then there is no match. Here is a recording of the issue using ASIN code B002V8H18I (or rather, B002v8h18i):

https://github.com/advplyr/audiobookshelf/assets/6700159/cd73c209-e501-431d-b5c6-a7247741c7c2

### Steps to reproduce the issue

1. Select and edit an existing book.
2. Change the uppercase characters of the ASIN code to lowercase (e.g. B002v8h18i), then click **Save**.
3. Click on the **Match** tab.
WHAT SHOULD HAPPEN: The ASIN should bring up a book match (e.g. Treasure Island)
WHAT REALLY HAPPENS: No match.
4. Go back to the **Details** tab.
5. Change the ASIN to all uppercase (e.g. B002V8H18I) and click **Save**. 
6. Click on the **Match** tab. 
7. The book matches as expected. 

### Audiobookshelf version

2.8.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Updated in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)

**Comment by ZLoth** [comment]
Looking forward to installing the updated docker container. Thank you.

**Comment by seannymurrs** [comment]
I'm not sure if the issue I'm experiencing is related to this or not, but it's the only thing I could find when I tried searching for what I'm seeing. When I try matching a book by ASIN, I'm getting "No Result". Even though I'm entering the ASIN in all caps, the logs show that it's searching Audnexus in all lowercase (which seems to be why I'm getting no result). This issue started yesterday afternoon, and I'm not sure how to troubleshoot further.

**Comment by advplyr** [comment]
The Audnexus API that is used to get audible data is currently down.
