### ISSUE TITLE
Download M4B timeout

### ISSUE THREAD

**Issue by szemlicka** [advplyr/audiobookshelf#286]
Hi,
I tried to download a huge audiobook (700MB) and its timed out. Is it possible to extend the timeout to one hour and the automaticly deletion of the file next day? Or, make it adjustable under system settings...:-)

**Comment by szemlicka** [comment]
Hi, I made some more tests. TRhe reason why it needs so long is that the process change the bit rate. That costs time and ressources. Is it possible to make it as an option to crunch everything in  one file without changing the bit rate.
And the file for download is .mp4 and not m4b. If I made it with an Ipad, its not possible to rename it after download. Can you change this too?

File size
Original ( 67 files, bit rate 192kb/s), 330MB)
.mp4 (m4B) one file, bit rate 67,2 kb/s, 115MB)

The convert to a lower bit rate is the reason for the time out.

**Comment by szemlicka** [comment]
Hi,
I checked this with version 1.6.58 and found an additional error. The mp3 tag are not fully used. I took a look to the corspondent metadata.txt file and found only following tags:
artist=Hanno Herzler
date=2012
comment=AudioBookshelf v1.6.58
genre=Audiobook

Gerne - why you do not use the original tag which is SCi-Fi for that audiobook
why you do not use album?

**Comment by advplyr** [comment]
The download feature needs a lot of work. It should be using the same tags that it parses from audio files.
I think the rename issue may be because of permissions? Will have to check that.

**Comment by advplyr** [comment]
I made 2 updates towards this issue in `v1.6.64`. Additional metadata tags to the m4b and setting the correct file permissions to the download so you can rename it.
The metadata tags I was able to use I got from https://wiki.multimedia.cx/index.php/FFmpeg_Metadata in the mp4 section.

The next part of this is to improve the encoding for performance

**Comment by advplyr** [comment]
The timeout time was extended a while ago to 20 minutes. There is another issue open for problems with the m4b merge performance that we can use as the main thread for that.
