### ISSUE TITLE
[Enhancement]: Have library stats display thousands with a comma

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2861]
### Describe the feature/enhancement

I've been uploading my Audible library to my own AudioBookShelf instance. One thing that I've noticed is that there is no "thousands" comma delimiter to make data easier to read.

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/fa32b492-f02a-410d-8149-e728e799efa7)

It would be nice if the display was closer to this....

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/3fd177c2-cbdf-4aac-be74-7647d0ce4335)

(Yes, I modified the HTML output to give example output)

**Comment by advplyr** [comment]
I also took some time to clean up the UI so the spacing is more even and they fit on one line.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/565439d6-df1b-4416-a8b7-5532423a9e92)

Uses the same locale set for the language

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/5c591f7a-9bbd-4755-b8cf-f5be2fadbec7)

**Comment by ZLoth** [comment]
> I also took some time to clean up the UI so the spacing is more even and they fit on one line.

_Nice_! Thank you, and I look forward to the release.

**Comment by advplyr** [comment]
Updated in [v2.9.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.9.0)
