### ISSUE TITLE
[Bug]: Podcasts library dissapeared when upgrading to v2.9.0

### ISSUE THREAD

**Issue by broizter** [advplyr/audiobookshelf#2867]
### Describe the issue

After upgrading from v2.8.1 to v2.9.0 my Podcast library dissapeared. My audiobook library was left intact. I have a snapshot pre-upgrade available so I can roll back to perform more debug steps, I just need to know what steps.

### Steps to reproduce the issue

1. Have one library for audiobooks and one for podcasts setup
2. Upgrade from v2.8.1 to v2.9.0
3. Check your libraries. Podcast library is gone

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Debian/PPA

**Comment by nichwall** [comment]
Do you have any logs from when you first start the server on 2.9.0?

**Comment by broizter** [comment]
I restored my snapshot to re-run the upgrade and collect logs but this time no bad things happen. I have no idea why it worked this time. I will close this issue and report if it ever happens again together with a full set of logs.
