### ISSUE TITLE
[Bug]: Volume button not visible when the browser window is narrow

### ISSUE THREAD

**Issue by Nathorr** [advplyr/audiobookshelf#2868]
### Describe the issue

Audiobookshelf's volume button is not visible if the browser is too narrow. Happens on both Firefox and Brave.

![image](https://github.com/advplyr/audiobookshelf/assets/12606615/f7e16570-6669-4d4c-b77e-a9d86c1ce80d)

![image](https://github.com/advplyr/audiobookshelf/assets/12606615/134a46fc-9256-4f48-831e-db297aedbb33)

### Steps to reproduce the issue

1. Open any file in Audiobookshelf
2. Make the browser window narrow
3. Volume button disappears

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Updated in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
