### ISSUE TITLE
[Bug]: The player's cover art formatting changes with selected library

### ISSUE THREAD

**Issue by shrugal** [advplyr/audiobookshelf#2870]
### Describe the issue

If you have something playing and switch between libraries with different cover art fomatting settings (square vs 1.6:1) then the player's cover art formatting switches as well.

![grafik](https://github.com/advplyr/audiobookshelf/assets/710525/8ec14f58-8673-442a-baba-947abbaf0c9f)
![grafik](https://github.com/advplyr/audiobookshelf/assets/710525/65a91c44-bacf-4a2b-bf75-c8fe18135021)

### Steps to reproduce the issue

1. Select a podcast or audiobook library (using square cover art)
2. Start playing something, the player shows a square cover art
4. Switch to a book library (using book cover art)
5. The player incorrectly changes to book cover art formatting as well
6. Switch back, the player's cover art is square again

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
