### ISSUE TITLE
[Bug]: A lot of "Error: port is undefined" logged in web

### ISSUE THREAD

**Issue by 0verEngineer** [advplyr/audiobookshelf#2871]
### Describe the issue

I get a "Error: port is undefined" like every second in the browser console.

In the last few days i also experienced a lot of the "Playback not synced..." Toast notifications

### Steps to reproduce the issue

1. Open browser console

### Audiobookshelf version

v2.7.1

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Does this still happen on the latest server version? The current version is 2.9.0

**Comment by 0verEngineer** [comment]
I cannot reproduce it anymore, it stopped happening.
