### ISSUE TITLE
[Enhancement]: Show active / inactive status of user within user-overview

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf#2876]
### Describe the feature/enhancement

![image](https://github.com/advplyr/audiobookshelf/assets/72630160/0fc05571-7f75-46da-b9fc-07f4a4fe05c1)

**Comment by jimski427** [comment]
The dot to the left of the username already does that. It turns green when the user is active...

**Comment by Gru0810** [comment]
Sorry to not describe in detail! I talk about this "atcive"-Flag:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/484b3730-1c7f-4056-80f4-1428f17393c3)

**Comment by advplyr** [comment]
This used to show the row as red but it broke at some point. Just fixed that

**Comment by advplyr** [comment]
Updated in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
