### ISSUE TITLE
[Bug]: The server is not starting in dev mode.

### ISSUE THREAD

**Issue by DenniLa2** [advplyr/audiobookshelf#2881]
### Describe the issue

Sure, here is the translation of the text into English:

English translation:

I cloned the repository today and ran 'npm run dev'. Unfortunately, I'm getting an error: "Error: Cannot find module './dev'
"

![image](https://github.com/advplyr/audiobookshelf/assets/9018493/5192ddaa-62e6-462d-be9a-bbcb7b66b2e7)

Could you please tell me what should be in the './dev.js' file?

### Steps to reproduce the issue

1. git clone
2. npm i
3. npm run dev

### Audiobookshelf version

2.9.0

### How are you running audiobookshelf?

Other

**Comment by advplyr** [comment]
See https://github.com/advplyr/audiobookshelf?tab=readme-ov-file#contributing

**Comment by nichwall** [comment]
Have you created the `dev.js` mentioned Development Commands in the readme?
