### ISSUE TITLE
[Bug] Users can be created with leading/trailing whitespace but can't login with it

### ISSUE THREAD

**Issue by MoldyHacker** [advplyr/audiobookshelf#2882]
### Steps to reproduce

1. Create a user with any additional whitespace trailing the username.

### Expected behaviour
- When creating a user there should be validation and cleanup of dirty strings to remove trailing whitespace and other undesirable characters.

### Actual behaviour
- When creating a user; if there is any trailing whitespace at the end of the username it is saved and preserved.

### Environment data

Audiobookshelf Version: 2.9.0

- [ x ] Android App v0.9.73-beta

#### Android Issue
Android version: 14

Device model: Google Pixel 8 Pro

Stock or customized system: Stock

**Comment by advplyr** [comment]
Fixed in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
