### ISSUE TITLE
[Bug]: Unable to remove item from Continue Listening section

### ISSUE THREAD

**Issue by SkippyTheMonkeyKeeper** [advplyr/audiobookshelf#2884]
### Describe the issue

I have one particular item that doesn't want to be removed from the Continue Listening section. I first tried to mark the book as finished in the latest version of the android app. That didn't work. Next I to used the `Remove from Continue Listening` button in the browser, at first it seemed to have worked, but after a refresh the item is back and clicking the button again does not work.

Removing other items via the `Remove from Continue Listening` button is working fine. So I'm not sure what's going on here. I checked the logs but the only log line that appears after clicking the button is: `[ApiCacheManager] Object.afterBulkUpdate: Clearing cache`. This log line doesn't appear when I use the button for my problematic item. 

Another interesting find is that the item disappears from the Continue Listening section after removing another item, however after a page refresh it's back again.

### Steps to reproduce the issue

1. Unfortunately I'm unable to provide a reproduction path.

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Can you try "Remove Progress" on the problem book and then "Mark as Finished"? It is probably another case of duplicate listening sessions.

Does restarting the server fix it?

**Comment by advplyr** [comment]
Was this a downloaded book that was downloaded on an old server version? If you remember it would have been v2.2.23 or earlier

**Comment by SkippyTheMonkeyKeeper** [comment]
I removed the progress of the 100% one and a new one of 0% popped up, when I removed that as well the item was removed from the Continue Listening. Marking it as complete again doesn't make it reappear in the Continue Listening section so luckily the issue has been resolved. Thanks for the suggestion @nichwall !

@advplyr I did download the book, but the version of the server at the time of downloading was 2.8.1.

**Comment by advplyr** [comment]
Thanks. This doesn't appear to be the same issue as before since that was specific to downloaded books using an old ID format.

To figure this out I'll have to reproduce it or someone reproduces it who can share the contents of the db. We'll re-open if it happens again
