### ISSUE TITLE
[Bug]: `docker-compose` is recommended over `docker compose` in the docs

### ISSUE THREAD

**Issue by C0rn3j** [advplyr/audiobookshelf#2886]
### Describe the issue

https://www.audiobookshelf.org/docs/#docker-compose-upgrade

docker-compose (compose v1) has been EOL for over a year at this point, `docker compose` plugin is pretty much a direct replacement, just dropping the `-` for a ` ` space is enough.

### Steps to reproduce the issue

docs issue

### Audiobookshelf version

N/A

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Thank, you can open PRs to help update documentation on the website repo. 

https://github.com/audiobookshelf/audiobookshelf-web
