### ISSUE TITLE
[Enhancement]: (Cosmetic) Picture dimensions should use “×” instead of lowercase x

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2888]
### Describe the feature/enhancement

This is purely cosmetic, but currently, the dimensions of a picture are being displayed with an lowercase x. 

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/04981b42-daeb-4a31-b282-8b9971319377)
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/9873244b-9725-47cb-b339-b7d23f9355d9)

It would be nice if it was displayed with the [&times;](https://www.compart.com/en/unicode/U+00D7) symbol instead.

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/ab157d3c-633b-4136-b330-2df2a481b77a)
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/78fc4c43-82c9-42e9-bc7d-5df708ce7e9d)

**Comment by advplyr** [comment]
I updated this for the next release. 

I want to note that for playback speed I was using unicode [⨯](https://www.compart.com/en/unicode/U+2A2F) and it didn't display on a firefox linux browser per https://github.com/advplyr/audiobookshelf/issues/1508

The unicode character you linked [×](https://www.compart.com/en/unicode/U+00D7) should be supported though.

**Comment by ZLoth** [comment]
Thank you for the update. Looking forward to the next release.

**Comment by criscrafter** [comment]
Honestly, I would like this to be a setting, as basically every software and every website uses an lowercase x, and I am used to it and like is way more, because its more compact.

**Comment by advplyr** [comment]
I have no preference at all. Whatever makes the most sense let me know. It's not going to be a setting

**Comment by ZLoth** [comment]
https://en.wikipedia.org/wiki/Multiplication_sign - "[Screen resolution](https://en.wikipedia.org/wiki/Screen_resolution) in pixels, such as 1920 pixels across × 1080 pixels down. Read as "by"."

**Comment by criscrafter** [comment]
Yeah, that is the theory, but in practice nobody does it that way.
Check any Monitor on Amazon and look at the resolution. There will be a x.
The only exception I could find is the small resolution shown in the bottom right corner of Google Images.
My issue is it would make things harder. When you want to copy the resolution into other programs, many of them expect an x.
I am fine with both, but you should consider the added hassle for many users that results from that.

**Comment by advplyr** [comment]
Updated in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)

I'm still open to changing this back if more users prefer the x. We'll see
