### ISSUE TITLE
[Enhancement]: (Cosmetic) For Book Matching, add CSS element padding 1px for images

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2889]
### Describe the feature/enhancement

On the matching screen, it would be nice to add a 1px padding so that the images are not closely together, but there is a 1-2 pixel "gutter" between the two images.

Currently: 
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/62199e8e-8f8b-4357-bb20-c8c82486e55f)

Suggested (I used a padding of 1px for the right and left side respectively):
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/92780d11-898d-4047-8cec-999fa39485ff)

**Comment by ZLoth** [comment]
Thank you. Looking forward to deployment.

**Comment by advplyr** [comment]
Updated in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
