### ISSUE TITLE
ID3 Metadata Tags

### ISSUE THREAD

**Issue by JKamsker** [advplyr/audiobookshelf#289]
Looking at https://www.audiobookshelf.org/docs/#metadata , i cannot seem to find the corresponding Tag Identifiers (e.g: composer: TCOM, according to [atldotnet-ID3v2.cs](https://github.com/Zeugma440/atldotnet/blob/f26d926ee2926f89cc934f4fc179b8feff9df709/ATL/AudioData/IO/ID3v2.cs) or [ffmpeg](https://github.com/FFmpeg/FFmpeg/blob/afeefb306e89b3ea3eb8ac8227996dc79589b669/libavformat/id3v2.c))

Could you please add those fields?
If not, providing a sample m4b file with all metadata fields set for further analysis would be helpful aswell :)

**Comment by mx03** [comment]
This is how my mp3 id3 tags are:

| ID3 Tag | Audiobookshelf Data | Tag Identifier |
| ------------- | ------------- | ------------- |
| artist / album-artist | Author | TPE1 / TPE2 |
| album / title | Title | TALB / TIT2 |
| subtitle | Subtitle | TIT3 |
| publisher | Publisher | TPUB |
| year | Publish Year | TYER |
| composer | Narrator | TCOM |
| description | Description | TXXX |
| genre | Genres * | TCON |
| series | Series | TXXX |
| series-part | Volume Number | TXXX |

**Comment by JKamsker** [comment]
Thanks!
But if the keys are the same, how can it tell them apart? 
@mx03

**Comment by mx03** [comment]
TXXX are user defined fields.

> 4.2.2. User defined text information frame
This frame is intended for one-string text information concerning the audiofile in a similar way to the other "T"-frames. The frame body consists of a description of the string, represented as a terminated string, followed by the actual string. There may be **more than one "TXXX" frame** in each tag, but **only one with the same description**.

https://id3.org/id3v2.3.0

**Comment by mx03** [comment]
Not sure if it was only an example, but with https://github.com/Zeugma440/atldotnet `theTrack.AdditionalFields["series"] = "seriesname"; // Support for custom fields` ?

Or https://wiki.multimedia.cx/index.php/FFmpeg_Metadata ` ffmpeg -i inputfile -metadata title="Movie Title" -metadata series="seriesname" outputfile` (If any additional metadata tags are specified that are not in the preceding table, the FFmpeg MP3 muxer encodes a TXXX user-defined information frame containing both the key and the value.)

Personal i use [mp3tag](https://www.mp3tag.de/) for manuel editing, for automatic conversion i use ffmpeg.

**Comment by JKamsker** [comment]
Yea, ffmpeg takes well known metadata, like composer, but TXXX data like series or series-data will go to the void.

**Comment by mx03** [comment]
You could try this: https://superuser.com/questions/1208273/how-to-add-new-and-non-defined-metadata-to-an-mp4-file .
I tried it and it "worked" with `-movflags use_metadata_tags`. It was visible with ffprobe, but not with mp3tag.

I use mainly mp3 and opus, not sure if its a bug or if its only a mess.

**Comment by JKamsker** [comment]
After some friendly (optimization/)help from atldotnet , saving tags now only takes 10 secs max.
This is how i did it: https://github.com/JKamsker/AudibleSyncService/blob/49f83db4f0247236d4d5b11fac65967294b69509/AudibleSyncService/Logic/Services/AudibleBook.cs#L190
