### ISSUE TITLE
[Bug]: Library keeps restoring settings to an older version

### ISSUE THREAD

**Issue by C0rn3j** [advplyr/audiobookshelf#2894]
### Describe the issue

Wrong state(I already corrected the folder here from `/opt/audiobooks`, that changes too):

![image](https://github.com/advplyr/audiobookshelf/assets/1641362/851fbee9-255d-4189-99d5-0d097ef69f02)

State I keep trying to set it to:

![image](https://github.com/advplyr/audiobookshelf/assets/1641362/a58f5cf0-dce3-490b-a68e-ab721db2e319)

This is about the third time it has happened.

If I had to suspect something, it would be the backup(???) routine

```yaml
[2024-04-30 11:00:01.005] ERROR: 
[fileUtils] Failed to getFileTimestampsWithIno for path "/opt/audiobooks/opt/ebooks/Audio" 
[Error: ENOENT: no such file or directory, stat '/opt/audiobooks/opt/ebooks/Audio'] {
```

`/opt/audiobooks` is a symlink to `/opt/ebooks/Audio` by `ln -s ebooks/Audio/ audiobooks`

### Steps to reproduce the issue

Unsure about repro, seems to happen over a longer period of time.

### Audiobookshelf version

v2.9.0, Arch Linux

### How are you running audiobookshelf?

Other

**Comment by advplyr** [comment]
I'm not sure who manages the arch linux package for Abs so hopefully this isn't an issue with that.
You should check that the sqlite database is in your `/config` folder wherever that is mapped. If you can open up the sqlite db there is a libraries table you can make sure that your path is being saved.

**Comment by C0rn3j** [comment]
It's a user package on AUR - https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=audiobookshelf

ends up with this config

```
METADATA_PATH=/var/lib/audiobookshelf/metadata
CONFIG_PATH=/var/lib/audiobookshelf/config
FFMPEG_PATH=/usr/bin/ffmpeg
FFPROBE_PATH=/usr/bin/ffprobe
TONE_PATH=/usr/bin/tone
PORT=13378
HOST=0.0.0.0
```

Now it has saved my changes but not my icon change, so the icon keeps reverting (which is infinitely less annoying than having my entire library break every few hours) - how exactly can I check the sqlite db for this?

I figure I can just `sqlite3 absdatabase.sqlite .dump` dump it, but unsure what to look for

**Comment by advplyr** [comment]
There is a libraries table in the db. If you don't have a visual editor you can use a free one online and upload your sqlite file.
