### ISSUE TITLE
[Bug]: Home page fails to load on larger library

### ISSUE THREAD

**Issue by rossengeorgiev** [advplyr/audiobookshelf#2895]
### Describe the issue

I've created a "large" library of ebooks (35k entries), and when I try to open the home page, the app stops working for a bit. Looking at the server I see a single thread maxing out CPU for a minute or two. After that the app recovers, but the home page never loads. Naturally, adding more resource makes no difference. The server is a VM with SSD storage and lots of ram, so pretty much ideal.

I've not looked at the source code, but I'm guessing the page does very expensive database queries.

When reconnecting to the audobookshelf server, or connecting for the first time, the home page is where you land. The library page works, but it still takes long time to load. Scanning that library initially took 12-16 hours (no book matching), which seems very slow as 35k entries is not that much.

### Steps to reproduce the issue

1.  Large library of ebooks (35k entries)
2. Attempt to load home page

### Audiobookshelf version

v2.8.1

### How are you running audiobookshelf?

Debian/PPA

**Comment by nichwall** [comment]
The expensive part is converting the data from SQLite back to the data model that the API expects. The API/apps are planned to be rewritten, it just hasn't happened yet.

If you are willing to provide the SQLite database file, that would be helpful. You can either send it to advplyr (email on GH profile or Discord) or myself and I can pass it along.

https://github.com/advplyr/audiobookshelf/issues/2073

**Comment by rossengeorgiev** [comment]
Hi, how is #2073 a duplicate? It talks about version 2.4.0. I see lots of comments about different changes, but nothing like the issue here. The home page never loads for me, its not just slow. Happy to provide a database file for you to reproduce.

**Comment by nichwall** [comment]
This is the same issue that was originally introduced in 2.4.0 with the migration to SQLite. There have been a lot of optimizations since then, but this is the same issue. If you can provide the SQLite database for testing that would be helpful.
