### ISSUE TITLE
[Bug]: When moving books within the same library, a broken picture is displayed in the browser

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2898]
### Describe the issue

I've been uploading books from a particular publisher, and have my directories set up as follows:

- Series Sets - Complete
- Series Sets - Missing Books
- Series Sets - Missing First Book

As I managed to complete the sets, I move my collection from "Series Sets - Missing Books". As I do, the book set goes temporary "offline", but instead of a placeholder picture, a broken browser picture is displayed. When I place the library into a new location, the pictures do get reloaded in the end, so it's not a showstopper issue. 

### Steps to reproduce the issue

1. Display a book
2. In my file manager, I move the book set from my current folder to a temporary folder. 
3. AudioBookShelf scans the library, notices the book set no longer exists, and should be putting up a temporary picture. It, instead, puts up a broken picture.
4. Bring back the book set to the new file location within the same library.
5. Pictures are restored as expected.

As tested under Chrome:
https://github.com/advplyr/audiobookshelf/assets/6700159/9b18464a-eb96-42bd-a225-a87a5831a450

### Audiobookshelf version

2.9.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not sure I understand because this seems like normal behavior to me. The image is no longer at the location so it shows a broken image letting you know. If we showed a placeholder every time instead of a broken image it would look like there is no image path set.

**Comment by ZLoth** [comment]
See the recording to see what the end user experience is like.
