### ISSUE TITLE
[Bug]: When editing a book, a book march and updated cover will show original cover until refreshed

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2900]
### Describe the issue

One cosmetic thing that I've noticed is that I'm performing a book match of a single title which usually results in a higher-resolutoin image. However, until I refresh the page, the original graphic appears to be displayed... or is it the new graphic with the original dimensions.

### Steps to reproduce the issue

1. Select a single title
2. Click on the image to show smaller size (usually 500×500).
3. Click on the edit button.
4. Perform a book match. Note that the new image is a higher resolution than the stored image.
5. Update and close the edit window.
6. Click on the image, and the smaller size is still displaying.
7. Refresh the page to shown the actual high-resolution image. 

Recording of issue:
https://github.com/advplyr/audiobookshelf/assets/6700159/c7f9ce5f-9dde-4dca-9df0-bc633f7af81f

### Audiobookshelf version

2.9.0, 2.8.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
