### ISSUE TITLE
[Bug]: Switching libraries while a specific series is set results in error message "No results"

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2902]
### Describe the issue

As my implementation is configured, I have my collection separated into several libraries to make management easier. This includes separating my Fiction, Science Fiction, and Western Collections into Regular and non-dramatized. As a result, I can be displaying a series from a non-dramatized library, switch the library, and because the UUID of the series is different, I get no results.

As a short term solution, if I'm switching libraries, I should be retuned to the root level of the series. A longer-term solution is a best match for a similar title. 

### Steps to reproduce the issue

1. Go to a library and select "Series".
2. Select a book series. 
3. Switch to a different library.

WHAT SHOULD HAPPEN: The series should be returned to the root level.
WHAT REALLY HAPPENS: No results.

Recording of issue:
https://github.com/advplyr/audiobookshelf/assets/6700159/b2f441df-cf99-4f8c-94d4-310e418203b6

### Audiobookshelf version

2.9.0, 2.8.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I updated this to redirect to the root series page for the next release. This isn't going to be updated to redirect to a series of a similar name because this isn't how libraries are intended to be used. Libraries were made to be completely separate

**Comment by ZLoth** [comment]
Thank you, awaiting release.

**Comment by advplyr** [comment]
Fixed in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
