### ISSUE TITLE
[Enhancement]: Authors should be cross libraries

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2905]
### Describe the feature/enhancement

As I have my server configured, I have my libraries set up across specific genres, and do a division between "Regular" and "Dramatized". This means that I can have the same author across multiple libraries, but each library considers it's list of authors to be exclusive to that library. It would be nice if the authors was "centralized" and crossed all the libraries.

**Comment by advplyr** [comment]
This isn't going to be supported because libraries are meant to be completely separate. We would have to do a bottom up redesign of the data model. If that were to happen we can start taking feature requests like this.

I know some users are not using libraries in the way I originally designed them to be used. There may be a different solution for those users that doesn't involve separate libraries

**Comment by ZLoth** [comment]
> This isn't going to be supported because libraries are meant to be completely separate. We would have to do a bottom up redesign of the data model. If that were to happen we can start taking feature requests like this.

(I'm going to post my reply in two places)

How are libraries supposed to be used? According to https://www.audiobookshelf.org/guides/library_creation#setting-up-a-library : 

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/6ea45310-1ccb-4b43-ba62-6b3977a85dcc)

As far as I can determine from the published documentation, there are just two types of libraries: Audiobook and Podcast. They differ in how the data is pulled and handled, much like the differences between Plex, Emby, and Jellyfin handles movies, tv shows, and music. 

When AudioBookShelf was created, how many titles would did you estimate that a user would have? While I initially planned on only hosting and listening to the titles that I had obtained from Humble Bundle sales over the years, the power of AudioBookShelf had me migrate my Audible book collection to my own TrueNAS SCALE server via a Docker container. At this writing, I have over 4,500 titles... over half of it from looking at their Plus catalog, with Great Courses, Modern Scholar, and GraphicAudio being my primary targets. With that many titles, one had to divide and conquer...

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/fe5fd1da-a0b7-4bc6-b1f1-06d0f48bc447)

Isn't that much easier than just dumping everything into a single library, especially when one shares his library with his 83 year old mother and a fiscally-challenged friend who is going through cancer? And, I really don't want to explain some of those science fiction titles, so turn off the library for her.
