### ISSUE TITLE
[Enhancement]: Add Display Name for sending emails

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2906]
### Describe the feature/enhancement

As currently designed, AudioBookShelf does not allow configuration of a Display Name when sending emails.

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/a2a6e05e-d735-4a3f-8c47-96128d8bb152)

This results in only the email address being displayed when sending a email.

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/427b1aa7-41a6-4181-837b-64b8e62c37de)

Other services with email utilize it...

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/fb7a070c-7298-45b0-ab26-6355ffa331a7)

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/1862515f-039c-403b-93cd-0739b68a7959)

**Comment by advplyr** [comment]
This is already supported. The from address can be in the form "Name \<test@example.com\>" or "test@example.com".

I added this to the list of guides we will add to the website https://github.com/audiobookshelf/audiobookshelf-web/issues/29#issuecomment-2090848868

**Comment by ZLoth** [comment]
> This is already supported. The from address can be in the form "Name <[test@example.com](mailto:test@example.com)>" or "[test@example.com](mailto:test@example.com)".

Can this please be added as part of a hover-over help?
