### ISSUE TITLE
[Enhancement]: Shared listening sessions

### ISSUE THREAD

**Issue by timshannon** [advplyr/audiobookshelf#2913]
### Describe the feature/enhancement

One of my favorite things to do with my wife is listen to a podcast with her (or an audiobook).  This usually requires a speaker of some sort, but when we're in public or going on a walk together a speaker isn't a good option.

The best solution I've found is Spotify's shared listening sessions, and it would be amazing if something similar was possible with audiobookshelf as well.

**Comment by nichwall** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2725

**Comment by timshannon** [comment]
Closing in favor of #2725
