### ISSUE TITLE
[Bug]: [Edit Chapters] button of "Chapters" tab of Edit item dialog doesn't work if in edit chapters view to start.

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf#2915]
### Describe the issue

the edit chapters button doesn't work in the specific case described...
it should basically close the EID and go back to the screen that was there before.  

obviously, there are other ways to get back to it, but if the button exists and it doesn't work it is broken.

### Steps to reproduce the issue

go to bookshelf view.
click top right `✎`pencil icon for edit item dialog (EID)
select `Chapters` tab in EID
select `Edit Chapters` button
select `✎` pencil icon to right of book title beneath search dialog to return to EID
...do stuff in EID as necessary...
select `Chapters` tab in EID
select `Edit Chapters` button
observe that nothing happens
:(

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Updated in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
