### ISSUE TITLE
InRelease is unsigned 

### ISSUE THREAD

**Issue by yuukiw** [advplyr/audiobookshelf#292]
Hi, 

I would need some help setting up the server. 

When installing it via docker I cant accses the server and when I want to install via apt install I get the following error
E: The repository 'https://advplyr.github.io/audiobookshelf-ppa ./ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

What is going wrong?
It's vps hosted in contabo.

**Comment by mx03** [comment]
Is there a firewall that blocks the port and which port do you use?
I would stick with the docker image if you can use docker.

**Comment by yuukiw** [comment]
The docker always seems to bind on 0.0.0.0 so locally, which isnt good when
trying to accses it from the outside.



mx03 ***@***.***> schrieb am Mi., 5. Jan. 2022, 10:25:

**Comment by yuukiw** [comment]
Here is  Part of the output

Config /config /metadata /audiobooks
[2022-01-05T09:36:06.937Z]  INFO: === Starting Server ===
[2022-01-05T09:36:06.938Z]  INFO: [Server] Init v1.6.52
[2022-01-05T09:36:06.979Z]  INFO: [DB] 0 Audiobooks Loaded
[2022-01-05T09:36:06.980Z]  INFO: [DB] 0 Users Loaded
[2022-01-05T09:36:06.980Z]  INFO: [DB] 0 Libraries Loaded
[2022-01-05T09:36:06.980Z]  INFO: [DB] 0 Collections Loaded
[2022-01-05T09:36:06.981Z]  INFO: [DB] 0 Authors Loaded
[2022-01-05T09:36:06.986Z]  INFO: [Db] Root user created
[Error: ENOENT: no such file or directory, access '/config/users/data/data.3.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/config/users/data/data.3.json'
}
[Error: ENOENT: no such file or directory, access '/config/libraries/data/data.0.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/config/libraries/data/data.0.json'
}
[Error: ENOENT: no such file or directory, access '/config/settings/data/data.0.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/config/settings/data/data.0.json'
}
[2022-01-05T09:36:07.028Z]  INFO: [BackupManager] 0 Backups Found
[2022-01-05T09:36:07.028Z]  INFO: [BackupManager] Auto Backups are disabled
[2022-01-05T09:36:07.038Z]  INFO: [LogManager] Init current daily log filename: 2022-01-05.txt
[2022-01-05T09:36:07.039Z]  INFO: [Watcher] Initializing watcher for "Main".
[2022-01-05T09:36:07.054Z]  INFO: Running on http://0.0.0.0:80
[2022-01-05T09:36:07.062Z]  INFO: [Watcher] "Main" Ready

**Comment by mx03** [comment]
Can you show me the docker command you use?

**Comment by yuukiw** [comment]
docker run -p 8080:8080  advplyr/audiobookshelf

**Comment by mx03** [comment]
The internal port for the webinterface is 80, that port must be the same and your mounted directories are missing too (/audiobooks , /config , /metadata)

**Comment by yuukiw** [comment]
How do I create them

mx03 ***@***.***> schrieb am Mi., 5. Jan. 2022, 10:48:

**Comment by mx03** [comment]
You could use https://github.com/jc21/nginx-proxy-manager as a reverseproxy.

Seems like you have not much knowledge with docker?

**Comment by yuukiw** [comment]
Not really

**Comment by mx03** [comment]
If you have more knowledge with the normal linux you could also use the normal package manager.

Have you installed the signing key for the ppa?
`curl -s --compressed "https://advplyr.github.io/audiobookshelf-ppa/KEY.gpg" | sudo apt-key add - `

**Comment by advplyr** [comment]
There is a signing warning on the PPA, but it should still be able to get installed.

If you have docker installed already then that is probably your easiest option to get it running.

**Comment by yuukiw** [comment]
the one step i dont quite get is the 
"
docker run -d \
    -e AUDIOBOOKSHELF_UID=99
    -e AUDIOBOOKSHELF_GID=100
    -p 13378:80 \
    -v </path/to/audiobooks>:/audiobooks \
    -v </path/to/config>:/config \
    -v </path/to/metadata>:/metadata \
    --name audiobookshelf \
    --rm advplyr/audiobookshelf
"

What am i supossed to do there?
btw nginx is setup now.

**Comment by yuukiw** [comment]
got it setup now but how to i add my current audionbok lib.
currenlty my books are in a folder called /audiooks on the server root folder

**Comment by advplyr** [comment]
You need to map your /audiobooks folder when starting the docker container.
`-v </path/to/audiobooks>:/audiobooks`

**Comment by yuukiw** [comment]
I change replace the <xxx> part right?

**Comment by yuukiw** [comment]
i got it working now somewhat but it only will detect ab i upload via the interface while the ones i upload via ftp wont show up when uploading via ftp.

**Comment by advplyr** [comment]
Did you map all 3 volumes? https://www.audiobookshelf.org/install#docker

Wherever you mapped the /metadata folder, take a look at the log file after restarting the server.
Confirm that you can see the logs similar to `[Watcher] main Ready`

The Watcher is responsible for listening to updates to your audiobook folder and scanning them into your bookshelf. The logs will confirm if the watcher initialized correctly.

**Comment by yuukiw** [comment]
thats what it says
> audiobookshelf@1.6.52 start /
> node index.js

Config /config /metadata /audiobooks
[2022-01-09T07:24:28.627Z]  INFO: === Starting Server ===
[2022-01-09T07:24:28.628Z]  INFO: [Server] Init v1.6.52
[2022-01-09T07:24:28.647Z]  INFO: [DB] 0 Audiobooks Loaded
[2022-01-09T07:24:28.647Z]  INFO: [DB] 0 Users Loaded
[2022-01-09T07:24:28.648Z]  INFO: [DB] 0 Libraries Loaded
[2022-01-09T07:24:28.648Z]  INFO: [DB] 0 Collections Loaded
[2022-01-09T07:24:28.648Z]  INFO: [DB] 0 Authors Loaded
[2022-01-09T07:24:28.651Z]  INFO: [Db] Root user created
[Error: ENOENT: no such file or directory, access '/config/users/data/data.0.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/config/users/data/data.0.json'
}
[Error: ENOENT: no such file or directory, access '/config/libraries/data/data.0.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/config/libraries/data/data.0.json'
}
[Error: ENOENT: no such file or directory, access '/config/settings/data/data.0.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/config/settings/data/data.0.json'
}
[2022-01-09T07:24:28.680Z]  INFO: [BackupManager] 0 Backups Found
[2022-01-09T07:24:28.681Z]  INFO: [BackupManager] Auto Backups are disabled
[2022-01-09T07:24:28.685Z]  INFO: [LogManager] Init current daily log filename: 2022-01-09.txt
[2022-01-09T07:24:28.686Z]  INFO: [Watcher] Initializing watcher for "Main".
[2022-01-09T07:24:28.733Z]  INFO: Running on http://0.0.0.0:80
[2022-01-09T07:24:28.744Z]  INFO: [Watcher] "Main" Ready

the yml looks like this:

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  audiobookshelf:
    image: advplyr/audiobookshelf
    ports:
      - 13378:80
    volumes:
      - ./audiobooks:/audiobooks \
      - ./root/audiobookshelf/config:/config \
      - ./root/audiobookshelf/metadata:/metadata \
