### ISSUE TITLE
[Enhancement]: Show Bitrate

### ISSUE THREAD

**Issue by darkalchemy** [advplyr/audiobookshelf#2926]
### Describe the feature/enhancement

Would it be possible to add the bitrate to metadata.json and to the book details page? Also, add as a filter item in Library tab.

This would help when converting, without having to check the files with mediainfo and for looking for audiobooks that are low quality and may need replacing.

Thank

**Comment by advplyr** [comment]
I don't think it should go in the metadata.json. As for the filter how would you handle bitrate for books with multiple files?

What do you mean it would help with converting? Are you converting from one format to another?

**Comment by darkalchemy** [comment]
Many of my audiobooks are multi file and single file mp3's, so when converting to m4b I need to go to the cli and use mediainfo to get the bitrate. I need this, as most are 64k, but the default is 128k when converting, which would be a wasted upscale.

I could use the bitrate in the json file so that I can have access to while scripting. This would help me locate versions that I might like to replace.

For multi-file content, you could scan all and use an average or just scan the first and use that. When I scan my files, I use the bitrate of second file, instead of scanning every file. Some books have 100's of tiny files. I have not come across any that have varying bitrates.

I appreciate you looking at this and I understand if it's not something you want to add.

Thanks

**Comment by advplyr** [comment]
Possibly sometime in the future if sorting/filtering gets revamped. There are FR's in for adding more advanced sorting/filtering. As of now this is not planned but can be mentioned in #1465
