### ISSUE TITLE
[Enhancement]: Logs files should be downloadable a tab-seperated text file, allow for specifying a time range

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2932]
### Describe the feature/enhancement

I was reviewing an issue that required a review of the log files and posting of the log sample as part of a defect request. Currently, the only way is to copy the text from the window and paste it into a text editor. It would be nice if I can specify a time range and download the log example to a text file that has the fields seperated by tabs. I can then import the file into Excel and use that programs filtering functions to view and select the necessary lines.

**Comment by nichwall** [comment]
Logs are available in `/metadata/logs`

**Comment by ZLoth** [comment]
There should be a note in the Logs screen stating that logs are available for download at /metadata/logs

**Comment by ZLoth** [comment]
Awesome, thank you!

**Comment by advplyr** [comment]
Updated in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
