### ISSUE TITLE
[Bug]: Updating author image does not refresh until page is reloaded

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2934]
### What happened?

When I am editing the author that has a pre-existing image, the new image does not appear until I save and refresh the page. Note that uploading a image for an author that does not have an image works as expected. 

### What did you expect to happen?

Author image should be replaced with new uploaded image if an image is already existing.

### Steps to reproduce the issue

1. Select an library
2. Go to Authors
3. Select an author that has a pre-existing image.
4. Edit the author
5. Paste in a URL of a new image and click Submit

WHAT SHOULD HAPPEN: The image is updated in the preview window.
WHAT REALLY HAPPENS: The image does not update until the page is refreshed. 
WORKAROUND: Delete the image and then upload a new image. 

Recording of issue: https://github.com/advplyr/audiobookshelf/assets/6700159/c37dc2a0-768e-4cd8-8fd6-0c484589e7cd

### Audiobookshelf version

2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

TrueNAS Scale - Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Logs
```
{"timestamp":"2024-05-05 22:50:07.296","source":"AuthorController.js:195","message":"[AuthorController] Requesting download author image from url \"https://www.federalreservehistory.org/-/media/images/greenspan_alan.jpg\"","levelName":"DEBUG","level":1}
{"timestamp":"2024-05-05 22:50:07.297","source":"fileUtils.js:248","message":"[fileUtils] Downloading file to /metadata/authors/63123827-ccef-45c8-b9db-b7dd7b8c60b3.jpg","levelName":"DEBUG","level":1}
{"timestamp":"2024-05-05 22:50:08.025","source":"CacheManager.js:94","message":"[CacheManager] Going to purge 63123827-ccef-45c8-b9db-b7dd7b8c60b3_400.webp","levelName":"DEBUG","level":1}
{"timestamp":"2024-05-05 22:50:08.073","source":"ApiCacheManager.js:21","message":"[ApiCacheManager] Object.afterBulkUpdate: Clearing cache","levelName":"DEBUG","level":1}
{"timestamp":"2024-05-05 22:50:13.471","source":"SocketAuthority.js:131","message":"[SocketAuthority] User Offline Mark","levelName":"DEBUG","level":1}
{"timestamp":"2024-05-05 22:50:13.471","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket SaYDmzhNmpEd6zFvAAAH disconnected from client \"Mark\" after 102373ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-05-05 22:50:13.932","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected MJADxmSEzfDrZaJVAAAJ","levelName":"INFO","level":2}
{"timestamp":"2024-05-05 22:50:14.040","source":"SocketAuthority.js:204","message":"[SocketAuthority] User Online Mark","levelName":"DEBUG","level":1}
{"timestamp":"2024-05-05 22:50:14.044","source":"ApiCacheManager.js:39","message":"[ApiCacheManager] count: 0 size: 0","levelName":"DEBUG","level":1}
{"timestamp":"2024-05-05 22:50:14.101","source":"ApiCacheManager.js:50","message":"[ApiCacheManager] Cache miss: {\"user\":\"Mark\",\"url\":\"/libraries\"}","levelName":"DEBUG","level":1}
{"timestamp":"2024-05-05 22:50:14.189","source":"ffmpegHelpers.js:76","message":"[FfmpegHelpers] Resize Image Cmd: ffmpeg -i /metadata/authors/63123827-ccef-45c8-b9db-b7dd7b8c60b3.jpg -y -vf scale=400:-1 /metadata/cache/images/63123827-ccef-45c8-b9db-b7dd7b8c60b3_400.webp","levelName":"DEBUG","level":1}
{"timestamp":"2024-05-05 22:50:14.353","source":"ffmpegHelpers.js:83","message":"[FfmpegHelpers] Image resized Successfully","levelName":"DEBUG","level":1}
```

### Additional Notes

This is similar to [Bug]: When editing a book, a book march and updated cover will show original cover until refreshed #2900.

**Comment by advplyr** [comment]
Fixed in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
