### ISSUE TITLE
[Enhancement]: add sort by "finished at"

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf#2935]
### Describe the feature/enhancement

I listen a lot! today I have listen more then 600 audiobooks.
Last week I met friends and I wanted to recommend an audio book that I listened to about 2 months ago. Unfortunately I didn't remember the title. So I filtered to the audio books that I had finished and unfortunately found that it wasn't possible to find the book without the option of sorting by "finished at".
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/846c03d8-313b-40db-a605-7d9edaf1dd65)

**Comment by advplyr** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1215
