### ISSUE TITLE
[Enhancement] Include Genre in global library search

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf#2937]
### What happened?

When I search for "Klassiker" which is used in "TAGS" (Schlagwörter)  all is fine:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/a5d8f220-590c-422e-8d73-da85f4cb4ffe)

But when I search for "AbenteuerRoman" which is used in "Genre" the system does not find the entry:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/0ea50c0f-3c81-4fb0-a9e3-a1337852cf02)

Under "Libray" the direct-filter on "AbenteuerRoman" works perfect:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/33c104d1-35dc-4cdf-8f4c-b2c53d3103cf)

### What did you expect to happen?

search will also find libray-item with Search-Text in Genre like it works for TAGS

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.8.1

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

**Comment by advplyr** [comment]
I don't understand, can you explain step-by-step how to reproduce this?

**Comment by nichwall** [comment]
Looks like information from https://github.com/advplyr/audiobookshelf/issues/2936 got copied into this issue.

**Comment by Gru0810** [comment]
sorry, did not check by preview
I just  add a new Genre / Kategory "test1234" to the audiobook and tehn search for it but 'no result':
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/9f3fb2d4-9b96-47e4-8b14-3725b7d44923)

**Comment by Gru0810** [comment]
I justtry to understand the Code for search at : 
https://github.com/advplyr/audiobookshelf/blob/master/server/utils/queries/libraryItemsBookFilters.js#L1157
and try to compare the block for searing within "tags" with "genres" and found this:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/b7013b6e-709c-4958-8666-718d74c21d99)

**Comment by advplyr** [comment]
I understand now. Genres are not part of the global search so I made this a feature request instead of a bug.

That screenshot is not related to searching.
