### ISSUE TITLE
[Enhancement]: Connect Library-Item by Library ID instead of Server

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf#2939]
### Describe the feature/enhancement

I have two Server
the first one I use when I'm at home by using the WLAN
the second one I use when I'm not at home by using mobile data.
But both point on the same library on my NAS. It would be great is the sync will use the Library (ID) and not the Servername:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/0d08ea20-ecde-46a2-b698-e63e764e14b1)

**Comment by advplyr** [comment]
This is in the wrong repo and this is already opened in the audiobookshelf-app repo if you search for it

**Comment by nichwall** [comment]
https://github.com/advplyr/audiobookshelf-app/issues/209
