### ISSUE TITLE
[Enhancement]: Make automatic cover search / download toggleable

### ISSUE THREAD

**Issue by kuldan5853** [advplyr/audiobookshelf#2945]
### Describe the feature/enhancement

I recently matched my library into ABS, and there are some books / shows that have no metadata that can be found online - the files are just files, and should be treated as such. 

However, for some reason ABS tried to match covers to each of those files, downloading absolutely any random kind of cover or image from somewhere, but nothing that was correct for the actual files (It was also explicitly only covers, not any kind of metadata). 

I had to go through 600 files one by one to unset the wrongly matched cover - and I have looked up and down the scanner settings but did not see a way to turn off this auto-matching?

**Comment by nichwall** [comment]
All retrieval of covers from the internet is manually initiated through a Match or Quick Match. By default the covers are not overwritten during a Quick Match unless you have enabled the "overwrite cover" setting, and during a normal match you have the option to get the cover or not.

Covers are automatically extracted from your media files during a scan if there is not an associated image file.

**Comment by kuldan5853** [comment]
> All retrieval of covers from the internet is manually initiated through a Match or Quick Match. By default the covers are not overwritten during a Quick Match unless you have enabled the "overwrite cover" setting, and during a normal match you have the option to get the cover or not.
> 
> Covers are automatically extracted from your media files during a scan if there is not an associated image file.

That is the point though - all I did was to copy the files into the folder. I never did a manual match or quick match on those files, and it still downloaded random covers for the episodes...

**Comment by nichwall** [comment]
> That is the point though - all I did was to copy the files into the folder. I never did a manual match or quick match on those files, and it still downloaded random covers for the episodes... 
> 
> The files also do not contain any embedded covers. 

Can you provide some logs for this? Based on the other issues you've opened just now it sounds like you are doing a quick match to either the files or entire library, at which point the covers are downloaded.

**Comment by kuldan5853** [comment]
Okay, I'm stupid. There's a "find covers" toggle in the scanner settings.

**Comment by nichwall** [comment]
Oh, glad you found that. I completely forgot about that setting. Maybe it should be moved from server settings to library settings.

**Comment by kuldan5853** [comment]
> Oh, glad you found that. I completely forgot about that setting. Maybe it should be moved from server settings to library settings.

Yes, that is where I expected it to be (because you probably want different settings per library to begin with). 

I just went through all the settings page by page when I noticed those options... anyway, I know how to prevent this happening in the future :)
