### ISSUE TITLE
[Enhancement]: When using "quick match" for Metadata, give us an option to customize the fields

### ISSUE THREAD

**Issue by kuldan5853** [advplyr/audiobookshelf#2947]
### Describe the feature/enhancement

I currently have been adding multiple thousands of books into my ABS instance, and I had to often match them one-by-one to the metadata provider due to some issues. More often than not, using "quick match" would destroy the metadata (matching something completely wrong, but with a lot of confidence), which makes fixing things like a wrong assignment to a series afterwards very tedious. 

The main pain here is that if you reload the page or switch views, the book will move to whatever name / series it was (wrongly) matched to, and you have to manually seek through the library to identify it and "fix" it back to the right book / series.. 

Since the most common way to use quick match is with a batch of books, I'd suggest to give us a toggle to optionally select which fields should be quick matched and which to ignore - that way you could omit the ASIN and Series tag for example until you have verified that all your books are matching correctly with Quick Match.

**Comment by nichwall** [comment]
Related to https://github.com/advplyr/audiobookshelf/issues/841

By default Quick Match does not overwrite any metadata fields that are already filled out.

**Comment by kuldan5853** [comment]
> Related to #841
> 
> By default Quick Match does not overwrite any metadata fields that are already filled out.

Correct, the problem is that when I scan a new episode into the system, it does not auto-match (only from the file system structure). I then add it to the correct series manually (as this is also not working very well for my use case of radio dramas). 

After that, I try to actually match the imported episodes to their metadata using quick match, but the metadata is "empty" at that point, with the exception of the author, title, and series (+cover if present) (all matched from the filesystem).

When I then do a "quick match" it is overwriting the metadata... I know there are toggles on the quick match page, but when I turn both off, it does not do any matching at all in my experience - not only ignoring already present metadata. 
(I would have to retest this though to be sure)

**Comment by nichwall** [comment]
> After that, I try to actually match the imported episodes to their metadata using quick match, but the metadata is "empty" at that point, with the exception of the author, title, and series (+cover if present) (all matched from the filesystem).
> 
> When I then do a "quick match" it is overwriting the metadata... I know there are toggles on the quick match page, but when I turn both off, it does not do any matching at all in my experience - not only ignoring already present metadata. 
> (I would have to retest this though to be sure)
> 

Quick Match applies the first result from online providers based on the provided metadata, so if it's not getting anything then you can try changing to another online provider or adjusting your metadata to better match what the online provider is expecting (removing series name, adding extra information, etc).

If you can provide some examples of input metadata and what provider you're using that would be good.

**Comment by kuldan5853** [comment]
Sorry, figured this out with nicholas - my settings were wrong - I searched for the respective settings in the scanner options per library, but those were global in the main settings page.
