### ISSUE TITLE
[Enhancement]: Show search book results on multiple lines

### ISSUE THREAD

**Issue by DDriggs00** [advplyr/audiobookshelf#2948]
### Describe the feature/enhancement

Currently, when searching (using the search box at the top of the screen), the books returned from the search are collapsed onto a single line, which you must click through horizontally. Would it be possible to show the book results on multiple lines, in a more library-like format when there are more than a single row?

**Comment by advplyr** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/923

**Comment by advplyr** [comment]
The original issue was for multiple rows. I updated it to add a "View all" link which would also be compatible on the home page
