### ISSUE TITLE
Series are not in the correct sort order

### ISSUE THREAD

**Issue by szemlicka** [advplyr/audiobookshelf#295]
I have a lot of series (433). In general it looks like they are sorted alphabetic. But not all of them. The list startet very often again fresh.

Example:

List looks like
a,b,c,d......z,a,b,c,....z,
The attached file shows the beginning of the series list and a snip of the end, where itz starts again.
![list_begin](https://user-images.githubusercontent.com/15927779/148355659-e04ce1e9-b994-4a19-a872-0ec045c4f3e2.jpg)
![list_middle](https://user-images.githubusercontent.com/15927779/148355670-230094af-7500-4763-b31e-dfbc4aa91627.jpg)

**Comment by mx03** [comment]
At which count does this repeats?

**Comment by advplyr** [comment]
This should be fixed in `v1.6.54`
