### ISSUE TITLE
[Bug]: Cannot add "AvTalk" podcast

### ISSUE THREAD

**Issue by Frosbe** [advplyr/audiobookshelf#2952]
### What happened?

When i try to add the podcast "AvTalk" from FlightRadar24 i get an error saying "Failed to get podcast feed", in the logs i see an Axios error 403.

### What did you expect to happen?

I expect the abs to add the podcast to my subscriptions

### Steps to reproduce the issue

1. Add RSS "https://www.flightradar24.com/blog/feed/podcast"
2. Error

### Audiobookshelf version

2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
2024-05-08 21:58:10.631

ERROR

[podcastUtils] getPodcastFeed Error AxiosError: Request failed with status code 403
```

### Additional Notes

I tried setting up the dev environment and its might just be that the axios connection is blocked from flightradar24.com

**Comment by advplyr** [comment]
Yeah I can confirm they are blocking the request. I'm not sure what reason they have for that so don't know what to update here
