### ISSUE TITLE
[Bug]: Web sessions dont show sync to mobile app

### ISSUE THREAD

**Issue by hskrtich** [advplyr/audiobookshelf#2953]
### What happened?

When I listen to a book I have already started on my mobile device and switch to web, the book picks up at the correct place. When I switch back to my mobile it doesnt pick up the new place in my book. 

I have tried completely closing out of the book and closing out of the app to try to get it to sync.

When checking the backend listening sessions, I do see both the web sessions and the mobile but the mobile app still will only see its sessions.

Web interface
![image](https://github.com/advplyr/audiobookshelf/assets/1214484/b017bb0f-3a90-4a61-877c-ecf608ec6d11)

Android App
![image](https://github.com/advplyr/audiobookshelf/assets/1214484/f0ed0023-2e0d-4699-b823-3552216c57aa)

### What did you expect to happen?

The mobile app should at least show the web sessions.

### Steps to reproduce the issue

1. Start a book on android
2. Switch to web player
3. Try to switch back to android

### Audiobookshelf version

v2.9.0 server, 0.9.73-beta android

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
https://logpaste.com/z19XWMfu
```

**Comment by nichwall** [comment]
The listening sessions you see on Android are device specific and do not sync with the server. The server listening sessions are only "total time listened during the session."

Listening sessions are planned to be reworked to allow for better syncing and viewing, but this hasn't happened yet (and I can't find the related feature requests for it at the moment)

**Comment by advplyr** [comment]
The play/pause history page is local only but the green cloud checkmark shows that it has been synced with the server.

Is the book downloaded? Have you tried this with other books?

**Comment by hskrtich** [comment]
This book is downloaded in the android app. I have tried this with others (including one that isnt downloaded) and I still cant get web progress to sync.

**Comment by hskrtich** [comment]
Ok, it doesnt seem to be happening with streamed books, just with downloaded books.

**Comment by advplyr** [comment]
M4B or MP3? Variable bitrate mp3 can have issues seeking correctly

**Comment by hskrtich** [comment]
M4B but now im not seeing the issue at all. I have no idea what has changed.

**Comment by advplyr** [comment]
Maybe a networking hiccup. Lmk if it becomes reproducible

**Comment by danielb2** [comment]
@advplyr this is happening for me. if I completely restart the android app, it will sync to the appropriate place. Maybe it would be useful to do a force sync on the app?
