### ISSUE TITLE
[Enhancement]: Name of file in failed upload response

### ISSUE THREAD

**Issue by lambchop01** [advplyr/audiobookshelf#2958]
### Describe the feature/enhancement

Hey, It would be nice to know the file name/ folder of a failed upload when uploading multiple books.  

I just tried to upload a series of 15ish books, and all I know is file #7 and #12 failed to upload.  To retry the upload of just those files I now have to compare files to the library and see what is missing.  If it could say "failed to upload xxx.m4b" that would really help!

![Screenshot 2024-05-09 120114](https://github.com/advplyr/audiobookshelf/assets/62576245/c2af7c5a-53b3-4e14-a984-6a2fa7ea4244)

**Comment by advplyr** [comment]
Added it before the success/fail message

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/600bdb1c-7b75-4026-a8fa-eb51d1f4301f)

**Comment by lambchop01** [comment]
That was fast! Awesome. Thanks!

**Comment by advplyr** [comment]
Updated in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
