### ISSUE TITLE
[Enhancement]: Store author image URL in author metadata, allow in-browser cropping of image

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2959]
### Describe the feature/enhancement

It would assist in editing the author image if the following was available:
- Storage of the image URL as part of the author metadata in AudioBookShelf
- Cropping and zooming of the image in-browser to better fit the dimensions that are used within AudioBookShelf.

**Comment by advplyr** [comment]
I don't understand what you mean with image URL in metadata. You mean an external URL to an image?

**Comment by ZLoth** [comment]
Yes, the External URL of where the author image was imported from.

**Comment by advplyr** [comment]
This isn't going to be supported and an in-browser image editor is outside the scope of the project.
User notes are planned though which will be a place you can store extra data in the future.
