### ISSUE TITLE
[Bug]: Metadata NFO and Covers not saving with library items for eBooks/PDFs

### ISSUE THREAD

**Issue by colvdv** [advplyr/audiobookshelf#2961]
### What happened?

I checked the box for metadata and covers to be stored with the library items but it is only doing so for my audiobook files. I have a library of PDFs also but the metadata doesn't seem to want to relocate itself.

### What did you expect to happen?

I expect metadata and covers to be found with the items they belong to, for all library items with metadata.

### Steps to reproduce the issue

1. Create eBook library, fill it with PDFs.
2. Edit metadata and covers for PDFs.
3. Toggle On "Store covers with item" and "Store metadata with item".
4. Refresh everything and patiently wait for it to move items, but it doesn't ever move them.

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Windows Tray App

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by nichwall** [comment]
The metadata is not moved automatically. Right now you will need to enable the "Store with..." settings first. The metadata files are written when the item is modified in ABS, so if the setting is enabled when you modify things, it will be saved with the media.

A tool to move the metadata and covers between the two locations is planned.

**Comment by colvdv** [comment]
I made changes to a few files shortly after receiving your reply but I am still not seeing .nfo or cover files being added to the item location. This is for my eBooks library which contains only PDFs and I have all of them in the same folder since I can edit metadata for individual book files within ABS easily and it organizes how I'd like, not sure if that matters.

A tool for moving these would be excellent. I am planning a switch from Windows to Linux soon and am thus preparing as best I can now for the changeover, organizing metadata and covers is a must!

**Comment by advplyr** [comment]
@colvdv Have you tried making a change inside Abs to see if it creates the metadata file? For example, add a random tag to one of the books that doesn't have a metadata file and see if it creates one in the book folder.

The cover isn't going to be moved unless you remove the cover from inside Abs and add it again.

**Comment by colvdv** [comment]
> @colvdv Have you tried making a change inside Abs to see if it creates the metadata file? For example, add a random tag to one of the books that doesn't have a metadata file and see if it creates one in the book folder.

Yes, I made changes earlier and again just now with the tags, but I'm not seeing any metadata files appear.

**Comment by advplyr** [comment]
Can you enable debug logs and make another edit in Abs for that book? If you watch the logs you will see debug logs about the update you made and then about it saving metadata to a file location. That file location is what we need to know about.

**Comment by advplyr** [comment]
Are the PDFs in sub-folders? If the PDF is in the library root folder it isn't going to put the `metadata.json` files there

**Comment by colvdv** [comment]
> Are the PDFs in sub-folders? If the PDF is in the library root folder it isn't going to put the `metadata.json` files there

No sub-folders, no. I have all of them in one folder, which is the library folder.


How might I go about moving them while keeping the metadata and covers? If I change the library directory I lose the metadata, that's the issue I'm experiencing.

**Comment by advplyr** [comment]
Moving the file into a subfolder should keep it the same item because it uses the inode value of the file. If you are using a network file system that isn't assigning inode values properly then you will have to remove the item from Abs and re-add it once it is in a subdirectory.
Moving a file from the root library folder to a sub-folder was fixed in https://github.com/advplyr/audiobookshelf/pull/2773. The original bug report was https://github.com/advplyr/audiobookshelf/issues/2767

**Comment by colvdv** [comment]
> Moving the file into a subfolder should keep it the same item because it uses the inode value of the file. If you are using a network file system that isn't assigning inode values properly then you will have to remove the item from Abs and re-add it once it is in a subdirectory.
>

Do I need folders for each book PDF, or would just author folders work with all PDFs from that author in the same folder?

**Comment by nichwall** [comment]
> Do I need folders for each book PDF, or would just author folders work with all PDFs from that author in the same folder?

All library items need to be in their own folder unless they are in the root folder.
