### ISSUE TITLE
[Bug]: Fetching author image from URL resets description text if not explicitly saved

### ISSUE THREAD

**Issue by OISumeko** [advplyr/audiobookshelf#2965]
### What happened?

When editing an author, I populated the description then provided a URL for the author image source. When I clicked the submit button to fetch the image, my description content was deleted.

https://github.com/advplyr/audiobookshelf/assets/9007982/8d1cf1f0-a85d-4194-899c-9c58e5f1f86b

### What did you expect to happen?

I expected the image to fetch and only update the image field, not also revert the description text. As I haven't left the edit window at any stage in the process it feels wrong for it to be resetting, my expectation is that the window holds changes in a staging/temporary space until I leave the window/tab or save it. 

This issue can be circumvented by editing the description text, clicking save, reopening the edit window, then continuing with the image selection process, but this feels quite awkward and I regularly make the mistake.

### Steps to reproduce the issue

1. Click the edit pencil icon on an author entry
2. Update the description field
3. Paste a URL into the image URL field
4. Click the Submit button to fetch the provided image
5. Note the description has reverted to its prior state

### Audiobookshelf version

2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

**Comment by ZLoth** [comment]
This occurs for me also in Chrome in Windows. Here is a recording. 

https://github.com/advplyr/audiobookshelf/assets/6700159/bc7cd91d-692d-450e-9786-ff7aac7fdb7d

**Comment by advplyr** [comment]
Fixed in [v2.10.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.1)

**Comment by ZLoth** [comment]
> Fixed in [v2.10.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.1)

Thank you!
