### ISSUE TITLE
[Bug]: Library's Series API Returning Empty Results Array

### ISSUE THREAD

**Issue by babatonga** [advplyr/audiobookshelf#2975]
### What happened?

When I try to fetch (GET) all series of a library I get an empty result:
`https://my-abs.tld/api/libraries/my-library-id/series`
```json
{
"results":[],
"total": 398,
"limit": 0,
"page": 0,
"sortDesc": false,
"minified": false,
"include": ""
}
```

### What did you expect to happen?

Like documented in https://api.audiobookshelf.org/#get-a-library-39-s-series I expect that all series and their books will be shown as array in results.

### Steps to reproduce the issue

1. Send a GET request to described API endpoint (with Authorization in headers)
2. Getting 200 response with empty results array

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Additional Notes

I have tried several query parameters but got the same result

**Comment by babatonga** [comment]
I just tried it with a limit and page set, now it works. Even with just limit set to 398 it's working.
So is there a hardoced limit or something like that if the response would be too big?

**Comment by advplyr** [comment]
The docs need to be updated since changing to the new database. A limit is now required and cannot be 0. Page is not required it will just default to the first page.

**Comment by advplyr** [comment]
I just updated the api docs. There are a few places it is out-of-date. We are working on auto-generated api docs but it will take some time.
