### ISSUE TITLE
[Bug]: "Collapse Series" checkbox breaks filter "No Series"

### ISSUE THREAD

**Issue by MikeBishop** [advplyr/audiobookshelf#2976]
### What happened?

In the Library view, if the "Collapse Series" checkbox is checked and the filter "Series > No Series" is applied, no results are shown.
![image](https://github.com/advplyr/audiobookshelf/assets/4273797/6137840d-e475-4219-accd-fa6c1b10c18b)

### What did you expect to happen?

If the checkbox is cleared, the filter works as expected:
![image](https://github.com/advplyr/audiobookshelf/assets/4273797/bb30f99f-4daa-4186-ad25-306b72f91242)

Since the books being returned do not have series to collapse, I would expect the checkbox to be a no-op in this view.

### Steps to reproduce the issue

1. Open Library view
2. Check the "Collapse Series" checkbox 
3. Apply the filter "Series > No Series"

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

**Comment by nichwall** [comment]
Was able to reproduce on 2.9.0.
However, the "Collapse Series" box works as expected when using the "Missing -> Series" filter.

**Comment by advplyr** [comment]
Fixed in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
