### ISSUE TITLE
[Bug]: Three dot menu jumps away from mouse pointer

### ISSUE THREAD

**Issue by chandz05** [advplyr/audiobookshelf#2980]
### What happened?

When trying to select an item on the 3-dot menu (within an ebook library specifically), the menu jumps to another part of the screen (see screen recording)

https://github.com/advplyr/audiobookshelf/assets/17502585/71123d77-ed6b-47d0-afeb-dbcd1d6266fb

### What did you expect to happen?

The menu should stay open where it appears.

### Steps to reproduce the issue

1. Click the dot menu on book on the main screen
2. Try to select a menu option

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Additional Notes

Audiobookshelf is installed via docker on Unraid. I have tried a fresh install.
Also to note, when selecting the menu in my Audiobook library, the menu behaves as expected and does not jump around. I have tried purging and recreating the ebook library, but that did not solve the issue either.

**Comment by chandz05** [comment]
> Could you verify the following:
> 
> * Does the same behavior happen if you put an ebook-only item in the audiobook library?
> * Does changing the cover aspect ratio change the behavior (square versus rectangle like in the video)?

1. Yes, same behavior on an ebook in the audiobook library. Audiobooks still behave as expected
2. Changing the cover aspect ratio does not change the behavior. I should have mentioned in my submission that that was one of the troubleshooting things I tried before as well.

**Comment by advplyr** [comment]
Fixed in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
