### ISSUE TITLE
[Bug]: Browser performance degradation after abs is left open in **chrome shortcut window** for an extended period of time 

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf#2983]
### What happened?

I've taken great advantage of the Google Chrome (current: 124.0.6367.207) Shortcut windows.  Not sure what else one would call them, but Chrome ⋮ > Save and Share > Create Window > ⌧ Open as Window.  I also have the built-in tab suspension enabled.
With audiobookshelf (abs) like a couple dozen other websites, the shortcut window uses the favicon for the desktop icon making the webpage more like an app which blurs the line with a PWA(?).  

After leaving abs open **in a shortcut window** for an undetermined time (on the order of several hours to a dozen hours), browser performance in other tabs will noticeably degrade:  primarily, if I am trying to read a document that extends beyond the current window, when I try to scroll there will be unacceptably long lags in responsiveness that make it impossible to navigate the document and read it properly.

**Hypothesis**: The reason I'm only seeing it in the shortcut window is because of the tab suspension, i.e., when I leave abs in a regular tab, it is suspended, but the shortcut windows do not get suspended.  As such, the hypothesis is that the reactive portions of the JS end up causing issues.  (There are also issues with gmail and google voice and some other google sites and they're currently included in this hypothesis).  The sheer number of idle wakeups vs. everything else seems to be in line with this hypothesis, though that could be merely correlation.

![Screenshot from 2024-05-17 10-16-36](https://github.com/advplyr/audiobookshelf/assets/535962/b7d6909b-f523-49ce-a0bb-2466a6d6bb12)

FWIW, as I was typing the above, it just happened again.  Switching to the abs tab (did not have to close it) fixed the problem, something I believe I observed last night, but I closed the window before I could really explore it.  The sheer number of idle wakeups in the task manager supports the hypothesis insofar as abs is definitely not sitting idle.

### What did you expect to happen?

Ideally there shouldn't be cross-talk between two browser windows, that's (what I thought was)  the point of the chrome sandboxing. 

### Steps to reproduce the issue

1. Create the shortcut window
2. Leave it open a while, probably on any library home view.
3. Wait 'till there's a problem in a tab in another window.

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Logs

```shell
Would chrome console logs even be instructive here?  How to output them?
```

### Additional Notes

**Extensions:**  I spent a good deal of time trying to isolate this problem to my extensions and had a fantastic time rationalizing all of them.  I now run with far fewer and the ones that remain are generally only active on click...this includes the adblock/cookie extensions I normally use, ghostery and ublocik origin.  As part of this effort, I switched to router-level ad blocking on my OpenWRT Cudy.  I'm not unwilling to look at them further, but I am fairly sure that will not be a profitable search.

**Other tabs:** I don't browse anything in isolation... I have lot of tabs open all the time (116 now) so it isn't really instructive to try this in isolation.  First, if it happens, so what, I'll never do that IRL, Second, I'll never leave my machine in that state long enough for the problem to develop...

**Comment by iconoclasthero** [comment]
**Extensions:**  I spent a good deal of time trying to isolate this problem to my extensions and had a fantastic time rationalizing all of them.  I now run with far fewer and the ones that remain are generally only active on click...this includes the adblock/cookie extensions I normally use, ghostery and ublocik origin.  As part of this effort, I switched to router-level ad blocking on my OpenWRT Cudy.  I'm not unwilling to look at them further, but I am fairly sure that will not be a profitable search.

**Other tabs:** I don't browse anything in isolation... I have lot of tabs open all the time (116 now) so it isn't really instructive to try this in isolation.  First, if it happens, so what, I'll never do that IRL, Second, I'll never leave my machine in that state long enough for the problem to develop...

**Comment by iconoclasthero** [comment]
This is going to be very difficult to duplicate but maybe someone else will stumble upon this with the same issue...

**Comment by nichwall** [comment]
I wonder if the chrome task manager would provide any additional information?
https://www.ninjaone.com/blog/chrome-task-manager/

**Comment by iconoclasthero** [comment]
Actually I came here to note that one thing that is happening is this...  In addition to closing the abs/app window, I can resolve the browser performance issue by simply opening or—I'm fairly sure, focusing on—the Chrome task manager.  Whatever SNAFU is going on behind the scenes with the browser, Chrome is e.g., resetting some buffer or whatnot when I open the task man.

**Comment by iconoclasthero** [comment]
The performance problem just reoccurred and there was not an ABS app window open.
In looking at those that were open, the one that is not usually or frequently open in an app window was Reddit and closing that solved the problem.

**Comment by nichwall** [comment]
Ah, nice! Glad you found it.
