### ISSUE TITLE
[Enhancement]: (Cosmetic) Add line about ensuring permission is provided to ereader provider when setting up ereader devices

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2990]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

In the Settings → Email Settings → Ereader Devices , there needs to be a disclaimer line stating that permission has to be provided in order for the ebooks to be emailed to the user. 

### Why would this be helpful?

While it is documented in https://www.audiobookshelf.org/guides/send_to_ereader#common-issues , this will actually call the issue out. 

### Future Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/a2b6b5c5-b010-4fcf-92ae-a1ef1187ad59)

### Audiobookshelf Server Version

2.9.0

### Current Implementation (Screenshot)

I don't have a image, but this would be something that would be assist a new administrator.

**Comment by advplyr** [comment]
Updated in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
