### ISSUE TITLE
[Enhancement]: List of Ereader devices should include access level

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2991]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

When setting up a e-reader device, there are several access levels available:
* Admin users only
* All users including guests
* All users excluding guests
* Specific Users

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/603d8b47-4b89-429a-9adf-272700e1c702)

However, when you display the list of devices, the associated access level isn't being displayed, and you have to edit the device to view the access level. 

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/ec0d84ff-479e-4ca4-8444-70393923c33e)

### Why would this be helpful?

It would make ereader administration easier in AudioBookShelf.

### Future Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/76b39277-986b-45d7-8c6a-d895d1890a92)

### Audiobookshelf Server Version

2.9.0

### Current Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/ec0d84ff-479e-4ca4-8444-70393923c33e)

**Comment by advplyr** [comment]
Updated in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)
