### ISSUE TITLE
[Bug]: Add timeout on matching with external providers

### ISSUE THREAD

**Issue by atais** [advplyr/audiobookshelf#3000]
### What happened?

I've chosed to fetch data from OpenLibrary but it takes ages. But I can't cancel. I need to wait :)

### What did you expect to happen?

Maybe 30 secs timeout? or configurable if possible

### Steps to reproduce the issue

1. match book with openlibrary
2. if it takes long you will see :)

### Audiobookshelf version

latest

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Logs

```shell
In the end its ok
```

**Comment by nichwall** [comment]
Some resources for additional reading

https://axios-http.com/docs/cancellation
https://stackoverflow.com/questions/68158083/how-to-handle-axios-timeout-with-hanging-api-server

**Comment by advplyr** [comment]
I set the default to 30s but for future reference this is controllable with a single variable in BookFinder

https://github.com/advplyr/audiobookshelf/blob/6fa49e0aab2309d6f64d08dcc18343f6d4c0694d/server/finders/BookFinder.js#L13

**Comment by advplyr** [comment]
Updated in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)

**Comment by WRLPDZ** [comment]
Hi @TN-SKYC

Can you change back this timeout to 30000ms as was before 2.30.0?

I'm getting [CustomMetadataProvider] Search error timeout of 10000ms exceeded when searching metadata from Audioteka or StoryTell.

Best Regards.
