### ISSUE TITLE
[Enhancement]: Ad detection and automatic skipping

### ISSUE THREAD

**Issue by Buchhems** [advplyr/audiobookshelf#3003]
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

In podcasts the server should be able to detect ads (using AI) and automatically cut them from the file.

### Why would this be helpful?

No more BetterHelp or Mailchimp ads. More listening to the real stuff

### Future Implementation (Screenshot)

I'm not sure.

### Audiobookshelf Server Version

v2.9

**Comment by nichwall** [comment]
Related to https://github.com/advplyr/audiobookshelf/issues/2203
https://github.com/advplyr/audiobookshelf/issues/2908

https://github.com/advplyr/audiobookshelf/discussions/2395

This is outside the scope of ABS and would fit more under as a third party tool or service that provides an RSS feed or edits your files.

**Comment by advplyr** [comment]
Yeah this is outside the scope of the project. #2203 would be the closest feature still in the "maybe" category of whether it will be added or not.

**Comment by samanthavbarron** [comment]
I was interested in this as well for ABS and came across this thread this morning.

I ended up writing a simple tool that monitors a directory for MP3 files and removes ads from them. It uses the OpenAI API to do this, but it wouldn't be too hard to swap out a self hosted model if you prefer.

Posting here in case other people come across this thread as well.

https://github.com/samanthavbarron/ad-begone

**Comment by paume** [comment]
> I was interested in this as well for ABS and came across this thread this morning.
> 
> I ended up writing a simple tool that monitors a directory for MP3 files and removes ads from them. It uses the OpenAI API to do this, but it wouldn't be too hard to swap out a self hosted model if you prefer.
> 
> Posting here in case other people come across this thread as well.
> 
> https://github.com/samanthavbarron/ad-begone

Hello, could add instructions on how to install /add this functionality to ABS? Thank you!
