### ISSUE TITLE
[Bug]: Failed to Ping Server

### ISSUE THREAD

**Issue by drknss89** [advplyr/audiobookshelf#3008]
### What happened?

Not sure if bug or user error, have set up on synology ds218.  When trying to connect to server When on network will always fail to ping server. When off network connects just fine. Any help would be greatly appreciated 
![Screenshot_20240524_164722_Audiobookshelf](https://github.com/advplyr/audiobookshelf/assets/93632931/ed75b56f-2a72-4f71-9b0b-66cbea17fa65)

### What did you expect to happen?

Expected to connect to server when on same network

### Steps to reproduce the issue

1. N/A

### Audiobookshelf version

2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Additional Notes

Synology NAS Container Manager

**Comment by advplyr** [comment]
I see you got help in Discord
