### ISSUE TITLE
v1.6.54 doesn't work on debian

### ISSUE THREAD

**Issue by szemlicka** [advplyr/audiobookshelf#302]
Hi, after installing v1.6.54, I get the error below. I switch back to v1.6.51 which works fine.

root@books:/usr/share/audiobookshelf# service audiobookshelf status
● audiobookshelf.service - Self-hosted audiobook server for managing and playing audiobooks
     Loaded: loaded (/lib/systemd/system/audiobookshelf.service; enabled; vendor preset: enabled)
     Active: failed (Result: start-limit-hit) since Sat 2022-01-08 12:10:37 CET; 1s ago
    Process: 1001343 ExecStart=/usr/share/audiobookshelf/audiobookshelf (code=exited, status=0/SUCCESS)
   Main PID: 1001343 (code=exited, status=0/SUCCESS)
        CPU: 531ms

Jan 08 12:10:37 books systemd[1]: audiobookshelf.service: Scheduled restart job, restart counter is at 5.
Jan 08 12:10:37 books systemd[1]: Stopped Self-hosted audiobook server for managing and playing audiobooks.
Jan 08 12:10:37 books systemd[1]: audiobookshelf.service: Start request repeated too quickly.
Jan 08 12:10:37 books systemd[1]: audiobookshelf.service: Failed with result 'start-limit-hit'.
Jan 08 12:10:37 books systemd[1]: Failed to start Self-hosted audiobook server for managing and playing audiobooks.

Here the error if I start it direct:
root@books:/usr/share/audiobookshelf# ./audiobookshelf
production Config /usr/share/audiobookshelf/config /usr/share/audiobookshelf/metadata /usr/share/audiobookshelf/audiobooks
[2022-01-08T11:11:24.522Z]  INFO: === Starting Server ===
[2022-01-08T11:11:24.522Z]  INFO: [Server] Init v1.6.54
(node:1001358) UnhandledPromiseRejectionWarning: Error: Function must return a value
    at validateFunction (/snapshot/audiobookshelf/node_modules/njodb/lib/validators.js:58:81)
    at Database.select (/snapshot/audiobookshelf/node_modules/njodb/index.js:365:9)
    at Db.load (/snapshot/audiobookshelf/server/Db.js)
    at Db.init (/snapshot/audiobookshelf/server/Db.js)
    at Server.init (/snapshot/audiobookshelf/server/Server.js)
    at async Server.start (/snapshot/audiobookshelf/server/Server.js)
(node:1001358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:1001358) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by advplyr** [comment]
Are you installing from the PPA?
Can you try v1.6.53?

**Comment by szemlicka** [comment]
v1.6.53 works fine.....:-)

**Comment by advplyr** [comment]
Great, thanks. Maybe it was just a corrupt build or something.

**Comment by advplyr** [comment]
Just released `v1.6.55` debian, if that doesn't work please re-open so I can investigate further

**Comment by szemlicka** [comment]
Hi,
I checked it today with the new bin audiobookshelf.1.6.55 and get the same error.
root@books:/usr/share/audiobookshelf# ./audiobookshelf
production Config /usr/share/audiobookshelf/config /usr/share/audiobookshelf/metadata /usr/share/audiobookshelf/audiobooks
[2022-01-09T09:48:02.687Z]  INFO: === Starting Server ===
[2022-01-09T09:48:02.687Z]  INFO: [Server] Init v1.6.55
(node:1024316) UnhandledPromiseRejectionWarning: Error: Function must return a value
    at validateFunction (/snapshot/audiobookshelf/node_modules/njodb/lib/validators.js:58:81)
    at Database.select (/snapshot/audiobookshelf/node_modules/njodb/index.js:365:9)
    at Db.load (/snapshot/audiobookshelf/server/Db.js)
    at Db.init (/snapshot/audiobookshelf/server/Db.js)
    at Server.init (/snapshot/audiobookshelf/server/Server.js)
    at async Server.start (/snapshot/audiobookshelf/server/Server.js)
(node:1024316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:1024316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by advplyr** [comment]
This is fixed now and `v1.6.58` debian is available https://github.com/advplyr/audiobookshelf-ppa

**Comment by szemlicka** [comment]
Hi, I checked it and it runs perfect. Thanks a lot.
