### ISSUE TITLE
download podcast to rss not found

### ISSUE THREAD

**Issue by Vincenzoferrara** [advplyr/audiobookshelf#3026]
### What happened?

I added a podcast rss  [https://www.spreaker.com[/]show/2960988/episodes/feed](url)

when I go to download the episodes it doesn't download them, or sometimes it seems that once downloaded it deletes them

I run audiobookshelf on a promox container but with a basic version of debian

the folder where I resolve the files is mounted with cifs in proxmox and then passed as a local folder

I have other not rss podcasts and they work

### What did you expect to happen?

donwload success

### Steps to reproduce the issue

1. add rss link https://www.spreaker.com[/]show/2960988/episodes/feed
2. download list episode

### Audiobookshelf version

v2.10.0

### How are you running audiobookshelf?

Debian/PPA

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
[PodcastManager] Podcast Episode downloaded but failed to probe "/mnt/nas/vincenzo/books/podcast/Survival Hacking/SP63 Survival Hacking - NAStardo !!.mp3" Probe Failed
```

**Comment by nichwall** [comment]
Related to ffmpeg/ffprobe issues with Debian https://github.com/advplyr/audiobookshelf/issues/3024

**Comment by advplyr** [comment]
Duplicate of #3024
