### ISSUE TITLE
[Enhancement]: missing translation

### ISSUE THREAD

**Issue by Machou** [advplyr/audiobookshelf#3027]
# Missings Translations

## 1

/config > ButtonPurgeItemsCache, a popup is opened and the text is:

```
Warning! This will delete the entire folder at /metadata/cache/items.
Are you sure you want to purge items cache?
```

![](https://i.ibb.co/fMcPKpD/1.png)

## 2

/config/item-metadata-utils/custom-metadata-providers

text missing: `No custom metadata providers`

![](https://i.ibb.co/ZSH0cj1/2.png)

## 3

/config/authentication

text missing: `Custom Message on Login`

![](https://i.ibb.co/h9q9qBp/3.png)

## 4

if i search Genre, tags, etc. button `Back` is not translate; example:

![](https://i.ibb.co/Z8rqqYx/a.png)

## 5

if i search a Tags, and Tags is empty, `No tags` is not translate; example:

![](https://i.ibb.co/WDXgkwP/b.png)

-----

# Unused string

l59 : "ButtonPurgeMediaProgress": "Purge Media Progress",

### Why would this be helpful?

Better translation/understanding.

### Audiobookshelf Server Version

2.10.1

**Comment by Machou** [comment]
I have found 2 news translation missing:

# Missings Translations

## 1

In the Notification

`Scanning file changes in "_name_"`

![1](https://github.com/advplyr/audiobookshelf/assets/1043650/796879ea-79d1-480a-b2aa-cd02d30db990)

## 2

Edit eBook > Tooltip of **ButtonReScan**

`Rescan library item including metadata`

![3](https://github.com/advplyr/audiobookshelf/assets/1043650/b180655c-a051-498b-817e-784adc282708)

**Comment by Machou** [comment]
### Edit eBook > Tooltip of **ButtonReScan**

`Rescan library item including metadata`

![3](https://github.com/advplyr/audiobookshelf/assets/1043650/b180655c-a051-498b-817e-784adc282708)

-----

### Settings > Your statistics > Show all

`No sessions yet...`

![335820590-b180655c-a051-498b-817e-784adc282708](https://github.com/advplyr/audiobookshelf/assets/1043650/c0d078be-329a-458d-a0d4-732159676296)

-----

### Settings > Emails

`No Devices`

![3](https://github.com/advplyr/audiobookshelf/assets/1043650/457cf0ca-058e-47a0-a649-f5a0468d6fb4)

**Comment by Machou** [comment]
Go on an item > on file list > More infos > button **Probe Audio File**

![1](https://github.com/user-attachments/assets/7563c856-a75e-4289-b637-bd016c00ffd3)

**Comment by nichwall** [comment]
This specific translation was not added in 2.12.0 due to the issue being reopened but still having the `awaiting-release` label applied.

You can reopen the issue or create a new issue with missing translations.
