### ISSUE TITLE
[Bug]: Anthologies with many authors result in player controls being displaced

### ISSUE THREAD

**Issue by EloquenceWinters** [advplyr/audiobookshelf#3038]
### What happened?

Whenever I have an anthology with a large-ish number of authors, the list of authors in the "player" strip at the bottom pushes the progress bar, chapter information, and controls down until they're no longer visible. This can be fixed by lowering the browser scale, but this isn't an optimal solution. 

![anthology](https://github.com/advplyr/audiobookshelf/assets/74223202/9ed9adf9-5d7a-47c9-92eb-e12af8ab9c50)

In the attached image, I've had to reduce the scale to 80% to even see the controls, and getting the progress bar and chapter information is impossible.

### What did you expect to happen?

The progress bar, chapter information, and controls should be static at the bottom of the player strip, so they are not lost when there are 10-20 authors in an anthology. 

### Steps to reproduce the issue

1. Add an anthology (e.g., The Big Book of Victorian Mysteries) with many authors (Otto Penzler, Waters, Wilkie Collins, Charles Dickens, James M'Govan, Eden Phillpotts, Moll Bourne, Dick Donovan, Arthur Conan Doyle, C. L. Pirkis, Max Pemberton, L. T. Meade, Clifford Halifax, Arthur Morrison, Headon Hill, George Griffith, M. McDonnell Bodkin, Fergus Hume, Emmuska Orczy, J. Sheridan Le Fanu, Catherine Crowe, Mary Elizabeth Braddon, Robert Louis Stevenson, Charles Reade, Thomas Hardy, Oscar Wilde, Robert Eustace, H. G. Wells, E. W. Hornungh, Grant Allen, George R. Sims, Guy Boothby, Pedro de Alarcón, Erckmann-Chatrian, Leo Tolstoy, Alfredo Oriani, Émile Gaboriau, Luigi Capuana, Guy de Maupassant, Anton Chekhov, Dietrich Theden, Edgar Allan Poe, Mark Twain, Ambrose Bierce, Frank Stockton, Melville Davisson Post, Anna Katharine Green, L. Frank Baum).
2. Try to play the book. 

### Audiobookshelf version

2.10.1

### How are you running audiobookshelf?

Windows Tray App

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Edge

### Additional Notes

I've selected my default ABS browser from the dropdown list (Edge, with ABS installed as an app), but the problem is browser-agnostic; I've tried Firefox, Chrome, and Opera as well.

**Comment by advplyr** [comment]
Fixed in [v2.11.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.11.0)
