### ISSUE TITLE
[Bug]: Episodes Not Downloading on Schedule

### ISSUE THREAD

**Issue by JakeB-OnGithub** [advplyr/audiobookshelf#3048]
### What happened?

New episodes for my subscribed podcasts are not automatically downloading anymore, although they were previously. I've put some information below, btu I'm not sure if there are any other logs or other information I can add. Please let me know if I'm doing something wrong!

I have a single library, named "podcasts". In it, I have several podcasts feeds, for this issue I'm looking at "Freakonomics Radio Plus", although it's true for all of them here.

Looking at the podcast, I see that Size is 0 bytes, which makes sense because I delete the episodes as I listen to them (could that be the problem? It wasn't before...)

If I hit the "Edit" button, under the "Episodes" tab, I have "Look for new episodes after this date" with today's date in it. Limit is set to 3. There's a button for "Check & Download New Episodes", and if I click it manually, it says "No new episodes found".

If I go to "Schedule", I have the interval set to "Every 15 minutes". The checkmark is enabled.

If I hit the search button manually, I can see recent episodes, among which is episode 590 which I have not yet downloaded. I can select it and hit "Download episode" manually, which works just fine. But why was that episode not downloaded automatically? How can I check that? Is there a log of previously-downloaded items that might list this for some reason, or some kind of activity log?

### What did you expect to happen?

I expect that this episode would have been downloaded.

### Steps to reproduce the issue

1. Start a VM running Ubuntu Server 22.04.4 LTS
2. Install Docker
3. Copy docker-compose.yml code from website
4. Add podcast subscriptions
5. Wait for new podcast to be released and note that it is not downloaded (for me, at least)

### Audiobookshelf version

2.10.1

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by nichwall** [comment]
Logs are stored under `/metadata/logs`, with crash logs stored in the `crash-logs.json` file. Your server may be crashing and restarting automatically. You can also change your server log level to Debug in the server settings (accessible when logged in as an admin user).

If you are using the "Search and Download New Episodes", you will need to change the date to in the past (because it only searches for episodes released after the specified date and time).

**Comment by JakeB-OnGithub** [comment]
https://github.com/advplyr/audiobookshelf/issues/1840

Turns out this was the issue...
