### ISSUE TITLE
[Feature Request] Additional Metadata

### ISSUE THREAD

**Issue by JKamsker** [advplyr/audiobookshelf#305]
ffprobe for my audiobooks from audible gives me following: 
```
    series          : Bobiverse
    series-part     : 3
    ASIN            : 3837146618
    track-language  : german
    spoken-language : german
    LANGUAGE        : german
```

- language
Can you add language to the search parameters? (It's custom/non standard but something like that would be very useful)
Somehow, ffmpeg doesn't echo out ``----:com.apple.iTunes:language``, so we would have to find an alternative key. 
I thought about "LANGUAGE" or ``spoken-language``
Im also not sure about wether or not we should use ``ISO 639-1``, ``ISO 639-2`` or no standard.

- ASIN
To gather more information from the audible servers later if necessary

- DateAdded/AddedAt
Overrides the value generated from Audiobookshelf. 
This allows for a better integration of my synchronizer (https://github.com/JKamsker/AudibleSyncService).
I would like to see my audiobooks sorted by the date i bought them on audible
Suggested formats:  ``DD-MMM-YYYY`` (01-Jan-2010) or ``YYYY-MM-DD`` (2010-12-24)

**Comment by advplyr** [comment]
Just released `v1.6.56` with support for language and ASIN meta tags.

Language tags on audio files can be either `language` or `lang` (case-insensitive)

ASIN tags on audio files can be `asin` (case-insensitive)

Note: the scanner actually only checks the first audio file after sorting, this might need to be adjusted but I suspect most people use the same meta tags for every audio file.

Added to details:
![image](https://user-images.githubusercontent.com/67830747/148708591-5057229e-acf6-4fdd-b82f-92a883c6a8e0.png)

ASIN is searchable:
![image](https://user-images.githubusercontent.com/67830747/148708577-28a782fa-a0ca-493c-b75b-34869bec391d.png)

Language is added as a filter option

ASIN is shown when matching with audible

**Comment by JKamsker** [comment]
Woha really didnt expect such an incredible fast implementation time :D
You are Great :)

Can i somehow modify the Added At parameter, to sort it by buydate from audible?

**Comment by advplyr** [comment]
For the DateAdded/AddedAt are you using existing ID3 tags for these?
I wasn't sure whether this should override the addedAt field already on the audiobook, or if it should be a separate field.

There is another issue open suggesting to use the created time from the filesystem to set the addedAt, but I'm not sure about that either.

**Comment by JKamsker** [comment]
Its not carved in stone, its just that I want to sort by buydate. 

I would do it via the tags, but im open for alternatives.
 
I could also introduce a BuyDate-tag if you could add this to the sorting column...

The fs thing...meh... Unintended file manipulation would fu** things up

**Comment by advplyr** [comment]
Just a heads up I had to re-deploy that version because of the typo.

I'll see if I can think of a way to handle the date, maybe adding another field is best.

**Comment by advplyr** [comment]
The purchased date field won't be supported at this time but this could change in the future. I'm trying to clean up the issues right now so they are manageable.
