### ISSUE TITLE
[Bug]: Edits made to author's names aren't saved

### ISSUE THREAD

**Issue by ReaderGuy42** [advplyr/audiobookshelf#3060]
### What happened?

I have several authors in my library where there were errors in the names, 

e.g. some books are attributed to `John Douglas` and some to `John E. Douglas`, so I get a duplicate author. So far it's fine, since it's just a middle initial, but to make him more identifiable, I change the first author to have the initial as well, and it correctly merges the authors. Good. 

However, it seems that if I remove and then add the docker image, e.g. after an update, or I just moved to a different device just now, the changes are reverted to the incorrect state again. 

I've corrected these errors several times, and I don't know why it doesn't save the changes.

I've used `ls -l` to see owner, etc. of my `metadata` directory, and I see that the `authors` folder hasn't been changed since April 23rd, which is weird since I've just been editing things. I don't know if this is helpful though. The only thing it's showing as having changed is `tmp`

Also this issue predates when I just changed the owner. I just did that today but I've been having the repeating errors for a few months.

### What did you expect to happen?

I would like the changes I make to authors or books to be saved. 
I'm not sure it was correct to change the user away from root? If so how do I reverse that so audiobookshelf can access the files again?

### Steps to reproduce the issue

1. See wrong author name
2. correct author name
3. reload audiobookshelf (e.g. after update)
4. author name back to being wrong

### Audiobookshelf version

2.10.1

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by ReaderGuy42** [comment]
I do have that setting on. And you're right, the metadata.json file in the book folder isn't being changed! So that's the problem. Do you know how to solve that?

**Comment by advplyr** [comment]
Can you share your settings?
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/ee4629ff-1678-4962-a338-fab91949fc08)

**Comment by ReaderGuy42** [comment]
![image](https://github.com/advplyr/audiobookshelf/assets/71895400/d84118b8-95af-4bf8-acf3-8ada84bd6745)

**Comment by ReaderGuy42** [comment]
Do you have any suggestions on what to try to change something?

**Comment by advplyr** [comment]
I would suggest checking the logs to see if you are getting permissions errors.

**Comment by ReaderGuy42** [comment]
Nothing shows up, even after making an edit:
![image](https://github.com/advplyr/audiobookshelf/assets/71895400/43b472e2-cb59-4b84-b83e-840bd629ab1b)
![image](https://github.com/advplyr/audiobookshelf/assets/71895400/44d16cee-77a1-4cd1-8d14-0c9a7af19dbc)

**Comment by advplyr** [comment]
I found the issue. If you want to try it out before the next release you can use the `edge` docker image.
