### ISSUE TITLE
[Enhancement]: A quick read/unread toggle on the main page

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#3065]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

It would be nice if I could toggle "only unread/unfinished" books with one click. Currently, I have to go to filter > progress > not-started to see books that I haven't read so far.

### Why would this be helpful?

saves time. helps find unfinished, next-to-listen-to book faster.

### Future Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf/assets/42061703/6d06840a-8bfa-4069-b6c9-b042713c0e33)
Replace "unfinished" with "not-started" (sorry, I didn't realize I used the wrong label)

### Audiobookshelf Server Version

2.10.1

### Current Implementation (Screenshot)

Library page (but applicable to any page with multiple books displayed - like series/collection)

**Comment by advplyr** [comment]
See https://github.com/advplyr/audiobookshelf/issues/3066#issuecomment-2161345590

Possibly a better option is to redesign the filter dropdown to include a few "quick" filters at the top but I don't know what this would look like
