### ISSUE TITLE
[Enhancement]: With companion ebook toggle

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#3066]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Another toggle would be for audiobooks with/without ebooks toggle.

### Why would this be helpful?

help find books faster.

### Future Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf/assets/42061703/47bca6d9-d094-45e3-80c4-d12069936abf)

the same but with "has ebook" instead of "unfinished"

### Audiobookshelf Server Version

2.10.1

### Current Implementation (Screenshot)

Library page, but applicable to any shelf page

**Comment by advplyr** [comment]
Not everyone puts ebooks in their libraries and/or would use that toggle if it was there. I don't think adding toggles there is a good idea since it is subjective to what you specifically filter for.
