### ISSUE TITLE
[Bug]: Importing chapters from OVERDRIVE MEDIAMARKERS tag is incorrect when items are over an hour per file

### ISSUE THREAD

**Issue by classicspam** [advplyr/audiobookshelf#3068]
### What happened?

When chapters are imported via the OVERDRIVE MEDIAMARKERS the chapter time calculation seems to be wrong if the number/time of the chapters spans 1 hour in a single file:

![chapter_error](https://github.com/advplyr/audiobookshelf/assets/2021242/ba4c9097-2252-4b1e-aa99-b5b6da48521b)

Where Line 12 and 13 are over an hour and line 14 is the start of the second file

the OVERDRIVE MEDIAMARKERS from the first file is as follows:

`<Markers><Marker><Name>"Blackstone Audio presents..."</Name><Time>00:00.000</Time></Marker><Marker><Name>Minus 100 and Counting</Name><Time>13:04.000</Time></Marker><Marker><Name>Minus 99 and Counting</Name><Time>19:47.000</Time></Marker><Marker><Name>Minus 98 and Counting</Name><Time>26:03.000</Time></Marker><Marker><Name>Minus 97 and Counting</Name><Time>28:54.000</Time></Marker><Marker><Name>Minus 96 and Counting</Name><Time>32:05.000</Time></Marker><Marker><Name>Minus 95 and Counting</Name><Time>35:30.000</Time></Marker><Marker><Name>Minus 94 and Counting</Name><Time>44:04.000</Time></Marker><Marker><Name>Minus 93 and Counting</Name><Time>46:32.000</Time></Marker><Marker><Name>Minus 92 and Counting</Name><Time>49:14.000</Time></Marker><Marker><Name>Minus 91 and Counting</Name><Time>56:05.000</Time></Marker><Marker><Name>Minus 90 and Counting</Name><Time>01:00:52.000</Time></Marker><Marker><Name>Minus 89 and Counting</Name><Time>01:07:31.000</Time></Marker></Markers>`

Please note that it does this for every file that crosses the one hour boundary. The chapter times fix themselves at the start of the next file.

### What did you expect to happen?

I expect that the chapter times import properly when total chapter time exceeds 1 hour per file.

### Steps to reproduce the issue

1. Import a book (split into multiple files) with OVERDRIVE MEDIAMARKERS that goes over 1 hour in a single file

### Audiobookshelf version

v2.10.1

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by advplyr** [comment]
Fixed in [v2.11.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.11.0)
