### ISSUE TITLE
[Bug]: OIDC not working in mobile app

### ISSUE THREAD

**Issue by Doug411** [advplyr/audiobookshelf#3069]
### What happened?

I'm unable to use oath in the mobile app.  When I set my redirects in Authentik as you listed (on separate lines).... I get a redirect uri error.  I'm using Nginx Proxy Manager.   Not sure how to fix it.   If I set my redirect URI to * it works, but I don't really want to do that.   It has always worked in browser, just not in mobile app unless I set the redirect to *.

Reference...(tried setting redirect in authentik as stated in thread below.  Not sure how to check x-forwarded-proto, but i've never had that issue on other OIDC apps.

for Authentik:

To add to this, in Authentik or other SSO software the redirect uri has to be set to:

https://youraudiobookdomain/auth/openid/callback
audiobookshelf://oauth
Don't use wildcards like .*, they are not required.
(In Authentik its seperated by new line, in Keycloak by comma afaik).

Also make sure your reverse proxy creates a X-Forwarded-Proto header correctly, otherwise you might receive a redirect_uri mismatch, because the redirect_uri is set to http even when the request was made using https.

### What did you expect to happen?

Successful login in mobile app

### Steps to reproduce the issue

1. open app.  click on oath login

### Audiobookshelf version

v2.10.1

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
xx
```

**Comment by nichwall** [comment]
Did you add the `mobile-redirect` mentioned at the end of the docs?

https://www.audiobookshelf.org/guides/oidc_authentication/

**Comment by Doug411** [comment]
No I missed that.   I added the redirect, but kept gettin a 400 error.  

 Then I uninstalled the app and reinstalled it.  When I reinstall it, it launches straight away into my audiobookshelf server with my account.  It didnt even direct me to authentik to get my login info.

 However when I delete my audiobookshelf cache and app data, and try to set it up manually be entering my external audibookshelf url and clicking SSO login,  I get a 400 error.   Then I uninstall the app, reinstall and it launches right back into my server.

How does it know my server URL from a fresh install and ID.  Is my database connection cached somewhere and somehow not fully deleted when i clear data/cache and uninstall the app, and therefore its not really doing a fresh install... Will new users will get the 400 error?   Or is it just vudu magic and I can accept that it will work for new users (hopefully it routes them to authentik and they can login successfully)

**Comment by advplyr** [comment]
Make sure to restart the server after making changes to the OIDC settings. Updating that after it is initialized is a work in progress.

After a successful login the users api token is used for authentication for all future auth attempts. The api token is cached but uninstalling and clearing data will remove it.

**Comment by advplyr** [comment]
Is this still an issue?

**Comment by JorisM** [comment]
@advplyr for me yes, with the latest docker version and the latest android app i get the same behaviour as described by @Doug411

**Comment by Sapd** [comment]
Probably access logs would be helpful (the one from the reverse proxy in front of authentik and the one in front of abs). I suspect a mismatch between http and http**s**. Is x-forward-proto set correctly?

@JorisM

**Comment by JorisM** [comment]
@Sapd 

I have authentik + adb behind the same traefik instance. If clicked on the login button, the access log for traefik spit out: 

    x.x.x.x - - [05/Aug/2024:07:18:26 +0000] "GET /auth/openid?code_challenge=1bTiYLr3VIWx5sy-IV6Yf9gPtv4vm2-trQYkYi5bWU4&code_challenge_method=S256&redirect_uri=audiobookshelf%3A%2F%2Foauth&client_id=Audiobookshelf-App&response_type=code HTTP/1.1" 400 20 "-" "-" 3534 "audiobookshelf@docker" "http://192.168.1.216:80" 6ms

where 192.168.1.216 is the audiobookshelf instance ip. 

authentik doesn't show any logs related to adb.

on the adb logs view, i see the following: 

    [Auth] Invalid redirect_uri=audiobookshelf://oauth

which is not what i have set though:

![image](https://github.com/user-attachments/assets/4d7753cc-bbb7-4812-8068-cd31d6f86db4)
![image](https://github.com/user-attachments/assets/5260bebf-3512-49ee-92a2-8715fb46b2ac)

maybe this default here somehow doesn't get overridden by the user preferences? 

https://github.com/advplyr/audiobookshelf/blob/8ff7b6b6e636a6d98bdb1f47e4658184b0c2ee1d/server/objects/settings/ServerSettings.js#L78C1-L78C67

let me know if this helps or i can provide something else

**Comment by Sapd** [comment]
@JorisM The redirect URls you specified is incorrect. 

The ones you specified have to go into the Authentik configuration.

If you want to use the official app, you just have to specify `audiobookshelf://oauth` if you also for example want to allow the 3rd party app plappa you have to also specify `plappa://oauth` 

The reason why you have to do this, is because Audiobookshelf itself (when you use the app) acts as a kind of oauth2 server, acting as middleman for your identity provider. It will replace the callback URL of the app `audiobookshelf://oauth` with the mobile-redirect URL against the iDP, because some identity providers do not like App-URL schemes. We also cannot allow every URL on default, as this would pose an open-redirect security vulnerability.

**Comment by JorisM** [comment]
ah you are right. sorry about that and thanks for the explanation! makes sense now. seems fixed for us. thanks again!

**Comment by jvines** [comment]
Hi! I'm still having this problem 😓 I have both redirect URIs and it works from my desktop, but not from iOS using Chrome or Safari.

It does work with '.*' but I obviously don't want to do that.

Could you help me out?

<img width="1050" alt="Image" src="https://github.com/user-attachments/assets/86b8be15-0cbc-4139-9e8f-7bdceb4d3b24" />

**Comment by jmadden91** [comment]
> Hi! I'm still having this problem 😓 I have both redirect URIs and it works from my desktop, but not from iOS using Chrome or Safari, as I get a 403 error.
> 
> It does work with '.*' but I obviously don't want to do that.
> 
> Could you help me out?
> 
> <img alt="Image" width="1050" src="https://private-user-images.githubusercontent.com/20781020/425886447-86b8be15-0cbc-4139-9e8f-7bdceb4d3b24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM1MDgyMDcsIm5iZiI6MTc0MzUwNzkwNywicGF0aCI6Ii8yMDc4MTAyMC80MjU4ODY0NDctODZiOGJlMTUtMGNiYy00MTM5LTllOGYtN2JkY2ViNGQzYjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDAxVDExNDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMjNjNjI5MWI0MjJhN2Q0Nzc5M2I4Y2EyMGEzN2Q4MjA1YmI2MjdmMWExNGY4OGExNDAyMDQ5MGQ0MzM3NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ss7rOyQQxLlrPH87JbsvFkRrgHSktgV1lDkLMLGN0cI">

You probably need: to add `/audiobookshelf`

Like this: 
```
https://absurl.com/audiobookshelf/auth/openid/callback
https://absurl.com/audiobookshelf/auth/openid/mobile-redirect
```

Due to this setting:

<img width="798" alt="Image" src="https://github.com/user-attachments/assets/c2d3bd74-a8cd-4776-ad76-d2e5c4f36c42" />
