### ISSUE TITLE
Re-scanning duplicates audio tracks

### ISSUE THREAD

**Issue by Eyeball753** [advplyr/audiobookshelf#307]
Every time a re-scan happens, all the audio tracks get added again. It doesn't matter if I force-scan the whole library or if I re-scan just a single book. It doesn't happen when I just do a normal scan of the library. Then it just says the library is already up-to-date or it only adds what's new.
In the screenshot you can see how it shows the all the chapters 3 times and it's not just a visual thing. I played it and it actually plays the chapters 3 times.
It's not a huge issue since you shouldn't re-scan often, anyway, but I thought I'd make you aware since I'm not seeing anyone else report this problem.
![firefox_2022-01-10_09-20-48](https://user-images.githubusercontent.com/63377657/148781389-f85fca18-43f8-4992-b48e-b595db0ff451.png)
![firefox_2022-01-10_09-21-14](https://user-images.githubusercontent.com/63377657/148781394-99d86072-9bb6-43d6-bab5-7330c2f2ebfc.png)

**Comment by advplyr** [comment]
What version of the server are you running?
Have you used other versions that were working properly?

**Comment by Eyeball753** [comment]
> What version of the server are you running? Have you used other versions that were working properly?

I'm running v1.6.56. It's through a container on Unraid. I have not tried any other versions, I only found out yesterday about Audiobookshelf. Is there another version you'd like me to try?

It also happens while copying new files (separate MP4s in this case, not just 1 M4B) to my audiobook folder. I assume because it re-scans on detecting a new file all the time. Currently I'm just manually fixing it by removing the book from Audobookshelf and then doing a normal scan.

**Comment by advplyr** [comment]
Just confirmed this is a bug with that version, going to patch now

**Comment by advplyr** [comment]
The problem was bigger than I thought so I released a new version, `v1.6.57`.

You should be able to re-scan and it will remove those duplicates, if not you will have to remove them manually.

**Comment by Eyeball753** [comment]
Wow, that was really quick. I just updated to test it out and can confirm that it's fixed. 
Thank you for fixing it and thank you for making this. I'm really digging the look of it compared to other similar applications out there. If I come across any other issues, I'll definitely let you know.
