### ISSUE TITLE
[Bug]: v2.10.1 there is no view chapters button when playing long audiobooks with chapter metadata

### ISSUE THREAD

**Issue by fureur7** [advplyr/audiobookshelf#3074]
### What happened?

there is no view chapters button when playing long audiobooks with chapter metadata
noramal:![Uploading e8e9957cb0c684579540c1596032862.jpg…]()
mine:
![d52e093dfc848514a6dc75d17f5f5e3](https://github.com/advplyr/audiobookshelf/assets/50503921/e209105d-7179-4c4c-990a-4ed4c58d901a)

### What did you expect to happen?

use the view chapters button

### Steps to reproduce the issue

synology nas with docker
1. add book type library
2. scan the audiobooks with a few chapter (more than 10)
3. become one long audio with no chapter button to choose the chapter

### Audiobookshelf version

2.10.1

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

**Comment by advplyr** [comment]
Does the audiobook have chapters?

**Comment by fureur7** [comment]
![image](https://github.com/advplyr/audiobookshelf/assets/50503921/d395b92e-36fc-4759-a58e-19730369e731)
yes sir 
It has chapters and desc.txt & reader.txt files in the root dir.

**Comment by nichwall** [comment]
Those are tracks (audio files), not chapters.

You can add tracks by going to the Chapter tab on the edit pop-up (the pencil button), then Editing chapters.

![Screenshot_20240613-224847.png](https://github.com/advplyr/audiobookshelf/assets/5686638/70708c41-4ae4-4d47-90e0-3fdaafc0e3e8)
