### ISSUE TITLE
Ubuntu Server cannot add PPA due to invalid GPG key.

### ISSUE THREAD

**Issue by njakes** [advplyr/audiobookshelf#308]
I am trying to install your service for the first time but am running into an issue following your instructions for the Ubuntu PPA install:

The key and list import ok, however, it fails upon updating.  I wanted to reach out in case it wasn't just user error on my end.

```
W: GPG error: https://advplyr.github.io/audiobookshelf-ppa ./ InRelease: The following signatures were invalid: F0BFFF44BC7DE9D288CF75C912269E7DCE24DB03
E: The repository 'https://advplyr.github.io/audiobookshelf-ppa ./ InRelease' is not signed.
```

**Comment by advplyr** [comment]
That error shouldn't prevent you from installing. It is because the PPA isn't officially registered, I just put it in a github repo. https://github.com/advplyr/audiobookshelf-ppa

Are you not able to install at all?

**Comment by njakes** [comment]
That is correct. I have tried to add the ppa and it won't update the sources due to the gpg issue. I also downloaded the latest Deb from the ppa repo. Dpkg returned something about it not being a valid deb file.  I can get you more later as I'm away from my computer.

**Comment by advplyr** [comment]
There was an issue with the deb files > v1.6.53, so I removed them and updated the PPA.
You can try installing v1.6.53

**Comment by njakes** [comment]
`dpkg-deb: error: 'audiobookshelf_1.6.53_amd64.deb' is not a Debian format archive
dpkg: error processing archive audiobookshelf_1.6.53_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 audiobookshelf_1.6.53_amd64.deb`

**Comment by njakes** [comment]
I was able to fix it by adding [trusted=yes]. It will now update from that repo, download the dependencies, and still fail when trying to install the deb unfortunately.
It is just saying 
`Erros were encountered while processing:
 /var/cache/apt/archives/audiobookshelf_1.6.58_amd64.deb
E: Sub-process /usr/in/dpkg returned an error code (1)`

**Comment by advplyr** [comment]
Can you provide details about your server setup? And are you running other media servers on there?

**Comment by njakes** [comment]
I am running Ubuntu Server 20.04 with Nextcloud, Plex and Jellyfin. I tried to download the deb from the repo that was updated yesterday and it gave the same error code complaining it wasnt a deb file. I wish I could provide you with more info.  I cant seem to find a dpkg log that will say what the error actually is.

**Comment by njakes** [comment]
I ended up installing PhotoPrism and after learning how to use docker-compose for that I muddled my way through installing this.

**Comment by advplyr** [comment]
Glad it is working for you now

**Comment by e0ipso** [comment]
I am still seeing the same issue here.

**Comment by e0ipso** [comment]
I could work around this by editing `/etc/apt/sources.list.d/audiobookshelf.list` so it reads:

```
deb [trusted=yes] https://advplyr.github.io/audiobookshelf-ppa ./
```
