### ISSUE TITLE
[Enhancement]: Update information on M4B files

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3082]
### Type of Enhancement

Documentation

### Describe the Feature/Enhancement

For the section https://www.audiobookshelf.org/faq/server → Should I use mp3 or m4b (or something else)?, there are a couple of suggestions for improvement in the guide from my perspective. Some of this is based upon my experience downloading my Audible library utilizing OpenAudible and initially converting the files as 100K VBR files, and then re-downloading the file as M4B files. 

- From a technical perspective, M4B files have better compression than MP3 files at the same bitrate. 
- Multipart M4B files seem to play fine from the web client as well as from the Android client. I don't have any iOS devices.
- It may be helpful to include a table of supported audio and ebook formats and any possible limitations.
- Is books encoded on FLAC supported? I know I have some books purchased from Humble Bundle that are in both FLAC and MP3 format, but FLAC tends to be larger. 

### Why would this be helpful?

This is some suggested clarifications in published documentation.

### Future Implementation (Screenshot)

Not applicable. 

### Audiobookshelf Server Version

2.10.1

### Current Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/604f201e-4300-409f-913d-bcdc5d897537)

**Comment by nichwall** [comment]
Thanks for the suggestion, the website repository is https://github.com/audiobookshelf/audiobookshelf-web if you would like to help update the answer.

As long as the media is DRM free and is supported by ffmpeg, it should be supported by ABS.

The client will attempt to direct play the audio. If the client cannot direct play (codec/container support, errors during playback), the server attempts to transcode the media. Playback can still fail during transcoding if there is a problem with the audio file (bad headers or bad audio data).

**Comment by advplyr** [comment]
I can't transfer this issue over to that repo since it is in the audiobookshelf organization
