### ISSUE TITLE
[Enhancement]: Add duration to web page chapter list

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3093]
### Type of Enhancement

None

### Describe the Feature/Enhancement

It would be nice to know the duration of a book chapter in addition to start and end times.

### Why would this be helpful?

It's helpful to know how long a chapter is without some mental arithmetic.

### Future Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/5b1f3a96-af93-4e4d-b209-c49c0d8663cb)

### Audiobookshelf Server Version

2.10.1

### Current Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/4593ae50-27ce-4d10-a81c-2a9101510c2d)

**Comment by ZLoth** [comment]
@advplyr Thank you! Looking forward to the next release.

**Comment by advplyr** [comment]
Updated in [v2.11.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.11.0)
