### ISSUE TITLE
[Optimization] Use nginx as reverse proxy in front of express

### ISSUE THREAD

**Issue by JKamsker** [advplyr/audiobookshelf#311]
Currently downloading is only half as fast as it would be possible. 
This is annoying, especially when i want to download an audiobook directly to my phone.

This could be solved by using nginx as fileserver and proxying api requests to express.
In my tests nginx almost always gave me 900+mbit while express only gave me 400-600mbit

Authentication shouldnt be an issue, because the "attacker" would have to know the exact path to the files. Those are already semi-protected by random id path-strings

Implementation should be pretty straight forward, maybe even with the same url schemes. If schemes change, clients would probably break :/

**Comment by mx03** [comment]
I don't think everyone does need a nginx and every docker should contain only one service, but a docker compose with a nginx that proxy the ui and override some paths for direct calls shouldn't be a problem.

For example for streams it is already possible (:
nginx maps the folder AUDIOBOOKMETA/streams/ AUDIOBOOKMETA/downloads/ , the ui with a reverse proxy and override the route to /hls/ and /api/download/

**Comment by JKamsker** [comment]
Oh nice thanks! 
I'll create a doc-pr explaining that for those who are interested as soon as i got it working :3

**Comment by JKamsker** [comment]
Thinking about that single service paradigm: nginx in front of the files and the api isnt exactly a separate service.

Its as much of a seperate service as ffmpeg or ffprobe which abs also needs to function.

**Comment by mx03** [comment]
No one docker container should use one service per container and use it as entry point. 
That would be the nodejs app, the app manage the subprocesses itself.

If you have this only in intranet you don't need a nginx or better performance.
If you have a server with many different apps you probably already have a gateway service like nginx.
A single docker without additional packed with nginx is only a unnecessary overhead.
If you dont have a nginx in front you could just use a docker compose.

**Comment by mx03** [comment]
Here is a working docker compose example:
https://gist.github.com/mx03/a83c1b274b833ad8ac25353bc892a57a
