### ISSUE TITLE
[Enhancement]: Add date to version in changelog.

### ISSUE THREAD

**Issue by xAhlen** [advplyr/audiobookshelf#3124]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Hi
Just feature request to include the release date in the version in the change log, just to make it easier to see if you're somewhat up to date.
Also clicking the changelog title could take you to the GitHub changelog?

### Why would this be helpful?

Makes it easier to see how old the version you are running are. 

### Future Implementation (Screenshot)

![330587111-5b04aa2d-bbc4-4e3e-b8f4-e306ce9bc093](https://github.com/advplyr/audiobookshelf/assets/24399180/29f57621-99f6-47e8-9139-898eba2b3a9b)

### Audiobookshelf Server Version

v2.10.1

### Current Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf/assets/24399180/ac823284-03be-4f1f-a3cb-87cd60be95d0)

**Comment by advplyr** [comment]
Added in [v2.11.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.11.0)
