### ISSUE TITLE
Failed to get track number for single file audiobooks

### ISSUE THREAD

**Issue by MartinCa** [advplyr/audiobookshelf#313]
Following commit afd2b8c98f9ec7c7615b469bffce23f9bc1b8094 the error message "Failed to get track number" is shown for single file audiobooks. Prior to this commit it seems `validateTrackIndex` was only called when an audiobook contained more than one file.

I believe the code could be changed to have a special case when there is only one file since sorting would also be trivial in that case.

**Comment by advplyr** [comment]
I actually fixed that in the release last night: https://github.com/advplyr/audiobookshelf/commit/e5f8be5b2460ed98f38564e9ff4a04622c578951

**Comment by MartinCa** [comment]
Sounds great, sorry about the issue then. I tested with scanning yesterday and decided to investigate why it was suddenly happening today.

I will test again.

**Comment by MartinCa** [comment]
I just rescanned my library and no errors reported this time so it seems the fix worked for me 👍
