### ISSUE TITLE
[Enhancement]: RSS Audiobook list order management

### ISSUE THREAD

**Issue by noahkiss** [advplyr/audiobookshelf#3137]
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

Currently, Audiobook RSS feeds sort based on the date/time the book was added to ABS. ABS correctly sorts the books by order when creating the RSS feed, but most clients use pubDate to sort items. This means that users are unable to edit the order of their RSS feeds, as "Date Added" is not exposed as an editable field in the client.

Instead, collection/series order should be used by default, where the first item in a collection/series is assigned the oldest pubDate (so that new additions are added as the newest episodes). The easiest way to accomplish this would be to assign fake sequential dates to sort the RSS feeds. 

The date should probably also leave room for adding mid-series books without needing to change the already existing items' dates, ex. always start at year 2020 and use increments of 10 days for the series to allow for numbers like `series #4.5` (gets assigned the 45th day in 2020).

A further enhancement could be a "sort" drop-down when opening a feed, then using the pubDate to sort based on the criteria the user selects.

### Why would this be helpful?

This would allow users to have control over the sorting of RSS feeds and more easily find the next book in a series or collection.

### Future Implementation (Screenshot)

<img width="858" alt="Screenshot 2024-07-08 at 11 59 11 AM" src="https://github.com/advplyr/audiobookshelf/assets/22437387/f19f15b2-1f05-46cd-9139-92a37aaf1f05">

### Audiobookshelf Server Version

v2.11.0

**Comment by advplyr** [comment]
I'm not entirely sure I understand everything you are suggesting but I can see how to fix the collection and series RSS feeds so that they are in order.
I can update it so that it uses the earliest book added at date as the starting point then add a day for each book.
If a new book were added, or if the order of the series/collection changed, then it would update the RSS feed.

**Comment by noahkiss** [comment]
That would be great! 

It sounds like you took the important parts from my ramblings, so it's probably not important that you try to make sense of the rest 😛 

Appreciate the reply & your work!
