### ISSUE TITLE
[Enhancement]: Disable maximum size for backups

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3157]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

As currently implemented, the maximum size of backups is 1 GB, although it is administrator-adjustable. It would be niuce to set it to 0 and not worry about the maximum size of backups. 

### Why would this be helpful?

As currently configured, ABS sets a maximum size for backups at 1 GB, although that is a administrator-adjustable option. I've had to increase it to 5 GB for the size of my library. However, while I can understand the need to limit the size of backups, I would like to disable the maximum size as it is very unlikely that a backup would exceed the 17TB I have available in my TrueNAS server.

If the feature already exists (e.g. setting the maximum size to 0 to disable), it is not documented in https://www.audiobookshelf.org/guides/migration-and-backups nor in the hover-over help. 

### Future Implementation (Screenshot)

Not applicable. 

### Audiobookshelf Server Version

2.11.0

### Current Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/c2a7654f-be28-42f8-a5af-3f8a888a1d2e)

**Comment by nichwall** [comment]
Fixed by https://github.com/advplyr/audiobookshelf/pull/3163

**Comment by ZLoth** [comment]
Thank you!
