### ISSUE TITLE
[Bug]:after upgrade complete library gone

### ISSUE THREAD

**Issue by rototom** [advplyr/audiobookshelf#3161]
### What happened?

after upgrade to 2.11.0 one of my two libraries is completely gone

### Steps to reproduce the issue

1. upgrade to 2.11.0., one library has been deleted

### Audiobookshelf version

2.11.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Other (list in "Additional Notes" box)

### Additional Notes

I have no idea what has happened, one library is completely gone!

**Comment by rototom** [comment]
Ok, so I made a mistake, I think....
Ich made up a new library in the webui and filled it with many (many) audiobooks.
Then I made the upgrade and docker compose down seems to have it killed. I didnt touch the docker-compose.yml, so the volume was not mounted. Perhaps we should clarify this in the documentation?

**Comment by advplyr** [comment]
I'm not sure what to clarify since that is how docker works. Here is the repo if you want to make a PR for suggested updates https://github.com/audiobookshelf/audiobookshelf-web
