### ISSUE TITLE
[Bug]: Shares, if timelimit is more then 23/24 days, it get removed after 1ms

### ISSUE THREAD

**Issue by Torstein-Eide** [advplyr/audiobookshelf#3164]
### What happened?

If trying to make a shared link with more then 23 days it get autoremoved.

#1768 

### What did you expect to happen?

I would not get autoremoved before the day expsire 

### Steps to reproduce the issue

1. Open share on audiobook
2. generate one at 23 days, it should work.
3. generate a new one at 25 days, it should fail.

### Audiobookshelf version

2.11

### How are you running audiobookshelf?

Debian/PPA

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```python
2024-07-16 08:27:12.044 INFO [ShareManager] Scheduled media item share "XXXXXXXX-61ca-4f26-9ea5-e3b9c17cd1a5" to expire in 2160002114ms
2024-07-16 08:27:12.045 INFO [ShareManager] Removing expired media item share "XXXXXXXX-61ca-4f26-9ea5-e3b9c17cd1a5"
```

**Comment by nichwall** [comment]
After more research, it looks like it may be due to the maximum value for a 32-but signed integer and that the expiration time is calculated based on milliseconds.

2^31 (signed integer) has a maximum value of 2,147,483,647 ms, or about 24.8 days.
