### ISSUE TITLE
Docker Image not pushed to hub.docker.com

### ISSUE THREAD

**Issue by typhooncarr** [advplyr/audiobookshelf#317]
Both the 1.6.58 and 1.6.59 images haven't been pushed up to Docker Hub. Docker Hub still shows 1.6.57 as latest version.

**Comment by advplyr** [comment]
That's because those other 2 versions were only related to the debian packaging, and I only incremented the version to play nice with the PPA.

**Comment by typhooncarr** [comment]
Ah, thank you very much for clarifying. Great project by the way. Closing issue.
