### ISSUE TITLE
[Enhancement]: Display additional or custom metadata tags

### ISSUE THREAD

**Issue by brianlg** [advplyr/audiobookshelf#3171]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

When viewing the Details of an audiobook, it would be helpful to customize this view to support additional metadata tags. Then these tag values can be viewed/edited. Additionally, it would be great to be able to choose which metadata tags display on the book page when you are viewing a specific audio book. 

### Why would this be helpful?

I use multiple metadata tags to maintain my collection. For example, I have a SOURCE field that I use to indicate where I purchased the audiobook (e.g. Audible, Apple Books, etc.) I also use something similar to ENCODEDBY to indicate what I used to encode the file (e.g. inAudible, Libation). This is helpful to know the source of my files, in case I want to go back and re-encode everything that I used inAudible for to now use Libation. Just a simple example. I'm sure others have different use cases. 

### Future Implementation (Screenshot)

Think mp3Tag where there's a default view of a files metadata tags. Then in settings you can choose which specific fields you want to display.

### Audiobookshelf Server Version

v2.11.0

**Comment by advplyr** [comment]
Do you see this being per user or per library? Where in the UI would you expect to see this?
