### ISSUE TITLE
[Enhancement]: Jump back to last played position (Auto bookmark?)

### ISSUE THREAD

**Issue by EddCase** [advplyr/audiobookshelf#3175]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

the ability able to jump back to the position when I last pressed play

### Why would this be helpful?

I primarily listen to audiobooks when I go to sleep, sometime my headset will die whist I'm asleep or I'll forget to set the sleep timer and I'll have no idea where I was in the book. An option to jump back to the last time I pressed play would be great to allow me to find roughly where I was the night before.

### Future Implementation (Screenshot)

Maybe this could be an automatically created bookmark?

### Audiobookshelf Server Version

v2.11.0  debian

### Current Implementation (Screenshot)

It would probably be best added as an automatic bookmark of "Last Played Position"

I noticed that it is already recorded in user stats in the web interface, could this be used to populate an automatic bookmark?

![Screenshot 2024-07-18 073230](https://github.com/user-attachments/assets/0612048d-8e68-4d75-8ce4-e9526102c167)

**Comment by advplyr** [comment]
Are you using the mobile app or web client to listen? The client manages playing/pausing/seeking and doesn't send a request to the server every time this happens necessarily. It will send sync requests in some instances but the server doesn't store the action that took place.

**Comment by EddCase** [comment]
Hi, thank you for replying, I'm not sure exactly what you are asking. I am using the Android version of the app. The feature I am asking for is a way to automatically add a bookmark when I press play, I noticed that the sessions get recorded on the server which show the start and end time of each session so suggested that as a way to populate the bookmark. I would like a feature to allow me to jump back to the start of the last session. So if my headphones die in the middle of a session whilst I am asleep or I forget to set the sleep timer I have an easy way to jump back to the begining of the session so I dont have to skip through manually to try and find a spot that I remember hearing

**Comment by nichwall** [comment]
You can view the "Play History" in the app, and tap on timestamps on the right of the screen to jump to that specific time.

![Screenshot_20240719-154825.png](https://github.com/user-attachments/assets/5abcdd3f-574e-472e-8045-3173e25ee708)

![Screenshot_20240719-154838.png](https://github.com/user-attachments/assets/5a7543ee-486b-4b67-8900-bdc425e1f42c)

**Comment by EddCase** [comment]
Thank you, I hadn't noticed that before. that will be useful

**Comment by advplyr** [comment]
This isn't going to be supported on the server at this time. That level of detail should be left up to the individual clients
