### ISSUE TITLE
[Bug]: Podcast episode match not properly encoding URL query param

### ISSUE THREAD

**Issue by onlineinternet** [advplyr/audiobookshelf#3177]
### What happened?

If I add a podcast series manually (ie episode files downloaded with yt-dlp) then add the RSS feed and try to match an episode, I get "No episode matches found"
I'm looking at the RSS feed and pasting in what's in the title tag. I even looked in the debug logs and saw that I'm successfully loading and parsing the RSS feed when I'm attempting to match.
What am I missing?

### What did you expect to happen?

I expected either a match or more information on why it wouldn't work.
A way to force a match would be great.

### Steps to reproduce the issue

1. Manually add podcast episode
2. Attempt to match it

### Audiobookshelf version

2.11.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### Logs

```shell
[2024-07-18 11:48:44.798] DEBUG: [podcastUtils] getPodcastFeed for "https://feeds.megaphone.fm/hubermanlab" (podcastUtils.js:229)

[2024-07-18 11:48:44.926] DEBUG: [podcastUtils] getPodcastFeed for "https://feeds.megaphone.fm/hubermanlab" success - parsing xml (podcastUtils.js:257)
```

**Comment by advplyr** [comment]
It is because of the `&` not being encoded in those titles. It will be fixed in the next release
