### ISSUE TITLE
loosing playback location when switching devices

### ISSUE THREAD

**Issue by argash** [advplyr/audiobookshelf#318]
### Discussed in https://github.com/advplyr/audiobookshelf/discussions/304

<div type='discussions-op-text'>

<sup>Originally posted by **argash** January  9, 2022</sup>
So I first noticed this issue with the web app on mobile safari. After getting the iOS test flight this morning, it went from happens every so often to happens every time. I reverted to web app and the problem reverted to happening occasionally. 

Specifically when I resume playback the location will revert to the beginning of the book. 

I am not sure yet if the issue is isolated to the book I happen to currently be listening to or if it happens to them all (I've got 4 hours or so left so I'm trying to get through it so I can test with another book). 

Also I'm not sure what logs to look at for details or what exactly to be looking for in them.</div>

**Comment by advplyr** [comment]
Is this happening also in a desktop browser?

There is an issue I'm aware of on the mobile app where progress stops getting synced when the app is closed and the audiobook is playing in the background. I recently fixed that for android, but some of that was a server update, so make sure to get the latest version of the server.

If you enable debug logs in config and watch the server logs while streaming an audiobook, you should see every 5 seconds a progress update is made.

**Comment by advplyr** [comment]
A lot has changed in v2. If progress syncing persists please open another issue.
