### ISSUE TITLE
[Enhancement]: Stream directly from Audible

### ISSUE THREAD

**Issue by ElysiumFic** [advplyr/audiobookshelf#3180]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Right now, if we want to include our Audible library in our AudioBookShelf libraries, we have to use Libation or a similar tool to liberate our Audible libraries. And while that's acceptable if it's our own purchased books, it's not if the book is borrowed from the Audible Plus library. If AudioBookShelf enabled to log in with our Audible credential to list books from our Audible Library (and possibly even stream them) then those books would appear in our AudiobookShelf library, as well as apps like ShelfPlayer or Plappa.

### Why would this be helpful?

It would allow us to include borrowed books from Audible Plus in our library without illegally downloading them. If Audible Plus works the way Kindle Unlimited works (KU plays authors by pages read, rather than books added to libraries), authors and possibly narrators probably only get paid for the portion of the book that is streamed. So this would enable to unify our independent and Audible libraries while still benefiting creators.

### Future Implementation (Screenshot)

![library2](https://github.com/user-attachments/assets/d96d749c-5bb3-43f6-beb7-0828c9bdc0e1)
![library](https://github.com/user-attachments/assets/b9462745-8806-4409-9d51-477f99594d2e)

### Audiobookshelf Server Version

2.8.1

### Current Implementation (Screenshot)

Home View

**Comment by nichwall** [comment]
ABS is designed to allow you to stream your local media files. Audible includes DRM on their streams and DRM removal is not planned to be included within ABS.

**Comment by advplyr** [comment]
This is outside the scope of the project
