### ISSUE TITLE
[Suggestion]: Make the cypress dependency optional (does not install on FreeBSD)

### ISSUE THREAD

**Issue by brendans-bits** [advplyr/audiobookshelf#3183]
### What happened?

When installing audiobookshelf >=2.10 from source, the client installation fails because cypress cannot be installed on FreeBSD.

This is a [known issue in cypress](https://github.com/cypress-io/cypress/issues/3382)

### What did you expect to happen?

N/A

### Steps to reproduce the issue

1. Install audiobookshelf from source on a FreeBSD system

### Audiobookshelf version

>= 2.10

### How are you running audiobookshelf?

Built from source

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Additional Notes

I have successfully installed audiobookshelf after changing cypress to an `optionalDependency` in package.json

I'm happy to submit a PR for this if you feel it is appropriate.

**Comment by advplyr** [comment]
I think it's no problem to move that to `optionalDependency` if you want to put in a PR for that.
