### ISSUE TITLE
[Enhancement]: Have your stats display thousands with a comma

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3187]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

This is similar to implemented suggestion [Enhancement]: Have library stats display thousands with a comma #2861. Simply put, if a number is in the thousands, add a comma to enhance readability. 

### Why would this be helpful?

It is easier to read.

### Future Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/66a55ce3-17f8-4d3c-beef-3b0ea5962549)

### Audiobookshelf Server Version

2.11.0

### Current Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/c0e4ed76-2a5a-4219-8f86-4941cf17bdba)

![image](https://github.com/user-attachments/assets/f9e0f128-1a57-41f9-ad2c-f206ff64f654)

**Comment by lkjfdsaofmc** [comment]
If this were to be implemented it should be noted some regions would need an option to have this display via periods instead of comma's. (1.000 instead of 1,000)

**Comment by ZLoth** [comment]
> If this were to be implemented it should be noted some regions would need an option to have this display via periods instead of comma's. (1.000 instead of 1,000)

This was addressed in the original feature request involving library stats that I linked to this request.

**Comment by advplyr** [comment]
> If this were to be implemented it should be noted some regions would need an option to have this display via periods instead of comma's. (1.000 instead of 1,000)

Number formatting uses the language setting
