### ISSUE TITLE
[Bug]: Uploading a large book to the server

### ISSUE THREAD

**Issue by ra3ggi** [advplyr/audiobookshelf#3191]
### What happened?

When  Uploading of a large book to the server ( 4 GB - 750 files), a maximum of 710 files are Uploading. 
There were made 5 attempts - always after 710-711 files failed. 
Is this a timeout limitation or on the number of files?

### What did you expect to happen?

Successful Uploading of a large book to the server

### Steps to reproduce the issue

Uploading a large book to the server ( 4 GB - 750 files)

### Audiobookshelf version

v2.11.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by advplyr** [comment]
Can you share more information? What is the error you are seeing? Have you looked at the logs? Are you using a local IP or are you behind a reverse proxy?

**Comment by Brynnan42** [comment]
I can confirm this or at least a related issue.

A friend of mine attempt to upload a 1.7GB audiobook (a single file) through the ABS interface from his house and office and it failed after a while.  Made several attempts from two locations.

He shared the book with me via cloud server, I downloaded it to my workstation and then used the ABS interface to upload it just fine.  All three places have highspeed internet, but it did seem to time out when attempting remotely.
