### ISSUE TITLE
[Bug] Collection & series RSS feeds are not using cover images

### ISSUE THREAD

**Issue by GKeckD2D** [advplyr/audiobookshelf#3193]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Currently, all RSS feeds have the same image, the standard ABS Logo.png of the white headphones around the three books on a shelf.
I'd like to be able to replace it with my own custom image or be able to set it per RSS feed when creating a new feed or editing an existing one.

### Why would this be helpful?

Being able to visually identify which feed a book came from would be helpful, no matter how you organize the content. Feeds by separate genres, feeds by series, feeds by author, whatever. I personally have many RSS feeds, with lots of crossover on content, but mostly I use two big feeds, One-Offs and Current Series. I try to break up a series by reading a one off book between each book in the series, so looking at a list of 15-20 books and seeing two One-Offs right next to each other is easier to spot when there is a visual difference based on what RSS feed they came from.

### Future Implementation (Screenshot)

![IMG_6773](https://github.com/user-attachments/assets/363ab333-8b94-424b-91c4-8c9458844a0e)
vs
![image](https://github.com/user-attachments/assets/2dc4b77c-ddcd-4b32-934f-ffcd685c5818)

### Audiobookshelf Server Version

v2.11.0

**Comment by nichwall** [comment]
Can you check for an `<image>` tag in the RSS feed?

I just opened an RSS feed for a book and see the cover image and I'm seeing cover images for my book. Or are you specifically referring to an RSS feed of something else?

Excerpt from my RSS feed:
```
<link>https://example.com/item/8a6743e1-83d9-49cf-b2fe-3e483e77e997</link>
<image>
<url>https://example.com/feed/8a6743e1-83d9-49cf-b2fe-3e483e77e997/cover.jpg</url>
<title>The Way of Kings</title>
<link>https://example.com/item/8a6743e1-83d9-49cf-b2fe-3e483e77e997</link>
</image>
```

**Comment by GKeckD2D** [comment]
Below is an example of a collection's RSS feed. All the book cover images are stored in the audio file itself as far as I can tell.

```
<rss version="2.0">
<channel>
<title>New Reads - One Offs</title>
<description>New Reads - One Offs</description>
<link>
http://example.com/collection/be124c69-7588-44b2-af7c-01925202fa9c
</link>
<image>
<url>http://example.com/Logo.png</url>
<title>New Reads - One Offs</title>
<link>
http://example.com/collection/be124c69-7588-44b2-af7c-01925202fa9c
</link>
</image>
<generator>Audiobookshelf</generator>
<lastBuildDate>Wed, 24 Jul 2024 13:07:32 GMT</lastBuildDate>
<atom:link href="example.com/feed/new-reads-one-offs" rel="self" type="application/rss+xml"/>
<language>en</language>
<author>
Robert Silverberg, Patrick Radden Keefe, Alaya Dawn Johnson & more
</author>
<itunes:author>
Robert Silverberg, Patrick Radden Keefe, Alaya Dawn Johnson & more
</itunes:author>
<itunes:summary/>
<itunes:type/>
<itunes:image href="example.com/Logo.png"/>
<itunes:owner>
<itunes:name>
Robert Silverberg, Patrick Radden Keefe, Alaya Dawn Johnson & more
</itunes:name>
<itunes:email/>
</itunes:owner>
<itunes:explicit>false</itunes:explicit>
<item>
<title>Lord Valentine's Castle</title>
<description>

**Comment by advplyr** [comment]
The image that is used in the RSS feed is the same one that is on the book/podcast in Abs. Do you have images set for all the books in the collection?

**Comment by GKeckD2D** [comment]
Yes, all the books in the collection have cover images
![image](https://github.com/user-attachments/assets/e9a9a55f-8375-4435-807c-e72b9e775aef)

**Comment by GKeckD2D** [comment]
Thank you!
