### ISSUE TITLE
[Enhancement]: Allow each user to define a "From Address" to use for emailing to their e-reader device 

### ISSUE THREAD

**Issue by MattBlackOnly** [advplyr/audiobookshelf#3196]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Firstly, thank you for creating this beautiful piece of software. I use it daily and I really appreciate the work that has gone into this.

My request is to allow each user to have an individual email address to use (the "from address") when sending to ereader device. 

So in essence each device can have its own send from and to address.

### Why would this be helpful?

Each user can setup their own email address and use that to send to device. 

That way  the root user doesn't need to add their own email address into the "Approved Personal Document E-mail list" 

### Future Implementation (Screenshot)

Update the current email settings to allow multiple email address definitions.

### Audiobookshelf Server Version

v2.11.0

**Comment by hardwareadictos** [comment]
That should be an amazing feature

**Comment by nichwall** [comment]
Is there a reason you can't have a single email address that everything is sent from? For example, I have an email specifically for my server that handles all email communication instead of my personal email.

**Comment by MattBlackOnly** [comment]
> Is there a reason you can't have a single email address that everything is sent from? For example, I have an email specifically for my server that handles all email communication instead of my personal email.

The main reason is that each user then has to add that email address into their "Approved Personal Document E-mail list" as opposed to using their own account

**Comment by hardwareadictos** [comment]
The idea would be that every user could set up it's own email service on its user settings with an own email address to send ebooks to a personal kindle/ebook reader 😃

**Comment by nichwall** [comment]
To me, it makes more sense to keep only one email set up for sending from on the server. Either way, configuration is required by a user (getting email settings correct, generating app app password if using Gmail).

Is this because users don't know how to add the server email to their trusted devices list and those instructions could be displayed somewhere in ABS to remind them?

**Comment by advplyr** [comment]
This would be allowing users of the server to enter in their own mail server address and port. Is that what you are requesting or just the ability to change the "From"?

**Comment by MattBlackOnly** [comment]
> This would be allowing users of the server to enter in their own mail server address and port. Is that what you are requesting or just the ability to change the "From"?

Thanks for taking the time to reply, I'm really enjoying ABS.

I'm having second thoughts on this feature, as its not that straightforward for each user to add their own "From" email address as @nichwall stated.

I originally wanted each user to setup there own "From" address and devices, (and then I thought setting up multiple "From" addresses and setting a different one for each user)

but now I think setting up a specific email address for the ABS server is probably a better way to do it.

**Comment by advplyr** [comment]
There is an open feature request for allowing users to setup their own ereader devices. https://github.com/advplyr/audiobookshelf/issues/1982

That may be what you are looking for. That seems like an administrative task to me but if enough users have that use-case we will figure something out. You can give it a thumbs up so it shows up higher when sorting for most wanted features.

It seems like we can close this issue now but let me know if not
