### ISSUE TITLE
[Documentation]: Documentation doesn't describe the 'Initial Server Setup'

### ISSUE THREAD

**Issue by paulhargreaves** [advplyr/audiobookshelf#3202]
### What happened?

On first load, 'Initial Server Setup' appears asking for a root user and password.
https://www.audiobookshelf.org/guides/library_creation excludes this step entirely and jumps straight into the 'Setting up a library' step. 

### What did you expect to happen?

The documentation to cover what the steps.

### Steps to reproduce the issue

1. Install.
2. Browse <url>.

### Audiobookshelf version

ghcr.io/advplyr/audiobookshelf:latest (version isn't shown on the bringup page)

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Other (list in "Additional Notes" box)

### Logs

```shell
Documentation.
```

**Comment by advplyr** [comment]
That guide is for setting up a library, that is why it doesn't show the initial server setup screen.
You can request guides here: https://github.com/audiobookshelf/audiobookshelf-web/issues
Although I'm not sure what would be said about that initial server setup screen.
