### ISSUE TITLE
Hide series from library

### ISSUE THREAD

**Issue by JKamsker** [advplyr/audiobookshelf#322]
I have a series (Perry Rhodan) with alot of episodes (200+) and it kindof floods my libary. 
Having a series tab and each episode in the library tab seems a bit redundant. 
Can we have a setting "Hide series from Library" ?

**Comment by mx03** [comment]
What do you think about showing only one entry for the whole series in the library and with a click on this you go to the series?

**Comment by JKamsker** [comment]
That might be even a better idea!

**Comment by advplyr** [comment]
I think there could be an option "collapse series" or something. 
My thought is it would live in the library toolbar next to the sort and filter dropdowns.

**Comment by advplyr** [comment]
While starting to add this I realized this had been brought up before and causes inconsistencies with sorting/filtering.

If you enable experimental features in `v1.6.60` you will see the collapse series checkbox above library.
Right now it just removes all but the first book in the series and adds the # of books in series over top. When clicking on the card it will take you to the series page.

The problem this causes is when selecting multiple books and batch editing/deleting it is not clear how this should function.
When sorting it is only going to sort using the first books values.

![image](https://user-images.githubusercontent.com/67830747/150887762-78e2fa0e-8040-4ba6-8d93-d41e70418a5c.png)

**Comment by jcrmit** [comment]
@advplyr - just gave this a go. Very nice - makes the library view super neat!
At the moment with batch editing - I use another process before going into Audiobookshelf, so will not run into that issue. 
Could you set the collapse series to off for certain filters?

**Comment by advplyr** [comment]
The filter is applied first. For example, if you have a series with multiple authors and filter by author, it will show the first book in the series matching that author.
The sort will always sort by the first book in the series after filtering.
That isn't too bad, but I think the batch editing is going to throw people off.

**Comment by mx03** [comment]
"The problem this causes is when selecting multiple books and batch editing/deleting it is not clear how this should function."
I would disable this at all for this type of entry. If someone want batch edit it he could disable the checkbox or go to the series and select all books inside.

**Comment by advplyr** [comment]
I moved this out of experimental. When hovering over the collapsed series you just see the series name now.

**Comment by trailingslash** [comment]
Any way to make it visible for users on Android?

**Comment by advplyr** [comment]
Sure I opened a feature request https://github.com/advplyr/audiobookshelf-app/issues/99

**Comment by Manantra** [comment]
would be nice to add this to iOS too
