### ISSUE TITLE
[Bug]: "server play request failed" and no covers via android app

### ISSUE THREAD

**Issue by jw2804** [advplyr/audiobookshelf#3222]
### What happened?

I see covers for all my audio files when accessing ABS on my PC and I can play the files with no issue but I dont see any covers when using the android app, when I hit "stream" I get the error "server play request failed" I can play audio files and see covers when I use the browser on my phone.

### What did you expect to happen?

I expect to be able to play my audio files and see my audio files have covers.

### Steps to reproduce the issue

I recently moved from Synology NAS to an Unraid NAS. I did a fresh install then a restore from back up and copied my audio files over. Accessing ABS on my Unraid NAS via my PC is fine, everything works as it should but when I connect the Andriod app to my Unraid NAS I dont see any covers and I get the "server play request failed" error.

### Audiobookshelf version

v 2.11.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Additional Notes

I uninstalled the Android app, restarted my phone, reinstalled the app and reconnected - still the same
I tried using the IP address rather than the domain name - still the same

**Comment by nichwall** [comment]
Did you restore from backup before copying the media files, or copy the media files first? The server may have detected the "newly created files" as new media and gotten the database into a weird state if you restored from backup first, but that doesn't really make sense if streaming is working in the browser.

When you say you can "play audio files" are you talking about in the web browser, or downloading the media files and playing them manually? Are you downloading media files from within ABS?

Can you enable debug logs in the settings and provide logs?

**Comment by DirkIngo** [comment]
I have the extact same bug. Everything works as expected inside the browser (PC and phone). The android app has the same behavior as described here. No covers not able play audio and Im getting logged out everytime accessing the app. Upgraded to 2.12.1 had the bug with the "corrupted" db and had to use the backup.

**Comment by jw2804** [comment]
Thanks for getting back to me. I didn't touch it for a couple of days as I'm moving all my "stuff" to my new NAS, when I next checked all the covers where there !

**Comment by Maximilian85** [comment]
I also currently have the error, I have set up the server again and imported a backup. Now only playback via the browser works. No covers are displayed in the app and I can't start an audio book.
