### ISSUE TITLE
[Bug]: Podcasts hosted on captivate.fm can no longer be downloaded

### ISSUE THREAD

**Issue by Peter-Maguire** [advplyr/audiobookshelf#3227]
### What happened?

Podcasts hosted on captivate.fm no longer work as they seem to be requiring authentication for any user-agent containing iTMS. 

### What did you expect to happen?

The podcasts should download correctly, however they give a 401 error. Other podcast providers are okay, but captivate hosts a sufficiently large amount of podcasts that I believe this is an issue that needs addressing.

### Steps to reproduce the issue

1. Add a podcast RSS from captivate.fm e.g https://feeds.captivate.fm/ed-gamble-matthew/  
2. Attempt to download an episode
3. The episodes will never load, and the log will display a 401 error

### Audiobookshelf version

v2.11.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
08-04 12:00:04.735

ERROR

[ffmpegHelpers] Failed to download podcast episode with url "https://dax.captivate.fm/677842cd-ffef-40af-a52c-3e45e29e7902/TM-POD-164-First-Cut-encoded.mp3?aw_0_1st.showid=0fabcf2a-33fb-4368-8a52-38fcfe82c2ad&aw_0_1st.episodeid=93a30615-c608-407e-84db-78be54305f2f" AxiosError: Request failed with status code 401
```

### Additional Notes

I would suggest either adding the ability to set a custom user-agent, or hardcoding a workaround for captivate.fm

**Comment by advplyr** [comment]
I missed this one. It is the same as https://github.com/advplyr/audiobookshelf/issues/3246 and was patched in v2.12.2
