### ISSUE TITLE
Ability to sort series by a user-defined tag

### ISSUE THREAD

**Issue by jkuettner** [advplyr/audiobookshelf#323]
I wonder if it is possible to sort the series by a specific metadata tag?

I have some audiobooks (among others from Audible) which has `series_sequence` as tag in the metadata. I would find it great if I could sort the series by this tag, if it is available.

**Comment by advplyr** [comment]
Is that just another term for volume #?

**Comment by jkuettner** [comment]
volume would also be ok for me. Basically I want to sort the series by some metadata tag other then title.

**Comment by advplyr** [comment]
what is the series_sequence tag though, is that just a number?
Is that in the audio file metadata? where are you seeing that?

**Comment by jkuettner** [comment]
I believe `series_sequence` is a custom field in the metadata, or id3 tags. I assume it is a string field, so that also values like `1/5`, `2/5`, ... `5/5` are possible.

Here is an example output from `mediainfo` of a local audiobook from my collection:

```
General
Complete name                            : audiobook.m4b
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/mp41)
File size                                : 863 MiB
Duration                                 : 15 h 16 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 132 kb/s
Album                                    : Ab die Post: Scheibenwelt 33
Track name                               : Ab die Post: Scheibenwelt 33
Performer                                : Terry Pratchett
Genre                                    : Hörbuch
Recorded date                            : 2013
Tagged date                              : UTC 2022-01-11 21:05:09
Writing application                      : Lavf58.76.100
Cover                                    : Yes
series_sequence                          : 33
series                                   : Scheibenwelt
[...]
```

**Comment by advplyr** [comment]
I haven't heard of that tag being used before, do you have a lot of audiobooks using that? I'm wondering how common this is.

Right now the scanner looks for the tag `series-part` and uses it as the volume number: https://www.audiobookshelf.org/docs#metadata

**Comment by jkuettner** [comment]
This is exactly what I was looking for, but unfortunately overlooked. The tag `series_sequemce` I have simply taken over from audible, without questioning this. But with `series-part` I get along just as well. Thanks for the clarification!
