### ISSUE TITLE
End of Chapter Sleep Timer Incorrect

### ISSUE THREAD

**Issue by tomatosoupcan** [advplyr/audiobookshelf#324]
When setting playback speed above 1.0, the end of chapter Sleep Timer incorrectly sets a timeout equal to the default playback speed.

**Comment by tomatosoupcan** [comment]
Fwiw this is only visual but it is confusing. Also forgot to note this is on the Android client. Untested but I presume this means that setting a timer in sped up mode will mean a shorter timer than you expect also.

**Comment by advplyr** [comment]
This issue was brought up on the mobile app repo already https://github.com/advplyr/audiobookshelf-app/issues/86
