### ISSUE TITLE
[Enhancement]: missing translation 2.12.1+

### ISSUE THREAD

**Issue by Machou** [advplyr/audiobookshelf#3242]
#### 1

Go on an item > on file list > More infos > button **Probe Audio File**

![1](https://github.com/user-attachments/assets/e6f9608c-19e6-4cc8-be3d-acb6dfdb92d6)

-----

#### 2

Go to an item (need be View) > Remove the tooltip > Alert: **Are you sure you want to reset your progress?**

![3-min(1)](https://github.com/user-attachments/assets/ce6898cf-12d1-4235-9023-14e8c8174257)

-----

#### 3

Start Reading an Audio Book > Sleep timer > Button **Set**

![Capture d’écran 2024-08-10 023135](https://github.com/user-attachments/assets/a2a1872e-1962-4127-8efa-b999d268561a)

-----

#### 4

Start Reading an Audio Book > Click on reset timer > Tooltip Popup: **Your progess was reset**

![a](https://github.com/user-attachments/assets/34459402-c813-43ad-9da1-344059d186be)

-----

#### 5

Upload a file: **Updated** & **Added**

![Capture d’écran 2024-08-11 234335](https://github.com/user-attachments/assets/85a4f847-9fc6-4468-990a-eff3a509cf07)

-----

#### 6

On eBook > Go to **Find** > Tooltip **Please wait**

![6](https://github.com/user-attachments/assets/98fc205f-ccc5-43fe-af47-accdc63b1c6c)

-----

#### 7

Go to **Library** > Sort by **File creation** > Below a book > **Born**

Same fr **Modified**
Same for **Duration**
Same for **Size**
Same for **Added** 
Same for **Published**

![Capture d’écran 2024-08-12 001533](https://github.com/user-attachments/assets/5baa116e-ccf5-4129-8b2b-64b01885a1a1)

-----

#### 8

Go To Authors > if 1 book, book have a **s**

1 book
2 book**s**

![Capture d’écran 2024-08-20 124812](https://github.com/user-attachments/assets/4c5b07ce-ff2b-44ad-8a08-c13db47bbb48)

**Comment by MikeGold** [comment]
Same in Polish.
Potential translations for your convenience:

1. 
Zbadaj plik audio

2. 
Czy jesteś pewien, że chcesz zresetować swój postęp?

3. 
5 minut
15 minut
30 minut
45 minut
60 minut
90 minut
2 godziny
Koniec rozdziału

4. 
Twój postęp został zresetowany

**Comment by Machou** [comment]
> Same in Polish.
> 
> Potential translations for your convenience:
> 
> 
> 
> 1. 
> 
> Zbadaj plik audio
> 
> 
> 
> 2. 
> 
> Czy jesteś pewien, że chcesz zresetować swój postęp?
> 
> 
> 
> 3. 
> 
> 5 minut
> 
> 15 minut
> 
> 30 minut
> 
> 45 minut
> 
> 60 minut
> 
> 90 minut
> 
> 2 godziny
> 
> Koniec rozdziału
> 
> 
> 
> 4. 
> 
> Twój postęp został zresetowany
> 
> 
> 
> 

Missing translations is for all languages (except en 🫣)

If you want to contribute to the Polish translation you can go to Weblate: https://hosted.weblate.org/engage/audiobookshelf/

😃

**Comment by Machou** [comment]
#### 5

Upload a file: **Updated** & **Added**

![Capture d’écran 2024-08-11 234335](https://github.com/user-attachments/assets/85a4f847-9fc6-4468-990a-eff3a509cf07)

**Comment by Machou** [comment]
-----

#### 6

On eBook > Go to **Find** > Tooltip **Please wait**

![6](https://github.com/user-attachments/assets/98fc205f-ccc5-43fe-af47-accdc63b1c6c)

**Comment by Machou** [comment]
#### 7

Go to **Library** > Sort by **File creation** > Below a book > **Born**

![Capture d’écran 2024-08-12 001533](https://github.com/user-attachments/assets/5baa116e-ccf5-4129-8b2b-64b01885a1a1)

**Comment by Machou** [comment]
#### 8

Go To Authors > if 1 book, book have a **s**

1 book
2 book**s**

![Capture d’écran 2024-08-20 124812](https://github.com/user-attachments/assets/4c5b07ce-ff2b-44ad-8a08-c13db47bbb48)
