### ISSUE TITLE
[Bug]: Icons broken after 2.12.0 / 2.12.1

### ISSUE THREAD

**Issue by Silther** [advplyr/audiobookshelf#3243]
### What happened?

text instead of icons for a few minutes
![image](https://github.com/user-attachments/assets/fe689290-679c-4180-b800-9e55ab5d5315)

### What did you expect to happen?

icons should be displayed

### Steps to reproduce the issue

1. open the homepage
2. for up to a few minutes there is text instead of the icons
3. icons will load correctly

### Audiobookshelf version

v2.12.1

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

**Comment by BerendWouters** [comment]
I actually encountered this too, but doing a hard refresh of the browser fixed the issue. Might be an issue related to some caching.

**Comment by advplyr** [comment]
Did a refresh fix the issue @Silther ?

**Comment by advplyr** [comment]
We changed font libraries so my guess is the browser has cached the old font. Is the issue reproducible still or is there any other information you can give?
