### ISSUE TITLE
[Enhancement]: centre the play button 

### ISSUE THREAD

**Issue by Silther** [advplyr/audiobookshelf#3244]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

centre the green play button in the browser window
or add a offset to the chapter name so they are both symmetrical 

### Why would this be helpful?

It would look better as the button is currently not centred.
![image](https://github.com/user-attachments/assets/2e69ca14-6ab1-49ba-bd3d-605ce08bf24c)
![image](https://github.com/user-attachments/assets/a6a48ff0-7bb4-4252-92b1-4f3ad0e14b52)

### Future Implementation (Screenshot)

Old
![Screenshot 2024-08-05 215507-1](https://github.com/user-attachments/assets/4f004de4-c80b-4662-a5bf-d3c802246d0b)
New
![Screenshot 2024-08-05 215507](https://github.com/user-attachments/assets/087429d3-24d0-4bf8-8bee-55471b33b155)

### Audiobookshelf Server Version

v2.12.0

**Comment by glorenzen** [comment]
I second this.

One way to fix this would be to remove or add an item in the playback controls. The playback controls are centered, but since there is an uneven number of icons, the play button is not centered.

I can tackle this if someone hasn't already started.
