### ISSUE TITLE
[Enhancement]: Skip cache for random library sort option

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#3249]
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

When selecting "Randomly" sort option skip the API cache.

### Why would this be helpful?

We want a random order on every load

### Future Implementation (Screenshot)

~

### Audiobookshelf Server Version

v2.12.1

**Comment by ZLoth** [comment]
Looking forward to the release. Thank you.
