### ISSUE TITLE
[Bug]: Server not reachable and unusual CPU use

### ISSUE THREAD

**Issue by Lebo77** [advplyr/audiobookshelf#3256]
### What happened?

I noticed something on my ubuntu server was using 100% of the CPU on a single thread. the Command was "node index.js". I tracked it down to the audio bookshelf docker container. I tried to connect to the server via the web interface but there was no response. I reset the container and everything returned to normal with no unusual CPU use.  

### What did you expect to happen?

The server to run normally with no unusual CPU use. 

### Steps to reproduce the issue

Unknown. I will report back if it happens again. 

### Audiobookshelf version

2.12.1 docker

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
No relevant logs. Noting in the crash log or daily logs looks unusual.
```

**Comment by cwar** [comment]
I'm having same issue here, 2 days in a row server unreachable... running on k8s and my `kubectl top` gave me 

```
NAME                                         CPU(cores)   MEMORY(bytes)
audiobookshelf-deployment-7f8d95444f-t94m8   1000m        80Mi
```

i dont have a request or limit set on cpu since it usually uses so little... i thought it was odd it was at 1000m?

**Comment by nichwall** [comment]
Yeah, duplicate of https://github.com/advplyr/audiobookshelf/issues/3251

**Comment by Lebo77** [comment]
> Yeah, duplicate of #3251

Agreed. Maek
