### ISSUE TITLE
[Enhancement]: Ebooks onlyⓘ library setting

### ISSUE THREAD

**Issue by danielb2** [advplyr/audiobookshelf#3264]
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

As there is a toggle for `Audiobooks only` in a library, it would be useful to have a `Ebooks only` setting. 

### Why would this be helpful?

ebooks are single files and do not need to be organized the same way in folders. For example, a common way to organize files is having files in subfolders in authors for epub, but not a subfolder per book. Current behavior means books are grouped together which is undesired. 

Consider the difference here:

```plaintext
.
├── audiobooks
│  └── author
│     ├── title01
│     │  ├── chapter01.mp3
│     │  └── chapter02.mp3
│     └── title02
│        ├── chapter01.mp3
│        └── chapter02.mp3
└── ebooks
   └── author
      ├── title01.epub
      └── title02.epub
```

Example result current behavior:
<img width="1027" alt="Screenshot 2024-08-10 at 09 31 56" src="https://github.com/user-attachments/assets/4c36f80c-a63f-4b43-80b1-1862659064fc">

Clearly these should be separate books, and I think for ebooks a simple recursive search will do.

<mark>Alternatively instead of a ebooks only setting, just handle epub differently</mark>

### Future Implementation (Screenshot)

<img width="695" alt="Screenshot 2024-08-10 at 09 33 35" src="https://github.com/user-attachments/assets/958cc036-5b06-4dbf-9aea-41633b164191">

add ebooks only option here to force simple recursive scan for ebooks. I'm not sure if cbr or other formats are handled differently, but needing a folder per book for epub doesn't make so much sense

### Audiobookshelf Server Version

v2.12.1

### Current Implementation (Screenshot)

N/A

**Comment by nichwall** [comment]
Related to https://github.com/advplyr/audiobookshelf/issues/2314 and https://github.com/advplyr/audiobookshelf/issues/2338

**Comment by danielb2** [comment]
Closing since #2314 seems to mostly cover this. I'll add my comments there
