### ISSUE TITLE
[Enhancement]: ABS cannot scan files which begin with a dot (Documentation)

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3274]
### Type of Enhancement

Documentation

### Describe the Feature/Enhancement

For the following pages:
* https://www.audiobookshelf.org/guides/book-scanner
* https://www.audiobookshelf.org/docs#book-title-folder-naming
* https://www.audiobookshelf.org/faq

It should be noted on Linux hosts, a file or folder that begins with a dot is considered "hidden", and is not scanned in by audiobookshelf. 

### Why would this be helpful?

Just to understand my configuration... my main computer is a Windows computer, but the server which I use to host ABS is a TrueNAS SCALE (Linux) running ABS as a docker container. The title in question is located at https://www.audible.com/pd/And-Your-Ass-Will-Follow-Audiobook/B0CS1S6HXK , and the title begins with three dots. This file converted normally, but included the three dots at the beginning. However, *nix OS treats the leading period as a hidden file/folder, and ABS is unable to scan the file. 

The workaround is simple: Just rename the file so that any leading dots are gone. The ABS database can hold the "true" title. 

This is such a corner case that I don't think any code fix would be worth the trouble. I have several thousand audiobooks, and this is the only title with the issue. And the only reason I have it is because it is a free Audible "Plus" title

### Future Implementation (Screenshot)

Not applicable. 

### Audiobookshelf Server Version

2.12.2

### Current Implementation (Screenshot)

Not applicable.

**Comment by nichwall** [comment]
I think items which begin with a dot should still be scannable by ABS.

Is this the same as https://github.com/advplyr/audiobookshelf/issues/3230? Not sure if your books didn't show up in the log at all or if you were getting the same error.

**Comment by ZLoth** [comment]
Looks to be the same. It was something that I had noticed, but when I remembered, the logs no longer existed. :(

**Comment by ZLoth** [comment]
@advplyr , @nichwall : Does this mean the online documentation won't be updated? That was the jist of this request (it's easy to do) rather than dealing with an extreme corner case that has a easy workaround.
