### ISSUE TITLE
[Bug]: incomplete search results

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf#3277]
### What happened?

I uploaded the audio book "Totholz (WALLNER & KREUTHNER.11)" a few days ago. Now I wanted to check whether various tags are correct. But when I search for "Totholz" I get the following result:
![image](https://github.com/user-attachments/assets/e118d18b-4094-4ac0-a916-44ca4cf32d3e)

### What did you expect to happen?

I would expect the first hits to be audio books that have the search term in the title. If there are no hits, you can show similar titles.
Today I have no chance to find this audiobook. If the title starts with the search term I can scroll to all 3500 audiobooks but when there is a word before "Totholz" like "im"or "Das" I never will find the audiobook.

### Steps to reproduce the issue

1. add audiobook "Totholz"
2. search for "Totholz"

### Audiobookshelf version

2.12.1

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

**Comment by mikiher** [comment]
First of all, 2.12.1 was a buggy version of Audiobookshelf. 
Please update to 2.12.3, and rescan the book. Does the problem persist after that?

**Comment by Gru0810** [comment]
with new Versio 2.12.3 it worksfine!
