### ISSUE TITLE
[Enhancement]: Ability to change and merge Audiobookshelf servers

### ISSUE THREAD

**Issue by charleshan** [advplyr/audiobookshelf#3279]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Currently, when the ip of the server is changed, the progress sync breaks. "Media is linked to an Audiobookself server on a different address (...). Progress will be synced when connected to this server address." It would be great if we can change/merge the ip address.

### Why would this be helpful?

I want to continue using progress sync after the ip address is changed or when I migrate to a different computer.

### Future Implementation (Screenshot)

We just need a way to override the login ip address and update the db from the frontend so that it syncs correctly.

### Audiobookshelf Server Version

v2.12.3

**Comment by nichwall** [comment]
This is specific to the apps (related to https://github.com/advplyr/audiobookshelf-app/issues/209)

Have you configured your server to work on a static IP? You can also get a free domain name from several online providers (such as duck DNS)

**Comment by charleshan** [comment]
Thanks.

> Have you configured your server to work on a static IP?
Not yet. I was running it locally and just set a new server. But I think the problem still stands. There's no easy way to change/merge after the initial basic setup. Also, wouldn't adding a reverse proxy have the same problem?

What if we let users assign a unique id to ABS? We can use to identify ABS server from the client

**Comment by nichwall** [comment]
Allowing multiple connections to be recognized as the same server by the app for download is the same as https://github.com/advplyr/audiobookshelf-app/issues/209.

> Not yet. I was running it locally and just set a new server. But I think the problem still stands. There's no easy way to change/merge after the initial basic setup. Also, wouldn't adding a reverse proxy have the same problem?

Yeah, you'll want to have a static IP set up, even if you're only accessing the server on LAN. Otherwise you'll need to change what you enter to access your server every time the IP changes, both in the app and web browser (usually when you reboot your server or router). Yes, a reverse proxy will also require a static IP.

Setting up a consistent method of connection to the server is outside the scope of ABS and up to the user to configure the network.

**Comment by charleshan** [comment]
I have static IP over LAN and the ip for my main computer hasn't changed in the past year. Static IP from my internet provider is something I need to look into.

I think this goes beyond dual IP setup. It look like in order to get the progress sync to work, I need to delete all local books from the client and redownload them just because ABS is using the ip address as the identifier.

**Comment by nichwall** [comment]
> I have static IP over LAN and the ip for my main computer hasn't changed in the past year. Static IP from my internet provider is something I need to look into.

Static IPs from ISP usually cost more, but you can use DDNS to automatically update the IP for a domain name, using either a paid domain name or a free option like DynDNS or Duck DNS (some routers will also provide this option for free).
