### ISSUE TITLE
[Bug]: "Permission Denied" message when making folder on SD card (Android 10 and below)

### ISSUE THREAD

**Issue by AythamiEsp** [advplyr/audiobookshelf#3285]
### What happened?

Can't make folders or access my SD card on my Android 9 (Sony Walkman device NW-A100). 
When I go to Local Media and press "Override", I select a media type "Books" or "Podcasts", then finally press "New Folder".
I get a red box containing the message: "ERROR: Permission Denied"

### What did you expect to happen?

Override the permissions to be able to access the SD card contents and save my media onto it.

### Steps to reproduce the issue

1. Go to Local Media
2. Press Override
3. Select any media type: eg. Books
4. Press New Folder
5. See the error message appear

### Audiobookshelf version

v0.9.76-beta (android)

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Additional Notes

Synology NAS - Docker container

**Comment by advplyr** [comment]
This is in the wrong repo. Using shared folders on Android 10 and below isn't supported but I added the override in there just in case someone had a device that allowed it.
It is unlikely this will ever be supported
