### ISSUE TITLE
[Bug]: Subseries no longer able to collapse with new Collapse/Expand Series control in Web UI

### ISSUE THREAD

**Issue by a-schwartz1** [advplyr/audiobookshelf#3287]
### What happened?

Web UI changed Collapse Series checkbox to drop-down selector. This menu is not available inside the series view, so subseries can no longer be collapsed in the Web UI, option still exists in the Android App.

### What did you expect to happen?

Collapse/Expand Series selector inside Series View.

### Steps to reproduce the issue

1. Go to a series in Web UI
2. Collapse/Expand Series option is not available

### Audiobookshelf version

v2.12.3

### How are you running audiobookshelf?

Other (list in "Additional Notes" box)

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### Additional Notes

Installed via TrueNAS Scale App

**Comment by mikiher** [comment]
This is probably a bug I introdcued with #3117. I'll have a look.
