### ISSUE TITLE
[Bug]: some podcast episodes ignoring pub date

### ISSUE THREAD

**Issue by Bigmack3000** [advplyr/audiobookshelf#3290]
### What happened?

I'm uploading my saved podcasts from iTunes.  Everything has a date in iTunes, but abs is not reading dates for some when they're loaded into it.

### What did you expect to happen?

I would like to see the pub dates for all episodes so they are sorted properly.

### Steps to reproduce the issue

1. 

### Audiobookshelf version

Downloaded today can't find version number.

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by Bigmack3000** [comment]
[2024-08-15.txt](https://github.com/user-attachments/files/16630336/2024-08-15.txt)

uploaded logs here.

![Screen Shot 2024-08-15 at 5 06 26 PM](https://github.com/user-attachments/assets/7cfa8385-a540-4d5e-b059-058470eee357)
![Screen Shot 2024-08-15 at 5 07 34 PM](https://github.com/user-attachments/assets/5d07e226-09d2-40d8-b11e-aa345c6aec8a)

also, two screenshots showing the date in itunes, and no date in abs. 

Thanks!

**Comment by advplyr** [comment]
Can you share the ffprobe output for that episode? Here is how https://www.audiobookshelf.org/guides/ffprobe#inspecting-an-audio-file

**Comment by Bigmack3000** [comment]
i appear to be missing the "more info" option.  
![Screen Shot 2024-08-15 at 6 53 38 PM](https://github.com/user-attachments/assets/6d1230fd-d63f-4642-b278-ec80bb3c113f)

**Comment by advplyr** [comment]
The table is on the page, not in the modal

**Comment by Bigmack3000** [comment]
I'm just trying to go off the link you posted.  It shows a screenshot in the same place as mine.

**Comment by advplyr** [comment]
It shows a screenshot of the audio tracks table on the books page

**Comment by Bigmack3000** [comment]
Sorry, the only screen the looks like that is the one i posted.  is it because these are podcasts and not audiobooks?

**Comment by advplyr** [comment]
Yeah the podcasts page is slightly different. On the podcast page you scroll all the way to the bottom and the Library files there will have the more info option on audio files.

**Comment by Bigmack3000** [comment]
Got it!

{
  "programs": [],
  "streams": [
    {
      "index": 0,
      "codec_name": "mp3",
      "codec_long_name": "MP3 (MPEG audio layer 3)",
      "codec_type": "audio",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "sample_fmt": "fltp",
      "sample_rate": "44100",
      "channels": 2,
      "channel_layout": "stereo",
      "bits_per_sample": 0,
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/14112000",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 3801634326,
      "duration": "269.390187",
      "bit_rate": "128000",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      }
    },
    {
      "index": 1,
      "codec_name": "mjpeg",
      "codec_long_name": "Motion JPEG",
      "profile": "Baseline",
      "codec_type": "video",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "width": 256,
      "height": 256,
      "coded_width": 256,
      "coded_height": 256,
      "closed_captions": 0,
      "film_grain": 0,
      "has_b_frames": 0,
      "pix_fmt": "yuvj420p",
      "level": -99,
      "color_range": "pc",
      "color_space": "bt470bg",
      "chroma_location": "center",
      "refs": 1,
      "r_frame_rate": "90000/1",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "duration_ts": 24245117,
      "duration": "269.390189",
      "bits_per_raw_sample": "8",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 1,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "comment": "Other"
      }
    }
  ],
  "chapters": [],
  "format": {
    "filename": "/audiobooks/13 Minutes to the Moon/S2 Delay to Episode 7.mp3",
    "nb_streams": 2,
    "nb_programs": 0,
    "format_name": "mp3",
    "format_long_name": "MP2/3 (MPEG audio layer 2/3)",
    "start_time": "0.000000",
    "duration": "269.390189",
    "size": "4338749",
    "bit_rate": "128846",
    "probe_score": 51,
    "tags": {
      "title": "S2 Delay to Episode 7",
      "artist": "BBC World Service",
      "album": "13 Minutes to the Moon",
      "genre": "Podcast",
      "copyright": "(c) BBC 2020",
      "TDES": "Producer Andrew Luck-Baker explains why the season finale will be delayed.",
      "TIT3": "Producer Andrew Luck-Baker explains why the season finale will be delayed",
      "TGID": "urn:bbc:podcast:p0894h2w",
      "iTunPGAP": "0",
      "date": "2020-20-20"
    }
  }
}

**Comment by advplyr** [comment]
You should be seeing a warning in your logs when it gets scanned in saying `Mapping pubDate with tag ${tagToUse} has invalid date "${value}"`

Because the date you are showing there is `2020-20-20` which is an invalid date.

**Comment by Bigmack3000** [comment]
interesting.  any particular reason that's happening, when the file has the correct date in itunes?

**Comment by advplyr** [comment]
I'm not sure where itunes is getting that date unless they are falling back to the date you got it or it is linked to a podcast on itunes.

If the podcast has an RSS feed you can edit the podcast in Abs and add it. Then use the match feature to match episodes pulling in their data. Or the quick match all feature.

**Comment by Bigmack3000** [comment]
ok great thanks!
