### ISSUE TITLE
[Bug]: Full Series matched as single book vs individual books

### ISSUE THREAD

**Issue by joshmans** [advplyr/audiobookshelf#3292]
### What happened?

I have the full Boxcar Children Collection (all volumes - books 1-157) - no matter how I do it, they get recognized as a single book in the library.  I've tried:
- Placing each file in just the author directory
- Placing each book in its own directory within the author directory
- Placing each book in its own directory within a Boxcar Children directory that sits in the author directory

### What did you expect to happen?

I expect each book to be matched to its own individual book rather than matching the whole thing as a single book.

### Steps to reproduce the issue

1.  Place book files in the file system and scan the library

### Audiobookshelf version

2.12.3

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Edge

### Additional Notes

I run ABS in docker on unraid

**Comment by nichwall** [comment]
Every library item needs to be in its own folder, without media files in a parent directory. For example, if you have something like the following, you can delete the "Boxcar Children" book from the ABS database without deleting from the file system (make sure the checkbox is not selected), and then scan the library. Deleting the books from within ABS will make sure you're staying at a fresh state since it sounds like the books were not detected correctly at the beginning.

If you can change your server log level to Debug that will also help provide logs.

```
/audiobooks/
│
└───Gertrude_Chandler_Warner/
    │
    └───Boxcar_Children/
        │
        ├───The_Boxcar_Children/
        │   ├── part1.mp3
        │   └── part2.mp3
        │
        ├───Surprise_Island/
        │   └── surprise_island.m4b
        │
        └───The_Yellow_House_Mystery/
            └── book.m4b
```

**Comment by advplyr** [comment]
If the books are already scanned in under a single item you should first *soft* remove the book from Abs. Then follow the supported directory structure.
If on a fresh scan it still groups them as the same book then there are only 2 ways that happens. Outlined here https://www.audiobookshelf.org/faq/server#why-are-multiple-books-showing-as-the-same-book

I'll close this until we establish it is a bug. We can continue the discussion if you are still having trouble

**Comment by joshmans** [comment]
> Every library item needs to be in its own folder, without media files in a parent directory. For example, if you have something like the following, you can delete the "Boxcar Children" book from the ABS database without deleting from the file system (make sure the checkbox is not selected), and then scan the library. Deleting the books from within ABS will make sure you're staying at a fresh state since it sounds like the books were not detected correctly at the beginning.
> 
> If you can change your server log level to Debug that will also help provide logs.
> 
> ```
> /audiobooks/
> │
> └───Gertrude_Chandler_Warner/
>     │
>     └───Boxcar_Children/
>         │
>         ├───The_Boxcar_Children/
>         │   ├── part1.mp3
>         │   └── part2.mp3
>         │
>         ├───Surprise_Island/
>         │   └── surprise_island.m4b
>         │
>         └───The_Yellow_House_Mystery/
>             └── book.m4b
> ```

This was the solution... though I thought I had it with this structure already once, but perhaps not.  My apologies for reporting this as a bug!
