### ISSUE TITLE
[Bug]: Playlists disappear from left navigation bar if no playlists exist

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3317]
### What happened?

One thing that I noticed is that if no playlists exist for a library, then the playlist button does not exist on the left navigation bar. 

### What did you expect to happen?

Like collections, playlists should always appear in the left navigation bar even if there are no playlists created

### Steps to reproduce the issue

This is best replicated if you have at least two libraries created without any playlists.

1. From Library A, add a single title to a Playlist. The Playlists button then appears.
2. Click on Playlist to confirm that playlist appears.
3. While on Playlist, switch to a different library without any playlists.

WHAT SHOULD HAPPEN: The Playlist button should always be present.
WHAT REALLY HAPPENS: The Playlist button disappears if there is no playlists present. 

Recording of issue:
https://github.com/user-attachments/assets/b521651d-11da-40ae-a477-f064a34ffed9

### Audiobookshelf version

2.12.3

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Logs

```shell
No logs.
```

### Additional Notes

This may be a regression defect.

**Comment by nichwall** [comment]
This is expected behavior. There is a feature request to hide other unused options (like Collections) https://github.com/advplyr/audiobookshelf/issues/887

**Comment by ZLoth** [comment]
Oh, okay. I was just kinda surprised. And I see the feature request was initially made in August, 2022.
