### ISSUE TITLE
[Enhancement]: In Playlists/Collection, Green "Play" button should be renamed to "Play Queue" or similar wording

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3320]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Rename the "Play" button for Playlists and Collections to be "Play Queue" or similar wording.

### Why would this be helpful?

This is a UX enhancement to help clarify the functionality. 

### Future Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/d3764401-890d-4104-8d18-31b3b279cd67)

### Audiobookshelf Server Version

2.12.3

### Current Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/18091091-fbd6-4595-b1de-167691035515)

**Comment by advplyr** [comment]
I don't like that wording "Play Queue". I would find that more confusing but that might just be me.

**Comment by ZLoth** [comment]
Per [Dictionary.com](https://www.dictionary.com/browse/queue), a queue is a "a file or line, especially of people waiting their turn" or a "Computers. a FIFO-organized sequence of items, as data, messages, jobs, or the like, waiting for action.". I couldn't think of a better word. Also, in the app, there are individual play buttons by each title to play as well as the "Play" button at the top which can lead to confusion.

**Comment by advplyr** [comment]
I put a poll in the Discord and "Play All" was chosen
![image](https://github.com/user-attachments/assets/356f4ab4-a700-4895-9795-b7c1ee7d45cb)

**Comment by ZLoth** [comment]
Works for me. I did say "similar wording".

**Comment by ZLoth** [comment]
Thank you.
