### ISSUE TITLE
[Bug]: Quick embed metadata failing

### ISSUE THREAD

**Issue by michelangelo4** [advplyr/audiobookshelf#3323]
### What happened?

When trying to quick embed metadata into a (test) file I get the error
 ENOTDIR, ERROR: [AudioMetadataManager] Target directory is not writable
and the metadata is not embedded.

### What did you expect to happen?

Metadata to be embedded and if this fails for a message to pop up. Here just nothing happened and at first I thought it finished properly.

### Steps to reproduce the issue

1.  Use a version higher than 2.11.0 and try to embed metadata on a file that is on a shared folder on a qnap. Run audiobookshelf via command line not container station (that's my case).

### Audiobookshelf version

v2.12.3

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
[2024-08-22 00:11:33.704] INFO: [fileUtils] Directory is not writable "/data/DDD.mp3" [Error: ENOTDIR: not a directory, open '/data/DDD.mp3/accessTest'] {
audiobookshelf-audiobookshelf-1  |   errno: -20,
audiobookshelf-audiobookshelf-1  |   code: 'ENOTDIR',
audiobookshelf-audiobookshelf-1  |   syscall: 'open',
audiobookshelf-audiobookshelf-1  |   path: '/data/DDD.mp3/accessTest'
audiobookshelf-audiobookshelf-1  | }
audiobookshelf-audiobookshelf-1  | [2024-08-22 00:11:33.707] ERROR: [AudioMetadataManager] Target directory is not writable: /data/DDD.mp3 (AudioMetadataManager.js:106)
```

### Additional Notes

Sorry in advance if something is not perfect, this is my first bug report.

This is on a Qnap QTS TS-877. I mounted a shared folder /share.../.../ to /data. I checked permissions, but they are all 777 or 666 and from within the containers shell using "docker exec -it <mycontainer> sh" I can access and move/copy everything. 

Important: This bug only occurs if the version is higher than 2.11.0. If I downgrade to 2.11.0 everything just works fine.

**Comment by advplyr** [comment]
Is the file stored in the root folder and not inside of a subdirectory?

**Comment by michelangelo4** [comment]
It is inside of a subdirectory, I shortened the upper path for privacy reasons. Real path would be something like
/data/michelangelo/audiobooks/DDD/DDD224.mp3
