### ISSUE TITLE
[Bug]: Docker installation will not work with an existing directory as volume

### ISSUE THREAD

**Issue by cavebutter** [advplyr/audiobookshelf#3324]
### What happened?

Attempting to install with docker compose.  Used an existing directory (/mnt/media/AudioBooks) as volume for /audiobooks.  Error: `Error response from daemon: error while creating mount source path '/mnt/media': mkdir /mnt/media: file exists`

### What did you expect to happen?

Expected result is a complete installation and launch of service.

### Steps to reproduce the issue

1. Create docker-compose.yml with the template supplied on website [here](https://www.audiobookshelf.org/docs#docker-compose-install).
2. For the audiobooks entry in the volumes section, enter an existing directory on the left side of the colon.
3. complete the template using valid, new values for the remainder of the volumes.
4. Save and exit the docker-compose.yml file
5. `docker-compose up -d`

### Audiobookshelf version

"latest" as of 8/22/24

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by nichwall** [comment]
Is this a docker error or an ABS error? Pre-existing directories should work.

Are you running the docker container as another user, and if so does that user have permissions to access that directory?

**Comment by nx-sm** [comment]
Happened to me as well when I unplugged/plugged again external SSD after creating a volume there. Rebooting docker desktop fixed this.
