### ISSUE TITLE
Handle folder renames without leaving behind invalid books

### ISSUE THREAD

**Issue by wtanksleyjr** [advplyr/audiobookshelf#334]
When a book-containing folder is renamed, the system seems to almost always mark the old book invalid and create a new book for the renamed folder. It would be nice if some provision could be made for detecting that the apparently new book is actually an existing entry, and somewhat more gracefully rescan it to see what metadata changes are implied.

Some approaches:

* track inodes (for systems using that of course).
* drop a UUID filename into the book's folder.
* Keep a table of recent folder changes for admin/root to review, allowing them to sort, search, mark duplicates, and so on.

**Comment by wtanksleyjr** [comment]
(This is an Enhancement, I think. But this is really bad for me, since I am trying to modify an existing HUGE directory folder, and I keep having to nuke-and-restart my audiobookshelf because I accumulate so many dead books that are near duplicates of existing books.)

**Comment by advplyr** [comment]
This should already happen, all the folders and files have their inode values stored.
There can be some issues with inodes. If when renaming the folder it gets put on another drive. From my tests this only happens when adding/removing files on Unraid, but could be possible.
I think there are also issues when using remote file systems. Are you using Unraid? What is your setup?

**Comment by wtanksleyjr** [comment]
That's good news, I must be doing something wrong in my script then. I'll
debug this from my end, feel free to close this and I'll just reopen or
raise a new more specific issue if I find something absolutely smoking-gun.

(I'm working from an ordinary internal drive, no special FS layers or
anything. In fact I depend on hardlinks elsewhere so I know they work.)

-Wm

**Comment by advplyr** [comment]
Sounds good
