### ISSUE TITLE
[Enhancement]: Add BookBeat as metadata provider

### ISSUE THREAD

**Issue by SwedishGojira** [advplyr/audiobookshelf#3341]
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

Add BookBeat as metadata provider. https://www.bookbeat.com

### Why would this be helpful?

BookBeat is a great source of metadata for books not in english, especially for the european market. I use it all the time for swedish books for example.

### Future Implementation (Screenshot)

-

### Audiobookshelf Server Version

-

### Current Implementation (Screenshot)

Image not needed. I think you understand the request anyway.

**Comment by nichwall** [comment]
I can't find documentation for a public API they are exposing, do you have any docs for it?

Custom metadata providers can be added for online providers that aren't officially supported by ABS. https://www.audiobookshelf.org/guides/custom-metadata-providers

**Comment by Vito0912** [comment]
I have created a provider that supports BookBeat. It's not tested that well yet as I am just lying out a foundation to add more providers to it: <https://github.com/Vito0912/abs-meta>
