### ISSUE TITLE
[Enhancement]: Run server as a different user

### ISSUE THREAD

**Issue by wantle** [advplyr/audiobookshelf#3349]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Windows Server:
Is it possible to run the server as a different user? 

### Why would this be helpful?

my current user cannot access network shares and they are not available as library folders in library folder selection

### Future Implementation (Screenshot)

Option to select server credentials

### Audiobookshelf Server Version

v2.12.3

**Comment by nichwall** [comment]
This is specific to the Windows version. https://github.com/mikiher/audiobookshelf-windows

**Comment by advplyr** [comment]
I can't transfer issues to that repo so you'll have to open your issue there. However, I'm pretty sure this is a general Windows Server question and not something that would be implemented in Abs. I suggest opening a discussion instead of an issue
