### ISSUE TITLE
[Enhancement]: Confirmation dialog before navigating away from bulk edit with unsaved changes

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf#3369]
### Type of Enhancement

Web Frontend

### Describe the Feature/Enhancement

A confirmation dialog about unsaved changes on the bulk edit screen would be helpful. Several users have mentioned problems with the bulk edit page in the past, but they have been due to not having pressed the "Save" button in the lower right of the screen.

This may be useful with other edit modals as well.

### Why would this be helpful?

This just tripped me up while searching for edge cases on 2.13.2 related to the model transition, so I just kept trying to debug exactly which fields were not being applied correctly. Then I realized I wasn't pressing save.

### Future Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/b505bf3c-27a4-46b2-9491-69ef5dfa18b6)

### Audiobookshelf Server Version

v2.13.2

### Current Implementation (Screenshot)

No user confirmation

**Comment by advplyr** [comment]
This could be further improved by showing our Confirm modal when navigating internally instead of the browser default confirm prompt.
I believe the browser default confirm prompt would still have to be shown for navigation not made in the website. e.g. the browser back button
