### ISSUE TITLE
[Enhancement]: Number of books in library should be comma-delimited (depending on region settings) if number exceeds 1,000

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3370]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

If number of books exceeds one thousand, then the number should be comma delimited (depends on region settings). This follows previous feature requests for the same thing in stats. 

### Why would this be helpful?

Readability. 

### Future Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/71c24ee8-c458-41e4-99a9-b16783113d93)

### Audiobookshelf Server Version

2.13.2

### Current Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/bc984901-8a5b-404c-a046-8b555d57dc90)

**Comment by advorsky73** [comment]
it should be according to region. EU would prefer 1.300 instead of 1,300.
Thanks!

**Comment by ZLoth** [comment]
> it should be according to region. EU would prefer 1.300 instead of 1,300. Thanks!

The folks who maintain the ABS code has been extremely good on applying regional settings.
