### ISSUE TITLE
[Bug]: ABS does not reconnect to server after force closing app (iOS & Android)

### ISSUE THREAD

**Issue by Boondoc0** [advplyr/audiobookshelf#3380]
### What happened?

When opening either ABS apps from a force close of the app or not already running in the background app does not retain login status and will force a login. After login there will be no cover art displayed.

iOS app version 09.76(33)
Android app 0.9.76-beta

### What did you expect to happen?

I expected to be able to login with cached creds without having to login manually. I expected to see cover art.

### Steps to reproduce the issue

1. Upgrade to abs v2.13.3
2. upgrade apps to latest versions available in their respective app stores.
3. attempt to use app

### Audiobookshelf version

v2.13.3

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Other (list in "Additional Notes" box)

### Additional Notes

OS: Debian 12.6 hosted on as Proxmox 8.2.2 vm.
Traefik 3.0.1 reverse proxy.

Downgrading to ABS v2.13.0 has resolved the issues.

**Comment by nichwall** [comment]
I am not able to reproduce this using server version 2.13.3 and Android app 0.9.76.
Running using Docker on Synology

Have you tried accessing the server directly (not going through Traefik)? Do you see anything in the server logs about not being authenticated?

**Comment by Boondoc0** [comment]
So i just recreated the ABS stack using the same compose. The only change made was unpinning the image tag from 2.13.0 back to latest and redeployed and i'm not seeing the same issues i saw before.

I have not made any changes to traefik or any changes to my abs compose. I'm not sure what wasn't meshing together before but it seems to have worked itself out.

**Comment by xcy7e** [comment]
So this can be closed, then, right? Thx
