### ISSUE TITLE
[Bug]: Socket Disconnected on Scan

### ISSUE THREAD

**Issue by GhostTownCowboy** [advplyr/audiobookshelf#3406]
### What happened?

I've added a library that links to a directory that is all comics (CBZ/CBR). When I scan the comic folder (issue not present in EBook/Audiobook directory) it starts, finds about 4 then gives the "SOCKET DISCONNECTED" popup. The scan seems to continue with notifications about the socket connecting and disconnecting. No other items are found. 

### What did you expect to happen?

The scan should add comics similar to other books unless I'm misunderstanding something. 

### Steps to reproduce the issue

1. Unsure without a Synology Nas and several hundred comic files.

### Audiobookshelf version

2.13.4

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
Crash Log: 
{"timestamp":"2024-09-11 09:44:43.583","source":"Server.js:185","message":"[Server] Unhandled rejection: [object Object], promise: Promise {\n  <rejected> {\n    message: 'Truncated RAR file data',\n    name: 'Error',\n    stack: 'Error: Truncated RAR file data\\n' +\n      '    at ArchiveReader.entries (/server/libs/libarchive/wasm-module.js:110:17)\\n' +\n      '    at entries.next (<anonymous>)\\n' +\n      '    at MessagePort.<anonymous> (/server/libs/libarchive/libarchiveWorker.js:43:20)\\n' +\n      '    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\\n' +\n      '    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)'\n  }\n}","levelName":"FATAL","level":5}
{"timestamp":"2024-09-11 09:45:38.316","source":"Server.js:185","message":"[Server] Unhandled rejection: [object Object], promise: Promise {\n  <rejected> {\n    message: 'Truncated RAR file data',\n    name: 'Error',\n    stack: 'Error: Truncated RAR file data\\n' +\n      '    at ArchiveReader.entries (/server/libs/libarchive/wasm-module.js:110:17)\\n' +\n      '    at entries.next (<anonymous>)\\n' +\n      '    at MessagePort.<anonymous> (/server/libs/libarchive/libarchiveWorker.js:43:20)\\n' +\n      '    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\\n' +\n      '    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)'\n  }\n}","levelName":"FATAL","level":5}
{"timestamp":"2024-09-11 11:38:32.669","source":"Server.js:185","message":"[Server] Unhandled rejection: [object Object], promise: Promise {\n  <rejected> {\n    message: 'Truncated RAR file data',\n    name: 'Error',\n    stack: 'Error: Truncated RAR file data\\n' +\n      '    at ArchiveReader.entries (/server/libs/libarchive/wasm-module.js:110:17)\\n' +\n      '    at entries.next (<anonymous>)\\n' +\n      '    at MessagePort.<anonymous> (/server/libs/libarchive/libarchiveWorker.js:43:20)\\n' +\n      '    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\\n' +\n      '    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)'\n  }\n}","levelName":"FATAL","level":5}
{"timestamp":"2024-09-11 16:31:22.819","source":"Server.js:185","message":"[Server] Unhandled rejection: [object Object], promise: Promise {\n  <rejected> {\n    message: 'Truncated RAR file data',\n    name: 'Error',\n    stack: 'Error: Truncated RAR file data\\n' +\n      '    at ArchiveReader.entries (/server/libs/libarchive/wasm-module.js:110:17)\\n' +\n      '    at entries.next (<anonymous>)\\n' +\n      '    at MessagePort.<anonymous> (/server/libs/libarchive/libarchiveWorker.js:43:20)\\n' +\n      '    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\\n' +\n      '    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)'\n  }\n}","levelName":"FATAL","level":5}
{"timestamp":"2024-09-11 16:41:09.506","source":"Server.js:185","message":"[Server] Unhandled rejection: [object Object], promise: Promise {\n  <rejected> {\n    message: 'Truncated RAR file data',\n    name: 'Error',\n    stack: 'Error: Truncated RAR file data\\n' +\n      '    at ArchiveReader.entries (/server/libs/libarchive/wasm-module.js:110:17)\\n' +\n      '    at entries.next (<anonymous>)\\n' +\n      '    at MessagePort.<anonymous> (/server/libs/libarchive/libarchiveWorker.js:43:20)\\n' +\n      '    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\\n' +\n      '    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)'\n  }\n}","levelName":"FATAL","level":5}
```

### Additional Notes

Running on Synology. 

[2024-09-11.txt](https://github.com/user-attachments/files/16970945/2024-09-11.txt)
[crash_logs.txt](https://github.com/user-attachments/files/16970946/crash_logs.txt)

**Comment by nichwall** [comment]
Related to https://github.com/advplyr/audiobookshelf/issues/3399, https://github.com/advplyr/audiobookshelf/issues/2526

Looks like that file is malformed based on the log, or at least the data is truncated.

If you're able to share the file for testing that would be helpful for debugging.

**Comment by GhostTownCowboy** [comment]
@nichwall Which file is it saying is bad? Am I just missing that? Judging by the Comics that are showing this seems to be the halting point.
![image](https://github.com/user-attachments/assets/f5c65733-9cf4-4abb-9395-0412330b34bf)

I am unable to upload the file as it's too large. Could the file size be the issue?

**Comment by GhostTownCowboy** [comment]
Also as a note, the files it did find are all CBR files. Do I need to convert my CBZs to CBRs?

**Comment by mikiher** [comment]
To diagnose which file caused the issue, can you please upload the scan log as well?

You should find it at `<your metadata directory>/logs/scans`.  Just upload the latest one.

**Comment by GhostTownCowboy** [comment]
Sorry about that, I didn't see those before. 

When I opened that log folder there were 3 files in there (Attached) I attempted to scan the comics again. They server crashed, restarted/socket reconnected and no additional log was written. Looking at the attached logs they all seem to be of E/Audiobooks however there is a high chance I'm missing something. 

[2024-09-11_e6e39b4f-b8bc-449b-8ce0-7df1eefbb4ae.txt](https://github.com/user-attachments/files/16977755/2024-09-11_e6e39b4f-b8bc-449b-8ce0-7df1eefbb4ae.txt)
[2024-09-10_f1f60f28-13c7-42ca-8efc-ae87ad33a985.txt](https://github.com/user-attachments/files/16977758/2024-09-10_f1f60f28-13c7-42ca-8efc-ae87ad33a985.txt)
[2024-09-10_8b7ff359-3689-4be5-b3ce-1b43eaf369f8.txt](https://github.com/user-attachments/files/16977759/2024-09-10_8b7ff359-3689-4be5-b3ce-1b43eaf369f8.txt)

**Comment by mikiher** [comment]
OK, sorry, my bad - the scan log is only saved if the scan is completed, but since the server crashes during the scan, there wouldn't be any scan log for it.

Instead, can you please:
- Set the server log level to DEBUG? 
  This will cause scan log lines to also appear in the main log file.
  (To set the server log level, go to Settings => Logs, and select `Debug` in the `Server Log Level` dropdown box).
- Run the scan again and re-upload the most recent main log file (should be logs/daily/2024-09-12.txt or similar)

**Comment by Nda70** [comment]
[2024-09-12.txt](https://github.com/user-attachments/files/16981919/2024-09-12.txt)
[crash_logs (1).txt](https://github.com/user-attachments/files/16981920/crash_logs.1.txt)


Hi, same problem here, i've already  sxwtch all my cbr to cbz,. Me too on synology nas latest docker version. I've remove some of the blocking CBZ, they are all big files around 400mb

**Comment by mikiher** [comment]
You can see in the log that it started parsing `/medias/Downloaded/test/Sur les rives du Lethe/Black Science - T04 (46)/Black Science - T04 - Sur les rives du Lethe.cbz` but did not finish, so this is probably the file it is crashing on.

If you can send this file to me privately on discord, I can try to see what's going on with it (I think you can send large files in discord)

**Comment by GhostTownCowboy** [comment]
> OK, sorry, my bad - the scan log is only saved if the scan is completed, but since the server crashes during the scan, there wouldn't be any scan log for it.
> 
> Instead, can you please:
> 
> * Set the server log level to DEBUG?
>   This will cause scan log lines to also appear in the main log file.
>   (To set the server log level, go to Settings => Logs, and select `Debug` in the `Server Log Level` dropdown box).
> * Run the scan again and re-upload the most recent main log file (should be logs/daily/2024-09-12.txt or similar)

I'll pull these when I get off work today.

**Comment by Nda70** [comment]
Hi, not good at discord but will try, my son will help :)

**Comment by Nda70** [comment]
How do we do? you give me your nickname or stuff like that and i ask to be friend?

**Comment by mikiher** [comment]
Yes, I think that will work. My nickname is mikiher there as well.

**Comment by Nda70** [comment]
Done

**Comment by GhostTownCowboy** [comment]
> OK, sorry, my bad - the scan log is only saved if the scan is completed, but since the server crashes during the scan, there wouldn't be any scan log for it.
> 
> Instead, can you please:
> 
> * Set the server log level to DEBUG?
>   This will cause scan log lines to also appear in the main log file.
>   (To set the server log level, go to Settings => Logs, and select `Debug` in the `Server Log Level` dropdown box).
> * Run the scan again and re-upload the most recent main log file (should be logs/daily/2024-09-12.txt or similar)

Okay the daily is below.

[2024-09-12.txt](https://github.com/user-attachments/files/16984180/2024-09-12.txt)

![Uploading image.png…]()

**Comment by GhostTownCowboy** [comment]
I think I sorted out how to tell what's breaking the scan from the logs. I've deleted a few folders and it's running now. It's not ideal but it's functioning.

**Comment by mikiher** [comment]
I think it would be good to keep the bug open until I figure out what's
causing parsing to fail on some of these files (and to also prevent the
parsing failure from failing the whole scan).

**Comment by GhostTownCowboy** [comment]
Sounds good. I'd like to upload one of the files that's causing the failure but they are too big for Git Comments. I'll drop it someplace reachable after work.

**Comment by GhostTownCowboy** [comment]
This is one of the folders that was causing the issue. On the server they are not zipped folders. 

https://drive.google.com/file/d/1N5Cn0nEV7bBA21zETHq16nL3RJ0yVPdg/view?usp=drive_link

**Comment by Nda70** [comment]
Hi, I put all my big cbz >400mo in one folder, the scan with the rest went well. But when i scanned the big file folder all went well too even with the file i upload for you. the main differences is 318  cbz of under 400Mo but only 10 >400mo
I'm lost...

**Comment by Nda70** [comment]
I will try again with all in one folder too see if it crash.

**Comment by mikiher** [comment]
I haven't had the time to check the files yet. Stay tuned...
