### ISSUE TITLE
[Bug]: Not saving square cover setting

### ISSUE THREAD

**Issue by igorkaldowski** [advplyr/audiobookshelf#341]
### Describe the issue

Whenever the server restarts or is updated it goes back to square covers. It looks like it doesn't save that setting between restarts.

### Steps to reproduce the issue

1. Turn off square covers
2. Restart Server

### Audiobookshelf version

1.6.62

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
There was an issue with the db in that version that impacted all server settings.
I just released `v1.6.63` that fixes this.

**Comment by igorkaldowski** [comment]
I am still having this issue on 1.6.63

**Comment by advplyr** [comment]
Is the server log showing db settings updated 0?

If you can run this project locally, are you also experiencing it on local? Looking for more data.

**Comment by igorkaldowski** [comment]
So the log is saying "[DB] Updated settings: 2" whenever I change the setting. I am also having the same issue when running it locally.

**Comment by advplyr** [comment]
It should definitely not have a value of 2. Can you check the json file in `/config/settings/data/`?
There should only be 1 json object in there.
![image](https://user-images.githubusercontent.com/67830747/152062720-ee87e7df-dfba-4a68-ae73-e324ec96a323.png)

**Comment by igorkaldowski** [comment]
So I have 2 files there. Both have 1 object inside and coverAspectRatio set to 0.

**Comment by advplyr** [comment]
That is really strange. You can delete one of those files.

**Comment by igorkaldowski** [comment]
So I deleted the first one but its still doing it.

**Comment by advplyr** [comment]
I think I'm confused about what it is doing exactly. When the coverAspectRatio is 0 it should be showing regular book aspect ratio book covers (1.6:1). If the coverAspectRatio is 1 it will be showing square book covers.

Are you not ever able to see a chance in the cover aspect ratio?

**Comment by igorkaldowski** [comment]
So it is set to 0 in that file but after a server restart it shows square covers.

**Comment by advplyr** [comment]
Ah yeah I see the issue now, it is saving fine but not loading properly. Not sure how you got a duplicate file though.

**Comment by igorkaldowski** [comment]
So I just deleted both of the files and let the server recreate it. "coverAspectRatio" doesn't change when I change the setting. It only does when I also change something else. It seems to be the only setting that has a problem.

**Comment by advplyr** [comment]
It was the initialization. I'm going to patch the current version.

**Comment by advplyr** [comment]
Just pushed the update, let me know how it goes

**Comment by igorkaldowski** [comment]
That's all working now.
