### ISSUE TITLE
[Enhancement]: Save streams between sessions

### ISSUE THREAD

**Issue by MidnightSnowleopard** [advplyr/audiobookshelf#342]
### Describe the feature/enhancement

As it stands currently every time a stream is closed for any reason, Audiobookshelf completely deletes the entire transcode stream.  This seems wasteful as all of the information has been converted to the HLS format already and, to the best of my understanding, still be ready and valid to resume playing.

I would like to see the ability to save up to a certain number of books/files/total size of stream for re-play later so transcoding doesn't need to happen as often and the churn of files being created and deleted is minimized.

Low priority request as in general transcoding isn't massively taxing on a system but would appreciate it due to some slowness regarding clearing streams that is entirely due to my own setup.

**Comment by MidnightSnowleopard** [comment]
Direct stream would be amazing for a lot of media but that introduces a lot more different avenues for issues with compatibility.

I'll stick with the much smaller and hopefully easier to implement idea of just keeping some streams around for now.

**Comment by advplyr** [comment]
Direct play is not supported on the web app and android app. For me my entire collection can be direct played so transcoding shouldn't be so common that this is required anymore.
