### ISSUE TITLE
[Enhancement]: Universe support

### ISSUE THREAD

**Issue by freitagdavid** [advplyr/audiobookshelf#344]
### Describe the feature/enhancement

First I have to start with thank you, thank you, thank you. I've been wanting something like this forever and was almost to the point of making it myself.

I took a look through the open requests and didn't see anything so apologies if this is a duplicate. I was wondering what would be the possibility of implementing support for universes/worlds. For example Star Wars since it will be the most well known, I would like to be able to make my directory structure something like this Audiobooks/{universe}/{author}/{series}/{book}, I have a couple collections that could really benefit from being able to actually mark universes/worlds so that I can see them as one.

**Comment by advplyr** [comment]
Welcome! This isn't a duplicate, but various folder structures have been mentioned.

In #320 the use-case was brought up for series with multiple authors, so to have the series directory before the author directories.

Here are some ideas:
1. We could have an option to disable using the directory structure to fill in book details.
    Having your audiobooks inside in a directory named after the book title would still be required, but that directory could be as deeply nested as you wanted, the structure wouldn't matter. The downside is the series and author (and universe in your case) would need to be in the audio file metadata or an OPF file or somewhere else if it was to be pulled by the scanner.

2. To handle the use-case you brought up, if the directories are nested 4 deep we could treat the first directory as a collection. So the scanner automatically creates a collection with the name of that first directory. `Audiobooks/{collection}/{author}/{series}/{book}/`. Maybe this is something you opt-in to with a scanner setting.

I've also thought of making a system where you specify your directory structure with some regex pattern or something, but this would be complicated and still not solve for cases where some series contain author folders and some author folders contain series.

**Comment by freitagdavid** [comment]
One potential idea that I've thought of when planning out my own audiobook application is to give users an advanced option where they can essentially write their own parser. So have a file somewhere along the lines of customParser.js or along those lines and allow them to select that option somewhere. Then if someone wanted to they could use regex, or they could do even more fancy stuff.

I do like the idea of just having the collections that would also achieve the same goal.

**Comment by advplyr** [comment]
I think the best solution for this is collections still. Detecting collections in the folder structure would be a separate issue so in an effort to clean up the open issues I will close this one. Feel free to open a feature request for collections folder structure.
