### ISSUE TITLE
[Bug]: Library Scan not completing - Socket Closed

### ISSUE THREAD

**Issue by sedgbeer** [advplyr/audiobookshelf#3452]
### What happened?

When running a manual or cron scan I am getting a socket closed from the Web App and the log files are presenting an uncaught exception causing the scan to stop.

### What did you expect to happen?

expected the library scan to complete

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.13.4

### How are you running audiobookshelf?

Debian/PPA

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Logs

```shell
2024-09-24 22:55:28.132

FATAL

[Server] Uncaught exception origin: uncaughtException, error: Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals. Please open an issue with this stack trace at https://github.com/nodejs/node/issues at assert (node:internal/assert:14:11) at internalConnectMultiple (node:net:1118:3) at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18) at GetAddrInfoReqWrap.emitLookup [as callback] (node:net:1510:7) at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:130:8) { code: 'ERR_INTERNAL_ASSERTION' }
```

### Additional Notes

attempted to recreate the library. now only have 2 books showing.

**Comment by sedgbeer** [comment]
Update - issue looks to be related to the removal and readdition of books.
Lead up to the issues, I had identified and audio issue with a title I was listening to.  faulty content was removed and the books removed from the library.
New content was located and placed back in the dir structure and a scan initiated. 
The scan was never completed and the refreshed books also did not get readded.

**Comment by mikiher** [comment]
It would be good to get more details and clear reproduction instructions:
- Can you post the the Audiobookshelf log up to the crash? Please include all the log messages since server start.
- Can you reproduce the crash? If so, can you please:
  - Set Audiobookshelf Log Level to debug
  - Reproduce the crash
  - Post the log containing the debug messages up to the crash?

**Comment by mikiher** [comment]
@advplyr Since the reporter didn't respond, can you mark this `Unable to reproduce`?

**Comment by sedgbeer** [comment]
Issues is not reproducible
