### ISSUE TITLE
[Enhancement]: add documentation on multi-authors for a series

### ISSUE THREAD

**Issue by alteredtech** [advplyr/audiobookshelf#347]
### Describe the feature/enhancement

For book series like Halo that span multiple authors and mini series within the series as a whole. It would be nice to know how to structure something like that. Other possibility is tagging separate books into a series that you can listen to in order of release/chronological. This part might already be in it but I am new to this and still figuring the bells and whistles.

**Comment by advplyr** [comment]
There is some talk of handling that situation in #320 
We haven't landed on a solution yet to support this in the directory structure. We can keep that as the main thread for this issue. If you have some suggestions/ideas please share in the thread.
