### ISSUE TITLE
Enhancement: Mark Read Button on Home Page During Multi-Select

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf#35]
I love this application and how quickly it is coming together.  In order to migrate an existing library from alternatives, the ability to quickly get the read status up to date is needed.

This can be mostly accomplished by adding a "Mark Read" button to the home screen when items are being multi-selected.

**Comment by advplyr** [comment]
That makes sense, I just added this to `v1.1.10`, you can update now.

![image](https://user-images.githubusercontent.com/67830747/133622727-03644b0a-4f38-4f7d-8790-2f53547a6fea.png)

**Comment by Budlyte** [comment]
Noice!  You're pretty quick.  The flag at the bottom of the cover loads more reliably as well.
