### ISSUE TITLE
[Bug]: Trying to rename libraries - Reverts back to the original name after server restart

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf#350]
### Describe the issue

I am trying to rename a library, and every time I restart the server after I rename the library, the name of the library reverts back to the original name when the library was created. 

### Steps to reproduce the issue

1. Navigate to Settings -> Libraries
2. Rename any library present
3. Refresh the page, to confirm library is renamed (also shows renamed library on the app)
4. Restart server
5. Library is back to original name before the rename (i.e. Main -> Audiobooks -> server restart -> Main)

### Audiobookshelf version

v1.6.63

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This should be fixed now in `v1.6.64`. Let me know how it goes

**Comment by feerlessleadr** [comment]
Confirmed fixed. Thanks!
