### ISSUE TITLE
[Enhancement]: PWA Support

### ISSUE THREAD

**Issue by Zibbp** [advplyr/audiobookshelf#354]
### Describe the feature/enhancement

PWA support would allow Chromium users to install the website as an "app" to their local desktop. I personally would prefer having a dedicated PWA then a tab in my browser for listening on my desktop.

Here is an example of [https://open.spotify.com/](https://open.spotify.com/) allowing me to install the PWA app.
![image](https://user-images.githubusercontent.com/21207065/153061133-d6c2a707-4c66-4695-b76e-ef43f5abb0ce.png)

**Comment by freitagdavid** [comment]
Another possibility since the mobile apps are built with react native would be to also create a react native desktop version so there was a native app for the desktop as well. Though I imagine that would take a whole lot of work.

**Comment by advplyr** [comment]
Yeah this is a good call. I've setup a few PWAs and it is a pretty quick add. There are a few pages/components in the web app that won't function well on mobile, but for the most part it is good to go.



> Another possibility since the mobile apps are built with react native would be to also create a react native desktop version so there was a native app for the desktop as well. Though I imagine that would take a whole lot of work.

The mobile app is actually made with Capacitor. Similar to React native but using Vue. It is also a good idea to make a desktop version of the mobile app, but right now it doesn't have the ability to add/update audiobooks, accounts, etc., so maybe something for the future.

**Comment by freitagdavid** [comment]
Ah really wow that looked very similar to react native, I was wondering why you had vue on the web side and react native on the apps guess that explains it haha.

**Comment by Zibbp** [comment]
Working great on Windows using Chrome with the "insecure origins" flag. Thanks for the quick implementation!

![image](https://user-images.githubusercontent.com/21207065/153299840-e46671cc-9b73-4732-a7a6-4cdeb4b25eba.png)

**Comment by advplyr** [comment]
Nice! Thanks for following up.

**Comment by alextenev** [comment]
Hi, @advplyr !

I'm using 2.2.2 and am unable to install the PWA. Tried the flags on both Brave and Edge. Is it still enabled?

Cheers,
Alex

**Comment by advplyr** [comment]
Hey I recently noticed this was not working. Will need to investigate this

**Comment by advplyr** [comment]
This is fixed again
