### ISSUE TITLE
[Enhancement]: Ability to Clone Users

### ISSUE THREAD

**Issue by maedas** [advplyr/audiobookshelf#3548]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Ability to clone a user (with a new name). Duplicates the listen history and other user-specific data.

### Why would this be helpful?

Manually populating reading history can be quite tedious, including specifying progress on uncompleted books.

### Future Implementation (Screenshot)

Button in the user management interface that opens a new menu to choose which user to clone.

### Audiobookshelf Server Version

2.10.1

**Comment by nichwall** [comment]
Is there a reason you're cloning a user instead of just renaming the user?

**Comment by advplyr** [comment]
Why would you need to do this?
