### ISSUE TITLE
[Enhancement]: Discord Channel

### ISSUE THREAD

**Issue by freitagdavid** [advplyr/audiobookshelf#355]
### Describe the feature/enhancement

So not related directly to the app but I thought it might be a good idea to create a Discord or something else along those lines for everyone to collaborate and talk about the application. There are a couple open source apps I use that have small communities surrounding them and it seems to work really well for generating ideas and dealing with issues people have outside of creating github issues. It eventually becomes untenable to have all the support in Github issues.

Thoughts?

**Comment by advplyr** [comment]
I'm just starting to lose track of conversation threads across the projects, so I can see the value in this now. It was brought up a few times when the community was just a few active people.
Discord is really smooth and well-built from my usage of it, but I'm not sure I like the direction they have been going. Do you have any suggestions for open-source chat services? Or any other alternatives you have used?

**Comment by freitagdavid** [comment]
There is [rocket.chat](https://rocket.chat/) which is an open source alternative to slack though you need to host it, [Matrix ](https://matrix.org/)is a decentralized chat protocol that has some good clients,  [Mattermost ](https://mattermost.com/)is another slack alternative that could be a good option though once again self hosted. There is also the possibility of just setting up an irc channel, though that's gonna leave out a lot of less technical users. There are definitely more but these were just the first off the top of my head.

I 100% understand your hesitation to use Discord I was actually a bit hesitant to recommend it but it's the most universally available option.

**Comment by freitagdavid** [comment]
Also there are a bunch listed here.

https://github.com/awesome-selfhosted/awesome-selfhosted#communication---custom-communication-systems

**Comment by argash** [comment]
honestly the best reason to pick discord is everyone mostly already has it. I've considered all three options that @freitagdavid mentioned for my various friend groups, however it always came back to they already have discord so why use something else. Unless there's a very compelling argument not to use discord, the fact remains that on discord you will get a much higher level of participation.

**Comment by mrdeadlocked** [comment]
+1 for discord

**Comment by freitagdavid** [comment]
There is an argument that having a slightly higher bar to entry, which honestly just downloading an app isn't much of a blocker, would improve the quality of the community by having those that join self filter.

**Comment by advplyr** [comment]
It makes sense we start off with Discord and can always move if something else comes along.
I got it started, come on in:
https://discord.gg/pJsjuNCKRq
