### ISSUE TITLE
[Enhancement]: Render PDF eBooks with PDF.js

### ISSUE THREAD

**Issue by cassiuscai** [advplyr/audiobookshelf#3551]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Render pdf files with https://github.com/mozilla/pdf.js

### Why would this be helpful?

Enhance the experience with pdf files

### Future Implementation (Screenshot)

<img width="1430" alt="Screen Shot 2024-10-26 at 03 40 56" src="https://github.com/user-attachments/assets/92ae7a50-ae96-4b22-8956-1b68ad309839">

### Audiobookshelf Server Version

v2.15.1

### Current Implementation (Screenshot)

<img width="1252" alt="Screen Shot 2024-10-26 at 03 43 40" src="https://github.com/user-attachments/assets/1e6cd590-8b20-4dcf-a36c-8432bca9ba31">

**Comment by advplyr** [comment]
This is what is being used just not with all those features in the pdf.js demo

**Comment by cassiuscai** [comment]
> This is what is being used just not with all those features in the pdf.js demo

It will be great with all those features enabled in the future release.
