### ISSUE TITLE
[Enhancement]: 1.15x speed

### ISSUE THREAD

**Issue by DankMemeGuy** [advplyr/audiobookshelf#3556]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Right now the lowest increase is 1.25x. Would be nice to have 0.15x

### Why would this be helpful?

1.25x is sometimes too much, but 1.0x is too slow. 1.15 is ideal. Many podcasting software use 1.15x option

### Future Implementation (Screenshot)

Screenshot isnt needed

### Audiobookshelf Server Version

2.16

**Comment by glorenzen** [comment]
Could you clarify this a little bit? Do you want to be able to increment by 0.05 for the playback rate? Right now, you can increment the playback rate by .1. Are you saying 1.1x is too slow and 1.2x is too fast?

![image](https://github.com/user-attachments/assets/7f666450-b039-4057-a252-7bff2791f800)

**Comment by DankMemeGuy** [comment]
> Could you clarify this a little bit? Do you want to be able to increment by 0.05 for the playback rate? Right now, you can increment the playback rate by .1. Are you saying 1.1x is too slow and 1.2x is too fast?
> 
> ![image](https://private-user-images.githubusercontent.com/31518305/381789890-7f666450-b039-4057-a252-7bff2791f800.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Mjg0ODcsIm5iZiI6MTczMDQyODE4NywicGF0aCI6Ii8zMTUxODMwNS8zODE3ODk4OTAtN2Y2NjY0NTAtYjAzOS00MDU3LWEyNTItN2JmZjI3OTFmODAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAyMjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwODBlNGNiZTM4MDI4ZTU2YjNkN2RmYjY3ZDQzOTlkNmYxZGI1YTgwYzgzZTNkNTk2ZTE5YWYyNjliMzlkZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8UsmUiFozf2LzgIYZZHDnW9qLw5I41ivEB8gah-Hyvg)

I just realized that I use ShelfPlayer on iOS which is an unrelated project to ABS, so my feature request is misguided. My bad!

**Comment by tuomotalvitie** [comment]
> Are you saying 1.1x is too slow and 1.2x is too fast?

Sure. Came to find an issue about this, as the near perfect speed for a reader was 1.15, after trying both 1.1x and 1.2x. Not sure how common the .05 changes are, but at least in Audible the + and - buttons have that as the step (together with the similar quick selections ABS has)

And yes, this is closed. Just pointing this out in case some other poor soul happens to find this and desires this more than I do. I'll try to manage.

**Comment by AJolly** [comment]
I'd really like to change the speed by 0.05, or ideally let me just type in a number.  I've been using SmartAudioBookPlayer on android, which lets me change by 0.05. I've been often setting books at .95x

**Comment by dankcellar** [comment]
This has not been fixed yet. I can't change it in the android app
