### ISSUE TITLE
[Bug]: Invalid request. Setting "onlyShowLaterBooksInContinueSeries" must be of type undefined

### ISSUE THREAD

**Issue by mrslapdash** [advplyr/audiobookshelf#3559]
### What happened?

I'm trying to save any setting in Libraries -> Audiobooks -> Edit, and every time I try to save a change I get this error: 

Invalid request. Setting "onlyShowLaterBooksInContinueSeries" must be of type undefined

The settings are not saved.

### What did you expect to happen?

I expect my settings to be saved correctly.

### Steps to reproduce the issue

1. Go into Library -> Audiobooks (or whatever your audiobooks library is named) and select Edit
2. Try to make any change to settings and save

### Audiobookshelf version

2.16.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### Additional Notes

I have tried this on many browsers and many computers, and am getting the same result every time.

**Comment by mrslapdash** [comment]
I have tried specifically changing the setting on "Skip earlier books in Continue Series" but that does not work.

**Comment by advplyr** [comment]
Can you share the actual error log because it will contain where in the code this is happening

**Comment by advplyr** [comment]
I see now it isn't actually logging an error for you to share. I found out how to reproduce it and will fix soon

**Comment by mrslapdash** [comment]
Thank you!
