### ISSUE TITLE
[Enhancement]: Export/import stats

### ISSUE THREAD

**Issue by CyberB1aze** [advplyr/audiobookshelf#3586]
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

Be able to export/import listening stats for users.

### Why would this be helpful?

- If needed to create a new user for someone on same server.
- deploying fresh server and syncing listening stats (probably wouldn't work well).
- having read stats on different ABS servers. 

### Future Implementation (Screenshot)

just a simple import and export button your listening stats page. 

### Audiobookshelf Server Version

2.16.2

### Current Implementation (Screenshot)

![vivaldi_G34IBQEloN](https://github.com/user-attachments/assets/9c39b048-9a10-4290-90d8-14e75a9cc409)

**Comment by advplyr** [comment]
As @nichwall pointed out this isn't possible since library item IDs are random

**Comment by CyberB1aze** [comment]
what about copying the listening stats from 1 user to another one?

**Comment by nichwall** [comment]
Why are you wanting to copy listening stats from one user to another?

**Comment by CyberB1aze** [comment]
> Why are you wanting to copy listening stats from one user to another?

Mostly so I can copy stats from root user (which I have been using exclusively on my own server until recently) to a non root user (for SSO login functionality). SSO for root user is not possible at the moment and for good reason (still be able to access server and settings if sso link is broken). maybe the functionality to be able to create a new root user and change the root user to a non-root user? not sure how feasible something like that would be.

**Comment by advplyr** [comment]
SSO for root user is possible. You use the match via username or email feature and make sure it matches.

**Comment by CyberB1aze** [comment]
> SSO for root user is possible. You use the match via username or email feature and make sure it matches.

I see, in my personal set-up I use this oidc identity provider (https://github.com/stonith404/pocket-id) and when using match by email in ABS it always gives unauthorized. would this be a discrepancy in what the email id field is?
