### ISSUE TITLE
[Enhancement]: Mass saving of metadata

### ISSUE THREAD

**Issue by SwedishGojira** [advplyr/audiobookshelf#359]
### Describe the feature/enhancement

One thing that would be awesome would be to be able to save metadata for several books at once instead of having to open them one by one and click the save metadata button. Maybe even the for the whole library.

This would help in reorganizing books as at least on the Unraid docker all metadata is lost when moving a book from one folder to another.

**Comment by freitagdavid** [comment]
Seconded.

**Comment by MidnightSnowleopard** [comment]
Thirded.

One of the issues with the current mostly directory based sorting mechanism is if you moved something after specifically identifying it then all the work of identifying it is gone.  It's a half-way point between actually trying to turn it into a metadata manager and staying hands off.  There will always be edge cases that don't work well but this feel like something that shouldn't take much effort and could help alleviate any issues in the present while a larger solution may be worked on.

**Comment by advplyr** [comment]
Just pushed `v1.6.68` and got started on this.

The first step was adding an option on the library modal for selecting a metadata provider.
![image](https://user-images.githubusercontent.com/67830747/154175862-251d675e-5bdb-4cb0-a15b-793f23ca68ba.png)

Added a "Quick Match" button on book details tab that will use the selected provider and fill in book details with the first match result.
![image](https://user-images.githubusercontent.com/67830747/154175682-a986da9a-80fb-4eb9-9c25-eca41b2d6cc8.png)

There are a lot of tweaks that can be made there to ensure the match is correct, but right now it is just taking the first result.

Then a "Match Books" button on the library which loops through all the books and just calls the same method that quick match uses. Again using the selected library metadata provider.
![image](https://user-images.githubusercontent.com/67830747/154175992-9eebccc7-9aeb-4668-8678-a51f1350368e.png)

Important to note is that it will only fill in details where fields are empty. If no book cover is set then it will use the book cover from the search result.

**Comment by cassieesposito** [comment]
This doesn't entirely address the issue, but turning on "Store metadata with book" in the settings allows you to reorganize without losing metadata as long as you make sure to also move the metadata file.
