### ISSUE TITLE
[Bug]: 0.9.77-beta - download doesn't background or resume 

### ISSUE THREAD

**Issue by danielb2** [advplyr/audiobookshelf#3590]
### What happened?

If I switch to another window the download stops. If I switch back it just says it's downloading but doesn't resume.

(Side note with the beta is that it also can't find current downloads )

### What did you expect to happen?

Downloads should continue in the background 

### Steps to reproduce the issue

1. Download book
2. Switch to another app

### Audiobookshelf version

0.9.77-beta

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by nichwall** [comment]
This belongs in https://github.com/advplyr/audiobookshelf-app

Scanning local files was removed in 0.9.67, almost a year ago due to additional complexity to link files back to the server.

**Comment by danielb2** [comment]
> This belongs in https://github.com/advplyr/audiobookshelf-app

see https://github.com/advplyr/audiobookshelf-app/issues/1367


> Scanning local files was removed in 0.9.67, almost a year ago due to additional complexity to link files back to the server.

how is this related to my current issue with the beta ?

**Comment by nichwall** [comment]
> how is this related to my current issue with the beta ?
> 

Usually when people have mentioned "can't find current downloads", they want scanning of local media files on their device, like when they downloaded ABS but then reset the app and still want the files linked to the server (or have unrelated media files). Do you mean something else?

**Comment by danielb2** [comment]
> Do you mean something else?

Yes. I mean the Local Books that had already been downloaded from the server that I was listening to. They were still occupying space, and I had to start over fresh and redownload all content to the phone to be able to listen again

**Comment by nichwall** [comment]
> > Do you mean something else?
> 
> Yes. I mean the Local Books that had already been downloaded from the server that I was listening to. They were still occupying space, and I had to start over fresh and redownload all content to the phone to be able to listen again

Yes, this is what I mean by scanning local files is not supported and was removed from the app.

**Comment by danielb2** [comment]
I think you misunderstand. I'm not talking about downloading content locally to my phone. I'm talking about downloading on the app from the audiobookshelf server for local listening.

**Comment by danielb2** [comment]
![1000330794](https://github.com/user-attachments/assets/0aa58ef8-3932-4edd-8f5a-8abef9e17ace)

**Comment by danielb2** [comment]
> * What do you mean by "downloads are disappearing"? From the app, from your filesystem on your phone?

I mean that after the app updated, all downloaded books were missing (no longer showing up in the app) hence forcing me to download ALL locally downloaded books again. Thus upon redownloading the book, I ran into the issue of the books failing to download.
