### ISSUE TITLE
Enhancement: Stack Into Series on Home Screen with Unread and/or Total Books Counters

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf#36]
Currently the Home Screen can be a bit cluttered, and make it difficult to determine if a book is missing or find it if the search isn't doing it due to some tagging error.

If the books were allowed to be stacked into their Series, with strays still cluttering the surrounding area, clean up of tagging would be improved and overall usability of the home screen could improve.

With that, if Series were marked with the number of Unread books at home screen then it becomes that much easier to identify where to go for a newly imported title for listening or download.

**Comment by advplyr** [comment]
I agree, can you provide an example of how you think this would look?

If a series is grouped, how would you differentiate between a series and a regular book?
What would the cover art look like for a series?

On a similar note, there is a "New" book flag that I want to further integrate, [discussed here](https://github.com/advplyr/audiobookshelf/discussions/13#discussioncomment-1248719)

**Comment by Budlyte** [comment]
Behold, my Paint-fu!

Right off the bat, I'd say just use the first cover available as the Series cover. The human brain identifies pictures quicker than text.

But that might still look cluttered and an option to toggle between using covers and just loading the default cover with info?  Or maybe add the Title to the bottom of the cover image?  

![image](https://user-images.githubusercontent.com/4451365/133628991-167940b6-2a83-465b-a2ca-8817c24ef98f.png)


The question now becomes, once a Series is clicked what does navigation look like? Should the bookshelf basically just set a filter load down to that series?

**Comment by advplyr** [comment]
`But that might still look cluttered and an option to toggle between using covers and just loading the default cover with info? Or maybe add the Title to the bottom of the cover image?`
I think the number over the cover will suffice in distinguishing it as consisting of multiple audiobooks.

With the current set-up you are only shown your progress and whether or not you've read the book. If we include the  notification for unread books then I think it would need to be optional.

How are you envisioning the option will look like for the user enabling this group by series? Do you see this as something in the toolbar next to the filter & sort, or is it a different view that you go to, or an option in user settings?

**Comment by Budlyte** [comment]
At first I thought it could easily just be tossed next to filter & sort, but I believe Plex has a similar option in library settings for Movies, "Automatically group movies by collections" or something similar. Probably best to use what they've figured out already and have it as a toggle somewhere in Settings.

Eventually the options will start to pile up, if you don't mind adding them, better to plan for them being where they'll need to be later rather than have 30 buttons on the home screen even if that means a silly looking lonesome toggle under some Settings category for a while.

**Comment by Budlyte** [comment]
The more I think about this one, the more I'm unsure if what I've suggested is the right move....

The main place I really see this being useful is when browsing a specific Author, because when viewing a single author it's a bit impossible to tell which book is actually next in the series, without using the Series filter.

I almost think that just moving the Series filter out on its own, or making a different one, next to the listed number of Audiobooks and limiting its scope to those same visible Audiobooks could be a more visibly pleasing solution.

Here's an Author sorted by Volume #
![image](https://user-images.githubusercontent.com/4451365/133953968-7eddc467-b1ab-475d-9ab3-cb4c31f39fc5.png)


And clicking the button would just dropdown like usual.  (Obviously I wanted to include "Murderhobo" in my example)
![image](https://user-images.githubusercontent.com/4451365/133954063-7252add5-92cf-41f9-b576-29773d77de8c.png)

**Comment by advplyr** [comment]
I'm still conflicted on this. There needs to be some level of grouping, but I'm not sure how sorting will function for groups.
The other issue mentioned talks about collections, but I think series should be enough. If a book belongs to a series and you want it part of another collection, then maybe that is what `tags` should be for.

I'm leaning towards an option like you mentioned that is called "Collapse Series" or "Group Series". That option will show one book with the number of books in the series. When sorting it will just use the first book in the series or for title it will just use the series name.
