### ISSUE TITLE
[Bug]: not all items adding to library

### ISSUE THREAD

**Issue by ylnest2018** [advplyr/audiobookshelf#3605]
### What happened?

books are missing from the library, files seem readable so I’m not sure.

### What did you expect to happen?

Books should add to the library

### Steps to reproduce the issue

1. Add file to library 
2. Run library scan

### Audiobookshelf version

v2.16.2

### How are you running audiobookshelf?

Debian/PPA

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by nichwall** [comment]
Do you have any logs?
Is each book in its own directory? Every book must be in its own directory or else books will be combined.

https://www.audiobookshelf.org/faq/server#why-are-multiple-books-showing-as-the-same-book

https://www.audiobookshelf.org/docs#book-directory-structure

**Comment by ylnest2018** [comment]
Definitely everything is in its own folder and being done through Readarr, it’s worked for 6600+ books but here and there I’ve noticed 13/18 from one author showing ABS

**Comment by nichwall** [comment]
Can you look at the books for that specific author to make sure that the missing books have not been grouped under another book in ABS?

That could have happened if ABS picked up the book before or during the rearrangement of files. If so, you will want to delete the problematic book from ABS and rescan.

**Comment by ylnest2018** [comment]
No search result will find those books but I will go through 1 by 1 to see if the files are part of another book from the same author

**Comment by ylnest2018** [comment]
To add to this, I have a whole authors collection missing so the author is in its own folder with 5-6 books but neither the author or any of her books appear, so it isn’t just a case of 13/18 etc it’s also whole lists missing

**Comment by ylnest2018** [comment]
> Do you have any logs? Is each book in its own directory? Every book must be in its own directory or else books will be combined.
> 
> https://www.audiobookshelf.org/faq/server#why-are-multiple-books-showing-as-the-same-book
> 
> https://www.audiobookshelf.org/docs#book-directory-structure

Which log do you think is best for missing items? I’m happy to submit to assist with the review. I looked through the author which has 18 books but only 13 showing, none of the 13 books have a secondary file so doesn’t appear to be the book finding before rearrangement issue you suggested above.

luckily (or unluckily depends how you look at it) I have an author which no books are showing for so would be interesting once grabbing the log you recommend to search for that author and it might give more info

**Comment by nichwall** [comment]
If you go to `metadata/logs` you should see logs from the scans. You will probably need to change your log level to Debug before scanning if you have not done so already.

It still sounds like your directory structure is not set up correctly (either now or at some point prior when ABS was running). It could also be a specific file causing the server to crash and not complete scanning the library, but we'll need to see that in the logs.

**Comment by ylnest2018** [comment]
ah this explains why my log file is so large it was already set to debug. thank you.

So from the logs, I do not see the authors name or part of her name in any of the entries, I am seeing a Socket Disconnect / Reconnect during a scan, this might indicate a file issue?

noticed this in the log, wondering if this could be the cause

![image](https://github.com/user-attachments/assets/3d1568f0-57b4-4029-b4e3-dd4919f039e2)
