### ISSUE TITLE
[Enhancement]: Download via share link

### ISSUE THREAD

**Issue by mrfluffy-dev** [advplyr/audiobookshelf#3606]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

When you share a book with someone via the share button I would love the ability for the user of the link to download the book. 

### Why would this be helpful?

This will be useful when you want to share the audio file with someone without needing to add the file to some other file sharing service.

### Future Implementation (Screenshot)

for example 

1. click the burger menu
2. select share
3. toggle downloadable radio button
4. get link

then from the link user's side 

1. open link 
2. click download button 
3. starts downloading the book

![screenshot-2024-11-12-16-31-42](https://github.com/user-attachments/assets/349806bd-a809-463d-99a2-3a92b6ce73a3)

### Audiobookshelf Server Version

v2.16.2

### Current Implementation (Screenshot)

![screenshot-2024-11-12-16-20-23](https://github.com/user-attachments/assets/c175302b-c482-40fa-a717-e4d444494db7)

**Comment by advplyr** [comment]
Are you talking about the zip file that gets downloaded like the download button on the item page?
