### ISSUE TITLE
[Enhancement]: Global Book search and Wishlist

### ISSUE THREAD

**Issue by ylnest2018** [advplyr/audiobookshelf#3609]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

I did a quick search and don’t think it’s been asked before so I’m not sure if there’s any plans to integrate but would be awesome to have a similar setup to the Plex <> Overseer <> Sonarr/Radarr setup for books, ability to search a repository that is used for book meta data look up (eg GoodReads, GoogleBooks etc) and it determine if you have that book and if not you could add it to a Wishlist it would send a request to Readarr or Readarr could read ABS’ Wishlist. If none of the other features then a global search and Wishlist would be awesome alone, which would even integrate with a goodreads list.

### Why would this be helpful?

The Wishlist would make managing the library a lot easier, eliminate the need for multiple services for the end user. 

### Future Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/c7488058-ed90-4ae4-a253-c5e32d240db6)

### Audiobookshelf Server Version

V2.19.2

### Current Implementation (Screenshot)

Doesn’t exist currently

**Comment by nichwall** [comment]
ABS does not support or promote piracy. It is designed to serve your own files, and does not include obtaining files.

With that said, there are a few issues related to managing a wishlist and missing books. Related to:
Release calendar https://github.com/advplyr/audiobookshelf/issues/443
Goodreads integration https://github.com/advplyr/audiobookshelf/issues/281
Webhook support https://github.com/advplyr/audiobookshelf/issues/1857
Missing books https://github.com/advplyr/audiobookshelf/issues/3221

**Comment by ylnest2018** [comment]
I’m glad to hear, I stand with you on that

![](https://img.memegenerator.net/instances/55527211.jpg)

thanks for those links I’ll take a look
