### ISSUE TITLE
[Enhancement] Ignore "The" at the beginning of a series or title when sorting

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#361]
### Discussed in https://github.com/advplyr/audiobookshelf/discussions/358

<div type='discussions-op-text'>

<sup>Originally posted by **snowmangoh** February  9, 2022</sup>
I would love the option to exclude "The" from being included in the sorting logic if it's at the beginning of a book or series title.</div>

**Comment by advplyr** [comment]
This is added in `v1.6.67` and can be enabled with a server setting.

![image](https://user-images.githubusercontent.com/67830747/153967763-f5a4e2af-1849-4e2b-9a52-3d6ded7186d4.png)

If you have alternate bookshelf enabled you can see the title updated with ", The" at the end.

![image](https://user-images.githubusercontent.com/67830747/153967948-a9929d6a-e6e9-4260-ab65-2fbc30ce4902.png)

**Comment by Xuereb** [comment]
I'd argue the same should be done for the prefix "A"
