### ISSUE TITLE
[Enhancement]: Add ability to "Follow" an author or series

### ISSUE THREAD

**Issue by bdstout1617** [advplyr/audiobookshelf#3610]
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

Add the ability to "follow" an author or series and be notified using the apprise (is that right?) notification system when a new audiobook by that author has been released and what publisher it was released under. Similar to how podcasts get notified when a new episode is released potentially? 

### Why would this be helpful?

It would be nice if you (like me) have many different series of books that you are currently listening to and are all currently still being actively written could get notifications on when a new book in that series or by that author is published so that you can go buy it from said publisher and add to your audiobook server. 

### Future Implementation (Screenshot)

No clue what it would look like, potentially a star next to the series? or a follow button on the description of the series or author page? Here is a screenshot of what Audible does when you follow an author. 
![image](https://github.com/user-attachments/assets/d4b286c7-b7d1-4e3d-b41b-d874a1896534)
Could add it maybe on the series page? 
![image](https://github.com/user-attachments/assets/a2f8f479-502b-474c-a82c-aa9ed8f73ee0)

### Audiobookshelf Server Version

2.8.1

### Current Implementation (Screenshot)

There is no following a series or author that I am aware of anyways.

**Comment by nichwall** [comment]
Related to https://github.com/advplyr/audiobookshelf/issues/963, https://github.com/advplyr/audiobookshelf/issues/443, https://github.com/advplyr/audiobookshelf/issues/281, https://github.com/advplyr/audiobookshelf/issues/3221.

**Comment by advplyr** [comment]
I see why this would be a nice to have but it is outside the scope of the project
