### ISSUE TITLE
[Bug]: Error adding new series if a series has `null` title in database

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf#3622]
### What happened?

If the `series` table has a row where the title is `null`, a TypeError is thrown in the web client when trying to add a new series. Adding a book to an existing series is able to be completed successfully, but new series cannot be created.

The error occurs at https://github.com/advplyr/audiobookshelf/blob/2b0ba7d1e28f8cc0bcce153cbcde1a06927f93d9/client/components/widgets/SeriesInputWidget.vue#L90

### What did you expect to happen?

Able to create a new series.

### Steps to reproduce the issue

1. Create a row in the `series` table where title is `null`
2. Attempt to add a new series to a book in the web client

### Audiobookshelf version

v2.17.0

### How are you running audiobookshelf?

Built from source

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
TypeError: se.name is null
```

**Comment by advplyr** [comment]
I fixed the error but we should be on the lookout for how to reproduce getting a series added to the db with a `null` title.

**Comment by nichwall** [comment]
I spent some time after opening this issue to try and add a `not null` to relevant columns in the database to help clean this up, but have not been able to get it to work yet for the series table due to a `delete cascade` being triggered, which removes all rows from the `bookSeries` table.

Once I figure out how to do that I'll open a PR. Initial research looks like it will be a bit involved for the migration (not as easy as just adding a new index) and will be SQLite specific, but that should be fine for now since everyone is using SQLite (and if anyone is using a different database backend, they will already need to be patching stuff anyway).

This was found in DieselTech's database, I am not sure how it happened either.

**Comment by advplyr** [comment]
There are only a few places where Series get created so we can add a check there for null and throw an error or just reject the series.
Ideally it would be not null in the DB but we shouldn't be forced to make a dialect specific update if we don't have to
