### ISSUE TITLE
[Enhancement]: add entire podcast to queue when play is clicked

### ISSUE THREAD

**Issue by Vincenzoferrara** [advplyr/audiobookshelf#3629]
### Type of Enhancement

None

### Describe the Feature/Enhancement

when I enter a podcast there is a play button, I expect it to queue up all the files, instead it only plays the last one.

### Why would this be helpful?

I listen to podcasts on the street, I hit play and I want to set all the podcasts from that creator, I don't want to have to click to play a new one every time an episode ends.

### Future Implementation (Screenshot)

![audiobookshelf foto1](https://github.com/user-attachments/assets/b1f53b97-0ddd-4b53-b887-81be58e0d4ef)
![audiobookshelf foto2](https://github.com/user-attachments/assets/008c4ffd-efa2-4fb1-9094-80fd3d89d050)

### Audiobookshelf Server Version

 v2.17.1

**Comment by advplyr** [comment]
Related to https://github.com/advplyr/audiobookshelf/issues/1321
The queue gets filled with any episode that is not finished and was released later than the one you clicked.
So if you click an episode a few episode down you will see the queue is populated

**Comment by Vincenzoferrara** [comment]
although it would make more sense to me if clicking the play button at the top of the podcast (and not the episode), compiles them all.

anyway it works so I can also close it if it is not foreseen
