### ISSUE TITLE
[Enhancement]: Add file name/path information to podcast episode records

### ISSUE THREAD

**Issue by Badger1919** [advplyr/audiobookshelf#3648]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

For a podcast episode record, there is no way to tell which file is linked to that episode record. When you view the details for an episode record, it should show the file name/path that is linked to it.

### Why would this be helpful?

The files downloaded through an rss feed for a podcast isn't always named in such a way that you can tell which episode it is. Being able to tell which file belongs to which episode record would make it easier to sort through them. Additionally, if you end up with duplicate episode records (multiple records for the same episode), you can't tell which record points to which file.

### Future Implementation (Screenshot)

I'm less concerned with the exact implementation than that the information is available somewhere. You could also put the information in the edit lightbox. In fact it would be nice to be able to change the file associated with a given episode record.

![future implementation](https://github.com/user-attachments/assets/4dabc02c-dd6b-470a-a44e-1ca0332e519b)

![future implementation (lightbox)](https://github.com/user-attachments/assets/0535340f-9528-49d6-b401-73187b0dd315)

### Audiobookshelf Server Version

v2.17.2

### Current Implementation (Screenshot)

![current implementation](https://github.com/user-attachments/assets/8c87249a-1036-4d52-b910-286cdab3f588)

![current implementation (lightbox)](https://github.com/user-attachments/assets/71b00019-e69e-4983-be12-d16f0f6004b2)

**Comment by advplyr** [comment]
I put this at the bottom of the view episode modal. Not sure of a better place for it

![image](https://github.com/user-attachments/assets/6806fbdc-982e-4c97-aed0-b233c034486e)

**Comment by Badger1919** [comment]
Great! Thanks!
