### ISSUE TITLE
[Enhancement]: If only one Collection/Playlist exists, go straight to the Collection/Playlist

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3660]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

In the Web Interface, if only one Collection/Playlist exists, then the Web page should go straight to that collection/playlist without selecting the list first.

### Why would this be helpful?

This is to reduce mouse clicks and make the experience better. 

### Future Implementation (Screenshot)

No screenshot. 

### Audiobookshelf Server Version

 v2.17.2

### Current Implementation (Screenshot)

Recording of the issue. 

https://github.com/user-attachments/assets/f23139f9-5af2-4df2-b30c-6234a1dbde39

**Comment by advplyr** [comment]
I think that creates for a more confusing user experience. If you have one then you should see one when you go to the playlist/collection page so you know you have only one. New users testing out playlists/collections would be confused if we implemented this.
We have a demo server now https://audiobooks.dev/ with user/password demo/demo and I added one collection in there. I want users demoing the software to see the collections page

**Comment by pwinnski** [comment]
Yeah, no. I didn't click on "Collection XYZ," I clicked on "Collections." I expect that click to do the same thing whether I have zero, one, or two or more collections. I don't like the idea of it behaving differently when the count is one than it does when the count is zero, two, or more than two.

The video is great, it demonstrates what I consider to be the correct behavior.
