### ISSUE TITLE
[Bug]: audiobookshelf.service file updating every time there is a change through apt-get

### ISSUE THREAD

**Issue by pjones112000** [advplyr/audiobookshelf#3669]
### What happened?

Every time there is an update, the audiobookshelf.service file gets modified...in my case I have a specific user/group I run the service as but it keeps changing it to the audiobookshelf user/group which of course causes it to fail to start.  Unless there is a specific need, it should not be modifying this service every update.

### What did you expect to happen?

Only files required for updating should be updated...if there is a conflict, then let the installer know but do not update manually edited files during an apt update.

### Steps to reproduce the issue

1. New release/update
2. Run apt-get update/upgrade
3. Service fails

### Audiobookshelf version

2.12.3

### How are you running audiobookshelf?

Debian/PPA

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by nichwall** [comment]
Is this the same as https://github.com/advplyr/audiobookshelf/issues/1927?

**Comment by pjones112000** [comment]
I looked but must have missed this post, but yes that seems to be the exact same issue.  I'll close mine.
