### ISSUE TITLE
[Bug]: After metadata match completes, screen refreshes again adding bad data.

### ISSUE THREAD

**Issue by Xuereb** [advplyr/audiobookshelf#368]
### Describe the issue

After doing a match on an audiobook. (Particularly one with missing Metadata) The metadata fills in and then the screen refreshes and it add the genre of "audiobook" which is meaningless in application meant entirely for audiobooks. In some cases this refresh also changes the title from what was just set by the match to include things like "(Unabridged)" or ": {Series} Book {#}" which to be clear was not in the preview that you click through for the data match and is an additional change being made.

I am working on getting screenshots of it changing the title, I already dealt with this happening several times before thinking to document and report it here. It is not something that happens every time and doesn't happen once the metadata is already completed.

### Steps to reproduce the issue

1. Edit audiobook with incomplete metadata
2. Use the "Match" tool to get metadata
3. Accept the metadata that will be added
4. Wait a few seconds on the refreshed page details page
5. "Audiobook" shows up in Genres

### Audiobookshelf version

v1.6.66

### How are you running audiobookshelf?

Docker / Unraid

**Comment by advplyr** [comment]
Do you have the server setting enabled that is saving the cover art in your audiobook directory?

Are you using a remote file system where your audiobooks are stored? What OS are you running docker?

**Comment by Xuereb** [comment]
> Do you have the server setting enabled that is saving the cover art in your audiobook directory?

I do, I could see how that could be triggering the refresh I'm seeing. Should I try disabling it and see if it stops.

>Are you using a remote file system where your audiobooks are stored? What OS are you running docker?

Local fs, running on Unraid

**Comment by advplyr** [comment]
Yeah so it seems the folder watcher is getting triggered by the added cover art, which is normal. Then the directory is scanned and the audio file is being detected as a new audio file, which would mean the inode value attached to the audio file is changing between scans.

I've only seen this happening with remote file systems, like using Unraid but storing your audiobooks on a Windows drive.

You should try scanning your entire library again to see if it is creating new audiobooks.

**Comment by Xuereb** [comment]
I was mucking about in the folder structure last night cleaning up the rest of my library and didn't run across the issue nearly as much. The main factor was likely the cover art, but by then I had found that I preferred getting the cover art separate from the metadata (match) as the match with the most complete metadata / description didn't have the best cover art. So as course I have been unticking getting the cover from the match and it stopped the refresh. And getting the cover from the cover tab does not pull errant genres or titles.

**Comment by advplyr** [comment]
That's good to hear. You will likely come across bigger issues when adding new audiobooks and scanning your library because there is something going on with your file system. If that happens feel free to open another issue or re-open this one.

**Comment by Xuereb** [comment]
Interesting, because in what I was doing last night I added about 30 files, and corrected a handful that had bad folder structure and were being merged (several book files under a series folder but not individual book folders), and even in all that rearranging I had no issues. I have about another 30 I'll be migrating over from Libro tonight. Are you saying issues should pop up from scans or a force re-scan, because I didn't do the latter.

**Comment by advplyr** [comment]
I may be misunderstanding your issue entirely. If you rename an audiobook folder by just changing the spelling and audiobookshelf creates a duplicate audiobook marking the original as missing, then it is what I expected.
Renaming an audiobook folder should just update the title or other missing book details.

**Comment by Xuereb** [comment]
>If you rename an audiobook folder by just changing the spelling and audiobookshelf creates a duplicate audiobook marking the original as missing, then it is what I expected.
This did happen when I was moving things around in the FS last night. But, like you, I considered it expected behavior. (Plex does the same)

But this is not the original trouble I was having. The trouble I was having before was entirely contained within the audiobookshelf web ui.

**Comment by advplyr** [comment]
The "audiobook" genre appears because the first audio file in that folder has an ID3 tag for genre with that value.
https://www.audiobookshelf.org/docs#metadata

Many audiobook audio files I have use "audiobook" as a genre, which I agree is meaningless. Maybe it is worthwhile adding a check to ignore this genre on the audio file. I'm sure the vast majority of users don't want to use this genre, only maybe some users with a lot of audio plays or podcasts, but those would be the exception.
