### ISSUE TITLE
[Bug/Enhancement]: For series detection by id3 tags, use GRP1 in addition to/instead of TXXX:grouping

### ISSUE THREAD

**Issue by Cantello** [advplyr/audiobookshelf#3681]
### What happened?

According to [this comment](https://github.com/advplyr/audiobookshelf/issues/3547#issuecomment-2440086269) the `grouping` tag is used to define series. However, when using abs to embed metadata into mp3 files, it writes the obsolete `TXXX:grouping` field, instead of  the widely accepted `GRP1` field, which is used by major id3 taggers (kid3, mp3tag, MusicBrainz Picard) and I cannot edit the tags anymore outside of abs, which kind of defeats the purpose of standardised tags.

### What did you expect to happen?

Adiobookshelf recognizes the `GRP1` tag when detecting metadata.

### Steps to reproduce the issue

1. Edit series in audiobookshelf
2. Embed metadata into mp3 files
3. Try editing with an id3 tagger

### Audiobookshelf version

2.17.3

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### Additional Notes

According to https://github.com/advplyr/audiobookshelf/blob/c03f18b90a100ab0041f05993700d3404f88c9dc/server/utils/prober.js#L192 the `grouping` tag is only defined by one property, whereas e.g. Album is defined as `file_tag_album: tryGrabTags(format, 'album', 'talb', 'tal'),`, Artist as `file_tag_artist: tryGrabTags(format, 'artist', 'tpe1', 'tp1'),`.
Could the definition of grouping be expanded similarly to `file_tag_grouping: tryGrabTags(format, 'grouping', 'grp1'),`?

**Comment by advplyr** [comment]
Does ffprobe detect that tag? https://www.audiobookshelf.org/guides/ffprobe/#inspecting-an-audio-file

**Comment by Cantello** [comment]
> Does ffprobe detect that tag? https://www.audiobookshelf.org/guides/ffprobe/#inspecting-an-audio-file

Yes, it does (output of ffprobe on a file with the GRP1 tag written):
```
  [...]
      "title": "Kapitel 1 & Kapitel 2.1 - Tintenwelt 1. Tintenherz",
      "track": "1/63",
      "GRP1": "Tintenwelt",
      "date": "2013-08-01"
  [...]
```

**Comment by Cantello** [comment]
Tested and it works, great, thanks!

**Comment by Cantello** [comment]
Did anything change since the last release? I checked and the only grouping tag that was recognized by abs was a TXXX frame with 'grouping' as the description. Whenever I try to tag something with Yate (Mac tagger comparable to mp3tag), the GRP1 tag (encoded in UTF16) was not recognized. Can provide samples if necessary.
