### ISSUE TITLE
[Bug]: v2.17.3 db migration does not complete if version skipped

### ISSUE THREAD

**Issue by cordlord** [advplyr/audiobookshelf#3686]
### What happened?

Updated to latest v2.17.4, but was still on v2.17.2. Container did not start, no logs, nothing.

Rolled back to v2.17.2. Manually updated to v2.17.3, then to latest and all is working again.

### What did you expect to happen?

Update to latest, v2.17.4, without issues.

### Steps to reproduce the issue

1. Run v2.17.2
2. Skip v2.17.3 and update to v2.17.4.
3. Start container.

### Audiobookshelf version

v2.17.4

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
There were no logs recorded until I re-installed v2.17.2.

I happened to see the db migration note and went from there on a hunch.
```

**Comment by advplyr** [comment]
I just tested this and wasn't able to reproduce the issue. 

To test this I started up a new server with docker tag `2.17.2`. Then initialized the server.

Then upgraded to docker tag `2.17.4`.

In the docker logs I saw both db migrations run successfully.

I'm not sure what you are using to run your docker containers but they should always have some logs.
