### ISSUE TITLE
Bug [Mobile]: Long Book Titles/Authors Push Interactive Buttons Off Screen In Downloads On Mobile App

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf#37]
If the book title or Author info is too long, the interactive buttons (Play & Delete) get shoved off the screen.

![image](https://user-images.githubusercontent.com/4451365/133644889-8bed211c-244e-43f1-a2e5-ac11ac40cdd3.png)

**Comment by advplyr** [comment]
Just fixed this in `v0.8.3-beta`
