### ISSUE TITLE
[Enhancement]: Bulk Editor: Apply field to multiple books

### ISSUE THREAD

**Issue by Jdiesel87** [advplyr/audiobookshelf#370]
Maybe this can all already be be done but it is it wasn't intuitive to me.

When you open up multiple books in the bulk editor it would be nice to be able to apply an edit to multiple books at once. I ran into the need for this when adding multiple books to a series. I could also see this being extremely useful for editing genre tags or getting consistent spelling on an authors name.

**Comment by advplyr** [comment]
Yeah this is needed for sure. Do you have an idea of what this would look like?

If you select multiple audiobooks with different genres would you be able to add a single genre to them, or just overwrite the genre for them all?

I'm thinking that each field will need a checkbox next to it for if you want to use that field. That would handle the use-case where you want to make a field empty for all selected books.

**Comment by Jdiesel87** [comment]
I can see use cases for both adding to a field and replacing the entire field. Given the choice between the two I think replacing the entire field would be the most flexible. 

Maybe a copy dialog which you are able to select from the source field, click copy-to, which would bring up checkboxes for the other books in the bulk editor view, and a confirmation box.

**Comment by Jdiesel87** [comment]
I'm not always the best person to get UI feedback from since I am very utilitarian. When I get home I will have a peek at how Calibre does it, I'm pretty sure it has the option to do exactly this

**Comment by advplyr** [comment]
I just pushed `v1.6.69` and added the map details section.

![image](https://user-images.githubusercontent.com/67830747/154593039-c6dcb559-b4e5-4017-a902-7efe6047d51a.png)

**Comment by Jdiesel87** [comment]
Works great! Thanks!

This should make taming my mess of a library much less painful.
