### ISSUE TITLE
[Enhancement]: Distinguish between an item being "matched" or "unmatched"

### ISSUE THREAD

**Issue by zahroc** [advplyr/audiobookshelf#3703]
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

Would be nice to know if an item has been "matched" with an item from an external source vs. an item that is "unmatched."
The capability exists in Plex where you can "unmatch" or "match" an item.

### Why would this be helpful?

Filter on unmatched to make sure all items get matched with details.

### Future Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/7a1a52d6-36b4-4e8d-b3b0-645ca60cfcf9)
![image](https://github.com/user-attachments/assets/c0ee382c-633b-4d35-a881-6ab2f203cad8)

### Audiobookshelf Server Version

2.17.5

### Current Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/d348951f-3b30-4edc-a895-2ef188938da3)

**Comment by nichwall** [comment]
Matching against an online provider will usually fill in the ISBN or ASIN for a book. You can use the Filter "Missing -> ASIN" or "Missing -> ISBN" depending on your library.

**Comment by advplyr** [comment]
This has been brought up before if anyone can find the github issue

**Comment by advplyr** [comment]
Both closed because that is what the missing field is for.

https://github.com/advplyr/audiobookshelf/issues/643
https://github.com/advplyr/audiobookshelf/issues/395
