### ISSUE TITLE
[Enhancement]: Cache books/podcast for offline listening

### ISSUE THREAD

**Issue by sbadger** [advplyr/audiobookshelf#3707]
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Cache some audiobooks and podcast locally on my device so they continue to play even into the next episode while the device is offline

### Why would this be helpful?

I listen to podcast and audio books often when I travel and don't always have data available. It would be nice to cache some audiobooks and podcast locally on my device so they continue to play even into the next episode while I am without data.

### Future Implementation (Screenshot)

Have an option to cache the book(s) via long press or something on the book cover.
For podcast you could say cache the next X number of episodes or the whole podcast

### Audiobookshelf Server Version

0.9.77

**Comment by nichwall** [comment]
Offline playback is supported in the mobile apps. There are several feature requests around automatically downloading files and automatically continuing to the next item in the queue in the app repo.
https://github.com/advplyr/audiobookshelf-app

**Comment by sbadger** [comment]
I just found the download button at the end of each episode.
Is there a way to have it automatically download a set number of episodes that are going to be served up in the next episode list so i don't have to go click a ton of them beforehand?

**Comment by nichwall** [comment]
There is not. There are some feature requests if you want to leave a thumbs up reaction on them in the app repository.

**Comment by sbadger** [comment]
I will!  Thank you

**Comment by sbadger** [comment]
I will go check those out
Thank you
