### ISSUE TITLE
[Enhancement]: Desktop client

### ISSUE THREAD

**Issue by TheOnlyJonto** [advplyr/audiobookshelf#373]
### Describe the feature/enhancement

A desktop client for accessing your library on a PC. Could simply be web based.

**Comment by advplyr** [comment]
The web client can be installed as a PWA now #354 

Did you have any specific features in mind that you would want in a desktop app that is not possible with a PWA?

**Comment by TheOnlyJonto** [comment]
My bad! I was just mistaken about how to access the web client. It works great, thanks!

**Comment by yougotwill** [comment]
Just in case any one stumbles on this issue. Using https://github.com/nativefier/nativefier I have perfectly running app on macOS with full media keys support.
