### ISSUE TITLE
[Bug]: Search request error

### ISSUE THREAD

**Issue by wisark** [advplyr/audiobookshelf#3747]
### What happened?

I have installed ABS for the first time on my Synology NAS DS224+ via docker compose file indicated in the docs. I have also configured Synology NAS Reverse Proxy Setup without problems, being able to access through the UI, but when searching for a podcast from “Add” I always get the result “No podcasts found”. I have previously added the Library from Settings.

### What did you expect to happen?

I hope to find the podcasts I was looking for.

### Steps to reproduce the issue

1. Click Add
2. Enter search term in the search box
3. Click Submit button

### Audiobookshelf version

v2.17.5

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Logs

```shell
[iTunes] search request error [AxiosError: timeout of 30000ms exceeded] { code: 'ECONNABORTED', config: { transitional: { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false }, adapter: [Function: httpAdapter], transformRequest: [ [Function: transformRequest] ], transformResponse: [ [Function: transformResponse] ], timeout: 30000, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, maxBodyLength: -1, env: { FormData: [Function] }, validateStatus: [Function: validateStatus], headers: { Accept: 'application/json, text/plain, */*', 'User-Agent': 'axios/0.27.2' }, params: { term: 'lex fridman podcast', media: 'podcast', entity: 'podcast', lang: undefined, limit: undefined, country: 'es' }, method: 'get', url: 'https://itunes.apple.com/search', data: undefined }, request: <ref *1> Writable { _events: { close: undefined, error: [Function: handleRequestError], prefinish: undefined, finish: undefined, drain: undefined, response: [Function: handleResponse], socket: [Array], timeout: undefined, abort: undefined }, _writableState: WritableState { highWaterMark: 16384, length: 0, corked: 0, onwrite: [Function: bound onwrite], writelen: 0, bufferedIndex: 0, pendingcb: 0, [Symbol(kState)]: 17580812, [Symbol(kBufferedValue)]: null }, _maxListeners: undefined, _options: { maxRedirects: 21, maxBodyLength: 10485760, protocol: 'https:', path: '/search?term=lex+fridman+podcast&media=podcast&entity=podcast&country=es', method: 'GET', headers: [Object], agent: undefined, agents: [Object], auth: undefined, hostname: 'itunes.apple.com', port: null, nativeProtocols: [Object], pathname: '/search', search: '?term=lex+fridman+podcast&media=podcast&entity=podcast&country=es' }, _ended: true, _ending: true, _redirectCount: 0, _redirects: [], _requestBodyLength: 0, _requestBodyBuffers: [], _eventsCount: 3, _onNativeResponse: [Function (anonymous)], _currentRequest: ClientRequest { _events: [Object: null prototype], _eventsCount: 2, _maxListeners: undefined, outputData: [], outputSize: 0, writable: true, destroyed: true, _last: true, chunkedEncoding: false, shouldKeepAlive: true, maxRequestsOnConnectionReached: false, _defaultKeepAlive: true, useChunkedEncodingByDefault: false, sendDate: false, _removedConnection: false, _removedContLen: false, _removedTE: false, strictContentLength: false, _contentLength: 0, _hasBody: true, _trailer: '', finished: true, _headerSent: true, _closed: false, socket: [TLSSocket], _header: 'GET /search?term=lex+fridman+podcast&media=podcast&entity=podcast&country=es HTTP/1.1\r\n' + 'Accept: application/json, text/plain, */*\r\n' + 'User-Agent: axios/0.27.2\r\n' + 'Host: itunes.apple.com\r\n' + 'Connection: keep-alive\r\n' + '\r\n', _keepAliveTimeout: 0, _onPendingData: [Function: nop], agent: [Agent], socketPath: undefined, method: 'GET', maxHeaderSize: undefined, insecureHTTPParser: undefined, joinDuplicateHeaders: undefined, path: '/search?term=lex+fridman+podcast&media=podcast&entity=podcast&country=es', _ended: false, res: null, aborted: true, timeoutCb: [Function: emitRequestTimeout], upgradeOrConnect: false, parser: [HTTPParser], maxHeadersCount: null, reusedSocket: false, host: 'itunes.apple.com', protocol: 'https:', _redirectable: [Circular *1], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false, [Symbol(kBytesWritten)]: 0, [Symbol(kNeedDrain)]: false, [Symbol(corked)]: 0, [Symbol(kOutHeaders)]: [Object: null prototype], [Symbol(errored)]: null, [Symbol(kHighWaterMark)]: 16384, [Symbol(kRejectNonStandardBodyWrites)]: false, [Symbol(kUniqueHeaders)]: null, [Symbol(kError)]: undefined }, _currentUrl: 'https://itunes.apple.com/search?term=lex+fridman+podcast&media=podcast&entity=podcast&country=es', _timeout: null, [Symbol(shapeMode)]: true, [Symbol(kCapture)]: false } }
```

### Additional Notes

OS: DSM 7.2.2. 
I have tried searching several podcasts with the same result. I have copied the iTunes URLs that appear in the logs effectively arriving at the podcast link on the platform.

**Comment by nichwall** [comment]
The search is timing out. Are you using a proxy to access the internet or have you changed anything for DNS or something else with your network?

If you have podcasts you have already set up in ABS, do those let you download episodes?

**Comment by wisark** [comment]
> The search is timing out. Are you using a proxy to access the internet or have you changed anything for DNS or something else with your network?
> 
> If you have podcasts you have already set up in ABS, do those let you download episodes?

Thanks for your answer! I am using synology.me reverse proxy, set up following the instructions in "Synology NAS Reverse Proxy Setup (DSM 7+/Quickconnect)" section of GitHub page. I can access to the UI through this reverse proxy. I've just tried to search for podcasts directly from my localhost:13378 but with the same negative result.

I don't have any podcast previously downloaded but I'm going to try that and see if it works. I assume I'll have to put a podcast in /podcasts/ folder, scan library and try to download more episodes.

**Comment by advplyr** [comment]
I've never used Synology but this is most likely a network issue. Have you tried this: https://github.com/advplyr/audiobookshelf/issues/3240#issuecomment-2269152458

**Comment by wisark** [comment]
I've solved it trying that solution. Thank you so much!
