### ISSUE TITLE
[Bug]: config/rss-feeds display distorted feed images

### ISSUE THREAD

**Issue by PhantomPhoton** [advplyr/audiobookshelf#3748]
### What happened?

When I go to config/rss-feeds, I see distorted cover images that make it difficult to use the list

![Screenshot 2024-12-26 at 12 03 51 AM](https://github.com/user-attachments/assets/c78e8855-f771-43a1-ac26-64eda9902a37)

### What did you expect to happen?

I expected to see the normal cover images

### Steps to reproduce the issue

1. Have active RSS feeds
2. Go to settings -> Rss Feeds

### Audiobookshelf version

v2.17.5

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Safari

**Comment by nichwall** [comment]
I'm not able to reproduce this. Do you see images with weird dimensions like this anywhere else?

Have you adjusted the zoom level of the browser or within ABS? Do you have any browser plugins installed, and if so does this go away when you disable all plugins?

**Comment by nichwall** [comment]
I do not have any Apple devices, I was testing with Firefox.

Thanks for helping narrow it down to the h-full property.

**Comment by nichwall** [comment]
Does adding a second RSS feed make the images half as tall? So the same vertical space is used, but split between two images?
