### ISSUE TITLE
[Enhancement]: Allow adjusting runtime log level without changing NODE_ENV

### ISSUE THREAD

**Issue by PhantomPhoton** [advplyr/audiobookshelf#3749]
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

Add environment variable to control the displayed log level in [Logger.js](https://github.com/advplyr/audiobookshelf/blob/master/server/Logger.js)

### Why would this be helpful?

I have a very large amount of podcasts and loading the library is very slow. I wanted to enable the [benchmark](https://github.com/advplyr/audiobookshelf/blob/master/server/Database.js#L209) on the database layer to view the queries and their latency, however, the logger will only log [INFO](https://github.com/advplyr/audiobookshelf/blob/master/server/Logger.js#L12) level messages unless running as `dev`.

I tried adjusting the `NODE_ENV` in the docker image and it crashed due to not being able to load the dev environment. 

```
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module './dev'
Require stack:
- /index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/index.js:6:18)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:173:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/index.js' ]
}

Node.js v20.18.1
```

### Future Implementation (Screenshot)

Check for `process.env.LOG_LEVEL` before setting `this.logLevel` in [Logger.js](https://github.com/advplyr/audiobookshelf/blob/master/server/Logger.js)

### Audiobookshelf Server Version

 v2.17.5

### Current Implementation (Screenshot)

As the log lines are currently missing, not sure there's anything I can add here.

**Comment by nichwall** [comment]
The log level can be set to `WARN`, `INFO`, or `DEBUG` in the server settings on the Logs page.

You can also manually change the log level in the database in the `settings` table.

**Comment by nichwall** [comment]
No worries, there are a few things like this that would be good to expose as an environment variable, it just hasn't been exposed since configuration should (currently) be done through the web UI.
