### ISSUE TITLE
[Bug]: RSS Feed Preview has empty table when viewing feed

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf#3752]
### What happened?

When viewing an RSS feed in the server settings, clicking on a feed with more than one file shows an empty table. If only one file is included in the RSS feed, the table is displayed correctly. The correct number of rows are displayed, they are just not populated.

Single track feed (correctly rendered):
![Screenshot from 2024-12-26 22-57-49](https://github.com/user-attachments/assets/a0e9e131-3226-4b59-af7f-6ccb50c60199)

Multi track feed (single book, 13 tracks):
![Screenshot from 2024-12-26 22-57-56](https://github.com/user-attachments/assets/c50ae2c0-3865-4447-8f4c-a539e90c4fd0)

### What did you expect to happen?

RSS Feed tables to show all files in the preview.

### Steps to reproduce the issue

1. Create RSS feed with more than one file (series or multi-track file)
2. Navigate to RSS Feed view in the server settings
3. Click on an RSS feed with more than one file

### Audiobookshelf version

f3e9cfb

### How are you running audiobookshelf?

Built from source

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### Additional Notes

This is after the Feed models were rewritten, after server version 2.17.5

**Comment by advplyr** [comment]
Thanks, this was specific to multi-track audiobooks that didn't have matching chapters.
