### ISSUE TITLE
[Enhancement]: Update Server Via Frontend/UI

### ISSUE THREAD

**Issue by MrBearedJoe** [advplyr/audiobookshelf#3758]
### Type of Enhancement

None

### Describe the Feature/Enhancement

When an update is available, the admin/root user has a front-end menu to be able to update to the next or newest version.

### Why would this be helpful?

Would make the client a bit more streamline?

### Future Implementation (Screenshot)

![Screenshot (2)](https://github.com/user-attachments/assets/ba3b39a6-8892-48bd-b685-ae7fc7356a98)

### Audiobookshelf Server Version

v2.17.2

**Comment by nichwall** [comment]
I think this is outside of the scope of ABS. ABS can't really control this, especially within a container environment like docker.

For example:
- Docker/containers, update your compose
- Windows, updates are already handled by the external tray app
- Linux, update using your package manager
- From source, pull code and rebuild

**Comment by MrBearedJoe** [comment]
Oh i see. was a thought :)
