### ISSUE TITLE
[Bug]: Authors view in reverse order

### ISSUE THREAD

**Issue by Masterz69** [advplyr/audiobookshelf#3763]
### What happened?

See authors sorted in reverse in both (First Last) & (Last, First).
As well IMHO when choosed (Last, First) to show names exactly as "Last, First", not "First Last".

### What did you expect to happen?

Authors sorted from A to Z.

### Steps to reproduce the issue

1. Just installed ABS and added Library.

### Audiobookshelf version

2.17.6

### How are you running audiobookshelf?

Windows Tray App

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Additional Notes

in ABS APP authors sorint is reverse too.

**Comment by nichwall** [comment]
Is the little arrow pointing up or down? That is how you sort ascending or descending.

![Screenshot_20241231-064547.png](https://github.com/user-attachments/assets/7dac5f85-09a2-49f8-93fa-c09195e4f30e)

**Comment by Masterz69** [comment]
Oops. Thanks for pointing.
