### ISSUE TITLE
[Enhancement]: Disable Watcher

### ISSUE THREAD

**Issue by mirisbowring** [advplyr/audiobookshelf#378]
### Describe the feature/enhancement

Hi,

i would like to have the option to disable the file watcher. I want to refresh the Library manually.
I am using unraid and it seems like my disks are spun up often due to the watcher.

Regards

**Comment by Jdiesel87** [comment]
Maybe the option to disable completely or run a scheduled scan?

**Comment by advplyr** [comment]
Added in [v1.7.0](https://github.com/advplyr/audiobookshelf/releases/tag/v1.7.0)

Disable watcher for entire server:

![image](https://user-images.githubusercontent.com/67830747/155863020-53d97dbb-3279-4bea-8184-ceea8d75d585.png)

Or for a specific library:

![image](https://user-images.githubusercontent.com/67830747/155863035-197fcf8f-df65-4031-87df-3103aa7dc29c.png)

Note: this setting requires a restart of your server to take effect

A scheduled scan should be a separate issue if anyone wants that feature.
