### ISSUE TITLE
[Enhancement]: Add stats to books read

### ISSUE THREAD

**Issue by tvories** [advplyr/audiobookshelf#383]
### Describe the feature/enhancement

I think it would be nice if you had some stats on the last readthrough.  Add some of the following:

Start Date
Read/Completed Date
Number of read-throughs

I am sure there are more nice stats to have, but that's what I can think of right now.

**Comment by advplyr** [comment]
How do you think number of read-throughs would be calculated? I think there are a lot of edge cases in making that calculation that could make it a tricky stat to keep. Also, do you know if tracking # of read-throughs is valuable to many people?

I can see the value in showing start and complete date though, which is already stored so it is a matter of improving the display.

**Comment by advplyr** [comment]
I know I saw the number of read-throughs in some book related software recently, so people definitely use it.

Where do you see the start and completion date data being shown? On the stats recent sessions, or do you go to the config accounts page?

**Comment by tvories** [comment]
I would think on the book page itself.  So where the book description is.

**Comment by advplyr** [comment]
In 1.7.2

![image](https://user-images.githubusercontent.com/67830747/156902655-07023185-fd3a-4e9b-bd34-d55cefc760d1.png)
![image](https://user-images.githubusercontent.com/67830747/156902682-41227353-a3c0-4d58-b183-4fa947856e08.png)

Doesn't look great, but does the job. I noticed a bug I think when I marked a book as read I had to refresh for it to display correctly.
