### ISSUE TITLE
[Enhancement]: Library Specific Settings

### ISSUE THREAD

**Issue by Thoroslives** [advplyr/audiobookshelf#387]
### Describe the feature/enhancement

As discussed in Discord.

The ability to have settings specific to the library including scanner settings.

e.g. Having the ability to  differ scanner and have square covers in a podcast library as compared to the audiobook library.

**Comment by advplyr** [comment]
Square covers moved to library specific setting in [2.1.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.3)

Some other settings there now too and will be moving more settings in future updates.
