### ISSUE TITLE
[Enhancement]: underscores to be treated like spaces

### ISSUE THREAD

**Issue by plague-doctor** [advplyr/audiobookshelf#388]
### Describe the feature/enhancement

This is an awesome piece of software. Thanks a lot for development.

Is there a reason why we have to use spaces in the filenames? This is a horrible idea to have them instead of underscores. From a scripting perspective spaces in the filenames are nightmares...

**Comment by advplyr** [comment]
You can choose not to use your folder names as metadata by enabling the server setting for prefer audio file metadata or prefer OPF metadata.
I don't think handling spaces in filenames is a problem anymore. It's just part of coding with file systems.
