### ISSUE TITLE
[Rnhancement]: improved sub folder management

### ISSUE THREAD

**Issue by kjames2001** [advplyr/audiobookshelf#391]
Kindly allow sub folders in secondary folders under root to be recognized as different books instead of chapters.

**Comment by kjames2001** [comment]
im asking because right now all the books for 1 author are audio tracks of 1 book named as the author. 

i wanted to change folder structure, but apparantly readarr doesnt allow it, or i just cant figure out how to do it.

**Comment by kjames2001** [comment]
i do not have loose files under authors folders.

still its not working as intended, or give me that option to choose.

**Comment by advplyr** [comment]
Great, glad it is working. If you have details on which special characters that is something we should fix since all valid characters in a filename are supported.

**Comment by kjames2001** [comment]
[رجل الخزانة] It was one of Stephen Kings books, named this

**Comment by kjames2001** [comment]
apparently it reads from right to left, and its copied directly from readarr (i have absolutely no idea what language it is).

**Comment by advplyr** [comment]
Ah okay, well if whoever speaks that language brings this up we can address it then.
