### ISSUE TITLE
[Enhancement]: add sorting in series view

### ISSUE THREAD

**Issue by KoMa1012** [advplyr/audiobookshelf#392]
### Describe the feature/enhancement

When in the Library view Audiobooks can be sorted by e.G. title:
![image](https://user-images.githubusercontent.com/2759494/157107470-0fa76f10-fef0-4bd4-8c9e-acd735fdcea8.png)

But when in Series view there is no option for sorting:
![image](https://user-images.githubusercontent.com/2759494/157107698-b3f82d73-68b3-4e85-a177-739ddc2e5944.png)

suggestion:

1. add sorting within series, this series for example has 50 books per "season" aka series with multiple seasons. It's ok to keep every season as a series, because I assume this book series is a cornercase.
2. add sorting of series

**Comment by hobesman** [comment]
I just wanted to add, that filtering within a series might also be nice. For example where a series has multiple authors and you want to filter to show a specific author's contributions.

**Comment by advplyr** [comment]
This was added a couple versions ago
