### ISSUE TITLE
[Enhancement]: Show unmatched books

### ISSUE THREAD

**Issue by jt196** [advplyr/audiobookshelf#395]
### Describe the feature/enhancement

Plex, while not being the best audiobook library, does allow the users to work through the books that haven't had a successful metadata match. 

In terms of implementation, I'd love to see the top menu filter with an "Unmatched" option, so the user could work through and match up any books that haven't been identified by the metadata search agent.

**Comment by cyberkoala** [comment]
Another thought, maybe options to filter by books with fields missing? like 'no cover, no description, narrator etc'. It might be a good way too bring up both unmatched books, and books that may have matched an entry with incomplete information.

**Comment by advplyr** [comment]
In [v2.0.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.1) you can now filter for books with missing fields.
