### ISSUE TITLE
[Enhancement]: Fuzzy Matching 

### ISSUE THREAD

**Issue by jt196** [advplyr/audiobookshelf#396]
### Describe the feature/enhancement

Adding a new library to your set up, and I'm finding that the match patterns are quite a lot stricter than I think they have to be. 

e.g. 

## Dots after abbreviated middle names: 

- James SA Corey + Expanse book title **no match**
- James S.A. Corey + Expanse book title **match**

## Book Title Match, author different

- Benedict Cumberbatch Reads Sherlock Holmes' Rediscovered Railway Stories + Arthur Conan Doyle **no match**
- Benedict Cumberbatch Reads Sherlock Holmes' Rediscovered Railway Stories + John Taylor (the actual author!) **match**. 

I get the latter, but it's a very long name and seems like there should at least return some results here.

The Plex audiobooks metadata agent returns with a percentage match based on several criteria. If you're worried about your auto-matching breaking with fuzzy matching, why not just have a threshold?

**Comment by jt196** [comment]
@Albuca, I think the [Audnexus Plex metadata agent](https://github.com/djdembeck/Audnexus.bundle) does a pretty good job of polling the Audible API - I think it's less strict than your search. Don't know if you're familiar with Python, but it's a pretty simple setup with just a few files. Think they use some sort of [scoring system](https://github.com/djdembeck/Audnexus.bundle/blob/main/Contents/Code/search_tools.py) to evaluate the returned results.

**Comment by advplyr** [comment]
@jt196 Audnexus has been being used for all audible searches for a few versions now

**Comment by jt196** [comment]
@advplyr, great stuff. Did double check the test searches above and neither returned results. Guess the Sherlock one isn't the biggest deal, but James SA Corey. Is there a way to dial down the fuzziness? Even if it didn't auto match below a certain threshold that would be useful in the manual search to have less accurate results returned.

**Comment by advplyr** [comment]
This was implemented pretty well for the next release. PR https://github.com/advplyr/audiobookshelf/pull/2099

**Comment by advplyr** [comment]
Added in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)
