### ISSUE TITLE
[Enhancement]: Scan only Author folders

### ISSUE THREAD

**Issue by ItsNoted** [advplyr/audiobookshelf#397]
### Describe the feature/enhancement

I realized after using this for a while that I had made several changes only to have them all reverted after doing a full scan again... It would be nice to be able to only scan a author folder so after removing books, it doesn't re add the ones I don't want after doing the scan again... Maybe there is a better way to do what I am trying to do? Really loving this project!

**Comment by advplyr** [comment]
I'm not sure what you mean here. If a scan is writing over data already saved on the item then that sounds like a bug, are you able to reproduce that?
