### ISSUE TITLE
[Enhancement]: ID3 POPM or equivalent from Google Books

### ISSUE THREAD

**Issue by yabdali** [advplyr/audiobookshelf#398]
### Describe the feature/enhancement

A typical approach for prioritizing my reading list is going through the ratings of each audio book.  I understand that using ID3 POPM tag is not straight forward.  However, would you please consider adding this through abs as I currently have to lookup the rating for each audio book before deciding which one to read? Thanks for your continuous support

**Comment by advplyr** [comment]
I haven't seen POPM used for audiobooks before. What does the data look like? Is this a number

**Comment by Alestrix** [comment]
Is this the request to upvote if I like to see a rating system or #701? I'd really like to be able to record how much I (dis)liked an audiobook, also to let other family members know about it.
