### ISSUE TITLE
[Enhancement]: Subsonic API

### ISSUE THREAD

**Issue by plague-doctor** [advplyr/audiobookshelf#399]
### Describe the feature/enhancement

Guys, the longer I use abs the more I like it. It is awesome!
I would really like to be able to listen to my collection on other devices via Subsonic streaming.

**Comment by Jdiesel87** [comment]
Not meaning to be critical of your request but I am genuinely curious to what benefits using a subsonic app would be? Is there something missing from the AudioBookShelf apps or an app for a specific device that is not yet available?

**Comment by plague-doctor** [comment]
I've got multiple Raspberry PIs running either kodi or subs (on headless). 
Also, from a freedom standpoint, there are ton of apps which could be used instead of AudioBookShelf app if someone prefers. (Not that there's anything wrong with the AudioBookShelf app).
Implementing Subsonic API would make AudioBookShelf more accessible and versatile.

**Comment by Jdiesel87** [comment]
Alright that makes sense and I see the appeal.

Thinking long term would it not make more sense to incorporate a REST API and have it well documented so other apps like Kodi can connect natively to AudioBookShelf rather than adapting to another platforms API?

Maybe something like Swagger. This could open up a magnitude of options for other integrations in addition to just requesting streams.

**Comment by nahsi** [comment]
> Alright that makes sense and I see the appeal.
> 
> Thinking long term would it not make more sense to incorporate a REST API and have it well documented so other apps like Kodi can connect natively to AudioBookShelf rather than adapting to another platforms API?
> 
> Maybe something like Swagger. This could open up a magnitude of options for other integrations in addition to just requesting streams.

Subsonic is more like a "standard" API for streaming audio. A lot of clients support it and a lot of servers implement it.

If audiobookshelf implements it I can listen to music provided by https://github.com/navidrome/navidrome and podcasts/audiobooks provided by abs in the same app on my phone, or on Kodi, without installing and configuring different applications.

It is usually better to implement a popular standard than to create your own.

**Comment by DDriggs00** [comment]
I'm not sure about this. While supporting an existing universal standard is nearly always a good idea, Audiobooks as a medium are substantially different from music. You would definitely need to see whether the subsonic api was capable of conveying audiobooks well enough to be worth using.

**Comment by mantaBracket** [comment]
Might be worth reconsidering since Homeassistant/Musicassistant recently added support for streaming Audiobooks via subsonic https://github.com/music-assistant/server/releases/tag/2.4.0
