### ISSUE TITLE
Request: Order by Volume # use absolute numbering

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf#40]
Currently when ordered by Volume # it comes out as:   (SQL default?)
1
10
11
2
20

Absolute numbering would be more useful for the user, as:
1
2
2.5
3

Using Real numbers to account for prequels & side stories.

**Comment by advplyr** [comment]
Yep, this was a bug. Volume number is not stored as an actual number intentionally, but the sort should always treat it as a number. This is fixed in `v1.1.11`
