### ISSUE TITLE
[Enhancement]: Labels/Tags

### ISSUE THREAD

**Issue by Kussie** [advplyr/audiobookshelf#402]
### Describe the feature/enhancement

Essentially this would be have similar to the labels features in Plex or even as a simple tagging system that is fairly common amongst these sort of applications. 

What i would like to see is the ability to place a label/tag on collections/series/individual books, these labels could then be used for searching and another level of pseudo organisation especially in the web app.  Ideally you would then be able to use these labels to control what other users can see as well.  At the moment we are limited to sharing on a per library basis, this feature would allow some greater flexibility in what is shared without having to break all of the media up into a bunch of libraries. As per Plex each user account could then have two additional fields, "Labels to include" and "Labels to exclude".  

- Labels to include: Would limit the user to only see content with the selected tags.
- Labels to exclude: Any content with any of these tags will not be shown to that user.

**Comment by Jdiesel87** [comment]
Just noticed this after creating a new discussion. I'm going to cross post it for now

https://github.com/advplyr/audiobookshelf/discussions/404

**Comment by M-archand** [comment]
`Labels to exclude: Any content with any of these tags will not be shown to that user.`

I would also love this feature. I use it a lot in Plex. It's a lot easier to just exclude 1 tag (e.g. _private)_ rather than allowing every single tag except _private_.

**Comment by Nuuki9** [comment]
> `Labels to exclude: Any content with any of these tags will not be shown to that user.`
> 
> I would also love this feature. I use it a lot in Plex. It's a lot easier to just exclude 1 tag (e.g. _private)_ rather than allowing every single tag except _private_.

Agreed. In Plex I have a mixture of adults and children using it and I use a couple of tags to ensure both groups only see things of interest/suitability - children only see things tagged "Kids" or "Kids Only" and adults exclude "Kids Only". That way I can have things appear for one, other or both groups of users.

I'd love to be able to do something similar with ABS, as about half my library is children's audiobooks. I know I could split into two libraries, but then everything of interest to both (e.g. Harry Potter) has to sit in one or the other library and be inaccessible to some interested users.

**Comment by advplyr** [comment]
There is another feature request specifically for denying user access based on tags #1545

The way the data model is setup now I don't think tags would be added to series/collections/etc. When restricting access based on tags these should be on library items (books or podcasts) otherwise we have to add logic that loops through books in a series and restrict each book. Maybe we do that but you could just bulk tag the books in the series.

**Comment by advplyr** [comment]
#1545 was added in a previous release. With the batch edit function you can easily add a tag to all books in a collection/series if you wanted.
