### ISSUE TITLE
[Bug]: Upload Page Fields not selectable

### ISSUE THREAD

**Issue by jflattery** [advplyr/audiobookshelf#406]
### Describe the issue

On the uploads page, the fields under "Book Files", namely the `filename` field is not able to be selected. These fields; `filename`, `size`, and `type` should be able to be selected by the user.

### Steps to reproduce the issue

1. Visit the  `/upload` page
2. Choose a file or folder to be uploaded
3. Expand the `Book Files` section
4. Attempt to select the filename

### Audiobookshelf version

v1.7.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.3)
