### ISSUE TITLE
[Enhancement]: Multiple Series

### ISSUE THREAD

**Issue by geekedtv** [advplyr/audiobookshelf#409]
### Describe the feature/enhancement

I sometimes like to add books to more than one series other than that native series that the book might belong to. Is there any chance of making this possible in a future release? 

I have been vigorously testing the app with over 1200 audiobooks and so far it has been withstanding everything I throw at it!

**Comment by mason-xx** [comment]
Isn't this usecase what collection are for?

**Comment by Drumhavoc** [comment]
I like this idea, the example I am working with is Joe Abercrombie, his first 3 books are in the series 'The First Law' the next 4 'First Law World' and the last 3 are 'The Age of Madness'. They are all part of the 'The First Law' series but are their own sub category.  It would be great to see them in both places so I can see what should be next in the series while also keeping their sub series intact.  Collections are cool, but they don't view and navigate like the series section which is really nice

**Comment by advplyr** [comment]
In [v2.0.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.1) books can belong to multiple series!
