### ISSUE TITLE
Request: User Level Mass-Mark Read

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf#41]
Now that the Mass Mark Read flag is available on the home screen when doing a multi-select, can multi-select be made available to the user level accounts and given that ability?

Here's a screenshot of a user mousing over a title, but the multi-select option is not available.
![image](https://user-images.githubusercontent.com/4451365/133839724-3ad2d97d-a722-4e50-983b-cdeba4217e7f.png)

**Comment by advplyr** [comment]
Nice catch again, this is fixed now in `v1.1.11`
