### ISSUE TITLE
[Bug]: Text overlap on Collection pages

### ISSUE THREAD

**Issue by geekedtv** [advplyr/audiobookshelf#410]
### Describe the issue

If book titles are too long, they over lap with the duration text on collection pages. See screenshot for example.

![raw](https://user-images.githubusercontent.com/57927413/157895847-de9b3be7-7689-4400-8528-776e47c3aa4d.png)

### Steps to reproduce the issue

1. 

### Audiobookshelf version

1.7.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.3)
