### ISSUE TITLE
[Bug]: unable to install via deb file

### ISSUE THREAD

**Issue by Benchwork** [advplyr/audiobookshelf#412]
### Describe the issue

following the instructions from the website to install on debian. I was unable to successfully install v1.7.1 
on a hunch I checked the github and saw there was a newer version of v1.7.2. and tried to install that one as well.
both failed to install of the exact same point.

this was installed on a fresh vm for testing. 

steps shown below 

Any assistance would be much appreciated.

### Steps to reproduce the issue

root@books ~# wget https://advplyr.github.io/audiobookshelf-ppa/audiobookshelf_1.7.2_amd64.deb
--2022-03-12 18:59:18--  https://advplyr.github.io/audiobookshelf-ppa/audiobookshelf_1.7.2_amd64.deb
Resolving advplyr.github.io (advplyr.github.io)... 185.199.109.153, 185.199.111.153, 185.199.110.153, ...
Connecting to advplyr.github.io (advplyr.github.io)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15591114 (15M) [application/octet-stream]
Saving to: 'audiobookshelf_1.7.2_amd64.deb'

audiobookshelf_1.7. 100%[===================>]  14.87M  13.9MB/s    in 1.1s

2022-03-12 18:59:19 (13.9 MB/s) - 'audiobookshelf_1.7.2_amd64.deb' saved [15591114/15591114]

root@books ~# sudo apt install ./audiobookshelf_1.7.2_amd64.deb
-bash: sudo: command not found
root@books ~# apt install ./audiobookshelf_1.7.2_amd64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'audiobookshelf' instead of './audiobookshelf_1.7.2_amd64.deb'
The following NEW packages will be installed:
  audiobookshelf
0 upgraded, 1 newly installed, 0 to remove and 31 not upgraded.
Need to get 0 B/15.6 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /root/audiobookshelf_1.7.2_amd64.deb audiobookshelf amd64 1.7.2 [15.6 MB]
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 29262 files and directories currently installed.)
Preparing to unpack .../audiobookshelf_1.7.2_amd64.deb ...
Existing config found.
AUDIOBOOK_PATH=/usr/share/audiobookshelf/audiobooks
  METADATA_PATH=/usr/share/audiobookshelf/metadata
  CONFIG_PATH=/usr/share/audiobookshelf/config
  FFMPEG_PATH=/usr/lib/audiobookshelf-ffmpeg/ffmpeg
  FFPROBE_PATH=/usr/lib/audiobookshelf-ffmpeg/ffprobe
  PORT=7331
Starting FFMPEG Install
--2022-03-12 18:59:51--  https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
Resolving johnvansickle.com (johnvansickle.com)... 107.180.57.212
Connecting to johnvansickle.com (johnvansickle.com)|107.180.57.212|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40881016 (39M) [application/x-xz]
Saving to: 'ffmpeg-git-amd64-static.tar.xz.2'

ffmpeg-git-amd64-st 100%[===================>]  38.99M  12.4MB/s    in 3.3s

2022-03-12 18:59:55 (11.9 MB/s) - 'ffmpeg-git-amd64-static.tar.xz.2' saved [40881016/40881016]

tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
dpkg: error processing archive /root/audiobookshelf_1.7.2_amd64.deb (--unpack):
 new audiobookshelf package pre-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 /root/audiobookshelf_1.7.2_amd64.deb
Enumerating objects: 1435, done.
Counting objects: 100% (1435/1435), done.
Compressing objects: 100% (877/877), done.
Writing objects: 100% (1435/1435), done.
Total 1435 (delta 102), reused 1435 (delta 102)
N: Download is performed unsandboxed as root as file '/root/audiobookshelf_1.7.2_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
Goot@books ~#

### Audiobookshelf version

1.7.2

### How are you running audiobookshelf?

Debian/PPA

**Comment by Benchwork** [comment]
I also installed ffmpeg from repo to see if it could help, it did not .

**Comment by Quietus** [comment]
If you're using the .Deb directly you should use dpkg not apt (apt has fetched from the repositories as can be seen from your log).  Your issue appears to be a leftover file - when downloading ffmpeg-git-amd64-static.tar.xz the logs show Saving to: 'ffmpeg-git-amd64-static.tar.xz.2'

It should save to the same filename unless it cannot (E.g. due to an existing file of the same name).

**Comment by Benchwork** [comment]
thank you for your reply.  I took your advice and installed via dpkg 
Please note that I am not downloading and installing ffmpeg-git-amd64-static.tar.xz  this seems to be part of the install process of audiobookshelf_1.7.2_amd64.deb and it does not check to see if it has ever been downloaded before. 

 ffmpeg-git-amd64-static.tar.xz keeps downloading to /usr/lib/audiobookshelf-ffmpeg
I  attempted to run the installer from that directory -- no change
copied ffmpeg-git-amd64-static.tar.xz to the same directory as audiobookshelf_1.7.2_amd64.deb -- no change

attempted to manually tar -xf ffmpeg-git-amd64-static.tar.xz -- and it failed.
it seemed that I was 100% blocked from installing.  

on a hunch I googled tar (child): xz: Cannot exec: No such file or directory and the answer was to install xz-utils

after that everything installed fine. 

thank you!!
