### ISSUE TITLE
[Enhancement]: Automatically convert mp3 of FLAC to m4b format

### ISSUE THREAD

**Issue by baloodusudouest** [advplyr/audiobookshelf#413]
### Describe the feature/enhancement

Hi,

It will be great to have an "input" folder with mp3 download from 1 side, and when scan this folder, automatically convert it to m4b format on an output folder with the folder structure wanted (for ex: Author, Series, Book.m4b)

**Comment by DDriggs00** [comment]
I would recommend against automatically doing any kind of lossy->lossy transcode even with audiobooks, where it matters substantially less.

**Comment by advplyr** [comment]
I think this is out of the scope of this project, but we will be improving and expanding on the tool that makes m4b's so it may come close to what you are asking here.
I could see a feature in the future for bulk converting m4b's
