### ISSUE TITLE
[Bug]: Speed changes back to 1.0x between files or sessions UI shows set speed on web player

### ISSUE THREAD

**Issue by riffy13** [advplyr/audiobookshelf#419]
### Describe the issue

The speed changes back to 1.0x between files or sessions, but the UI doesn't change on web player. Shows that it's playing at the rate you set & even the time is showing the faster time for how long is left, but it plays at 1x speed. Same thing happens if you exit & come back to resume playing. UI shows the old set speed, but it's only playing at 1x speed. 

### Steps to reproduce the issue

1. Set speed on web player. (Chrome)
2. On the next file (such as each chapter is a separate mp3) the UI will show the set speed, but it's only playing at 1x speed.
3. The same thing happens if you exit & come back & hit play.
4. UI shows old set speed but plays at 1x speed.

### Audiobookshelf version

v1.7.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This is fixed in [v2.0.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.2)
