### ISSUE TITLE
[Enhancement]: Read List

### ISSUE THREAD

**Issue by burnshroom** [advplyr/audiobookshelf#422]
### Describe the feature/enhancement

Ever see a book you wanted to read and added it to your collection, but then when you are ready to read it you forgot what book it was?

A read list would be great in app.  Something like a queue but a place where you can store titles for future consumption.  
Ideally it can be on the homepage along side your continue reading section.

**Comment by jpzbkk** [comment]
I really like the idea of queue and being able to sort it.  Very similar functionality to the collections.

**Comment by advplyr** [comment]
What sort of functionality are you thinking would be here that is not in collections now?

**Comment by burnshroom** [comment]
Not that I have used Collections much, but my assumption on Collections is I can collect all the Star Wars titles under one umbrella no matter the author or series.

The idea of a read list.  Say I am currently listening to a book that is 15 hours long and at some point I find I book I am interested in.  At present, the chances are high by the time I am done with current book I will have forgotten what it was.  I suppose I could make a "To Read" collection, but ideally a read list connotation seems better.  And as I listen to whichever book it would automatically remove from the list... 

But in the interim I will play around with collections to see what it offers.

**Comment by DDriggs00** [comment]
Eventually, this could be synced with the Goodreads "Want to read" list.

**Comment by Cobolt78** [comment]
Thumbs up for this Enhancement 👍

**Comment by nichwall** [comment]
Now that user-specific playlists have been added (as of 2.2.6), would this enhancement be considered complete?

**Comment by advplyr** [comment]
@nichwall Yeah good call. I'm sure there will be a lot of ideas on how to improve playlists but they can be put into separate feature requests.
