### ISSUE TITLE
[Enhancement]: Option to disable wood paneling everywhere

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf#424]
### Describe the feature/enhancement

Similar to the "alternative library bookshelf view" but the option would remove the wood background from everywhere in the application. Mobile app as well.

**Comment by Jdiesel87** [comment]
Check out the texture button in the bottom right corner of the webclient. Don't think it is possible on the mobile app yet.

**Comment by SenorSmartyPants** [comment]
After I enabled experimental features the texture button appeared. Nice to have options, but there isn't a no texture option.

**Comment by Jdiesel87** [comment]
Ah I though the dark one was pure black but I guess there still is a pattern there. No texture would be great

**Comment by millermarkj** [comment]
The wood paneling is stored in the docker container as `/client/dist/textures/wood_default.jpg`. If you volume mount that to `/dev/null`, you get a much cleaner background. This doesn't affect the app, unfortunately.

**Comment by advplyr** [comment]
Using the alternate bookshelf view now disables the wood texture everywhere in [v2.0.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.12)
