### ISSUE TITLE
[Bug]: Unable to download podcast episodes if the podcast already exists

### ISSUE THREAD

**Issue by Zibbp** [advplyr/audiobookshelf#427]
### Describe the issue

**Occurs when building from the master branch.**

When attempting to download a new podcast episode through the web interface while already having some episodes downloaded it will error with the following:
```
[2022-03-29T01:51:17.768Z] ERROR: [PodcastController] Attempt to create podcast when folder path already exists "/podcasts/Darknet Diaries"
```

Note - This only happens when importing an existing podcast and not when adding a new podcast via the UI and downloading episodes.

### Steps to reproduce the issue

1. Build current master branch container.
2. Create a library with an existing podcast.
3. Attempt to download an episode *that you do not have* from the imported podcast.

### Audiobookshelf version

master

### How are you running audiobookshelf?

Docker

**Comment by jflattery** [comment]
Reproduced and confirmed on my end.

**Comment by advplyr** [comment]
Are you attempting to create a new podcast from the "Search" page when the podcast already exists?

I think you should be matching the podcast instead to set the RSS feed in the details, then on the podcast landing page there is a search for episodes there.

**Comment by advplyr** [comment]
Podcast episode downloader was removed from the form to create a new podcast.
This shouldn't be an issue anymore since you can use the Match tab to match existing podcasts you have.
