### ISSUE TITLE
[Enhancement]: Please add an option to Collapse by Author

### ISSUE THREAD

**Issue by Versalight** [advplyr/audiobookshelf#429]
### Describe the feature/enhancement

Please consider adding a "Collapse by Author" tickbox or option in the Library tab
which would show the authors in alphabetical order (with maybe the first available book cover as an image).

Clicking on the author would then either show all of the available books by said author or the collapsed series.
In case of multiple authors, the easiest resolution would be to defer to the first author in the list.

Collapse by author would help avoid visual clutter in large libraries,
and would also more closely mimic the actual library directory structure.

**Comment by advplyr** [comment]
There is an authors page in experimental and completed in v2 not yet released. The authors page will show the number of books and clicking on an author will filter by those books. Authors will also support photos in v2.
Is this the same thing you are asking basically?

**Comment by Versalight** [comment]
Pretty much that, yeah!

**Comment by advplyr** [comment]
Authors page included in [v2.0.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.1)!
