### ISSUE TITLE
Request: Turn Off Automatically Empty Trash

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf#43]
Anyone using this with remote mounted storage will likely get frustrated if they start up their machine and the remote mount doesn't come up, then the scanner can't find the files so it removes the book from the library and then pairs it as something new once reconnected.

Please add an option to turn off the Automatically Empty Trash on scan in the Settings.

**Comment by advplyr** [comment]
Good point. Instead of automatically removing items it should flag them as having missing files, similar to other media platforms.

**Comment by advplyr** [comment]
This update warrants a bit of an explanation. 

As of `v1.1.12` it functions like this:

* If a scan occurs and an entire audiobook directory is not found, it will be marked as "isMissing".
    * Missing audiobooks will have disabled or not shown play & download buttons
* If the audiobook directory is added back it will be automatically detected and matched
    * **It must be the same directory**. Meaning the internal id (inode) assigned to that directory from the OS is the same. A copy of the directory or just a directory with the same name will most likely create a new audiobook.
 * If all the audio tracks are removed, but the directory is the same, this **will remove** the audiobook.
     * Audiobooks must have valid audio files to be considered an audiobook. This can be improved later if necessary.

**Comment by Budlyte** [comment]
Awesome. I'll test it later by moving a directory or something. I know this kind of thing drove me nuts and almost made me quit Ubooquity back when I used it and also ran a NAS.

How is the trash emptied now? Is there a button to force it and clear some memory?

Also, what file should I copy to backup the db? Or I'll just backup the whole container once/week maybe.

**Comment by Budlyte** [comment]
Alright, so to test I'm moving an author to a temp folder. Everything in the system is hardlinks, so the ID shouldn't be changing, correct? Either I'm mistaken or the system doesn't preserve listening progress through the missing and rediscovery.

Marked it read
![image](https://user-images.githubusercontent.com/4451365/134408174-2177eff5-a54f-4502-9017-fc32979dce9f.png)

Move it out, Scan, and get the 1 missing
![image](https://user-images.githubusercontent.com/4451365/134408267-459f6936-31b5-439f-9e6b-7f1595b9cb88.png)

Move it back, file system still shows it hasn't been modified in over a year
![image](https://user-images.githubusercontent.com/4451365/134408409-b5f11d04-c292-41b9-b460-267ef097a09f.png)

Next scan shows everything is there.
![image](https://user-images.githubusercontent.com/4451365/134408730-ed16b634-85af-43d0-a8d5-123fa3e25c86.png)

Reading status is reset though.
![image](https://user-images.githubusercontent.com/4451365/134408777-f4bb3940-4149-496c-8ba7-879253223e86.png)


- Relevant logs

[2021-09-22T19:22:23.616Z] INFO: [Server] Starting Scan
[2021-09-22T19:22:24.121Z] INFO: [Scanner] Audiobook "A Rational Zombie" is missing
[2021-09-22T19:22:24.927Z] INFO: [Scanned] Finished | 0 added | 0 updated | 0 removed | 1 missing | elapsed: 0:01
[2021-09-22T19:22:24.927Z] INFO: [Server] Scan complete
[2021-09-22T19:22:24.935Z] INFO: [Server] 2 Files Changed
[2021-09-22T19:22:25.120Z] INFO: [Server] Files changed result [ 3 ]
[2021-09-22T19:22:50.911Z] INFO: [Server] 2 Files Changed
[2021-09-22T19:22:50.992Z] INFO: [Scanner] Audiobook "A Rational Zombie" Scanned (380 MB) [13 hr 57 min]
[2021-09-22T19:22:50.996Z] INFO: [Server] Files changed result [ 1 ]
[2021-09-22T19:24:02.512Z] INFO: [Server] Starting Scan
[2021-09-22T19:24:03.648Z] INFO: [Scanned] Finished | 0 added | 0 updated | 0 removed | 0 missing | elapsed: 0:01
[2021-09-22T19:24:03.648Z] INFO: [Server] Scan complete

**Comment by advplyr** [comment]
I just tested this and the audio progress for me is not changed. Something strange is happening with the inode values your OS is assigning.
I think if we can get to the bottom of that, then we can solve this issue and the other one for you.

--
**On the topic of backups:**

I've been thinking on this. Now that covers will start to be stored locally, a system for backups becomes more important. I'm not sure how other media servers are handling this yet, so I'm going to look into that.

In the meantime you can do a full backup of the database by copying this directory `user/appdata/audiobookshelf/config/`, that directory will have 3 folders for `audioooks`, `settings`, and `users`.

**Comment by Budlyte** [comment]
Yeah, something's going on. Maybe it's permissions, I don't know yet, but I'm not terribly worried about it since my system is all local storage. I just know that others use NASs, running stuff on RPis and whatnot, and if things are trashed whenever a reboot occurs it can be a huge pain.

For backups, I just did the Plugin: CA Backup / Restore Appdata on Unraid.  It's making a weekly backup of select containers into my array. Plenty of space in there, especially for <50GB of containers.

**Comment by advplyr** [comment]
I'm not sure I understand what you mean. 
Are you using the original files for your audiobooks, or are you using symlinks?

**Comment by Budlyte** [comment]
I'm using the actual files.

Which part was confusing though? Maybe I can clarify that portion.

**Comment by advplyr** [comment]
What do you mean by `my system is all local storage`?

Also, `I just know that others use NASs`, because aren't you also using a NAS since you are running Unraid?

**Comment by Budlyte** [comment]
Hmm, I forgot NASs these days can run docker and things, but the support is usually questionable.

I used to run a windows server, to host my programs, with my TBs of data stored in a Synology NAS. These days it's all in one physical machine running Unraid, with my HDDs connected to the same motherboard as the OS running the programs accessing them, so I don't consider it a NAS.

**Comment by Budlyte** [comment]
I'm gonna close this, since it looks like the progress tracking is a "me" issue and everything else has been added.  

 Great job, as always!
