### ISSUE TITLE
[Enhancement]: reverse proxy apache2 

### ISSUE THREAD

**Issue by marioscube** [advplyr/audiobookshelf#430]
### Describe the feature/enhancement

I downloaded the Docker image and is seems to work as intended.

In my home-setup I use apache2 with reverse proxy (on server A) to access Docker container(s) (on server B).

I would like to be able to access audiobookshelf (on server B) through http://<IP-server-A>/audiobookshelf.

Using the example in the readme (for apache2) and changing 
**ProxyPass /  http://<IP-server_B>:<audiobookshelf_port>/** 
to 
**ProxyPass /audiobookshelf  http://<IP-server-B>:<audiobookshelf_port>/** 
leads to an endless spinning circle.

Am I doing something wrong here or am I missing a setting?

**Comment by advplyr** [comment]
I think this is related to https://github.com/advplyr/audiobookshelf/issues/385
using a path isn't yet supported

**Comment by advplyr** [comment]
Subdirectory main issue will be here #385
