### ISSUE TITLE
[Enhancement]: When Matching book, show Metadata Changes

### ISSUE THREAD

**Issue by Albuca** [advplyr/audiobookshelf#431]
### Describe the feature/enhancement

When editing a books metadata and manually matching -- it would be nice to be able to see what the current metadata is, along with the new metadata pulled from the provider.

This would be helpful so that I am able to make sure the new data is not vastly different than what already exists, and would allow me to see if I have made changes in the past that I would like to keep - rather than overwriting.

For example:
![audiobookshelf - Copy](https://user-images.githubusercontent.com/699690/160878648-6b9c6ba8-0a2c-41d2-82b5-0a3467a1261f.JPG)

**Comment by advplyr** [comment]
Agreed, that will be useful

**Comment by advplyr** [comment]
![image](https://user-images.githubusercontent.com/67830747/161158459-c05adbd9-c87f-4229-9d27-efd705663af3.png)

This is now wrapped up in v2 which does not have an ETA on release yet.

**Comment by advplyr** [comment]
Included in [v2.0.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.1)
