### ISSUE TITLE
[Enhancement]: When Matching, Prefer ASIN (if present)

### ISSUE THREAD

**Issue by Albuca** [advplyr/audiobookshelf#432]
### Describe the feature/enhancement

It would be awesome if there was the option to have the automatic (and manual) matching prefer to search by ASIN (if already present).

This would vastly improve the automatic searching (with my collection at least), as the search by title is fairly strict (see: https://github.com/advplyr/audiobookshelf/issues/396; granted, this may be a limitation of the audible provider).

**Comment by advplyr** [comment]
Good call. I don't think it even needs to be an option, if you have selected Audible then use ASIN if present and fallback to title/author if not.

**Comment by advplyr** [comment]
When using Audible provider and an ASIN is set that will be used when quick matching as of [v2.0.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.18)
