### ISSUE TITLE
[Enhancement]: Scrape chapter metadata and allow editing of existing chapters

### ISSUE THREAD

**Issue by benonymity** [advplyr/audiobookshelf#435]
### Describe the feature/enhancement

It would be very convenient to have the ability to fetch the chapters for an audiobook based on ASIN from Audible, which I believe has an API for it which is nicely exposed through Audnexus ([Chapter API Documentation](https://audnex.us/#operation/getChapterById)). Or if that isn't feasible would it be possible to use FFMPEG or mp4v2 or equivalent to manually modify chapters in the audio files or store changes in metadata? Having the ability to modify (name, retime, delete, etc.) chapters within the web app would be very handy. 

Thanks for all your work on this awesome piece of software, can't wait to see where it goes!

**Comment by advplyr** [comment]
Chapter editor with audible chapter lookup went straight to production in [v2.0.13](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.13).

An improvement we discussed is allowing you to shift the chapter times. Not quite sure how the UI for this would look like yet.
Chapters can also be embedded in audio files using the experimental embed metadata feature.

**Comment by benonymity** [comment]
Sweet! The editor seems to be working great. Thanks for the work, has really simplified my metadata editing.
