### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by andycol** [advplyr/audiobookshelf#438]
### Describe the issue

When scanning on a rclone mount it just crashed and does find any data

### Steps to reproduce the issue

1. scan a rclone mount

### Audiobookshelf version

1.7.2

### How are you running audiobookshelf?

Debian/PPA

**Comment by Inrego** [comment]
I'm having similar issues.
I've mounted a google drive with Rclone, and it kinda crashes Rclone after a short while of scanning the library.

**Comment by advplyr** [comment]
we'll keep the main issue for this as #444
