### ISSUE TITLE
[Enhancement]: Advanced podcast sorting / filtering

### ISSUE THREAD

**Issue by rasmuslos** [advplyr/audiobookshelf#447]
### Describe the feature/enhancement

Apple Podcasts allows users to filter their podcasts by some criteria like `played`. You can also invert the sort order of podcasts. Both would be awesome additions to ABS

![IMG_BF760FE399AE-2](https://user-images.githubusercontent.com/49640416/162563167-e899d258-2ce2-4d7c-ae87-fe2777e40b4c.jpeg)
![IMG_BF760FE399AE-1](https://user-images.githubusercontent.com/49640416/162563166-5a6885d9-26a6-40b2-b464-26e3ebaae674.jpeg)

**Comment by jt196** [comment]
Came here looking for reverse sort in podcasts. I've got a bunch of radio shows that don't fit in the Audiobook style, but would love to be able to listen to them in order of file name for example.

**Comment by advplyr** [comment]
I think this was added and I missed this request. Let me know if I'm misunderstanding though.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/c6603338-4aba-4dd6-a92f-b2ed5120debb)
