### ISSUE TITLE
Request: New Filter Option, Status, Containing: Unread, Read, In Progress

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf#45]
A filter option to view books that are in specific states would be useful.  The three I think are needed are:

- Unread
- Read
- In Progress

This would allow a user to more easily navigate to the next Unread they could be looking for, rediscover a book they had stopped midway, and manage their library of Read items.

**Comment by advplyr** [comment]
Been meaning to add this, thanks for bringing this up. Added in [v1.1.14](https://github.com/advplyr/audiobookshelf/releases/tag/v1.1.14)

**Comment by Budlyte** [comment]
You're a beast
