### ISSUE TITLE
[Enhancement]: Add options to mark all books in a series as read

### ISSUE THREAD

**Issue by BRTPOB** [advplyr/audiobookshelf#452]
### Describe the feature/enhancement

Currently there's two different ways of marking a book as read: either clicking the 3 dots in the bottom right corner of an individual book, or clicking on the empty bullet in the top left and then selecting multiple books then clicking "Mark as read" however neither of these options are available for series.

Enhancement is to allow both options for series as well.

**Comment by advplyr** [comment]
Added in [v2.0.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.3)

![seriesfinished](https://user-images.githubusercontent.com/67830747/165003336-adafacc0-e237-4b51-b5aa-60af0ee652c4.gif)
