### ISSUE TITLE
[Enhancement]: Add link to authors/book/series from Library Stats page

### ISSUE THREAD

**Issue by BRTPOB** [advplyr/audiobookshelf#453]
### Describe the feature/enhancement

When looking at the Library Stats page, it would be cool to have a link that goes to the different authors/series for the different options listed, to either go directly to that book (longest book/series) or to the page with all of the books written by whichever author it was you clicked on.

**Comment by advplyr** [comment]
This is included in [v2.0.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.1)
