### ISSUE TITLE
Request: Manually select local cover image file

### ISSUE THREAD

**Issue by Amitheous** [advplyr/audiobookshelf#46]
After the scanner was unable to find some niche book covers, I found my own links and used those, but found that occasionally links wouldn't work for the images, so I'd like to be able to go into a single book and select an image I've downloaded, or have the database automatically recognize an image file in the folder with a book (Either with the same name as the book or just named "cover.jpg" for example) and have the option to use local files for cover images.

Along with this, not sure if it would be possible, but it would be nice if there was an option to download found covers in the scanner and have those files available locally and placed alongside their respective books, so that all book and cover files could be hosted locally.

**Comment by Budlyte** [comment]
The scanner should be recognizing local image files, in the same folder as your audiobook, and applying it to the cover. If you add a cover later, you'll need to hit the Scan button in the settings.

Here's an example of a local path being set in the book's config when the local image is grabbed. "local" is the audiobook library that has been assigned.  I tested with another book and manually updating this path does work to set an image as well.
![image](https://user-images.githubusercontent.com/4451365/134212526-222a41cf-2b97-470a-b50a-ba5e74d51913.png)

I'll agree that a button to browse for a cover, starting from the location of the audiobook, would be cool but I don't see it being needed yet as I haven't seen any cases where the scanner doesn't pickup the image file.  If enough reports of that start showing up then either the scanner would need updating or a button added.

**Comment by advplyr** [comment]
You shouldn't even need to press scan anymore, just copying an image into the audiobook directory will auto-apply that image as a cover if there is none set already.

I think the biggest thing with covers right now is they need to be downloaded. I had a whole batch of covers using LibGen URL's break, they are not reliable long-term solutions. When you enter a URL, or select a cover from search, it should download the cover to either the `/metadata` folder or to your audiobook directory if you chose. Then there needs to be a button for uploading a cover image.

**Comment by advplyr** [comment]
I got the ball rolling on storing covers locally by adding an upload local cover option, in [v1.1.15](https://github.com/advplyr/audiobookshelf/releases/tag/v1.1.15)

Couple notes:

- Upload button will only be available to users with Upload permission
- Uploaded covers are stored in `/metadata/books/[BOOK ID]/...` and always named `cover.[EXT]`
    - there will be a server setting to allow storing directly in your audiobook directory
    - only 1 cover will be stored here at a time
- Covers stored in the `metadata` directory are prefixed with `/metadata/` as shown below


![image](https://user-images.githubusercontent.com/67830747/134272037-dcf858b6-8142-48d0-8386-0dd1ba75c972.png)

**Comment by advplyr** [comment]
There was a bug where the scanner wasn't automatically picking up non-audio files when they were added or modified. This could have been why your covers weren't getting added.
This is fixed in [v1.2.5](https://github.com/advplyr/audiobookshelf/releases/tag/v1.2.5)
