### ISSUE TITLE
[Bug]: Back arrow doesn't go "back"

### ISSUE THREAD

**Issue by Albuca** [advplyr/audiobookshelf#467]
### Describe the issue

When clicking the back arrow after selecting a book series from the library page, when you have collapsed books into series:

1) The back arrow (which starts as the audiobookshelf logo, next to the text logo), takes you to the 'home' page

2) The back arrow next to the series name, takes you to the 'series' page

Neither arrow takes you back to the library page which was originally navigated from.

### Steps to reproduce the issue

1. Library View: Tick 'Collapse Series'
2. Click on a series
3. Click on the back arrow (either next to the text logo, or series name)
4. Takes you back to the 'Series' page (or 'home' page), as opposed to the 'Library' page

### Audiobookshelf version

1.7.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
The back arrow was removed from the top left, and the arrow inside the toolbar is meant to go back to the series. It could be more clear but I think series will eventually have their own dedicated page in the future.
