### ISSUE TITLE
[Enhancement]: GraphicAudio Metadata Provider

### ISSUE THREAD

**Issue by dcoffin88** [advplyr/audiobookshelf#472]
### Describe the feature/enhancement

I have a lot of GraphicAudio files and it would be nice to have the metadata scan show the proper information for that version.

While some are on Audible others like Mistborn are only available from GraphicAudio

**Comment by freitagdavid** [comment]
I'll +1 this they have really great cover art.

**Comment by Kholtien** [comment]
would be a definite plus

**Comment by advplyr** [comment]
GraphicAudio doesn't have a public API at the moment so this won't be supported. Abs won't be implementing any web scraping but if another public API does we can add support for that.

**Comment by binyaminyblatt** [comment]
I made a scraper that pulls all the data from graphic audio

https://github.com/binyaminyblatt/graphicaudio_scraper 

https://graphicaudio-api.endl.site/
