### ISSUE TITLE
[Bug]: WARN: [LibraryItemController] User attempted to update without permission User

### ISSUE THREAD

**Issue by VladoPortos** [advplyr/audiobookshelf#473]
### Describe the issue

Updated to docker version 2.0.0 and can't play any book. Its just spinning the green play button. In log there is a message:

`WARN: [LibraryItemController] User attempted to update without permission User ...`

Downgrading back resulted in loss of all statistic and progress.

### Steps to reproduce the issue

1. Update from 1.7.2 to 2.0.0

### Audiobookshelf version

v2.0.0

### How are you running audiobookshelf?

Docker

**Comment by szemlicka** [comment]
Hi, I made that update too but I have no problem with playing books. I try it with the root user.

**Comment by advplyr** [comment]
Can you play any media? What about if you create another user, can that user play anything?

**Comment by VladoPortos** [comment]
@advplyr I'll test

**Comment by VladoPortos** [comment]
@advplyr hmm something is wrong with the users, my root password stopped working and after update my user is back to be user account. Is there a way to reset  root password and remove all other users ( I don't care about the progress or stats at this point )

**Comment by VladoPortos** [comment]
Managed to get root account back, and users is empty... the files with users are there, and I can log in, but they are not in Users in menu.

**Comment by advplyr** [comment]
Sounds like something got messed up with the users data. Best bet is to shut down the server and delete the entire folder /config/users. That will recreate the root user. You will lose all progress though.

**Comment by VladoPortos** [comment]
Ok, so I removed the users folder, recreated users. But still the same issue, root user can now play everything just fine, but other users gets:  `WARN: [LibraryItemController] User attempted to update without permission User ` and can't play any audio book.

**Comment by advplyr** [comment]
Just confirmed this is a bug. Will fix now

**Comment by VladoPortos** [comment]
Looks like its permissions related, I need to enable "can update" for the user to be able to play the books under that user.

**Comment by advplyr** [comment]
Deploying a patch now

**Comment by advplyr** [comment]
Patch has been pushed. Let me know how it goes.

**Comment by VladoPortos** [comment]
@advplyr works perfectly now :) thanks for superfast update.
