### ISSUE TITLE
[Enhancement]: 'Remove All Issues' button

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf#476]
### Describe the feature/enhancement

Having a button to clear issues, without purging a library and rebuilding it, would be useful for those who organize files after setting up the environment. I had quite a few issues with series numberings, and book subfolders making it think a single book was a series, so I have done a lot of cleanup and needed to delete every issue by hand. One button to clear issues after a library cleanup would be a super useful tool

**Comment by szemlicka** [comment]
100% agree

**Comment by advplyr** [comment]
Added in [v2.0.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.3)
