### ISSUE TITLE
Enhancement: add chapter "tick" marks to the playback progress bar

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#48]
Would it be possible to make selecting chapters a bit easier by adding little "ticks" onto or under the playback progress bar that are selectable (and, if possible, also show the chapter's name while hovering over)?

What you currently have:
![image](https://user-images.githubusercontent.com/25695143/134162950-612737b4-6801-4013-8cdd-696a94f67eb2.png)

How VLC portrays chapters on their playback progress bar (notice the chapter name "020" displays when I mouse hover over that "tick" mark or the section of the playback bar covered by that chapter):
![image](https://user-images.githubusercontent.com/25695143/134163344-d5909eb4-2055-43da-ac79-99ff727f5f3c.png)

What do you think?

**Comment by Budlyte** [comment]
Currently Chapters are available for selection from that dotted hamburger button on the right side.  I'll admit I have been wishing for the current chapter to be highlighted within the popup though, and hadn't gotten around to opening a req on it.

![image](https://user-images.githubusercontent.com/4451365/134209194-9d11258a-d87c-4247-9594-d4e6cc3f995f.png)

**Comment by advplyr** [comment]
Added all of these in [v1.1.14](https://github.com/advplyr/audiobookshelf/releases/tag/v1.1.14)

Chapter tick-marks, tooltip with chapter name, highlighting current chapter in chapters modal.

![image](https://user-images.githubusercontent.com/67830747/134256643-6ac00787-d158-46be-bb8b-d6dcc12792d6.png)
