### ISSUE TITLE
“Empty” library after upgrade to 2.0.0

### ISSUE THREAD

**Issue by norseghost** [advplyr/audiobookshelf#480]
Upgraded to latest, and now my library in the web app (and iOS) shows up as empty even though the scanner says “12 items added”.

the metadata scan log seems reasonable enough; and the server logs seem fine too:

```
2022-04-22 06:08:45
INFO
[Scanner] Starting library scan lscan_3xme0ycu429eb1ttxf for Main
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/Robert Jordan/The Path of Daggers/metadata.abs"
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/Robert Jordan/Vindarnas skål/metadata.abs"
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/Robert Jordan/The Fires of Heaven/metadata.abs"
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/Robert Jordan/The Shadow Rising/metadata.abs"
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/Robert Jordan/The Eye of the World/metadata.abs"
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/Robert Jordan/The Great Hunt/metadata.abs"
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/Robert Jordan/Lord of Chaos/metadata.abs"
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/Robert Jordan/A Memory of Light/metadata.abs"
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/John Scalzi/Zoe's Tale/metadata.abs"
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/Robert Jordan/The Dragon Reborn/metadata.abs"
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/John Scalzi/Murder by Other Means/metadata.abs"
2022-04-22 06:08:45
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/John Scalzi/Lock In/metadata.abs"
2022-04-22 06:08:45
DEBUG
[DB] Library Items updated 12
2022-04-22 06:08:45
INFO
[Scanner] Library scan lscan_3xme0ycu429eb1ttxf completed in 0:00.0 | 0 Added | 12 Updated | 0 Missing
2022-04-22 06:08:45
INFO
[LibraryController] Scan complete
2022-04-22 06:08:45
INFO
[LibraryScan] Scan log saved "/metadata/logs/scans/2022-04-22_lscan_3xme0ycu429eb1ttxf.txt"
```

I’d like to supply more information; but idk where to find it.

**Comment by Albuca** [comment]
Known issue: https://github.com/advplyr/audiobookshelf/issues/470

We have to wait for Google to approve the latest app update in the Play Store -- or you can grab the apk and sideload the app until the Play Store version is updated.
The apk is available here: https://github.com/advplyr/audiobookshelf/issues/470#issuecomment-1105173611

**Comment by norseghost** [comment]
Nope, different issue. I have an empty library view in the web app and iOS.

**Comment by norseghost** [comment]
This is with a completely fresh install too.

**Comment by prolife86** [comment]
Like this:
![194787c1-70c1-4a5d-a263-0289bc4efa90](https://user-images.githubusercontent.com/49482721/164619085-bc220aaf-f9f5-4fd5-98f2-fafeeaf746f7.jpg)

**Comment by norseghost** [comment]
Exactly like that

**Comment by prolife86** [comment]
> 

This is different, the problem with the apps is something I had yesterday, 2.2.0 with (in my case android) v0.9.40-beta was not working, the WebApp was good and working, after a manual update to v0.9.41-beta it was working perfectly.

But this morning tha app was again blank, no book.
But this time I also have no books in the WebApp, the complete Main libraiy contents is invisible, but not gone as the log shows.
Something in the 2 updates from last night changed it.

**Comment by norseghost** [comment]
@prolife86 that issue might be messing up things. I don’t have any tags set; maybe that trips it up (although it shouldn’t on the face of it)

it does seem like a view issue and not a library issue

**Comment by prolife86** [comment]
True, but that is the only one that looks suspicious ;)
The [other commits ](https://github.com/advplyr/audiobookshelf/commits/master)are less suspicious

**Comment by soilheart** [comment]
Same issue here.

> @prolife86 that issue might be messing up things. I don’t have any tags set; maybe that trips it up (although it shouldn’t on the face of it)

Well, that may be the issue. If I read this this line correctly, checkCanAccessLibraryItemWithTags will always return false if you have no tags:

https://github.com/advplyr/audiobookshelf/commit/22762285316ccc083e584792be3e1731b2ad1823#diff-89cde91967c084b20c4b2c39fbf0391d022633ed7722f576db77f09e985a957bR311

**Comment by norseghost** [comment]
> Same issue here.
> 
> > @prolife86 that issue might be messing up things. I don’t have any tags set; maybe that trips it up (although it shouldn’t on the face of it)
> 
> Well, that may be the issue. If I read this this line correctly, checkCanAccessLibraryItemWithTags will always return false if you have no tags:
> 
> [2276228#diff-89cde91967c084b20c4b2c39fbf0391d022633ed7722f576db77f09e985a957bR311](https://github.com/advplyr/audiobookshelf/commit/22762285316ccc083e584792be3e1731b2ad1823#diff-89cde91967c084b20c4b2c39fbf0391d022633ed7722f576db77f09e985a957bR311)

That line errors out (well, actually, fails silently) if no tags are passed in to the function; it seems; so I don’t think that’s it

**Comment by Leave-MeAlone** [comment]
after upgrade the library is empty, but during a scan everything is found but not being displayed.

**Comment by prolife86** [comment]
I changed line 311     if (!tags || !tags.length) return false to     if (!tags || !tags.length) return true
in server/objects/user/User.js

It is working again!

**Comment by Typhonragewind** [comment]
> I changed line 311 " if (!tags || !tags.length) return false" to " if (!tags || !tags.length) return true" in [server/objects/user/User.js](https://github.com/advplyr/audiobookshelf/commit/22762285316ccc083e584792be3e1731b2ad1823#diff-89cde91967c084b20c4b2c39fbf0391d022633ed7722f576db77f09e985a957bR311)
> 
> **It is working again, although this will not survive an update, as I'm running it in a Docker Container and is a temporary workaround.**

This fix worked for me! Thanks

**Comment by advplyr** [comment]
Just fixed this and patched. Nice catch @prolife86

**Comment by iSplasher** [comment]
Would it be possible to add a changelog for v2.0.0?

**Comment by advplyr** [comment]
Yes, I'm releasing that today

**Comment by yourjelly** [comment]
> I changed line 311 " if (!tags || !tags.length) return false" to " if (!tags || !tags.length) return true" in [server/objects/user/User.js](https://github.com/advplyr/audiobookshelf/commit/22762285316ccc083e584792be3e1731b2ad1823#diff-89cde91967c084b20c4b2c39fbf0391d022633ed7722f576db77f09e985a957bR311)
> 
> **It is working again, although this will not survive an update, as I'm running it in a Docker Container and is a temporary workaround, use at your own risk!**

Yes, this fixed it, my library wasn't empty it was only showing the books that had a tag.
Had to figure out how to use Vi again to make the change in my docker container tho. XD

**Comment by norseghost** [comment]
> I changed line 311 " if (!tags || !tags.length) return false" to " if (!tags || !tags.length) return true" in [server/objects/user/User.js](https://github.com/advplyr/audiobookshelf/commit/22762285316ccc083e584792be3e1731b2ad1823#diff-89cde91967c084b20c4b2c39fbf0391d022633ed7722f576db77f09e985a957bR311)
> 
> **It is working again, although this will not survive an update, as I'm running it in a Docker Container and is a temporary workaround, use at your own risk!**

Oh ok I can’t read JS very well! Good job!

**Comment by advplyr** [comment]
You don't need to do the workaround that @prolife86 pointed out anymore, that fix is not in the current v2.0.0 release.

**Comment by yourjelly** [comment]
Yeah, but it was faster than figuring out how to force docker to update when it wasn't requesting to.

**Comment by skyzuma** [comment]
yeasterdays upgrade / migration to v2 was successfull but today my library was fully empty after load the litte v2 patch (docker on armv8 x64) ... the server was loading al contentl correct ... ONLY after delete and redownload the latest docker image all is there back

**Comment by Albuca** [comment]
The hash changes with each commit (even if the version number does not), so a 'docker-compose pull' would grab the latest image and see that the hash does not match what is existing on the system and thus mark it as the 'newest'. Therefore a subsequent 'docker-compose up -d' would recreate the container using the newest image.

n.b. docker pull advplyr/audiobookshelf ((followed by your cli command to initiate the container would also grab the newest image and recreate the container using it))

That said, @advplyr I see that you've pushed V2.0.1 (https://github.com/advplyr/audiobookshelf/commit/d4525ad5ca3153b765bdbb730147a1c308eb2882) and it's been pushed to Docker Hub - so that should hopefully catch anyone whos systems weren't grabbing the latest revision to the 2.0.0 release.

Lastly, I'll open an issue with regards to release notifications within the application itself - so we can track discussion/requirements/need in its own topic.

**Comment by advplyr** [comment]
I appreciate you all. Hopefully with the official release notes for [v2.0.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.1) everyone should be aware to update.
