### ISSUE TITLE
[Bug]: 'Edit Metadata' window changes to old book when notification goes away

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf#483]
### Describe the issue

On the latest version (v2.0.1)

Im in the process of matching all of my books manually, and stumbled across this: 
If I edit/match something, and save it then move to another book with the right/left arrows while the notification is still up, the data displayed shifts back to the original book when the notification disappears. If I then move left/right again to the second book I switched to, it seems to not 'be in the queue'. 

### Steps to reproduce the issue

1. Match a book or make a metadata change
2. Save it, and the notification should pop up in the top right corner
3. While the notification is still on the screen, use a right or left arrow to move to a different book
4. When the Notification Disappears, you'll see the data shown switches back to the one you were just on. Trying to move to the book you had just moved to in step 3 will show that it 'skips over' the book that should be there. Leads me to believe the server thinks it is still displaying the book you were on, but the frontend is not displaying it.

### Audiobookshelf version

v2.0.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This is fixed now in [v2.0.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.2)
