### ISSUE TITLE
[Bug]: When having multiple entries for the same author, manually editing names does not merge them

### ISSUE THREAD

**Issue by TK3D** [advplyr/audiobookshelf#487]
### Describe the issue

I had 2 entries for the same author with slightly different names due to their metadata.
When editing both of them to have the exact same name and ASIN, the 2 entries do not get merged.
Screenshot of issue: [[imgur link]](https://imgur.com/a/RRqZLX0)

### Steps to reproduce the issue

1. Import 2 books of the same author with different author name in metadata
2. Manually edit the data of both to be the same

### Audiobookshelf version

v2.0.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.1.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.1)
