### ISSUE TITLE
Enhancement: Make the information that displays for the audiobook that's playing, clickable links

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#49]
Would it be possible to make this pictured area "clickable"?

![image](https://user-images.githubusercontent.com/25695143/134166512-8c7c309e-f853-4f8c-bfd6-14a33ad00a57.png)

The Author could give a view filtered to display that author. The title could take you to the book details page. And the Picture could do the same and also take you to the book details page.

What do you think?

**Comment by advplyr** [comment]
This made sense to me, I added it in `v1.1.14`.

Fyi I started filling out the [release notes](https://github.com/advplyr/audiobookshelf/releases/tag/v1.1.14) and referencing issues.
