### ISSUE TITLE
[Bug]: Books that have files with Failed Track Numbers not shown in the Issues tab.

### ISSUE THREAD

**Issue by Strider27** [advplyr/audiobookshelf#491]
### Describe the issue

If the scanner fails to extrapolate a track number during scan (if filename has no number and id3 tag is blank) for multi-file audiobooks, it displays a warning on the books page and a notification on the issues tab, however if issues tab is clicked the list is empty.

### Steps to reproduce the issue

1. have a track with no track number.

### Audiobookshelf version

v2.0.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
These will show in issues now for [v2.0.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.2)

**Comment by advplyr** [comment]
Found more issues with issues. Fixed in [v2.0.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.3)
