### ISSUE TITLE
[Bug]: Error when importing Podcast with many episodes

### ISSUE THREAD

**Issue by duplaja** [advplyr/audiobookshelf#493]
### Describe the issue

Error below occurred when importing a podcast with 374 episodes. (For testing purposes: https://podcasts.apple.com/us/podcast/aws-morning-brief/id1466344305?uo=4 )

![0sz6EZG5bcT8oZ9QoKXPhjR74kYqXd2o](https://user-images.githubusercontent.com/20245408/164948177-eefedf53-01f5-4311-ba8a-a4e70296898c.png)

### Steps to reproduce the issue

1. Try to import all episodes at once from the podcast link above.

### Audiobookshelf version

v2.0.1

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
When implementing this and testing with the podcast you linked I added some indicator of the current downloads.

![image](https://user-images.githubusercontent.com/67830747/164951173-da865f44-e913-461d-b476-6d26141fb75a.png)

**Comment by advplyr** [comment]
This is fixed now in [v2.0.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.2)
It may need to be adjusted again though because it only supports 5MB requests.
