### ISSUE TITLE
[Bug]: Podcast Import Popup Hides "Add Podcast" Button on Smaller Screens

### ISSUE THREAD

**Issue by duplaja** [advplyr/audiobookshelf#494]
### Describe the issue

When you click on a podcast from search, the pop-up modal not responsively sized / does not scroll. You have to zoom out on smaller screens, to be able to see the "Add Podcast" button. (~70% browser zoom on a 14" screen)
![biPlnZ9Wm0HUPWixzeQPJM6mluG2vnTe](https://user-images.githubusercontent.com/20245408/164949797-11463323-0bd6-4011-a955-57a90f619e88.png)
.

### Steps to reproduce the issue

1. Search Podcast
2. Click to open modal
3. Have to zoom out to add.

### Audiobookshelf version

v2.0.1

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
In fixing the other issue you posted about request size I decided to just remove the episode select on the right and instead you will download episodes on the landing page.
The current design was too cramped I didn't like it, hopefully this will be cleaner.

**Comment by duplaja** [comment]
Thank you!

**Comment by advplyr** [comment]
Fixed in [v2.0.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.2)
