### ISSUE TITLE
Ubuntu ppa certificate issues.

### ISSUE THREAD

**Issue by cenjui** [advplyr/audiobookshelf#495]
Hello,

Thanks for the project, looks great so far!

I was trying to install on ubuntu 20.04 and I kept getting certificate errors with the ppa. I tried deleting and re-downloading the key but kept getting the same invalid cert issue.

I worked around it by changing the list file (/etc/apt/sources.list.d/audiobookshelf.list) to include trusted=yes, ie:
<Code>
deb [trusted=yes] https://advplyr.github.io/audiobookshelf-ppa ./
</Code>

Thanks,
David.

**Comment by advplyr** [comment]
Thanks for the heads up. I still don't know much about hosting a PPA and getting it trusted. I will put this in the docs in the meantime.

**Comment by advplyr** [comment]
Added that in audiobookshelf.org/install
Thanks!
