### ISSUE TITLE
[Bug]: Filters are not presented in any sort of identifiable order

### ISSUE THREAD

**Issue by cassieesposito** [advplyr/audiobookshelf#497]
### Describe the issue

When attempting to filter library by author, narrator, or any other field, choices are not presented alphabetically or by any other identifiable method, which makes it difficult to use.

Issue is presumably server side, since order presented is consistent across devices, in web interface, and in android app.

UPDATE: This issue also affects Authors tab from web interface side bar.

### Steps to reproduce the issue

1. Go to library
2. Select Filter button in android app or filter dropdown menu in web interface
3. Select Authors

### Audiobookshelf version

2.0.2

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
I think this got lost when re-doing the api for v2, thanks

**Comment by advplyr** [comment]
Fixed in [v2.0.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.3)
