### ISSUE TITLE
Enhancement: Would it be possible to view the ebook version

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#50]
I'm aware that the primary focus of this is to play audiobooks and do it well.

The thing is, your layout and interface and feature set is so good, that I'd LOVE to make this the access point to my personal library of ebooks and audiobooks!

We could include common ebook formats (epub, pdf, etc) in the same locations as the audiobooks. And if one of those formats is detected, we could have a "read"/"eBook" button show up that will let us select which file to display (in case of multiple eBook files) and view the eBook version.

example:
![image](https://user-images.githubusercontent.com/25695143/134170298-f5ec5986-b49a-4e81-9a19-cacd4e134f00.png)

This would be perfect for books that have rich art that goes along with them that is hard/impossible to convey in the audio format. (Several Brandon Sanderson books come to mind that are Art rich titles)

I would just LOVE to have something exactly like what you've built that makes it easy to display, share, and use the many eBooks that I also have. And I figure, if we could do it all from the same place, that would be even better! If you're worried about too many non-audio books showing up (maybe the scanner sees the books even if the audiobook file is missing), then maybe we could simply add a quick-select switch on the main screen that let's us view books that "have audio", "eBooks" or "Both/All". This way, maybe there won't be too much extra to do. 

Maybe something like this?:
![image](https://user-images.githubusercontent.com/25695143/134171970-7a9cfc35-78ed-4ac1-bcd9-1e0dfc168223.png)

But, what do YOU think?

P.S. reading this again, I realize that it would have been more accurate to have the "display quick-select" options read more like: Show All, Includes Audio, Includes eBook. The idea was meant to have it quickly display everything, or only all the books that have an audio file to go with it (even if they also have eBook files), or only display all the books that include eBook files (even if they also have audio files too). Do you know what I'm meaning?

**Comment by advplyr** [comment]
I'm glad you brought this up, I always planned on adding this because I put my ebooks in the same directory as the audiobook already. It is the next logical step to expand the project to more than 1 medium.

The scanner already classifies `pdf` and `epub` files as ebooks. The next step for this would be displaying the ebooks in a separate section on the audiobook landing page (between audio tracks and other files), then allowing the user to manage ebooks similar to how they can manage audio tracks.

I hadn't thought about the Read button, but I like your idea there. I'm thinking an open book icon with "Read".

I understand what you mean about the filter in the toolbar. I never liked my initial design for the filters/sorting, I would like to completely re-think that toolbar layout, but design in general is not my forte.

**Comment by Kudjo-Grand** [comment]
Oh, that's SO AWESOME! I would be happy to help you test this (even if it's experimental at first)! Just let me know. 

We'll get this sorted and working well soon, you'll see!

**Comment by binarygeek119** [comment]
if this get impended i love the docker to look at this paths
/audiobooks = audiobooks
/books = books
/Comics = Comics
/Magazines  = Magazines

**Comment by Kudjo-Grand** [comment]
Multiple path support? That's a great idea! This would easily allow anyone to bring in their existing liberals without needing to move a bunch around.

+1

**Comment by advplyr** [comment]
I'm playing around with this now and have a *very* primitive epub reader.
It is going to be a challenge, so I'm going to do it in small increments and add an experimental feature toggle switch so it can be tested in production.

I agree on supporting multiple paths, however I don't want to force the user to distinguish which paths are ebooks or audiobooks. What I'm thinking now is that mapping different paths creates a separate library. All libraries are treated the same in terms of their contents, but if you choose to separate your ebooks and audiobooks that should work just fine.
Hope that made sense.. still working this out in my head.

**Comment by advplyr** [comment]
The very very beginning of adding ebook support has begun. Enable experimental features in `v1.3.5`

![image](https://user-images.githubusercontent.com/67830747/135730037-94c38c03-cd79-41b1-a789-6ba8edda604b.png)

and I started a discussion #75 with some more info

**Comment by Kudjo-Grand** [comment]
I'm SO excited for this feature to get built out! I'll try it today and help as best I can.

**Comment by Kudjo-Grand** [comment]
Haha. Well, I feel silly. I just spent too much time trying to figure out why my install wasn't updating to the correct version (1.3.5)... Until I thought to check, and realized that it hasn't been pushed yet and the latest is 1.3.4. 

Lesson learned: be more patient and check if it's been pushed in the future.

:P

**Comment by advplyr** [comment]
It has been pushed, I just didn't create a release for it yet. Now I'm curious why you aren't able to update..
