### ISSUE TITLE
[Bug]: Covers/Backgrounds for books in a series are sometimes offset on the home tab

### ISSUE THREAD

**Issue by TK3D** [advplyr/audiobookshelf#505]
### Describe the issue

Sometimes the book covers and their blurred backgrounds are offset/cut off in the home tab.
This only happens in the "recent series" row and is usually fixed by either reloading the page or clicking on a different tab and back again.

Screenshot of issue: [imgur link](https://i.imgur.com/UDvuASr.png)

I tried the following browsers and confirmed all of them had the same result:
- Firefox
- Edge
- Chrome

### Steps to reproduce the issue

This seems to happen randomly without any apparent way to reproduce consistently.

### Audiobookshelf version

v2.0.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.8](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.8)
