### ISSUE TITLE
[Bug]: File path parsing adding special character if author name has a period

### ISSUE THREAD

**Issue by alexpearce92** [advplyr/audiobookshelf#506]
### Describe the issue

It looks like the parsing of the file path is adding special characters to the author's name on initial scan. A folder with the name "Rowling, J. K." will result in an author name of "J. Kf Rowling", where the f has an apostrophe. Changing the author folder to "J. K. Rowling" will result in the author name of "J. K.F Rowling" where again, the F will have an apostrophe.

File path ("J. K. Rowling"):
<img width="657" alt="Screen Shot 2022-04-25 at 11 22 40 AM" src="https://user-images.githubusercontent.com/6473983/165131895-a5d1a47a-e494-4b18-8ac6-3dede8b0c8a5.png">

File path ("Rowling, J. K."):
<img width="576" alt="Screen Shot 2022-04-25 at 11 29 15 AM" src="https://user-images.githubusercontent.com/6473983/165132847-73bd75b2-1be9-4b5a-910e-c824bec73ab7.png">

Parsed author:
<img width="266" alt="Screen Shot 2022-04-25 at 11 22 23 AM" src="https://user-images.githubusercontent.com/6473983/165131889-8846e184-35ff-41a8-808b-ad0d8d3c40bb.png">

Author tag:
<img width="421" alt="Screen Shot 2022-04-25 at 11 27 18 AM" src="https://user-images.githubusercontent.com/6473983/165132407-14845084-159f-44fc-8866-b309eb6853df.png">

Current workaround is to not include the periods or just manually fix the metadata by editing the book.

### Steps to reproduce the issue

1. Create path "J. K. Rowling/My Book Name/Book.m4b" and "Rowling, J. K./My Book Name/Book.m4b"
2. Edit book metadata in audiobookshelf for "My Book Name". Author's name will have the special character

### Audiobookshelf version

v2.0.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Is the directory you are mapping in docker from windows?

**Comment by apearce-nov** [comment]
Linux based Synology

**Comment by nichwall** [comment]
I think this may have been fixed at some point, I'm not able to reproduce this bug using ABS server 2.11.0 with Synology DSM 7. The scanner had been rewritten around server 2.4.0-2.6.0, so may have been at that point?
