### ISSUE TITLE
[Enhancement]: Add podcast 'add via search' permissions for non-root users

### ISSUE THREAD

**Issue by njhdunn** [advplyr/audiobookshelf#507]
### Describe the feature/enhancement

When trying to add a podcast via the 'Search' interface in a library with media type 'Podcast', I get an "Internal server error" popup in the web interface and an error shows up in the logs:

```
[2022-04-25T16:54:17.828Z] ERROR: [PodcastController] Non-root user attempted to create podcast
```

It would be nice if there were a permission toggle per account in the user management interface to allow non-root accounts to add new podcasts in this way.

**Comment by advplyr** [comment]
Updated in [v2.0.8](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.8) admin users now have permission to add new podcasts and download podcast episodes.

**Comment by BlackHoleFox** [comment]
@advplyr Ping on this if possible. Not sure why regular users can't upload these?

**Comment by advplyr** [comment]
There is an issue for this #1258
I think this will be a new permission for "Manage Podcasts" that allows for adding new podcasts, downloading episodes and updating podcasts/episodes.
