### ISSUE TITLE
[Bug]: Invalid Feed Payload

### ISSUE THREAD

**Issue by jflattery** [advplyr/audiobookshelf#510]
### Describe the issue

The auto download feature for podcasts is broken.

### Steps to reproduce the issue

1. Use the search feed to import the "Self-Hosted" podcast
2. Download the penultimate episode
3. Check the "Auto Download New Episodes" checkbox
4. wait for `checkPodcastForNewEpisdoes` to execute
5. Observe `invalid feed payload` error in logs

### Audiobookshelf version

v2.0.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I think we've solved this one for now
