### ISSUE TITLE
[Enhancement]: Multiple books in single file

### ISSUE THREAD

**Issue by tHeCh0s3n0n3** [advplyr/audiobookshelf#511]
### Describe the feature/enhancement

I have a few audiobook files which contain multiple books in a single mp3 file (ex: an Omnibus). When naming the file I can't find a way to indicate that there are multiple books included in the same file.

**Example:**
<ins>File path is:</ins> Author Name/Series/Book 1 to 3 - Omnibus/Omnibus.mp3

While scanning, the "Book 1" part of the filename works as expected and the book gets a "#1" tag. However the other book number(s) in the same filename appear to be completely ignored. I can manually add them later though, but it's not ideal.

**Enhancement:**
Make the filename parser able to accept multiple books in the same file.

**Suggesting file naming conventions:**
* Book 1-3 *- Book Name*
* Book 1, Book 2, Book 3, ... *- Book Name*
* Book 1 to 3 *- Book Name*
* Vol and other book number prefixes should also act the same

**Comment by dweomer21** [comment]
I was about to write up an issue requesting this same feature! 
Consider this an upvote.

**Comment by advplyr** [comment]
How would you show the series sequence for multiple books in one?

**Comment by tHeCh0s3n0n3** [comment]
Not sure I understand the question, but the result I'm suggesting is something like this once it's imported:
![image](https://user-images.githubusercontent.com/1936117/178202715-992fda6d-5d48-408b-b6f4-242a785fb5a7.png)

**Comment by advplyr** [comment]
If the title came in as `0.5-3` then the scanner would have no way to know that there is a sequence for 1 and 2. Maybe there is a sequence 1.5.
This seems complex with a ton of edge cases that would have to be considered. When we plan out how to allow the user to customize the path parsing then we can revisit this but for now it is not planned to support.
