### ISSUE TITLE
[Enhancement]: Default sort options to Descending

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf#515]
### Describe the feature/enhancement

When selecting a sort option, like author name, it should sort by descending order first as opposed to ascending. 

Right now, if click on 'sort by author (first, last)' it displays a 'V' arrow as the sort direction, but actually sorts them in reverse alphabetical order. Most people, when sorting, expect it to be in alphabetical order on their first sort, so I think making it the default would be a better option.

It could honestly be a bug, with the way the arrow is pointing in the dropdown, but Im not sure.

**Comment by advplyr** [comment]
I changed the default sort to ascending when clicking on title or author, but I think the arrow directions are correct.

An up arrow represents ascending (A -> Z) or (0 -> 9) and a down arrow represents descending.

**Comment by advplyr** [comment]
Updated in [v2.0.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.4)
