### ISSUE TITLE
[Bug]: Wrong File Order after renaming files, and doing re-scan

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf#517]
### Describe the issue

Wrong File Order after renaming files, and doing re-scan. Doing re-scan via re-scan button in EDIT book does not help either.   Files have now order - >  OLD FIles + NEW FILEs ( Probably ).  Files have Tracks number in ID3 and are in good name order. ( Scanner prefers .opf)

Screenshoots: https://imgur.com/a/XT6uUKe

Missing Parts (9)

22, 25, 28, 32, 38-40, 42, 45

# | Filename | Size | Duration | Download
1 | 00 Wstep.mp3 | 511.23 KB | 0:18 | download
2 | 01 Skala uciekajaca.mp3 | 10.37 MB | 17:59 | download
3 | 02 Za i przeciw.mp3 | 10.01 MB | 14:27 | download
3 | 03 Jak im sie podoba.mp3 | 8.86 MB | 12:46 | download
4 | 05 Na los szczescia.mp3 | 10.36 MB | 14:58 | download
5 | 04 Ned Land.mp3 | 10.22 MB | 17:43 | download
5 | 06 Cala sila pary.mp3 | 11.44 MB | 19:50 | download
6 | 12 Wszystko za pomoca elektrycznosci.mp3 | 12.41 MB | 17:57 | download
7 | 16 Przechadzka po rowninie.mp3 | 11.1 MB | 16:02 | download
8 | 07 Wieloryb gatunku nieznanego.mp3 | 10.3 MB | 17:51 | download
8 | 21 Pare dni na ladzie.mp3 | 13.54 MB | 23:31 | download
9 | 08 Mobilis in mobili.mp3 | 11.36 MB | 19:42 | download
9 | 24 Panstwo koralowe.mp3 | 13.84 MB | 20:01 | download
10 | 09 Gniewy Neda Landa.mp3 | 10.74 MB | 15:31 | download
10 | 27 Perla wartosci dziesieciu milionow frankow.mp3 | 16.11 MB | 28:00 | download
11 | 10 Pan wod.mp3 | 13.4 MB | 23:16 | download
11 | 31 Przez Morze Srodziemne w czterdziesci osiem godzin.mp3 | 17.84 MB | 25:51 | download
12 | 11 Nautilus.mp3 | 11.63 MB | 20:10 | download
12 | 37 Lawica lodowa.mp3 | 20.12 MB | 29:10 | download
13 | 38 Biegun Poludniowy.mp3 | 19.75 MB | 34:22 | download
14 | 13 Troche liczb.mp3 | 13.26 MB | 19:11 | download
14 | 39 Nieszczescie czy wypadek.mp3 | 12.79 MB | 18:30 | download
15 | 14 Czarna Rzeka.mp3 | 17.06 MB | 29:40 | download
15 | 41 Z Przyladka Horn do Amazonki.mp3 | 17.32 MB | 25:06 | download
16 | 15 Zaproszenie listowne.mp3 | 11.4 MB | 19:46 | download
16 | 44 Pod 47deg24' szerokosci i 17deg28' dlugosci.mp3 | 14.57 MB | 21:06 | download
17 | 46 Ostatnie slowa Kapitana Nemo.mp3 | 11.36 MB | 16:25 | download
18 | 17 Las podmorski.mp3 | 12.58 MB | 18:11 | download
18 | 47 Zakonczenie.mp3 | 2.8 MB | 3:57 | download
19 | 18 Cztery tysiace mil pod Oceanem Spokojnym.mp3 | 12.8 MB | 22:13 | download
20 | 19 Vanikoro.mp3 | 11.77 MB | 17:01 | download
21 | 20 Ciesnina Torresa.mp3 | 13.96 MB | 20:12 | download
23 | 22 Piorun Kapitana Nemo.mp3 | 13.94 MB | 24:13 | download
24 | 23 Aegri Somnia.mp3 | 14.75 MB | 21:21 | download
26 | 25 Ocean Indyjski.mp3 | 15.27 MB | 26:32 | download
27 | 26 Nowa propozycja Kapitana Nemo.mp3 | 16.87 MB | 24:26 | download
29 | 28 Morze Czerwone.mp3 | 18.87 MB | 32:49 | download
30 | 29 Arabian Tunnel.mp3 | 14.67 MB | 21:14 | download
31 | 30 Archipelag Grecki.mp3 | 18.64 MB | 27:01 | download
33 | 32 Zatoka Vigo.mp3 | 18.4 MB | 26:40 | download
34 | 33 Lad zaginiony.mp3 | 16.95 MB | 24:33 | download
35 | 34 Podmorskie kopalnie wegla.mp3 | 17.07 MB | 24:44 | download
36 | 35 Morze Sargasowe.mp3 | 16.2 MB | 23:28 | download
37 | 36 Potwale i wieloryby.mp3 | 18.15 MB | 26:18 | download
41 | 40 Brak powietrza.mp3 | 13.94 MB | 24:13 | download
43 | 42 Matwy.mp3 | 17.89 MB | 25:56 | download
44 | 43 Golf-Stream.mp3 | 19.9 MB | 28:51 | download
46 | 45 Hekatomba.mp3 | 14.94 MB | 21:38 | download

### Steps to reproduce the issue

1.  DO scan, rescan 
2. Change file nnames of mp3  for example.   2.  Everyhing is changing Track 2.mp3  - >  2.  Everyhing is changing.mp3
3. Do Re-scan

### Audiobookshelf version

2.0.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Are you still seeing this issue?

**Comment by superpawko** [comment]
I tested 4 books, and it looks like everything is now fine on 2.0.17.   I can't find Manage audiotracks  anymore.

**Comment by superpawko** [comment]
If my files are like these: 

01 a[96].mp3
01 b[96].mp3
02 a[96].mp3
02 b[96].mp3
03 a[96].mp3
03 b[96].mp3
04 a[96].mp3
04 b[96].mp3
05 a[96].mp3
05 b[96].mp3


1. And  I will first change  05 a[96].mp3   -  to -  > 05 a.mp3 
2. Do Rescan. 
3. Do nothing else in ABS.  Rename all other files to match  01 a.mp3 02 b.mp3 etc....   
4. Do Rescan 

I'm ending with wrong order as it somehow remembers file order from before.

![image](https://user-images.githubusercontent.com/11931157/171032069-cf479064-b490-4d60-b870-cb069da233fd.png)

**Comment by advplyr** [comment]
I'm pretty confident this was fixed in 2.0.24 when I pushed a fix for #823
The problem was when it scanned in new audio files it wasn't including the old ones when sorting again.

Let me know though if this should be re-opened
