### ISSUE TITLE
[Enhancement]: Goodreads button

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf#518]
### Describe the feature/enhancement

It would be great to have a goodreads button on the item page to be able to search by the title easily

**Comment by DDriggs00** [comment]
Goodreads has special links for books with an isbn. Presumably for ASINs as well.

**Comment by advplyr** [comment]
Can you elaborate on this? I'm not sure what you mean.

We have no way to link with Goodreads or communicate with Goodreads in any way so any links or IDs would need to be entered manually.

**Comment by barelylit** [comment]
I have a tasker task searching just with :

https://www.goodreads.com/search?q=title here

That would do it.

**Comment by advplyr** [comment]
So a button that searches goodreads with the title? What is the use-case for this?

**Comment by raviwarrier** [comment]
The use case is that people might want to open GR while or after reading a book. To mark status or rate/review it. Getting there directly from the app would be just a bit faster than switching apps.

**Comment by advplyr** [comment]
I'm closing out the Goodreads requests since Goodreads isn't developer friendly right now given they closed their public API.

I wrote more about it here: https://github.com/advplyr/audiobookshelf/issues/281#issuecomment-1159572840

**Comment by raviwarrier** [comment]
I understand.

**Comment by barelylit** [comment]
To log the book as read in Goodreads. Which is then good for building
recommendations based on previous read.
