### ISSUE TITLE
[Bug]: (Lack of) visual feedback on checkboxes is confusing

### ISSUE THREAD

**Issue by cassieesposito** [advplyr/audiobookshelf#521]
### Describe the issue

Checkboxes are empty whether selected or not. You can tell by whether the relevant field is grayed out, but the lack of an X or ✔ or some other visual indicator in the box itself violates UI/UX conventions, creating user confusion.

Expected behavior: visual feedback in the checkbox itself indicating selection status.

### Steps to reproduce the issue

1. Open web interface
2. Edit a book
3. Match tab
4. Search for a book
5. Select the correct match
6. Click checkboxes

OR

1. Open web interface
2. Library tab
3. Select multiple books
4. Click orange edit button in top right
5. Open "Map details" dropdown
7. Click checkboxes

### Audiobookshelf version

2.0.3

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
This is fixed in [v2.0.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.4)
