### ISSUE TITLE
[Bug]: OPF scanner, undefined date  in Calibre. <dc:date>0101-01-01T00:00:00+00:00</dc:date>

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf#524]
### Describe the issue

Maybe it is not a bug, but date: <dc:date>0101-01-01T00:00:00+00:00</dc:date>  Is seen by Calibre as Undefined.  Could You please make special check for this <dc:date>0101-01-01T00:00:00+00:00</dc:date>  so it will be ignored.

### Steps to reproduce the issue

1. Opf file has to be from calibre wher Publish Date was not defined.
2. Re-scan books with metadata from OPF

### Audiobookshelf version

2.0.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Does this issue still persist? I think since you made this request I updated the OPF scanner for handling prefixes like "dc".

**Comment by superpawko** [comment]
I did only re-scan. And it is showing again 0101.

Problem is :  Publish date from  dc:date**0101-01-01T00:00:00+00:00**    in  ABS is  **0101**.     This is correct via parser. But I'm asking to add special case for this date: 0101-01-01T00:00:00+00:00   to be set as **UNKNOWN**.  

 Thank you for your consideration.

**Comment by advplyr** [comment]
Right now the publish date is not validated in anyway, it is just a string. I don't see this on the roadmap now but maybe in the future.

**Comment by superpawko** [comment]
I understand,  thank you.
