### ISSUE TITLE
[Bug]: Covers are not replaced with new version after RE-SCAN

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf#525]
### Describe the issue

Covers are not replaced with new version (after file was replaced with new one)  after RE-SCAN

### Steps to reproduce the issue

1. After already made DB 
2. Change Cover.jpg to diffrent file with the same name
3. DO Re-Scan
4. Covers are not replaced with new version after RE-SCAN
5. Cover has to be deleted by hand and pointed again

### Audiobookshelf version

2.0.3

### How are you running audiobookshelf?

Docker

**Comment by jmt-gh** [comment]
>Covers are not replaced with new version after RE-SCAN

Can you be a bit more specific here? Which cover? In the UI you see it revert? The actual cover file that gets downloaded and stored on disk? The cover embedded in to the audiobook itself?

**Comment by superpawko** [comment]
I'm rebuilding RAID matrix, I will let you know in 3 days.   As far as I remember If I replaced cover.jpg with new cover.jpg ( only on HDD) did re-scan, the change was not seen by ABS. ABS did not populate DB with new cover, because the filename was the same.

**Comment by advplyr** [comment]
We'll re-open if this is reproducible
