### ISSUE TITLE
[Enhancement]: Filtering common issues on matches

### ISSUE THREAD

**Issue by cyberkoala** [advplyr/audiobookshelf#526]
### Describe the feature/enhancement

When matching, the most common reason for failure I've seen is the title containing some variation of  '(unabridged)', and getting no returns. Manually deleting that last bracketed bit, hit match, and instantly finds the title. While i understand it can help differentiate versions of an audiobook, I've not yet found a case where it was more helpful. I know some titles out there probably contain the word itself, so maybe the helpful behavior would be logic where after a match attempt- if no matches are returned, try again, removing some of the most common artifacts, like '(Unabridged)', or a series number at the start (like '1 way of kings', drop 1).

Not the biggest problem in the world, but seems like a relatively quick fix, and if implemented as a backup to the first attempt to match would not cause any additional problems with failed matches.

**Comment by advplyr** [comment]
This will be updated in the next release. See https://github.com/advplyr/audiobookshelf/pull/735
