### ISSUE TITLE
[Enhancement]: Play history

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf#527]
### Describe the feature/enhancement

I would be good if there was a button to list the last stop points and the time they were achieved, something like:

09:00am - 01:43:56
10:00am - 01:55:23

The reason I ask for this is I had been listening on desktop at work with the web client, then i got in the car and it skipped back to where i was was up to on the phone as i just hit play from the notification tile on the phone. If there had been a history list I could have gone straight back to the last played time showing when i left the desk

**Comment by JamesDean3** [comment]
This is similar to what I was thinking would be nice to have for cases like you mentioned above but I would like both a start and stop time, allowing you to narrow things down a bit and skip forward from last start time in certain situations. Like if you were to have fallen asleep without the sleep timer or the audiobook somehow got started without you realizing it.

**Comment by DDriggs00** [comment]
Smart Audiobook Player on Android has a similar feature, although it records the play and pause events.

**Comment by hobesman** [comment]
I don't know if a button is or isn't the best approach, but _something_ to indicate where you were at specific times would be helpful. For example the "stats" page in the web UI currently lists when you had a recent session and how long it was, but doesn't say what part of the book you started or stopped at.  

I have bluetooth headphones that have one button on them. It turns them on and once on, that same button also acts as the play button. So at least every few days I'll find my headphones playing an audiobook in my pocket, and I have to try to guess where I was before and how long it's been playing. Not everybody's problem, but long story short I too would like a more detailed view of my history. Either on a per-book basis accessible on the book's details page, or else on a separate page showing a user's history all on one page. Or maybe both.

**Comment by advplyr** [comment]
The latest release has a page you can view all the listening session and click into them and view all the details about that listening session. This doesn't record play/pause but it does record the media time when started and last media time saved in that session. You can also view the listening sessions for all your users also (I think we should all a "global" listening sessions page too).

In the next app release it will also send with it the details about the app version, device model, etc.

This will also be implemented in some way on mobile so you can see your local listening sessions too.

That bug you mentioned I hadn't thought about before, I have an idea on how to fix that.

**Comment by burnshroom** [comment]
To expand on this, and if a new feature request is needed I can do that too, but...

Would it be possible to have per book stats.  Things like how many times you've finished a book.  In addition to the actual sessions when you did listen to a book, where you started and finished that session.  All accessible from that books info page.  

This maybe an overreach but nothing ventured...

**Comment by advplyr** [comment]
You mean like tracking how many times you finished the same book? I think this would be difficult to track. Adding a filter to the listening sessions page per library item and linking to that from the item page is do-able.
