### ISSUE TITLE
[Bug]: Unable to change main library location to a subfolder of original directory

### ISSUE THREAD

**Issue by DDriggs00** [advplyr/audiobookshelf#529]
### Describe the issue

When attempting to set the main library to be a subdirectory of it's original location, it causes a crash without adding anything to the log. Changing it to other directories, such as `/media`, works without issues.

### Steps to reproduce the issue

1. Setup a new docker container with no existing data or configuration
2. Link `/audiobooks` in the docker container to a directory containing multiple subdirectories (e.g. `/library1`), each of which includes a structured audiobook library
3. Under Config -> Libraries, edit the `Main` library
4. Since editing paths is impossible at this point, add `/audiobooks/library1` as a path, and remove `/audiobooks`
5. When clicking save, the server will crash, which will be exhibited by the client showing a socket disconnect error.

### Audiobookshelf version

v2.0.3

### How are you running audiobookshelf?

Docker

**Comment by DDriggs00** [comment]
I figured out the problem: When adding or removing paths from a library, abs sets permissions on the path. With a read-only library, this causes a crash.

**Comment by advplyr** [comment]
Fixed in [v2.0.15](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.15)

Should work fine with a read-only library as long as the folders exist first.
