### ISSUE TITLE
Request: Pressing Enter in Global Search Loads Page of Results

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf#53]
The search bar not doing anything when Enter is pressed seems like a waste of its use, but it seems to basically do the same thing as the Keyword Filter entry but in a dropdown list.

Can the function of the Keyword Filter entry be moved to when Enter is pressed when using the Search box?

**Comment by advplyr** [comment]
My initial thought was that the global search would search across everything. Authors, tags, series, etc., like Plex.

Then pressing enter would bring you to a search page. In that case it would function much different then keyword filter.

I always liked the global search.

**Comment by Budlyte** [comment]
Oh, I totally missed that the Keyword Filter is a custom filter that can further refine the results already selected from the filter in a dropdown list.  I was treating it like a global search from the main show All page.

Yeah, if hitting Enter from Search would work, that's pretty much what I meant here.

**Comment by advplyr** [comment]
Added in [`v1.2.1`](https://github.com/advplyr/audiobookshelf/releases/tag/v1.2.1)

I still plan to add searching for authors, collections, series, etc.
