### ISSUE TITLE
Removing section while uploading removes the file only, not intended section

### ISSUE THREAD

**Issue by jonathondk** [advplyr/audiobookshelf#530]
### Steps to reproduce

1. Upload Folder Tree with multiple books using the recommended folder structure (Author\Series\Title)
2. ABS scans the folder tree, separates the books by the folders into sections
3. Click on the "X" on one section

### Expected behaviour
The section with the "X" clicked should be removed, file and author/title/series data as well

### Actual behaviour
The file is removed, the files all move up one section with data not moving

Screenshots
- Just after selecting a folder tree for upload
 
![image](https://user-images.githubusercontent.com/41386243/165530568-15d7360d-8322-431b-b6fa-95ab9483d2e6.png)

- After clicking the "X" on advplyr/audiobookshelf-app#7, the Blinding Knife

![image](https://user-images.githubusercontent.com/41386243/165530866-9690d94f-d3a1-4372-b100-7f7c3c12581b.png)

### Environment data
Using web app, chrome and MS Edge

Audiobookshelf Version:
2.0.3 (Linux Docker)

**Comment by advplyr** [comment]
This is fixed in [v2.0.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.4)

**Comment by jonathondk** [comment]
I am still getting this error. v2.0.7

**Comment by advplyr** [comment]
Fix attempt 2 in [v2.0.8](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.8)
