### ISSUE TITLE
[Enhancement]: Under "Recent Listening Sessions" please put the current listen time for that audiobook.

### ISSUE THREAD

**Issue by JamesDean3** [advplyr/audiobookshelf#532]
### Describe the feature/enhancement

I originally posted this in the app github but realized that wasn't the correct place for it, so I'm coping and pasting it here.

Is your feature request related to a problem? Please describe.

When using these new features as we know there can be problems that cause the app to crash or something to go wrong some where along the way, often times that will make us lose our current position in our audiobook and not have the correct position reported anywhere.
Describe the solution you'd like

The "Recent Listening Session" does a great job at telling us how long we listened to something and how long ago it was we listened to it, but if it were to put what our current progress through the audiobook was, we would be able to find our placement after running in to any unexpected issues that caused the app to crash.
Describe alternatives you've considered

I've tried to use the information given in the "Recent Listening Session" to figure out my placement in the audiobook, but I haven't been successful. That and possibility remembering the chapter is the only solutions I can think of.
Additional context

Once things are more stable then I imagine this feature won't be quite as useful, since the actual designated spot should show the current time your at, but I can still see it being useful, for example, you fall asleep and forget to put the sleep timer on, you can see the last place you started at and find your place by moving forward instead of backwards, which could possibility cause you to hear something you would have rather not heard yet.

Thank you for your work in this project, I think it is turning out great

**Comment by advplyr** [comment]
This was added in the latest release. You can now view all of your listening sessions and sessions now store the start time and the last synced time as well as a lot of other info you can view about the session.

The mobile apps still need to be updated since they will also send up the current app version, sdk/ios version and device model.
