### ISSUE TITLE
[Bug]:  Can't go to Series via Search. "Oops... Series not found"

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf#533]
### Describe the issue

If you find for anything in a library, and don't use list view but press Enter. New view will be loaded.  In that view you can find Books and Series.  If you press on Series it will Open.  it returns:  http://localhost:13378/oops?message=Series%20not%20found

### Steps to reproduce the issue

1. Type something in Search 
2. Let ABS find something with Series
3. Dont press on anything
4. Press Enter
5. In new view , press on any Series
6. Series will load with: "Oops... Series not found"

### Audiobookshelf version

2.0.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.8](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.8)
