### ISSUE TITLE
[Bug]: Docker pulled last image but still older version started (2.0.4) 

### ISSUE THREAD

**Issue by digitalwm** [advplyr/audiobookshelf#536]
### Describe the issue

I have done a docker pull on the :latest tag and after restarting the container (docker-compose up) still the 2.0.3 is started and not 2.04

### Steps to reproduce the issue

`
version: "3"
services:
 audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
`

1. docker-compose pull audiobookshelf
2. docker-compose stop
3. docker-compose up -d
4. Version still 2.0.3

### Audiobookshelf version

2.0.4

### How are you running audiobookshelf?

Docker

**Comment by szemlicka** [comment]
Same problem here but the fix from 2.0.4 are inside that image. I checked the problem with the checkboxes. So it looks like only version string is wrong in the docker image

**Comment by digitalwm** [comment]
Thank you for further investigating this.

**Comment by advplyr** [comment]
Thanks yeah that was the problem, still getting used to the new github action workflow. I just pushed 2.0.4 again so if you want to update again that should go away.

**Comment by advplyr** [comment]
Nevermind... the github action is still building one commit behind. Still figuring this out.

**Comment by advplyr** [comment]
We're back on track a few versions ahead with v2.0.7
