### ISSUE TITLE
[Bug]: Podcast does not download episodes

### ISSUE THREAD

**Issue by timconsidine** [advplyr/audiobookshelf#540]
### Describe the issue

New Docker installation self-hosted
App runs and website displayed
No episodes downloaded
Set up NGINX reverse proxy as per docs
Used certbot to add certificate
Sample podcast added shows in Library
Directory structure created
Only downloads cover and metadata : no episodes
Scan and Force Rescan shows green completion flash
No error message in nginx error log

### Steps to reproduce the issue

1. Docker install as per docs
2. NGINX proxy set up as per docs
3. certbot added
4. add podcast via search
5. shows Incomplete on Scan and Force Rescan

### Audiobookshelf version

2.0.7 docker latest

### How are you running audiobookshelf?

Docker

**Comment by timconsidine** [comment]
Re-started docker
Forced re-scan 
No error in nginx error log
App logs show : 
```
2022-04-30 13:28:22
INFO
[Scanner] Starting library scan lscan_9nma8y7ml37ivjbj8t for Podcasts

2022-04-30 13:28:22
ERROR
Root path has no media folders: /audiobooks

2022-04-30 13:28:22
DEBUG
[LibraryItem] Success saving abmetadata to "/audiobooks/FLOSS Weekly (Audio)/metadata.abs"

2022-04-30 13:28:22
DEBUG
[DB] Library Items updated 1

2022-04-30 13:28:22
INFO
[Scanner] Library scan lscan_9nma8y7ml37ivjbj8t completed in 0:00.0 | 0 Added | 0 Updated | 1 Missing

2022-04-30 13:28:22
INFO
[LibraryController] Scan complete

2022-04-30 13:28:22
INFO
[LibraryScan] Scan log saved "/metadata/logs/scans/2022-04-30_lscan_9nma8y7ml37ivjbj8t.txt"
```

Path /audiobooks is mapped in docker run command
Local server path shows entry for podcast (and cover.jpg and metadata)
So confused why it says `Root path has no media folders`

**Comment by advplyr** [comment]
You have to create a new library with the library type of "Podcast". By default the /audiobooks folder will be for library type "Audiobooks" and cannot be deleted.
This will be improved in future updates since Podcasts were just recently added.

**Comment by timconsidine** [comment]
I created the Library but used the /audiobooks folder.
Do you mean I have to create a specific folder on server as well as a Library ?
And also map it in Docker ?

**Comment by advplyr** [comment]
Correct, you have to have an audiobooks library that maps to the /audiobooks folder (that is created by default).
If you want podcasts you need to create a new library with a new path mapped in docker.

**Comment by timconsidine** [comment]
Thank you.
So I created a folder in local server, ~/audioboooks/podcasts, alongside ~/audioboooks/audiobooks.
I adjusted Docker start command to this : 
```
docker run -d \
  -e AUDIOBOOKSHELF_UID=99 \
  -e AUDIOBOOKSHELF_GID=100 \
  -p 13378:80 \
  -v /root/audiobookshelf/audiobooks:/audiobooks \
  -v /root/audiobookshelf/podcasts:/podcasts \
  -v /root/audiobookshelf/config:/config \
  -v /root/audiobookshelf/metadata:/metadata \
  --name audiobookshelf \
  ghcr.io/advplyr/audiobookshelf
```
I created new Library using type podcasts and called it podcasts and set it to search iTunes and set it to /podcasts in app.
All works fine EXCEPT same problem : does not download.
App logs now show `ERROR Root path has no media folders: /podcasts`
Errr, yes it does.
Let me know if I am doing something stupid but this does not smell like a folder/directory issue.

**Comment by timconsidine** [comment]
Seems like it is a sockets issue
But I don't understand why

**Comment by advplyr** [comment]
What does your /podcasts folder look like? Each podcasts needs to be in its own folder.

**Comment by timconsidine** [comment]
Yes, they are.
The app creates the folders.  I assume correctly.
I can see 2 podcast feeds installed as samples.
In the app, the podcast is shown with correct path for e.g. cover.jpg

**Comment by timconsidine** [comment]
error.log shows :
```
2022/04/30 17:26:20 [error] 158864#158864: *1505 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: xx.xx.xx.xx, server: audiobookshelf.domain.tld, request: "GET /socket.io/?EIO=4&transport=websocket HTTP/1.1", upstream: "Http://127.0.0.1:13378/socket.io/?EIO=4&transport=websocket", host: "audiobookshelf.domain.tld"
```

**Comment by advplyr** [comment]
The web socket shouldn't be required to download episodes, unless that is causing the server to crash.

You are going to the podcast page and pressing the search button and downloading episodes from there? Can you check the logs when you do that? You should see logs referring to your request to download.

**Comment by timconsidine** [comment]
Manually doing rescan on one podcast :
```
2022-04-30 18:37:01
INFO
[Scanner] Scanning Library Item "FLOSS Weekly (Audio)"

2022-04-30 18:37:01
DEBUG
[LibraryItem] Success saving abmetadata to "/podcasts/FLOSS Weekly (Audio)/metadata.abs"

2022-04-30 18:37:01
DEBUG
[DB] Library Items updated 1
```
But no feed shows no episodes and red swatch/button 'Incomplete' 


Settings --> Libraries --> Podcasts --> Force Re-scan : 
```
2022-04-30 18:39:32
INFO
[Scanner] Starting library scan lscan_1fplc1o2qsoywxztv0 for Podcasts

2022-04-30 18:39:32
ERROR
Root path has no media folders: /podcasts

2022-04-30 18:39:33
DEBUG
[LibraryItem] Success saving abmetadata to "/podcasts/Ukraine: The Latest/metadata.abs"

2022-04-30 18:39:33
DEBUG
[LibraryItem] Success saving abmetadata to "/podcasts/FLOSS Weekly (Audio)/metadata.abs"

2022-04-30 18:39:33
DEBUG
[DB] Library Items updated 2

2022-04-30 18:39:33
INFO
[Scanner] Library scan lscan_1fplc1o2qsoywxztv0 completed in 0:00.0 | 0 Added | 0 Updated | 2 Missing

2022-04-30 18:39:33
INFO
[LibraryController] Scan complete

2022-04-30 18:39:33
INFO
[LibraryScan] Scan log saved "/metadata/logs/scans/2022-04-30_lscan_1fplc1o2qsoywxztv0.txt"
```
NB : still getting `Root path has no media folders: /podcasts`

<Scratches head>

**Comment by timconsidine** [comment]
Red flag on podcast feed used to say Incomplete.  Now says Missing.
But : 
```
root@xxxxx:~/audiobookshelf# tree podcasts
podcasts
├── FLOSS Weekly (Audio)
│   ├── cover.jpg
│   └── metadata.abs
└── Ukraine: The Latest
    ├── cover.jpg
    └── metadata.abs

2 directories, 4 files
```

**Comment by advplyr** [comment]
What files are in the `/podcasts/FLOSS Weekly (Audio)/` folder?

**Comment by timconsidine** [comment]
See tree output above.
Just cover.jpg and metdata.abs

**Comment by timconsidine** [comment]
Not sure if important but "fullPath" in the podcast json file does not show the podcast folder

```
less config/libraries/data/data.0.json
{"id":"lib_jrmsltvpfquvj75fgc","name":"Podcasts","folders":[{"id":"fol_nxef28k3mkjob3dp2h","fullPath":"/podcasts","libraryId":"lib_jrmsltvpfquvj75fgc","addedAt":1651339624275}],"displayOrder":2,"icon":"podcast","mediaType":"podcast","provider":"itunes","settings":{"disableWatcher":false,"skipMatchingMediaWithAsin":false,"skipMatchingMediaWithIsbn":false},"createdAt":1651272811148,"lastUpdate":1651339624275}
```

**Comment by advplyr** [comment]
Did you specifically select episodes you wanted to download?
Adding a podcast alone doesn't download any audio files.

**Comment by timconsidine** [comment]
I did not get shown a list of episodes to download.
Clicking on a specific podcast shows all its 'header' info, but clicking on the episodes tab shows no episodes.
So can't specifically select an episode.
Just trashed the install and re-run it.
Same behaviour : podcast created (very nicely) from search, folder created by app, cover.jpg and metadata download.
But no episodes shown in list

**Comment by timconsidine** [comment]
<img width="1537" alt="Screenshot 2022-04-30 at 20 37 47" src="https://user-images.githubusercontent.com/28682881/166120248-c0f305d7-4ac6-4aa2-9108-003369a71fe6.png">
<img width="1537" alt="Screenshot 2022-04-30 at 20 37 13" src="https://user-images.githubusercontent.com/28682881/166120253-960b109b-53cb-438a-9e65-1c893b5f57d5.png">
<img width="1531" alt="Screenshot 2022-04-30 at 20 36 56" src="https://user-images.githubusercontent.com/28682881/166120254-3e27c11c-e786-41d9-976d-7b57b2da4247.png">

**Comment by advplyr** [comment]
Have you tried clicking the search icon to the right of the edit button?

**Comment by timconsidine** [comment]
Errr.
No.
God, I'm so sorry.
But in my defence, I think this is a UI issue
There is no search button on the Episodes tab.
And UI messages in red like `Incomplete` or `Missing` and log messages like `Root path has no media folders: /podcasts` pointed me in the wrong direction.
There are excellent screen buttons like [Scan Library] elsewhere.
The Episode tab and the Episode list should have something similar.

Anyway, thanks so much for your patience and your support.
And thank you for such a nice app : beats my previous setup (Jellyfin and bashpodder). 👍 
Hope my idiocy is helpful to suggest some UI improvement.
Closing this now.

**Comment by advplyr** [comment]
No problem, podcasts being so new there are many UI improvements to make. Thanks for the suggestions.

**Comment by snonux** [comment]
Just stumbled on the same issue, that Podcasts were not downloaded. After reading this issue, I was able to resolve it (was a user error, not finding the correct buttons). I am very happy with Audiobookshelf so far!

**Comment by kyelewis** [comment]
Thank-you, I also had no idea how to retrieve podcasts until I found this issue, the circle icon doesn't represent anything to do with fetching episodes to me.. maybe just a big "find episodes to download" button where the "no episodes" text is would be clearer. 

Haven't looked in to audiobookshelf far enough yet to look at making a PR but I'll kick the idea around my head this weekend.

**Comment by nichwall** [comment]
> Thank-you, I also had no idea how to retrieve podcasts until I found this issue, the magnifying glass 'search' icon doesn't represent anything to do with fetching episodes to me.. maybe just a big "find episodes to download" button where the "no episodes" text is would be clearer. 
> 
> Haven't looked in to audiobookshelf far enough yet to look at making a PR but I'll kick the idea around my head this weekend.

There is this documentation as well. The website needs some more guides if you think of other things that can be added and might reorganized soon so guides are easier to find.
https://www.audiobookshelf.org/guides/podcasts
