### ISSUE TITLE
[Bug]: Version mismatch between showed in Frontend and Backend

### ISSUE THREAD

**Issue by digitalwm** [advplyr/audiobookshelf#544]
### Describe the issue

Backend has version 2.0.8 - source docker Github

- audiobookshelf  |
- audiobookshelf  | > audiobookshelf@2.0.8 start
- audiobookshelf  | > node index.js
- audiobookshelf  |
- audiobookshelf  | Config /config /metadata /audiobooks
- audiobookshelf  | [2022-04-30T19:42:10.398Z]  INFO: === Starting Server ===
- audiobookshelf  | [2022-04-30T19:42:10.399Z]  INFO: [Server] Init v2.0.8
- audiobookshelf  | [2022-04-30T19:42:10.608Z]  INFO: [DB] 4 Users Loaded
- audiobookshelf  | [2022-04-30T19:42:10.609Z]  INFO: [DB] 1 Libraries Loaded
- audiobookshelf  | [2022-04-30T19:42:10.610Z]  INFO: [DB] 1 Collections Loaded
- audiobookshelf  | [2022-04-30T19:42:10.626Z]  INFO: [DB] 383 Authors Loaded
- audiobookshelf  | [2022-04-30T19:42:10.637Z]  INFO: [DB] 387 Series Loaded
- audiobookshelf  | [2022-04-30T19:42:11.634Z]  INFO: [DB] 2082 Library Items Loaded
- audiobookshelf  | [2022-04-30T19:42:11.669Z]  INFO: [Db] Root user exists, pw: true
- audiobookshelf  | [2022-04-30T19:42:12.187Z]  INFO: [BackupManager] 2 Backups Found

Frontend shows version 2.0.3

![Screenshot 2022-05-01 114406](https://user-images.githubusercontent.com/1193701/166140676-2f99305f-ee8d-49f2-a401-9d469f4de6c9.jpg)

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.0.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I think this was an issue with the github workflow cache. I just pushed v2.0.9 if you want to try that and see if it persists.

**Comment by advplyr** [comment]
I believe this to be resolved now with the latest updates, but let me know if it persists.

**Comment by digitalwm** [comment]
Works. Thank you
