### ISSUE TITLE
[Enhancement]: author: without update permission

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#549]
### Describe the feature/enhancement

this is a suggestion: if an user have no permission to update ("Can Update") and the user like to update an author > it comes a popup with "author not found" (in any case > new/empty or existing) >>> better way: "u have no permission to edit / update the author" or anything similar ...

**Comment by advplyr** [comment]
Fixed in [v2.0.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.9)
