### ISSUE TITLE
[Enhancement]: Add the ability to "re-broadcast" or "re-host" podcasts with an RSS feed

### ISSUE THREAD

**Issue by Cairxoxo** [advplyr/audiobookshelf#553]
### Describe the feature/enhancement

Audiobookshelf is already fantastic and extremely polished for what it is, but I think an absolutely killer feature would be the ability to host your own RSS feeds from downloaded podcasts, which would allow them to be read by standard podcatcher apps like Overcast, Pocketcast etc rather than just the native Audiobookshelf app.

The logic flow would then be:

1. Add Podcast to Audiobookshelf
2. Audiobookshelf downloads episodes/monitors new episodes
3. RSS feed hosted from Audiobookshelf - could be accomplished as subfolders from main domain perhaps? i.e. https://audiobookshelf.domain.com/custompodcastrssurlgoeshere
4. Add RSS URL to podcatcher app of choice

This would be perfect in instances such as Dan Carlin's Hardcore History or downloaded Patreon/Stitcher Premium podcasts, where the optimal listening experience is via dedicated podcast apps.

**Comment by advplyr** [comment]
As discussed in discord, this is in [v2.0.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.9) as experimental.

![rssfeed](https://user-images.githubusercontent.com/67830747/166367382-c589abe2-f143-4d0b-8e0f-9194c6b89daa.gif)

RSS feeds are generated with a random ID in the URL. This can be improved by using a user-defined ID or using the library item ID. We can also add a form of authentication in the URL.

Only admin users and root can open/close a podcast feed, but any user will be able to see the RSS feed button if it is open and view the URL.

Great start!

**Comment by Cairxoxo** [comment]
Tested originally on [v2.0.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.9) and now upgraded to [v2.0.10](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.10).

Custom slugs work great - solves the issue of URLs changing when restarting the server. As discussed on discord, Pocketcasts streaming doesn't play nice, but if you download the episode it downloads and plays flawlessly. Metadata such as titles, descriptions, and even custom episode numbering all feed through and are recognised perfectly.

The only other issue I've noticed is with artwork. In Pocketcasts, the artwork never appears to load at all (even if you refresh it directly in the app). In Overcast, the artwork doesn't show when looking at the show, but **does** show when you play an episode. Streaming vs Downloading also works in Overcast fine.

**Comment by advplyr** [comment]
I just got Pocket Casts on android to test and the cover art was showing and had no problems with streaming.

Pocket Casts requires submitting the RSS feed to them first and they give you another URL to use which is not something I've seen before. Most other podcast apps will let you enter the URL directly.
One thing to note though is that Pocket Casts required me to have a pubDate and a description (I didn't test either or so might have just been the pubDate).

I was implementing the cached cover art when I realized that iTunes requires cover art at least 1600x1600 and most cover arts that I looked at were large, so I don't think we need to compress covers for podcasts we can use the image directly.

Are you using iOS or Android?

Have you tried using any other podcast apps or even tried any other devices to check whether this is isolated to Pocket Casts or your device? You can also test in the browser using Google Podcasts podcasts.google.com.
You can just enter your podcast feed directly in these other apps.

**Comment by advplyr** [comment]
This was moved out of experimental in [v2.0.13](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.13).

I believe the issues you are coming across are specific to your device or connection.

**Comment by ofifoto** [comment]
How does one add a RSS feed url to mirror?

**Comment by advplyr** [comment]
I don't understand the question

**Comment by ofifoto** [comment]
In OP 1/2 say add a podcast and audiobookshelf could monitor/download new episodes - is this possible? Say if I wanted to add https://feeds.99percentinvisible.org/99percentinvisible and have ABS download that podcast and make it available for listening

**Comment by advplyr** [comment]
Yes it is possible, it has nothing to do with this issue request though.
Create a podcast library then press the button named "Search" in the siderail. Paste in your RSS feed url.

**Comment by ofifoto** [comment]
Ahh! Thanks :). Sorry about that
