### ISSUE TITLE
[Enhancement]: Sort Library by audiobook length

### ISSUE THREAD

**Issue by jonathondk** [advplyr/audiobookshelf#558]
### Describe the feature/enhancement

There is already a sort by size, but not by length. It can be good to pick an audiobook that you want to listen to on a car trip that will be a specific length. I couldn't find a way to filter or sort by length.

**Comment by advplyr** [comment]
Added in [v2.0.10](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.10)
