### ISSUE TITLE
[Bug]: Can't mark Podcast as Finished

### ISSUE THREAD

**Issue by geekedtv** [advplyr/audiobookshelf#559]
### Describe the issue

There's not a way to mark a Podcast episode as finished on the Podcast home page.

![raw](https://user-images.githubusercontent.com/57927413/166516969-ddc4c499-053a-41dc-8078-e2585f4ead2c.png)

You can do this with Audiobooks

![abooks](https://user-images.githubusercontent.com/57927413/166517059-8916f0c8-6bfa-48ce-98ee-bfb03dad7454.png)

### Steps to reproduce the issue

1. Go to the Podcast home page and look :

### Audiobookshelf version

v2.0.9

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Added in [v2.0.10](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.10)
