### ISSUE TITLE
Enhancement: Add a little dot to your chapter highlight

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#56]
I love the little tweaks being made to make this more powerful and at the same time, easy to use. Keep it up!

My suggestion comes because while testing your recently added feature of having the currently playing chapter highlighted in the chapter's modal, I noticed that it was trickier to spot the highlight.

Maybe you could change the color of the highlight, or just add a little dot, like so:
![image](https://user-images.githubusercontent.com/25695143/134534639-817e542e-704e-4cd1-92c9-144f71d7920b.png)

What do you think?

**Comment by advplyr** [comment]
Agree. I think making the highlight lighter and adding a 4 pixel yellow line on the left.
I also planned on having it open already scrolled to the current chapter.

**Comment by advplyr** [comment]
Added in [`v1.2.1`](https://github.com/advplyr/audiobookshelf/releases/tag/v1.2.1) with scrolled to current chapter.

![image](https://user-images.githubusercontent.com/67830747/134740554-2886ab46-7e70-45eb-bd51-b02dc24a3a39.png)

**Comment by Kudjo-Grand** [comment]
You're a rockstar! It looks great
