### ISSUE TITLE
[Bug]: Drag and Drop Upload tracks seemingly limited

### ISSUE THREAD

**Issue by 77boaz** [advplyr/audiobookshelf#560]
### Describe the issue

When uploading a book via the drag-n-drop.. (Which I might add is a great feature),  Audiobooks over 100 tracks only listed as 100 tracks.  Uploaded and said that they were complete.  But some tracks were dropped and/or missing.  For instance I uploaded a book that had around 130 tracks but it still showed only 100.  However, if I moved it directly to the folder from the back end linux terminal, it then would show all 130 tracks.  I tried dragging and dropping multiple in the same series same author and it still only showed 100 tracks.  Just to test I also dropped a single book with more than 100 tracks and it did the same.  All terminal back end linux copying still works showing all of the tracks.  Thanks!

### Steps to reproduce the issue

1. click the upload UP arrow in the upper right corner.
2. Drag an entire audiobook whether it be a part of a series or the book itself over.  Only 100 tracks show.

### Audiobookshelf version

v2.0.8

### How are you running audiobookshelf?

Docker

**Comment by 77boaz** [comment]
Man you're fast!  Where can I donate? :-)

**Comment by 77boaz** [comment]
Yay!

**Comment by advplyr** [comment]
Fixed in [v2.0.10](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.10)
