### ISSUE TITLE
[Enhancement]:  Add: Can Access All Genres 

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf#565]
### Describe the feature/enhancement

Let define which type of genres can be accesed per user. 
why? :   to let kids access only few genres appropiate for them or limit erotic books from someone who should not see them despite of age.   

Adding another account type: kids  , could be useful.

**Comment by advplyr** [comment]
I think the main use-case for this is restricting explicit content which was added in the latest release.
At this point I think adding restrictions by genre would be overkill. More support will be added to tags to allow restricting certain tags instead of having to set allow on specific tags.
