### ISSUE TITLE
[Bug]: docker died if I start a simple re-scan of the library

### ISSUE THREAD

**Issue by szemlicka** [advplyr/audiobookshelf#566]
### Describe the issue

When I start a rescan of my library, at one point the docker container died. At the terminal I can see before it died a lot of messages like 
`[2022-05-05T14:43:38.955Z] DEBUG: [LibraryItem] Success saving abmetadata to "/audiobooks/books/files/Robert A. Heinlein/Revolte auf Luna/metadata.abs"`

This is the latest messages that I can find before it died

2```
022-05-05 15:08:23 | stderr | at async Scanner.scanLibrary (/server/scanner/Scanner.js:269:7)
-- | -- | --
2022-05-05 15:08:23 | stderr | at Scanner.updateLibraryItemChunk (/server/scanner/Scanner.js:286:10)
2022-05-05 15:08:23 | stderr | at Server.emitter (/server/Server.js:108:13)
2022-05-05 15:08:23 | stderr | at Server.<computed> [as emit] (/node_modules/socket.io/dist/index.js:576:33)
2022-05-05 15:08:23 | stderr | at Namespace.emit (/node_modules/socket.io/dist/namespace.js:170:73)
2022-05-05 15:08:23 | stderr | at BroadcastOperator.emit (/node_modules/socket.io/dist/broadcast-operator.js:109:22)
2022-05-05 15:08:23 | stderr | at Adapter.broadcast (/node_modules/socket.io-adapter/dist/index.js:107:45)
2022-05-05 15:08:23 | stderr | at Encoder.encode (/node_modules/socket.io-parser/dist/index.js:45:22)
2022-05-05 15:08:23 | stderr | at Encoder.encodeAsString (/node_modules/socket.io-parser/dist/index.js:69:25)
2022-05-05 15:08:23 | stderr | at JSON.stringify (<anonymous>)
2022-05-05 15:08:23 | stderr | RangeError: Invalid string length
2022-05-05 15:08:23 | stderr |  
2022-05-05 15:08:23 | stderr | ^
2022-05-05 15:08:23 | stderr | throw error;
2022-05-05 15:08:23 | stderr | /server/njodb/index.js:103
2022-05-05 15:07:51 | stdout | [2022-05-05T15:07:51.704Z] DEBUG: [DB] Library Items updated 5803

```




### Steps to reproduce the issue

1. Just simple start a library scan

### Audiobookshelf version

v2.0.10

### How are you running audiobookshelf?

Docker

**Comment by szemlicka** [comment]
At the moment it is useless for me. I cannot add new audiobooks. every scan end up in a crashed container.

**Comment by 77boaz** [comment]
I 2nd this bug.  It crashes the docker container if running docker.  It did manage to scan a few books.. but it won't complete.

**Comment by szemlicka** [comment]
After I purge the DB and start from fresh, it reslove the problem. So there was something with the DB.

**Comment by 77boaz** [comment]
Interesting... So I set it up on a new fresh install and it just crashed.  I keep trying and can't scan my entire library only parts, because it keeps dying..

**Comment by advplyr** [comment]
Are there any error logs you can provide?

**Comment by 77boaz** [comment]
Sure where are the best logs located?  I only see the ones in the GUI..

**Comment by advplyr** [comment]
If your server is crashing the best place to get logs is from the docker container.
Abs stores its own logs in /metadata/logs/daily and we could use that to at least see what happened leading up to the crash

**Comment by 77boaz** [comment]
Duh.. I should have known that.. Attached the two files it made.  This was on a separate installation brand new from the most recent docker version.. Thanks!
[daily.tar.gz](https://github.com/advplyr/audiobookshelf/files/8647788/daily.tar.gz)
.

**Comment by advplyr** [comment]
The logs are going to need to be put in here directly so that a download isn't necessary. The only useful part is going to be the last ~30 lines or so before the crash.

**Comment by 77boaz** [comment]
Sorry.. Here's directly..

{"timestamp":"2022-05-06T22:55:37.837Z","message":"[BackupManager] Auto Backups are disabled","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:55:37.843Z","message":"[LogManager] Init current daily log filename: 2022-05-06.txt","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:55:37.852Z","message":"[Watcher] Initializing watcher for \"Main\".","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:55:37.893Z","message":"Listening on http://0.0.0.0:80","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:55:39.484Z","message":"[Watcher] \"Main\" Ready","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:55:45.238Z","message":"[Server] Socket Connected vDUDDzeQk4udP5q7AAAB","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:57:24.565Z","message":"[Scanner] Starting library scan lscan_ljcmz8udxm8armw8kk for Main","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.540Z","message":"=== Starting Server ===","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.541Z","message":"[Server] Init v2.0.11","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.592Z","message":"[DB] 0 Collections Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.593Z","message":"[DB] 0 Series Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.733Z","message":"[DB] 1 Libraries Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.737Z","message":"[DB] 10 Authors Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.744Z","message":"[DB] 9 Library Items Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.746Z","message":"[DB] 1 Users Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.747Z","message":"[Db] Root user exists, pw: false","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.751Z","message":"[BackupManager] 0 Backups Found","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.752Z","message":"[BackupManager] Auto Backups are disabled","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.757Z","message":"[LogManager] Init current daily log filename: 2022-05-06.txt","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.766Z","message":"[Watcher] Initializing watcher for \"Main\".","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:32.800Z","message":"Listening on http://0.0.0.0:80","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:34.368Z","message":"[Watcher] \"Main\" Ready","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:35.688Z","message":"[Server] Socket Connected hUEtsOYwTU1WhvLuAAAB","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:58:55.272Z","message":"[Server] Socket hUEtsOYwTU1WhvLuAAAB disconnected from client \"root\" after 19586ms","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T22:59:42.493Z","message":"[Server] Socket Connected YvasxF-sUwI9ziVNAAAD","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T23:00:59.505Z","message":"[Server] Socket YvasxF-sUwI9ziVNAAAD disconnected from client \"root\" after 77011ms","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T23:01:07.840Z","message":"[Server] Socket Connected BUl9K3x3R_R84gH7AAAF","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T23:05:23.615Z","message":"[Server] Socket BUl9K3x3R_R84gH7AAAF disconnected from client \"root\" after 255777ms","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T23:05:24.499Z","message":"[Server] Socket Connected 1HCNVRSzX8yUwg6XAAAH","levelName":"INFO","level":2}
{"timestamp":"2022-05-06T23:05:25.614Z","message":"[Server] Socket 1HCNVRSzX8yUwg6XAAAH disconnected from client \"root\" after 1117ms","levelName":"INFO","level":2}

**Comment by advplyr** [comment]
Unfortunately the internal logs aren't providing anything useful. We would need to look at the docker container logs.

**Comment by 77boaz** [comment]
Are just the jsons fine?

**Comment by 77boaz** [comment]
config.v2.json 

{"StreamConfig":{},"State":{"Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"RemovalInProgress":false,"Dead":false,"Pid":19369,"ExitCode":0,"Error":"","StartedAt":"2022-05-07T21:00:08.489497849Z","FinishedAt":"0001-01-01T00:00:00Z","Health":null},"ID":"a22dc00304cefaf362ab72f97780eb9b0eb15ecd38a9922302ba60680920c6cf","Created":"2022-05-07T21:00:06.704960826Z","Managed":false,"Path":"docker-entrypoint.sh","Args":["npm","start"],"Config":{"Hostname":"a22dc00304ce","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"80/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["AUDIOBOOKSHELF_UID=99","AUDIOBOOKSHELF_GID=100","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","NODE_VERSION=16.15.0","YARN_VERSION=1.22.18","NODE_ENV=production"],"Cmd":["npm","start"],"Image":"ghcr.io/advplyr/audiobookshelf","Volumes":null,"WorkingDir":"","Entrypoint":["docker-entrypoint.sh"],"OnBuild":null,"Labels":{}},"Image":"sha256:a9f1645e7e77c602971a22efc390a86be856d237dcf5a0d519f83a5839cf5b89","NetworkSettings":{"Bridge":"","SandboxID":"bc8f345742e54cd2ea134a207eec8fa91f9f99217de5070f2bc2af560073458b","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"aa7e2656c0d1efe8eefdd7c84a33b8fc6263307c4dc21568fb80e6e43fc570c7","EndpointID":"8050baae2e7de2c5d32b7daeafdce0f80fb214a66d0c8050857e6efcf499c207","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02","DriverOpts":null,"IPAMOperational":false}},"Service":null,"Ports":{"80/tcp":[{"HostIp":"0.0.0.0","HostPort":"13378"},{"HostIp":"::","HostPort":"13378"}]},"SandboxKey":"/var/run/docker/netns/bc8f345742e5","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"IsAnonymousEndpoint":false,"HasSwarmEndpoint":false},"LogPath":"","Name":"/audiobookshelf","Driver":"overlay2","OS":"linux","MountLabel":"system_u:object_r:container_file_t:s0:c74,c578","ProcessLabel":"system_u:system_r:container_t:s0:c74,c578","RestartCount":0,"HasBeenStartedBefore":true,"HasBeenManuallyStopped":false,"MountPoints":{"/audiobooks":{"Source":"/data/audiobookshelf/audiobooks","Destination":"/audiobooks","RW":true,"Name":"","Driver":"","Type":"bind","Propagation":"rprivate","Spec":{"Type":"bind","Source":"/data/audiobookshelf/audiobooks","Target":"/audiobooks"},"SkipMountpointCreation":false},"/config":{"Source":"/data/audiobookshelf/config","Destination":"/config","RW":true,"Name":"","Driver":"","Type":"bind","Propagation":"rprivate","Spec":{"Type":"bind","Source":"/data/audiobookshelf/config","Target":"/config"},"SkipMountpointCreation":false},"/metadata":{"Source":"/data/audiobookshelf/metadata","Destination":"/metadata","RW":true,"Name":"","Driver":"","Type":"bind","Propagation":"rprivate","Spec":{"Type":"bind","Source":"/data/audiobookshelf/metadata","Target":"/metadata"},"SkipMountpointCreation":false}},"SecretReferences":null,"ConfigReferences":null,"AppArmorProfile":"","HostnamePath":"/var/lib/docker/containers/a22dc00304cefaf362ab72f97780eb9b0eb15ecd38a9922302ba60680920c6cf/hostname","HostsPath":"/var/lib/docker/containers/a22dc00304cefaf362ab72f97780eb9b0eb15ecd38a9922302ba60680920c6cf/hosts","ShmPath":"","ResolvConfPath":"/var/lib/docker/containers/a22dc00304cefaf362ab72f97780eb9b0eb15ecd38a9922302ba60680920c6cf/resolv.conf","SeccompProfile":"","NoNewPrivileges":false,"LocalLogCacheMeta":{"HaveNotifyEnabled":true}}

hostconfig.json

{"Binds":["/data/audiobookshelf/audiobooks:/audiobooks","/data/audiobookshelf/config:/config","/data/audiobookshelf/metadata:/metadata"],"ContainerIDFile":"","LogConfig":{"Type":"journald","Config":{}},"NetworkMode":"default","PortBindings":{"80/tcp":[{"HostIp":"","HostPort":"13378"}]},"RestartPolicy":{"Name":"no","MaximumRetryCount":0},"AutoRemove":true,"VolumeDriver":"","VolumesFrom":null,"CapAdd":null,"CapDrop":null,"CgroupnsMode":"private","Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"private","Cgroup":"","Links":null,"OomScoreAdj":0,"PidMode":"","Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"SecurityOpt":null,"UTSMode":"","UsernsMode":"","ShmSize":67108864,"Runtime":"runc","ConsoleSize":[0,0],"Isolation":"","CpuShares":0,"Memory":0,"NanoCpus":0,"CgroupParent":"","BlkioWeight":0,"BlkioWeightDevice":[],"BlkioDeviceReadBps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteIOps":null,"CpuPeriod":0,"CpuQuota":0,"CpuRealtimePeriod":0,"CpuRealtimeRuntime":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DeviceCgroupRules":null,"DeviceRequests":null,"KernelMemory":0,"KernelMemoryTCP":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":null,"OomKillDisable":null,"PidsLimit":null,"Ulimits":null,"CpuCount":0,"CpuPercent":0,"IOMaximumIOps":0,"IOMaximumBandwidth":0,"MaskedPaths":["/proc/asound","/proc/acpi","/proc/kcore","/proc/keys","/proc/latency_stats","/proc/timer_list","/proc/timer_stats","/proc/sched_debug","/proc/scsi","/sys/firmware"],"ReadonlyPaths":["/proc/bus","/proc/fs","/proc/irq","/proc/sys","/proc/sysrq-trigger"]}

**Comment by szemlicka** [comment]
Hi, server crashed again. Looks like there is a general problem. Last log line was :
<html><body>


date | stream | content
-- | -- | --
2022-05-09 08:10:14 | stderr | at async Scanner.scanLibrary (/server/scanner/Scanner.js:269:7)
2022-05-09 08:10:14 | stderr | at Scanner.updateLibraryItemChunk (/server/scanner/Scanner.js:286:10)
2022-05-09 08:10:14 | stderr | at Server.emitter (/server/Server.js:108:13)
2022-05-09 08:10:14 | stderr | at Server.<computed> [as emit] (/node_modules/socket.io/dist/index.js:576:33)
2022-05-09 08:10:14 | stderr | at Namespace.emit (/node_modules/socket.io/dist/namespace.js:170:73)
2022-05-09 08:10:14 | stderr | at BroadcastOperator.emit (/node_modules/socket.io/dist/broadcast-operator.js:109:22)
2022-05-09 08:10:14 | stderr | at Adapter.broadcast (/node_modules/socket.io-adapter/dist/index.js:107:45)
2022-05-09 08:10:14 | stderr | at Encoder.encode (/node_modules/socket.io-parser/dist/index.js:45:22)
2022-05-09 08:10:14 | stderr | at Encoder.encodeAsString (/node_modules/socket.io-parser/dist/index.js:69:25)
2022-05-09 08:10:14 | stderr | at JSON.stringify (<anonymous>)
2022-05-09 08:10:14 | stderr | RangeError: Invalid string length
2022-05-09 08:10:14 | stderr |  
2022-05-09 08:10:14 | stderr | ^
2022-05-09 08:10:14 | stderr | throw error;
2022-05-09 08:10:14 | stderr | /server/njodb/index.js:103
2022-05-09 08:09:55 | stdout | [2022-05-09T08:09:55.549Z] DEBUG: [DB] Library Items updated 3013


</body>
</html>

**Comment by szemlicka** [comment]
Fixed with v2.0.12

**Comment by szemlicka** [comment]
Fixed with v2.0.12

**Comment by 77boaz** [comment]
This seems to still be happening to me in the latest docker version... It could be just me though...

**Comment by datagutten** [comment]
I got the same issue after adding a specific book. The book had some text in the "composer" id3 field, after removing that I was able to run a scan without problems.
