### ISSUE TITLE
[Bug]: Manage Track screen no longer loads (error in console)

### ISSUE THREAD

**Issue by galacticat** [advplyr/audiobookshelf#567]
### Describe the issue

When the manage track dialog is opened an error is thrown in the console and the page doesn't load
[https://i.imgur.com/mso2Lso.png](url)

### Steps to reproduce the issue

1. Open any book
2. In the Audiobook Tracks section, click Manage Tracks

### Audiobookshelf version

v2.0.10

### How are you running audiobookshelf?

Docker

**Comment by szemlicka** [comment]
Same error here. I am using the docker v2.0.10 version

**Comment by advplyr** [comment]
Fixed in [v2.0.11](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.11)
