### ISSUE TITLE
Enhancement: Segmented streaming 

### ISSUE THREAD

**Issue by Jdiesel87** [advplyr/audiobookshelf#57]
First off thanks for the great project. A self-hosted audiobook platform is greatly needed and currently underserved. I hope this project takes off and I will be following closely and assisting where I can.

I don't know the correct terminology but I have noticed that when playing m4b files on a remote network through the Android app the entire file is downloaded in advance rather than it caching and beginning playback as soon as enough data is available. Is this a limitation of the mb4 file format? If so are there other options to remux or transcode into a container or format that supports this?

**Comment by advplyr** [comment]
Thanks for supporting the project. I just added install instructions to the [readme](https://github.com/advplyr/audiobookshelf#linux-amd64-install) for linux users not using docker.

I'm not sure what you mean exactly. There are 2 ways to play an audiobook in the app, from a download or from a stream on the server.
Buffering and caching for streams is handled by the audio player ([ExoPlayer](https://github.com/google/ExoPlayer)). The file isn't getting downloaded, your server transcodes the file into an HLS stream and the audio player requests segments as needed.
What do you mean with the file is downloaded?

**Comment by Jdiesel87** [comment]
Hey looks like it is working for me now. When I was first testing the files were failing to start playing on my remote network. I thought the entire m4b was being sent to my android device prior to playback starting and thus the delay. I tried again today and playback started within a few seconds. Maybe it was an issue with my reverse proxy? Does the app use a websocket or any special headers that need to be passed through?

**Comment by advplyr** [comment]
Yes the app and the main web gui relies heavily on a socket.io connection. The login won't be successful until the socket connection is established.

**Comment by Jdiesel87** [comment]
Thanks. Turns out this is not an issue but a user error
