### ISSUE TITLE
[Bug]: ASIN & ISBN settings for podcasts

### ISSUE THREAD

**Issue by jflattery** [advplyr/audiobookshelf#573]
### Describe the issue

The `Skip matching books that already have an (ASIN | ISBN)` settings found on a library media type of `Podcast` should not display these options.

### Steps to reproduce the issue

1. Visit `/config/libraries`
2. Go to the Edit settings page of a `Podcast` media type library 
3. View settings not appropriate for library type

### Audiobookshelf version

v2.0.11

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Nice catch
