### ISSUE TITLE
[Bug]:Edit GUI issue

### ISSUE THREAD

**Issue by BDaddyG** [advplyr/audiobookshelf#574]
### Describe the issue

While editing an audiobook, I'm having an issue where fields of the GUI are covered.

![ksnip_20220508-125913](https://user-images.githubusercontent.com/29808864/167309328-d739e2cf-1228-4661-b32e-80d94041933f.png)

Thinking back, I've had this issue since I started using ABS v2.0.6, and only discovered it when I zoomed out my browser window which showed the above.

Running the docker on unRAID

### Steps to reproduce the issue

1. Edit any audiobook

### Audiobookshelf version

2.0.11

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.12)
