### ISSUE TITLE
[Enhancement]: Allow saving of details without closing modal

### ISSUE THREAD

**Issue by jberlyn** [advplyr/audiobookshelf#575]
### Describe the feature/enhancement

When you are editing the metadata of a book, if you switch tabs without hitting the Submit button, your data will be lost. It would be great if changes were saved when you click off a field you're editing, or if there was a button you could click to save your changes without closing the modal, which is how the Submit button currently works.

I've attached a screenshot of the screen in question.
![image](https://user-images.githubusercontent.com/10014944/167323590-11d5dff2-7f8c-4e91-9f24-a53618999d88.png)

**Comment by advplyr** [comment]
Added in [v2.0.12](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.12)
