### ISSUE TITLE
[Bug]: AUDIOBOOKSHELF_UID & AUDIOBOOKSHELF_GID values not being honored

### ISSUE THREAD

**Issue by wshyang** [advplyr/audiobookshelf#584]
### Describe the issue

I started a container following the sample docker command provided on the main page

`docker run -d \
    -e AUDIOBOOKSHELF_UID=65500 \
    -e AUDIOBOOKSHELF_GID=65500 \
    -p 13378:80 \
    -v $PWD/audiobooks:/audiobooks \
    -v $PWD/config:/config \
    -v $PWD/metadata:/metadata \
    --name audiobookshelf \
    --rm ghcr.io/advplyr/audiobookshelf`

However subsequently when checking the contents of the files created in the volumes, I found that they are all created under root:root. It appears that within the container itself, the process is running as root too.

### Steps to reproduce the issue

1. `docker run -d \
    -e AUDIOBOOKSHELF_UID=65500 \
    -e AUDIOBOOKSHELF_GID=65500 \
    -p 13378:80 \
    -v $PWD/audiobooks:/audiobooks \
    -v $PWD/config:/config \
    -v $PWD/metadata:/metadata \
    --name audiobookshelf \
    --rm ghcr.io/advplyr/audiobookshelf`
2. Check permissions of created files

### Audiobookshelf version

2.0.12

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
A lot of updates were made to setting ownership of files/folders created by abs. If this is still an issue we can re-open this but please provide specific folders/files that are not set correctly.

**Comment by advplyr** [comment]
@raviolispy Thanks. I can confirm the database files being created in /config and the logs in /metadata/logs are not getting the ownership set correctly.

**Comment by advplyr** [comment]
Fixed in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)
