### ISSUE TITLE
[Bug]: Filter: "Issues" is displayed until its removed

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#585]
### Describe the issue

If i select the Filter "Issues" on the library tab, there can i read in red: "Remove All 0 Books ... but if i go to Series - without clear Filter -  there i can read "Remove All X Books" ... this also happens on collection tab "Remove All X Collections"

### Steps to reproduce the issue

1. every time u select the filter up to u remove the filter (u can go around and com back)

### Audiobookshelf version

v2.0.12

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.13](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.13)
