### ISSUE TITLE
[Bug]: Docker image crashing during both scan or re-scan

### ISSUE THREAD

**Issue by 77boaz** [advplyr/audiobookshelf#587]
### Describe the issue

Docker image crashes during scan or re-scan.  This has been an issue for me since version 2.0.11 when someone else reported it.
![Screenshot from 2022-05-12 16-38-59](https://user-images.githubusercontent.com/46000001/168164493-31841a26-c278-4a51-942e-b2dace029ab6.png)

tail -30 config.v2.json 
{"StreamConfig":{},"State":{"Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"RemovalInProgress":false,"Dead":false,"Pid":14466,"ExitCode":0,"Error":"","StartedAt":"2022-05-12T20:44:13.365047464Z","FinishedAt":"0001-01-01T00:00:00Z","Health":null},"ID":"5b00d7ac540014d8f5fe333bdd9cff7f24515fcdc0a0b525ba39f57521e4c5a4","Created":"2022-05-12T20:44:12.163670522Z","Managed":false,"Path":"docker-entrypoint.sh","Args":["npm","start"],"Config":{"Hostname":"5b00d7ac5400","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"80/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["AUDIOBOOKSHELF_UID=99","AUDIOBOOKSHELF_GID=100","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","NODE_VERSION=16.15.0","YARN_VERSION=1.22.18","NODE_ENV=production"],"Cmd":["npm","start"],"Image":"ghcr.io/advplyr/audiobookshelf","Volumes":null,"WorkingDir":"","Entrypoint":["docker-entrypoint.sh"],"OnBuild":null,"Labels":{}},"Image":"sha256:a53fd73f9a2cba8e5f07db999147ff5437c3ea3ac96a61e5a8187778e2de4d37","NetworkSettings":{"Bridge":"","SandboxID":"a40e57475fac8d87742449dac001fab4bacb73af536fff2813d6013add687fbc","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"7c2e93959e3ec7ee770639b19b0dafaa765a89d10155b50b4bb48c71fd683348","EndpointID":"b94a3cca7c07bc969ae42d63f0618fd87a0614c9b642f1b6cd5659b5f28ffb79","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02","DriverOpts":null,"IPAMOperational":false}},"Service":null,"Ports":{"80/tcp":[{"HostIp":"0.0.0.0","HostPort":"13378"},{"HostIp":"::","HostPort":"13378"}]},"SandboxKey":"/var/run/docker/netns/a40e57475fac","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"IsAnonymousEndpoint":false,"HasSwarmEndpoint":false},"LogPath":"","Name":"/audiobookshelf","Driver":"overlay2","OS":"linux","MountLabel":"system_u:object_r:container_file_t:s0:c2,c902","ProcessLabel":"system_u:system_r:container_t:s0:c2,c902","RestartCount":0,"HasBeenStartedBefore":true,"HasBeenManuallyStopped":false,"MountPoints":{"/audiobooks":{"Source":"/data/audiobookshelf/audiobooks","Destination":"/audiobooks","RW":true,"Name":"","Driver":"","Type":"bind","Propagation":"rprivate","Spec":{"Type":"bind","Source":"/data/audiobookshelf/audiobooks","Target":"/audiobooks"},"SkipMountpointCreation":false},"/config":{"Source":"/data/audiobookshelf/config","Destination":"/config","RW":true,"Name":"","Driver":"","Type":"bind","Propagation":"rprivate","Spec":{"Type":"bind","Source":"/data/audiobookshelf/config","Target":"/config"},"SkipMountpointCreation":false},"/metadata":{"Source":"/data/audiobookshelf/metadata","Destination":"/metadata","RW":true,"Name":"","Driver":"","Type":"bind","Propagation":"rprivate","Spec":{"Type":"bind","Source":"/data/audiobookshelf/metadata","Target":"/metadata"},"SkipMountpointCreation":false}},"SecretReferences":null,"ConfigReferences":null,"AppArmorProfile":"","HostnamePath":"/var/lib/docker/containers/5b00d7ac540014d8f5fe333bdd9cff7f24515fcdc0a0b525ba39f57521e4c5a4/hostname","HostsPath":"/var/lib/docker/containers/5b00d7ac540014d8f5fe333bdd9cff7f24515fcdc0a0b525ba39f57521e4c5a4/hosts","ShmPath":"","ResolvConfPath":"/var/lib/docker/containers/5b00d7ac540014d8f5fe333bdd9cff7f24515fcdc0a0b525ba39f57521e4c5a4/resolv.conf","SeccompProfile":"","NoNewPrivileges":false,"LocalLogCacheMeta":{"HaveNotifyEnabled":true}}

tail -30 hostconfig.json 
{"Binds":["/data/audiobookshelf/metadata:/metadata","/data/audiobookshelf/audiobooks:/audiobooks","/data/audiobookshelf/config:/config"],"ContainerIDFile":"","LogConfig":{"Type":"journald","Config":{}},"NetworkMode":"default","PortBindings":{"80/tcp":[{"HostIp":"","HostPort":"13378"}]},"RestartPolicy":{"Name":"no","MaximumRetryCount":0},"AutoRemove":true,"VolumeDriver":"","VolumesFrom":null,"CapAdd":null,"CapDrop":null,"CgroupnsMode":"private","Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"private","Cgroup":"","Links":null,"OomScoreAdj":0,"PidMode":"","Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"SecurityOpt":null,"UTSMode":"","UsernsMode":"","ShmSize":67108864,"Runtime":"runc","ConsoleSize":[0,0],"Isolation":"","CpuShares":0,"Memory":0,"NanoCpus":0,"CgroupParent":"","BlkioWeight":0,"BlkioWeightDevice":[],"BlkioDeviceReadBps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteIOps":null,"CpuPeriod":0,"CpuQuota":0,"CpuRealtimePeriod":0,"CpuRealtimeRuntime":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DeviceCgroupRules":null,"DeviceRequests":null,"KernelMemory":0,"KernelMemoryTCP":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":null,"OomKillDisable":null,"PidsLimit":null,"Ulimits":null,"CpuCount":0,"CpuPercent":0,"IOMaximumIOps":0,"IOMaximumBandwidth":0,"MaskedPaths":["/proc/asound","/proc/acpi","/proc/kcore","/proc/keys","/proc/latency_stats","/proc/timer_list","/proc/timer_stats","/proc/sched_debug","/proc/scsi","/sys/firmware"],"ReadonlyPaths":["/proc/bus","/proc/fs","/proc/irq","/proc/sys","/proc/sysrq-trigger"]}

### Steps to reproduce the issue

1.  Click Libraries under root.  Click scan.. Click force re-scan.
3. It will start scanning fine.  In around 20 seconds or so it will crash.  The docker container will be brought down.

### Audiobookshelf version

v2.0.13

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
We need the logs leading up to the crash

**Comment by 77boaz** [comment]
I blew away all of the logs just to make sure it's fresh... Started the server.. then immediately went to do a re-scan.  This is what I found in the daily log.  Let me know if you need anything else?  Thanks!

{"timestamp":"2022-05-12T23:09:50.949Z","message":"=== Starting Server ===","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:50.950Z","message":"[Server] Init v2.0.13","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.020Z","message":"[DB] 0 Collections Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.021Z","message":"[DB] 0 Series Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.191Z","message":"Set Log Level to DEBUG","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:09:51.193Z","message":"[DB] 1 Users Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.196Z","message":"[DB] 1 Libraries Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.205Z","message":"[DB] 9 Library Items Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.246Z","message":"[DB] 10 Authors Loaded","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.247Z","message":"[Db] Root user exists, pw: false","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.253Z","message":"[BackupManager] 0 Backups Found","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.255Z","message":"[BackupManager] Auto Backups are disabled","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.260Z","message":"[LogManager] Init current daily log filename: 2022-05-12.txt","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.270Z","message":"[Watcher] Initializing watcher for \"Main\".","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:51.271Z","message":"[Watcher] Init watcher for library folder path \"/audiobooks\"","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:09:51.305Z","message":"Listening on http://0.0.0.0:80","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:52.853Z","message":"[Watcher] \"Main\" Ready","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:56.143Z","message":"[Server] Socket Connected v6HKC68oxNtYdudDAAAB","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:09:56.193Z","message":"[Server] User Online root","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:09:56.220Z","message":"[DB] Updated user: 1","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:09:56.271Z","message":"[Server] Cancel scan main","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:17.235Z","message":"[Server] User Offline root","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:17.237Z","message":"[Server] Socket v6HKC68oxNtYdudDAAAB disconnected from client \"root\" after 21094ms","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:10:18.142Z","message":"[Server] Socket Connected KqDnxU7wOXhJ4zHCAAAD","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:10:18.188Z","message":"[Server] User Online root","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:18.203Z","message":"[DB] Updated user: 1","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:19.652Z","message":"[Scanner] Starting library scan lscan_npnlbxneymg32i0ged for Main","levelName":"INFO","level":2}
{"timestamp":"2022-05-12T23:10:30.850Z","message":"[LibraryItem] Success saving abmetadata to \"/metadata/items/li_x2915wojxgk40awge2/metadata.abs\"","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:30.852Z","message":"[LibraryItem] Success saving abmetadata to \"/metadata/items/li_o2785wmxma67c34pbd/metadata.abs\"","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:30.937Z","message":"[DB] Library Items updated 2","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:34.158Z","message":"[LibraryItem] Success saving abmetadata to \"/metadata/items/li_3t407kv1pro9e9urn5/metadata.abs\"","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:34.160Z","message":"[LibraryItem] Success saving abmetadata to \"/metadata/items/li_saknir8v9ka0kv10vk/metadata.abs\"","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:34.162Z","message":"[LibraryItem] Success saving abmetadata to \"/metadata/items/li_csgs7l0apsvi07nv2j/metadata.abs\"","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:34.163Z","message":"[LibraryItem] Success saving abmetadata to \"/metadata/items/li_hp7ez1y1oz3a3n033k/metadata.abs\"","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:34.165Z","message":"[LibraryItem] Success saving abmetadata to \"/metadata/items/li_c52yk9008779kg6yvc/metadata.abs\"","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:34.166Z","message":"[LibraryItem] Success saving abmetadata to \"/metadata/items/li_5i9g6p4ihehbymq5ri/metadata.abs\"","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:34.237Z","message":"[DB] Library Items updated 6","levelName":"DEBUG","level":1}
{"timestamp":"2022-05-12T23:10:37.871Z","message":"[LibraryItem] Success saving abmetadata to \"/metadata/items/li_e8r8ukdojxy0hy7uw4/metadata.abs\"","levelName":"DEBUG","level":1}

**Comment by advplyr** [comment]
Unfortunately none of these show what the error was. I'm not sure what to suggest except for maybe starting with a fresh database and maybe there was some corrupt database file.

**Comment by 77boaz** [comment]
Yah ugh.. I will try that..Maybe it is in fact remedied but I just need to start anew.. I'll give that a shot Thanks!

**Comment by 77boaz** [comment]
Unfortunately it did the same thing.. the log doesn't look too different.  Just in case it matter I'm running on fedora.  Also, I wouldn't think it would matter but I have some super large audiobooks.  Maybe I will try to remove a few and re-scan just to see/troubleshoot Thanks!

**Comment by advplyr** [comment]
Yeah I think you need to isolate whichever one is causing the crash.

**Comment by 77boaz** [comment]
I'm in the process of removing chunks of types of audiobooks but so far to no avail.  Would running docker as root mess things up potentially.  I'm pretty new at using docker.  Also a question.  Is there any chance in the future of creating an appimage?  Thanks!

**Comment by 77boaz** [comment]
Ok I'm not sure else what to do.. I removed every book down to nothing with re-scans in between and it crashes around 20-30 seconds no matter what.. :(  I'm still poking around but am kinda at a loss unless it's just the docker version or my OS..

**Comment by advplyr** [comment]
The scanner crashes with no books?

**Comment by 77boaz** [comment]
Actually I didn't go down to complete nothing.  :) I can try nothing I suppose :)

**Comment by 77boaz** [comment]
It completes when down to nothing.  I also noticed it will automatically populate without my intervention if I copied a couple books over which is cool! Interesting...

**Comment by advplyr** [comment]
Is your media sitting on the same server as the docker container?
It seems like you may be using a remote file system.

**Comment by 77boaz** [comment]
Yes it is, although it is on a samba share if that could be an issue...  I can try moving it out of that.. It's basically a samba share with music to share off to windows mac whatever..

**Comment by advplyr** [comment]
Remote file systems cause a lot of issues

**Comment by 77boaz** [comment]
So I disabled smb (samba) and still the same.. the only other difference is they are on different drives.. partitions..

**Comment by 77boaz** [comment]
Ok.. There were packages missing and or I guess older versions of docker in fedora.. so I went with podman.  Now everything is updating.. I do get intermittent socket disconnected while it's updating but that could be due to this slow server - I hope to upgrade soon! It looks like it's all good!  Sorry if this was any waste of time and thanks again! Sweet server/app :-)
