### ISSUE TITLE
[Enhancement]: OPML import

### ISSUE THREAD

**Issue by revilo951** [advplyr/audiobookshelf#588]
### Describe the feature/enhancement

It'd be great to be able to export an OPML file from say podgrab or pocket casts, and have ABS add all the podcasts to my library - a checkbox or something to download all previous episodes would also be great.

**Comment by advplyr** [comment]
OPML importer was added in [v2.0.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.18)

Currently no way to trigger downloading all previous episodes, that will need to be thought out more.

**Comment by Utopiah** [comment]
In case others wonder, it can be done via https://www.audiobookshelf.org/guides/podcasts/#adding-through-the-ui
