### ISSUE TITLE
[Bug]: Internet Archive RSS Feeds

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf#589]
### Describe the feature/enhancement

The Internet Archive offers RSS feeds for things like Podcast collections. Podgrab recognizes these, and is able to download episodes, but ABS does not recognize that it is a valid RSS URL.

Example Collection:  https://archive.org/details/podcast_roundtable-live_964743670
RSS link: https://archive.org/services/collection-rss.php?collection=podcast_roundtable-live_964743670

**Comment by jflattery** [comment]
This already works. Albeit, you need to edit the podcast after adding it to re-add the feed url.

**Comment by HStep20** [comment]
Good to know - I had fiddled with it a bit last night, and couldn't get it working no matter what I tried. I renamed it to a bug, but not sure how to re-tag it as a bug instead of enhancement.

**Comment by advplyr** [comment]
In testing adding this manually as a podcast I noticed that the title had a semicolon which it was trying to use in the folder path causing an error. We will need to strip invalid characters from titles.

Then I also had the issue with the feed url not saving properly and I had to go back in and save it again.

Is there anything else we should be doing for internet archive feeds?

**Comment by HStep20** [comment]
I don't think so. I think I had the feed url issues, as opposed to the character in the folder path issue. jflattery was able to get it downloading episodes, so I think once those two things are fixed, it should basically support them like a normal rss feed.

**Comment by advplyr** [comment]
Fixed in [v2.0.14](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.14)
