### ISSUE TITLE
[Bug]: Create Bookmark button keeps disappearing after 5-10 minutes. 

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf#592]
### Describe the issue

[Bug]: Create Bookmark button keeps disappearing after 5-10 minutes.  App restart is required to make it work again.

### Steps to reproduce the issue

1. Play Audiobook for longer than 10 minutes.
2. No Create Bookmark button

### Audiobookshelf version

2.0.12

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Is this an issue with the mobile app?

**Comment by advplyr** [comment]
Just tested and unable to reproduce this. I don't see how the amount of time something is played would have any impact on whether the bookmarks button is shown.

The bookmarks button is not shown for downloaded media items that are not connected to a server item. It is also not shown if you are not connected to a server.

I think this needs some more testing put into it and opened in the mobile app repo. https://github.com/advplyr/audiobookshelf-app

**Comment by superpawko** [comment]
Yes sorry my bad, I should use audiobookshelf-app repo. I will test it for downloaded books and not downloaded. And let you know.
