### ISSUE TITLE
[Enhancement]: Add a "Merge and Add" option (Picture included)

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#594]
### Describe the feature/enhancement

As mentioned previously, I use the "merge"/"Make M4B Audiobook File" feature ALL THE TIME! But the biggest bummer is when I do the merge action and then forget to get the output file before it's cleaned up by the program after 60 minutes. For me, I always wind up just taking this file and putting it right back into Audiobookshelf and testing it there to make sure it works as expected. 

And then it hit me: Maybe we could have that be an option when we generate the file in the first place?!

It could look something like this:
![image](https://user-images.githubusercontent.com/25695143/168494002-71b1066a-d489-4e95-86ad-66c223900b08.png)

Suggested behavior of new feature:
The merged output (M4B) file could be generated just like normal, but it wouldn't stay in just the temp directory anymore. The completed file could be added (copied?) to the same directory the source file(s) came from when it's finished being generated. (And If possible, it would be awesome if it could be set as the primary file in the "Track list" too so it was the file that was played first).

This would greatly improve the speeds that I can do my conversions and save a lot of toil.

What do you think?

**Comment by Kudjo-Grand** [comment]
I just thought of a bonus! If this feature was present, it would also allow other admins that don't have access to the filesystem to help in converting my Library to m4b when they come across the need.

This would also help me out a lot.

What do you think?

**Comment by Kudjo-Grand** [comment]
Friendly bump.

Your thoughts?

**Comment by advplyr** [comment]
If you generate an m4b from multiple mp3s then that m4b gets moved into the same folder as the other mp3s then the scanner will add this to track list which is not desirable.
We wouldn't want to remove the mp3s either incase something was wrong with the m4b conversion.

**Comment by advplyr** [comment]
This won't be added due to the reason above

**Comment by samosbor** [comment]
I am using this auto-m4b tool to merge my mp3s. The solution they have for the above issue is that they move the old mp3 files to a "backup" folder after the conversion so they are not lost but not in the same folder anymore. Doubles the file size, but easy enough to manage and clean up in batches when you don't need the mp3s anymore.

https://github.com/seanap/auto-m4b

**Comment by advplyr** [comment]
@samosbor That's a great idea. I'll have to think it out more but that seems like the move.

**Comment by proteus077** [comment]
Very much on board with the "Merge & Replace" idea, with the source mp3 files being moved into a backup folder so they are effectively removed from audiobookshelf's library. Then can manually check that the merge went okay and delete the source files later. While not as easy from a user perspective as having a Merge & Replace button that does delete the source files, I'm sure there's a good reason for not implementing this in case the merge fails or something along those lines.

**Comment by advplyr** [comment]
Added in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)

Keep in mind your original audio files will be stored in cached indefinitely until your purge the cache. We can eventually have periodic cache purging setup but in the meantime make sure to check that so it doesn't get too big.
