### ISSUE TITLE
[Enhancement]: Prologue App

### ISSUE THREAD

**Issue by matusaurio** [advplyr/audiobookshelf#596]
### Describe the feature/enhancement

Hi,

I know there's an app for the project but, are you open to third party apps' integration? 

There's an open discussion on Reddit, and there's a [comment](https://www.reddit.com/r/PrologueApp/comments/u8w6vj/audiobookshelf_integration/i5v35s6/) from the developer of [Prologue](https://prologue.audio/).

**Comment by genebean** [comment]
One perk to this as a user is Prologue has CarPlay support

**Comment by genebean** [comment]
At https://discord.com/channels/942908292873723984/954760207131615264/981588553836408883 the author said 

“I would prefer to have some devs helping with the FOSS software we are building, but the second best thing devs could be doing to help abs is building 3rd party integrations. Monetized or not monetized doesn't matter as long as it doesn't break the license”

So, sounds like making Prologue work with ABS is welcomed.
