### ISSUE TITLE
[Enhancement]: Return to last position in library when going 'back' from item description page

### ISSUE THREAD

**Issue by c-hri-s** [advplyr/audiobookshelf#604]
### Describe the feature/enhancement

I'm I'm browsing the library (http://<server>/library/<library>/bookshelf) and click to view the details of an Audiobook (http://<server>/item/<item>), when I click the browser 'back' button, I'd like to be returned to the previous place in the library.

If I have a large collection and wish to browse titles for an interesting book to listen to, then continually being returned to the top of the library is very frustrating.

If there are technical limitations preventing this, then open the item detail in a new browser tab which would at least leave the main library where it was.

**Comment by advplyr** [comment]
Added in [v2.0.15](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.15)

**Comment by c-hri-s** [comment]
Awesome, thanks!
