### ISSUE TITLE
[Enhancement]: 'Continue Series' should use 'first unplayed book' instead of 'next book after last played book'

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf#608]
### Describe the feature/enhancement

The 'Continue Series' section on the landing page seems to show the 'next unplayed book after the last played book'. Usually, this is a minor thing, since things are listened to sequentially, but I think it should show 'the first unplayed book' instead of being tied to the last played book.

My main concern is when it comes to book with novellas that fall between other books. I recently added in recently released novellas to this series, and you can see that 2 of them fall between book 2 and 3. This causes ABS to show 'book 3.1' as next up, even though there are other unplayed books in the series. 

![image](https://user-images.githubusercontent.com/6693120/169320863-4e43033a-a010-466f-88af-e5fe3b049f43.png)

This can also cause issue with non-linear series like Discworld, where you can listen to them in most any order, so it won't be listened to linearly.

**Comment by HStep20** [comment]
Looks like theres still a few little bugs with it. It does show the next unplayed book (yay), but it also shows the last book in a series if all of them are played, as well as the book in progress in a current series. The second book is the last book of a completed trilogy, but marking any series as complete has the same effect - the last book shows up in the list regardless of play status

![image](https://user-images.githubusercontent.com/6693120/169441841-b1e2aa20-bd8c-4cf3-8905-697ba6a6935c.png)

**Comment by advplyr** [comment]
Fixed (again) in [v2.0.16](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.16)
