### ISSUE TITLE
[Enhancement]:  Let view only books in a grid view or a list view.

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf#609]
### Describe the feature/enhancement

Now when you find an author and you see his books it is impossible to easily see all books. And choose one. You have to move to the right. You can't sort it. 

I think pressing "books" should send you to new better view, where all library options are avaible and filter is set for the author name.
![image](https://user-images.githubusercontent.com/11931157/169377495-ad6b8b99-a377-4b45-bca5-67cb48e5fbd0.png)

**Comment by advplyr** [comment]
Added in [v2.0.15](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.15)
