### ISSUE TITLE
Enhancement: In progress/Recently Played views

### ISSUE THREAD

**Issue by Jdiesel87** [advplyr/audiobookshelf#61]
A view with all in progress books sorted by most recently played would be great to have. Having the option to make this the default view when opening the webui/app makes sense to me from an intuitive use case as more often than not I am looking to continue a book already in progress rather than searching for a new book to start.

I realized that this can already be done using the filters but I think it really deserves its own tab like library and collections.

**Comment by advplyr** [comment]
Agree, I talked about something similar before but in the context of having a different home page view, like Plex, Jellyfin, etc.

Then each shelf would be something, like the top shelf would be recently played, next might be recently added, etc.

Do you think adding a "home" page bookshelf view is the way to go? With the addition of the side rail this makes more sense. Library is now its own separate page.

**Comment by Jdiesel87** [comment]
Yeah recently added is another view that would be helpful to quickly find what you are looking for. Plex and Emby both use a "home" page to serve you media that you are most interested in. I find with that approach I very seldom need to dig deeper into the library view when the in-progress, recently added, and search option are all available on the home page.

Other option would be a "random" row too

**Comment by advplyr** [comment]
I spent far too long playing around with different designs for the shelf category label on the home page. I posted them in a discussion #63 and would appreciate your thoughts and feedback.

There have been other features I never rolled out because I couldn't get them looking right. I don't have much of an eye for design, but I think the look and feel of the bookshelf is important.

**Comment by svdztn** [comment]
I just found this: 
![image](https://user-images.githubusercontent.com/39606957/135008663-826476a3-4a30-4686-ba8d-1ae261deb884.png)
![image](https://user-images.githubusercontent.com/39606957/135008731-8ec7c6ea-0212-4dae-8799-e3579628cb87.png)
![image](https://user-images.githubusercontent.com/39606957/135008910-6aa107ad-1803-482b-a7a3-cc336a497ec4.png)

It is enough for me.
Good job!

> Look forward to seeing these features in the Android app soon.

**Comment by advplyr** [comment]
Home page released in [v1.2.6](https://github.com/advplyr/audiobookshelf/releases/tag/v1.2.6)
