### ISSUE TITLE
[Bug]: Audio does not continue to next chapter when screen is locked on an iOS device, using Safari

### ISSUE THREAD

**Issue by george-asda** [advplyr/audiobookshelf#613]
### Describe the issue

I understand this may be an iOS limitation, and I may need to wait for the full release of the iOS app however currently on my daughter's device she cannot access testflight due to her age (there's a limitation that you must be 13+).

Many thanks for creating this app, by the way - it's looking great so far.

### Steps to reproduce the issue

1. Start playing an audiobook which is split into multiple audio files (mp3 in my case)
2. lock the screen
3. when the end of the current chapter/mp3 is reached, audio stops playing and the next chapter/mp3 does not play

### Audiobookshelf version

v2.0.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I just tested this on an android device (Pixel 6) using Chrome and an iphone 10 using Safari and both worked.

What device is this happening on?

**Comment by advplyr** [comment]
You may want to check the audio tracks and make sure they are all in the correct order

**Comment by advplyr** [comment]
Unable to reproduce

**Comment by jango-fx** [comment]
I have the same problem. 

iOS 26.2.1
The native app works as expected. (awesome app btw. love it)
I have another instance as PWA saved to the home screen, to be able to have multiple users logged in at the same time. there I'm experiencing the issue regularly.

But I can't reproduce it reliably either (I had the feeling it happened every time, but now that I'm testing it more thoroughly, it works as expected at least 50% of the time, of course...).
It seems to be the same with Firefox or Safari.

When a chapter ends and the screen is locked, the audio stops (not always, though. sometimes there's just a short pause, then it continues). As soon as the browser/window is opened again, it continues. Sometimes a "Socket disconnected" message pops up, followed by "Socket connected".

I guess it's a caching issue? I doesn't seem to occur with single file books. And (maybe?) less so with smaller files per chapter? Or with the same chapter twice... I can't really tell yet.
