### ISSUE TITLE
[Bug]: E-reader doesn't turn on

### ISSUE THREAD

**Issue by zblesk** [advplyr/audiobookshelf#614]
### Describe the issue

Issue: type 'user' can't use e-reader.

I've installed the latest version today. I have enabled the Experimental features and can now read e-books. 
I've also created a user (of the type 'user') for a friend. That account still just sees this warning:

![image](https://user-images.githubusercontent.com/4245227/169524678-a3dd0a9c-bea0-4300-9c9a-1ac0c6afec12.png)

The root still sees the feature as enabled; and the standard user can't access Settings to change anything. It seems as if root sets the site-wide config, which then doesn't take effect for the other user. 

### Steps to reproduce the issue

1. Log in as root
2. Go to Settings
3. Enable Experimental features 
4. Log in as someone else (type: 'user')

### Audiobookshelf version

v2.0.15

### How are you running audiobookshelf?

Docker

**Comment by skyzuma** [comment]
The best way is, to hide the ebook library (and / or any other experimental functions) to other users, that's only root (or the user that can enable experimental) can see / use this. I got many questions from my users: why I can't use this library, plz activate experimental.

How? Maybe a user setting like 'can use experimental' 

OR

Hide experimental completly until it goes out of this state

**Comment by advplyr** [comment]
New server setting is added in [v2.0.16](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.16)
