### ISSUE TITLE
ID3 Tag series does not exist. How can I add series to my audiobooks when not using the folder structure?

### ISSUE THREAD

**Issue by dmuiX** [advplyr/audiobookshelf#616]
### Describe the feature/enhancement

I want to add series to my audiobooks. But there is no id3 tag that is called series: https://exiftool.org/TagNames/ID3.html. My taggers mp3tag and mediamonkey cannot add this tag either. 
The documentation says there should be one: https://www.audiobookshelf.org/docs#book-audio-metadata
So which ID3 tag are you using to add series? Or are you just using the folder structure for this tag?

**Comment by skyzuma** [comment]
u can add custom tags and profiles for tags (to switch) to mp3tag ...

**Comment by dmuiX** [comment]
You're right thank you. Did not think it would be possible to add arbitrary tags in the enhanced tag section. Thats a good way to add that tag easily.
