### ISSUE TITLE
[Enhancement]: Parse new lines in Audible API for descriptions

### ISSUE THREAD

**Issue by valdearg** [advplyr/audiobookshelf#620]
### Describe the feature/enhancement

When matching data using the Quick Match using the Audible option, the description can have basic HTML code for handling new lines and similar formatting.

For example, the following URL [here](https://api.audible.com/1.0/catalog/products?response_groups=rating%2Cseries%2Ccontributors%2Cproduct_desc%2Cmedia%2Cproduct_extended_attrs&image_sizes=500%2C1024%2C2000&num_results=25&products_sort_by=Relevance&title=Book+of+Night&author=Holly+Black).

I presume it uses the "publisher_summary" for the description field which looks like:

`<p><b>Number-one </b><b><i>New York Times</i></b><b> best-selling author Holly Black makes her stunning adult debut with </b><b><i>Book of Night</i></b><b>, a modern dark fantasy of shadowy thieves and secret societies in the vein of </b><b><i>Ninth House</i></b><b> and </b><b><i>The Night Circus</i></b></p> <p>In Charlie Hall’s world, shadows can be altered, for entertainment and cosmetic preferences—but also to increase power and influence. You can alter someone’s feelings—and memories—but manipulating shadows has a cost, with the potential to take hours or days from your life. Your shadow holds all the parts of you that you want to keep hidden—a second self, standing just to your left, walking behind you into lit rooms.</p> <p>And sometimes, it has a life of its own.</p> <p>Charlie is a low-level con artist, working as a bartender while trying to distance herself from the powerful and dangerous underground world of shadow trading. She gets by doing odd jobs for her patrons and the naive new money in her town at the edge of the Berkshires.</p> <p>But when a terrible figure from her past returns, Charlie’s present life is thrown into chaos, and her future seems at best, unclear—and at worst, nonexistent. Determined to survive, Charlie throws herself into a maelstrom of secrets and murder, setting her against a cast of doppelgangers, mercurial billionaires, shadow thieves, and her own sister—all desperate to control the magic of the shadows.</p> <p>With sharp angles and prose, and a sinister bent, Holly Black is a master of shadow and story stitching. Remember while you listen, light isn’t playing tricks in <i>Book of Night</i>, the people are.</p> <p><b>Praise for Holly Black:</b></p> <p>“Black is a master at world-building.” (<i>The New York Times Book Review</i>)</p> <p>“No one writes like Holly Black.” (John Green, number-one <i>New York Times</i> best-selling author)</p>`

It would be really nice to include the formatting, e.g. the paragraph breaks,

**Comment by advplyr** [comment]
We will keep the main thread for this #617 
An html sanitizer and rich text editor was just recently added, so support for this should come soon.
