### ISSUE TITLE
[Enhancement]: Date formatting

### ISSUE THREAD

**Issue by jt196** [advplyr/audiobookshelf#624]
### Describe the feature/enhancement

Would it be possible for the user to be able to set their date formatting? Switch between European/US and maybe ISO8601? Can't see anywhere to do this in the settings section.

**Comment by cassieesposito** [comment]
I'd be willing to take this on if you can point out places that dates appear.

**Comment by jt196** [comment]
So, date is displayed when the user listened info (currently mm/dd/yy):

![image](https://user-images.githubusercontent.com/8290163/174255724-fea74598-1537-424e-9fde-0c70981e7a3c.png)

Also, on the sorting by date added (currently mm/dd/yy):

![image](https://user-images.githubusercontent.com/8290163/174256068-0f18931f-d971-406e-8ce2-99dc7ce97476.png)

In the Users section in the settings (currently mmm dd, yyyy):

![image](https://user-images.githubusercontent.com/8290163/174256194-99e3b2d5-4d1e-4d12-83f8-a28d7f3cf088.png)

**Comment by cassieesposito** [comment]
https://github.com/advplyr/audiobookshelf/pull/736 deals with the first two. I'm going to leave the users section alone for now.
