### ISSUE TITLE
[Enhancement]: allow non-admin users to enable experimental features

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#625]
### Describe the feature/enhancement

I have a few users who wanted to try some of the experimental features, but were unable to toggle them on.

Is it possible to allow other, non-admin users to enable the experimental features?

What do you think?

**Comment by advplyr** [comment]
I think the only experimental feature that could be tried by a regular user is the e-reader.
The next update there is already a new setting added to enable the experimental e-reader for all users.

Admin users now have full access so admin users can go into the config.

**Comment by advplyr** [comment]
Experimental e-reader server setting added in [v2.0.16](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.16)

**Comment by Kudjo-Grand** [comment]
Sorry for the Rez.
My users use the "merge files" feature. Is there any way to allow them to use that too?
