### ISSUE TITLE
[Bug]: Download of audiobook fails if file is in root of library

### ISSUE THREAD

**Issue by notnamed** [advplyr/audiobookshelf#627]
### Describe the issue

I had an audiobook library bind-mounted into my Docker container as /audiobooks containing a flat directory of MP3s (one per book). It was ABS was able to read these files fine enough to import them into the library, match them, even stream them on web and mobile, but downloading on web and mobile (Android) failed. On mobile, the download of the cover art succeeded, but the MP3 failed to download with the error:

Item download complete but failed to create library item

On web, it downloaded an HTML file with the contents "Not found"

Creating subdirectories for each audiobook and placing the MP3 for each book inside its subdirectory resolved the issue.

### Steps to reproduce the issue

1. Create an /audiobooks library containing a flat directory hierarchy of MP3s, one per audiobook
2. Try to download the item on web or mobile

### Audiobookshelf version

Server v2.0.15; Android 0.9.46-beta

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.16](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.16)
