### ISSUE TITLE
change root password?

### ISSUE THREAD

**Issue by timconsidine** [advplyr/audiobookshelf#628]
Running audiobookshelf with docker
Is there a way to reset the root user password ?
A script ?  
Manual edit of config/users/data/ json file ? But how to generate the `pash` value ?

**Comment by advplyr** [comment]
No script yet, but you can just set the pash value to an empty string for the root user. I described it here: https://forums.unraid.net/topic/112698-support-audiobookshelf/page/7/#comment-1126005

I just recommend backing up that data.json file before editing it, it is easy to break that file.

**Comment by jasonmhite** [comment]
Sorry to resurrect an old issue, but somehow the password for my root user seems to have gotten set to something other than what it originally was. I need to reset it, but it doesn't look like there is a users folder in my config directory anymore. Is something wrong with my setup and it should still be there, or is there a different way I can reset my password now?

**Comment by nichwall** [comment]
You will need to edit the SQLite database to reset a root password.

https://www.audiobookshelf.org/faq/server#how-can-i-reset-a-password

**Comment by jasonmhite** [comment]
@nichwall Thanks a bunch, somehow I missed that in the docs page.
