### ISSUE TITLE
[Bug]: After deleting the last podcast episode, podcast status now shows as  "incomplete" with issues

### ISSUE THREAD

**Issue by andonevris** [advplyr/audiobookshelf#636]
### Describe the issue

Using the new delete podcast episode function, after deleting an episode leaving no more episodes the podcast enters an error state "Incomplete" and also shows up on the issues tab.

There is no issue with the podcast it should not be in an error state, it should just wait for the next episode to release.

### Steps to reproduce the issue

1. Delete final episode in a podcast using the new "hard delete" feature.
2. Podcast status is now errored "incomplete"

### Audiobookshelf version

v2.0.17

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
For audiobooks they show an error if there are no audio files/ebooks, but this is not ideal for podcasts so this is updated now in [v2.0.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.18)

**Comment by andonevris** [comment]
Hi, I just tested this and still got the "incomplete" error running 2.0.18

**Comment by advplyr** [comment]
I just tested again and am not able to replicate.

**Comment by skyzuma** [comment]
ive tested also and delete all files [Hard delete file] and no problem with incomplete BUT ABS listed all files in the UI ... i think the DB was not updated after deleting files and if i dl the same file again > new (same) entry ... after 10 times i have 10 same names on the UI (the downloaded files are root:root)

**Comment by advplyr** [comment]
@skyzuma Are you using a network drive?

**Comment by skyzuma** [comment]
oh sry no, its all local ... sry my fault ... should i need to open a new issue ?

**Comment by advplyr** [comment]
When I added this feature I assumed the watcher would clean up the library files but forgot that not everyone uses the watcher.
I will need to update this feature to also remove the episode library file.

**Comment by advplyr** [comment]
Fixed in [v2.0.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.19)
