### ISSUE TITLE
Delete Downloaded Files

### ISSUE THREAD

**Issue by ddubnyk** [advplyr/audiobookshelf#639]
### Describe the feature/enhancement

Any chance to have the option to delete the downloaded files when we delete the episodes? From what i see currently it only deletes it from showing up in the UI.

**Comment by advplyr** [comment]
What version of abs are you using?

**Comment by ddubnyk** [comment]
> What version of abs are you using?

Ah i just noticed the Hard Delete file option in the web interface. I did not see this in previous release. I just updated to the latest version now. Will this also be added into the android and iOS app?

**Comment by advplyr** [comment]
You can already delete local files from the android app but the ui/ux has a ways to go.

**Comment by ddubnyk** [comment]
Okay good to know.  Thanks!
