### ISSUE TITLE
about chapter name

### ISSUE THREAD

**Issue by svdztn** [advplyr/audiobookshelf#64]
Sometimes the name of audiobookfile is chapter name, not just `001.mp3` ...   
So if the chapters is empty, use filename as chapter name is helpful. And we can know which file is being played while playing.

> My temporary method：
> ![image](https://user-images.githubusercontent.com/39606957/135008248-c2b19daf-d127-44c8-8f50-dee712b15f88.png)

**Comment by advplyr** [comment]
Makes sense to me. This is released in [v1.2.6](https://github.com/advplyr/audiobookshelf/releases/tag/v1.2.6)
