### ISSUE TITLE
UNC Path adds drive letter.  [Bug]: 

### ISSUE THREAD

**Issue by MrKuenning** [advplyr/audiobookshelf#640]
### Describe the issue

A library located at `\\NAS\Media\Audio\Library` is being rewritten as `"E:\\NAS\\Media\\Audio\\Library"`

`path: "E:\\Media\\Media\\Audio\\Library - Audiobooks\\Hank The Cowdog\\Hank The Cowdog - 3 - It's a Dog's Life.m4b"`

Resulting in scan errors:

```
Failed to getFileTimestampsWithIno [Error: ENOENT: no such file or directory, stat 'E:\NAS\Media\Audio\Library - Audiobooks\Hank The Cowdog\Hank The Cowdog - 3 - It's a Dog's Life.m4b']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: "E:\\NAS\\Media\\Audio\\Library - Audiobooks\\Hank The Cowdog\\Hank The Cowdog - 3 - It's a Dog's Life.m4b"
}
```

### Steps to reproduce the issue

1. Add a new library from a UNC path.
2. Scan library

### Audiobookshelf version

Windows Build : v2.0.17

### How are you running audiobookshelf?

Other

**Comment by advplyr** [comment]
Abs is resolving relative paths and I think I'd like to keep it that way for now. Wouldn't a UNC path be entered with double backslashes like `\\NAS\Media\etc`?

I think it could check for a double slash before it resolves it. I'm not sure I don't use any UNC paths so let me know.

**Comment by MrKuenning** [comment]
Strange I typed it with two backslashes, but the get hub post formatting was removing the first one.
I added code markers so it will show up now.

It's basically taking a network SMB share and appending the drive letter that the exe file is located into the path.

**Comment by advplyr** [comment]
Does that mean it is working now for you?

**Comment by MrKuenning** [comment]
No, I was just saying that I do have double back shashes.  Git just made it look like I don't.

I downloaded the latest release v2.0.20 and it still fails to scan the library.
The strange thing is it lists all the files one by one and then says it can find that file because it cant be found.

**Comment by advplyr** [comment]
What do you mean it lists all the files one by one?

It is adding the drive letter and still able to find that path?
