### ISSUE TITLE
[Bug]: MATCH : AUDIBLE : (UNABRIDGED)

### ISSUE THREAD

**Issue by sxb1n9** [advplyr/audiobookshelf#641]
### Describe the issue

Audible will not match on title name if "(unabridged)" is at the end of the name.   I need to manually remove it and re-match for match to work on each audiobook.   Could you please automagically remove (unabridged) from the end of the title name search? 

### Steps to reproduce the issue

1. see above explains issue

### Audiobookshelf version

2.0.17

### How are you running audiobookshelf?

Docker

**Comment by sxb1n9** [comment]
i should note this is because my books have id3 and metadata for title already and they don't get stripped or cleaned titles in your search class.

**Comment by sxb1n9** [comment]
Thank you fixed in 2.0.18

**Comment by sxb1n9** [comment]
accidentally closed the wrong one

**Comment by advplyr** [comment]
Next release will solve for this https://github.com/advplyr/audiobookshelf/pull/735
