### ISSUE TITLE
[Enhancement]: Badge for no match

### ISSUE THREAD

**Issue by sxb1n9** [advplyr/audiobookshelf#643]
### Describe the feature/enhancement

It is difficult to see which titles have no search match when you have information in the metadata of the audiobook already.   Please add a badge or indication that there is no match / needs match.

**Comment by advplyr** [comment]
That is what the "Missing" filter is for. 

It is up to you what you pull in from a match, so there cannot be a matched/unmatched flag. Unless you have some other idea let me know.

**Comment by sxb1n9** [comment]
> That is what the "Missing" filter is for.
> 
> It is up to you what you pull in from a match, so there cannot be a matched/unmatched flag. Unless you have some other idea let me know.

There is no selection for missing match in the missing filter so if you already have information int he metadata of the file you can't find the ones missing match still.
