### ISSUE TITLE
[Bug]: Multi-track audiobooks in the 'Listen again' section won't start from the beginning

### ISSUE THREAD

**Issue by Eftimin70** [advplyr/audiobookshelf#644]
### Describe the issue

When playing an audiobook from the 'Listen again' section of the 'Home' page, it usually doesn't start at the first track but at any other track (it "feels" random)

### Steps to reproduce the issue

1. Using any audiobook with more than one track

### Audiobookshelf version

v2.0.18

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I just tested and am not able to replicate this, they always start at the first track for me.

**Comment by Eftimin70** [comment]
Ah OK, thanks. very interesting. Now I also found some audiobooks where it doesn't happen, but they are very rare. I'll have a further look into this, maybe I'll find a certain pattern.

**Comment by advplyr** [comment]
We can re-open this if you are able to reproduce
