### ISSUE TITLE
[Bug]: unable to download podcasts after awhile

### ISSUE THREAD

**Issue by muppie** [advplyr/audiobookshelf#645]
### Describe the issue

After downloading a few podcasts, new one will fail. I can’t understand why nor do I understand the error messages. Several different podcasts are affected. No change after reboot either. 
[_audiobookshelf_logs.txt](https://github.com/advplyr/audiobookshelf/files/8795140/_audiobookshelf_logs.txt)

### Steps to reproduce the issue

1.  Not sure.

### Audiobookshelf version

2.18

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Did you check if the path `/podcasts/The Paul Minors Podcast -  Productivity, Business & Self-Improvement` exists?

**Comment by advplyr** [comment]
The folder is created when you first add the podcast. If you say you have downloaded other episodes already then where are they located if not in the podcast folder?

**Comment by muppie** [comment]
Hi again,

Sorry, I meant other shows, not other episodes. I cannot download any episodes from the Paul Minors show, Bunga Bunga, Dr Death or similar.
