### ISSUE TITLE
[Enhancement]: option to set database import date to file modification time

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf#646]
### Describe the feature/enhancement

I have audiobooks that I have collected over the years. When I import them into ABS some books that are years old show up on the top of the list of recent books. Add an option to set database import date equal to file timestamp

**Comment by advplyr** [comment]
You can sort by file birthtime and other file specific timestamps. As of now the added at timestamp will remain the time that it was added to abs.
