### ISSUE TITLE
[Bug]: Cover doesn't update from match dialog

### ISSUE THREAD

**Issue by cassieesposito** [advplyr/audiobookshelf#648]
### Describe the issue

When updating a book using the match tab of the book's edit dialog, the cover does not update as it should.

Expected behavior: cover changes to match the one from metadata source.
Actual behavior: cover is unchanged.

### Steps to reproduce the issue

1. Open Library
2. Click pencil in top right corner of a book
3. Open "Match" tab
4. Match the book (have tested Audible and Google Books)
5. Leave checkbox for "Cover" checked
6. Click "Update"

### Audiobookshelf version

2.0.18

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Confirmed, it appears something broke here recently as this was working an update or 2 ago.

**Comment by cassieesposito** [comment]
Correct. It definitely worked in 2.0.16

**Comment by advplyr** [comment]
I found the issue, will be fixed in the next release

**Comment by whaddayakno** [comment]
I'm having this issue too, good to hear it will be fixed

**Comment by advplyr** [comment]
Fixed in [v2.0.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.19)
