### ISSUE TITLE
Bug: Generate M4B creates a 30kb file instead of complete file.

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#65]
![image](https://user-images.githubusercontent.com/25695143/135042517-597cb530-7c62-4259-b0db-935585e8f343.png)

When I clicked on the "Start Download" button, it finishes almost immediately and the button then says "Download". But when I click it the download it gives me (while it IS the expected filename and .m4b format) is only a few kb instead of the complete file I was expecting.

In case it's helpful, I'm including the logs generated in the metadata folder where the generated file is stored:

`file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 01.m4b
duration 1124.636

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 02.m4b
duration 1448.902

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 03.m4b
duration 1247.098

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 04.m4b
duration 864.015

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 05.m4b
duration 822.939

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 06.m4b
duration 669.664

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 07.m4b
duration 891.531

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 08.m4b
duration 1243.058

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 09.m4b
duration 858.582

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 10.m4b
duration 2289.929

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 11.m4b
duration 774.386

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 12.m4b
duration 795.191

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 13.m4b
duration 1838.092

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 14.m4b
duration 1186.122

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 15.m4b
duration 1429.63

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 16.m4b
duration 1154.357

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 17.m4b
duration 1004.728

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 18.m4b
duration 1692.131

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 19.m4b
duration 922.994

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 20.m4b
duration 1136.176

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 21.m4b
duration 1426.681

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 22.m4b
duration 1377.826

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 23.m4b
duration 972.081

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 24.m4b
duration 1034.24

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 25.m4b
duration 1075.293

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 26.m4b
duration 1903.967

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 27.m4b
duration 1284.644

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 28.m4b
duration 1098.606

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 29.m4b
duration 1507.068

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 30.m4b
duration 853.821

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 31.m4b
duration 996.183

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 32.m4b
duration 1898.139

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 33.m4b
duration 1576.984

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 34.m4b
duration 605.507

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 35.m4b
duration 559.834

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 36.m4b
duration 961.423

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 37.m4b
duration 501.76

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 38.m4b
duration 722.814

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 39.m4b
duration 484.81

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 40.m4b
duration 970.014

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 41.m4b
duration 1355.14

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 42.m4b
duration 478.564

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 43.m4b
duration 253.168

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 44.m4b
duration 318.439

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 45.m4b
duration 632.605

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 46.m4b
duration 824.309

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 47.m4b
duration 429.755

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 48.m4b
duration 824.657

file /audiobooks/Brandon\ Sanderson/Skyward\ Series/Book\ 02\ -\ Starsight/Starsight\ -\ 49.m4b
duration 1584.922`

`;FFMETADATA1
title=Starsight
artist=Brandon Sanderson
date=
comment=AudioBookshelf v1.2.5
genre=Audiobook
[CHAPTER]
TIMEBASE=1/1000
START=0
END=1124636
title=Chapter 1
[CHAPTER]
TIMEBASE=1/1000
START=1124636
END=2573538
title=Chapter 2
[CHAPTER]
TIMEBASE=1/1000
START=2573538
END=3820636
title=Chapter 3
[CHAPTER]
TIMEBASE=1/1000
START=3820636
END=4684651
title=Chapter 4
[CHAPTER]
TIMEBASE=1/1000
START=4684651
END=5507590
title=Chapter 5
[CHAPTER]
TIMEBASE=1/1000
START=5507590
END=6177254
title=Chapter 6
[CHAPTER]
TIMEBASE=1/1000
START=6177254
END=7068785
title=Chapter 7
[CHAPTER]
TIMEBASE=1/1000
START=7068785
END=8311843
title=Chapter 8
[CHAPTER]
TIMEBASE=1/1000
START=8311843
END=9170425
title=Chapter 9
[CHAPTER]
TIMEBASE=1/1000
START=9170425
END=11460354
title=Chapter 10
[CHAPTER]
TIMEBASE=1/1000
START=11460354
END=12234740
title=Chapter 11
[CHAPTER]
TIMEBASE=1/1000
START=12234740
END=13029931
title=Chapter 12
[CHAPTER]
TIMEBASE=1/1000
START=13029931
END=14868023
title=Chapter 13
[CHAPTER]
TIMEBASE=1/1000
START=14868023
END=16054145
title=Chapter 14
[CHAPTER]
TIMEBASE=1/1000
START=16054145
END=17483775
title=Chapter 15
[CHAPTER]
TIMEBASE=1/1000
START=17483775
END=18638132
title=Chapter 16
[CHAPTER]
TIMEBASE=1/1000
START=18638132
END=19642860
title=Chapter 17
[CHAPTER]
TIMEBASE=1/1000
START=19642860
END=21334991
title=Chapter 18
[CHAPTER]
TIMEBASE=1/1000
START=21334991
END=22257985
title=Chapter 19
[CHAPTER]
TIMEBASE=1/1000
START=22257985
END=23394161
title=Chapter 20
[CHAPTER]
TIMEBASE=1/1000
START=23394161
END=24820842
title=Chapter 21
[CHAPTER]
TIMEBASE=1/1000
START=24820842
END=26198668
title=Chapter 22
[CHAPTER]
TIMEBASE=1/1000
START=26198668
END=27170749
title=Chapter 23
[CHAPTER]
TIMEBASE=1/1000
START=27170749
END=28204989
title=Chapter 24
[CHAPTER]
TIMEBASE=1/1000
START=28204989
END=29280282
title=Chapter 25
[CHAPTER]
TIMEBASE=1/1000
START=29280282
END=31184249
title=Chapter 26
[CHAPTER]
TIMEBASE=1/1000
START=31184249
END=32468893
title=Chapter 27
[CHAPTER]
TIMEBASE=1/1000
START=32468893
END=33567499
title=Chapter 28
[CHAPTER]
TIMEBASE=1/1000
START=33567499
END=35074567
title=Chapter 29
[CHAPTER]
TIMEBASE=1/1000
START=35074567
END=35928388
title=Chapter 30
[CHAPTER]
TIMEBASE=1/1000
START=35928388
END=36924571
title=Chapter 31
[CHAPTER]
TIMEBASE=1/1000
START=36924571
END=38822710
title=Chapter 32
[CHAPTER]
TIMEBASE=1/1000
START=38822710
END=40399694
title=Chapter 33
[CHAPTER]
TIMEBASE=1/1000
START=40399694
END=41005201
title=Chapter 34
[CHAPTER]
TIMEBASE=1/1000
START=41005201
END=41565035
title=Chapter 35
[CHAPTER]
TIMEBASE=1/1000
START=41565035
END=42526458
title=Chapter 36
[CHAPTER]
TIMEBASE=1/1000
START=42526458
END=43028218
title=Chapter 37
[CHAPTER]
TIMEBASE=1/1000
START=43028218
END=43751032
title=Chapter 38
[CHAPTER]
TIMEBASE=1/1000
START=43751032
END=44235842
title=Chapter 39
[CHAPTER]
TIMEBASE=1/1000
START=44235842
END=45205856
title=Chapter 40
[CHAPTER]
TIMEBASE=1/1000
START=45205856
END=46560996
title=Chapter 41
[CHAPTER]
TIMEBASE=1/1000
START=46560996
END=47039560
title=Chapter 42
[CHAPTER]
TIMEBASE=1/1000
START=47039560
END=47292728
title=Chapter 43
[CHAPTER]
TIMEBASE=1/1000
START=47292728
END=47611167
title=Chapter 44
[CHAPTER]
TIMEBASE=1/1000
START=47611167
END=48243772
title=Chapter 45
[CHAPTER]
TIMEBASE=1/1000
START=48243772
END=49068081
title=Chapter 46
[CHAPTER]
TIMEBASE=1/1000
START=49068081
END=49497836
title=Chapter 47
[CHAPTER]
TIMEBASE=1/1000
START=49497836
END=50322493
title=Chapter 48
[CHAPTER]
TIMEBASE=1/1000
START=50322493
END=51907415
title=Chapter 49`

**Comment by Kudjo-Grand** [comment]
I did a little test. I wondered if it just had something to do with how your code handles JUST the .m4b extension while trying to stitch everything together to make a new .m4b file with chapters and everything. 

So, I cheated. I didn't convert anything. I just changed the file extension from .m4b to .mp3 reloaded the book into ABS. I then re-ran the generate .m4b process by pushing the "Start Download" button again. And BINGO! This time, it worked as expected. A  400+ MB file was generated with chapters in the correct order and cover embedded. So, well done!

It's a little hacky, but it looks like I know what to do in the future to make this work.

Hopefully, this was helpful.

What do you think?

**Comment by advplyr** [comment]
I came across this issue as well with m4b files, but didn't dig into it too much. Thanks for experimenting and finding that out, that will give me a starting place in fixing that issue.

**Comment by Kudjo-Grand** [comment]
I just tried this trick again (change file extension to .mp3) with a different book that had .FLAC as the source files and it worked there too! However, I noticed something that makes me wonder.

At first, I thought the generate m4b process didn't "touch" the source files at all; just repackaged them into the m4b format. But when the source FLAC files total up to 6.1GB and the generated file is only 504MB, then I know that I thought wrong.

Would you mind telling me how the conversion is taking place? What settings are being used? Out of curiosity:  Is there a way to change the settings?  Or turn off compression?

Thank you.

**Comment by advplyr** [comment]
The source file does not get manipulated at all. It is using Ffmpeg and the source is an input, Ffmpeg doesn't modify input files.
You can see the exact command that is being run to generate the m4b if you open the log, then start the m4b download, and look for a log that starts with this: `[DownloadWorker] FFMPEG concat started with command: `

That command is doing all the work. There are 2 text files that are generated that you will see in the command, `files.txt` and `metadata.txt`. These files are stored in `/metadata/downloads/{download id}/..` and automatically deleted when the download expires, times out, or fails.

**Comment by advplyr** [comment]
Are you still seeing this issue?

**Comment by Kudjo-Grand** [comment]
I'll check.

**Comment by advplyr** [comment]
We'll re-open if this is reproducible
