### ISSUE TITLE
[Enhancement]: Support for WAV format

### ISSUE THREAD

**Issue by rosystain** [advplyr/audiobookshelf#652]
### Describe the feature/enhancement

I have some files in WAV format, some of them can be scanned, but Audiobookshelf can't stream them unless I  rename WAV as MP3 simply without transcoding.The only action I can do with them is the botton of download.
There are also some files can‘t be scanned, the log tell me there is no audio track in my folders. I cannot figure out the difference with these two situations.
Perhaps WAV is not supported yet.

Since WAV cannot be embedded with ID3 tags, it would be very nice if OPF works great with files in WAV format.

**Comment by Jdiesel87** [comment]
I know space is cheap, relatively speaking, these days but how many people are storing audiobooks in WAV format? Almost every book I have encountered has been in highly compressed in a lossy format. A 16bit WAV file averages about 10Mb per minute. Even with 8bit WAVs you are looking at a very large file.

**Comment by advplyr** [comment]
The scanner was not setup to pull in wav files as audio tracks, so what you were seeing was the wav file pulled in as a regular library file which wouldn't be playable. Support will be in the next release.

An 8 hour audiobook as a wav file would be almost 5GB, and 8 hours is a short audiobook.

**Comment by advplyr** [comment]
Added in [v2.0.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.19)
