### ISSUE TITLE
[Enhancement]: Chapter editing improvements

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf#657]
### Time Format
In the chapter edit screen, chapter starts are listed in seconds.milliseconds format
![image](https://user-images.githubusercontent.com/991618/171492407-8c114d3f-e843-4ab0-ab23-c05b5f52f843.png)

But when you use the `Lookup` button they are listed in H:MM:SS format. 
![image](https://user-images.githubusercontent.com/991618/171492520-a0069c51-0f71-4729-a2e1-472099b01256.png)

This makes it difficult to compare chapter start times. Please use the same format in both locations. And possibly set up an option to change between the two formats listed (I might prefer seeing milliseconds and others might not), or a combined format of H:MM:SS.milliseconds

### Chapter Start Time Difference
In the lookup, show a time difference to the nearest chapter. Using the example screenshots above, the lookup window would show something like `12:45 (+0.739s)`. Don't show a difference if the audiobook file on the server has no chapter marks, or if the difference is less than a user configurable threshold.

### Color Code Key
Explain the color coding of a chapter:
![image](https://user-images.githubusercontent.com/991618/171493829-5398e462-f228-46b3-b86d-612a491b3588.png)
I think this means my audio file ends during this chapter. There is a message on the lookup screen that `Chapter data invalid duration
Your media duration is shorter than duration found`

If there are other color options no currently present in my example, those should have a descriptive key as well.

**Comment by advplyr** [comment]
Updated in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)
