### ISSUE TITLE
[Bug]: Long delay when pressing play on chapter marks in edit chapter screen with M4B media

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf#658]
### Describe the issue

Delay can be over a minute on a rockpi4.

### Steps to reproduce the issue

1. Select an M4B
2. edit chapters
3. click play on a later chapter in the book

### Audiobookshelf version

2.0.18

### How are you running audiobookshelf?

Docker

**Comment by Alumniminium** [comment]
`Content-Length: 235104494
Content-Range: bytes 65536-235170029/235170030`

It appears that m4b's are getting downloaded in its entirety whenever you click play. 
That's whats causing the delay, its not streaming, its downloading.

**Comment by alexmaras** [comment]
It may be worth pulling the latest image (`advplyr/audiobookshelf:edge`) and testing again. There was an issue with a Service Worker that has now been disabled. I was hitting this same issue and no longer have a problem - m4b filers play almost instantly no matter where in the file is requested.

**Comment by advplyr** [comment]
This is in the latest release now. Please test again

**Comment by SenorSmartyPants** [comment]
Plays right away.

**Comment by Alumniminium** [comment]
it does not play right away for me. also there's very high cpu usage until it starts playing. I'm on the latest version using docker
