### ISSUE TITLE
[Bug]: Author page url does not work

### ISSUE THREAD

**Issue by bskrtich** [advplyr/audiobookshelf#659]
### Describe the issue

When you click on an author from the `/library/main/authors` section it will show the author page inside ABS, the app will also change the URL to something like `/author/aut_j39vva2vwrawpu2sjs`. This URL doesnt actually work. When you refresh the page or try to go back to that URL directly.  When you do it shows an error `Cannot GET /author/aut_j39vva2vwrawpu2sjs`

### Steps to reproduce the issue

1. Log in to web interface
2. Go to authors on the left
3. Click on an author
4. Refresh the page

### Audiobookshelf version

v2.0.18

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.19)
