### ISSUE TITLE
BUG: Settings page will not allow scrolling. Must use browser zoom.

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#66]
So, the settings page will not allow scrolling. I must use the browser zoom feature to see the bottom of the page (where the version number is, for example). Here are some pictures to demonstrate (I've blanked out my list of users).

Here is 1080p resolution with browser set to 100%:
![image](https://user-images.githubusercontent.com/25695143/135134053-329d259d-b5b0-48bf-b42e-2af0eec2fa31.png)
(I can't see below "the fold")

At 50% browser zoom, I can finally see the bottom.
![image](https://user-images.githubusercontent.com/25695143/135134147-4197e566-1580-41c9-8941-284398924973.png)

**Comment by advplyr** [comment]
Fixed this in [v1.2.6](https://github.com/advplyr/audiobookshelf/releases/tag/v1.2.6), appreciate ya
