### ISSUE TITLE
[Enhancement]: Ability to trigger manual docker build

### ISSUE THREAD

**Issue by bskrtich** [advplyr/audiobookshelf#661]
### Describe the feature/enhancement

It would be nice if we can manually trigger a docker build using a specific tag and the latest source code

**Comment by Jdiesel87** [comment]
You should already be able to do this 

https://hub.docker.com/r/advplyr/audiobookshelf/tags

**Comment by bskrtich** [comment]
This is a request from @advplyr 
https://github.com/advplyr/audiobookshelf/pull/418#issuecomment-1144193822
