### ISSUE TITLE
[Enhancement]: Add healthcheck endpoint

### ISSUE THREAD

**Issue by bskrtich** [advplyr/audiobookshelf#662]
### Describe the feature/enhancement

We need some sort of health check endpoint to make sure the webapp/server is up and responding correctly. This then could be added to the docker setup or other setups to auto restart if the server dies.

**Comment by advplyr** [comment]
There is a ping endpoint now that returns a JSON object.
`https://yourserver.com/ping`

I think the JSON object is unnecessary to return but if all you need to check is the status code then it will return a 200 if it succeeds.
