### ISSUE TITLE
[Enhancement]: Pull Title and Author from metadata if available

### ISSUE THREAD

**Issue by kymahi** [advplyr/audiobookshelf#666]
### Describe the feature/enhancement

i have users uploading multiple files at once, and it would make the process much quicker if, if it's available, the title and author fields are autofilled via the file metadata, so it's more automated and less of a manual process.

**Comment by advplyr** [comment]
There is no good way to scan audio file metadata inside the browser that I know of. If you know of a way to do this we can re-open this.
