### ISSUE TITLE
[Bug]: Artist Captain Future (mp3tag) is showing as artist Future. Captain is missing

### ISSUE THREAD

**Issue by szemlicka** [advplyr/audiobookshelf#668]
### Describe the issue

I have a lot of audiobooks with the artist "Captain Future". But the Artist field shows only Future.
![grafik](https://user-images.githubusercontent.com/15927779/171854467-8a34b16a-9e0e-4709-9973-d3ef9d2a8dd0.png)
![grafik](https://user-images.githubusercontent.com/15927779/171854574-bd4e3f1f-7875-455f-9aee-655c81b12815.png)

### Steps to reproduce the issue

1. Tag the artist as Captain Future" and scan for new files.

### Audiobookshelf version

latest 

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you share your server settings?

**Comment by szemlicka** [comment]
![grafik](https://user-images.githubusercontent.com/15927779/171858668-9a267704-2cd3-4748-a15a-66a9407ee944.png)

**Comment by advplyr** [comment]
Have you been able to reproduce this issue with anything else? I can't reproduce this it seems like a one-off thing.
