### ISSUE TITLE
[Enhancement]: Sort by Series

### ISSUE THREAD

**Issue by kymahi** [advplyr/audiobookshelf#669]
### Describe the feature/enhancement

I would love a way to sort by series in the standard library view. I know you can collapse books into their respective series, but that sorts by the first book's title instead of the series name (e.g. 'A Series of Unfortunate Events' is up in the "B" area because the first book is 'The Bad Beginning', instead of in the "S" area), which makes it more difficult to find.

Thanks!

**Comment by advplyr** [comment]
There is a request for this already #629 
There is some problems I have with this but we discussed in Discord and we will try it out. Follow that thread for updates.

**Comment by kymahi** [comment]
Whoops! Sorry missed that one! Thanks!
