### ISSUE TITLE
[Enhancement]: More manual control of Series

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#671]
### Describe the feature/enhancement

I would like to have more control over the Series. The ability to add/remove/hide/unhide books from a series, and to be able to hide/unhide the entire series.

![image](https://user-images.githubusercontent.com/42061703/171971451-aa2fcea9-9c24-4091-89f7-55844f277c28.png)

From the image above, one can see that I have only 1 book in that series (if they are actual book series - I don't think 10% Happier is a part of any series, but that's not the point) and it kinda looks stupid/incomplete to have a series with one book in it. I would like to hide the entire series in this example.

![image](https://user-images.githubusercontent.com/42061703/171971470-3a629b25-c35d-4854-a40b-258512f1f9ff.png)

From the image above, one can see that one series is split into two automatically - the regular one and the abridged one (even though there's nothing in the ID3 to suggest that the book is abridged - I checked twice). I would like to move the books from the abridged series to the regular series (in two steps - add them to regular, remove them from abridged and remove the abridged series itself).

**Comment by hobesman** [comment]
I'm not sure if this resolves your issue, but you can edit series info by clicking the pencil icon that appears when you hover over the cover art. From there you can add books to a second series, remove it from the first series, or remove it from a series altogether so that it's not part of that series, or any series at all.

If there are no books left in a series, the series won't show up.

Does that accomplish most of what you intended? Beyond the idea of showing which books are missing, is there something more you want to happen?

**Comment by raviwarrier** [comment]
Dude, you are everywhere! :D
I guess, there's much I need to learn about ABS - all the nooks and crannies of where actions lie. :)
Yes, your suggestions did help me remove/add albums into series. Cheers.

But my suggestions would be to make things more intuitive and easy to understand.

For example, when I clicked on remove (after clicking on pencil) it said, are you sure you want to remove (and this will not delete the file, just remove from ABS). It wasn't clear what 'this' was - the book or the series? Made me think thrice before clicking on it... And the whole act of editing the series is a bit lengthy along with being un-intuitive.

Are you on the dev team or is this all from experience?

**Comment by raviwarrier** [comment]
Here's what I mean by confusing:

Step 1 - Go to Series page and choose a series you want to edit.
![image](https://user-images.githubusercontent.com/42061703/171988023-4f9ba616-cc68-4b6c-b6f9-985bbb40a651.png)

Step 2 - Click on the name of the series that appears to go into it.
![image](https://user-images.githubusercontent.com/42061703/171988044-5733f6c1-1850-4cc0-992e-ad7196d7c5fd.png)

Step 3 - Well, there is no button to remove the series (or rename it or anything else)...
![image](https://user-images.githubusercontent.com/42061703/171988071-a24702b0-8dd8-48bf-99d5-dee935c51d26.png)

Step 4-minus - Hover over a book and click on the pencil icon (this needs to be done individually for each book in the series as the multi-select-edit doesn't have any remove option - see image below)
![image](https://user-images.githubusercontent.com/42061703/171988138-14c26d24-adbb-4cba-9ea7-10703256a505.png)

Step 4-plus - there is a delete button that appears when you select multiple files, but it's not clear if it deletes the albums from the series or the whole series. My guess is it removes the books, but that's not very clear if all books in the series is selected.
![image](https://user-images.githubusercontent.com/42061703/171988200-b8faff3e-2571-4325-a944-cc3381f2fb69.png)

Step 5 - Make a risky guess on whether this means remove from series (what I intend) or remove from library (not what I intend and very bad if it happens). I guess this questions comes only the first time someone attempts this, but it's bad design. Changing the question to "Are you sure you want to remove these 3 times from the series?" just makes it a bit clear and less scary.
![image](https://user-images.githubusercontent.com/42061703/171988276-41b75fe3-8fb0-40b3-b99c-ce7ac88e1e69.png)

Step 6 - Press 'yes' (after the first-time scare).

All this is to remove a 'series'. Just like there is a select radio button for the book inside the series, it would be nice to have a select radio button for the series to directly edit/delete it from the series page itself.

PS: I could really be doing this wrong (since I am still learning to use ABS). So, if I am, please correct me and guide to a quicker way of doing this. Cheers.

**Comment by raviwarrier** [comment]
And, so to add the books back to the library, I started the scan. It did add the 3 books to the library, but it also recreated the series with the 3 books after the scan.

![image](https://user-images.githubusercontent.com/42061703/171988607-4f288510-f3c3-4c5d-8b5d-745d11e8c732.png)

**Comment by hobesman** [comment]
Not a dev, just enjoy seeing the project progress.

After you click the pencil icon to see all the metadata, hover over the series name and another pencil appears, and an x. Click pencil to renumber it in that series, and x to remove it from that series. And + to add it to another series.

"Remove" means remove the book's record from your library, not just the series.

**Comment by advplyr** [comment]
I think to most people the remove action is clear as to what is happening. If you have a specific suggestion on what text to add and where to make it more clear then definitely share that.
I recommend clicking around and playing with abs for a while and I think it will make more sense why we made the decisions we made so far. Definitely a ways to go though.

As far as hiding series from the series page I don't see a use-case for this really. Just remove the series if you don't want it to show in the series page.

**Comment by raviwarrier** [comment]
Just add the specifics:
If removing from the library: Are you sure you want to remove X books from your library?
If removing from series or collection: Are you sure you want to remove X books from <series name> series/<collection name> collection?

**Comment by raviwarrier** [comment]
> Not a dev, just enjoy seeing the project progress.
> 
> After you click the pencil icon to see all the metadata, hover over the series name and another pencil appears, and an x. Click pencil to renumber it in that series, and x to remove it from that series. And + to add it to another series. Then click save.
> 
> ![171988138-14c26d24-adbb-4cba-9ea7-10703256a505~2](https://user-images.githubusercontent.com/29721765/171989024-d008593a-5056-42ae-80d7-ca60e151a80e.png)
> 
> "Remove" means remove the book's record from your library, not just the series.

Eventually, that's what I did. But it's painful/effortful to do that individually for each book. I had created a series (Very Short Introductions) with 60 books and I had to individually select the series name for each of them.

**Comment by advplyr** [comment]
Using the "Map details" menu you can apply the update to all books at once, no need to update each one individually. That's what the batch editor is for.

**Comment by raviwarrier** [comment]
I am super impressed. Will try it out. If you guys ever come out with a manual, I am sure it's gonna be a book by itself. That was a compliment on how many good features you have (sometimes people don't understand when I give a compliment, hence clarifying).
