### ISSUE TITLE
[Enhancement]: Show/indicate missing books in a series

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#672]
### Describe the feature/enhancement

Since the app magically, already showing that the book is a part of the series, it would be nice to know which other books are in it that are missing from the library. For example:

![image](https://user-images.githubusercontent.com/42061703/171971624-fda90c02-4944-40cb-ac9e-78cc9dc512f7.png)

I am sure that HBR Insights has many more books and since the app already clubbed this book as a part of the series, show additional book covers (with some kind of marking/indication for missing) in the same series. That way, one would know what is missing from their collection/library.

**Comment by raviwarrier** [comment]
This may seem like a counter to the previous request of "being able to hide/unhide series", but it's actually not. If the person chooses to make their 1-book series visible, then the thumbnail aesthetics of the series card can be improved by showing all the books in the series (with an indication of what's missing - like perhaps grayed cover, or a missing icon).
On the other hand, if I didn't care about other books in the HBR Insights and just wanted this book, I could hide the series and forget about the incomplete collection.

**Comment by advplyr** [comment]
Merging this issue with #963
