### ISSUE TITLE
[Enhancement]: Choose the default home page 

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#673]
### Describe the feature/enhancement

The web-app always loads on Home. But since it doesn't show all the books (and personally doesn't add value to my viewing/listening experience), one would need to go to the library section to pick a book that they want to see/listen to. Allow the users to choose what they would like to start in - Home or Library.

**Comment by advplyr** [comment]
I think you are a specific edge case here as most people would prefer the home page or at least. The home page will be more configurable in the future so maybe you can make a better home page experience then.

**Comment by drichline** [comment]
Strong disagree: with few items in a library, there are **over a dozen** instances of the same icon on the default view. Very frustrating and bad for accessibility
