### ISSUE TITLE
[Enhancement]: [Minor] Accuracy of Author v Narrator Information

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#674]
### Describe the feature/enhancement

This is a very minor change, but important as to how ABS may represent the book's info.

![image](https://user-images.githubusercontent.com/42061703/171978419-dda07080-be6f-4c11-a9ac-ff13bfff7e49.png)

In the example above, the book is by Stephen Macknik et al and narrated by Lloyd James. While in the item page, there is a label that says "Narrated by: Lloyd James", the line above and in the search show only "by Lloyd James", which can be misleading to users who may searching for a book "Sleights of Mind" by Stephen Macknik.

So, adding "narrated" to both those labels would be a better representation of the data.

Additional Info: The way I tag (using Seanap's scripts for MP3Tag) is use the authors for "Album Artist" and narrators for "Artists and Composers" and hence not everyone may face the same problem.

**Comment by advplyr** [comment]
Abs uses the composer meta tag for narrators. This doesn't have anything to do with the search because the search supports "narrated by" if you have your book details set correctly.

**Comment by raviwarrier** [comment]
Yeah, I figured when I just tagged and uploaded a new book. We can go two ways from here:
1. I can re-tag all my books to match artist and album artist and you can close this request. 
2. You can take a new feature request: let the user select while setting up whether they want to use Album Artist or Composer for narrator tag and you can close this request. :)

The first is a lot of work for me. The second is a lot of work for you. I'll let you choose. :)

**Comment by advplyr** [comment]
Hah I don't think using Album Artist makes sense. I think there is a "Performer" meta tag or similar I've considered using for narrator.
You don't need to re-tag your audiobooks, you can edit it in abs press save. Then turn on experimental features go to the "Manage" tab and embed the book details from abs into your audio files. Check it out!

**Comment by raviwarrier** [comment]
Will try it out. But I think selecting all the books in MP3Tag and tagging "Album Artist" = "Artist" would be faster (at least in terms of clicking around).
I apologize for all the stuff here and on discord. As I mentioned to hobesman, there's a lot to learn and until then, some stupid suggestion or bug may be posted.

**Comment by advplyr** [comment]
No apology needed, we're glad to have you here.
