### ISSUE TITLE
[Bug]: Match Books overwrites data

### ISSUE THREAD

**Issue by kymahi** [advplyr/audiobookshelf#675]
### Describe the issue

Despite the assurance on Library Settings page, Match Books overwrites data, specifically, in this case, Authors. I overwrote the authors on some books due to issue #667 (I inserted the individual authors and deleted the multiple authors combined into one author tag). After clicking Match Books, it overwrites the author fixes I made and reinserted the multiple authors as a single author tag.

### Steps to reproduce the issue

1. Match a book with multiple authors
2. Observe multiple authors as a single author tag as described in issue #667 
3. Add each author in the combined tag as their own author tag
4. Remove the combined author tag
5. Go to Settings > Libraries
6. Match Books on the library with the book you just modified
7. Observe the single author tags are removed and the combined multi-author tag has returned

### Audiobookshelf version

v2.0.18

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Do you have the server setting enabled to store metadata in your library item folders?

**Comment by kymahi** [comment]
No it is off

**Comment by advplyr** [comment]
I looked into this and it seems to only be possible to overwrite the authors if it is already set if you have this setting enabled.
![image](https://user-images.githubusercontent.com/67830747/179118595-b0e1b3fb-d9b2-46f8-b2c8-dfbfdbb5c110.png)

Do you have the setting "Prefer matched metdata" toggled on?
