### ISSUE TITLE
[Bug]: "Embed metadata" does not properly embed chapter metadata

### ISSUE THREAD

**Issue by jmt-gh** [advplyr/audiobookshelf#676]
### Describe the issue

I uploaded an m4b file to Audiobookshelf. I updated some of the metadata, including the chapters (both the timings and the names). Afterwards, I used the Embed Data tool to push this data back in to my m4b. 

Upon both manually ffprobe-ing the file, and removing it and rescanning it in to audiobookshelf, the non-chapter updated metadata was shown properly, but the chapter metadata was still the original.

### Steps to reproduce the issue

1. Upload an m4b file to audiobookshelf
2. Modify the chapter timings and chapter names
3. Use the embed metadata tool
4. Validate:
4a. ffprobe the resulting file, and notice that the chapter metadata is not updated
4b. remove the audiobook from audiobookshelf (edit -> remove), and then rescan the library. When the audiobooks is reimported, note that the chapter data is not updated properly

### Audiobookshelf version

v2.0.18

### How are you running audiobookshelf?

Docker

**Comment by jmt-gh** [comment]
Ah. I think I figured this out. Taking the ffmpeg command that is being run from the logs, and testing locally, I had to add `-map_chapters 1` to it for it to work. 

I'm actually interested in fixing this myself. Could I have this assigned to me?

**Comment by advplyr** [comment]
Live in [v2.0.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.19)

**Comment by listy-bit** [comment]
This issue still persists (v2.1.4 Docker) for Opus files. Confirmed it works for .m4b files.
