### ISSUE TITLE
[Enhancement]: Use ID3 Title tag for chapter name when prefer audio metadata

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf#679]
### Describe the issue

When metadata is preferred chapter names should be imported from ID3 title field. Currently filename is used as chapter title, even if metadata is preferred and title field is present.

### Steps to reproduce the issue

My files are named in this format, with track number and then track title.
01 - Intro
02 - Chapter 1
etc

### Audiobookshelf version

2.0.18

### How are you running audiobookshelf?

Docker

**Comment by SenorSmartyPants** [comment]
Any updates to this now that ABS is using tone?

**Comment by QantumEntangled** [comment]
Came here for the same issue.

Version 2.2.14 in Docker

Spent hours editing ID3 tags to make them pretty, but the filenames are long and gross.

**Comment by advplyr** [comment]
I'm confused on this implementation. Currently the album or the title id3 tag is used as book title.
If this were set then all the chapters would have the same name. I'm not sure what you were intending here.

**Comment by SenorSmartyPants** [comment]
Book title in ABS is fine. Just a problem with track/chapter titles.

Here's part of ffprobe of some files affected.
```
Input #0, mp3, from '01 - Opening Credits.mp3':
  Metadata:
    title           : Opening Credits
    artist          : Blake Crouch
    track           : 1/17
    album           : Dark Matter
```

```
Input #0, mp3, from '02 - Chapter 1.mp3':
  Metadata:
    title           : Chapter 1
    artist          : Blake Crouch
    track           : 2/17
    album           : Dark Matter
```

Gets imported into ABS like this.
![image](https://user-images.githubusercontent.com/991618/224849472-479ac012-f2eb-4fbb-8a66-b44aa8ccf664.png)

It has been a while since I imported these, so if I should reimport/rescan just let me know how you would like me to do that and I'll try it out.

**Comment by advplyr** [comment]
Ok I put this in for next release. The only criteria is that the title tag should not be the same as the book title. The reason for this is because in the docs we also support using the title tag as your book title.

**Comment by SenorSmartyPants** [comment]
Sounds great. Thank you! Would doing a book rescan be the way to update these fields for me then?

**Comment by advplyr** [comment]
Unfortunately not. The chapters won't get rebuilt unless an audio track changes. You could press Manage Tracks and change the order of a track, press save, then change the order back.

**Comment by Demian98** [comment]
This would be a great feature and very useful for me. @advplyr if the ID3 title can be used as chapter, the embed metadata feature should also write the chapter as ID3 title. Because currently all information can be stored into the mp3 with the embed metadata feature, expect of the chapters. It would be great if this would be change too :)

**Comment by hobesman** [comment]
> This would be a great feature and very useful for me. @advplyr if the ID3 title can be used as chapter, the embed metadata feature should also write the chapter as ID3 title. Because currently all information can be stored into the mp3 with the embed metadata feature, expect of the chapters. It would be great if this would be change too :)

I agree it would be cool to embed chapter as track title, but the problem is, this assumes each file is one chapter. But often mp3 files are divided into ~1 hour segments, not chapters.

Also, some mp3 files are the entire book in one file, so no way to embed each chapter title.

**Comment by advplyr** [comment]
Updated in [v2.2.17](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.17)

**Comment by SenorSmartyPants** [comment]
> Unfortunately not. The chapters won't get rebuilt unless an audio track changes. You could press Manage Tracks and change the order of a track, press save, then change the order back.

I can confirm this works. You don't even need to alter the track order. Just Manage Tracks -> Save. And chapter titles will update.
