### ISSUE TITLE
[Enhancement]: Add Playlist creation for users

### ISSUE THREAD

**Issue by Cobolt78** [advplyr/audiobookshelf#684]
### Describe the feature/enhancement

Would it be possible to add playlist creation. I would like to create a playlist of books I would like to listen to in the future, with playlists I could create playlists on books I come across that interest me the most and could also create playlists for different genre's as well, if that makes sense. I know I could use tags or collections but they show up for all users.

**Comment by advplyr** [comment]
Is this a duplicate of #422 ?

**Comment by Cobolt78** [comment]
> Is this a duplicate of #422 ?

:( yes sorry for wasting your time.
