### ISSUE TITLE
[Bug]: since update to 2.0.19 (docker) play stops after every Track

### ISSUE THREAD

**Issue by swoop124** [advplyr/audiobookshelf#685]
### Describe the issue

Since i updated autiobookshelf over docker to version 2.0.19 playback stops after every track.
I have to start it again.

### Steps to reproduce the issue

1. Start playback
2. wait for the next chapter/track
3. restart playback

### Audiobookshelf version

2.0.19

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.20](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.20)
