### ISSUE TITLE
[Bug]: Downloaded m4b audiobooks are removed after scanning local folder

### ISSUE THREAD

**Issue by whaddayakno** [advplyr/audiobookshelf#687]
### Describe the issue

What happened: Downloaded m4b audiobook, then scanned the local folder. All m4b audiobooks are now gone from local books.

Expected outcome: Local books should show all audiobooks in the folder, including m4b's.

Using a galaxy note 9, android 10 with v0.9.48 app.

### Steps to reproduce the issue

1. Download an m4b audiobook
2. Scan local folder
3. Audiobook is removed from local books

### Audiobookshelf version

v2.0.19

### How are you running audiobookshelf?

Docker

**Comment by kymahi** [comment]
You should log this with the app repository, since this seems like a client-side issue and not an issue with the server.
https://github.com/advplyr/audiobookshelf-app/issues

**Comment by whaddayakno** [comment]
oh whoops. will repost there, thanks @kymahi
