### ISSUE TITLE
[Bug]: The search finds nothing

### ISSUE THREAD

**Issue by stefanop1** [advplyr/audiobookshelf#688]
### Describe the issue

If you search in web or Android, the search does respond 'no result' although I certainly have titles / series / authors. Even with only the first two or three letters.
I think that this is the error:

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at /server/objects/metadata/BookMetadata.js:341:45
    at Array.filter (<anonymous>)
    at BookMetadata.searchSeries (/server/objects/metadata/BookMetadata.js:341:24)
    at Book.searchQuery (/server/objects/mediaTypes/Book.js:307:29)
    at LibraryItem.searchQuery (/server/objects/LibraryItem.js:455:23)
    at /server/controllers/LibraryController.js:372:28
    at Array.forEach (<anonymous>)
    at ApiRouter.search (/server/controllers/LibraryController.js:371:18)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:144:13)

### Steps to reproduce the issue

1. Make a search pressing the icon

### Audiobookshelf version

2.0.20

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Somehow one of your books has an invalid series saved on it. Maybe you can try to find that bad series?

**Comment by stefanop1** [comment]
Thank you for your help. I try to find the culprit. Perhaps in a future version it might be useful to use a trap

**Comment by stefanop1** [comment]
Found!
<img width="157" alt="Schermata 2022-06-05 alle 19 22 27" src="https://user-images.githubusercontent.com/8995697/172062558-f2714be3-93ba-425d-85e2-70199f287557.png">

**Comment by advplyr** [comment]
Any idea how that happened? It shouldn't be possible to happen.

**Comment by stefanop1** [comment]
Could be happen, I think. Just add a bunch of new audiobooks. Maybe there are one that has embedded a wrong serie

**Comment by stefanop1** [comment]
The audiobook has the title in the tags with underscores instead of spaces. Oddly enough, the scanner still found the match

**Comment by advplyr** [comment]
No idea how it could happen. If you find out any more info let me know!
