### ISSUE TITLE
[Bug]: Match from ITunes

### ISSUE THREAD

**Issue by Thovi98** [advplyr/audiobookshelf#689]
### Describe the issue

Since update to 2.0.19 (but maybe before, because it’s been a while since I used this feature), I encounter a problem when updating metadata from ITunes (Audible works great).
Whenever I press on `Update`, nothing appens. But in Firefox’s console, I see this : 
![2022-06-05 19_18_06-Paramètres](https://user-images.githubusercontent.com/51749973/172062445-2675dbf4-94b1-48c0-b149-5e208aefe1e1.jpg)

### Steps to reproduce the issue

1. Match an audiobook via ITunes (Les Misérables - Édition abrégée)
2. Click on `Update`

### Audiobookshelf version

v2.0.19 Debian

### How are you running audiobookshelf?

Other

**Comment by advplyr** [comment]
I see it also. Looks like more issues then just that after the updates from this PR https://github.com/advplyr/audiobookshelf/pull/622

**Comment by advplyr** [comment]
I think this was fixed in 2.0.21 but let me know if not.
