### ISSUE TITLE
BUG: "Series" view is of a single shelf only

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#69]
You'll notice in the picture below, that only one "shelf" is ever displayed in the "series" view.

I have to zoom out in order to see the rest. I'm guessing this is supposed to have multiple shelves like the other views.

![image](https://user-images.githubusercontent.com/25695143/135407680-265c45e1-4e72-4812-b809-dacbc53f4b11.png)

Same view, zoomed out let's me see the other groupings that were out of sight to the right:
![image](https://user-images.githubusercontent.com/25695143/135407788-6fd924c6-0736-4124-87d0-e81dc6a550f7.png)

What do you think?

**Comment by Budlyte** [comment]
This bug is being discussed over in #47 where the feature was introduced.

https://github.com/advplyr/audiobookshelf/issues/47#issuecomment-927375362

**Comment by advplyr** [comment]
I thought I fixed this, but it was an issue with the width being bigger than regular books.
Fixed in [v1.3.1](https://github.com/advplyr/audiobookshelf/releases/tag/v1.3.1)

**Comment by Budlyte** [comment]
Oh, lol I thought you were still looking into it.   It's looking good.
