### ISSUE TITLE
[Bug]: genre / tag / language have wrong language

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#690]
### Describe the issue

genre / tag / (language) is only english but all other are the language that i want ... search by title and search by asin > same results

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.0.20 (but ABS shows 2.0.19)

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I don't understand, can you be more specific?

**Comment by skyzuma** [comment]
genre / tag / (language) are in english but all other are in my language (german), also on the audible webseite are "genre" are german ... or is this a audible api "bug"?

**Comment by advplyr** [comment]
Abs has no control over what the audible api is returning

**Comment by advplyr** [comment]
I believe this can fall under #731
