### ISSUE TITLE
[Bug]: series number 1 vs 01

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#691]
### Describe the issue

i use since 1.x the same number naming like "Vol 01" / "Vol 02" / "Vol 03" but since a few updates ABS cant recognize this naming and i need to manual update the series number

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.0.20 (but ABS shows 2.0.19)

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
There was a request to strip leading zeros if the sequence was a valid number.

https://github.com/advplyr/audiobookshelf/issues/562

Why do you prefer the leading zero?

**Comment by skyzuma** [comment]
i do it for 40 years xD and windows is the bad guy why i use it ... windows sorted like 1 / 10 / 2 / 20 ... so i use 01 and windows understand this (01/ 02 / xx / 10 / xx) an iam working as an system admin / programmer and yes i use also 00 instead of 0 :)

the problem: cause ABS cant recognize this naming the series tag is empty so a series with 100 books > manual update > no fun ... maybe ABS can use 1 AND 01

**Comment by advplyr** [comment]
Oh I see, I confused the issue you are having. That "Vol 01" should still get detected fine. 

@cassieesposito refactored the scanner recently and maybe something broke with that. https://github.com/advplyr/audiobookshelf/pull/631

**Comment by cassieesposito** [comment]
Bug confirmed. Working on it now.

**Comment by cassieesposito** [comment]
Resolved with PR https://github.com/advplyr/audiobookshelf/pull/692

**Comment by advplyr** [comment]
Fixed in 2.0.21
