### ISSUE TITLE
[Bug]: Issues don't clear when jumping back to library

### ISSUE THREAD

**Issue by cassieesposito** [advplyr/audiobookshelf#694]
### Describe the issue

Expected behavior: "Issues" tab disappears
Actual behavior: "Issues" tab remains

### Steps to reproduce the issue

1. Remove a book from your filesystem
2. Wait for scanner to notice
3. Jump to "Issues" tab
4. Clear issue by removing book from library or replacing the book in the filesystem
5. Wait until page reads "No Issues" with a clear filter button
6. Click on Library tab
7. Click on Issues Tab
8. Goto 6

In order to clear it, you need to click on the "Home," "Series," or "Collections" tabs.

### Audiobookshelf version

2.0.20

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Fixed in [v2.1.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.5)
