### ISSUE TITLE
[Enhancement]: Podcast/RSS feed persist on server restarts

### ISSUE THREAD

**Issue by WetenSchaap** [advplyr/audiobookshelf#696]
### Describe the issue

When an RSS feed is generated for an audiobook, it is not persistent over restarts of the container/server as far as I can tell.

### Steps to reproduce the issue

1. Generate podcast link using `Open RSS feed` button.
2. Restart server or container.
3. The RSS feed has dissapeared. The `Open RSS feed` button generates a new RSS feed with a new url.

### Audiobookshelf version

v2.0.17

### How are you running audiobookshelf?

Docker

**Comment by jmt-gh** [comment]
I'm not able to reproduce on the latest version (v2.0.20). Can you try upgrading?

Though in truth, the URL is based on the itemID of the audiobook once it gets scanned in to the library and cataloged. That shouldn't / doesn't change between reboots of the server.

What does your docker config look like? Are you having to recreate your library every time you restart the container?

**Comment by advplyr** [comment]
RSS feeds persist in [v2.0.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.21)
