### ISSUE TITLE
[Bug]: Merge does not create /metadata/downloads

### ISSUE THREAD

**Issue by Fabaderheld** [advplyr/audiobookshelf#698]
### Describe the issue

Tried the merge into m4b feature but it fails with

```[AbMergeManager] Failed to make directory /metadata/downloads/abmerge_qkrbjaje2jmop142vx```

fixed it by manually creating ```/metadata/downloads```

hope this helps

regards

Fabian

### Steps to reproduce the issue

1. Try merge multiple files into one

### Audiobookshelf version

v2.0.20

### How are you running audiobookshelf?

Docker

**Comment by jmt-gh** [comment]
I noticed this as well. I'll take a look at this one
