### ISSUE TITLE
Enhancement: Could we add FLAC & MOBI file extensions support?

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#70]
Could we add FLAC & MOBI file extensions support?

I'm not sure if that's easy to do or not, but the FLAC audio format and the MOBI eBook format are present in my library (although I do plan on continuing to convert everything to M4B and ePub). The support would make it a bit easier.

What do you think?

**Comment by advplyr** [comment]
I added support for these in [v1.3.1](https://github.com/advplyr/audiobookshelf/releases/tag/v1.3.1)

In order to get FLAC to play nice with the HLS streams they will get transcoded to AAC. I doubt this would matter for audiobooks, but still notable.
