### ISSUE TITLE
[Bug]:  matching "Audiobooks"... notification covers player so I can't control the playing audiobook

### ISSUE THREAD

**Issue by zombiehoffa** [advplyr/audiobookshelf#702]
### Describe the issue

![image](https://user-images.githubusercontent.com/627402/172485198-48f1c76f-34d9-4845-b049-389b35e5abde.png)
the  information pop up (and probably others) covers the plays controls of the player. I don't exactly want to click cancel since I do want it to continue matching audiobooks, but it would be better if this didn't cover up the player window.

### Steps to reproduce the issue

1. start matching your library then play an audiobook

### Audiobookshelf version

2.0.20

### How are you running audiobookshelf?

Docker

**Comment by jmt-gh** [comment]
Opened a PR to fix this in #752 752

**Comment by jmt-gh** [comment]
This will be fixed in the next server release. Thanks for the report!

**Comment by advplyr** [comment]
Updated in [2.0.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.23)
