### ISSUE TITLE
[Bug]: Search is not working

### ISSUE THREAD

**Issue by kymahi** [advplyr/audiobookshelf#703]
### Describe the issue

Search is not working for any queries.

Entering in anything it says, "Thinking" and then "No results". Same result after hitting Enter to get the full page search instead of the modal search box.

### Steps to reproduce the issue

1. Have a library of books
2. Search for a title/author/genre/anything
3. Observe "No Results"

### Audiobookshelf version

v2.0.20

### How are you running audiobookshelf?

Docker

**Comment by stefanop1** [comment]
I had the same issue. Advplyr found the solution. It was a series with garbage. You can find the solution here:
https://github.com/advplyr/audiobookshelf/issues/688

**Comment by kymahi** [comment]
Thanks @stefanop1! I'll look around and see if I missed any on my cleanup

**Comment by kymahi** [comment]
> I had the same issue. Advplyr found the solution. It was a series with garbage. You can find the solution here: #688

@stefanop1's reply was correct. I had some bad authors.

@advplyr I saw that you were asking how to get that bad author in the #688 bug, so I found the books that got it

https://www.audible.com/pd/Blood-Territory-Audiobook/B07WK6VRSV?ref=a_library_t_c5_libItem_&pf_rd_p=80765e81-b10a-4f33-b1d3-ffb87793d047&pf_rd_r=RHXK6ZY663WYYM606HR0

https://www.audible.com/pd/Pines-Audiobook/B008RO91LA?ref=a_library_t_c5_libItem_&pf_rd_p=80765e81-b10a-4f33-b1d3-ffb87793d047&pf_rd_r=21BW9KX3ZVTAY81NYQRQ

(The second seems to be removed from Audible, so I grabbed a screenshot of the book from my library)
<img width="804" alt="image" src="https://user-images.githubusercontent.com/5601322/172749249-2596ce13-de4a-494f-97b7-e5fe0c92859a.png">

These two were filled by running Match Book
