### ISSUE TITLE
[Bug]: Output from console is not saving in file based logs. 

### ISSUE THREAD

**Issue by DieselTech** [advplyr/audiobookshelf#706]
### Describe the issue

Checking dockers logging function shows me the console output of ABS, which does not match what is in the logs stored in /metadata/logs/daily/

### Steps to reproduce the issue

1. View logs in docker
2. View logs in /metadata/logs/daily/
3. Realize not everything is in daily logging

You can see the timestamp is highlighted on the right where the error info should be. 

![tempsnip](https://user-images.githubusercontent.com/30128380/172723303-7ac5bec7-1515-4144-a8f5-25fe818e39ca.png)

### Audiobookshelf version

2.0.20

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.8.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.0)

`/metadata/logs/crash_logs.txt` for uncaught exceptions.
