### ISSUE TITLE
Match book not properly filling in authors/series

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#708]
> I had the same issue. Advplyr found the solution. It was a series with garbage. You can find the solution here: #688

@stefanop1's reply was correct. I had some bad authors.

@advplyr I saw that you were asking how to get that bad author in the #688 bug, so I found the books that got it

https://www.audible.com/pd/Blood-Territory-Audiobook/B07WK6VRSV?ref=a_library_t_c5_libItem_&pf_rd_p=80765e81-b10a-4f33-b1d3-ffb87793d047&pf_rd_r=RHXK6ZY663WYYM606HR0

https://www.audible.com/pd/Pines-Audiobook/B008RO91LA?ref=a_library_t_c5_libItem_&pf_rd_p=80765e81-b10a-4f33-b1d3-ffb87793d047&pf_rd_r=21BW9KX3ZVTAY81NYQRQ

(The second seems to be removed from Audible, so I grabbed a screenshot of the book from my library)
<img width="804" alt="image" src="https://user-images.githubusercontent.com/5601322/172749249-2596ce13-de4a-494f-97b7-e5fe0c92859a.png">

These two were filled by running Match Book

_Originally posted by @kymahi in https://github.com/advplyr/audiobookshelf/issues/703#issuecomment-1150593696_

**Comment by advplyr** [comment]
@kymahl I wasn't able to reproduce this since both of those titles don't return results from the Match tab.

Did you have Audible selected as the provider when you ran the match books?

**Comment by kymahi** [comment]
Yes I believe so. I'm not positive, but I think it occurred when do the library-wide match and not the quick match nor the individual Edit > Match tab matching

**Comment by advplyr** [comment]
I believe this to be fixed in [v2.0.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.21)

**Comment by kymahi** [comment]
Awesome! Thanks for all the hard work!
