### ISSUE TITLE
[Enhancement]: FYI m4btool 

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf#710]
### Describe the feature/enhancement

Just in case you weren't aware of this tool. https://github.com/sandreas/m4b-tool It has quite a few interesting functions. Especially related to chapter manipulation.

**Comment by advplyr** [comment]
I am, @sandreas is a friend of abs

**Comment by sandreas** [comment]
> I am, @sandreas is a friend of abs

Indeed he is :-)

@SenorSmartyPants Thx, I really appreciate the mention.
