### ISSUE TITLE
[Enhancement]: Sort and filter series (as in sort and filter which series appear on the "all series" page)

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#712]
### Describe the feature/enhancement

There's already a request for the ability to sort books within a series on the page for a specific series, but I'm talking about the ability to sort and filter which series show up when browsing all of the series. 

For example, it'd be nice to be able to show sci-fi series, or series with more than a certain number of books, or series with books by a certain author, etc. Or similarly, to sort series by author, or by how many books, or by total duration of books in the series, etc.

**Comment by advplyr** [comment]
Added in [v2.2.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.2)
