### ISSUE TITLE
[Bug]: Search bar not always visible on (non-app) mobile version

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#715]
### Describe the issue

Search field is not immediately visible while on mobile (reducing usability).
Worse: rotating the display should make it show up, but often does not make the search field visible, rendering this incredible app highly unusable with large collections.

### Steps to reproduce the issue

1. Open webpage on a mobile device 
2. The search bar is not immediately visible. (I've seen this on all kinds of sizes and on IOS and Android)
![Screenshot_20220611-105750396](https://user-images.githubusercontent.com/25695143/173198142-a4216215-7260-4cf2-8cfa-b1755713cebe.jpg)

3. You usually have to rotate the phone to make the search appear, but sometimes (often) it doesn't show up at all. Making search impossible.
![Screenshot_20220611-105759832](https://user-images.githubusercontent.com/25695143/173198167-1163face-62d0-467e-8a68-f3999f551e5d.jpg)

Suggestion: I few ideas...
1. Make the search field visible immediately on mobile so the user doesn't have to "go looking for it".
2. Maybe you could have a second way to reach the search function. Perhaps with the "Home", "Library" and "Series" buttons.

Your thoughts?

### Audiobookshelf version

2.0.21

### How are you running audiobookshelf?

Docker

**Comment by jmt-gh** [comment]
Thanks for the report! I've opened #739 to look at fixing this
