### ISSUE TITLE
RSS Feed Cover doesn't load

### ISSUE THREAD

**Issue by kjboa** [advplyr/audiobookshelf#717]
### Describe the issue

The Cover of Audiobooks is not shown when connecting via rss

### Steps to reproduce the issue

I checked three different audiobooks using two clients ( Antennapod & Tsacpod) and using local and public domains. The Covers somehow do not show up

### Audiobookshelf version

v2.0.21

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I tested on Anennapod and Google podcast and the covers showed up for me.
Maybe check the error log?

**Comment by advplyr** [comment]
Can you test this using https and google podcasts? podcasts.google.com in the desktop browser then add rss feed button.
