### ISSUE TITLE
When Matching, Separate Narrators

### ISSUE THREAD

**Issue by thebiggeordiegeek** [advplyr/audiobookshelf#719]
Ok at the moment when you match a book with say Audible, if you have multiple authors, ABS recognises the commas separate the authors and adds them individually.

It doesn’t do this for narrators, and just adds multiple narrators as one big single entry, would it be possible for it to crate separate entries for each narrator instead of just one big long one with them all.

**Comment by jmt-gh** [comment]
Hey @thebiggeordiegeek ! Can you share an example where this occurs? It is supposed to do this automatically, and in my testing on some of my local books, it does indeed. If you can point us to an example where it does + the ASIN, that would be great.

**Comment by hobesman** [comment]
I know a number of GraphicAudio for example have numerous narrators and they all get lumped into one entry if you match it with Audible. e.g. ASIN 1648812082
![Screenshot_20220614-185706](https://user-images.githubusercontent.com/29721765/173720345-1ba6ff84-0b9c-4caf-ace8-13c22ab06b3b.png)

**Comment by jmt-gh** [comment]
Thanks! I'm able to reproduce this on my end with that ASIN. At first glance, the API response seems the same, as other, working, multi narrator books I've matched with Audible. I'll report back my findings!

**Comment by jmt-gh** [comment]
A fix for this is here: #730 

Thanks for the report!
