### ISSUE TITLE
Enhancement: Web UI log viewer for root user

### ISSUE THREAD

**Issue by Jdiesel87** [advplyr/audiobookshelf#72]
Include the option to view the log file from within the web UI for the root using. Mainly a convenience thing, especially with Docker setups.

**Comment by Jdiesel87** [comment]
It could even just be a link to download the logfile from the settings page

**Comment by advplyr** [comment]
I put a primitive logger page in [v1.3.1](https://github.com/advplyr/audiobookshelf/releases/tag/v1.3.1), you can find the button on the config page.
You can also set your log level there which will persist in server settings.

**Comment by advplyr** [comment]
Daily log files are now stored in `/config/logs/daily` as of `v1.6.2`.
The last 7 days of logs are kept.
The log page in config now shows all the logs for the day and listens to logs in realtime.

Next up is storing separate scanner logs.
