### ISSUE TITLE
[Enhancement]: A drop-down instead of dialog for "add to collection" action (at least from the book description page)

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#722]
### Describe the feature/enhancement

For people who may use collections extensively, adding a book at a time is in itself cumbersome. To top that, when I click on the icon to add to collection, I get a dialog to select the collection, and then have to hover over a collection name to get the "+" button and then click on it. That's 3 steps a bit many.

If instead, we could just show a drop-down (like Plex's add to playlist feature, image attached), it would make it more user friendly and fast.
![image](https://user-images.githubusercontent.com/42061703/173536184-b0195849-c437-456a-8645-a9cf1ebb3e3a.png)

**Comment by KaiStarkk** [comment]
It's not necessary to add a book at a time, you can multiselect in the library:

![image](https://github.com/advplyr/audiobookshelf/assets/1722064/f3ac4c92-e786-4839-a7b8-c642c8eddc3e)

Does that solve the issue?

**Comment by raviwarrier** [comment]
For some reason, I did not try that... I guess, it was because I was picking books from all over the place on my library (some on top, some bottom, etc.) and it didn't strike me multi-select. Cheers mate.

**Comment by raviwarrier** [comment]
Marking it as closed. :)
