### ISSUE TITLE
[Enhancement]: Auto clear the search text box upon completion of a search

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#723]
### Describe the feature/enhancement

It would be nice if the search bar clears on it's own once the search operation is complete/book is selected.
![image](https://user-images.githubusercontent.com/42061703/173536780-17fe0035-8162-4ee2-959b-5aed216ca30a.png)

In the example above, I found the book, clicked on it, opened the page, but in order to start a new search, first I have to press 'x' to clear the search bar which is one extra step hindering seamless user experience.

**Comment by advplyr** [comment]
This is added in [2.0.22](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.22)

**Comment by raviwarrier** [comment]
Yup. Saw that. Cheers. :)
