### ISSUE TITLE
[Enhancement]: Support different regions for Audible Matching (i.e. audible.de)

### ISSUE THREAD

**Issue by thebiggeordiegeek** [advplyr/audiobookshelf#731]
### Describe the feature/enhancement

Just as I said there are sometimes differences between the services in the UK and US.

just wondering if it’s possible to be able to match data from the UK service too, I’d imagine it would have to be a separate option.

**Comment by advplyr** [comment]
I'm not sure what you mean, can you give a specific example?

**Comment by thebiggeordiegeek** [comment]
Hey

So when you match a book, to get the metadata, you can choose different sources, such as Audible, Google Books, iTunes etc.

There are sometimes, admittedly rare occasions when a book or audio drama is on one but not the other, or has different publishers etc.

it’s not an urgent request, just cause it’s super rare that it happens, but it can be silly things, like descriptions using colour instead of color for example.

**Comment by advplyr** [comment]
Do you know if the Audible API supports returning other languages?

**Comment by mmuenker** [comment]
I have a similar problem with Audable DE.

For example the book "Der kleine Ritter Trenk".

When the matching is executed, the request is sent to `api.audible.com`. This request results in an empty response. However, if the same request is sent to `api.audible.de`, a match results.

**Comment by advplyr** [comment]
I see what you mean now. We just moved from the audible api to the audnexus api which gives us more metadata from audible that the audible api doesn't provide.
It looks like audnexus only supports `api.audible.com` right now

**Comment by Hoempi** [comment]
Would it be possible to support direct API calls again, in addition to AudNexus? For example for children's audiobooks a lot of the foreign languages are on e.g. Audible.de but not Audible.com. So right now, they cannot be matched at all.

**Comment by Hoempi** [comment]
Since work on the multi-region support AudNexus is continued, I guess waiting for it makes more sense, as not to bloat the code base of Audiobookshelf.

**Comment by advplyr** [comment]
Added in [v2.2.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.1)

![image](https://user-images.githubusercontent.com/67830747/194730929-bbbeecda-26e9-49a3-a247-ed08c8291031.png)

I think we'll also need to add this for the author lookups but in my tests the same author data was getting pulled so I haven't done that part yet.

**Comment by Hoempi** [comment]
Works like a charm, thank you very much!
