### ISSUE TITLE
[Bug]: Support for subfolders for reverse proxies

### ISSUE THREAD

**Issue by Moltenkore** [advplyr/audiobookshelf#740]
### Describe the issue

It looks like only the root domain can be used:
e.g ``amazingdomain.com/``
instead of ``amazingdom.com/audiobookshelf/``

### Steps to reproduce the issue

1. Try and set a reverse proxy to a subfolder.
2. The interface errors out when visited.

### Audiobookshelf version

v2.0.21

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Duplicate of #385
