### ISSUE TITLE
[Enhancement]: Have an option for the progress bar to only be for the current chapter

### ISSUE THREAD

**Issue by alexmaras** [advplyr/audiobookshelf#741]
### Describe the feature/enhancement

I'd like to have the option to have the progress bar only be for the current chapter, not for the length of the book. At the moment, I've had a couple of instances where my progress has reset intermittently (I'll file a bug about that, trying to work out the pattern there), and trying to get back to where I was was quite cumbersome.

This is especially important for audiobooks with long chapters - skipping to a chapter is fine, but if that chapter is multiple hours long, finding out where within that chapter I was was really difficult.

**Comment by jmt-gh** [comment]
Added support for this in #744

**Comment by alexmaras** [comment]
@jmt-gh I'm testing this out on `:edge` from the docker image. The track itself is working well - tracking correctly, and updating well when skipped using the skip back and forward. It doesn't work when clicking on the progress bar to skip around however - it's still tracking as if it's the progress bar for the whole book.

**Comment by alexmaras** [comment]
https://github.com/advplyr/audiobookshelf/pull/776 - made up a quick PR to fix the issue.

**Comment by alexmaras** [comment]
Thanks for all your help @jmt-gh and @advplyr - Happy that this is working great now :+1:
