### ISSUE TITLE
[Bug]: Search should to include hits with or without apostrophes, commas and other special characters

### ISSUE THREAD

**Issue by FlamingoDaBird** [advplyr/audiobookshelf#750]
### Describe the issue

Search should to include hits with or without apostrophes, commas and other special characters

Example; If I search for at title named: "Old Mans War"
I find nothing

But if I search for "Old Man's War" I do find the title. (or "Old", "Old Man"   and such)

running backend v2.0.22
and android app 0.9.49  (same search 'bug' here as well)
Unraid docker.

Would be great if would include search hits with or without special characters.
Thank you very much.

### Steps to reproduce the issue

1. search without special characters doesn't find titles.

### Audiobookshelf version

v2.0.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Updated in [2.0.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.23)
