### ISSUE TITLE
Help: Apache reversproxy problem

### ISSUE THREAD

**Issue by kobemtl** [advplyr/audiobookshelf#751]
Thanks for all the good work first. 

I am using portainer with the default docker-compose for audibookshelf. Apache reversproxy config from the official document as well. Everything was working perfectly until 2 days ago. Now my subdomain for audiobookshelf is very very slow to open. Then after input username and password I get "unknow error" and not able to login. By using the internal IP I have no problem to access. No error log related find on the audiobookshelf or apache host. from my apapche instance i have no problem to curl or telent audiobookshelf. And I have some other application with same way ( portainer + apapche reversproxy ) works fine. 

I already tried everything I could think of to pinpoint what goes wrong. But I just can't get anything. Could someone help or have idea please? Thanks.

**Comment by advplyr** [comment]
Your best option to get help will be in the discord server

**Comment by kobemtl** [comment]
Oh I see. Thanks.
