### ISSUE TITLE
[Bug]: Triggering library scan impossible on touch screen

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#753]
### Describe the issue

Things that require the cursor to hover over something are unusable on touchscreens (e.g. mobile devices). This affects things like triggering a library scan, changing library settings, etc.

### Steps to reproduce the issue

1. Access the web UI on a touchscreen.
2. Try to access any function that requires hover.

### Audiobookshelf version

2.0.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [2.0.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.23)
