### ISSUE TITLE
[Bug]: tabs missing from the "edit" modal while in landscape on (non-app) mobile. (Pictures included)

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#754]
### Describe the issue

Tabs missing from the "edit" modal while in landscape on (non-app) mobile.

Portrait (expected appearance):
![Screenshot_20220618-195533844](https://user-images.githubusercontent.com/25695143/174491174-60364545-b937-4aac-af43-b25d05f2eb2a.jpg)

Landscape send to cut off the top, making the tabs unusable:
![Screenshot_20220618-195525318](https://user-images.githubusercontent.com/25695143/174491199-54f724bd-b90e-43f9-bb00-9dde75fea6b3.jpg)

### Steps to reproduce the issue

1. Go to any book details page.
2. Click/Tap thethe pencil icon "edit" button.
3. Enter landscape mode.

### Audiobookshelf version

2.0.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [2.0.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.23)
