### ISSUE TITLE
[Bug]: Updating to 2.0.22 appears to break Chromecast

### ISSUE THREAD

**Issue by dchawisher** [advplyr/audiobookshelf#756]
### Describe the issue

Version 2.0.22 appears not to detect my Nest Mini Chromecast device, but 2.0.21 does. 

### Steps to reproduce the issue

1. Set up a Chromecast device on the network. 
2. Open the android app or the web browser with an audiobookshelf server running version 2.0.22. The chromecast button will not be available.
3. Revert to version 2.0.21. The chromecast button should now be available (and will work normally when pressed). 

### Audiobookshelf version

2.0.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
The issue here is the chromecast button on mobile screen size of the web app is disappearing. I just fixed that for the next release. I tested the android app and that is still working and larger screen sizes of the web app is still working.

**Comment by dchawisher** [comment]
I was having the problem in the web app. But whatever it is, updating to 2.0.22 again did not cause it to recur, so I'm happy to treat this as closed.

**Comment by advplyr** [comment]
Fixed in [2.0.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.23)
