### ISSUE TITLE
[Bug]: Automatic backup very often does not work

### ISSUE THREAD

**Issue by stefanop1** [advplyr/audiobookshelf#761]
### Describe the issue

If I use manual backup, it always works but automatic (at 1:00 am) doesn't work.
I think it's due to competition with podcast downloads.
The log contains:

2022-06-20 01:00:41
DEBUG
[LibraryItem] Success saving abmetadata to "/podcast/The Atlas Obscura Podcast/metadata.abs"

2022-06-20 01:00:44
**WARN
[BackupManager] Archiver warning: ENOENT: no such file or directory, lstat '/config/libraryItems/tmp/data.0.json.1655679632289.tmp'**

2022-06-20 01:00:45
DEBUG
[DB] Library Items updated 1

### Steps to reproduce the issue

1. Add some podcast with automatic download of new episodes
2. Configure n automatic daily backup

### Audiobookshelf version

v2.0.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.24](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.24) as temp workaround backups are scheduled for 130. Eventually this should be configurable and podcast episode checks will be configurable so that's why I call this a temp fix.
