### ISSUE TITLE
Show book # in list of results for possible matches

### ISSUE THREAD

**Issue by JamesDean3** [advplyr/audiobookshelf#762]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

Some times the initial screen that shows your matches isn't enough to know which you should select because all you know is which book number it is in the series, in these cases, you might have to click each possible match to find the correct one. 

### Describe the solution you'd like

If your API calls include the book number when searching possible matches, please include that in the list of results. 

### Describe alternatives you've considered
Looking at each individual possible match.

**Comment by advplyr** [comment]
Added in [2.0.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.23)
