### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by dmuiX** [advplyr/audiobookshelf#763]
### Describe the feature/enhancement

 I am just impressed how good this server app is working. Been using it for 2 months now. Had no issues so far. Also the beta apps for ios and android are working pretty amazing. Thanks a lot :)

**Comment by projx** [comment]
I'm 100% with the OP, I'm in awe of this app..

**Comment by advplyr** [comment]
Thank you! There are still plenty of bugs with the mobile apps but I'm glad you have managed to avoid them so far.
