### ISSUE TITLE
[Feature Request]: Show Chapter Length

### ISSUE THREAD

**Issue by fabh2o** [advplyr/audiobookshelf#767]
### Describe the feature/enhancement

At the moment in the chapter menu we can see the title of the chapter and the absolute start time of it inside the audiobook.
While it might be useful to know when each chapter start, I think that knowing the duration (relative difference between each chapter) can be more interesting.
Having a switch in the settings to toggle between the two display mode would be ideal.

**Comment by advplyr** [comment]
Added in [2.0.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.23)
