### ISSUE TITLE
[Bug]: 'Mark as Not Finished' doesn't work

### ISSUE THREAD

**Issue by filcuk** [advplyr/audiobookshelf#771]
### Describe the issue

'Mark as Finished' works as expected.
However when attempting to 'Mark as Not Finished', UI message pops up to confirm but the audiobook remains marked as read.

Debug log returns: `[DB] Updated user: 1`

Restarting container doesn't help.

### Steps to reproduce the issue

1. Navigate to Audiobooks
2. Select one
3. Mark as Finished
4. Mark as Not Finished
5. Check the status

### Audiobookshelf version

v2.0.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [2.0.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.23)
