### ISSUE TITLE
[Enhancement]: Store tags in the .abs file

### ISSUE THREAD

**Issue by Rubecks** [advplyr/audiobookshelf#772]
### Describe the feature/enhancement

With the "Store metadata with item" setting enabled, all the other metadata is stored inside the .abs file, but the tags aren't.

**Comment by itschrisonline** [comment]
This was raised in this issue here https://github.com/advplyr/audiobookshelf/issues/203 but is no lnger on the wiki.

**Comment by advplyr** [comment]
Added in [v2.2.15](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.15)

Note: tags are saved in the metadata.abs in a JSON format. see https://github.com/advplyr/audiobookshelf/pull/1469
