### ISSUE TITLE
[Bug]: Docker image version 2.0.21 and 2.0.22 no longer start

### ISSUE THREAD

**Issue by DocBrown101** [advplyr/audiobookshelf#773]
### Describe the issue

The docker image version 2.0.20 works fine. As soon as I update to version 21 or 22, access via the web interface is no longer possible.
The image then stops completely after a short time.

After that I use version 2.0.20 and everything works again.

Unfortunately, there is no error message in the log.

### Steps to reproduce the issue

1. Update to version 21 or 22 and start the image.

### Audiobookshelf version

2.0.21 and 2.0.22 

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not able to reproduce this issue

**Comment by DocBrown101** [comment]
I was able to identify the error. For security reasons I run all my containers as "read_only". This was no longer possible with the new versions 21 and 22.

I have now mapped a temp directory to the directory "/home/node/.npm" and now it works again :)

**Comment by skyzuma** [comment]
is there any other folder needed to add to the tmpfs like metadata or if a book ended? i have warn in the logs "[ApiRouter] Library item not found for users progress li_XXX"?

**Comment by DocBrown101** [comment]
For the operation of the image, this one folder was enough:
tmpfs:
      - /home/node/.npm:mode=770,size=10m,uid=1000,gid=1000

**Comment by skyzuma** [comment]
i think there are more folder needed ... my ended books was not automarked as complete > manual mark needed ... the backup was not created ([BackupManager] Archiver warning: ENOENT: no such file or directory, lstat '/config/sessions/tmp/data.1.json.1656198025043.tmp' ... "[BackupManager] Backup appears to be corrupted: /metadata/backups/2022-06-26T0100.audiobookshelf") ...

i think @advplyr can say more about it ?

**Comment by DocBrown101** [comment]
@skyzuma oh, I hadn't thought of that at all. Then there are probably still a few directories missing. Thanks for the hint!
@advplyr I hope you can help us here to continue to operate the image as read only.

**Comment by advplyr** [comment]
The `/metadata` and `/config` folders will need to be writable. Your libraries will only need to be writable if you have server settings enabled to store covers/metadata with your library items.

**Comment by skyzuma** [comment]
/metadata and /config are mounted volumes and writable (these cant add to "tmpfs" cause of duplicated entries) ... now i listen an book and the log tells me this:

error: all 5 seconds
> [DB] Update entity session Failed: Error: ENOENT: no such file or directory, lstat '/config/sessions'

error: all 5 seconds
> [DB] Update entity user Failed: Error: ENOENT: no such file or directory, lstat '/config/users'

and after i paused the book

warn
> [ApiRouter] Library item not found for users progress li_gn4ymda1xv72abbfnq-ep_3ctcbfr4c5jyuajn2x
> [ApiRouter] Library item not found for users progress li_gn4ymda1xv72abbfnq-ep_7alovemhdbajvkvenp
> [ApiRouter] Library item not found for users progress li_gn4ymda1xv72abbfnq-ep_528ol0zr9vqhfi28h4

and after that start the book again ... same error all 5 seconds ...

**Comment by DocBrown101** [comment]
@skyzuma If you have already mounted the directory, you probably lack write permissions for it.
