### ISSUE TITLE
[Bug]: Can't save manually inputted series

### ISSUE THREAD

**Issue by DieselTech** [advplyr/audiobookshelf#778]
### Describe the issue

When editing metadata, if you try to manually add a series title and sequence # , pressing save does nothing. It won't close the dialog box. This prevents manual edits from being able to save. 

### Steps to reproduce the issue

1. Edit metadata
2. Add series info
3. Try to press save

### Audiobookshelf version

v2.0.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not able to replicate this. Are you saying you are unable to add new series from the details tab?

**Comment by DieselTech** [comment]
Yesterday when I created the bug report I was able to replicate it across every entry I came across. Now today I'm not able to. If it happens again I'll make sure to take a video of it right away.

**Comment by advplyr** [comment]
Sounds good let me know
