### ISSUE TITLE
[Enhancement]: [podcasts] Manual Download options for podcasts?

### ISSUE THREAD

**Issue by SuburbanVampire** [advplyr/audiobookshelf#779]
### Describe the feature/enhancement

Unless I'm not seeing it in the UI and documentation (which is entirely possible), at present the only way to make ADB download podcasts is via automatic scans. It would require additional UI work to implement, but being able to manually download individual or bulk episodes from a podcast's back catalog would be probably one of the single most helpful things for me as a new user migrating over.

A use case: I have some old episode of Some Podcast that is one of my favorites, and randomly sometimes would like to listen to it. 
Currently there's no way to do that I can find.
It seems like either the edit podcast details pop-up or the main page for an individual podcast within the library would make the most sense. 
I was thinking this would be basically a table type of display which is pretty much just a dump of the current RSS feed from the podcast, enabling the user to scroll through and pick what they want to download.

Probably would want to cap the maximum number of downloads in a batch to something reasonable like 100? I'm just a QA guy, I don't really know what I'm talking about with design.

**Comment by advplyr** [comment]
Have you tried pressing the search icon?
![image](https://user-images.githubusercontent.com/67830747/175792270-c5f45c3e-3c9e-47c4-9aec-192c5568f8f4.png)

I'm not sure if I'm understanding your request but if so then that is what you are looking for.

**Comment by SuburbanVampire** [comment]
This is literally the first I'm seeing this button despite spending hours editing podcast LOL

Sorry about that. Is there documentation to this effect anyplace? If not, would be helpful.
