### ISSUE TITLE
[Bug]: after backup load > invalid (no) author cover

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#781]
### Describe the issue

ive change from normal docker to rootless docker ... ofyi

after loading the latest backup (without "read_only" / "tmpfs" flag ) > all author cover are invalid but all images are there and i can find it in the location ... all others are fine :) .. ive deleted manual all invalid covers and runned: "match all authors" and now its fine :)

> [2022-06-26 19:50:15]  WARN: [CoverManager] Attempting to remove file that does not exist /metadata/authors/aut_cmhi8vmzrh9vz37dgr.jpg
[2022-06-26 19:50:16] ERROR: [FfmpegHelpers] Resize Image Error Error: ffmpeg exited with code 1: /metadata/authors/aut_e5xl1ex4f73bpdqf2r.jpg: No such file or directory
  ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219
  configuration: --prefix=/usr --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --disable-debug
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
/metadata/authors/aut_e5xl1ex4f73bpdqf2r.jpg: No such file or directory

### Steps to reproduce the issue

1. create any new ABS instance and load the backup ...

### Audiobookshelf version

2.0.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Updated in [2.1.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.3)

Backups will not include the author images.
