### ISSUE TITLE
[Enhancement]: Podcast episode counter should show new episodes not total count

### ISSUE THREAD

**Issue by andonevris** [advplyr/audiobookshelf#782]
### Describe the feature/enhancement

Currently when listing podcasts in the "recently added" view there is a number on the top right showing episode number count.

I would argue it's far more useful to know how many new episodes are in each podcast in the top right corner rather than total episode count.

**Comment by advplyr** [comment]
Since we use that same format for showing the number of books in a series we should change how it is displayed so it is clear that it is the number of new episodes. Do you have an idea for design?

**Comment by andonevris** [comment]
I think it could be as simple as changing the colour of the badge to something like yellow or red like so it looks more like a flag..

**Comment by advplyr** [comment]
What would determine whether an episode is new?
Would that be all episodes that have no progress?

**Comment by andonevris** [comment]
I would say anything that isn't finished should count as new

**Comment by advplyr** [comment]
This was added in v.2.3.0 but best to use the latest 2.3.3
