### ISSUE TITLE
Unknown error for login to playstore app

### ISSUE THREAD

**Issue by ThaBlazee** [advplyr/audiobookshelf#789]
![Screenshot_20220629-000349_audiobookshelf](https://user-images.githubusercontent.com/38342167/176375686-9d47a110-04a0-4601-8543-54d4292ce71a.jpg)
getting an unknown error when trying to log into the app from playstore. tried with different users as well with no luck. logging in via browser works, even on the phone. 
[Edit1]
sorry I force closed the app and tried to reconnect and it worked for some reason. 

Also I did not see the app repo until I had already posted this, and I cant seem to delete this issue. 

Apologies
[Edit2]
Just found another error though, cant download audiobooks from either web or the application. It fails.

I run the service on a docker.

**Comment by advplyr** [comment]
Please open another issue in the audiobookshelf-app repo with reproducible steps and info about your device model and version. Also audiobook format (single m4b or multiple mp3). As much detail as you can provide.
