### ISSUE TITLE
[Enhancement]: possibility to sync progress of downloaded media

### ISSUE THREAD

**Issue by sluggathor** [advplyr/audiobookshelf#790]
### Describe the feature/enhancement

is syncing of progress of downloaded audiobooks with the server possible? i am listening mostly on the go and don't have my server exposed to the internet. would it be feasible to sync when the connection is restored. there is also no progress synced when listening to downloaded media while being connected.
i am using the android app and server in docker.

**Comment by advplyr** [comment]
Yes that is how it should work now. There are some issues open relating to this in the audiobookshelf-app repo. Maybe join the discord with more info about your setup
