### ISSUE TITLE
[Bug]: ASIN Search Appears to be Broken

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf#794]
### Describe the issue

I am trying to add the audiobook 'Galaxy's Edge' to my server and use the match function. When I search via the title with the Audbile provider, since the audiobook title is the same as the series title, the results are all of the books in the series (and since only a limited number of results are returned, the book named Galaxy's Edge does not show up). 

I then attempted to search using the ASIN of the book (which is B079LRSMNN), and it says that there are no results. I tried other ASINs and received the same result (no results). 

Here is what the debug log says:

> 2022-06-29 22:11:08 DEBUG  Book Search: title: "B079LRSMNN", author: "", provider: audible
> 
> 2022-06-29 22:11:08 DEBUG [Audible] ASIN url: https://api.audnex.us/books/B079LRSMNN
> 
> 2022-06-29 22:11:08 DEBUG Book Search, no matches.. checking cleaned title and author
> 
> 2022-06-29 22:11:08 DEBUG Book Search: title: "b079lrsmnn", author: "", provider: audible
> 
> 2022-06-29 22:11:08 DEBUG [Audible] Search url: https://api.audible.com/1.0/catalog/products?num_results=10&products_sort_by=Relevance&title=b079lrsmnn

It appears that the ASIN URL finds the book, but the search still comes back empty. 

### Steps to reproduce the issue

1. Go into the book editor
2. Go to the Match tab
3. Search for a book using the ASIN with Audible as the metadata provider
4. No results

### Audiobookshelf version

v2.0.22

### How are you running audiobookshelf?

Docker

**Comment by jmt-gh** [comment]
Noting that I was able to reproduce this on my production instance by just trying to match an arbitrary book to `B079LRSMNN`

@feerlessleadr , can you confirm the metadata at the following URL is indeed the metadata you'd expect to see?
https://api.audnex.us/books/B079LRSMNN

**Comment by feerlessleadr** [comment]
Yep, that's the correct metadata.

**Comment by jmt-gh** [comment]
Thanks! I was able to reproduce this with seemingly other ASINs as well. I'll take a look

**Comment by jmt-gh** [comment]
A fix for this is up in #795 -- it will be available in whatever the next release is after that PR gets merged. Thanks for the report!

**Comment by feerlessleadr** [comment]
Thank you!

**Comment by advplyr** [comment]
Fixed in [2.0.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.23)
