### ISSUE TITLE
[Enhancement]: Bookmark improvements

### ISSUE THREAD

**Issue by zblesk** [advplyr/audiobookshelf#796]
### Describe the feature/enhancement

Thanks for the great app. I love the bookmarks, and the fact that they sync. 

A few minor things I'm missing: 

As it is, I can only view bookmarks for the *currently playing* book. I would like for the UI to have an extra button in the book menu, e.g. here. 
![image](https://user-images.githubusercontent.com/4245227/176614545-874dbb93-c2dd-4347-966c-95cd53b95d5c.png)
(I have to admit, a few times I clicked the 'mark as finished' button because I thought it looks like bookmarks.)

Secondly, I can only view bookmarks for the currently playing *book*. I would really like to make bookmarks in podcasts as well. 

(And third, I would appreciate the bookmarks in e-books as well, but I understand that's probably further in the future.)

**Comment by advplyr** [comment]
Added in [v2.1.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.1)

Bookmarks for podcast episodes should be in a different issue but I'm not sure about supporting that.
There is a request open for ebooks

**Comment by zblesk** [comment]
@advplyr Thank you! 

Do you not want podcast bookmarks? Why is that? (So I should not open a separate feature request?) 

I often listen to books and podcasts on the go; but I still try to learn something from them. With books, I just make a bookmark and process it later, when I'm sitting at my computer; I'd like to be able to do the same with podcasts. (As it is, I either have to jot down a few keywords and hope I remember what I meant, or write down a timestamp manually... neither is very convenient.)

**Comment by advplyr** [comment]
I see what you mean and can see that value in that. You can open another request for podcast episode bookmarks, I don't think it will be too difficult to implement.
