### ISSUE TITLE
[Enhancement]: Go to Time Stamp 

### ISSUE THREAD

**Issue by DieselTech** [advplyr/audiobookshelf#798]
### Describe the feature/enhancement

Having the ability to jump directly to a time stamp would be nice. That way when the app screws up I can get back to my last known spot without dragging a fine grained progress bar kind of close to where I was, then cranking on the 10 second rewind button a dozen times. 

Or maybe in the last sessions window having the "Last Time" clickable. 
![image](https://user-images.githubusercontent.com/30128380/176977744-4c165904-f025-4d13-adfd-1590e07e55c5.png)

**Comment by advplyr** [comment]
Added in [v2.1.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.1)

This has to first check if the library item still exists.
