### ISSUE TITLE
[Bug]: Cache directory not recreated after purge

### ISSUE THREAD

**Issue by mcdinner** [advplyr/audiobookshelf#800]
### Describe the issue

After purging the cache directory in settings the cache folder is not recreated.
After restart / container restart the cache folder is recreated.

As I can see the cachePathsExist property in the CacheManager does not get reset on purge.

### Steps to reproduce the issue

1.  Go to Settings and purge cache folder.

### Audiobookshelf version

v2.0.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.24](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.24)
