### ISSUE TITLE
[Enhancement]: maintenance Mode

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#803]
### Describe the feature/enhancement

if i add books and the scanner runs (watcher disabled (watcher enabled = multible wrong / same books) > manual scan), the server comes "unavailable" during the scan ... is this a possible feature?

if i add books > any button / switch > server "offline / maintenance Mode" > so i can add my books and no one can connect (web/app) > anyone see the message: " maintenance in progress" or any similar ...

**Comment by advplyr** [comment]
I don't really understand the use-case for this

**Comment by skyzuma** [comment]
i have a raspberry pi with a external harddrive = slow in all >>> maintenance Mode >>> i can work / upload and edit books without any other user have an unusable sever connections ... if i upload books and the watcher runs > any connected user will be offline during the watcher scan process (logs: user offline / connection lost / ...)

**Comment by advplyr** [comment]
This is not going to be supported
