### ISSUE TITLE
[Enhancement]: Support OGG Audio file extension (.oga)

### ISSUE THREAD

**Issue by mchl-btlr** [advplyr/audiobookshelf#804]
**Describe the issue**
".oga" file extension is not recognized as proper OGG audio file.
Please enhance scanner to treat ".oga" files the same as ".ogg" files.

**Steps to reproduce the issue**
After adding an audiobook file with an .oga extension (official extension for file format OGG/Opus) and starting a library scan, it does not get added to the library.
After changing the file extension to .ogg (formerly used extension for OGG/Vorbis) and starting the scan, the file gets recognized and properly added with its metadata.
Audiobookshelf version
v2.0.23

**How are you running audiobookshelf?**
Docker

**Comment by advplyr** [comment]
Added in [v2.0.24](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.24)

**Comment by mchl-btlr** [comment]
Thanks for fixing that so quick, I can confirm it is now working as expected (v2.0.24). :+1:
