### ISSUE TITLE
[Enhancement]: warning on 'Mark as Finished'

### ISSUE THREAD

**Issue by Lanjelin** [advplyr/audiobookshelf#805]
### Describe the feature/enhancement

'Mark as Finished' does exactly that, with no warning, even if you're in the middle of a book.
Resetting progress gives a popup that you'll have to confirm.

Adding a similar popup to 'Mark as Finished' __\_if\___ there is progress on the book, would avoid accidentally losing progress due to misclicks, while maintaining the flexibility to quickly set unstarted books as finished.

**Comment by advplyr** [comment]
Added in [v2.1.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.1)
