### ISSUE TITLE
[Enhancement]: Audiodrama library & light app theme

### ISSUE THREAD

**Issue by Thomas-O** [advplyr/audiobookshelf#806]
### Audiodrama library & light app theme

Audiobookshelf is a revelation. A far more polished (and reliable) experience than my previous audiobook solution: PiCorePlayer / LMS + bookmark plugin. The added support for podcasts is an additional wonderful and welcome surprise. To be honest, I don't think there's that much that can be done to improve the experience. Though if I was being a little picky I would suggest these two enhancements. Hope it's not too much to ask. 

1. Audiodrama library. I know Audiodrama is a relatively niche interest - _outside of the UK and few other countries with enlightened public service broadcasting_ - but it really would be grand to have an Audiodrama library option with an appropriate library and metadata structure. It's possible to lump them in with audiobooks but it's a slightly rubbish and clumsy compromise.

2. What about a white or light theme option for the Audiobookshelf mobile app? I know black is the eternal cool but sometimes it can be a little difficult to navigate a dark mobile screen in bright / outdoor conditions. And it'd be nice to have the alternative view on the app.

**Comment by advplyr** [comment]
Audiodrama's have been brought up a few times. I think they are one of the reasons the "collapse series" option was requested because users were putting them into series and didn't want them clogging up their library view.

Do you know of any audiodrama API's that we could use?

**Comment by Thomas-O** [comment]
> Do you know of any audiodrama API's that we could use?

Other than a handful of release on Audible there isn't a platform where you can buy or stream audiodrama, so I don't imagine you'll be able to find a commercially supported API. Though maybe you could look at something like [Audio-Drama.com](http://audio-drama.com/doku.php). But when I've use the site's search function it came up short every time.

Maybe the only realistic route would be to provide a custom library option. Where the user can disable metadata fields.

When I use LMS I access audiodrama via the Genre tag. While that helps a little, the next step in the LMS library is a confusing list of artists. Which isn't that useful. I suppose there are some people who can remember who wrote the script for this or that audiodrama, but it ain't me. The only way to simplify the navigation is to put the audiodrama title in the artist metadata field. But then your metadata becomes an utter mess.

If I was using a custom library option for audiodrama* I'd probably disable most of the fields and limit the metadata to just 2: title and description. Though maybe a few tags (genre & original author etc.) might also be useful.

* _A custom library could also be useful for poetry, soundart, documentary and other bits and bobs that won't fit neatly in to an audiobook library._

**Comment by advplyr** [comment]
What would be the problem with creating a book library and only using the title/description metadata?

Nothing says you need to use the metadata fields that are there. I'm not sure what the difference would be with a custom audio library other than removing the series. I imagine some people using the custom audio library would still want to put in an author/artist.

**Comment by Hackmodford** [comment]
I am currently using a book library and have no issues. I just wish there was a better icon choice such as a microphone or a radio :)

![image](https://user-images.githubusercontent.com/326668/196270113-e27955c0-63a9-4ab1-ab56-991bbf6ba2a6.png)

![image](https://user-images.githubusercontent.com/326668/196270154-3dd8f31d-f751-4dd0-b9d6-936d6c95c4cb.png)

**Comment by advplyr** [comment]
Good idea, we can add more icons. Created an issue for that #1075

As for this OP I think we can manage audiodramas using the book media type unless some specific outline can be made for that with metadata providers.
OP also mentions light theme which I would also like to do at some point. We have even discussed allowing for custom themes. That is for another issue though.
