### ISSUE TITLE
[Bug]: clientEmitter - no clients found

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#807]
### Describe the issue

LOG
>DEBUG [Server] clientEmitter - no clients found for user usr_l6exxcqul8u9nmnnxh

what is this meaning? the server cant identify the (mobile) device who is playing the book? if so, in the Listening Sessions (Device Info) there are  the device model (phone model / browsername)

Android version: 12 (One UI 4.1) > Device model: SM-G975F (this is showing in: Listening Sessions (Device Info) )

### Audiobookshelf version

2.0.23

### How are you running audiobookshelf?

Docker

**Comment by skyzuma** [comment]
>DEBUG [Server] clientEmitter - no clients found for user root (Tablet SM-t725)

its todays log for me (root / owner)

**Comment by advplyr** [comment]
A client is referring to a web socket connection. The server attempted to emit an event to the root user but no clients were found to be connected for the root user.
Socket connections can be shaky but if the mobile app for you is never connecting as a client then you have an issue with your network.

**Comment by skyzuma** [comment]
> but no clients were found to be connected for the root user.

i dont understand this information

> but if the mobile app for you is never connecting as a client then you have an issue with your network.

all is ok ... no problems in the network ... i can hear books without any problems from internal and external address ...  this message comes with "[PlaybackSessionManager] syncSession" ... is this message a bug or can i ignore this?

**Comment by advplyr** [comment]
The next mobile release will have an icon in the toolbar showing whether you are correctly connected to the server through the web socket. There were some fixes with that connection in the next release of the mobile app.

You can ignore this now but after the mobile app release look for that icon in the app bar you won't be able to miss it.
