### ISSUE TITLE
[Bug]: quickmatch Books with 2 authors, 2 authors get added as a single unit

### ISSUE THREAD

**Issue by ThaBlazee** [advplyr/audiobookshelf#808]
### Describe the issue

![firefox_i3DIfDlLdp](https://user-images.githubusercontent.com/38342167/177411840-90e2a5b8-7d73-4486-a3c5-77a718b382f3.png)

Trying to quickmatch the metadata of books who have 2 authors or more, the authors get added as a single unit with a comma separating them instead of separate authors.

### Steps to reproduce the issue

1. Try to quickmatch metadata for any book with multiple authors

### Audiobookshelf version

edge

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.24](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.24)
