### ISSUE TITLE
Root user login reset to default after server updates

### ISSUE THREAD

**Issue by scorpio862** [advplyr/audiobookshelf#81]
I noticed that some updates of the AudioBookshelf server are causing the reset of the root user login details. 
So my username goes back to Root but the bigger problem is that the password is beeing removed.

My server is accesible externally from the web so few times I ended up with unsecured access to the server so anybody could access it until I noticed this and set up the password again.

This happened after recent update to v1.3.5 and few times before.

**Comment by advplyr** [comment]
I just released an update `v1.4.0`.
When you get a moment can you update and see if the user gets reset again?

**Comment by scorpio862** [comment]
I just updated to 1.4.0 and there was no root user reset. 
I'm following this project since it appeared in Unraid comunity apps and I noticed user reset maybe around 4 times so it wasn't after every single update. It looks like only the root user was reset. The other users I've created has were fine.

**Comment by advplyr** [comment]
Can you check the logs for any errors on startup?

**Comment by scorpio862** [comment]
The AudioBooshelf logger page does not show any logs from the strartup so I didn't see any errors. It looks like it starts showing the logs from the moment I open logger page and set it to Debug.

I checked the container log as well and there was no errors in the log. 

I just updated to v.1.4.5 and the root accound didn't reset to default after this update.

**Comment by advplyr** [comment]
Do you have other users, and those users are not getting reset? Just the root?

**Comment by scorpio862** [comment]
I have another user and it never changes. Only the root user gets reset to default.
