### ISSUE TITLE
[Enhancement]: own page for ... like plex

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#810]
### Describe the feature/enhancement

(Recently Added) / Recent Series / Listen Again (as complete series with the readed green underline and the series name (no collapse series)) and Newest Authors ordered with the latest updates like seeing on the startpage ... maybe list the latest 10 / 20 / 30/ items?

why?

only as faster way to identify the newest items

**Comment by advplyr** [comment]
I don't think I understand what you are asking for

**Comment by skyzuma** [comment]
an own page or "a linked to" for every category like "Recently Added" / "Recent Series"  / "Listen Again" ... Newest Authors can linked to the authors page with "sorted by newest author" or similar

if i can click on in Home on "Recently Added" and its goes to an own / new page with listed all recently added books or linked to the library category with the filter "Recently Added" if its available

if i can click on in Home on "Recently Series" and its goes to an own / new page with listed all recently created series or linked to the library category with the filter "Recently Series" if its available

if i can click on in Home on "Listen Again" and its goes to an own / new page with all book i have listened or linked to the library category with the filter "listened books" if its available

**Comment by advplyr** [comment]
Combining this request with #923 to add a separate page for each category and a view all button on the category shelves.
