### ISSUE TITLE
[Bug]: Notification toast blocks settings

### ISSUE THREAD

**Issue by Jdiesel87** [advplyr/audiobookshelf#819]
### Describe the issue

When running a library scan or other task the status/notification bubble blocks the settings and use buttons.
<img width="395" alt="Screenshot 2022-07-07 223906" src="https://user-images.githubusercontent.com/14824476/177918253-10bf054a-f5e9-485b-8183-91eec46751d1.png">

### Steps to reproduce the issue

1.  Run a library scan
2. Try to access the settings menu

### Audiobookshelf version

2.0.23

### How are you running audiobookshelf?

Docker

**Comment by Jdiesel87** [comment]
Either move bubble to bottom right/left or have ability to dismiss or minimize without canceling

**Comment by advplyr** [comment]
Fixed in [v2.0.24](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.24)

The toasts will be shown underneath the appbar/toolbars
