### ISSUE TITLE
Fix birth-time sorting defect

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#820]
### Describe the issue

Both ascending and descending sort shows books in the same order. Issue created based on conversation on discord.

### Steps to reproduce the issue

NA

### Audiobookshelf version

2.0.23

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I think this has since been fixed. I remember seeing this at one point but must have fixed it without noticing
