### ISSUE TITLE
[Bug]: New Tracks not ordered correctly

### ISSUE THREAD

**Issue by MikePrime21** [advplyr/audiobookshelf#823]
### Describe the issue

I use this for WebNovels and convert the chapters to speech mp3 files.  Since the watcher makes everything too slow, I turned it off an just scan the library when needed.  What I noticed is that after the scan, newly added chapters appear at the top and not at the end.  The Track From Filename is correct, but the Current track number has duplicates.  See image below.

![image](https://user-images.githubusercontent.com/84364521/178128158-f748a5f4-bbb5-4b51-b197-fd2cdf8b529a.png)

### Steps to reproduce the issue

1. Make sure Scanner is disabled
2. Import an audiobook using the library scan
3. Add new tracks that should be at end of book
4. Run library scan again
5. Newly added tracks are inserted at top of track list alternating between new and old.  See image.  

### Audiobookshelf version

v2.0.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.0.24](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.24)
