### ISSUE TITLE
[Enhancement]: Return to previous page after editing chapters

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#827]
### Describe the feature/enhancement

Currently after editing chapters it drops you onto the book's page. I would prefer that it returns you to the page you were on before editing chapters. 

So if I'm on the library page and click on the pencil to edit metadata of a book, and then click chapters tab to edit chapters, when I finish editing chapters it should return me to the library page instead of opening the book's page.

**Comment by advplyr** [comment]
Added in [v2.1.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.1)
