### ISSUE TITLE
Unlimited Right Scroll (Feature Request)

### ISSUE THREAD

**Issue by Cobolt78** [advplyr/audiobookshelf#829]
I love the UI and love Continue Series but can you code it so you can scroll right unlimited times or until the end instead of 10 books for all sections on the home page, Continue listening, Continue Series, Recently added, recent series, listen again. I have listened to more than 10 books that are in a series and to only be able to scroll across 10 books it won't show all the books that are next in the series that I have listened to. Likewise sometimes I would love to scroll through recently added series but can only scroll a few across.
Even if the Heading's like "Continue Series" was clickable and would take you to a new page with all your continue series books, likewise if Recent Series was clickable and would take you to the series page but was sorted from the last added to oldest. 

Thanks again for everyone's hard work, just wish I could help out someway instead of just requesting features. :(

**Comment by advplyr** [comment]
Why did you close this as not planned?

**Comment by Cobolt78** [comment]
No worries, I'm a penut, I wanted to fix up my mistake by not putting
enhancement in front, I'm new to posting and still trying to get the right
formatting/edicate to make life easier on others.
Sorry for any inconvenience.
