### ISSUE TITLE
Display image resolution and/or size in search results

### ISSUE THREAD

**Issue by Jdiesel87** [advplyr/audiobookshelf#83]
It would be nice to have some info when choosing cover images with multiple results.

**Comment by advplyr** [comment]
I'm working on a new way to search & match book data (you'll notice the "match" tab is gone now), so in the meantime I added a button on hover to view the original cover image.

![image](https://user-images.githubusercontent.com/67830747/136666057-7cdda096-f740-4272-a2aa-8e3fc3ca08fb.png)
