### ISSUE TITLE
[Feature Request] Add Bookmarking to eBooks

### ISSUE THREAD

**Issue by DJalup** [advplyr/audiobookshelf#831]
Can you add Bookmarking or progress tracking to the eBook feature. This is really the only thing it's missing. Thank you.

**Comment by captainnapalm** [comment]
Yes, hard to read a book when you constantly lose your progress. Excited to have this app as a one stop for audiobooks and ebooks.

**Comment by advplyr** [comment]
Added saving progress for epub ebooks in [v2.2.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.18)

The next release of the mobile apps will include this

**Comment by wieluk** [comment]
Is saving progress also possible for pdf files?
