### ISSUE TITLE
[Bug]: Match metadata automatically reverts seconds after saving.

### ISSUE THREAD

**Issue by silentArtifact** [advplyr/audiobookshelf#833]
### Describe the issue

This is an odd one. After using the "Match" functionality to select and save new metadata, the previous metadata will overwrite the new within 3-5 seconds. Re-matching and re-saving a second time will stick, but the first one rolls back almost immediately.

### Steps to reproduce the issue

1. Search for audiobook (so far seen with Audible, not tested on others).
2. Select audiobook selection
3. Click "Update"
4. Wait 3-5 seconds.

### Audiobookshelf version

v2.0.23

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you note the specific details that are getting reverted? Are there any that are not being reverted?
Are you storing a `.abs` file inside that library item folder and have enabled the server setting to store metadata with library items?

**Comment by silentArtifact** [comment]
I think the latter part might have been it! Removing the `.abs` file from one I was updating and then running the match worked this time. I'll try unchecking the "store metadata" option.

Unrelated, but I love the metadata embedding function you're testing! I've been dreaming of something like this for _ages_!
