### ISSUE TITLE
[Bug]: WebUI library config not accessable on mobile browser.

### ISSUE THREAD

**Issue by Presjar** [advplyr/audiobookshelf#839]
### Describe the issue

Chrome, Android (Mobile view) it is not possible to access the edit, &vellip; or &equiv; menu. Attempting to touch these menus results in the library moving position action.

Chrome, Android (Desktop site view) only &equiv;  menu is visible, however it is also unable to be selected.

Recording of issue:
https://user-images.githubusercontent.com/18156203/179215208-26ce869a-a0d4-4559-ba20-8bc4d4c7047b.mp4

### Steps to reproduce the issue

1. Access the WebUI as root user
2. Navigate to /config/libraries
3. Attempt to access any menu. Note library will move. Menu not selected.

### Audiobookshelf version

V2.0.24

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This is fixed in [v2.1.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.0)
