### ISSUE TITLE
Bug: Bulk Edit Results in "Page not found"

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf#84]
After doing a bulk edit on a couple different series, one doing tags and the other doing genre, I got the below.

![image](https://user-images.githubusercontent.com/4451365/136297357-6f939a1a-40cc-4090-b2e9-876f77b2cdeb.png)

**Comment by advplyr** [comment]
Just fixed this in [v1.4.1](https://github.com/advplyr/audiobookshelf/releases/tag/v1.4.1)
