### ISSUE TITLE
[Bug]: When adding new books, sometimes add as duplicates

### ISSUE THREAD

**Issue by jt196** [advplyr/audiobookshelf#843]
### Describe the issue

Copying over a file via Samba, I found 2 books referencing exactly the same files after they were added. 

Inspecting the files in the interface, the names are the same, but one of the file sizes is different. Of 3 files, the last one was 105MB. In the first book, the file shows as 5MB, in the second book it shows as 100MB. 

It seems like ABS scans the file that is being copied, takes a snapshot, turns that into a book. Then a bit further along, ABS finds the file having changed in size, assumes it's a new book, and turns all 3 files into a new book. 

In order to resolve this, I moved the files to a different folder, removed the books from the library, then moved them back. This has happened on one other occasion, so not very often, but enough for me to notice and put an issue here. 

### Steps to reproduce the issue

1. Copy larger files via samba (or any method that takes a minute or two), so that the scan is done while the files are copying. 

### Audiobookshelf version

2.0.24

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Are you using a NFS share for your audiobook library?

I'm not sure how this could have happened, I don't have a way to reproduce this.

**Comment by jt196** [comment]
This is happening on a NAS - copying with a Samba network file share.

**Comment by jt196** [comment]
[Samba NFS](https://wiki.samba.org/index.php/Server-Side_Copy). Looks like the copy operations are run server side in the Synology version (4.10.18 as of 10/21), but I'd wager that's something to do with it.

**Comment by advplyr** [comment]
I think this issue may be related to #906 which I fixed in v2.1.5

Let me know fi this is still happening
