### ISSUE TITLE
[Enhancement]: Add instead of overwrite in bulk editor

### ISSUE THREAD

**Issue by wazabees** [advplyr/audiobookshelf#848]
### Describe the feature/enhancement

Would it be possible to have an option to add, instead of replace for the bulk editor? For instance, if I select a few books to bulk/mass edit and enter a tag, all existing tags will be replaced with the one new tag.

**Comment by advplyr** [comment]
I'm not sure about this because I don't know what the UI would look like. I think the workaround for this shouldn't be too bad, batch editing the items that already have the same tag.

**Comment by hobesman** [comment]
I think the idea is for example with genre or tags, if you want to add a tag or genre without losing the existing info. So if I have 10 books with tags, and I want to add a tag to all of them without losing the tags that each already has, I can't use bulk.

**Comment by advplyr** [comment]
That was my understanding as well, I'm just not sure how the UI would look like for that so it is clear to the user

**Comment by wazabees** [comment]
Maybe an append button and an information overlay that if it's un-ticked, the data filled in the form will overwrite existing data?

I suck at mockups, but hey.
![Untitled](https://user-images.githubusercontent.com/14857141/181580037-d5e8a8ce-7e15-4e68-bf41-c9b7d5cb408e.jpg)

**Comment by advplyr** [comment]
The problem is you wouldn't be appending a subtitle or a publish year. It wouldn't make sense to go next to "Explicit" either.

**Comment by chyron8472** [comment]
a mark to Append/Overwrite should go next to, or in place of, the checkmark. Maybe a tickbox that if ticked to the left will overwrite, or ticked to the right will Append.

**Comment by hobesman** [comment]
I think tick to the left should be off/append (then if the text box is empty it appends nothing) and tick to the right is overwrite. That way the toggle could replace the check box altogether.

**Comment by gvarph** [comment]
Or maybe add a second div next to 'map details'. It could look something like this (Include only the fields that can contain multiple items)
![image](https://user-images.githubusercontent.com/17300137/207437235-e6c0f08c-a32f-49da-9626-06939ae6119e.png)

**Comment by hobesman** [comment]
Hmm. What if there's something for Author in both divs? How should it be handled? Seems redundant. But I think the multi-div idea could have merit. 

Another idea: Maybe one master toggle "Append/Replace" at the top, and certain fields drop away if set to Append.

**Comment by advplyr** [comment]
![append_details](https://user-images.githubusercontent.com/67830747/207457482-69f84a08-b8b6-4b4a-b992-55bf3db49216.gif)

**Comment by advplyr** [comment]
Added in [v2.2.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.9)
