### ISSUE TITLE
[Bug]: iOS app cannot connect to server

### ISSUE THREAD

**Issue by apearce-nov** [advplyr/audiobookshelf#849]
### Describe the issue

iOS app is not able to connect to server. It shows an error "Audiobookshelf server not connected". When I hit connect, it asks for my credentials again. When I enter my credentials, it says that config is already setup. I have confirmed that my server is accessible via web portal.

### Steps to reproduce the issue

1. Open iOS audiobookshelf. Error that the server is not connected.
2. Click connect
3. Enter credentials. Error that the config is not found.

### Audiobookshelf version

v2.1.0 docker; v0.9.51-beta ios

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This is a known bug will be fixed in the next release. Please delete the config and add it back in again.

**Comment by apearce-nov** [comment]
Resolved. Thank you!
