### ISSUE TITLE
[Enhancement]: Ability to edit series and option to add series to collection

### ISSUE THREAD

**Issue by araujojr82** [advplyr/audiobookshelf#851]
### Describe the feature/enhancement

First of all, thank you very much for the effort you put into this app. It is really amazing.

I would like to suggest 2 features that I couldn't find anywhere (I apologize if they are already implemented):

1) Ability to edit a Serie: Change the name of the series on the Series page, instead of having to go through each book to change it.

2) Option to Add the whole Serie to a Collection. Again, instead of having to add individual books one by one.

Thank you!

**Comment by advplyr** [comment]
For the second one you can select multiple books and bulk add to a collection.

For the first one I think we may make a series page similar to how we have a collection page. In that case we would have the series name editable.

**Comment by advplyr** [comment]
Series page was requested here #711
