### ISSUE TITLE
[Enhancement]:audiobboks -> series -> sort bij book nr

### ISSUE THREAD

**Issue by PoepieFloepie** [advplyr/audiobookshelf#856]
### Describe the feature/enhancement

if i have a collection audiobooks and they are sorted bij numbers ...lijk blabla is boek 1 and blablabla is book 2

now they are all over the place in series..

so is it possible to sort them bij book number...
or place a number under the bookself ,so that i can see what book number it is
you have this done in series ,then you see the collection name,but now i want this under every book in series collection
![Schermafbeelding](https://user-images.githubusercontent.com/46219717/180638537-22fee2a1-b048-4be3-a2d6-c58d54bd31f5.png)

**Comment by advplyr** [comment]
If I'm understanding what you are saying then all you need to do is press edit on the audiobook, then press edit on the series and add a series sequence.
When a book in a series has a sequence number set then it will show over top of the book and will be sorted by that sequence.

![image](https://user-images.githubusercontent.com/67830747/180646052-3f961139-2fa4-4700-9c0c-e2b9dfd14a4b.png)

![image](https://user-images.githubusercontent.com/67830747/180646062-6203adea-1100-414f-abdb-aedda90eafa9.png)
