### ISSUE TITLE
[Bug]: Long Library names cause text overflow on the library select button

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf#858]
### Describe the issue

I have a library with the name 'Graphic Audio & Full Cast' in order to keep those style of books separate from the normally read audiobooks, but it seems the long name causes a little UI issue with the library select. The button should resize to fit the text within the bounds of the box, or it should scale the text appropriately. 

![image](https://user-images.githubusercontent.com/6693120/181069277-e177a0f3-9a01-4b89-b470-972b3ead8495.png)

### Steps to reproduce the issue

1. Create a library with a long name.

### Audiobookshelf version

v2.1.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.1.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.1)
