### ISSUE TITLE
New library and share system 

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#859]
### Describe the feature/enhancement

I have many users, each with their own library.  Neither can use the other's library.  However, if someone now wants to use a book from another library, this is not possible.  So it would make sense if you could share a book, series or collection for another user or even globally for all users.  For the latter there would be something like a global page to which every user has access.

**Comment by advplyr** [comment]
This wouldn't make sense with how Ab is setup now. The way Plex is setup makes sense for this, but not Abs.
