### ISSUE TITLE
[Enhancement]: Section for Narrators just like authors

### ISSUE THREAD

**Issue by ThaBlazee** [advplyr/audiobookshelf#860]
### Describe the feature/enhancement

would be nice to have a separate section for Narrators just like Authors.

**Comment by lerndmina** [comment]
Agreed.

**Comment by wtanksleyjr** [comment]
Also would be nice to be able to see narrators in search results.

**Comment by advplyr** [comment]
The issue with narrators is they don't have images, or we don't have a way to fetch images. If we don't have images you think it should be use the same as authors when they don't have an image?

**Comment by lerndmina** [comment]
> If we don't have images you think it should be use the same as authors when they don't have an image?

I think that would work. Maybe a desaturated version of the authors profile image. Or some kind of overlay that makes it clear they are the narrator and not the author.

**Comment by toxic0berliner** [comment]
Would like this too regardless of picture

**Comment by SkippyTheMonkeyKeeper** [comment]
> The issue with narrators is they don't have images, or we don't have a way to fetch images. If we don't have images you think it should be use the same as authors when they don't have an image?

We could always fill the information manually if we really want to, but maybe it's an idea to make the Narrator's section optional.

**Comment by advplyr** [comment]
Added in [v2.2.20](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.20)

This is pretty basic for now
