### ISSUE TITLE
[Enhancement]: Allow weekly, fortnightly or monthly automatic backups

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#863]
### Describe the feature/enhancement

Not much happens in a span of a day to warrant a daily backup (just a little progress on reading generally). Would like to be able to configure backups to longer periods to accommodate more changes over the span of that period.

**Comment by advplyr** [comment]
I'm going to consider this a duplicate of #822
When the scheduler is implemented it will allow setting weekly etc.
