### ISSUE TITLE
[Bug]: Library stats' numbers are grossly incorrect

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#865]
### Describe the issue

![image](https://user-images.githubusercontent.com/42061703/181296537-920dbc90-1cdb-4df4-b2a7-948d564e40c4.png)

I don't know what's happening here, but as you can see some of the numbers are definitely wrong.

### Steps to reproduce the issue

1.  Can't tell, but this is the "Library Stats" view when you click on the gear icon/settings.

### Audiobookshelf version

2.1.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I didn't see this issue. #868 is a duplicate created after this one that will be the main thread.

This was an issue with the android app sending a unix timestamp as listening time that is fixed in v0.9.55-beta and the next server release will remove these invalid playback sessions on update.
