### ISSUE TITLE
[Bug]: Ignore prefixes does not work in series section

### ISSUE THREAD

**Issue by nealhead** [advplyr/audiobookshelf#866]
### Describe the issue

I have "Ignore prefixes when sorting" enabled and this works when browsing library but not when browsing series. Is this intended or a bug?

### Steps to reproduce the issue

1. enable "Ignore prefixes when sorting"
2. add a series with "the" or "a" at the start
3. when viewing series section, sorting will place all of the "the" prefixed series in with other Ts

### Audiobookshelf version

v2.1.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.1.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.1)

Also fixed for collapsed series names
