### ISSUE TITLE
[Enhancement]: Remain on the same tab when switching to the next or previous book in the Edit Metadata window

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#867]
### Describe the feature/enhancement

I'd like to remain on the same tab when switching to the next or previous book in the Edit window. 

For example if I'm editing the cover image of a book and then press the > button to go to the next book, I'd like to stay on the Cover tab.

Currently it reverts back to the main Details tab each time you switch books.

**Comment by advplyr** [comment]
Added in [v2.1.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.1)
