### ISSUE TITLE
[Bug]: Issue with stats

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf#868]
### Describe the issue

There seems to be an issue with stats...

### Steps to reproduce the issue

1. I just click in stats, and this is my view
![image](https://user-images.githubusercontent.com/101836977/181598650-dc87976a-b8e6-4f66-83d6-6cd099b34d90.png)

I'm fairly sure I didnt listen to 52 years of audiobooks on Sunday, I feel I would have remembered something like that.

Here is the offending entry in the log

![image](https://user-images.githubusercontent.com/101836977/181599240-27c50226-a585-4df9-9126-17e16fa2c6ba.png)

### Audiobookshelf version

2.1.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Do you know if that listening session was over android auto?
Or anything to help me reproduce this like how you stopped the playback for that media session, maybe you stopped using the notification.

**Comment by barelylit** [comment]
I'm afraid i stopped and started a few times on Sunday, i was doing some work in the garage and pausing when coming into the house etc. It wont have been android auto, but it could have been with app, notification or with bluetooth button on earphone as I opften do all three,

**Comment by advplyr** [comment]
I was able to reproduce it and pretty sure I fixed it in the next android release. I will also have to put in the next server release a check to remove the playback sessions that got messed up.

**Comment by advplyr** [comment]
Fixed in [v2.1.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.1)

Those playback sessions will be removed on server init after updating
