### ISSUE TITLE
[Enhancement]: Change default setting for "Ignore prefixes when sorting" setting

### ISSUE THREAD

**Issue by cassieesposito** [advplyr/audiobookshelf#869]
### Describe the feature/enhancement

I realize this is a matter of opinion, so obviously overrule and close if stronger feelings prevail.

I love the idea of this feature, and I think it's 100% on point to default to having "the" set as a prefix by default. But while I can understand why someone might want to include "a" as a prefix, I think it's weird, and should not be the default setting. So my first choice would be to remove "a" as a prefix.

But if we can't have that, I think it's extra weird to have "a" as a default prefix but not "an." So my next choice would be to add "an" to the list of defaults.

The third option is leave it alone, which is a choice I would find baffling. But since this can be set manually, this is obviously not a huge or urgent issue.

**Comment by advplyr** [comment]
Forgot to close this. It has been implemented for a while.
