### ISSUE TITLE
[Bug]: cosmetic bug

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#876]
### Describe the issue

if i upload books with "vol XX" and open the editor window > match > search > the series tag shows as "#X" instead of (my) "#XX" ... its possible to detect what sequence the folder have? So "Vol 1" can detect as series "#X" and "Vol 01" can detect as series "#XX" ... i cant use quick match, cause of all my files will moved with "#X" to other location instead of "#XX" and if u use the normal match, i need to deselect or edit the series sequence ...

### Steps to reproduce the issue

upload an folder with Vol XX instead of Vol X

### Audiobookshelf version

2.1.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
There was a request to remove the leading 0 https://github.com/advplyr/audiobookshelf/issues/562

I don't really understand the issue you are having with quick match. Quick match shouldn't have anything to do with the series volume number.

**Comment by skyzuma** [comment]
but with manual matching ... maybe this can be solved with an option in the setting ....

**Comment by advplyr** [comment]
I still don't know what you mean, manual matching? I'm trying to understand what the problem is the not having a leading 0.

**Comment by skyzuma** [comment]
like this

![image](https://user-images.githubusercontent.com/1676196/182041734-261808c5-e446-4016-9964-ba2b9ad2ca7a.png)

and it is ONLY a cosmetic bug like i sayd

**Comment by advplyr** [comment]
Did you update that so it shows as "Book 3" for the volume number? That doesn't seem right if the match result returned with that volume number.

The volume number returned from the match is exactly how it is stored in audible. I don't think modifying the results from audible will be a good idea. Some users may want it to update to match audible instead of the volume number they have with leading zeros.

**Comment by skyzuma** [comment]
> I don't think modifying the results from audible will be a good idea. Some users may want it to update to match audible instead of the volume number they have with leading zeros.

thats why i suggested with an option in the  settings and i think its the best options for all ... i know many ppl to use this like me :)

**Comment by advplyr** [comment]
This is not going to be implemented at this time, perhaps sometime in the distant future we add a setting for volume number format but this runs into issues when not dealing with numbers.
