### ISSUE TITLE
[Enhancement]: Run match when selecting match on book

### ISSUE THREAD

**Issue by jt196** [advplyr/audiobookshelf#882]
### Describe the feature/enhancement

If I select the Match option on a book, I arrive at the Match tab. I then press search to search for the item. Assuming in most cases, the book is labelled correctly, would it be better to run the search on opening the tab? Or at the very least have an option to run the search automatically on opening?

**Comment by advplyr** [comment]
Agreed, added for the next release

**Comment by advplyr** [comment]
Added in [v2.1.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.2)
