### ISSUE TITLE
[Enhancement] Image resolution on Cover tab, especially when matching

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#885]
It would be nice to see image resolution right on the match results page rather than having to load each image in a separate tab to compare. I propose putting the resolution right under each image but there might be better solutions.

Something like this screenshot:

![Screenshot_20220802-1243382](https://user-images.githubusercontent.com/29721765/182466864-5d47b030-0990-4861-aa00-0a5ada6ab28a.png)

I'd also put similar numbers under the "current" image, and under each local image thumbnail too.

**Comment by advplyr** [comment]
Added in [v2.1.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.2)
