### ISSUE TITLE
[Enhancement]: Duration and narrator in "Match" search results

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#886]
### Describe the feature/enhancement

Depending on what information is available from the provider, it would be nice to see the duration and possibly the narrator in the results to compare with the data we already have. So I can tell for example if an item in a list of results is a different recording by a different narrator, or is an abridged version, or there are multiple listings for the same recording, or what.

Here's a proposed mock-up.

![Screenshot 2022-08-02 135106](https://user-images.githubusercontent.com/29721765/182472727-837c0225-890c-4d0f-82ef-82cd1446fd39.png)

**Comment by advplyr** [comment]
Added in [v2.1.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.2)
