### ISSUE TITLE
[Enhancement]: When editing series set focus on inputs

### ISSUE THREAD

**Issue by wtanksleyjr** [advplyr/audiobookshelf#889]
### Describe the issue

When attempting to edit a series in a book, I expect to click the button and then type; but the resulting typing winds up in some other field.

Workaround: be paranoid, remember to always look for the blinking cursor before typing.

Proposed solution: when the Series box pops up, the keyboard focus should move to the Series box, either in the title (for new series) or in the index (for existing series).

### Steps to reproduce the issue

1. Go to Details tab in a book.
2. Click in Description so you can see your cursor.
3. Click the + under Series to add a series, or click the pencil icon on an existing series. Notice that the Series modal dialog pops up, and so the Description is now dimmed; but contrary to the implication of the dimming, the cursor is still in the Description and is blinking.
4. Then begin typing; the input goes into the Description field (I expected it to go into the Series field).

### Audiobookshelf version

v2.1.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Agree this is a nice feature. Updated for the next release.

**Comment by advplyr** [comment]
Added in [v2.1.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.2)
