### ISSUE TITLE
Huge file size of Audiobookshelf automatic backup file

### ISSUE THREAD

**Issue by scorpio862** [advplyr/audiobookshelf#89]
I tried new Backup feature yesterday and I setup AudioBookshelf server to create auto backups every day. 
When I woke up this morning I noticed that my Cache drive on Unraid is 100% full and something just used almost 500GB of space.

It was new automatic backup file of Audiobooshelf. It took 486GB of space and it would probably take more if there was more available on the disk.

![image](https://user-images.githubusercontent.com/50056988/136690579-cf824669-425d-4cdf-9b08-e86c69d20e1b.png)

**Comment by advplyr** [comment]
Wow, no clue how that is possible. Did you delete it yet? It is just a zip file, change the extension to `.zip` and open it up, I'm curious what is in there.

**Comment by scorpio862** [comment]
Yesterday, I created a backup manually and it was only 276MB. 
The size of my /config folder (without Backups) is at the moment 670MB.
I don't have anything else in the /config folder, only what AudioBookshelf server creates.

I didn't delete the file. After reneming to .zip file, when I try to open it I get the error message "Unexpected end of archive".
All my docker containers crashed when my Cache drive run out of space so I'm guessing that the archive was never finished building.

**Comment by advplyr** [comment]
Two folders get zipped, /config and /metadata/books

Maybe you pointed the /metadata and the /config to the same folder?

```js
var metadataBooksPath = Path.join(this.MetadataPath, 'books')
var zipResult = await this.zipBackup(this.ConfigPath, metadataBooksPath)
```

**Comment by scorpio862** [comment]
You are right. I have metadatata folder mounted inside of config folder

**Comment by advplyr** [comment]
I didn't think about that possibility. I will write something to check for this, but you should change your paths to be separate folders.

**Comment by advplyr** [comment]
I wonder if this is happening to others as well. It's not the default for me and it is not the default in the unraid template.
