### ISSUE TITLE
[Enhancement]: unlock editing series name to make it easier to fix up series

### ISSUE THREAD

**Issue by wtanksleyjr** [advplyr/audiobookshelf#890]
### Describe the feature/enhancement

I'd like to be able to edit the series name of a book from the Details tab of the book.

Right now, when I click the pencil button on a series in the Details tab of a book, the name is grayed out so I can only change the number. But I often WANT the number the same and only want to change the series (for example, Audible offers "Star Wars: The Thrawn Trilogy - Legends (abridged)" as a SERIES name, not even kidding). The only alternative right now is to delete the old series info and create a new one, leaving the series number a memorization problem. Also, I have a bunch of books in "The Dresden Files" and a bunch in "Dresden Files".

**Comment by advplyr** [comment]
This will require some UI that explains that updating that series name will iterate through all the books that have that series and update them. That is the reason it was disabled because I couldn't think of the best way to handle it.

**Comment by wtanksleyjr** [comment]
I don't want to do that, though. I wouldn't want or expect editing a book to change any other books; I'd suggest that when you edit a book's series in the book's details, just change that one book. You get exactly the effect I'd like when you run Match on a book and then edit its suggested series there (i.e. you can change the series name or the index).

On the other hand, when I created this issue I also scanned through related issues; several people (including myself) also want to be able to change a whole series at a time, for which the Series screen makes perfect sense. Everyone will expect all the books to change then, so there's no need for a warning or anything.

**Comment by advplyr** [comment]
That's even more confusing to me. I would expect if I edit that series name then it will update it for every book. If I want to add a completely different series then I should remove the series currently there and create a new one.

Every series has its own unique ID and is stored in the database. When editing a series I would expect it to edit the series, not create a new one.

This has me double down more on keeping that title disabled because it can be interpreted 2 different ways. For now editing a series name on the book detail modal won't be supported, but I do think we will support editing the series name on a separate series page or adding an edit button on the series covers.

**Comment by wtanksleyjr** [comment]
I see -- so although a series name LOOKS like it's part of the book's metadata, this app actually treats it as an object all of its own.

I agree very much that having tools like "change series name" available in the Series page will be wonderful. I still think I would rather be able to actually change the data in the book Details (without having to memorize the sequence number), but I understand why that's not as simple as it seemed at first.

For now, a workaround is to run a Match; the resulting screen allows me to edit ANY field, including series name. This becomes a PITA in some cases whether Audible thinks the series is some crazy mega-collection like "Audible Originals" or "Star Wars"... but oh well.

**Comment by advplyr** [comment]
It is difficult to remember a digit for the sequence when you create a new series? I don't really understand how adding a new series and removing the old one is problematic.

**Comment by wtanksleyjr** [comment]
Over the last few days adding a new series has messed me up too many times -- either I misspell a word, or forget to put in the word "The", or any tiny little divergence and I have to do the whole thing over again, with no way to correct a typo because (as mentioned) it's impossible to edit a series once it's been entered, you have to do the whole thing over again (and that's assuming I even notice it; I might not see it until I reload the author page).

Anyhow, if this is a final decision it's OK, this app is AWESOME and I'm not going to even get annoyed over something so little :) . I'm definitely more interested in the Series page mentioned in some other discussions, since of course that'll give me what I want AND allow me to fix a bunch of books at once.
