### ISSUE TITLE
[Enhancement] Add filter for Books with Open RSS

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#893]
### Discussed in https://github.com/advplyr/audiobookshelf/discussions/892

<div type='discussions-op-text'>

<sup>Originally posted by **Jumbs** August  4, 2022</sup>
I have not been able to find any way to show books that have open RSS, as I lose track which are open.

Adding that the the main library filter area would allow someone to take inventory and disable things without opening everything one at a time to check. </div>

**Comment by Jumbs** [comment]
Perfect thank you. 
I hope i am not the only person who gets a brain itch about unknown open feeds.

**Comment by advplyr** [comment]
Next release added filter for open RSS feeds and show icon on cover.

![image](https://user-images.githubusercontent.com/67830747/183249876-af06821e-f658-4d0a-a715-e84c4048acb1.png)

**Comment by advplyr** [comment]
Added in [v2.1.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.2)
