### ISSUE TITLE
[Bug]: [UI] Library stats overflows below the menu on Firefox

### ISSUE THREAD

**Issue by lerndmina** [advplyr/audiobookshelf#896]
### Describe the issue

When resising the browser window the "Library Stats" page overflows behind the menu bar on the left.

The library stats window should conform like the "Your Stats" page and resize correctly

https://user-images.githubusercontent.com/10632157/183095340-2fba4823-d6f4-485e-8884-9f3ed32815ca.mp4

_(PS: The issue doesn't cause a loss in functionality, just something inconsistant that I noticed.)_

### Steps to reproduce the issue

1. Visit audiobookshelf.URL/config/stats in Firefox
2. Change the horisontal size of the browser
3. observe the window overflowing behind the screen

### Audiobookshelf version

v2.1.1

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
Fixed in [v2.1.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.2)
