### ISSUE TITLE
[Bug] Title and Subtitle mis-alignment

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#898]
### Steps to reproduce

1. Open any book/item view that has a long title and subtitle
2. NA 
3. NA

![image](https://user-images.githubusercontent.com/42061703/179337304-181c1fe6-7ced-4805-bd4f-d20a078b0e73.png)

### Expected behaviour
- It would be nice to see the three lines of text this way:

[Title]
[Subtitle]
[Author]

Example (ignore the horizontal lines, wasn't my intention of having them there): 
<H1>Plays Well With Others
<H2>The Surprising Science Behind Why Everything You Know About Relationships Is (Mostly) Wrong
<H3>By Eric Barker </H3>

Instead of:
[Title]       [Subtitle]
[Author]

### Actual behaviour
- See alignment of the text in the image above

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: NA

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by raviwarrier** [comment]
oh, sorry, I should have mentioned that this is on the web-app / web-ui. Since I wasn't sure I put it under this repo instead of abs-app.

**Comment by advplyr** [comment]
Updated in [2.1.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.3)
