### ISSUE TITLE
[Enhancement]: display cover when matching a book

### ISSUE THREAD

**Issue by Benni-chan** [advplyr/audiobookshelf#899]
### Describe the feature/enhancement

On the detail screen after matching a book, it would be nice to see the cover and not only an url.
You can use the same ui as when searching only for a cover. Display the cover and resolution. Zoom the cover with a click.

**Comment by advplyr** [comment]
Added in [v2.1.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.3)
