### ISSUE TITLE
[Bug]: Matching books(audible), shows wrong format of time, minutes and seconds instead of hours and minutes.

### ISSUE THREAD

**Issue by BionicAlice** [advplyr/audiobookshelf#904]
### Describe the issue

Small issue, when matching a book (audible), the length/runtime of the book shows minutes and seconds and not hour and minutes. If a book is 10 hours 57 minutes it will show as 10m 57s

### Steps to reproduce the issue

1. match a book with audible

### Audiobookshelf version

v2.1.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [2.1.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.3)
