### ISSUE TITLE
[Enhancement]: Expanded support for commas in author name

### ISSUE THREAD

**Issue by wtanksleyjr** [advplyr/audiobookshelf#907]
### Describe the feature/enhancement

This is not going to be easy, I know names are just insanely hard. But perhaps this can be aspirational, hence an enhancement request rather than calling it a bug.

Authors like "L.E. Modesitt, Jr." and "Janet Bond Brill, PhD, RD, LDN" produce multiple authors regardless of how their metadata is imported.

In my library in particular all of these came from OPF files, which might make the problem easier by not requiring comma processing (because commas in OPF files are never an indication of multiple authors).

**Comment by advplyr** [comment]
I'm not sure the best way to handle that outside of OPF files, but for OPF files I updated it so that each author name listed is put in as-is and not ran through the name parser.
The OPF file parser was also only supporting a single author so I hopefully fixed that.

**Comment by advplyr** [comment]
Updated in [2.1.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.3)
