### ISSUE TITLE
[Enhancement]: Separate Playback Speed Setting Per Library

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf#911]
### Describe the feature/enhancement

Would it be possible to have separate playback speed settings (or remember separate playback speed settings) on a per library basis? 

I have a library for Audiobooks and a library for Podcasts, and I like to listen to my Audiobooks at a much faster speed than my podcasts (i.e. 1.7x vs 1.0x). Rather than just switching back and forth with playback speeds, is it possible to have the server (not sure if this is a server setting or app setting) remember playback speed based on the library, rather than a global setting. 

Thanks!

**Comment by advplyr** [comment]
Playback speed persists per user. This would get complicated when trying to decide whether to override a users playback speed for the libraries playback speed and would probably require an additional setting for that.
This seems like a rare use-case and would need additional settings and logic that isn't worth the effort at this time.

**Comment by feerlessleadr** [comment]
Fair enough, thanks for the consideration!

**Comment by ScuttleSE** [comment]
I would ask you to reconsider this one. My ABS is separated into Podcasts and Audiobooks, just like the OP, and having to fiddle with the speed-setting mulitple times per day is getting kind of annoying.

**Comment by ScuttleSE** [comment]
Take a look at the settings in Overcast f.ex. You have a global speed-setting, but you can then choose to have custom settings per podcast.

Something similar in ABS would be very nice. A default setting, then an optional setting per book/podcast

**Comment by feerlessleadr** [comment]
For others with this issue, here is how I tackled this on Android (don't think it's possible on iOS). I cloned the ABS apk using the app 'App Cloner'. I named the cloned app 'audiobookshelf-podcast', which I then installed on my phone next to the normal ABS app. 

On ABS server, I created a second user 'feerlessleadr-podcast', and then signed into the cloned app on my phone using that user. Now when I want to listen to podcasts, I upen up the cloned up, and audiobooks, the main app. Not quite as slick as having everything under 1 roof and 1 user, but it works very well.

**Comment by iconoclasthero** [comment]
I too would like to request that this feature be reconsidered and I will add a usecase beyond podcasts, meditation:
I went to my meditation library last night and it played at 2.x speed off the bat.  Since I don't meditate as much as I should [read: ever], I've not run into this much, but it might become more of an issue.  

The playback setting would need to be both per user and per library.  (It would be possible to add a user config option to enable different playback speeds by library too.)  I haven't looked at the data structure lately, but if there's a way to save a per library volume in each user's setup, that would be cool.

**Comment by iconoclasthero** [comment]
> For others with this issue, here is how I tackled this on Android (don't think it's possible on iOS). I cloned the ABS apk using the app 'App Cloner'. I named the cloned app 'audiobookshelf-podcast', which I then installed on my phone next to the normal ABS app.
> 
> On ABS server, I created a second user 'feerlessleadr-podcast', and then signed into the cloned app on my phone using that user. Now when I want to listen to podcasts, I upen up the cloned up, and audiobooks, the main app. Not quite as slick as having everything under 1 roof and 1 user, but it works very well.

Huh, does this still work?
Can you change the icon?  
I was primarily interested in this when I was thinking I was going to meditate...and I could've made a meditation account and apk clone, etc...

**Comment by feerlessleadr** [comment]
> > For others with this issue, here is how I tackled this on Android (don't think it's possible on iOS). I cloned the ABS apk using the app 'App Cloner'. I named the cloned app 'audiobookshelf-podcast', which I then installed on my phone next to the normal ABS app.
> > On ABS server, I created a second user 'feerlessleadr-podcast', and then signed into the cloned app on my phone using that user. Now when I want to listen to podcasts, I upen up the cloned up, and audiobooks, the main app. Not quite as slick as having everything under 1 roof and 1 user, but it works very well.
> 
> Huh, does this still work? Can you change the icon? I was primarily interested in this when I was thinking I was going to meditate...and I could've made a meditation account and apk clone, etc...

Yep, still works without issue for me. The app cloner app uses the same icon, but it adds a little cloner badge to the icon so I can tell them apart. I'm sure I could pay money to get more features, but the simple cloning works fine for me.
