### ISSUE TITLE
[Enhancement]: Podcast metadata from podcastindex.org

### ISSUE THREAD

**Issue by rallyJonWest** [advplyr/audiobookshelf#914]
### Describe the feature/enhancement

Right now the only source available for podcast metadata is iTunes.  I would like to see the podcastindex.org as a source for podcast metadata.  This way we take back power from Apple and use decentralized source for podcasts.

**Comment by advplyr** [comment]
Completely agree, this is a duplicate of #677

I want to do this but it requires a bit more than other providers because we will need users to provide their own API key. Unless this became public recently that I don't know about.

**Comment by Majester** [comment]
A user can get an API key at https://api.podcastindex.org/signup
