### ISSUE TITLE
[Enhancement] Removing items from home page shelves

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#919]
### Is your feature request related to a problem? Please describe.
I currently have four books in the "Continue in Series" shelf that I don't want to continue. The first books were terrible and I don't intend to read the rest. The problem is that marking the book as "read/listened to" only cues up the next book as shown by the "Kalki" book in the image below (book advplyr/audiobookshelf-app#2 was marked as finished).

![image](https://user-images.githubusercontent.com/42061703/185741949-58a6de92-62e6-473f-97f3-a371ac6b55d4.png)

It would be nice to have an option in the context menu to ignore the entire series (preferably without marking it as finished).
![image](https://user-images.githubusercontent.com/42061703/185741983-fadde6da-e9a8-4123-b63b-ab449b80700b.png)

**Comment by advplyr** [comment]
This feature will be for removing items from the continue listening shelf also.
For the continue series shelf I think we will need to add an option in the dropdown for removing the entire series from this shelf.

**Comment by AngusNB** [comment]
Thanks for looking at this feature. I am looking forward to it.

It makes sense to me that removing my Listening Session info, for a book, would have removed the books from Continue Listening. That isn't the case.

Saved Media Progress under each User would be another place that I would have expected to find a way to remove the book from Continue Listening.

**Comment by advplyr** [comment]
Added in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)

@AngusNB Listening session and media progress are different entities. The continue listening shelf uses your media progress.
