### ISSUE TITLE
[Enhancement]: Podcasts support iTunes tags for Season and Type

### ISSUE THREAD

**Issue by kormoc** [advplyr/audiobookshelf#922]
### Describe the feature/enhancement

Podcasts appear to only download new episodes, and doesn't seem to support seasons and `types` like apple's podcast app does.

the `itunes:type` tag inside the `channel` node can contain two different values

```
Episodic (default). Specify episodic when episodes are intended to be consumed without any specific order. Apple Podcasts will present newest episodes first and display the publish date (required) of each episode. If organized into [seasons](https://help.apple.com/itc/podcasts_connect/#/itc77382b700), the newest season will be presented first - otherwise, episodes will be grouped by year published, newest first.
For new subscribers, Apple Podcasts adds the newest, most recent episode in their Library.

Serial. Specify serial when episodes are intended to be consumed in sequential order. Apple Podcasts will present the oldest episodes first and display the episode numbers (required) of each episode. If organized into seasons, the newest season will be presented first and <itunes:episode> numbers must be given for each episode.
For new subscribers, Apple Podcasts adds the first episode to their Library, or the entire current season if using seasons.
```

It appears that ABS only supports an `Episodic` view, however only partially. It doesn't seem to download from the start of the current season.

It would be awesome to expand this support to download correctly based on the type tag and to support seasons correctly.

Thank you

Itunes Documentation: https://help.apple.com/itc/podcasts_connect/#/itcb54353390

**Comment by advplyr** [comment]
I'm not sure what you mean download from the start of the current season. How would this work? What would it look like in the web?
