### ISSUE TITLE
[Bug]: 'invalid cover' errors (cover art does not load) after updating 2.12 -> 2.14

### ISSUE THREAD

**Issue by danieljclark** [advplyr/audiobookshelf#924]
### Describe the issue

"Invalid cover" errors for audiobook covers pulled from Audible and iTunes matched metadata after updating from 2.12 to 2.14.

Have had to manually re-match the metadata to restore the covers.

![image](https://user-images.githubusercontent.com/103375932/185797105-46752107-d1bc-4c48-9f7e-791f459e8d0b.png)
![image](https://user-images.githubusercontent.com/103375932/185797143-f4d73134-4ee2-4a37-b210-13870ef8f45a.png)

Covers manually added as jpg were not affected and loaded normally.

### Steps to reproduce the issue

1. Update docker by following documentation for updating a docker compose installation (v2.9).
2. Album covers missing.

### Audiobookshelf version

v2.14

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
At first thought this seems like an issue with your docket setup. The `/metadata` folder that stores those covers must have been removed or the permissions changed or you changed the location of that folder.
