### ISSUE TITLE
[Enhancement]: Docker TimeZone parameter

### ISSUE THREAD

**Issue by MikePrime21** [advplyr/audiobookshelf#925]
### Describe the feature/enhancement

Now that I can schedule library scans, it helps if the docker container is running on my timezone.  Some docker containers allow me to pass in a timezone environment variable.  I don't know if there is any other way to modify the timezone besides that, but this would help docker noobs like myself greatly.

**Comment by advplyr** [comment]
The dockerfile uses tzdata which means you can pass in an environment variable `TZ` to set the time zone for your container.

There are some examples here: https://www.howtogeek.com/devops/how-to-handle-timezones-in-docker-containers
