### ISSUE TITLE
[Bug]: Crash when downloading an episode which contains an emoji

### ISSUE THREAD

**Issue by scaevolax** [advplyr/audiobookshelf#926]
### Describe the issue

The application crashs when downloading an episode which contains an emoji
The name of the episode is "[EXTRAIT] Épisode Retour #16 : BHL - Le poisson d'avril 🐟"

2022-08-22 08:48:40

INFO

[PodcastManager] checkAndDownloadNewEpisodes for "Le Précepteur" - Last episode check: Tue Feb 22 2022 09:40:00 GMT+0000 (Coordinated Universal Time)

2022-08-22 08:48:40

DEBUG

[PodcastManager] getPodcastFeed for "https://feeds.audiomeans.fr/feed/aced395e-6351-498a-9397-144bb12e80d6.xml"

2022-08-22 08:48:40

DEBUG

[PodcastManager] getPodcastFeed for "https://feeds.audiomeans.fr/feed/aced395e-6351-498a-9397-144bb12e80d6.xml" success - parsing xml

2022-08-22 08:49:07

DEBUG

[LogManager] Daily log file already exists - set in Logger

2022-08-22 08:49:07

DEBUG

[DailyLog] 2022-08-22: Loaded 103 Logs

2022-08-22 08:49:06

INFO

=== Starting Server ===

2022-08-22 08:49:06

INFO

[Server] Init v2.1.4

### Steps to reproduce the issue

1. Download the episode

### Audiobookshelf version

2.1.4

### How are you running audiobookshelf?

Docker

**Comment by barrycarey** [comment]
I tried to replicate this and it's downloading successfully. 

Looks like there's a few episodes with emojis in the title.  Can you download the others and see if you get the same issue?

**Comment by advplyr** [comment]
I also tested this and had no problems with emojis.

![image](https://user-images.githubusercontent.com/67830747/187794854-cc3d2e11-cfdb-4479-9957-0fb93e5a7e37.png)

I don't see any error log in the log you shared indicating it was the emoji. Do you have any more data you can provide?

**Comment by scaevolax** [comment]
I tried to download the other episode but the issue is still there
It's not so important, i will check theses episodes an other way, thanks guys for your help and this excellent tool !
