### ISSUE TITLE
[Enhancement]: Mass Chapter Timestamp Editor

### ISSUE THREAD

**Issue by SkippyTheMonkeyKeeper** [advplyr/audiobookshelf#927]
### Describe the feature/enhancement

This request can be seen as an addition to: https://github.com/advplyr/audiobookshelf/issues/657

The issue I am facing is that all Chapter timestamps are sometimes a few or more seconds of. 

This issue could be solved by adding an input field where you can insert a value as (-)hh:mn:ss.mss click a button and all the timestamps of the chapters will be delayed.

**Comment by advplyr** [comment]
Just to clarify, this request is for the ability to shift all chapter times forward/backward. Shifting them forward would be a positive value

**Comment by SkippyTheMonkeyKeeper** [comment]
Yes, exactly that.

**Comment by advplyr** [comment]
Added in [v2.2.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.1)
