### ISSUE TITLE
Bug: Root user password can't be changed in WebUI

### ISSUE THREAD

**Issue by Sleuth56** [advplyr/audiobookshelf#93]
When setting up a new instance for the first time. The root user's password is set to none.
The WebUI won't allow you to set a new password because it requires a previous password and won't take none as an option.

I see three possible fixes. 
1. On first run generate a password and print that to the console.
2. Allow password resets with none in the current password field.
3. Require a password for the root user the first time the WebUI gets loaded.

## The Work around
Create a new user account with a password.
List the contents of `config/users/data/` open the new `.json` file. The root user is `data.0.json` so we want the other one. copy the pash key and past it into the root user's file. 
Restart audiobookshelf.
Now refresh the web interface and change the password using the password from the other user account as the current password.

**Comment by wtanksleyjr** [comment]
Can you double-check this? The current behavior as of v1.6.57 seems to be that there's no ability to change anything about the root user except its name -- it has no password and cannot be given one, has no access to any collections and cannot be given any; but it can change anything about any other user.

This seems horrid. Surely it's not actually impossible to lock down root, just like I'd be able to delete or modify any other user account when accessing the system as root?

Or am I missing something?

**Comment by wtanksleyjr** [comment]
OK, I'm missing something - EVERY user, including root, can change their own password by clicking on their own user token in the top right -- it's just that as a new user I didn't know how to do that, but I did know how to click on "users" and see myself uneditable and then realize I can edit other users. So now I know how to change root's password.
