### ISSUE TITLE
[Enhancement]: manual book mapping/split

### ISSUE THREAD

**Issue by toxic0berliner** [advplyr/audiobookshelf#930]
### Describe the feature/enhancement

When a book has incorrectly been matched allow the user to delete the book and then allow the user to manually select a folder from the library and say "this is a book to match" give match results and let the user select the right one. 
Even allô to select a folder and say "this is the xxx series containing the 5 books of the series".

Maybe I missed how it should work, but I have trouble getting my library recognized.
I have the complete works (audiobooks) of Orson Scott card, the format is:
SCOTT CARD Orson/xx - Serie Saga/yy - Book - ISBN zzz/file-n.mp4
Like this: SCOTT CARD Orson/01 - Ender Saga/03 - Xenocide - SCOTT CARD Orson - ISBN 9781593974794/Xenocide 001.mp3

But it failed to recognize multiple books and put a metadata file in the first folder that actually contains no book at all only folders for each saga, and it added all the mp3/MP4 files to it is is 1100 hours long...

If someone has an idea to get if fixed I'm all ears, else I think something to manually import part of your library would be welcome.

**Comment by advplyr** [comment]
That folder structure is fine. My guess is that you have an audio file or more likely an ebook file (pdf, epub, azw3, etc) inside one of those sub-folders.
The scanner is going to treat the first folder that has an ebook file or an audio file as the library item, then all subfolders within that will be the same library item.

The manual mapping idea is likely far too complex. In that case it would be better to upload through the Abs upload form.
I will close this as will not implement, but let me know if you still have issues with your folder structure because that should be working.

**Comment by toxic0berliner** [comment]
It's currently rescanning but for sure I had a bibliography pdf in the root folder that I just moved, you found that one out so right that I trust it'll solve the issue. I get that it's a complex one to implement, but I feel it's still a bit sad to simply close it as won't do. 
I'm really finding this software useful, finally a self hosted solution that keeps my progress across devices! Amazing!
But I was still thinking it's of value to be able to manually manage the library. For the requirements or the workflow, simply compu what arr is doing for sonarr or radarr. 
Even with manual import I think not having clear visibility on folder structure, keywords (year of publishing, repeat the author or saga...) or the choice of separators and such is a miss...

**Comment by toxic0berliner** [comment]
Oh and yes it's now correctly finding the 95 books I have from Orson Scott Card ;) Didn't get rid of the fake old book only flagged it as missed, will forever full rescan should fix 😀

**Comment by advplyr** [comment]
I plan on adding some form of file/folder view and manager so it will be easier to see how the scanner mapped everything and make adjustments. Currently #450 is the request that mentions this although the details haven't been worked out.

**Comment by toxic0berliner** [comment]
Gotcha! So better things are planned, good to hear! Thanks again for the very nice software!👍

**Comment by toxic0berliner** [comment]
and the very quick and effective help !!!
