### ISSUE TITLE
[Bug]: [Podcasts][Find Episodes] Downloaded Episodes Remain Selected Post-Download, Results In Unnecessary Extra Downloads

### ISSUE THREAD

**Issue by SuburbanVampire** [advplyr/audiobookshelf#931]
### Describe the issue

This is a bug in the Find Episodes dialog that comes up when you click the Find Episodes button from within any podcast in the library.  It looks like the logic for when finishing the batch download isn't clearing out everything at the end like it needs to. Also there's no check for an existing file before a download is done?

### Steps to reproduce the issue

1. open a podcast where you have episodes left to download
2. open Find Episodes
3. Click the checkbox on 1 or more episodes and then click "Download # Episode(s)" button
4. open Find Episodes again
5. the "Download # Episode(s)" button is now stuck with the count of all currently downloaded episodes. If clicked, all episodes will be re-downloaded again

To escape this condition you must refresh the page.

### Audiobookshelf version

2.1.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.1.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.5)
