### ISSUE TITLE
[Bug]: Incorrect File Size Being Displayed

### ISSUE THREAD

**Issue by ericb0x** [advplyr/audiobookshelf#933]
### Describe the issue

When adding a new file (m4b, m4a, mp3) to abs, the file size is often incorrectly displayed. Seen here: https://postimg.cc/gallery/7GMskfx

The file size is always reported as smaller than the actual file size, never larger. This is not a huge issue but I often use file size to determine the quality and or version of the file I'm looking at. This issue occurs in the browser and mobile app (iOS). 

### Steps to reproduce the issue

1. Add new file to audiobook directory. 
2. 'Scan' library. 

### Audiobookshelf version

v2.1.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not seeing this issue. Are you able to reproduce this when adding a new library item?
Is this happening with items you scanned in for the first time or only items you are updating?
