### ISSUE TITLE
[Bug]: New podcast episodes autodownload, but the RSS feed is not automatically updated

### ISSUE THREAD

**Issue by ajm1014** [advplyr/audiobookshelf#939]
### Describe the issue

New podcast episodes are downloading as expected and displaying correctly in audiobookshelf, but the RSS feeds for each show are not being updated to include those new episodes. I was expecting the RSS feed to also refresh when the new episode was added to audiobookshelf so the new episode would be picked up by my other podcast apps.

### Steps to reproduce the issue

1. Add a show to audiobookshelf
2. Set up an RSS feed for that show
3. Download a new episode for the show (I used the 'Find Episodes' button)
4. Check the RSS feed for the show to confirm the episode is not present

### Audiobookshelf version

v2.1.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I'm not sure what you mean. Do you mean the episode list is not showing that you downloaded that episode?

**Comment by ajm1014** [comment]
The episode list shows it as downloaded and I can see it/play it within the web page (see episode 78 in the screenshot below). The issue I'm running into is that it doesn't seem to be getting added into the RSS feed (I copied the RSS page into this text file: [rss.txt](https://github.com/advplyr/audiobookshelf/files/9436362/rss.txt)).

I assumed the RSS page would also get updated with the information for the new episode so my podcast app (currently using Overcast) that is configured to pull episodes from that RSS feed would be able to see and pull new episodes.


<img width="1146" alt="Self-Hosted_Screenshot" src="https://user-images.githubusercontent.com/84141101/186989049-58a6af96-ad1c-4e99-a1ae-6bde14f12beb.png">

**Comment by advplyr** [comment]
Oh okay got it. It looks like I forgot to handle updating the feed.

**Comment by advplyr** [comment]
Fixed in [v2.1.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.5)

**Comment by ajm1014** [comment]
Thank you, I confirmed it's working as expected!
