### ISSUE TITLE
Enhancement: Add "Last Seen" (or similar) to user details section of config/settings page

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#94]
Personally, I get a lot of joy out of knowing that others are happily using things that I host on my servers.

Could we add something like "Last Seen" here with a date:

![image](https://user-images.githubusercontent.com/25695143/136902226-39ce8a85-93d6-4afb-b640-886ef02f6c2d.png)

If that gets added, maybe we could include a line that mentions something like "Last Seen Reading:" and then include the name of the last file they interacted with.

What do you think?

**Comment by Jdiesel87** [comment]
This is a nice feature to have. I personally would use it when doing server maintenance as to not disrupt any users that are currently listening.

**Comment by advplyr** [comment]
Discussion on the stats page is here #167
