### ISSUE TITLE
[Enhancement]: Hide "played" podcasts and audiobook chapters

### ISSUE THREAD

**Issue by Diviance** [advplyr/audiobookshelf#940]
### Describe the feature/enhancement

The UI (for both web and mobile) should have an option to not display audiobook files and podcast episodes you have already listened to all the way through and are "finished".  

Very useful for podcasts which have a LOT of episodes so you can always unhide them to listen again later and don't have to worry about downloading them again.

**Comment by Kudjo-Grand** [comment]
This is a Great idea! Just like your other suggestion. I hope they make their way in to the codebase.

**Comment by advplyr** [comment]
Podcast episode filter was added and by default finished episodes are hidden. Hiding audiobook chapters won't be supported at this time.
