### ISSUE TITLE
[Enhancement]: Podcast episode batch "mark as finished".

### ISSUE THREAD

**Issue by Diviance** [advplyr/audiobookshelf#941]
### Describe the feature/enhancement

The new ability to batch delete files in podcasts is excellent.  It would be very useful to be able to use the same "batch" checkboxes to mark episodes as watched if something happens and you need to re-add a podcast (or are coming from a podcast app where you already listened to a bunch of episodes).

**Comment by advplyr** [comment]
Added in [v2.1.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.5)
