### ISSUE TITLE
Some more details in the collection view (web app only)

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#943]
### Is your feature request related to a problem? Please describe.
![image](https://user-images.githubusercontent.com/42061703/179337111-55fc0493-21b5-448e-9524-c967afe30e41.png)
Just like the mobile app, it would be nice if the web app also showed basic details like author name and duration.

### Describe the solution you'd like
NA

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by advplyr** [comment]
Updated in [v2.2.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.2)
