### ISSUE TITLE
[Bug]: when editing chapters player keeps playing if you navigate away from the editor

### ISSUE THREAD

**Issue by dacmcbibs** [advplyr/audiobookshelf#945]
### Describe the issue

When using the chapter editor, if you start to play a chapter to check your work and then navigate away from the editor without pausing, the stream continues to play with no way to stop it since it doesn't spawn any player controls.  Navigating back to the editor doesn't give you the ability to pause the existing stream, it only lets you start additional streams.

### Steps to reproduce the issue

1.  edit book
2.  choose chapters tab
3. click edit chapters
4. press the play button next to any defined  chapter
5. navigate to the home screen using the home icon on the left

### Audiobookshelf version

v2.1.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.1.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.5)
