### ISSUE TITLE
[Bug]: Horizontal Scrollbar appearing in Firefox (or browsers with wider scrollbar widths)

### ISSUE THREAD

**Issue by chyron8472** [advplyr/audiobookshelf#950]
### Describe the issue

I noticed that there is a horizontal scrollbar on the Home tab while using Firefox:

![image](https://user-images.githubusercontent.com/12549803/187282741-b3d58066-7ddf-4c0b-a18d-96ae31f4bcee.png).

If I install a Custom Scrollbar extension and set the width to Narrow, the horizontal scrollbar goes away:

![image](https://user-images.githubusercontent.com/12549803/187283183-4053fb90-db11-440f-a985-091259278f11.png)

### Steps to reproduce the issue

Access ABS' Home tab while using Firefox as the browser on a PC.

### Audiobookshelf version

v2.1.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Unfortunately Firefox only allows for the scrollbar to be "auto" or "thin" ([scrollbar-width](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width)), but when I tested using "thin" it worked great on the latest Firefox.

That should fix this but I'm not sure why your rows have scrollbars, they didn't for me. Are you using an older version of Firefox ?

**Comment by chyron8472** [comment]
Firefox v104.0

The Custom Scrollbars extension I installed is adding scrollbars to the rows. For some reason. I only installed it after noticing the horizontal scrollbar at the bottom of the home screen.

**Comment by advplyr** [comment]
Oh good that explains it then. Will be fixed in the next release
