### ISSUE TITLE
[Bug]: Guest/User account types have ability to view/edit/delete collections for everyone

### ISSUE THREAD

**Issue by endangered-maritime-walrus** [advplyr/audiobookshelf#951]
### Describe the issue

Both Guests and Users have the ability to view, but more importantly, edit/delete items and/or entire collections.

Ideally, there would be a way to make a collection completely private.

### Steps to reproduce the issue

1. Create Collection in Admin account
2. Create User/Guest
3. Log in as User/Guest
4. Go to collections
5. Reorder, delete book from collections, or delete entire collection

### Audiobookshelf version

v2.1.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I completely missed this somehow. Originally collections were going to be per-user then we decided to add "playlists" in the future that will be per-user.
In this case I think collections should only be editable/deleted by admin users, but everyone on the server will be able to view collections.
Playlists will essentially be collections but private per-user.

**Comment by advplyr** [comment]
Fixed in [v2.1.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.5)
