### ISSUE TITLE
[Enhancement]: RE #888 Invert order or add option to invert of podcast dates

### ISSUE THREAD

**Issue by Jumbs** [advplyr/audiobookshelf#952]
### Describe the feature/enhancement

In #888 a small time drift was added that allowed podcast apps to sort the items.
The drift system used is inverse of how both apple and android podcasts expect (Apple and Google Podcast app tested). It can be resorted, but it defaults to the opposite direction of the book.

**Requesting the drift in the opposite direction, or an option when creating the RSS feed.**

**Comment by advplyr** [comment]
Updated in [v2.1.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.5)
