### ISSUE TITLE
[Bug]: Library filter Series: No Series isn't working

### ISSUE THREAD

**Issue by SkippyTheMonkeyKeeper** [advplyr/audiobookshelf#956]
### Describe the issue

When viewing my library and filtering on Series: No Series, no books show up while there should be a over a dozen of them. 

Btw the filter Missing: Series is working.

### Steps to reproduce the issue

1. Go to Library
2. Click Filter > Series > No Series

### Audiobookshelf version

v2.1.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.1.5](https://github.com/advplyr/audiobookshelf/releases/tag/v2.1.5)
