### ISSUE TITLE
Series not sorted correctly after scan

### ISSUE THREAD

**Issue by Guardian1987** [advplyr/audiobookshelf#965]
I have imported my audiobook library and almost none of the books are sorted correctly. E.g. 
![AA776034-DFFE-4F5A-92EB-7B2107FF1611](https://user-images.githubusercontent.com/53516713/188287539-babf949e-8e9e-4b08-8e7f-22fb7c47e596.jpeg)

I’ve tried audible, iTunes, Google books, the order always remains wrong. Anyone else with this issue?

**Comment by advplyr** [comment]
In the website click edit on a book and then hover over the series and press edit again. There needs to be a sequence set for each of your books.
There will most likely be no sequence so go to the Match tab and see if it matches correctly and shows a series volume number.

**Comment by advplyr** [comment]
Unlike other media servers you may have used, audiobookshelf does not look up and tag your books automatically. If your folder structure and audio file ID3 tags do not match what audiobookshelf is looking for then you will need to use the Match features (Match tab or quick match) to fill in the missing details.

Feel free to join the discord if you have more questions about how this works. I don't believe there is an issue here though.

**Comment by Guardian1987** [comment]
Thanks for the super quick feedback! The books matched fine, but as you suspected the sequence wasn't filled for them.
But even though a series is recognized in the match, the sequence seems to never be filled.
Here is an example where I see the series name and number, but sequence wasn't filled:

![image](https://user-images.githubusercontent.com/53516713/188288009-fc69e4e0-54d3-4b7c-ac1f-570f403b3a65.png)

Of course I can fix it manually and that is a good solution. But it seems like the info is there and "just" needs to be filled.

**Comment by advplyr** [comment]
When you say the books matched fine you are saying you went into the Match tab and matched it that way? Or you just scanned in the media?

In the Match tab you can see if the volume number is getting pulled in.

**Comment by Guardian1987** [comment]
Sorry, seems I'm an idiot. I mistook the ID3 tags imported as a successful match. When I manually match the books it does work and the sequence is filled.

I've sorted all my audiobooks with ID3 tags though and I would have thought the sequence should be taken from this automatically. This doesn't seem to be the case though. Another example given here:

<img width="881" alt="Bildschirmfoto 2022-09-04 um 21 16 57" src="https://user-images.githubusercontent.com/53516713/188329930-eeb3cfec-d079-4d4a-ac3f-05a23f32eded.png">
