### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by booleansmith** [advplyr/audiobookshelf#969]
## A more intuitive way to assign sequence order to a book series 

I finally realized I could assign sequence order to a book in a series by hovering over the series assignment and selecting the "edit" icon. 

It would be more intuitive, and quicker to assign book sequence if the sequence field was in the main edit menu, next to the series field (maybe taking up 20% of the line?)

something like this?
![example](https://user-images.githubusercontent.com/32348565/188505593-6ade0123-bf77-458a-8daa-fd3f272740b4.jpg)

**Comment by advplyr** [comment]
Every series can have its own sequence so one sequence input is not going to do it.

**Comment by booleansmith** [comment]
Yeah that's true I didn't consider that. Maybe a way to organize the series within the series page? That solution sounds a lot more involved then an additional field entry though.

**Comment by advplyr** [comment]
I think that is a good idea. There is another issue open for creating a separate page for series and I added a note there for your request #711

**Comment by booleansmith** [comment]
Sounds great! Thanks again for making this project truly awesome!
