### ISSUE TITLE
BUG: There seems to be a disconnect in how the locally stored cover images get their path

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#97]
Let me start by saying I **_LOVE_** that you have allowed us to store the covers locally. (No more dependence on external links!) So, thank you for that!

Here's what happened.
I moved some books around and the locally stored cover.jpg got lost and I can't select it anymore.

![image](https://user-images.githubusercontent.com/25695143/136923971-b9ba56e8-cbf9-4834-b550-539960b9407c.png)

Logs reveal that it seems to be looking in old location... 

![image](https://user-images.githubusercontent.com/25695143/136923994-a93ee67d-dc09-45c5-95de-ded191fe9eaf.png)

...even though the book itself is recognized to be in a different location.
![image](https://user-images.githubusercontent.com/25695143/136924006-2f936ce6-a89f-4962-ba70-f40397cd91e0.png)

What do you think is going on here? Anything you'd like me to try?

**Comment by advplyr** [comment]
I think this may have been the problem with the path not updating correctly that I fixed in the last release.
Let me know if this happens again and this can be re-opened.
