### ISSUE TITLE
[Enhancement]: Add a setting to hide ebook-only folders

### ISSUE THREAD

**Issue by dessalines** [advplyr/audiobookshelf#970]
### Describe the feature/enhancement

I'm only using this as an audiobook reader, but I have hundreds of folders showing up as books, and when I click on them, it shows a book with an ID, but not an audiobook.

It'd be great to have a setting that could hide these ebook folders, so they don't clutter up the library.

**Comment by advplyr** [comment]
In [v2.2.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.23) a feature was added for "Audiobooks only" library setting.

I believe this will accomplish what you want. After setting that and scanning those ebook only library items will show as missing so remove them from the library in the ui after that.

See guide https://www.audiobookshelf.org/guides/ebooks
