### ISSUE TITLE
[Bug]: missing scrollbars on Add Podcast, cannot reach button to submit

### ISSUE THREAD

**Issue by wtanksleyjr** [advplyr/audiobookshelf#975]
### Describe the issue

The modal dialog when you Search for and find a podcast on a PC browser is normally too big to fit in a window, at least for everything except my biggest monitor, and lacks scrollbars, and cannot be mouse-scrolled. The only way to subscribe is to `tab` through the entries until the dialog scrolls on its own, or according to #494 by shrinking the text size to reach the button.

Suggest adding a scrollbar? Or being a bit more responsive to the actual display size?

The fix in the above-mentioned issue seems to have worked for it, but doesn't seem to be a general fix.

I also checked on a mobile browser, and the UI elements seem to be rearranged to all fit on screen, so you clearly have some responsive-design code in there.

### Steps to reproduce the issue

1. Begin on a laptop PC or some other not-absolutely-huge screen that's not a mobile browser.
2. Search for a podcast. Select it so that the subscription modal pops up.
3. Confirm that if you cannot see the green button, it is not possible to scroll the dialogue to see it -- you have to `tab` until the dialogue scrolls.

### Audiobookshelf version

2.1.5

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)
