### ISSUE TITLE
[Bug]: Match tab doesn't show existing genres & tags data & description

### ISSUE THREAD

**Issue by Smoukus** [advplyr/audiobookshelf#976]
### Describe the issue

Match tab doesn't recognize the metadata section of genres and tags even if they are filled out prior to matching.
An example:
This is how my Details tab looks like prior to trying to Match:
![image](https://user-images.githubusercontent.com/48409293/189500766-9218dd8a-90b2-4e72-9c08-55920244c43f.png)

This is how the Match tab looks like:
![image](https://user-images.githubusercontent.com/48409293/189500777-4e50be7a-828a-4dce-9f00-40137042922b.png)

As you can see, ABS recognized that `Published Year`, `Series`, `ASIN`, `Publisher` were already filled out because of the `Currently` text underneath each section.
However Genres & Tags were also filled out prior to matching, but they don*t have the `Currently...` text. Same applies to Description.

### Steps to reproduce the issue

1. Fill out Genres, Tags and Description fields first.
2. Start to match
3. You will see that Genres, Tags and Description fields don't have `Currently...` text displayed. That means ABS didn't recognize that those fields were filled out.

### Audiobookshelf version

v.2.1.5

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Updated in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)
