### ISSUE TITLE
[Bug]: m4b merge output file has no audio stream when input files are also m4b

### ISSUE THREAD

**Issue by listy-bit** [advplyr/audiobookshelf#977]
### Describe the issue

Books made up of multiple m4b files don't merge correctly.

Log:
`[DownloadWorker] FFMPEG concat started with command: ffmpeg -safe 0 -f concat -i /metadata/downloads/abmerge_425ih6jxamcdkh3k1e/files.txt -i /metadata/downloads/abmerge_425ih6jxamcdkh3k1e/metadata.txt -f image2pipe -i /audiobooks/The Colour of Magic/cover.jpg -y -loglevel error -max_muxing_queue_size 1000 -c:a copy -map_metadata 1 -c:v copy -map 2:v -f mp4 /metadata/downloads/abmerge_425ih6jxamcdkh3k1e/The Colour of Magic.m4b`

The output file (600kb) contains the metadata, chapters, and cover art, but no audio data at all.

### Steps to reproduce the issue

1. Add book consisting of multiple m4b files
2. Start m4b merge

### Audiobookshelf version

2.1.5

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Please test this on the latest server version 2.2.0. I wasn't able to reproduce this, multiple m4b audiobook merged correctly.
