### ISSUE TITLE
[Bug] .ignore not working in library item subfolders

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#979]
I'm running audiobookshelf on a Synology NAS using Docker. Synology Universal search creates a folder "\@eadir" with metadata for it's search engine.

I place a file named .ignore into that directory and re-scanned the item. The files are still shown in the "Files" tab of the item.

The current directory structure looks like this:
![grafik](https://user-images.githubusercontent.com/40570297/189284967-6bdbd9df-c293-486a-a754-47036e8c5fe9.png)

Within audiobookshelf I get this:
![grafik](https://user-images.githubusercontent.com/40570297/189285125-46e7c9be-f46c-489b-9530-3a37a6e18531.png)

_Originally posted by @Hoempi in https://github.com/advplyr/audiobookshelf/issues/516#issuecomment-1241552161_

**Comment by advplyr** [comment]
Fixed in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)

**Comment by Hoempi** [comment]
Just had the update installed by Watchtower. Works like a charm, thank you very much!
