### ISSUE TITLE
[Minor Enhancement]: Relabel 'Apply' to 'Restore' in the backups list

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#981]
### Describe the feature/enhancement

Just to make it more intuitive to the user.

![image](https://user-images.githubusercontent.com/42061703/189677700-5c927e94-364a-402b-a3e5-711b3fca7d20.png)

Having the button labeled as 'Restore' adds clarity.

**Comment by advplyr** [comment]
Fixed in 2.2.0
