### ISSUE TITLE
[Enhancement]: Fetch podcast episodes information after Match

### ISSUE THREAD

**Issue by judicandus** [advplyr/audiobookshelf#983]
### Describe the feature/enhancement

When importing an already existing library, after matching the podcast information using the "Match" function it would be great if also the individual episodes information were matched. In that way the episodes from existing library will have correct name and information. 
Now what happens is that podcast information is correct but episodes have random file names. 

Thank you for amazing sleek program!

**Comment by advplyr** [comment]
Yeah this is coming. 

You can match individual episodes using the episode match tab. That would need to be one-by-one right now until this gets implemented but it is basically calling the same function I'll be using for this feature.

**Comment by advplyr** [comment]
Added in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)

There is still a lot more I want to do here. How this works now is if you quick match the podcast (and it has updates to be made) then it will loop through all the episodes and it will attempt to quick match it only if it is not already matched with a podcast episode.
