### ISSUE TITLE
[Enhancement]: Match remaining time to playback speed

### ISSUE THREAD

**Issue by swedishstyle** [advplyr/audiobookshelf#984]
### Describe the feature/enhancement

It would be nice if, when you adjusted the playback speed, the remaining time indicator would update to show how much longer in real time is left, at least as a toggle-able option

**Comment by advplyr** [comment]
Isn't this already how it works? I may not be understanding

**Comment by swedishstyle** [comment]
Wow, I'm blind - it certainly does! Sorry, closing. Thanks for all your great work :)
