### ISSUE TITLE
[Enhancement]: Disable Auth

### ISSUE THREAD

**Issue by SylverRat** [advplyr/audiobookshelf#989]
### Describe the feature/enhancement

I’d like to disable Auth, I use it behind a reverse proxy, which authenticates with Authelia or Google OAuth, and I don’t need it.
How can I turn it off?
TIA

**Comment by advplyr** [comment]
There is no way to turn it off. I think this will have to wait until #339 gets figured out.

**Comment by camaz** [comment]
Same issue here; single user, private lan, tailscale auth. Ideally I would pin to a single user with no auth, but the allowance of null passwords for users (similar to root) would be half a step in the right direction.

Thanks!

**Comment by advplyr** [comment]
That's why root user doesn't require a password. If you're the only user of the server then why wouldn't you use the root user?

**Comment by xoxfaby** [comment]
Some way to skip the auth could still be very useful I feel. Maybe by passing an api key for an account in a header or something similar? That way a request that's going through a reverse proxy that has authenticated the user could send it along to bypass the auth?
