### ISSUE TITLE
ENHANCEMENT: Add a "Files" tab to the edit menu

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#99]
Maybe it's just me, but I have found that I have to switch between the edit menu and the book details screen to get all the information I'm after while curating my libraries. When I reflected on this, I realized that the main thing I'm looking for is the file information. 

I like having the file information on the book details screen, so don't think I'm suggesting that moves. I'm hoping that same information gets ADDED to a "Files" tab. Even if it's super simple. I think it would be helpful while editing.

![image](https://user-images.githubusercontent.com/25695143/137268860-a6b686d7-7b84-43d1-8f8e-82d82be62a5f.png)

What do you think?

**Comment by advplyr** [comment]
Definitely agree with this. I chose to make it an "all files" table, let me know if that still needs improvement.
[v1.4.9](https://github.com/advplyr/audiobookshelf/releases/tag/v1.4.9)
