### ISSUE TITLE
[Enhancement]: Youtube Integration for podcasts

### ISSUE THREAD

**Issue by ClaasF** [advplyr/audiobookshelf#990]
### Describe the feature/enhancement

Maybe I've overlooked it, but there seems to be no support for Youtube channels as podcast sources (and no discussions about it, either).

If there a reason for that? If it's a purely legal thing, than that would be perfectly reasonable, of course. Otherwise, it would be a nice feature.

My JS-skills are rather surface level, but I might even be able contribute a few lines of code for that.

**Comment by advplyr** [comment]
I think it has been brought up in the discord. 

There is no consistent reliable way to download youtube videos. ytdl and other libraries are scraping the html to get the links last time I checked. Youtube doesn't provide a way to download videos.

As of now this project isn't going to include any web scraping. Unless you have another way?

**Comment by ClaasF** [comment]
Not that I know of. My naive approach would have been to simply include ytdl (or a similar lib).

**Comment by advplyr** [comment]
Okay there may be another way to implement this that doesn't involve web scraping but until then this is not planned.
