### ISSUE TITLE
[Enhancement]: Possibility to just get chapter titles without overwriting timestamps.

### ISSUE THREAD

**Issue by garlik82** [advplyr/audiobookshelf#991]
### Describe the feature/enhancement

Hi. 

When merging mp3 files with m4b-tool, we get the a chapter.txt with the correct timestamps for the chapters, (assuming every file merged corresponds to a book chapter). I would like to be able to use lookup in chapter editor to just get the chapter titles. 

Thanks.

**Comment by advplyr** [comment]
If the timestamps don't match up then how do you know the chapter titles will be correct?
I'm not sure what this would look like in the UI

**Comment by garlik82** [comment]
Would have to listen to the chapter to be sure. 
Maybe, manually matching the lookup chapters to our file chapters. I would listen to the chapter using the preview button in chapter editor and pick what chapter it corresponds in the lookup generated file. 
Sorry for my English.

**Comment by garlik82** [comment]
Uhuh. Thanks :)

**Comment by advplyr** [comment]
Added in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)

![image](https://user-images.githubusercontent.com/67830747/193477603-396893f6-9b28-4349-8531-2e7c4cf5ca7f.png)
