### ISSUE TITLE
[(Very) Minor Enhancement]: Include author name in toasts

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#992]
### Describe the feature/enhancement

It's impossible to know which author wasn't updated and which author wasn't found. It would be nice if the toasts read "No updates were made for [author name]" or "[author name] not found"...

![image](https://user-images.githubusercontent.com/42061703/190862716-95354380-9b83-482a-bc5f-3ba3ba2c95b3.png)

**Comment by raviwarrier** [comment]
Apparently, the author name shows up when I clicked the "Match all authors" button (the one on the top right)...

![image](https://user-images.githubusercontent.com/42061703/190862825-f8ea832a-13a0-4364-b9f9-fbe9c3ed5384.png)

**Comment by advplyr** [comment]
That can be updated. I would have put the author name in the match all because otherwise you wouldn't know which one was not found, but I can see it being useful when clicking on the quick match directly on the author too.

**Comment by advplyr** [comment]
Updated in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)
