### ISSUE TITLE
[Enhancement]: Ignore punctuation marks (and titles) in Author names

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#993]
### Describe the feature/enhancement

![image](https://user-images.githubusercontent.com/42061703/190862941-93a50956-9273-463a-b4bd-e7ed16bf8a97.png)

As you can see from the above image, the only difference between the two Burton G. Malkiels is the period after the 'G', making them displayed as two different authors.

While this is metadata taken from other sources and is no fault of ABS, we can at least ignore the punctuation marks and match the name. Also, it would be nice if  we could ignore titles (Dr., etc.) or suffixes (PhD, MD, etc.) at the same time.

**Comment by raviwarrier** [comment]
![image](https://user-images.githubusercontent.com/42061703/190863107-ce229cfc-e0e6-4d21-8ad7-7886883df4bd.png)

This I agree is a trickier problem and probably doesn't warrant writing hundreds of lines of code to match & merge.

**Comment by advplyr** [comment]
I think your second example and the prefixes/suffixes you mentioned would be included in #908. I think the solution is to include alternative names for authors.

I think we can have the scanner automatically handle the punctuation case

**Comment by raviwarrier** [comment]
Yes #908 is pretty much the same thing.

Thanks for considering the other use case.

**Comment by advplyr** [comment]
Updated in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)

**Comment by JakobTischler** [comment]
I'm not 100% certain this is caused by the commit linked above, but I have some punctuation stripped from the artist in ABS, even though the file tag has it included. This leads to author mismatches.

Example: I have an .m4b file with the artist (and album artist) being `C. J. Box`. The file is parsed (and displayed) as `C. J Box` (notice the missing dot after the J) though.

**Comment by JakobTischler** [comment]
Sure, but why is the folder name relevant at all? I have `Prefer audio metadata` turned on in the settings.

**Comment by advplyr** [comment]
Are you storing a `metadata.abs` file inside your library item folder? That file will override everything and maybe the author name was set in there before you enabled prefer audio metadata.

**Comment by JakobTischler** [comment]
No, no .abs files. These are freshly added audiobooks with only the .mob file.
