### ISSUE TITLE
[Bug]: Docker container vanishes

### ISSUE THREAD

**Issue by Thomas-O** [advplyr/audiobookshelf#994]
### Describe the issue

I'm using Audiobookshelf v2.1.5 (docker) in DietPi (v8.8.1) on a Pi2. The library is on a usb stick formatted to ext4.

If I shutdown or reboot the Pi then the Audiobookshelf container will vanish. On the subsequent boot the image is still there but I can no longer start the non-existent Audiobookshelf container. The only option for this bear of little brain is to re-run the install script. Again and again and again.

This issue isn't present with the only other [container](https://github.com/akhilrex/podgrab#installation) I'm running.

When looking to restart the Audiobookshelf container on reboot I saw this report: "Error response from daemon: Cannot update container 9528f1e16215bdf60e1546980ad2ff6fee50cfdebbbf74c3b4ca576846fe5fd6: Restart policy cannot be updated because AutoRemove is enabled for the container". Is this the reason it keeps going awol, and is there anything I can do about it?

Help, guidance or words of soothing comfort much appreciated.

### Steps to reproduce the issue

Shutdown or reboot.

### Audiobookshelf version

v2.1.5 (docker)

### How are you running audiobookshelf?

Docker

**Comment by hobesman** [comment]
I suspect it's the last line of the docker instructions. 

`--rm ghcr.io/advplyr/audiobookshelf`
If you remove that line, you should be able to set the restart policy.

**Comment by Thomas-O** [comment]
> I suspect it's the last line of the docker instructions.
> 
> `--rm ghcr.io/advplyr/audiobookshelf` If you remove that line, you should be able to set the restart policy.

I've removed the line but now it won't install and concludes with the protest that _"docker run" requires at least 1 argument_. Do I need to replace or amend the final line with something to get it started?

**Comment by hobesman** [comment]
Perhaps replace it with `--restart unless-stopped`

**Comment by Thomas-O** [comment]
> Perhaps replace it with `--restart unless-stopped`
> 
> Edit: actually I think it might be: `--restart unless-stopped ghcr.io/advplyr/audiobookshelf`

I tried the 2nd and it appears to have worked. Thank you for your help. Much appreciated.
