### ISSUE TITLE
Synology Reverse Proxy Doesn't Work

### ISSUE THREAD

**Issue by NAL100** [advplyr/audiobookshelf#995]
Following the instructions of @silentArtifact in https://github.com/advplyr/audiobookshelf/issues/241#issuecomment-1036732329_ didn't work - There is no way to "3. Select the proxy rule for which you want to enable Websockets and click on Edit" as he suggests. I'm using the latest Synology Disk Station Manager, 7.1. I think he must have been using an earlier version.

![image](https://user-images.githubusercontent.com/68204128/190881145-4c9e6d77-6aa3-4559-ae35-53bf4007afec.png)

In the "Source" port you can't use any port that has already been used, including the 13378 port used for the Container, or 80 for http. So I'm at a loss of which port to put here. When I tried to give a different port, I still get "Failed to ping server" in the iOS app.

I set it up in Docker for Synology nas with the following port settings in Docker: Remote port 13378, Local port 80, TCP. Network is bridge.  I was able to access the web interface (through http).

Any suggestions? I'm creating this issue because the instructions for Synology are incorrect / do not work.

**Comment by epolinom** [comment]
my settings that work, you can do by analogy
set up without instructions
sorry, the language on the screenshots is not english
![Снимок экрана 2022-09-18 123329](https://user-images.githubusercontent.com/49395995/190889111-6e31681c-4adc-4d17-b2dd-2b79b33f4a75.png)
![Снимок экрана 2022-09-18 123230](https://user-images.githubusercontent.com/49395995/190889113-6768b8e9-1040-4c9b-9749-a92f73bb7fd2.png)

**Comment by silentArtifact** [comment]
I'm currently on DSM 7.1-42661, and the instructions still work. Synology moved the reverse proxy rules to within "Login Portal", but you seem to have already found that. Still, proof below:

![Screenshot 2022-09-19 055449](https://user-images.githubusercontent.com/11065620/191003054-a64abd26-4c32-4274-845c-fcad9da7fa1b.png)
![Screenshot 2022-09-19 055515](https://user-images.githubusercontent.com/11065620/191003074-42cbbff5-9202-4ecf-9194-0de670ed5fe9.png)

If you're running into port conflicts, why not change the ports the docker container is presenting? That way the reverse proxy won't have any conflicts.

**Comment by NAL100** [comment]
@epolinom, thank you for the screenshot.

@silentArtifact,
> I'm currently on DSM 7.1-42661, and the instructions still work. Synology moved the reverse proxy rules to within "Login Portal", but you seem to have already found that. Still, proof below:
> If you're running into port conflicts, why not change the ports the docker container is presenting? That way the reverse proxy won't have any conflicts.

Right it has moved, so the instructions should state that. More importantly though, adding the header works however your instructions specify that you should "Select the proxy rule for which you want to enable Websockets" and there is no proxy listed by default. So you have to add a new proxy rule, and there are no instructions for what to put in those fields. There's no "in source put HTTPS/443, and in destination put HTTP/13378" and in hostname put your, what, DDNS? I don't even know what hostname to put in that field. The point is it isn't clear.

For the ports, there isn't an issue so long as you put 443 there, but that wasn't specified. I'm currently dealing with external connectivity issues separate from this, so can't test it, but I would like it if the instructions were updated to state this new information.

I will close this issue after this but first can someone comment on what should be in the hostname field, though? Is that the auto-generated DDNS by synology, like the one used for file transfers, or is that your external IP or what?

**Comment by advplyr** [comment]
I've never used Synology but reading over this it looks like your hostname should be your domain name.

Most people use a subdomain for each of their services. i.e. you own `somedomain.com` so you setup a subdomain `audiobookshelf.somedomain.com` and that is what you would put in the hostname.

We can definitely use help with documentation if you are up for it.
