### ISSUE TITLE
[Bug]: Trailing spaces on series name causes odd behaviour

### ISSUE THREAD

**Issue by jamerst** [advplyr/audiobookshelf#997]
### Describe the issue

I was experiencing some odd issues with some of the series in my audiobook library that appear to have been caused by trailing spaces in the series name.

I have 3 series, each with 3 volumes of 1 .m4b file each. Each series has the same name set in the `series` ID3 tag, but they appear as separate series in audiobookshelf, one for each volume, even though they are named identically:
![image](https://user-images.githubusercontent.com/10601770/191046556-14ae507d-4f0e-4329-9e0e-35af9ad1629c.png)

Attempting to edit the series for one of these audiobooks results in a TypeError which prevents interacting with the page:
```
TypeError: a is undefined
    NuxtJS 56
6a08a5a.js:2:12698
```

There were only 3 series in my library with this issue, and after some investigation I realised that they were the only ones that had a trailing space in the series name. Removing the space resolved all the issues I was having.

### Steps to reproduce the issue

1. Modify the `series` ID3 tag of audiobooks to include a trailing space
2. Force rescan library
3. Go to series view to find duplicates
4. Try editing the series of one of the books in the duplicate series 

### Audiobookshelf version

v2.1.5

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)

All meta tags probed from audio files will have whitespace trimmed. This should fix it for new scans.
