### ISSUE TITLE
[Bug]: Book file names not ordered lexicographically

### ISSUE THREAD

**Issue by TaakoMagnusen** [advplyr/audiobookshelf#999]
### Describe the issue

When a list of books is in lexicographic order in the underlying directory structure, they are not always ordered the same way in audiobookshelf

### Steps to reproduce the issue

1. Get audiobook comprised of many files
2. name them in the following order
        BOOKNAME_01_01_01.mp3
        BOOKNAME_01_01_02.mp3
        BOOKNAME_01_02_01.mp3
        BOOKNAME_01_02_02.mp3
4. Import book into audiobookshelf
5. The order of the files is imported in the following way
        BOOKNAME_01_01_01.mp3
        BOOKNAME_01_02_01.mp3
        BOOKNAME_01_01_02.mp3
        BOOKNAME_01_02_02.mp3

### Audiobookshelf version

v2.1.5

### How are you running audiobookshelf?

Docker

**Comment by TaakoMagnusen** [comment]
Attaching image of this phenomena for stormlight series book 1
<img width="886" alt="Screen Shot 2022-09-21 at 3 47 08 PM" src="https://user-images.githubusercontent.com/39819109/191624250-b190e8d4-d26f-46fd-ae92-1539a574dd04.png">

**Comment by advplyr** [comment]
Press Manage Tracks and see how the filename is being parsed. The track number and disc number attempt to get parsed and that determines the order of the tracks

**Comment by TaakoMagnusen** [comment]
awesome! I just went to Manage Tracks, clicked the Filename header to sort by ascending, and saved the tracklist; that was so easy!

Incredible UI, great app, very excited about this amazing new self-hosted tool!

**Comment by TaakoMagnusen** [comment]
the manage tracks didn't really tell me much about how the track number and disc number were parsed from the file name, i think the file metadata must be screwy, but that's on my/the files.
